### ISSUE TITLE
Fails to compile UWP with AppInstaller option enabled

### ISSUE THREAD

**Issue by Guerra24** [actions/virtual-environments#3507] opened 2021-06-02 03:08 UTC
**Description**  
After environment update msbuild fails to compile UWP with AppInstaller option enabled. I'm unable to replicate the issue locally with VS Community 16.10.

**Area for Triage**:  
.NET Core

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Image version**
20210525.0

**Expected behavior**  
Should compile successfully.

**Actual behavior**  
Errors out with `error APPX0002: Task 'GenerateAppInstallerFile' failed. Input string was not in a correct format.`
```
(GenerateAppInstallerFileForPackage target) -> 
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(6361,5): error APPX0002: Task 'GenerateAppInstallerFile' failed. Input string was not in a correct format. [D:\a\broken-msbuild\broken-msbuild\broken-msbuild.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(6361,5): error APPX0002:  [D:\a\broken-msbuild\broken-msbuild\broken-msbuild.csproj]
   C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(6361,5): error MSB4018: The "GenerateAppInstallerFile" task failed unexpectedly. [D:\a\broken-msbuild\broken-msbuild\broken-msbuild.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(6361,5): error MSB4018: System.FormatException: Input string was not in a correct format. [D:\a\broken-msbuild\broken-msbuild\broken-msbuild.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(6361,5): error MSB4018:    at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args) [D:\a\broken-msbuild\broken-msbuild\broken-msbuild.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(6361,5): error MSB4018:    at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args) [D:\a\broken-msbuild\broken-msbuild\broken-msbuild.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(6361,5): error MSB4018:    at System.String.Format(String format, Object[] args) [D:\a\broken-msbuild\broken-msbuild\broken-msbuild.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(6361,5): error MSB4018:    at Microsoft.Build.AppxPackage.AppxPackagingTaskHelper.LogError(String context, String fileName, Int32 lineNumber, Int32 columnNumber, String message, Tuple`2 callerInfo, Object[] messageArgs) [D:\a\broken-msbuild\broken-msbuild\broken-msbuild.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(6361,5): error MSB4018:    at Microsoft.Build.AppxPackage.GenerateAppInstallerFile.ExecuteImplementation() [D:\a\broken-msbuild\broken-msbuild\broken-msbuild.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(6361,5): error MSB4018:    at Microsoft.Build.AppxPackage.AppxPackagingTaskHelper.Execute(String file) [D:\a\broken-msbuild\broken-msbuild\broken-msbuild.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(6361,5): error MSB4018: --- End of stack trace from previous location where exception was thrown --- [D:\a\broken-msbuild\broken-msbuild\broken-msbuild.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(6361,5): error MSB4018:    at Microsoft.Build.AppxPackage.AppxPackagingTaskHelper.Execute(String file) [D:\a\broken-msbuild\broken-msbuild\broken-msbuild.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(6361,5): error MSB4018:    at Microsoft.Build.AppxPackage.AppxPackagingTaskBase.Execute() [D:\a\broken-msbuild\broken-msbuild\broken-msbuild.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(6361,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [D:\a\broken-msbuild\broken-msbuild\broken-msbuild.csproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(6361,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() [D:\a\broken-msbuild\broken-msbuild\broken-msbuild.csproj]
```

**Repro steps**  

I've put an example here: https://github.com/Guerra24/broken-msbuild.
Failing action: https://github.com/Guerra24/broken-msbuild/runs/2724258752?check_suite_focus=true

**Comment by miketimofeev** [comment] 2021-06-02 06:41
Hi @Guerra24!
Thanks for the provided example, we will take a look.

**Comment by dmitry-shibanov** [comment] 2021-06-08 13:00
Hello @Guerra24  ! Thank you for the repro steps. We were also able to reproduce your issue on a local machine with Visual Studio 16.10.0. Could you please clarify if you have any optional UWP packages pre-installed on your machine? Thanks!

**Comment by dmitry-shibanov** [comment] 2021-06-10 16:47
Hello @Guerra24 . We could reproduce your issue on both the hosted Windows-2019 and our local machine. It's look like that this is expected behavior for Visual Studio 16.10. Probably, you haven't faced this issue locally due to some preinstalled packages or precached dependencies. Please find details about pre-installed Visual Studio extensions in the [Windows2019-Readme.md](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#visual-studio-enterprise-2019). As for our local machine, it includes the default configuration for UWP:![image](https://user-images.githubusercontent.com/28229110/121557347-5b539a00-ca1d-11eb-8147-175761d44114.png)
I'm going to close this issue, please let us know if you have any concerns.

**Closed by dmitry-shibanov** 2021-06-10 16:47 UTC
Labels: Area: .NET Core, OS: Windows, investigate

**Comment by Guerra24** [comment] 2021-06-10 17:28
I see, thanks for your time looking into this. I did a bit of research and found this https://developercommunity.visualstudio.com/t/microsoftappxpackagetargets63615-error-appx0002-ta/1437188 (I didn't found it during my initial research) so it a appears to be a bug in Visual Studio 16.10, I will keep an eye on that feedback.
