### ISSUE TITLE
pkg installer sometimes hangs on macOS

### ISSUE THREAD

**Issue by gaborcsardi** [actions/virtual-environments#4836] opened 2022-01-05 16:59 UTC
### Description

I have a couple of JS actions that download and install `.pkg` installers on macOS. Very rarely one of the installers hang. Here is an example, the output of the installer log, here I cancelled the installer after 30 minutes (the install only takes a couple of seconds).

```
2022-01-05T12:44:08.1412420Z [command]/usr/bin/sudo installer -allowUntrusted -dumplog -package /Volumes/gfortran-8.2-Mojave/gfortran-8.2-Mojave/gfortran.pkg -target /
2022-01-05T12:44:08.2767460Z Jan  5 12:44:08  installer[1197] <Debug>: fileURLForURL = x-disc://gfortran-8.2-Mojave/gfortran-8.2-Mojave/gfortran.pkg
2022-01-05T12:44:08.2871220Z Jan  5 12:44:08  installer[1197] <Debug>: fileURLForURL = file://localhost/Volumes/gfortran-8.2-Mojave/gfortran-8.2-Mojave/gfortran.pkg
2022-01-05T12:44:08.9498810Z Jan  5 12:44:08  installer[1197] <Debug>: Referenced component packages (1) trustLevel=350
2022-01-05T12:44:08.9602120Z Jan  5 12:44:08  installer[1197] <Debug>: -[IFPKGDerivedDocument sortedPackageLocations]: result = (
2022-01-05T12:44:08.9705050Z 	    "file://localhost"
2022-01-05T12:44:08.9812120Z 	)
2022-01-05T12:44:08.9918330Z Jan  5 12:44:08  installer[1197] <Debug>: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: location = file://localhost
2022-01-05T12:44:09.0025590Z Jan  5 12:44:08  installer[1197] <Debug>: -[IFDInstallController(Private) _buildInstallPlanReturningError:]: file://localhost/Volumes/gfortran-8.2-Mojave/gfortran-8.2-Mojave/gfortran.pkg
2022-01-05T12:44:09.0128490Z Jan  5 12:44:08  installer[1197] <Debug>: Set authorization level to root for session
2022-01-05T12:44:09.0129580Z Jan  5 12:44:08  installer[1197] <Info>: Administrator authorization granted.
2022-01-05T13:13:53.9292480Z ##[error]The operation was canceled.
```

I cannot reproduce this locally, even on a clean macOS install. Some admittedly vague ideas:
* we have had this issue for a while, but I don't know if it was present on the 10.15 images.
* possibly the installer brings up a dialog box. 
* it seems that concurrency makes the issue more severe. We used to have several `installer` calls in parallel, and then the hangs were _maybe_ more common.
* The first call to `installer` never seems to fail. 
* There are a bit more details and links to failed jobs in this issue: https://github.com/r-lib/actions/issues/435

If anybody has ideas or even just guesses why `installer` might hang, I would be grateful to hear them.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20211219.1

https://github.com/r-lib/actions/runs/4714679983?check_suite_focus=true
https://github.com/r-lib/actions/runs/4714679819?check_suite_focus=truehttps://github.com/rstudio/learnr/runs/4695923834?check_suite_focus=true

### Is it regression?

no

### Expected behavior

Clean finish from the installer.

### Actual behavior

`installer` hangs and the job is killed after the 6 hours of time limit.

### Repro steps

See the `R-CMD-check` workflow at https://github.com/r-lib/actions/

Unfortunately most of the time the installer works, and only very rarely hangs.

**Comment by al-cheb** [comment] 2022-01-10 06:25
Hey, @gaborcsardi 
We will take a look at it.

**Comment by dsame** [comment] 2022-01-11 10:43
Most probably the parallel installers mutually lock some resource 

I advise to call `installer` under `dtruss` control and get some ideas from the log.

Pay attention it is not possible to use dtruss against /usr/bin due to SIP and you should use unsigned copy of `installer`

```
    - name: prepare installer to run under dtruss
      run: |
        cp /usr/sbin/installer /tmp
        sudo codesign --remove-signature /tmp/installer
```

The sample build https://github.com/dsame/actions-demo/runs/4773647262?check_suite_focus=true

I doubt there are popup windows which are sporadic, but just in case this can be detected by getting snapshots `screencapture  pic.png` and uploading them as artifacts, but i'd use this only if dtruss does not help

**Comment by dsame** [comment] 2022-01-18 08:04
@gaborcsardi have you succeeded to get the logs from dtruss?

**Comment by dsame** [comment] 2022-01-26 08:15
I am closing the issue because there's no reply more than 7 days since the last contact

@gaborcsardi feel free to reopen the issue in case the problem is not resolved

**Comment by gaborcsardi** [comment] 2022-01-26 08:25
I am sorry for the slow reply. It is a sporadic issue, and I don't have the logs yet. Feel free to close, and I'll reopen with the logs if it happens again.

**Closed** 2022-01-26 08:59 UTC
Labels: Area: Packages, OS: macOS, investigate
