### ISSUE TITLE
Cannot create Android 28 emulator in macOS hosted agent 10.15

### ISSUE THREAD

**Issue by DSK1990-sam** [actions/virtual-environments#1241] opened 2020-07-15 12:46 UTC
**Describe the bug**
A clear and concise description of what the bug is, and why you consider it to be a bug.
I encounter the following problem.
./sdkmanager --install "system-images;android-28;google_apis;x86"
Warning: Failed to find package system-images;android-28;google_apis;x86

**Area for Triage**: 

**Question, Bug, or Feature?**: 

"Bug"

**Virtual environments affected**
- [yes ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
A description of what you expected to happen.
Expected to get normal x86 sdk image as for android 27 and android 29

**Actual behavior**
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.
Tried running with system-images;android-28;google_ndk;x86 works. I am using azure hosted agent.
The issue with the ndk image is the app UI crashes. It crash when trying to switch context to native and capture the alert message with selenium.
App goes into error UI not responding.
Testcases with alert Works fine with android 27 and 29 google_apis images. So seems like issue is with ndk image.

Also tried with x86_64 googe_apis image. But Start emulator always fails for this image in the hosted agent.

Any help is appreciated

@miketimofeev

**Comment by maxim-lobanov** [comment] 2020-07-15 12:53
Hello, 
Does "Start emulator" works for you locally with `system-images;android-28;google_ndk;x86` image?
Could you please share public repository with minimal repro steps for this issue?

**Comment by DSK1990-sam** [comment] 2020-07-15 13:02
Locally i am using windows. So i have the system-images;android-28;google_apis;x86 image and everything works perfect.. Currently I dont have a public repo for this as it's related with a customer, I could provide details anything required.

**Comment by maxim-lobanov** [comment] 2020-07-15 13:24
Could you please try to install `system-images;android-28;google_ndk;x86` on your local machine and confirm that emulator with this image works locally for you?
Unfortunately, we don't have much experience with Android but probably, `system-images;android-28;google_apis;x86` and `system-images;android-28;google_ndk;x86` images could have different set of installed tools and it could be an issue. So it could be useful to double check if the ndk image works locally

**Comment by DSK1990-sam** [comment] 2020-07-15 17:07
In my windows machine i have done it with android studio and it doesn't have the ndk image.
Can I install it from command line?. what's the windows command for the same

**Comment by maxim-lobanov** [comment] 2020-07-16 06:29
@DSK1990-sam , I believe this image can be downloaded via Android Studio.
It is named: `Google X86_ARM Intel x86 Atom System Image`
![image](https://user-images.githubusercontent.com/16715858/87634243-91bd6200-c745-11ea-93d7-84fa9d0254f6.png)

As one more possible solution, you can try image: `system-images;android-28;google_apis;x86_64`

Also I don't think that the issue is related to the image itself. Looks like project was configured for the specific android system-image that was removed recently and project has to be re-configured.

**Comment by DSK1990-sam** [comment] 2020-07-16 06:35
Ok i will try ndk in local and update you.
I have tried this system-images;android-28;google_apis;x86_64 but the  issue is 
nohup $ANDROID_HOME/emulator/emulator -avd $(DeviceName) -skin $(skin) -dns-server 8.8.8.8 -writable-system -netdelay none -netspeed full > /dev/null 2>&1 &
$ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done; input keyevent 82'

wait-for-device shell does not complete and the start emulator will fail always

**Comment by DSK1990-sam** [comment] 2020-07-16 06:45
As you said trying to install ndk image 
![image](https://user-images.githubusercontent.com/59908010/87636171-eb318b00-c75d-11ea-9225-ecf9b4d03803.png)

But that also is downloaded from google_apis as shown. Is it what expected?

**Comment by DSK1990-sam** [comment] 2020-07-16 09:41
I tried with android 28 ndk image in local windows machine but app doesn't even login successfully. Login fails.
But runs perfect on  android 28 google_api image

**Comment by maxim-lobanov** [comment] 2020-07-16 10:09
I believe `system-images;android-28;google_ndk;x86` is something different and can't be used as a replacement of `system-images;android-28;google_apis;x86`.

Unfortunately, we are not Android experts so we don't have context why `system-images;android-28;google_apis;x86` was removed from sdkmanager and can't be downloaded anymore. I suggest to ask on Android related community forum. May be they know more.

**Comment by DSK1990-sam** [comment] 2020-07-17 06:03
Is there any way I can get the deprecated image for system-images;android-28;google_apis;x86 ?

**Comment by maxim-lobanov** [comment] 2020-07-17 07:40
Looks like, it can be downloaded from https://androidsdkmanager.azurewebsites.net/GoogleAPIaddonSystemImages (not sure that it is official resource)
Also, you will have to implement code to download and unpack it to the machine in runtime.

I am going to close this issue since it is not the image defect. Feel free to ping if you have any questions

**Closed by maxim-lobanov** 2020-07-17 07:40 UTC
Labels: Area: Android, OS: macOS, investigate
