### ISSUE TITLE
Is there an easy way to let Azure Resource Manager Templates build a docker image?

### ISSUE THREAD

**Issue by daniela-waranie** [actions/virtual-environments#196] opened 2019-12-20 13:11 UTC
I do not know the azure ecosystem. Is there an option in azure to build a docker image based on this file: https://github.com/actions/virtual-environments/blob/master/images/linux/ubuntu1804.json

I could try to execute or convert all shell commands to a Dockerfile but i would prefer an automated approach, to easily catch-up this this repo, if it changes. Is azure able to output docker images from this template? Is there a converter to Dockerfile available? Other ideas?

PS: I want to run some stuff in a local build environment, before pushing it to github (to let github build my official release).

**Comment by alepauly** [comment] 2019-12-20 22:47
Hi @daniela-waranie, it might be possible but I'm not sure how straightforward it would be. I think @StanleyGoldman tried it once and went through some pain (please correct me if I'm wrong), maybe he can share his experience.

**Comment by christian-weiss** [comment] 2019-12-21 20:34
I am also interessted in a docker image.

**Comment by christian-weiss** [comment] 2020-02-20 08:59
@StanleyGoldman, please share your experience with us.

**Comment by jpb** [comment] 2020-03-12 16:25
I was able to modify the packer definition to build a [docker image](https://hub.docker.com/r/unbounce/actions-virtual-environment) for my use cases. I ended up removing a lot of packages that I did not need to reduce the image size, the build time, and to avoid issues caused by differences between the Azure and Docker base images. The excluded packages may have issues when building in docker that I did not encounter. This could be the starting point for more generalized docker support: https://github.com/actions/virtual-environments/compare/master...jpb:docker.

**Comment by alepauly** [comment] 2020-03-18 14:34
@daniela-waranie I'll close this since there's no supported way to do this right now. I think it's fine to keep the discussion going here as a closed issue or we can move it to the community forums: https://github.community/t5/GitHub-Actions/bd-p/actions.

**Closed by alepauly** 2020-03-18 14:34 UTC
Labels: no-issue-activity, question

**Comment by daniela-waranie** [comment] 2020-04-04 07:57
This ticket started out as a support request, but more and more thinking about it i would now like to treat it as a feature request:  "build azure base images and docker images with the same provisioning tool"  / "add docker image as a supported option to run github actions locally"

**Comment by daniela-waranie** [comment] 2020-04-04 07:58
would be cool it you can reopen this ticket

**Comment by alepauly** [comment] 2020-04-28 14:24
Hi, @daniela-waranie. At this time this is not a feature we plan to support.
