### ISSUE TITLE
Packer images creating VHD is being deprecated - need to support creating as managed images

### ISSUE THREAD

**Issue by Marcus-James-Adams** [actions/virtual-environments#3147] opened 2021-04-10 20:32 UTC
When running the scripts we get
azure-arm: Warning: You are using Azure Packer Builder to create VHDs which is being deprecated, consider using Managed Images. Learn more https://www.packer.io/docs/builders/azure/arm#azure-arm-builder-specific-options

**Comment by catthehacker** [comment] 2021-04-10 20:34
Duplicate of #1037 and #2224

**Comment by maxim-lobanov** [comment] 2021-04-12 09:23
We don't have plans to switch to manage disks in near future because it will require additional changes on infra side. Also VHDs won't be deprecated in near future, see details in https://github.com/actions/virtual-environments/issues/1037#issuecomment-674850320
We should just ignore this warning for now

**Closed by maxim-lobanov** 2021-04-12 09:23 UTC
Labels: Area: Image administration, needs eyes, question
