### ISSUE TITLE
PHP gone from Ubuntu 18.04 image?

### ISSUE THREAD

**Issue by jrushlow** [actions/virtual-environments#981] opened 2020-06-02 14:33 UTC
PHP pipelines on 2 separate repo's failed today during a cron run. Several errors are triggered but the most apparent is one generated by `composer` that reads in part:
```
... the requested PHP extension xml is missing from your system.
```
Looking through https://github.com/actions/virtual-environments/commit/8c049cd8222a0e55c44b3f2f3a585a06a71df0ed specifically line 200 - PHP references were removed. PHP is obviously still available on the images otherwise composer wouldn't be functional. But I don't think the default PHP extensions are being built correctly in version `20200531.1`. Yesterdays CI run built on version `20200525.2` didn't experience any problems..

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Comment by vmapetr** [comment] 2020-06-02 15:04
Hi @jrushlow!
We aware of this issue, and currently reverting Ubuntu images to fix this. We will keep you posted.

**Comment by leerlemoniii** [comment] 2020-06-02 15:21
As a note for anyone trying to work around this while the problem is repaired... I was able to add an install to my github deploy.yml  
this forced the install of PHP and php-curl (which we required for our deployment).
Not a code fix, but though it may help someone trying to work past the code issue.
run: |
        sudo apt-get install php-curl

**Comment by Abncoffee** [comment] 2020-06-02 18:03
Same issue here
Tried with all available ubuntu versions (18.04, 16.04 and even 20.04)

The pipeline YML has PHP 7.2 explicitly set, but when pipeline runs it fails to get 7.2 and apparently enforces 7.4

```
update-alternatives: error: alternative /usr/bin/phar7.2 for phar not registered; not setting
update-alternatives: error: alternative /usr/bin/phpdbg7.2 for phpdbg not registered; not setting
update-alternatives: error: no alternatives for php-cgi
update-alternatives: error: alternative /usr/bin/phar.phar7.2 for phar.phar not registered; not setting
PHP 7.4.6 (cli) (built: May 14 2020 10:02:44) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.6, Copyright (c), by Zend Technologies
    with Xdebug v2.9.5, Copyright (c) 2002-2020, by Derick Rethans

```

**Comment by miketimofeev** [comment] 2020-06-02 18:24
@jrushlow @Abncoffee we've finished the rollback a few minutes ago, could you check one more time, please?

**Comment by Abncoffee** [comment] 2020-06-02 19:47
> @jrushlow @Abncoffee we've finished the rollback a few minutes ago(except Ubuntu20, because it was the very first image), could you check one more time, please?

Now it's working again!

```
update-alternatives: using /usr/bin/phar7.2 to provide /usr/bin/phar (phar) in manual mode
update-alternatives: using /usr/bin/phpdbg7.2 to provide /usr/bin/phpdbg (phpdbg) in manual mode
update-alternatives: using /usr/bin/php-cgi7.2 to provide /usr/bin/php-cgi (php-cgi) in manual mode
update-alternatives: using /usr/bin/phar.phar7.2 to provide /usr/bin/phar.phar (phar.phar) in manual mode
PHP 7.2.31-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: May 14 2020 08:27:35) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.31-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.9.5, Copyright (c) 2002-2020, by Derick Rethans

Finishing: Use PHP version 7.2

```

Thank you very much, guys!

**Comment by jrushlow** [comment] 2020-06-03 14:41
@miketimofeev sorry for the delay, I'm showing v `20200525.2` on the cron job runs for last night w/ green checks. Things are happy happy happy again on my end.

**Comment by miketimofeev** [comment] 2020-06-03 14:53
@jrushlow I'm going to close the issue, feel free to contact us if you have any concerns.
Thank you!

**Closed by miketimofeev** 2020-06-03 14:53 UTC
Labels: Area: PHP, OS: Ubuntu, bug, in development

**Comment by leerlemoniii** [comment] 2020-06-03 14:55
can confirm this is now working correctly.  Thanks go out to all the devs that worked on this !

**Comment by jrushlow** [comment] 2020-06-03 14:59
@leerlemoniii based on the repo's that I'm managing - the Ubuntu 18.04 images are as they were 3 days ago (v`20200525.2`) and running without issue
