### ISSUE TITLE
Ruby/ImageMagick issue: checks hang with no output

### ISSUE THREAD

**Issue by gimenete** [actions/virtual-environments#434] opened 2020-02-20 12:17 UTC
**Describe the bug**

From this community question: https://github.community/t5/GitHub-Actions/Checks-hang-with-no-output/td-p/46658

There seems to be an intermittent issue that below 2 combinations will hang at commend 'bundle exec rake' sometimes: "ruby 2.6 + IM6.7/6.8".

However it passed consistently on CircleCI and local server.

**Area for Triage**: 

**Question, Bug, or Feature?**: 

Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**

Checks should pass or fail, but not hang.

**Actual behavior**

Checks hang with no output.

cc @weide-zhou

**Comment by maxim-lobanov** [comment] 2020-04-02 09:28
Hello @gimenete , Could you please double check if the issue is still actual?

**Comment by AlenaSviridenko** [comment] 2020-04-14 07:55
Hi @weide-zhou! Few images were rolled out since your original issue, could you please check if the issue still appears for you?

**Comment by AlenaSviridenko** [comment] 2020-04-24 09:20
Closing this issue since we didn't get any confirmation the issue is still actual. 
If it continue happening, please, feel free to file a new issue.

Thanks!

**Closed by AlenaSviridenko** 2020-04-24 09:20 UTC
Labels: OS: Ubuntu, OS: Windows, investigate
