### ISSUE TITLE
Cannot find an installed Xcode satisfying '12.1'

### ISSUE THREAD

**Issue by danieleforlani** [actions/virtual-environments#1989] opened 2020-11-05 12:01 UTC
**Description**  
From this morning, we cannot build using the version 12.1 of xCode, the current stable last version from Apple. From the Gihub actions we are setting the version to 12.1 accordingly to the available versions here: https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#xcode

**Area for Triage**:  

[Apple]

**Question, Bug, or Feature?**:  

[BUG]

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
The Xcode version is found and we can run unit tests and build the app

**Actual behavior**  
![Screenshot 2020-11-05 at 12 55 29](https://user-images.githubusercontent.com/2291670/98238625-f441a480-1f66-11eb-9a04-a435d7913431.png)

**Repro steps**  
try to build/run tests an iOS app with Xcode 12.1

**Comment by maxim-lobanov** [comment] 2020-11-05 12:03
Duplicate of https://github.com/actions/virtual-environments/issues/1984.
Documentation will be updated when the deployment is finished

**Comment by andy-mishechkin** [comment] 2020-11-05 13:35
I think we can close this ticket.
If you'll not find the documentation updated - please feel free to reopen

**Comment by maxim-lobanov** [comment] 2020-11-05 13:36
@danieleforlani , JFYI: we are rolling back the current image: https://github.com/actions/virtual-environments/issues/1984#issuecomment-722363035

**Closed by andy-mishechkin** 2020-11-05 13:35 UTC
Labels: Area: Apple, needs triage
