### ISSUE TITLE
Projects with Sdk="MSBuild.Sdk.Extras" are failing

### ISSUE THREAD

**Issue by qwertylolman** [actions/virtual-environments#5766] opened 2022-06-17 15:57 UTC
### Description

Xamarin solution with multitarget project configured via Sdk="MSBuild.Sdk.Extras" are failing on restore Nuget step with errors:

error : Unable to resolve 'MSBuild.Sdk.Extras (= 3.0.44)' for '.NETStandard,Version=v0.0'.
error : /Users/runner/work/_temp/dotnet/sdk/5.0.408/Sdks/MSBuild.Sdk.Extras/Sdk not found. Check that a recent enough .NET SDK is installed and/or increase the version specified in global.json.
error MSB4236: The SDK 'MSBuild.Sdk.Extras' specified could not be found.

Changing of the sdk versions didn't help

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20220614.2

### Is it regression?

20220605.1

### Expected behavior

Build didn't fails

### Actual behavior

Build fails

### Repro steps

1. Create Xamarin solution with multitarget project that uses MSBuild.Sdk.Extras (any version) and global.json
2. Try to restore nugets in pipeline via NuGetCommand@2 task with 'restore' command

**Comment by qwertylolman** [comment] 2022-06-17 15:59
this issue is critical, as it fail the builds for our internal framework and few applications. one of this application planned to go live in next few days

**Comment by qwertylolman** [comment] 2022-06-17 17:36
seems to be working on macos-10.15 agent
so i'm pretty sure it's an msbuild 16.10.1.31401
still we cannot downgrade, because of Xamarin.Ios

**Comment by mikhailkoliada** [comment] 2022-06-20 11:01
@qwertylolman Hi!

Could you please provide us a minimalistic pipeline and an msbuild spec to reproduce the issue?

**Comment by akoeplinger** [comment] 2022-06-20 16:13
This looks like the same underlying issue as https://github.com/actions/virtual-environments/issues/5768 i.e. the nuget.config being wrong/empty.

**Comment by qwertylolman** [comment] 2022-06-20 17:41
> @qwertylolman Hi!
> 
> Could you please provide us a minimalistic pipeline and an msbuild spec to reproduce the issue?

not sure i can provide you the pipeline. the failed step looks like this:
`  - task: NuGetCommand@2
    displayName: "Restoring project's NuGets"
    inputs:
      command: 'restore'
      restoreSolution: ${{ parameters.solutionPath }}
      feedsToUse: 'select'
      vstsFeed: ${{ parameters.vstsFeed }}      `

where parameters.vstsFeed is out internal feed deployed in Azure. It also has copies of required packages from nuget.org, and to exclude issue with nuget tool i tried to add "includeNuGetOrg: true"
before NugetCommand@2 we have some extra steps, but i'm sure they shouldn't affect the pipeline:

` - custom sh script to get installed Xamarin versions for diagnostic which basically do the ls command
- task: UseDotNet@2
        inputs:
          packageType: 'sdk'
          version: '$(XamarinDotNetVersion)'
          installationPath: '$(Agent.TempDirectory)/dotnet'

      - script: |
          /bin/bash -c "sudo $(Agent.HomeDirectory)/scripts/select-xamarin-sdk-v2.sh --mono=$(MonoSdkVersion) --ios=$(XamarinIosSdkVersion) --android=$(XamarinAndroidSdkVersion)"`

**Comment by akoeplinger** [comment] 2022-06-21 10:15
@qwertylolman can you add a step to your pipeline that prints the contents of `~/.config/NuGet/NuGet.Config` ?

If that file has an empty `<packageSources>` element then it is the same issue as #5768

**Comment by qwertylolman** [comment] 2022-06-21 11:26
> @qwertylolman can you add a step to your pipeline that prints the contents of `~/.config/NuGet/NuGet.Config`, i.e. before you run any of your actual build steps ?
> 
> If that file has an empty `<packageSources>` element then it is the same issue as #5768

ok, assuming you are right. how would you explain this? the same solution, one with multitarget projects, other has platform specific projects instead of multitarget
<img width="1131" alt="Screenshot 2022-06-21 at 14 20 39" src="https://user-images.githubusercontent.com/539593/174788546-3a30c8e4-f9f5-4fbb-a011-b9d54bbdda50.png">
<img width="1102" alt="Screenshot 2022-06-21 at 14 24 17" src="https://user-images.githubusercontent.com/539593/174788582-f2cd63de-5b12-404b-b839-65535d6e7ce5.png">

**Comment by qwertylolman** [comment] 2022-06-21 11:29
> @qwertylolman can you add a step to your pipeline that prints the contents of `~/.config/NuGet/NuGet.Config`, i.e. before you run any of your actual build steps ?
> 
> If that file has an empty `<packageSources>` element then it is the same issue as #5768

also here is the ouput from failed nuget restore task
`/Library/Frameworks/Mono.framework/Versions/Current/Commands/mono /Users/runner/hostedtoolcache/NuGet/6.2.1/x64/nuget.exe sources Add -NonInteractive -Name FooBarFeed -Source https://foobar.dev.azure.com/foobar/_packaging/foobar/nuget/v3/index.json -ConfigFile /Users/runner/work/1/Nuget/tempNuGet_2204124.config
Package source with Name: FooBarFeed added successfully.
/Library/Frameworks/Mono.framework/Versions/Current/Commands/mono /Users/runner/hostedtoolcache/NuGet/6.2.1/x64/nuget.exe sources Add -NonInteractive -Name NuGetOrg -Source https://api.nuget.org/v3/index.json -ConfigFile /Users/runner/work/1/Nuget/tempNuGet_2204124.config
Package source with Name: NuGetOrg added successfully.
/Library/Frameworks/Mono.framework/Versions/Current/Commands/mono /Users/runner/hostedtoolcache/NuGet/6.2.1/x64/nuget.exe restore /Users/runner/work/1/s/src/FooBar.sln -Verbosity Detailed -NonInteractive -ConfigFile /Users/runner/work/1/Nuget/tempNuGet_2204124.config
`

**Comment by qwertylolman** [comment] 2022-06-21 18:14
ok, we added nuget.config to our solution and magic happened. it's building for now. but i still don't get why it's working without multitarget projects and empty `~/.config/NuGet/NuGet.Config`

**Comment by akoeplinger** [comment] 2022-06-22 19:10
Hmm not sure why it works in one case and not the other, but the root cause for your issue is still the malformed nugget.config

**Comment by miketimofeev** [comment] 2022-06-23 09:19
@SVetrichelvan @qwertylolman another possible option is to remove the broken nuget config from the user's home directory before restoring the packages `rm -rf ~/.config/NuGet/NuGet.Config`
Sorry for the inconvenience, the new image with the fix will be deployed in a few days.

**Comment by mikhailkoliada** [comment] 2022-06-24 11:35
The fix has been deployed.

**Closed by mikhailkoliada** 2022-06-24 11:35 UTC
Labels: awaiting-deployment, Area: Common Tools, investigate, bug report

**Comment by qwertylolman** [comment] 2022-07-01 11:31
Confirmed, fixed. Thank you!
Btw, we found another workaround - add nuget.config with nuget.org and our azre feed to solution
