### ISSUE TITLE
Add hardware virtualization in github-hosted runner(ubuntu)

### ISSUE THREAD

**Issue by koteswara-kelam** [actions/virtual-environments#114] opened 2019-11-27 09:47 UTC
**Tool information**
- Tool name: qemu-kvm libvirt-bin ubuntu-vm-builder bridge-utils
- Add or update? add
- Desired version: 
- Approximate size: 
- If this is an add request:
  - Brief description of tool: To enable hardware virtualization, we need to install qemu-kvm libvirt-bin ubuntu-vm-builder bridge-utils
  - URL for tool's homepage: 

**Virtual environments affected**
- [ ] macOS 10.15
- [*] Ubuntu 16.04 LTS
- [*] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
sudo apt-get install qemu-kvm libvirt-bin ubuntu-vm-builder bridge-utils
sudo systemctl enable libvirt-bin

**Are you willing to submit a PR?**
yes

**Comment by eleni-salamani** [comment] 2019-11-28 15:56
Would the software installation suffice though, to have nested virtualization working on the ubuntu runners? To the best of my knowledge, KVM is not enabled on those machines, I think that would be the first thing to address.

**Comment by felipecassiors** [comment] 2019-12-19 12:47
Issue #183 is required for completing this one.

**Comment by oxr463** [comment] 2020-03-25 15:13
Please keep this open.

**Comment by Andrei-Pozolotin** [comment] 2020-04-02 16:15
+1

**Comment by felipecassiors** [comment] 2020-04-02 16:21
Isn't this a duplicate of https://github.com/actions/virtual-environments/issues/183?

**Comment by oxr463** [comment] 2020-04-02 16:23
> Isn't this a duplicate of #183?

This lists specific packages for use on Linux. The other pertains to Azure infrastructure limitations.

**Comment by alepauly** [comment] 2020-04-06 22:38
@koteswara-kelam Unfortunately we are unable to support this at the moment, thanks for suggesting it.

**Closed by alepauly** 2020-04-06 22:38 UTC
Labels: needs eyes

**Comment by MaxPeal** [comment] 2020-05-12 06:48
+1

**Comment by pp185214** [comment] 2020-06-12 10:28
+1

**Comment by typetetris** [comment] 2020-07-04 08:18
+1

**Comment by filipkowicz** [comment] 2020-07-07 08:35
Android developers need it run emulator way faster. Needed for instrumentation tests

**Comment by AfzalivE** [comment] 2021-03-11 22:26
> @koteswara-kelam Unfortunately we are unable to support this at the moment, thanks for suggesting it.

If this isn't supported yet, wouldn't it be better to keep this issue open?

**Comment by headsvk** [comment] 2022-02-09 15:52
Can this be done as part of [Roadmap #161 ](https://github.com/github/roadmap/issues/161)?
