### ISSUE TITLE
Image 20210525.0 Azure MSIX build and package task error NETSDK1004

### ISSUE THREAD

**Issue by JulesMBooth** [actions/virtual-environments#3501] opened 2021-06-01 13:04 UTC
**Description**  
Azure MSIX build and package task build always fails with:  error NETSDK1004: Assets file 'D:\a\8\s\xxxxxx.Packager\obj\project.assets.json' not found. Run a NuGet package restore to generate this file. [D:\a\8\s\xxxxxx.Packager\xxxxxxx.Packager.wapproj]. 
No changes were made to the solution between builds. Was working last week, experienced intermittent errors on Thursday now 100% error in pipeline. Looked at difference between successes and fails from last week. Image <= 20210516.0 produced successful builds all builds on 20210525.0 fail.

**Area for Triage**:  
.NET Framework

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Image version**
20210525.0 

**Expected behavior**  
Task to run successfully as with previous images. 

**Actual behavior**  
Error during build looking for a project.assets.json file that would not exist and isn't necessary. 

Replacing the MSIX Build and Package task with a Visual Studio build task also produces the same error. 

**Repro steps**  
Create a pipleline with a MSIX Build and Package task or use a Visual Studio Build Task with parameters to create MSIX. 

I have a sandbox pipeline pointing at a very simple Solution with the same basic setup WPF Project +UWP Packing project built via Azure Pipeline which has developed the exact same issue.

**Comment by LeonidLapshin** [comment] 2021-06-01 13:12
Hey, @JulesMBooth !
Have you tried to upgrade VS to latest version (16.10) on your local machine? Does this issue reproduce for you locally?

**Comment by JulesMBooth** [comment] 2021-06-01 14:11
> Hey, @JulesMBooth !
> Have you tried to upgrade VS to latest version (16.10) on your local machine? Does this issue reproduce for you locally?

Not as yet, other issues I need to attend to after spending a lot of time on this I'm afriad. I was assuming it will reproduce the error if I do though. Will try to replicate locally when I can.

**Comment by JulesMBooth** [comment] 2021-06-02 09:31
I've now tested 16.10 on an AWS EC2 Windows Server 2019 Build 17663 instance and there does _not_ seem to be an issue. 

I made a test hello world app and then got down the actual Solution in question from DevOps and both worked succesfully locally. I was able to produce a MSIX.

**Comment by JulesMBooth** [comment] 2021-06-09 08:08
Still seems to be an issue in 20210531.1. Any ideas?

**Comment by miketimofeev** [comment] 2021-06-09 08:27
@JulesMBooth we've started the new image rollout with VS 16.10.1 on board. If you don't mind let's wait for the deployment and get back to this if the issue persists. The new image version is 20210608.0

**Comment by kassannk** [comment] 2021-06-11 07:21
Hi @JulesMBooth,
Looks like you forget to give us a link on the failed build, please let me take a look on the failed build.

**Comment by JulesMBooth** [comment] 2021-06-11 09:20
Hi @kassannk, I am not sure if this is what you are asking for or not? That's the latest failed build link. 

https://dev.azure.com/watsonwheatleyfinancialsystems/WWFS/_build/results?buildId=3043&view=results

**Comment by kassannk** [comment] 2021-06-11 09:45
> Hi @kassannk, I am not sure if this is what you are asking for or not? That's the latest failed build link.
> 
> https://dev.azure.com/watsonwheatleyfinancialsystems/WWFS/_build/results?buildId=3043&view=results

I cannot follow this link, I do not have access to this link.

**Comment by JulesMBooth** [comment] 2021-06-11 10:03
Yeah I didn't think you would be able to I'm not sure how I would share a build with someone outside my organisation TBH? 

The build is part of my Organisations Azure DevOps  and you would need to be part of the Organization to view the build.

What can I provide you to give you the info you need?  I believe my Reproduciton steps are accurate.

**Comment by kassannk** [comment] 2021-06-11 10:36
> Yeah I didn't think you would be able to I'm not sure how I would share a build with someone outside my organisation TBH?
> 
> The build is part of my Organisations Azure DevOps and you would need to be part of the Organization to view the build.
> 
> What can I provide you to give you the info you need? I believe my Reproduciton steps are accurate.

1. Do you have .yml file in the root of your project?
2. If not please to export YML like on the screenshot
3. Also please open the last build and download the raw logs of the build
4. You did nuget restore?

Thanks.

**Comment by kassannk** [comment] 2021-06-11 10:42
> Yeah I didn't think you would be able to I'm not sure how I would share a build with someone outside my organisation TBH?
> 
> The build is part of my Organisations Azure DevOps and you would need to be part of the Organization to view the build.
> 
> What can I provide you to give you the info you need? I believe my Reproduciton steps are accurate.

1. Do you have .yml file in the root of your project?
2. If not please to export YML like on the screenshot
3.  Alst please open the last build and download the raw logs of the build
4.

**Comment by JulesMBooth** [comment] 2021-06-11 10:55
Please see attached files. I've also included the logs from Build 2984 the last success and a prior failure to that build 2978 that failed when the image updated to 20210525.0.

[logs_2978_first_fail_with_image_20210525.0.zip](https://github.com/actions/virtual-environments/files/6637850/logs_2978_first_fail_with_image_20210525.0.zip)
[logs_3043_last_fail.zip](https://github.com/actions/virtual-environments/files/6637851/logs_3043_last_fail.zip)
[logs_2984_last_success..zip](https://github.com/actions/virtual-environments/files/6637852/logs_2984_last_success.zip)
[iRecsDesktop-MSIX.zip](https://github.com/actions/virtual-environments/files/6637853/iRecsDesktop-MSIX.zip)

**Comment by JulesMBooth** [comment] 2021-06-11 11:28
Can you confirm you have these logs etc. I'd like to remove the links if so.

**Comment by kassannk** [comment] 2021-06-11 11:31
> Can you confirm you have these logs etc. I'd like to remove the links if so.



> Can you confirm you have these logs etc. I'd like to remove the links if so.

I'm looking at the logs. you can delete links

**Comment by JulesMBooth** [comment] 2021-06-15 08:30
Still an issue in 20210608.0

**Comment by kassannk** [comment] 2021-06-15 08:35
> Still an issue in 20210608.0

Hi. Thank you for message. I am currently reviewing the error completely, and come back to you.

**Comment by kassannk** [comment] 2021-06-15 09:38
@JulesMBooth 
1. I looked and it seems the file is in the obj folder, it most likely ends up in .gitignore and therefore it is not in the repository. It is created by nuget, but apparently there is no such step in the pipeline.
2. I assume that you did not add this obj \project.assets.json file to the repo, so you build everything locally, and regeneration is needed on the github
3. And it would be nice to give a link to the failed build. I could better understand what the problem is.
We are looking forward to your reply.

**Comment by JulesMBooth** [comment] 2021-06-15 12:39
Hi,

I've actually found a work around for this now having taken a little inspiration from [here](https://improveandrepeat.com/2019/10/how-to-generate-a-missing-project-assets-json-in-azure-devops/), That's for a .Net Core solution which my solution is not and is out of date (the Azure pipeline task they suggest to use to fix it does not exist anymore) but anyway I found putting in a VS build task with the arguments: _/t:Restore_  creates the "missing" project.assets.json file in the Windows Application Packaging project obj folder for the pipeline.  If that is run before the MSIX build and package task then the task succeeds. 

Hopefully this will keep working for a bit. 

To answer some of the questions above though we dont's use Git we use Azure Devops Server (Team Foundation Studio, TFS in Azure) but either way we wouldn't include the contents of the obj directory in our source control.

The file that it claims is missing would never exist and up to 20210525.0 was never required.  The project the task is failing on is a    [Windows Application Packaging Project](https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-packaging-dot-net) (.wapproj) and would never have nuget dependencies. I did add in a nuget restore step after the pipeline started failing for no (apparent based on changes we'd made) reason and I saw this error but as there is nothing to restore the file is never created. If you compare the logs of the last successful build to the first failure you can see nothing has changed in that area between builds 

This is the issue, I run the same MSBuild arguments as the MSIX build and package on another machine (with as close as possible to the Azure agent environment as I can manage) and we didn't have this problem and it didn’t exist prior to 20210525.0.

I would love to supply you with a link to the failed build(s) but have no idea how to share a build from inside my organisation with people outside the organisation. 

Thanks for your help.

**Comment by kassannk** [comment] 2021-06-15 13:23
> Hi,
> 
> I've actually found a work around for this now having taken a little inspiration from [here](https://improveandrepeat.com/2019/10/how-to-generate-a-missing-project-assets-json-in-azure-devops/), That's for a .Net Core solution which my solution is not and is out of date (the Azure pipeline task they suggest to use to fix it does not exist anymore) but anyway I found putting in a VS build task with the arguments: _/t:Restore_ creates the "missing" project.assets.json file in the Windows Application Packaging project obj folder for the pipeline. If that is run before the MSIX build and package task then the task succeeds.
> 
> Hopefully this will keep working for a bit.
> 
> To answer some of the questions above though we dont's use Git we use Azure Devops Server (Team Foundation Studio, TFS in Azure) but either way we wouldn't include the contents of the obj directory in our source control.
> 
> The file that it claims is missing would never exist and up to 20210525.0 was never required. The project the task is failing on is a [Windows Application Packaging Project](https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-packaging-dot-net) (.wapproj) and would never have nuget dependencies. I did add in a nuget restore step after the pipeline started failing for no (apparent based on changes we'd made) reason and I saw this error but as there is nothing to restore the file is never created. If you compare the logs of the last successful build to the first failure you can see nothing has changed in that area between builds
> 
> This is the issue, I run the same MSBuild arguments as the MSIX build and package on another machine (with as close as possible to the Azure agent environment as I can manage) and we didn't have this problem and it didn’t exist prior to 20210525.0.
> 
> I would love to supply you with a link to the failed build(s) but have no idea how to share a build from inside my organisation with people outside the organisation.
> 
> Thanks for your help.

I am going to close this issue then, please, feel free to contact us if you see this error again. Thanks

**Closed** 2021-06-15 13:24 UTC
Labels: Area: .NET Framework, OS: Windows, investigate

**Comment by kassannk** [comment] 2021-06-15 13:41
@JulesMBooth 
Also I would like to mention that the only important update was the studio upgrade, and probably the task does not support it normally yet, you can open your problem at https://developercommunity.visualstudio.com/

**Comment by kassannk** [comment] 2021-06-15 13:42
@JulesMBooth 
Also I would like to mention that the only important update was the studio upgrade, and probably the task does not support it normally yet, you can open your problem at https://developercommunity.visualstudio.com/
