### ISSUE TITLE
pip3 and python3 seem to use different versions

### ISSUE THREAD

**Issue by jurplel** [actions/virtual-environments#1818] opened 2020-10-14 15:56 UTC
**Description**  
When using pip3, it installs modules for python 3.9, but using python3 searches for modules for python 3.8.

**Area for Triage**:  Python

**Question, Bug, or Feature?**:  Bug

**Virtual environments affected**  
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
I expect python3 and pip3 to use the same python version, as they have before today.

**Actual behavior**  
Python3 and pip3 are from different python versions

**Repro steps**  
1. Install module with pip3
2. Try to use that module with python3
3. Module not found

**Comment by maxim-lobanov** [comment] 2020-10-14 16:31
Thank you for report, we will take a look.
For now, I suggest using [setup-python](https://github.com/marketplace/actions/setup-python) (GitHub Actions) or [UsePython](https://docs.microsoft.com/ru-ru/azure/devops/pipelines/tasks/tool/use-python-version?view=azure-devops&viewFallbackFrom=azure-devops-2019) (Azure DevOps) tasks to switch Python and don't depend on system one.
It is recommended ways to use Python on image.

**Comment by jurplel** [comment] 2020-10-14 16:34
I am the author of an action that uses python internally

**Comment by LeonidLapshin** [comment] 2020-10-14 17:58
Hi @jurplel 
Deploy of the new image for macOS is cancelled due this problem
Currently rollback to the previous image stable version is in progress.
Thank you for your report!

**Comment by maxim-lobanov** [comment] 2020-10-15 08:26
Hello, thank you for reporting this issue.
Broken image was rolled back so you should be unblocked.

We have found root cause related to `brew` and prepared fix from our side. See details in #1819 .
I will close this issue as duplicate.

**Closed by maxim-lobanov** 2020-10-15 08:26 UTC
Labels: Area: Python, awaiting-deployment, investigate

**Comment by jurplel** [comment] 2020-10-15 13:45
Thank you!
