### ISSUE TITLE
Add configurable OS versions of Xcode Simulators.

### ISSUE THREAD

**Issue by descorp** [actions/virtual-environments#996] opened 2020-06-03 09:52 UTC
**Description**

I want to run my tests on different versions of iOS / macOS / watchOS using the latest Xcode.

Right now, each version of Xcode comes with the corresponding "build-in" versions of SDKs.
So, the only way to run an iPhone Simulator with an iOS 12.4 is by switching to an `Xcode 10.3`.

The problem is that it is not possible to run swift5 code on Xcode 10.3.

**Possible solution**

1. Stash all `.sdk` images from all Xcodes  `/Applications/Xcode_[Version].app/Contents/Developer/Platforms/[Platform]/Developer/SDKs/` in one place.
2. Create a configuration for environment like:

       env:
          DEVELOPER_DIR: '/Applications/Xcode_11.4.1.app/Contents/Developer'
          DEVELOPER_SDK: ['iPhoneSimulator13.2', 'WatchOS6.1' ]

3. Move / Copy `.sdk` to a correspondent `DEVELOPER_DIR`.

**Virtual environments affected**
- [x] macOS 10.15

**Can this tool be installed during the build?**
Yes

**Comment by maxim-lobanov** [comment] 2020-06-03 09:55
Duplicate of #551. 
We have a plan to pre-install more simulators but can't provide any ETA for now.
I am closing this one as duplicate so you can track status of this request in #551

**Closed** 2020-06-03 09:56 UTC
Labels: Area: Apple, duplicate
