### ISSUE TITLE
Choco install `visualstudio2017-workload-vctools` no longer works on `windows-2019`

### ISSUE THREAD

**Issue by bdemers** [actions/virtual-environments#2857] opened 2021-03-05 19:56 UTC
**Description**  

A recent update to the windows-2019 image has broken the ability to run:

```sh
choco install visualstudio2017-workload-vctools
```

This was working until 2020/03/01
My last successful build: https://github.com/okta/okta-cli/actions/runs/612582756

Example error log: https://github.com/okta/okta-cli/runs/2025623252?check_suite_focus=true

**Work around**

Switching from `windows-latest` to `windows-2016` seems to work around the issue (with the downside of being a different version of windows)

https://github.com/okta/okta-cli/pull/91/files

**Area for Triage**:  

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Image version**

Windows: 20210219.1

**Expected behavior**  

A successful install, likely containing the following:

```txt
visualstudio2017buildtools has been installed.
  visualstudio2017buildtools may be able to be automatically uninstalled.
 The install of visualstudio2017buildtools was successful.
  Software installed to 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools'
```

**Actual behavior**  

Install failure 

```txt
WARNING: Found 2 still running Visual Studio installer processes:
WARNING: [436] vs_bootstrapper
WARNING: [3104] vs_setup_bootstrapper
WARNING: Waiting for the processes to finish...
visualstudio2017buildtools has been installed.
  visualstudio2017buildtools may be able to be automatically uninstalled.
 The install of visualstudio2017buildtools was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

visualstudio2017-workload-vctools v1.3.2 [Approved]
visualstudio2017-workload-vctools package files install completed. Performing other installation steps.
ERROR: Unable to detect any supported Visual Studio product. You may try passing --installPath or both --productId and --channelId parameters.
The install of visualstudio2017-workload-vctools was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\visualstudio2017-workload-vctools\tools\ChocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 5/6 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Installed:
 - visualstudio2017buildtools v15.9.33.0
 - dotnetfx v4.8.0.20190930
 - chocolatey-visualstudio.extension v1.9.0
 - visualstudio-installer v2.0.1
 - chocolatey-dotnetfx.extension v1.0.1

Failures
 - visualstudio2017-workload-vctools (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\visualstudio2017-workload-vctools\tools\ChocolateyInstall.ps1'.
```

**Repro steps**  

Minimal repro [case](https://github.com/bdemers/gh-actions-vs-code-test/blob/bdemers-patch-1/.github/workflows/blank.yml):

```yaml
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Visual C Build Tools Workload for Visual Studio 2017 Build Tools
        run: |
          choco install visualstudio2017-workload-vctools
```

**Comment by gep13** [comment] 2021-03-06 13:27
@jberezanski can you offer any help here?

**Comment by jberezanski** [comment] 2021-03-06 22:23
From the posted log snippet, it seems that although the dependent Build Tools package installed successfully, the workload package could not see the installed Build Tools instance for some reason.
In order to try to determine the cause, I would need:
- the full Chocolatey log: `$Env:ChocolateyInstall\logs\chocolatey.log`
- the Visual Studio log files (there will be a lot of them): `$Env:TEMP\chocolatey\dd_*.log`

One quick suggestion: the installed VS instance detection logic in the packages works better (more reliably) if the `VSSetup` module is installed (`Install-Module -Name VSSetup -Repository PSGallery -Force`).

By the way, I've just installed that workload successfully (without the VSSetup module) on a clean Windows Server 2019 Datacenter Core virtual machine (installed from an MSDN image) with OS patches from December 2019 (grossly outdated, I know, but that's what I had at hand).

**Comment by maxim-lobanov** [comment] 2021-03-08 07:35
@bdemers , both failed and successful builds were run on the same image version: 20210219.1
![image](https://user-images.githubusercontent.com/16715858/110288986-d742de00-7ff9-11eb-941e-258bd528c709.png)
it means that both builds were run on the identical VM machine and no changes from side that could break it.

**Comment by maxim-lobanov** [comment] 2021-03-10 14:56
Closing the issue since we have confirmed that failures above are not related to changes on Hosted images

**Closed by maxim-lobanov** 2021-03-10 14:56 UTC
Labels: external
