### ISSUE TITLE
Increased number of `npm ERR! cb() never called!` failures

### ISSUE THREAD

**Issue by desrosj** [actions/virtual-environments#3572] opened 2021-06-11 18:14 UTC
**Description**  
On the [WordPress/Gutenberg](https://github.com/WordPress/gutenberg/) repository, we've been experiencing an increased number of workflows failing due to the following error:
```
npm ERR! prepareGitDep npm ERR! cb() never called!
npm ERR! prepareGitDep 
npm ERR! prepareGitDep npm ERR! This is an error with npm itself. Please report this error at:
npm ERR! prepareGitDep npm ERR!     <https://npm.community>
npm ERR! prepareGitDep 
npm ERR! prepareGitDep npm ERR! A complete log of this run can be found in:
npm ERR! prepareGitDep npm ERR!     /home/runner/.npm/_logs/2021-06-10T14_22_37_476Z-debug.log
npm ERR! prepareGitDep 
npm ERR! premature close

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-06-10T14_22_37_959Z-debug.log
```

**Area for Triage**:  
JavaScript and Node.js

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

20210606.1

**Expected behavior**  
`npm install` completes without an error.

**Actual behavior**  
Error listed above is displayed and the job fails.

**Repro steps**  
It has happened on almost all of the workflows in the repository running `npm install` or `npm ci`. It is seemingly random, but has only happened on:
- Jobs using NodeJS 14.
- Jobs using `ubuntu-latest`.

We have not encountered the issue on MacOS jobs, or any job that uses NodeJS 12. In most cases, re-running the workflow will succeed, but occasionally a third run is required.

Some examples of this happening:

- https://github.com/WordPress/gutenberg/runs/2772750162?check_suite_focus=true
- https://github.com/WordPress/gutenberg/runs/2796371763?check_suite_focus=true
- https://github.com/WordPress/gutenberg/runs/2792357958?check_suite_focus=true
- https://github.com/WordPress/gutenberg/runs/2794893452?check_suite_focus=true
- https://github.com/WordPress/gutenberg/runs/2796376926?check_suite_focus=true

From what I've been able to find on this error, there are three ways people usually resolve this issue:
- Running `npm cache clean --force`.
- Uninstalling and reinstalling NodeJS.
- Changing the `ulimit` for NodeJS.

We've ruled out that any cache being restored from https://github.com/actions/cache is causing the problem (unless there is some type of cache at the system level), as the error has happened when there was no cache restored. Some workflows where that is the case:
- https://github.com/WordPress/gutenberg/pull/32588/checks?check_run_id=2794349657
- https://github.com/WordPress/gutenberg/runs/2795420302?check_suite_focus=true
- https://github.com/WordPress/gutenberg/runs/2804309744

I don't think we have the ability to try the other two ways to resolve.

At the direction of GitHub support, I've also posted this to [actions/setup-node](https://github.com/actions/setup-node/issues/268).

**Comment by desrosj** [comment] 2021-06-14 17:32
Just to add a few more jobs showing this error since creating the initial ticket:
- https://github.com/WordPress/gutenberg/runs/2821787867?check_suite_focus=true
- https://github.com/WordPress/gutenberg/runs/2820196534?check_suite_focus=true
- https://github.com/WordPress/gutenberg/runs/2820180799?check_suite_focus=true
- https://github.com/WordPress/gutenberg/runs/2820180683?check_suite_focus=true
- https://github.com/WordPress/gutenberg/runs/2820173098?check_suite_focus=true

**Comment by desrosj** [comment] 2021-06-15 00:19
Looks like this error is also happening in other repos. Just had an instance in WordPress/wordpress-develo: https://github.com/WordPress/wordpress-develop/runs/2824875313?check_suite_focus=true.

**Comment by al-cheb** [comment] 2021-06-15 06:18
Hello, @desrosj.
Thank you for your report. We will take a look.

**Comment by nikita-bykov** [comment] 2021-06-21 17:12
Hello @desrosj. 
It looks like this issue is reproducible not only in our CI, but also in the local environment. [NPM repository ](https://github.com/npm/cli/issues?q=is%3Aissue+cb%28%29+never+called+is%3Aopen)has a lot of opened and closed issues related to `npm ERR! cb() never called`. Many reasons can lead to this error and they have an [article ](https://github.com/npm/cli/wiki/%22cb()-never-called%3F--I'm-having-the-same-problem!%22)described it.
Considering the fact that issue is reproduced outside of GitHub Actions CI and only with specific version of Node.js, we should report this issue to Node.js team. Not much we can do from our side.

**Comment by nikita-bykov** [comment] 2021-06-28 13:38
Hello @desrosj. I'm going to close this issue. If you have any questions feel free to contact us.

**Closed by nikita-bykov** 2021-06-28 13:38 UTC
Labels: Area: JavaScript and Node.js, Area: Packages, OS: Ubuntu, investigate

**Comment by desrosj** [comment] 2021-06-30 19:04
Thanks @nikita-bykov. I'll follow up with the NPM team.
