### ISSUE TITLE
Rust self-update will block builds

### ISSUE THREAD

**Issue by kaylangan** [actions/virtual-environments#246] opened 2020-01-09 22:44 UTC
**Describe the bug**
See https://github.com/microsoft/azure-pipelines-image-generation/issues/1224

**Area for Triage**: Rust

**Question, Bug, or Feature?**: Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**
Rust call succeeds even if an update is available.

**Actual behavior**
Call fails with:
```
error: could not remove 'setup' file: 'C:\Users\runneradmin\.cargo\bin/rustup-init.exe'
info: caused by: Access is denied. (os error 5)
```

**Comment by kinnison** [comment] 2020-01-09 23:06
FYI I think I'm managing to update rustup and rust in some fashion in a workflow: https://github.com/rust-lang/rustup/runs/381347070#step:11:12

**Comment by AlenaSviridenko** [comment] 2020-04-10 08:34
Closing this issue since no customers raise this issue for a while. 
Feel free to open new ticket if the issue still persists and blocks something.

**Comment by divergentdave** [comment] 2020-07-19 17:50
I ran into this issue with this build: https://github.com/spacejam/sled/pull/1129/checks?check_run_id=887343882. The command was `rustup update`, and the error message was:

```
error: could not remove 'setup' file: 'C:\Users\runneradmin\.cargo\bin/rustup-init.exe'
error: caused by: Access is denied. (os error 5)
```

Presumably this issue went away previously because the image was updated, and it has come back again since rustup released a new version recently.

**Comment by maxim-lobanov** [comment] 2020-07-20 05:03
Reopened to revisit this issue

**Comment by al-cheb** [comment] 2020-07-20 06:13
@divergentdave,
Could you please replace and validate your workflow with `rustup update` to `rustup update | Out-Null` ?

**Comment by maxim-lobanov** [comment] 2020-07-20 08:00
Related issue: https://github.com/rust-lang/rustup/issues/2415
`--no-self-update` does workaround and build is green but rust self-update still fails.
Interesting point that file `C:\Users\runneradmin\.cargo\bin/rustup-init.exe` doesn't exist until `rustup update` command

**Comment by divergentdave** [comment] 2020-07-20 13:55
@al-cheb My builds are also running on Linux and Mac, so I don't think I can use `Out-Null`. I plan to use the `--no-self-update` workaround.

**Comment by mati865** [comment] 2020-07-20 18:54
@divergentdave you can use bash everywhere and then run with `rustup update || true`. This will ignore update error.

**Comment by Darleev** [comment] 2020-07-27 16:46
Hello,
The issue was reproduced locally and finally reported to Rust team. You can track status of the issue in the Rust repository:
https://github.com/rust-lang/rustup/issues/2441
As a workaround, just need to add some sleep interval between `rustup update` and other rust-related tasks. Also, you can use the previously mentioned solution: `rustup update --no-self-update`

In case of any questions, please do not hesitate to contact us.

**Closed by Darleev** 2020-07-27 16:46 UTC
Labels: Area: Rust, investigate
