### ISSUE TITLE
WiX Builds are broken with recent update to virtual environments

### ISSUE THREAD

**Issue by svnscha** [actions/virtual-environments#4582] opened 2021-11-24 16:19 UTC
### Description

Our WiX setup builds are suddenly broken. The build system is reporting that the following file is missing:

- `C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\WiX\v3.x\Wix.targets`

Recently WiX was updated - is the Visual Studio extension missing/broken now?

- https://github.com/actions/virtual-environments/releases

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Agent name: 'Azure Pipelines 2'
Agent machine name: 'WIN-3155C9SFUN7'
Current agent version: '2.195.0'
Operating System
Virtual Environment
Virtual Environment Provisioner
Current image version: '20211122.1'

### Is it regression?

no

### Expected behavior

I expect the build to complete successfully.

### Actual behavior

The build breaks because of recently missing files in the build environment.

### Repro steps

Build a WiX Setup project using Visual Studio.

**Comment by al-cheb** [comment] 2021-11-24 16:20
@svnscha , Please take a look at https://github.com/actions/virtual-environments/issues/4419

**Comment by bstr413** [comment] 2021-11-24 17:36
Can confirm that this is an issue. Switching the agent to windows-2022 or windows-latest is a workaround for this issue.

**Comment by dibir-magomedsaygitov** [comment] 2021-11-24 20:48
Closing this issue as a duplicate of #4419

**Closed by dibir-magomedsaygitov** 2021-11-24 20:48 UTC
Labels: needs triage

**Comment by svnscha** [comment] 2021-11-25 07:45
The comments in issue #4419 indeed helped. But the actual fix is changing the *.wixproj file as mentioned by someone in that thread.

```
<Import Project="$(WixTargetsPath)" Condition=" '$(WixTargetsPath)' != ''" />
  <Import Project="$(MSBuildExtensionsPath32)\Microsoft\WiX\v3.x\Wix.targets" Condition=" '$(WixTargetsPath)' == '' AND Exists('$(MSBuildExtensionsPath32)\Microsoft\WiX\v3.x\Wix.targets') "/>
  <Target Name="EnsureWixToolsetInstalled" Condition=" '$(WixTargetsImported)' != 'true' ">
     <Error Text="The WiX Toolset v3.11 (or newer) build tools must be installed to build this project. To download the WiX Toolset, see http://wixtoolset.org/releases/" />
  </Target>
```

For reference, the required change and `windows-2019` still works with that, too.

**Comment by AlmightyFuzz** [comment] 2021-11-25 14:14
@dibir-magomedsaygitov I don't think this is a duplicate of #4419 because adding the Wix tools to the `windows-2022` vm image should not have broken the `windows-2019` vm image.

**Comment by al-cheb** [comment] 2021-11-25 14:22
@AlmightyFuzz , This https://github.com/actions/virtual-environments/pull/4448 PR affected all Windows Server 2016,2019,2022 images.

**Comment by AlmightyFuzz** [comment] 2021-11-25 14:29
@al-cheb Why? The pull request title suggests it should only affect 2022?

**Comment by al-cheb** [comment] 2021-11-25 14:55
> @al-cheb Why? The pull request title suggests it should only affect 2022? The #4419 issue also says that it should only affect 2022.
> 
> Because of this change our builds on windows-2019 are now failing.

It's a single script for all images - https://github.com/barnson/virtual-environments/blob/main/images/win/scripts/Installers/Install-Wix.ps1

**Comment by AlmightyFuzz** [comment] 2021-11-25 15:51
I understand what has changed now, as part of the update to the `windows-2022` image you have removed the `Wix Toolset Studio 2019 Extension` from the `windows-2019` image. See [win-2019 readme changes](https://github.com/actions/virtual-environments/commit/446bf8d222493ea5c155c47024263a72f3aa87dc#diff-b60cdaf0c005f4f4f992f022cc8eb2ef29c8c03c8f18f04d225851500acd0325)

If the script is used by all images then shouldn't a `Test-IsWin22` check have been added to that script file rather than removing something that was already installed on the vm image that people were already using and relying on?

**Comment by Gallimathias** [comment] 2021-11-25 15:59
Adjusting the files has not helped us at the moment. We are now running the script that @barnson removed again manually in the CI process.

Warning. This could extend every build by at least 20 minutes.

This issue cost us today and the next day's a lot of time 😑

_Have to remove the test call because file is not there_

````
Choco-Install -PackageName wixtoolset -ArgumentList "--force"

if (Test-IsWin19)
{
    $extensionUrl = "https://wixtoolset.gallerycdn.vsassets.io/extensions/wixtoolset/wixtoolsetvisualstudio2019extension/1.0.0.4/1563296438961/Votive2019.vsix"
    $VSver = "2019"
}
else
{
    throw "Invalid version of Visual Studio is found. 2019 are required"
}

$extensionName = "Votive$VSver.vsix"

#Installing VS extension 'Wix Toolset Visual Studio Extension'
Install-VsixExtension -Url $extensionUrl -Name $extensionName -VSversion $VSver

````

**Comment by KlausLinzner** [comment] 2021-11-26 08:15
Please don't get me wrong - I completely understand that changes can be necessary f.e. switching from windows-2019 to windows-2022; this is not a problem as it can be handled via regular change & deployment process to make those changes ahead of time.
And while everybody understands that bugs can occur, (intentionally) breaking a released image is a completely different situation; 

We ship build pipelines and deployment pipelines to customers - some repos we don't event have access to.
At the moment it's a lot of work to update all of our repositories and their branches and to ship emergency fixes to customers.

Once the current situation is dealt with we'll have to answer why we chose a platform that can break at a moment's notice - and we'll likely need to move away from hosted Azure.
