### ISSUE TITLE
apt-get failing. Broken apt list?

### ISSUE THREAD

**Issue by gimenete** [actions/virtual-environments#443] opened 2020-02-21 12:06 UTC
**Describe the bug**

People were getting yesterday "Conflicting distribution" error when using "apt-get update":
https://github.community/t5/GitHub-Actions/apt-get-update-failing-with-quot-Conflicting-distribution-quot/td-p/47157

A user posted a workaround https://github.community/t5/GitHub-Actions/apt-get-update-failing-with-quot-Conflicting-distribution-quot/m-p/47169/highlight/true#M6749

**Area for Triage**: 

**Question, Bug, or Feature?**: 

**Virtual environments affected**
- [ ] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**

apt-get update to work with no errors.

**Actual behavior**

`apt-get update` was failing yesterday with the following error message: "Conflicting distribution"

**Comment by al-cheb** [comment] 2020-02-21 12:26
Hello, @gimenete 

I could not reproduce the issue on Ubuntu 16.04/18.04:

Ubuntu 16.04
![16 04 - Copy](https://user-images.githubusercontent.com/47745270/75034536-73b54380-54be-11ea-8b49-0c6a94f964c7.JPG)

Ubuntu 18.04
![18 04 - Copy](https://user-images.githubusercontent.com/47745270/75034542-76b03400-54be-11ea-9941-bcc756a746f0.JPG)

**Comment by gimenete** [comment] 2020-02-21 12:30
Thanks @al-cheb !

Is it possible that was a temporary issue?

**Comment by al-cheb** [comment] 2020-02-21 12:41
@gimenete 

I looked at customer asnwer:
https://github.community/t5/GitHub-Actions/apt-get-update-failing-with-quot-Conflicting-distribution-quot/m-p/47160#M6742

His broken build: https://github.com/kubernetes/minikube/pull/6723/checks?check_run_id=459207826 step  `install libvirt`
```
W: Conflicting distribution: https://packages.microsoft.com/ubuntu/16.04/prod xenial InRelease (expected xenial but got stable)
E: Repository 'https://packages.microsoft.com/ubuntu/16.04/prod xenial InRelease' changed its 'Origin' value from 'microsoft-ubuntu-xenial-prod xenial' to 'vscode stable'
E: Repository 'https://packages.microsoft.com/ubuntu/16.04/prod xenial InRelease' changed its 'Label' value from 'microsoft-ubuntu-xenial-prod xenial' to 'vscode stable'
E: Repository 'https://packages.microsoft.com/ubuntu/16.04/prod xenial InRelease' changed its 'Suite' value from 'xenial' to 'stable'
E: Repository 'https://packages.microsoft.com/ubuntu/16.04/prod xenial InRelease' changed its 'Codename' value from 'xenial' to 'stable'
```

2 ago build was fine at step  `install libvirt`:
https://github.com/kubernetes/minikube/runs/459920975?check_suite_focus=true

![ubuntu - Copy](https://user-images.githubusercontent.com/47745270/75035466-95172f00-54c0-11ea-93d5-08cd5979ad3f.JPG)

**Comment by gimenete** [comment] 2020-02-21 12:46
@al-cheb 

Thanks for looking deeper into it. Which information do you need from customers? @BrightRan is the support person that is on charge of this support ticket. I believe he could answer them for any additional information useful for investigating the problem.

Thanks both!

**Comment by al-cheb** [comment] 2020-02-21 12:51
@gimenete,

May be the miss something and I think we should request a minimal step to reproduce the issue from customer side.

**Comment by traversaro** [comment] 2020-02-21 14:44
I also experienced the same issue in https://github.com/robotology/gazebo-yarp-plugins/runs/459286832 . This is the usual flakiness of the Microsoft apt repos at https://packages.microsoft.com/repos, you can find more about this in https://github.com/actions/virtual-environments/issues/323, and  also a workaround in https://github.com/actions/virtual-environments/issues/323#issuecomment-578392268 .

The root problem is tracked by the dotnet community in https://github.com/dotnet/core/issues/4167 . As mentioned there (in https://github.com/dotnet/core/issues/4167#issuecomment-578350465), however : 
> It's all about https://packages.microsoft.com/. (VSCode and PowerShell use it too, for example.) We don't understand and don't yet have transparency into how the service works and why.
> 
> The Microsoft linux package repository team has no public presence, so unfortunately there's nothing I can point to. We're going to post info here when we have something to share.

As I do not need the packages provided by those repos, I started to just remove the apt repos from all my GitHub Actions jobs as a first step, to avoid meeting this problem every few weeks.

**Comment by LorenzE** [comment] 2020-02-21 14:46
I encountered the exact same issue yesterday. Works fine for us today.

**Comment by maxim-lobanov** [comment] 2020-03-16 13:13
It looks like it is a transient issue. I am closing the issue for now but feel free to reopen if any

**Closed by maxim-lobanov** 2020-03-16 13:13 UTC
Labels: OS: Ubuntu, needs triage
