### ISSUE TITLE
Windows bash: kill command takes up to 15min to kill process

### ISSUE THREAD

**Issue by BrightRan** [actions/virtual-environments#917] opened 2020-05-21 06:00 UTC
In [this Community Forum ticket](https://github.community/t5/GitHub-Actions/Windows-bash-kill-command-takes-up-to-15min-to-kill-process/td-p/59188), the user is using Windows runner and different Python versions for integration tests.
It seems that all the Python builds (Python 2.7, 3.5, 3.6, 3.7 and 3.8) on Windows always run time out.
The user figured out that the `kill` command used in Windows takes way too long, it takes up to 15 minutes to kill the Python process.
The program itself does not intercept signals send to it. It works fine on Ubuntu and MacOS.

I also forked and tested the user's workflows on my side, I can reproduce the same problem.

**Comment by cytopia** [comment] 2020-05-23 18:05
If you need any help triaging this, let me know - it directly affects my builds.

**Comment by nikita-bykov** [comment] 2020-05-28 16:20
Hello @cytopia , thank you for the report!
We tried to reproduce an issue from our side (run python process in background with infinity loop and kill it from bash via "kill" command) but everything passed successfully and quickly.
Unfortunately, we don't have enough context to investigate an issue based on your repository because it is pretty complicated. Is it possible to provide minimal repro steps for this issue?

**Comment by cytopia** [comment] 2020-05-28 17:16
If you have a local Windows machine at hand, you can simply run it with `make test`. I unfortunately do not own any Windows OS, so cannot reproduce this behaviour.

If trying this out locally is not an option I can try to provide a simple repository for debugging purposes.

**Comment by nikita-bykov** [comment] 2020-05-29 16:27
Hello @cytopia 
As a possible fix, you can try to change bash that is used in your build (by default Git bash is used on image).
For example, you can select MSYS bash using the following code:
```
- name: Add bash to the Path
   run: |
     echo "::add-path::c:\msys64\mingw32\bin"
     echo "::add-path::c:\msys64\usr\bin"
```
if it doesn't help, please provide minimal repro steps for this issue to simplify debugging.

**Comment by cytopia** [comment] 2020-06-05 15:44
@nikita-bykov I've added your suggestions. Seems like it is an outdated bash which doesn't support this:

```bash
$ diff <(printf expect | od -c) <(cat file_stdout | od -c)
diff: /dev/fd/63: No such file or directory
```

Are the default bash versions different on older and newer Windows version?

**Comment by nikita-bykov** [comment] 2020-06-09 18:05
Hello @cytopia 
The default git bash version is 4.4.23(1)-release and msys64 bash version is 4.4.23(2)-release. Unfortunately, these are all available versions on Windows images.
You can try to apply the following fix:
```
- name: Add bash to the Path
   run: |
         echo "::add-path::c:\msys64\mingw32\bin"
         echo "::add-path::c:\msys64\usr\bin"
-  name: Fix
   run: |
         ln -s /proc/self/fd /dev/fd
         echo -n expect > test.txt
         diff <(printf expect | od -c) <(cat test.txt| od -c)
      shell: bash 
```
If you still have the kill command issue, please provide the repro steps for this issue to simplify debugging.

**Comment by nikita-bykov** [comment] 2020-06-17 13:09
Hello @cytopia! Please let us know if you have any updates or if you need any help.

**Comment by cytopia** [comment] 2020-06-21 07:23
@nikita-bykov I've implemented a lot of changes within the Python program and now Windows seems to be able to `kill` the program without delays. I suppose I hit an edge case of some Python functionality (which did not apply for pypy[23]) and Windows.

For me this issue is gone as it does not occur anymore. Thanks anyway for being available and trying to solve this with me

**Comment by nikita-bykov** [comment] 2020-06-22 09:05
You're welcome, @cytopia!
I'm closing this issue. If you have any other questions please feel free to ask!

**Closed by nikita-bykov** 2020-06-22 09:05 UTC
Labels: Area: Scripting and command line, OS: Windows, investigate

**Comment by yukihiko-shinoda** [comment] 2021-02-14 07:03
In my case, this resoleved by following update:

```python
#!/usr/bin/env python

import setuptools

setuptools.setup(
    name = "my_package",
    ....,
)
```

🔽

```python
#!/usr/bin/env python

import setuptools

if __name__ == '__main__':
    setuptools.setup(
        name = "my_package",
        ....,
    )
```

see: [Answer: How to get `setup.py test` working with `multiprocessing` on Windows?](https://stackoverflow.com/a/50402381/12721873)
