### ISSUE TITLE
mini-kube instable on macos

### ISSUE THREAD

**Issue by sebastian-toepfer** [actions/virtual-environments#3031] opened 2021-03-25 21:58 UTC
**Description**  
We use mini-kube to setup our application to run test agains.
To setup mini-kube we use fork from `medyagh/setup-minikube` (fork only has macos support). This action works most time, sometimes the setup failed. After setup we must install/active a ingress. this setp timed out in 5 of 10 runs. Some days we have multiple runs without issues on other we have more runs that failed.

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
setup an ingress node failed every time or run every time stable.

**Actual behavior**  
setup of an ingress node failed randomly.
```
Verifying ingress addon...

X Exiting due to MK_ENABLE: run callbacks: running callbacks: [waiting for app.kubernetes.io/name=ingress-nginx pods: timed out waiting for the condition]
* 

* If the above advice does not help, please let us know: 
  - https://github.com/kubernetes/minikube/issues/new/choose
Error: Process completed with exit code 10.
```

**Repro steps**  
sample workflow
```
- name: start minikube
      id: minikube
      uses: sebastian-toepfer/setup-minikube@master
      with:
        minikube-version: 1.17.1

    - name: configure minikube
      run: |
        minikube addons enable ingress
        minikube update-context
        kubectl delete -A ValidatingWebhookConfiguration ingress-nginx-admission
```

**Comment by LeonidLapshin** [comment] 2021-03-26 07:54
Hey, @sebastian-toepfer !
Thank you for your proposal, we need some time for initial investigation, will back to this ticket soon and keep you updated :)

**Comment by dmitry-shibanov** [comment] 2021-03-30 16:59
Hello @sebastian-toepfer. I tried to reproduce your issue but unsuccessful . Could you please try to use the latest version of `minikube 1.18.1`.

**Comment by sebastian-toepfer** [comment] 2021-03-31 05:14
Hello @dmitry-shibanov, had update mini-kube to 1.18.1 short after open this issue, but it doesn't change anything. Yeah the issue is tricky, sometimes it doesn't occured. Sometime many times in a row. Have you a tip to enable some tracing logs to help you to dig deeper into this?

**Comment by dmitry-shibanov** [comment] 2021-03-31 15:07
Hello @sebastian-toepfer. I'm not really sure that the issue is related to images itself, because I saw some similar [issues](https://github.com/kubernetes/minikube/issues?q=is%3Aissue+Exiting+due+to+MK_ENABLE%3A+run+callbacks%3A+running+callbacks%3A+%5Bwaiting+for+app.kubernetes.io%2Fname%3Dingress-nginx+pods%3A+timed+out+waiting+for+the+condition%5D+is%3Aopen) in minikube repository. I think It's some kind of issue with minikube.

**Comment by sebastian-toepfer** [comment] 2021-04-07 05:44
agree, minikube is not the best friend of macos. our issue is, that it runs 50 percent of the time and the same amount it doesn't. so for us it looks that some images has issues - may workload or so. It would be nice to get actions that run stable, to get more confindence about runs ... and not oh it was macos is normal and restart it without looking at the error. It would be nice if you hit us in the right direction. And if is a issue with the image we can fix it together. If you are not interesst, than close this issue.

**Comment by dmitry-shibanov** [comment] 2021-04-07 08:27
Hello @sebastian-toepfer. Unfortunately, we can't reproduce the issue from our side, that is why we're blocked to fully investigate the issue. Through 20-30th runs we didn't face up with it. We don't have much experience with `minikube` and we have found  the similar issues in `minikube` repository. As we understood the issue can be reproduced outside of CI that is why we think it's not really related to CI itself. If you can share some other logs or information it would be helpful.

**Comment by dmitry-shibanov** [comment] 2021-04-15 07:49
Hello @sebastian-toepfer. I'm closing the issue, because for now we can't reproduce it from our side and don't have enough information about it. If you get any extra information please share with us and feel free to reopen the issue.

**Closed by dmitry-shibanov** 2021-04-15 07:49 UTC
Labels: Area: Common Tools, Area: Containers, OS: macOS, investigate

**Comment by sebastian-toepfer** [comment] 2021-05-07 12:25
@dmitry-shibanov : can you me explain how to setup a github like runner as self-hosted. we would dig deeper into this issue.

**Comment by sebastian-toepfer** [comment] 2021-05-12 12:11
Hello @dmitry-shibanov, i have setup a runner with this guide, but is behave different to a hosted macos runner. So i ask how to emulate a fullblow github runner and not a selfhosted only.

**Comment by maxim-lobanov** [comment] 2021-05-17 16:24
Unfortunately, currently, macOS is not supported in Azure and it is a tricky to configure identical environment.
One possible way is taking clean macOS machine and run all necessary scripts in the same order: https://github.com/actions/virtual-environments/blob/main/images/macos/templates/macOS-10.15.json
But it is definitely not simple and could take a lot of time.

**Comment by sebastian-toepfer** [comment] 2021-06-08 05:49
@maxim-lobanov thx, will try it and come back if i know more about this issue.
