### ISSUE TITLE
Error on cloning a repository on windows-2019 20210914.2

### ISSUE THREAD

**Issue by adrianeui** [actions/virtual-environments#4099] opened 2021-09-16 07:30 UTC
### Description

Hi, 

We've an error while executing the github action actions/checkout@v2  on the repo 

This started all the sudden like 10 days ago or so , as you can see the error reported is 

Error: fatal: early EOF
Error: fatal: fetch-pack: invalid index-pack output

Which basically indicates somekind of network issue , the error is consistent now all builds fails and reruing previous successful builds it raises the same error as it will pick a different windows-2019 image.

I've been comparing both images and I've detected that git version changed to 2.33 I've tried in a windows 10 laptop but no error so far (i've tried multiple attempts executing the same git commands)

Then I suspect that might be something related to openssl or so but I didn't have time to check it.  I've tried doing a new run with full log enabled for github actions but no luck to get more insight on what's going on.

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Environment: windows-2019
  Version: 20210914.2
  Included Software: https://github.com/actions/virtual-environments/blob/win19/20210914.2/images/win/Windows2019-Readme.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/win19%2F20210914.2

### Is it regression?

Version: 20210815.1. 

### Expected behavior

It should clone successfully the repository.

### Actual behavior

We get an error while doing the clone , it's consistent error as we did multiple attempts and no clone ended-up correctly.
Having said that the error is random as it may happen while doing the fetch of the parent or cloning the subrepos.

Error: fatal: early EOF
Error: fatal: fetch-pack: invalid index-pack output

### Repro steps

1. Execute github action actions/checkout@v2 on repo

**Comment by Darleev** [comment] 2021-09-16 08:43
Hello @adrianeui,
Could you please provide an example of a workflow where it is possible to reproduce the issue? It will help to speed up the investigation.
We're looking forward to your reply.

**Comment by adrianeui** [comment] 2021-09-16 10:15
I can't share it as it's a private repo which I don't wanna make the urls public , is there a way to share them to you directly ?

**Comment by Darleev** [comment] 2021-09-16 12:06
@adrianeui maybe is it possible to reproduce this behavior on another project/repository? If the issue is agent-specific, I guess it should reproduce on other cases as well.

**Comment by adrianeui** [comment] 2021-09-16 12:11
well this repository has multiple submodules and I'm not sure if the size or some type of file is affecting to the fetch / clone ops then trying to replicate it in other repos might be is not feasible

**Comment by miketimofeev** [comment] 2021-09-16 12:16
@adrianeui have you tried another image or even another OS (ubuntu, for example)? Does the issue occur there as well?

**Comment by adrianeui** [comment] 2021-09-16 12:19
we're using for the same job a mac from macstadium provisioned there and all builds works fine. Also I've tried to do the clone in my windows 10 - laptop using same git version as the one in your image and it works fine. As I've mention this was working like a charm during a lot of time.

BTW I've opened a ticket via github company support you might get the info from there.

**Comment by miketimofeev** [comment] 2021-09-16 12:56
@adrianeui got it but is it possible for you to try other hosted images like windows-2016 or ubuntu-20? I'm asking because the issue can be related to the actions\checkout task rather than the VM image.

**Comment by adrianeui** [comment] 2021-09-16 13:00
Let me try with windows-2016

**Comment by adrianeui** [comment] 2021-09-16 13:06
good news is that the clone works in windows-2016 not sure what differences are between 2019 and 2016. But it crashes in this action:

Run kuler90/setup-unity@v1
Error: Unable to locate executable file: D:\a\_temp\02194f74-c7eb-48b6-bebd-6faafb8cee66. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also verify the file has a valid extension for an executable file.

Anyway I think is better to focus in 2019 as 2016 I suppose eventually will be deprecated.

**Comment by miketimofeev** [comment] 2021-09-16 13:12
@adrianeui thanks for checking! Does windows-2022 works as well?

**Comment by adrianeui** [comment] 2021-09-16 13:23
windows-2022 fails in the same way as 2019

**Comment by adrianeui** [comment] 2021-09-16 14:32
btw I was checking now the checkout version but I dont see any change in the recent dates 
https://github.com/actions/checkout/releases then this shouldn't be the issue as the last one is from previous year.

**Comment by Darleev** [comment] 2021-09-16 14:37
@adrianeui could you please try to clone your repository directly using `git` command and remove actions/checkout step? Does it still get stuck?
We're looking forward to your reply.

**Comment by adrianeui** [comment] 2021-09-16 16:07
i've tried it and it works doing a basic 

         git clone --recursive --depth 1 git@github.com:scopely/Scopely-SDK-Dev.git C:/old-clone
          cd C:/old-clone
          git submodule update --init --recursive

But how can it be that the issue is the action if that didn't change ? It seems that there's a specific operation inside that action that has a problem with something updated in the image.

**Comment by adrianeui** [comment] 2021-09-16 16:13
This is what we're using from checkout. 
  
  - name: Clone step
        uses: actions/checkout@v2
        with:
          lfs: true
          repository: XXXX
          ssh-key: ${{secrets.XXX}}
          submodules: recursive
          persist-credentials: true

**Comment by Darleev** [comment] 2021-09-17 14:48
@adrianeui we've contacted the Github Actions Checkout team and it seems we are unable to proceed with the investigation without steps to reproduce the issue. The issue is quite specific for your project, and we cannot reproduce it on our side.

**Comment by jww3** [comment] 2021-09-17 15:43
Possibly related:  https://portal.microsofticm.com/imp/v3/incidents/details/262023309/home

**Comment by adrianeui** [comment] 2021-09-20 06:50
Is there a way to continue this issue via the Github Enterprise support ? There we provided all the details.

**Comment by Darleev** [comment] 2021-09-20 14:19
@adrianeui we've discussed the issue internally, and it seems there is a problem with `git pull` using ssh for GitHub actions job. Since we have no ideas how to reproduce the issue at this moment - the best way to investigate the issue further - contact GitHub Enterprise Support.
If additional assistance information is required from our side, do not hesitate to contact us.

**Comment by Darleev** [comment] 2021-09-27 07:23
Hello @adrianeui,
I'm going to close the issue until further clarifications from your side.
Feel free to contact us at any time.

**Closed by Darleev** 2021-09-27 07:23 UTC
Labels: OS: Windows, investigate
