### ISSUE TITLE
Add Python 3.0.x, 3.1.x, 3.2.x, 3.3.x and 3.4.x to python-versions.

### ISSUE THREAD

**Issue by AraHaan** [actions/virtual-environments#1943] opened 2020-10-31 18:55 UTC
**Tool information**
- Tool name: Python
- Tool license: 
- Add or update? Add
- Desired version: Any version of 3.0.x, 3.1.x, 3.2.x, 3.3.x, and 3.4.x on Windows for both x86 and x64
- Approximate size: 
- If this is an add request:
  - Brief description of tool: A interpreter based programming language.
  - URL for tool's homepage: https://www.python.org/downloads/
  - Provide a basic test case to validate the tool's functionality: import sys; print(sys.modules)

**Area for Triage**:

**Question, Bug, or Feature?**:

Feature

**Virtual environments affected**
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**

Nope, the build errors because the versions of the tool needed do not exist on some of the virtual environments (windows specifically most of the time).
3.4.x might work for linux / mac since there are versions in python-versions with only linux or mac, however 3.3.x, 3.2.x, 3.1.x and 3.0.x are missing entirely.

**Tool installation time in runtime**

Not sure.

**Are you willing to submit a PR?**

I already submitted one to python-versions including an temporary fix for windows only. I will need help since I do not have a working linux and mac to compile for those as well for the python versions I pull requested to add.
https://github.com/actions/python-versions/pull/61

Also I got the sources to the absolute latest versions of those python versions however trying to build the msi installer files for python does not work since I do not know exactly how to find all the things I actually need to create the msi installer for those specific python versions.
The urls I used to download the installers for these in the mean time:
https://www.python.org/downloads/release/python-301/
https://www.python.org/downloads/release/python-314/
https://www.python.org/downloads/release/python-325/
https://www.python.org/downloads/release/python-335/
https://www.python.org/downloads/release/python-344/

**Comment by maxim-lobanov** [comment] 2020-11-02 14:53
Hello @AraHaan , thank you for feature request.
For Ubuntu and MacOS, we build python from source code. It is pretty tricky to build those old versions. Some time ago we have tried but failed and wouldn't like to invest more time into it. For example, Python 3.4 end of life was more than 1 year ago.
For Windows, we don't build from source code and just re-pack existing Python binaries so if it makes sense to you, we can upload Windows binaries for these versions

**Comment by AraHaan** [comment] 2020-11-03 05:29
Alright, however I do know how to build those versions of python as I done so before, however for 3.4.10 it fails to create the msi for x64 since it fails on also the ssl module and the xxlimited module as well, but I did manage to build x86 msi for 3.4.10 however.

**Comment by MaksimZhukov** [comment] 2020-11-06 09:28
Hello @AraHaan !
We've published the following Python versions for Windows to the [actions/python-versions](https://github.com/actions/python-versions/releases) repository:
- 3.4.4 
- 3.3.5 
- 3.2.5 
- 3.1.4 
- 3.0.1 

We've also updated the `versions-manifest.json` file in scope of [this pull request](https://github.com/actions/python-versions/pull/62), so these Python versions can be installed by [actions/setup-python](https://github.com/actions/setup-python) action.

I'm closing this issue, but feel free to contact us if you have any questions.

**Comment by Leseratte10** [comment] 2020-11-06 09:50
Just leaving this comment here' not 100% sure if this is the correct place: It looks like the old Python versions were now added (requesting Python version 3.4.4 on Windows x86 does now work), but it seems like there is an error in the install script. 

The file that is downloaded contains a "setup.ps1" script that installs and configures the Python stuff, and that script is updating Pip with the following command `cmd.exe /c "$PythonExePath -m ensurepip && $PythonExePath -m pip install --upgrade pip"`. 

In my case, this removes Pip 7.1.2 and installs Pip 20.2.4. 

However, it looks like Pip 20.2.4 requires Python 3.5 or later, so this Python installation is effectively broken now as it has a Pip version that can no longer run using the installed Python version: 

```
  File "c:\hostedtoolcache\windows\python\3.4.4\x86\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 92, in <module>
    raise RuntimeError("Python 3.5 or later is required")
RuntimeError: Python 3.5 or later is required
```

Can the installation script be changed so it doesn't update Pip to the most recent version, or maybe make it update to the last version that supports the given Python version?

**Comment by maxim-lobanov** [comment] 2020-11-06 10:05
cc: @MaksimZhukov to take a look.

**Comment by MaksimZhukov** [comment] 2020-11-09 14:24
Hello @Leseratte10 ! Thank you for the your comment! 

We have rebuilt the recently added Python versions. We've removed Pip upgrading for Python 3.4.4 so the default Pip version will be used. Could you please verify if it works for you?

Please note that Pip is not automatically installed with Python less than 3.4. If you are going to use Pip, you need to install it yourself.

**Comment by Leseratte10** [comment] 2020-11-09 15:52
Thanks. I can confirm that Python 3.4.4 now works fine with my app, that was all I needed for Windows XP support. 

I tested 3.3 as well and that still display some weird error, but I believe that is due to my application / the fact that 3.3 is very very outdated, and not due to a packaging error.

**Comment by MaksimZhukov** [comment] 2020-11-09 17:03
Thanks for the quick response! 

I will close this issue, but feel free to contact us if you have any concerns.

**Closed by MaksimZhukov** 2020-11-09 17:03 UTC
Labels: Area: Python, feature request
