### ISSUE TITLE
Installation failure for grub-efi-amd64-signed

### ISSUE THREAD

**Issue by jamtur01** [actions/virtual-environments#1605] opened 2020-09-16 15:19 UTC
**Description**  
We're seeing some intermittent failures using the ubuntu-20.04 image (Version: 20200914.1). We run a bootstrap script that does an apt update and then an apt upgrade which fails with:

```text
Setting up grub-efi-amd64-signed (1.142.6+2.04-1ubuntu26.4) ...
Trying to migrate /boot/efi into esp config
Installing grub to /boot/efi.
Installing for x86_64-efi platform.
grub-install: warning: Internal error.
grub-install: error: failed to register the EFI boot entry: Operation not permitted.
```

You can see some failures here:

https://github.com/timberio/vector/pull/3932

Specifically:

https://github.com/timberio/vector/pull/3932/checks?check_run_id=1123684447

You can see one of the workflows here:

https://github.com/timberio/vector/blob/master/.github/workflows/tests.yml

And the bootstrap script we run here:

https://github.com/timberio/vector/blob/master/scripts/environment/bootstrap-ubuntu-20.04.sh

**Area for Triage**:  
Packages

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [X] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
To be able to apt upgrade successfully.

**Actual behavior**  
apt upgrade fails with:

```
Setting up initramfs-tools (0.136ubuntu6.3) ...
update-initramfs: deferring update (trigger activated)
Setting up grub-efi-amd64-signed (1.142.6+2.04-1ubuntu26.4) ...
Trying to migrate /boot/efi into esp config
Installing grub to /boot/efi.
Installing for x86_64-efi platform.
grub-install: warning: Internal error.
grub-install: error: failed to register the EFI boot entry: Operation not permitted.
dpkg: error processing package grub-efi-amd64-signed (--configure):
 installed grub-efi-amd64-signed package post-installation script subprocess returned error exit status 1
Setting up cryptsetup-initramfs (2:2.2.2-3ubuntu2.2) ...
update-initramfs: deferring update (trigger activated)
update-initramfs: deferring update (trigger activated)
Processing triggers for libc-bin (2.31-0ubuntu9) ...
Processing triggers for rsyslog (8.2001.0-1ubuntu1.1) ...
Processing triggers for systemd (245.4-4ubuntu3.2) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for install-info (6.7.0.dfsg.2-5) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for initramfs-tools (0.136ubuntu6.3) ...
update-initramfs: Generating /boot/initrd.img-5.4.0-1025-azure
Errors were encountered while processing:
 grub-efi-amd64-signed
E: Sub-process /usr/bin/dpkg returned an error code (1)
##[error]Process completed with exit code 100.
```

**Repro steps**  

It's intermittent - but is happening more on each run we've monitored.

https://github.com/timberio/vector/pull/3932
https://github.com/timberio/vector/pull/3932/checks?check_run_id=1123684447

**Comment by al-cheb** [comment] 2020-09-16 16:57
Hello, @jamtur01 
Could you please add `update-grub` command before `apt update --yes` and validate build?

**Comment by jamtur01** [comment] 2020-09-16 17:22
Looks like that fixes it from what I can see. Certainly, none of our bootstraps have failed, but the problem has been intermittent.

**Comment by jamtur01** [comment] 2020-09-16 20:46
This isn't a permanent solution. We use the same bootstrap script inside Docker containers - this solution will obviously choke in there as `update-grub` will fail.

**Comment by al-cheb** [comment] 2020-09-17 06:16
@jamtur01 , As a temporary workaround you can test if process running in a docker container:

```
if ! grep 'docker' /proc/1/cgroup -q ; then  
	update-grub
fi
```

**Comment by al-cheb** [comment] 2020-09-30 07:39
Feel free to open the thread if you have any concerns.

**Comment by jamtur01** [comment] 2020-09-30 13:57
Has the issue been resolved and can we remove the workaround?

**Comment by al-cheb** [comment] 2020-09-30 17:54
@jamtur01, Looks like the issue doesn't reproduce on the new image:
```
 - name: Azure
      run: |
        sudo apt update --yes
        sudo apt upgrade --yes
```

**Comment by jamtur01** [comment] 2020-10-26 15:20
This is back again.

https://github.com/timberio/vector/runs/1308881114?check_suite_focus=true

```
Setting up grub-efi-amd64-signed (1.142.8+2.04-1ubuntu26.6) ...
Trying to migrate /boot/efi into esp config
Installing grub to /boot/efi.
Installing for x86_64-efi platform.
grub-install: warning: Internal error.
grub-install: error: failed to register the EFI boot entry: Operation not permitted.
dpkg: error processing package grub-efi-amd64-signed (--configure):
 installed grub-efi-amd64-signed package post-installation script subprocess returned error exit status 1
Processing triggers for systemd (245.4-4ubuntu3.2) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for dbus (1.12.16-2ubuntu2.1) ...
Processing triggers for install-info (6.7.0.dfsg.2-5) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for libc-bin (2.31-0ubuntu9.1) ...
Processing triggers for initramfs-tools (0.136ubuntu6.3) ...
update-initramfs: Generating /boot/initrd.img-5.4.0-1031-azure
Errors were encountered while processing:
 grub-efi-amd64-signed
E: Sub-process /usr/bin/dpkg returned an error code (1)
Error: Process completed with exit code 100.
```

**Comment by al-cheb** [comment] 2020-10-27 08:52
Hello, @jamtur01 
Looks like a bug - https://bugs.launchpad.net/ubuntu/+source/dpkg/+bug/1871963

As a temporary workaround, please update workflow to include:
```
- run: sudo apt-get purge grub\*
- run: sudo bash scripts/environment/bootstrap-ubuntu-20.04.sh
```

**Comment by hloeung** [comment] 2020-11-22 17:43
Maybe https://bugs.launchpad.net/ubuntu/+source/grub2/+bug/1901650 ?

**Comment by al-cheb** [comment] 2020-12-14 08:58
Hello, @jamtur01 
Seems the bug is fixed in - https://launchpad.net/ubuntu/+source/efivar/37-2ubuntu2.2

Waiting for a new image rollout with updated libs:
```
libefiboot1/focal-updates,now 37-2ubuntu2.2 amd64 [installed,automatic]
libefivar1/focal-updates,now 37-2ubuntu2.2 amd64 [installed,automatic]
```

**Comment by al-cheb** [comment] 2020-12-17 06:16
Deployment of Ubuntu 20.04 has been finished.

**Closed by al-cheb** 2020-12-17 06:16 UTC
Labels: OS: Ubuntu, bug, external, investigate
