### ISSUE TITLE
The ps commands fails in workflows running on macos-latest

### ISSUE THREAD

**Issue by rlepigre** [actions/virtual-environments#3462] opened 2021-05-27 00:24 UTC
**Description**  
Running the `ps` command (without any argument) in a `macos-latest` virtual environment fails after only printing the header line of its output. On the other hand, running `ps $$` succeeds as expected.

In an `ubuntu-latest` environment both commands succeed as expected.

**Area for Triage**:  

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

Possibly macOS 11 as well, but I could not test for some reason.

**Image version**
20210525.2

**Repro steps**  

To reproduce the following trivial workflow can be used:
```yaml
name: Debugging workflow
on: [push]
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Testing the ps command (with $$)
        run: ps $$
      - name: Testing the ps command (no argument)
        run: ps
```

A failing run with this workflow can be found [here](https://github.com/rlepigre/GameShell/runs/2680376882?check_suite_focus=true).

**Comment by rlepigre** [comment] 2021-05-27 00:27
cc @phyver

**Comment by dibir-magomedsaygitov** [comment] 2021-05-27 09:06
Hello @rlepigre. Thank you for your report. We will take a look.

**Comment by Darleev** [comment] 2021-06-01 13:17
Hello @rlepigre,
Most probably, ps returns with a non-zero exit code on some BSD-based systems when there are no processes found. ( https://github.com/sarugaku/shellingham/issues/15, which is an unrelated project but describes a similar problem.) So I guess you could either provide arguments to decide what processes to look for or add `ps || true` to avoid ps command failures.

**Comment by rlepigre** [comment] 2021-06-01 13:39
Hi @Darleev,
Thanks for looking into this! I can see how that may be the case with the example of failing workflow I proposed, but in my actual workflow I use `ps` to monitor processes I launched myself (and which can only be stopped with a `kill`), so there should definitely be processes to find I think.

**Comment by Darleev** [comment] 2021-06-07 20:38
@rlepigre I've reproduced the issue and gathered all required data. 
Currently, we involved our internal engineering team to investigate the issue further. 
As soon as new information appears, I'll let you know.

**Comment by rlepigre** [comment] 2021-06-07 20:58
Thanks, that's great!

**Comment by Darleev** [comment] 2021-06-21 14:02
Hello @rlepigre,
We've investigated the issue and it seems the issue can be reproduced on macOS machine locally as well. 
For example, you can easily reproduce the issue just using the following context:

`ssh user@macos ps`

At the same time, the example above returns actual user processes for ubuntu agents. I see the following workarounds for the issue:

1. If it is possible, use ubuntu agents;
2. Use `ps` command with keys(-a, -aux, -auxfww etc.) and grep required processes

If you have any additional information for us, we will be glad to assist you further.
We're looking forward to your reply.

**Comment by Darleev** [comment] 2021-06-23 19:33
@rlepigre I'm going to close the issue since it's not agent-specific, it's how it works on macOS machines itself.
In case of any questions, feel free to contact us.

**Closed by Darleev** 2021-06-23 19:33 UTC
Labels: Area: Scripting and command line, OS: macOS, investigate

**Comment by rlepigre** [comment] 2021-06-23 21:13
OK makes sense. Thanks a lot for looking into this @Darleev!
I'll try to find myself a macOS machine to experiment on locally.
