### ISSUE TITLE
[ubuntu-18.04] Installation of wine32:i386 broken since last night

### ISSUE THREAD

**Issue by hartwork** [actions/virtual-environments#3339] opened 2021-05-07 12:39 UTC
**Description**  
My workflow YAML is installing package `wine32:i386` on image `ubuntu-18.04` and it worked fine until yesterday, but started failing tonight (error below) and keeps failing when I re-run that job.

PS: Running things outside GitHub Actions with plain Docker like this still works fine todday:
```console
# docker run --rm -it ubuntu:18.04 bash -c 'dpkg --add-architecture i386 && apt-get update && apt-get install --yes --no-install-recommends -V wine32:i386'
```

**Area for Triage**:  

???

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [x] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

`20210504.1`

**Expected behavior**  
Be able to install `wine32:i386` as working previously.

**Actual behavior**  
I get this error, also when re-running the task:
```
The following packages have unmet dependencies:
 wine32:i386 : Depends: libwine:i386 (= 3.0-1ubuntu1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Repro steps**  
This workflow YAML has everything:
https://github.com/libexpat/libexpat/blob/4a7b1d5dcf91c95d472f4ebb73291d7785edd626/.github/workflows/coverage.yml

Sample error ouput:
https://github.com/libexpat/libexpat/runs/2527225732?check_suite_focus=true

**Comment by miketimofeev** [comment] 2021-05-07 12:55
Hi @hartwork!
The root cause is that some packages depends on "ppa:ondrej/php" repository, which were removed from the apt list after the image was generated.
Adding it back solves the issue:          
`sudo apt-add-repository "ppa:ondrej/php" -y`

**Comment by miketimofeev** [comment] 2021-05-07 13:16
@hartwork actually we are also surprised by the number of packages that come from the `ppa:ondrej/php` and agree that it's not obvious at all to add that ppa back when you have no dependencies on PHP.
We're going to revert this PR https://github.com/actions/virtual-environments/pull/3272 and deploy the new image next week.
Sorry for the inconvenience!

**Comment by hartwork** [comment] 2021-05-07 13:21
> @hartwork actually we are also surprised by the number of packages that come from the `ppa:ondrej/php` and agree that it's not obvious at all to add that ppa back when you have no dependencies on PHP.

:+1: 

> We're going to revert this PR #3272 and deploy the new image next week.
> Sorry for the inconvenience!

@miketimofeev I guess the…
> ```
> # remove repository after successfull installation
> rm -r /etc/apt/sources.list.d/ondrej-ubuntu-php-*
> ```
…in #3272 are the problem, maybe not the rest of it. Thanks again for your quick and helpful reaction! :+1: :+1: 

PS: It sounds like the ticket will remain open until then. I will stay subscribed here then and drop the workaround on ticket closing. If that's a misunderstanding on my side, please let me know.

**Comment by hartwork** [comment] 2021-05-07 15:06
@miketimofeev excellent! :+1:

**Comment by miketimofeev** [comment] 2021-05-13 13:40
@hartwork we've deployed the new images. I checked wine32 installation — everything works like a charm now.
I'm going to close the issue. Please feel free to contact us if you have any concerns

**Closed by miketimofeev** 2021-05-13 13:40 UTC
Labels: Area: Deployment/Release, Area: Image administration, Area: Scripting and command line, OS: Ubuntu, awaiting-deployment

**Comment by hartwork** [comment] 2021-05-13 15:04
Thanks! :+1:

**Comment by LordOfDragons** [comment] 2022-05-23 15:00
I've got the same problem. Seems like the regression is back.
