### ISSUE TITLE
Flaky networking on macos-11

### ISSUE THREAD

**Issue by trinitronx** [actions/virtual-environments#4809] opened 2021-12-27 08:05 UTC
### Description

Networking appears to be flaky, resulting in intermittent job failures.  Symptoms in logs vary, but are all networking errors.  I tried using the workaround mentioned in #1187, but this appears not to have fixed the issue.

For example:

- GitHub actions itself could not download the `setup-ruby` action:

        Warning: Failed to download action 'https://api.github.com/repos/ruby/setup-ruby/tarball/168d6a54b412713c0ed60998a78093a270ca8d84'. Error: The operation was canceled.

- A ruby gem `librarian-chef` could not finish a cookbook dependency download:

        /Users/runner/work/sprout-wrap/sprout-wrap/vendor/bundle/ruby/2.7.0/gems/librarian-0.1.2/lib/librarian/posix.rb:116:in `run!': error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54 (Librarian::Posix::CommandFailure)
        fatal: expected flush after ref listing

- Networking errors from `git` commands:

        error: 6086 bytes of body are still expected
        fetch-pack: unexpected disconnect while reading sideband packet
        fatal: early EOF
        fatal: fetch-pack: invalid index-pack output

- Homebrew `brew tap` error also from flaky networking:

            ================================================================================
            Error executing action `tap` on resource 'homebrew_tap[homebrew/cask-drivers]'
            ================================================================================
            
            Mixlib::ShellOut::CommandTimeout
            --------------------------------
            Command timed out after 600s:
            Command exceeded allowed execution time, process terminated
            ---- Begin output of /usr/local/bin/brew tap  homebrew/cask-drivers  ----
            STDOUT: 
            STDERR: ==> Tapping homebrew/cask-drivers
            Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers'...
            Warning: Permanently added the ECDSA host key for IP address '140.82.113.4' to the list of known hosts.
            fetch-pack: unexpected disconnect while reading sideband packet
            Error: SIGTERM
            Do not report this issue until you've run `brew update` and tried again.
            /usr/local/Homebrew/Library/Homebrew/utils.rb:38:in `wait'
            /usr/local/Homebrew/Library/Homebrew/utils.rb:38:in `_system'
            /usr/local/Homebrew/Library/Homebrew/utils.rb:47:in `system'
            /usr/local/Homebrew/Library/Homebrew/utils.rb:302:in `safe_system'
            /usr/local/Homebrew/Library/Homebrew/tap.rb:306:in `install'
            /usr/local/Homebrew/Library/Homebrew/cmd/tap.rb:65:in `tap'
            /usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
            ---- End output of /usr/local/bin/brew tap  homebrew/cask-drivers  ----
            Ran /usr/local/bin/brew tap  homebrew/cask-drivers  returned 1
            
            Cookbook Trace:
            ---------------
            /var/chef/cache/cookbooks/homebrew/resources/tap.rb:33:in `block (2 levels) in class_from_file'
            /var/chef/cache/cookbooks/homebrew/resources/tap.rb:32:in `block in class_from_file'
            
            Resource Declaration:
            ---------------------
            # In /var/chef/cache/cookbooks/homebrew/recipes/install_taps.rb
            
             24:     homebrew_tap tap
             25:   elsif tap.is_a?(Hash)
            
            Compiled Resource:
            ------------------
            # Declared in /var/chef/cache/cookbooks/homebrew/recipes/install_taps.rb:24:in `block in from_file'
            
            homebrew_tap("homebrew/cask-drivers") do
              action [:tap]
              default_guard_interpreter :default
              declared_type :homebrew_tap
              cookbook_name "homebrew"
              recipe_name "install_taps"
              homebrew_path "/usr/local/bin/brew"
              owner "runner"
            end
            
            System Info:
            ------------
            chef_version=13.10.0
            platform=macos
            platform_version=11.6.2
            ruby=ruby 2.7.5p203 (2021-11-24 revision f69aeb8314) [x86_64-darwin20]
            program_name=chef-solo worker: ppid=37306;start=04:43:36;
            executable=/Users/runner/work/sprout-wrap/sprout-wrap/vendor/bundle/ruby/2.7.0/bin/chef-solo
            
        [2021-12-27T05:07:46+00:00] INFO: Running queued delayed notifications before re-raising exception

        Running handlers:
        [2021-12-27T05:07:46+00:00] ERROR: Running exception handlers
        Running handlers complete
        [2021-12-27T05:07:46+00:00] ERROR: Exception handlers complete
        Chef Client failed. 109 resources updated in 24 minutes 09 seconds
        [2021-12-27T05:07:46+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
        [2021-12-27T05:07:46+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
        [2021-12-27T05:07:46+00:00] ERROR: homebrew_tap[homebrew/cask-drivers] (homebrew::install_taps line 24) had an error: Mixlib::ShellOut::CommandTimeout: Command timed out after 600s:
        Command exceeded allowed execution time, process terminated
        ---- Begin output of /usr/local/bin/brew tap  homebrew/cask-drivers  ----
        STDOUT: 
        STDERR: ==> Tapping homebrew/cask-drivers
        Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers'...
        Warning: Permanently added the ECDSA host key for IP address '140.82.113.4' to the list of known hosts.
        fetch-pack: unexpected disconnect while reading sideband packet
        Error: SIGTERM
        Do not report this issue until you've run `brew update` and tried again.
        /usr/local/Homebrew/Library/Homebrew/utils.rb:38:in `wait'
        /usr/local/Homebrew/Library/Homebrew/utils.rb:38:in `_system'
        /usr/local/Homebrew/Library/Homebrew/utils.rb:47:in `system'
        /usr/local/Homebrew/Library/Homebrew/utils.rb:302:in `safe_system'
        /usr/local/Homebrew/Library/Homebrew/tap.rb:306:in `install'
        /usr/local/Homebrew/Library/Homebrew/cmd/tap.rb:65:in `tap'
        /usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
        ---- End output of /usr/local/bin/brew tap  homebrew/cask-drivers  ----
        Ran /usr/local/bin/brew tap  homebrew/cask-drivers  returned 1
        [2021-12-27T05:07:46+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
        +(./bootstrap-scripts/bootstrap.sh:244): errorout 'Soloist provisioning failed!'
        ERROR: Soloist provisioning failed!
 - Another example from `brew install mediainfo` failing to download:

            ================================================================================
            Error executing action `install` on resource 'homebrew_package[mediainfo]'
            ================================================================================
            
            Mixlib::ShellOut::ShellCommandFailed
            ------------------------------------
            Expected process to exit with [0], but received '1'
            ---- Begin output of ["brew", "install", "mediainfo"] ----
            STDOUT: ==> Downloading https://ghcr.io/v2/homebrew/core/media-info/manifests/21.09
            STDERR: Warning: Treating mediainfo as a formula. For the cask, use homebrew/cask/mediainfo
            curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
            Error: media-info: Failed to download resource "media-info_bottle_manifest"
            Download failed: https://ghcr.io/v2/homebrew/core/media-info/manifests/21.09
            ---- End output of ["brew", "install", "mediainfo"] ----
            Ran ["brew", "install", "mediainfo"] returned 1
            
            Resource Declaration:
            ---------------------
            # In /var/chef/cache/cookbooks/homebrew/recipes/install_formulas.rb
            
             31:     package formula
             32:   end
            
            Compiled Resource:
            ------------------
            # Declared in /var/chef/cache/cookbooks/homebrew/recipes/install_formulas.rb:31:in `block in from_file'
            
            homebrew_package("mediainfo") do
              package_name "mediainfo"
              action [:install]
              default_guard_interpreter :default
              declared_type :package
              cookbook_name "homebrew"
              recipe_name "install_formulas"
            end
            
            System Info:
            ------------
            chef_version=13.10.0
            platform=macos
            platform_version=11.6.2
            ruby=ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin19]
            program_name=chef-solo worker: ppid=16101;start=07:52:49;
            executable=/Users/runner/work/sprout-wrap/sprout-wrap/vendor/bundle/ruby/2.6.0/bin/chef-solo
            
        [2021-12-27T08:44:18+00:00] INFO: Running queued delayed notifications before re-raising exception

        Running handlers:
        [2021-12-27T08:44:18+00:00] ERROR: Running exception handlers
        Running handlers complete
        [2021-12-27T08:44:18+00:00] ERROR: Exception handlers complete
        Chef Client failed. 129 resources updated in 51 minutes 29 seconds
        [2021-12-27T08:44:18+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
        [2021-12-27T08:44:18+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
        [2021-12-27T08:44:18+00:00] ERROR: homebrew_package[mediainfo] (homebrew::install_formulas line 31) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
        ---- Begin output of ["brew", "install", "mediainfo"] ----
        STDOUT: ==> Downloading https://ghcr.io/v2/homebrew/core/media-info/manifests/21.09
        STDERR: Warning: Treating mediainfo as a formula. For the cask, use homebrew/cask/mediainfo
        curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
        Error: media-info: Failed to download resource "media-info_bottle_manifest"
        Download failed: https://ghcr.io/v2/homebrew/core/media-info/manifests/21.09
        ---- End output of ["brew", "install", "mediainfo"] ----
        Ran ["brew", "install", "mediainfo"] returned 1
        [2021-12-27T08:44:18+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
        +(./bootstrap-scripts/bootstrap.sh:299): errorout 'Soloist provisioning failed!'
        ERROR: Soloist provisioning failed!

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
Current runner version: '2.285.1'
Operating System
  macOS
  11.6.2
  20G314
Virtual Environment
  Environment: macos-11
  Version: 20211219.1
  Included Software: https://github.com/actions/virtual-environments/blob/macOS-11/20211219.1/images/macos/macos-11-Readme.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/macOS-11%2F20211219.1
Virtual Environment Provisioner
  1.0.0.0-main-20211214-1
```

### Is it regression?

_🤷_

### Expected behavior

- Networking should operate fully on the GitHub Actions runner node
- Jobs should be reliable... For example:
  - After merging to a staging branch, a job should complete successfully in a no-op merge to master pull request
  - Re-launching the same job on the same `git` commit should be deterministically reliable

### Actual behavior

- Networking is not reliable
- Jobs fail unpredictably at different points during dependencies download steps

### Repro steps

1. Start with a known successful workflow that has many dependencies to download
  - Example: Ruby Gems, `git` repo cloning, Chef Cookbooks, Homebrew packages, etc...
2. Launch the same workflow during different times of the day
  - Hypothesis: If GitHub Actions bandwidth / network hardware is under high network load, it will be more probable to fail
3. Watch for networking related failure messages in the logs

**Comment by miketimofeev** [comment] 2021-12-27 08:31
Possibly related to the https://github.com/actions/virtual-environments/issues/4807#issuecomment-1001418792 as ruby and homebrew packages are hosted in GitHub.

**Comment by asenyaev** [comment] 2021-12-27 09:17
@miketimofeev, looks like it affects all platforms. I face the same issue on [`ubuntu-latest`](https://github.com/opencv/opencv-python/runs/4640548644?check_suite_focus=true#step:5:20), [`windows-latest`](https://github.com/opencv/opencv-python/runs/4640531783?check_suite_focus=true#step:6:303), [`macos-10.15`](https://github.com/opencv/opencv-python/runs/4640708049?check_suite_focus=true#step:2:778) and [`macos-11`](https://github.com/opencv/opencv-python/runs/4640157263?check_suite_focus=true#step:2:556). 

The fails can be as a ssl problem, a timeout calling github API or a downloading some components from open resources.

**Comment by littledivy** [comment] 2021-12-27 11:44
Facing similar issues on all platforms. Here's an example: https://github.com/denoland/rusty_v8/runs/4639678330?check_suite_focus=true#step:3:588
Usually fails at `actions/checkout` when cloning large repositories from Chromium or V8

**Comment by asenyaev** [comment] 2021-12-27 12:48
Update: Finally, my workflows are passed on macOS-10.15 and macOS-11 w/o any issues.

**Comment by miketimofeev** [comment] 2021-12-27 13:23
closing this as a duplicate of https://github.com/actions/virtual-environments/issues/4807

**Closed by miketimofeev** 2021-12-27 13:23 UTC
Labels: external
