### ISSUE TITLE
Hang on snap install

### ISSUE THREAD

**Issue by lechen26** [actions/virtual-environments#998] opened 2020-06-03 14:28 UTC
Hi
we are using ubuntu-18.04 version 20200525.2
during our workflow we use snap to install bump tool "sudo snap install -y bump".
it worked before, but in the last hour this command just hang and nothin happens.
it doesnt seems there is a change on the snapd version installed (2.42.1+18.04), and no new version for bump (still same old  0.0.5 version).
is there any other issue on the runner which can cause this issue?

thanks
Chen

**Comment by andy-mishechkin** [comment] 2020-06-04 07:01
Hello!
Would you please provide some links to your workflow where you've got this issue, or some more information.
We have no known issues, which can cause this.

**Comment by maxim-lobanov** [comment] 2020-06-04 17:37
Unfortunately, we can't reproduce it from our side. Command `sudo snap install bump` works as expected.
It would be great if you can provide some public link to repro.

**Comment by lechen26** [comment] 2020-06-07 07:38
Hi

thanks.
i cannot provide a public link but i've attached screenshot from the failure.
you can see its at the beginning of the workflow, we just used to install the bump package and that day this command just hang (we cancled it after 11 min).

![image](https://user-images.githubusercontent.com/7347506/83962941-89eae200-a8aa-11ea-8a5e-cbbf327a1d9d.png)

it started to work again after a day, but as it blocked all our workflows i've decided to ditch this tool and use our own one.

thanks

**Comment by dibir-magomedsaygitov** [comment] 2020-06-08 14:14
Thank you @lechen26.
I'm closing this issue. If you will have any concerns feel free to contact us.

**Closed by dibir-magomedsaygitov** 2020-06-08 14:14 UTC
Labels: OS: Ubuntu, investigate

**Comment by salimkayabasi** [comment] 2020-12-03 09:03
It is still hanging with very basic workflow. You can find the logs of my execution (396228146)

<details>
<summary>Workflow</summary>

```yaml
name: Draw.io Compiler

on:
  push:
    paths:
      - '**/*.drawio'
env:
  DRAWIO_FILE: drawio.deb
  DRAWIO_VERSION: 13.9.9

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Instaling drawio
        timeout-minutes: 3
        run: |
          sudo snap install drawio
          drawio --help
```

</details>

<details>
<summary>Logs</summary>

```
2020-12-02T14:47:39.8101018Z ##[section]Starting: Request a runner to run this job
2020-12-02T14:47:39.8601867Z Can't find any online and idle self-hosted runner in current repository that matches the required labels: 'ubuntu-latest'
2020-12-02T14:47:39.9284251Z Can't find any online and idle self-hosted runner in current repository's organization account that matches the required labels: 'ubuntu-latest'
2020-12-02T14:47:40.0578661Z Found online and idle hosted runner in current repository's organization account that matches the required labels: 'ubuntu-latest'
2020-12-02T14:47:40.1989991Z ##[section]Finishing: Request a runner to run this job
2020-12-02T14:47:48.9779138Z Current runner version: '2.274.2'
2020-12-02T14:47:48.9808944Z ##[group]Operating System
2020-12-02T14:47:48.9810178Z Ubuntu
2020-12-02T14:47:48.9810712Z 18.04.5
2020-12-02T14:47:48.9811173Z LTS
2020-12-02T14:47:48.9811729Z ##[endgroup]
2020-12-02T14:47:48.9812334Z ##[group]Virtual Environment
2020-12-02T14:47:48.9813069Z Environment: ubuntu-18.04
2020-12-02T14:47:48.9813726Z Version: 20201129.1
2020-12-02T14:47:48.9814843Z Included Software: https://github.com/actions/virtual-environments/blob/ubuntu18/20201129.1/images/linux/Ubuntu1804-README.md
2020-12-02T14:47:48.9815988Z ##[endgroup]
2020-12-02T14:47:48.9819396Z Prepare workflow directory
2020-12-02T14:47:49.0679425Z Prepare all required actions
2020-12-02T14:47:49.0692345Z Getting action download info
2020-12-02T14:47:50.9770775Z Download action repository 'actions/checkout@v2.3.4'
2020-12-02T14:47:51.6133575Z Download action repository 'peter-evans/create-pull-request@v3.5.1'
2020-12-02T14:47:56.1174043Z ##[group]Run sudo snap install drawio
2020-12-02T14:47:56.1174782Z [36;1msudo snap install drawio[0m
2020-12-02T14:47:56.1175276Z [36;1mdrawio --help[0m
2020-12-02T14:47:56.1221773Z shell: /bin/bash -e {0}
2020-12-02T14:47:56.1222389Z env:
2020-12-02T14:47:56.1222825Z   DRAWIO_FILE: drawio.deb
2020-12-02T14:47:56.1223304Z   DRAWIO_VERSION: 13.9.9
2020-12-02T14:47:56.1223750Z ##[endgroup]
2020-12-02T14:48:08.8567255Z 2020-12-02T14:48:07Z INFO Waiting for automatic snapd restart...
2020-12-02T14:51:08.6122868Z ##[error]The action has timed out.
2020-12-02T14:51:08.6186944Z Cleaning up orphan processes
```

</details>

**Comment by maxim-lobanov** [comment] 2020-12-03 09:15
@salimkayabasi , thank you for provided logs. could you please create the new issue with this info?

**Comment by salimkayabasi** [comment] 2020-12-07 10:08
https://github.com/actions/virtual-environments/issues/2209
created thanks
