### ISSUE TITLE
D lang fails on link on Ubuntu latest

### ISSUE THREAD

**Issue by Shaac** [actions/virtual-environments#528] opened 2020-03-09 22:31 UTC
**Describe the bug**
The link phase of a very simple program written in D lang, with the `gdc` executable, fails.

It is not just a Ubuntu problem because Travis CI has no problem to link this with their bionic image.

**Area for Triage**: 
Packages

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**

The following code should link with `gdc`:

```d
import std.stdio : stdin, writeln;

void simple(int n, int otherNumber)
{
    writeln(n);
    writeln(otherNumber);
}

void main()
{
    int n;
    stdin.readf("%d\n", &n);
    int otherNumber;
    stdin.readf("%d\n", &otherNumber);

    simple(n, otherNumber);
}
```

**Actual behavior**

The code do not link.

I’ve made a minimal reproduction here: https://github.com/Shaac/test-ci-d/runs/495059988

The only occurence of this link error I found on internet is https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=933675

**Comment by al-cheb** [comment] 2020-03-10 10:55
Hello, @Shaac 
Could you please install gdc-7 or gdc-8?
gdc-7:
`sudo apt-get install -y gdc-7
`
gdc-9:
`sudo apt-get install -y gdc-9`

**Comment by Shaac** [comment] 2020-03-10 12:26
Hello,

I tried several versions on my test repo.

- [gdc default fails](https://github.com/Shaac/test-ci-d/actions/runs/52928561) ❌
- [gdc 7 works](https://github.com/Shaac/test-ci-d/actions/runs/52928581) ✅
- [gdc 8 fails](https://github.com/Shaac/test-ci-d/actions/runs/52928584) ❌
- [gdc 9 works](https://github.com/Shaac/test-ci-d/actions/runs/52928585) ✅

Since gdc default seems to be version 8, just one version seems to be broken. Sadly it is the default one.

I’ll install an other version for my own builds. This is a good workaround, but something is still broken on the image. Compiling and linking with bionic image from travis and vagrant works well.

**Comment by al-cheb** [comment] 2020-03-10 20:49
Workaround for default gdc:

```
name: CI

on: [push]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - name: remove packages
      run: |
          sudo apt remove gcc-8 g++-8 gcc-8-base -y	
          sudo apt autoremove -y
          sudo rm -rfv /etc/apt/sources.list.d/*
          sudo mv /etc/apt/sources.list /etc/apt/sources.list.BKP
          sudo bash -c "cat >> /etc/apt/sources.list" << EOF
          deb http://it.archive.ubuntu.com/ubuntu/ bionic main universe restricted multiverse
          deb-src http://it.archive.ubuntu.com/ubuntu/ bionic main universe restricted multiverse
          EOF
          sudo apt update
    - name: Install GDC
      run: |
          sudo apt-get install gdc
    - name: Get GDC version
      run: |
          gdc --version 
    - name: gdc
      run: |
          git clone https://github.com/Shaac/test-ci-d
          cd test-ci-d
          gdc simple.d

```

![Capture - Copy](https://user-images.githubusercontent.com/47745270/76358022-d36a7600-6329-11ea-8502-881f2ea62dad.JPG)

**Comment by Darleev** [comment] 2020-04-21 10:11
Hi @Shaac, let me describe current investigation details:
We found that two libraries `/usr/lib/x86_64-linux-gnu/libgdruntime.so.76` and `/usr/lib/x86_64-linux-gnu/libgphobos.so.76` affects gdc by the following way:
If gdc-9 installed with libgdruntime and libgphobos.so versions 8, the same issue as you reported repeats for gdc-9
If gdc-8 installed with libgdruntime and libgphobos.so versions 9, we got exact the same issue as in the topic.
Initial issue appears since version of mentioned libraries is 9, and installs since we have pre-installed gcc-9 in the system.
I guess, we have only one way how to properly fix the issue:
Install gdc-7,8,9 on Ubuntu images
Remove libraries link to make it work:
```
rm -v /usr/lib/x86_64-linux-gnu/libgdruntime.so.76
rm -v /usr/lib/x86_64-linux-gnu/libgphobos.so.76
```
I have verified the following workaround in runtime:
```
sudo apt install gdc
rm -v /usr/lib/x86_64-linux-gnu/libgdruntime.so.76
rm -v /usr/lib/x86_64-linux-gnu/libgphobos.so.76
```
and It work perfectly fine. I will prepare pull request for the issue and let you know.

**Comment by Darleev** [comment] 2020-04-21 11:07
The issue was additionally discussed internally, and it seems to be more related to a compatibility between gdc/gcc libraries than images build. The root cause is that different gcc and gdc libraries conflict to each others and we don't see the correct fix for that (except the workaround that we have provided above, but it can't be applied to image during image-generation because we don't pre-install gdc)
I'm going to close the issue. Please feel free to contact us.

**Closed by Darleev** 2020-04-21 11:07 UTC
Labels: OS: Ubuntu, bug
