### ISSUE TITLE
GitHub Actions has encountered an internal error when running your job.

### ISSUE THREAD

**Issue by alexlamsl** [actions/virtual-environments#3363] opened 2021-05-11 15:39 UTC
**Description**  
Since earlier today almost all macOS jobs started failing, and the incident (not shown on githubstatus.com) began without any changes committed to the repository. The following is a few examples:

Triggered by schedule:
https://github.com/mishoo/UglifyJS/actions/runs/830698643
https://github.com/mishoo/UglifyJS/actions/runs/830735540
https://github.com/mishoo/UglifyJS/actions/runs/830761990
https://github.com/mishoo/UglifyJS/actions/runs/830801330
https://github.com/mishoo/UglifyJS/actions/runs/830837479

Triggered by push:
https://github.com/mishoo/UglifyJS/actions/runs/831491203

**Area for Triage**:  
Deployment/Release

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
Current runner version: '2.278.0'

**Expected behavior**  
Jobs run.

**Actual behavior**  
Most jobs remained queued seemingly indefinitely, the ones which don't throw error as noted in title.

**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

1. watch scheduled workflow spawn
2. wait for the macOS job to fail while the rest runs

**Comment by alexlamsl** [comment] 2021-05-12 01:50
> Triggered by `schedule`:
> https://github.com/mishoo/UglifyJS/actions/runs/833578564

The 2nd attempt just started executing, which puts it ~90mins behind the rest of the workflow.

**Comment by alexlamsl** [comment] 2021-05-12 08:18
https://github.com/mishoo/UglifyJS/actions/runs/834180326

**Comment by miketimofeev** [comment] 2021-05-12 12:16
@alexlamsl sorry for the inconvenience. We're investigating this at the moment

**Comment by miketimofeev** [comment] 2021-05-13 13:33
@alexlamsl quick update — we've identified the root cause. The issue should be resolved next week.

**Comment by alexlamsl** [comment] 2021-05-13 13:50
Thanks for the effort &minus; much appreciated.

**Comment by alexlamsl** [comment] 2021-05-17 14:31
Looks like macOS jobs are stalling again...
https://github.com/mishoo/UglifyJS/actions/runs/849980452
https://github.com/mishoo/UglifyJS/actions/runs/850008747
https://github.com/mishoo/UglifyJS/actions/runs/850077342

**Comment by alexlamsl** [comment] 2021-05-19 21:09
This one is triggered by Pull Request, and is reported as "skipped" after seemingly running for a while:
https://github.com/mishoo/UglifyJS/runs/2623465438?check_suite_focus=true

**Comment by alexlamsl** [comment] 2021-05-26 11:30
One fresh & stalling `macos` job by `schedule` trigger:
https://github.com/mishoo/UglifyJS/actions/runs/878295584

**Comment by alexlamsl** [comment] 2021-05-26 14:57
I guess after 30mins of queuing they will start to err...
https://github.com/mishoo/UglifyJS/actions/runs/878552676

**Comment by alexlamsl** [comment] 2021-06-01 16:40
Now getting macOS jobs with missing logs, sometimes accompanying with:
> `An error occurred while provisioning resources (Error Type: Disconnect).`

https://github.com/mishoo/UglifyJS/actions/runs/895267624
https://github.com/mishoo/UglifyJS/actions/runs/895962536
https://github.com/mishoo/UglifyJS/actions/runs/896482876

**Comment by miketimofeev** [comment] 2021-06-02 13:48
@alexlamsl these disconnects look like a different issue, actually because the run was started successfully, but then something went wrong. Is the job CPU-consuming? I wonder if we have any underlying infrastructure issues related to significant resource usage.

**Comment by alexlamsl** [comment] 2021-06-02 14:32
I see &minus; thanks for clarifying.

> Is the job CPU-consuming?

They generate & test random code snippets continuously, so I'd expect them to be CPU-intensive.

**Comment by miketimofeev** [comment] 2021-06-02 15:04
@alexlamsl do you mind create another issue for that with the reproduce steps? We will try to reproduce the problem and provide all the data to the engineering team.

**Comment by alexlamsl** [comment] 2021-06-02 16:48
Filed as #3517

**Comment by miketimofeev** [comment] 2021-06-02 16:53
@alexlamsl thanks! I'm going to close this one since the new issue seems to be of a different kind.

**Closed by miketimofeev** 2021-06-02 16:53 UTC
Labels: OS: macOS, investigate
