### ISSUE TITLE
Issue in executing long running task on a remote server from runner

### ISSUE THREAD

**Issue by ruchir1988** [actions/virtual-environments#3592] opened 2021-06-16 10:02 UTC
I have a requirement of running some task on a freebsd machine as a part of CI. 
As we don't have support for a freebsd-runner on github action right now,

I am working around it via doing ssh from a ubuntu runner to freebsd server and running task. 

I faced a challenge in github step, which takes long time to execute on a remote freebsd server (12.2).
 
We found, when ubuntu runner, ssh into freebsd build machine and invoke a long running task,  github action never exit, on the  completion of task on remote freebsd machine. 

For example, below github step hungs forever in github action.

```
    - name: ssh into build machine and run script
        run: |
           sh scripts/test.sh
```

test.sh is simply doing below .i.e. it ssh into freebsd 12.2 machine and run below command
  
`ssh -o StrictHostKeyChecking=no -i .id_rsa root@xx.xxx.xxx.xxx "cd /root/testing && sleep 900"`

We do see that during the time its executing sleep there is ssh connection established from ubuntu runner .i.e.  

```
 netstat -p tcp | grep ssh
tcp4       0    268 xxx.xx.xx.xxx.ssh     xx.xx.xxx.xx.1988     ESTABLISHED. (github runner)
tcp4       0     44 xx.xx.xx.xxx.ssh     xx.xx.xx.xx.50878   ESTABLISHED. (my phyical machine)
```

and when sleep finishes, we do see that ssh connection going away on freebsd machine, .i.e. 

```
netstat -p tcp | grep ssh (only connection from my physical machine visible )
tcp4       0     44 xxx.xx.xxx.xx.ssh     xx.xx.xxx.xx.50878   ESTABLISHED. (my physical machine)
```

however github action never realize that the, github step has been finished and its keep on going.
I have to manually cancel the build

**Comment by al-cheb** [comment] 2021-06-17 06:48
Hello, @ruchir1988 
Thank you for your report. We will take a look.

**Comment by al-cheb** [comment] 2021-06-17 09:33
Hello, @ruchir1988 

I am not able to reproduce the issue.  I'm going to close the issue since it's not related to the virtual-environments images.

Pipeline:
```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
         - uses: actions/checkout@v2
         - run: chmod 600 freebsd01_key.pem
         - run: sh script.sh
```
script.sh:
`ssh -o StrictHostKeyChecking=no -i freebsd01_key.pem azureuser@13.79.231.133 "cd ~/testing && id && uname -a && sleep 900 && echo Done"`

Output:
![image](https://user-images.githubusercontent.com/47745270/122370811-0d341e80-cf68-11eb-8079-7328ca09c75d.png)

**Closed by al-cheb** 2021-06-17 09:33 UTC
Labels: external

**Comment by ruchir1988** [comment] 2021-06-17 11:21
@al-cheb : Thank you for trying to replicate this issue.

however not sure what is the issue here , I tried the command you have above for me it still hangs

![image](https://user-images.githubusercontent.com/75368485/122386951-00c1bd00-cf8c-11eb-8f4d-f69d3f563441.png)

**Comment by al-cheb** [comment] 2021-06-17 11:29
> @al-cheb : Thank you for trying to replicate this issue.
> 
> however not sure what is the issue here , I tried the command you have above for me it still hangs
> 
> ![image](https://user-images.githubusercontent.com/75368485/122386951-00c1bd00-cf8c-11eb-8f4d-f69d3f563441.png)

What is the output of the command?
`ssh -o StrictHostKeyChecking=no -i .id_rsa root@xx.xxx.xxx.xxx "cd /root/testing && sleep 5 && id && uname -a && echo Done"`

**Comment by ruchir1988** [comment] 2021-06-17 11:30
![image](https://user-images.githubusercontent.com/75368485/122388407-7a0ddf80-cf8d-11eb-986c-01f78df8fa7d.png)

**Comment by al-cheb** [comment] 2021-06-17 11:32
@ruchir1988, Why do you provide output of the difference scripts?

**Comment by ruchir1988** [comment] 2021-06-17 11:38
@al-cheb above screen shot is of cancelled build , now I am running below command in compress-usr.sh
`ssh -o StrictHostKeyChecking=no -i .id_rsa root@xx.xxx.xxx.xxx "cd /root/testing && sleep 5 && id && uname -a && echo Done`


whose output is 

![image](https://user-images.githubusercontent.com/75368485/122389420-8c3c4d80-cf8e-11eb-8f24-1bad104ab0e0.png)
