### ISSUE TITLE
azure-pipelines-tasks Docker V1 doesn't work as expected using the pre-release ubuntu1604/20210208.0

### ISSUE THREAD

**Issue by jblafage** [actions/virtual-environments#2686] opened 2021-02-11 13:25 UTC
**Description**  
Using an hosted agent based on latest pre-release ubuntu1604/20210208.0, the native Docker task (version 1) available in 
[azure-pipelines-tasks](https://github.com/microsoft/azure-pipelines-tasks) does not push specific tags into an Azure Container Registry except the latest tag.

**Area for Triage**:  Containers

**Question, Bug, or Feature?**:  Bug

**Virtual environments affected**  
- [X] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
Environment: ubuntu-16.04
Version: 20210208.0

**Expected behavior**  
Docker build task is used to build Docker image and set several tags like latest and the build number of the pipeline (eg: 20210211.1). Docker push task should push all the tags into the target container registry.

**Actual behavior**  
Only latest tag is taken into account.

**Repro steps**  

1. Use docker build task (V1) and define a specific tag and latest tag
2. Use docker push task (V1) to push your image into an Azure Container Registry
3. Check if all the tags are available on Azure Container Registry

**Comment by dibir-magomedsaygitov** [comment] 2021-02-11 14:05
Hello @jblafage. Thank you for your report. I have a couple questions:
1) Did this task work as expected until today?
2) If yes, could you please provide us task version of last successful and first failed and image version of last successful and first failed.

**Comment by jblafage** [comment] 2021-02-11 14:23
Hello,

We encounter this strange behavior since yesterday. On our side, nothing has changed about how we use this task (we have defined a YAML template that we use in our different projects).

I have an example with a pipeline that has been executed today. For this pipeline I have 2 jobs:
* 1 job to build API application component and push docker image into an Azure Container Registry
* 1 job to build Frontend application component and push docker image into the same Azure Container Registry

For both jobs, Docker tasks are configured by the same way. But it work as expected only for job running for API component.

# Hosted agent information

## Job running for API component

* Environment: **ubuntu-16.04**
* Version: **20210131.1** (this is the latest [release](https://github.com/actions/virtual-environments/tree/ubuntu16/20210131.1) image)
* Agent version: 2.181.2

## Job running for Frontend component

* Environment: **ubuntu-16.04**
* Version: **20210208.0** (this is the current [pre-release](https://github.com/actions/virtual-environments/tree/ubuntu16/20210208.0) image)
* Agent version: 2.181.2

We have several applications using the same template and for which we have the same behavior. Each time, the issue happens when the job run with an agent based on the latest pre-release image (20210208.0). This is the only difference I can observe.

**Comment by maxim-lobanov** [comment] 2021-02-11 14:29
@jblafage , could you please also check task version for both successful and failed builds?
![image](https://user-images.githubusercontent.com/16715858/107649558-a12a6c80-6c8e-11eb-9030-d6b48ca52892.png)

**Comment by jblafage** [comment] 2021-02-11 14:46
I confirm, this is the same Docker task version used for both.
The task will finish without errors in both cases. 

From the task logs, we can see a log about the digest that correspond to the tag of the image (build number in our case) when job is running with agent 20210131.1 version. With the pre-release digest line from logs doesn't appear (except for the latest tag).

Logs when it works as expected:
```diff
80b5239588f1: Preparing
579a8f1d6a12: Preparing
15e45d99c926: Preparing
0cf75cb98eb2: Preparing
814c70fdae62: Preparing
15e45d99c926: Waiting
0cf75cb98eb2: Waiting
814c70fdae62: Waiting
579a8f1d6a12: Layer already exists
15e45d99c926: Layer already exists
0cf75cb98eb2: Layer already exists
eb4c50103a21: Pushed
814c70fdae62: Layer already exists
be94b7a694da: Pushed
8c731c90820f: Pushed
80b5239588f1: Pushed
+ 20210211.2: digest: sha256:82f6a8d917a02a713a79e5e7f49c888807e3702fd07da65da6f5fb1efaacf422 size: 2004
8c731c90820f: Preparing
eb4c50103a21: Preparing
be94b7a694da: Preparing
80b5239588f1: Preparing
579a8f1d6a12: Preparing
15e45d99c926: Preparing
0cf75cb98eb2: Preparing
814c70fdae62: Preparing
be94b7a694da: Layer already exists
80b5239588f1: Layer already exists
579a8f1d6a12: Layer already exists
15e45d99c926: Waiting
0cf75cb98eb2: Waiting
814c70fdae62: Waiting
15e45d99c926: Layer already exists
0cf75cb98eb2: Layer already exists
814c70fdae62: Layer already exists
8c731c90820f: Layer already exists
eb4c50103a21: Layer already exists
latest: digest: sha256:82f6a8d917a02a713a79e5e7f49c888807e3702fd07da65da6f5fb1efaacf422 size: 2004
Finishing: Push Docker image: kdm-ng-api
``` 

Logs when tag is missing on ACR:
```text
The push refers to repository [acrdevkdmng001.azurecr.io/kdm-ng-web]
e6a56c4e7d32: Preparing
e91f318be727: Preparing
f318a20de14e: Preparing
c86a71df3449: Preparing
033b1bd7e320: Preparing
2a31345abb21: Preparing
7ff6d3516ea0: Preparing
f1b5933fe4b5: Preparing
2a31345abb21: Waiting
7ff6d3516ea0: Waiting
f1b5933fe4b5: Waiting
f318a20de14e: Pushed
e91f318be727: Pushed
c86a71df3449: Pushed
7ff6d3516ea0: Layer already exists
e6a56c4e7d32: Pushed
033b1bd7e320: Pushed
2a31345abb21: Layer already exists
f1b5933fe4b5: Layer already exists
latest: digest: sha256:5e0828238b4431f71f0f85e16c9052318ef5c90e799e39a37a0a0896b00b334e size: 1996
Finishing: Push Docker image: kdm-ng-web
```

**Comment by dibir-magomedsaygitov** [comment] 2021-02-11 15:21
@jblafage Thank you for the information. Could you please try run these commands before using Docker task:
```
sudo apt-get remove -y moby-engine moby-cli
sudo apt-get update
sudo apt-get install -y moby-engine=19.03.14+azure-1 moby-cli
apt-get install --no-install-recommends -y moby-buildx
```

**Comment by jblafage** [comment] 2021-02-11 15:50
I have added a bash step before Docker steps:
```yaml
 bash: |
   sudo apt-get remove -y moby-engine moby-cli
   sudo apt-get update
   sudo apt-get install -y moby-engine=19.03.14+azure-1 moby-cli
   sudo apt-get install --no-install-recommends -y moby-buildx
 displayName: 'Reinstall moby-engine'
```

But there is no change. Tag with build number is not pushed into the ACR (job used enviroment version **20210208.0**)

**Comment by jblafage** [comment] 2021-02-11 15:52
In addition, I have tested to run the job with hosted agents:
* ubuntu-16.04
* ubuntu-18.04
* ubuntu-20.04
All of them are using the corresponding environment version **20210208.0** and we have the same result: tag with build number is not pushed into ACR.

**Comment by anatolybolshakov** [comment] 2021-02-11 17:05
Hi @jblafage could you please share pipeline logs for successful and failed runs with system.debug option enabled ('Enable system diagnostics')? You can send it to us by email, here's mine - v-anbols@microsoft.com

**Comment by jblafage** [comment] 2021-02-11 19:35
@anatolybolshakov , I sent to your mail address pipeline logs for failed run. Unfortunately, I'm not able to reproduce a successful job as all new jobs run with environment version 20210208.0.

**Comment by dibir-magomedsaygitov** [comment] 2021-02-11 21:35
@jblafage could you please try this bash step one more time:
```
 bash: |
   sudo apt-get remove -y moby-engine moby-cli
   sudo apt-get update
   sudo apt-get install -y moby-engine=19.03.14+azure-1 moby-cli=19.03.14+azure-1
   sudo apt-get install --no-install-recommends -y moby-buildx
 displayName: 'Reinstall moby-engine'
```
Seem like new version of `moby-cli` is the root cause of this issue.

**Comment by Chili-Man** [comment] 2021-02-12 01:12
I can confirm that the new version of `moby-cli`  in 20210208.0 is causing the issue; downgrading it to version `19.03.14+azure-1` fixes it for me.

**Comment by Chili-Man** [comment] 2021-02-12 04:44
See https://github.com/actions/virtual-environments/issues/2691#issuecomment-777911076 for the root cause of the issue. There was a a breaking change in behavior for `docker push` in moby-cli 19.03.15+azure-1 which should have only been present on moby-cli version 20.10+ ;  to get the previous behavior, you need to add the `--all-tags` flag

**Comment by jblafage** [comment] 2021-02-12 08:10
> @jblafage could you please try this bash step one more time:
> 
> ```
>  bash: |
>    sudo apt-get remove -y moby-engine moby-cli
>    sudo apt-get update
>    sudo apt-get install -y moby-engine=19.03.14+azure-1 moby-cli=19.03.14+azure-1
>    sudo apt-get install --no-install-recommends -y moby-buildx
>  displayName: 'Reinstall moby-engine'
> ```
> 
> Seem like new version of `moby-cli` is the root cause of this issue.

I confirm, it works as expected when we downgrade `moby-cli` to version `19.03.14+azure-1`.

**Comment by dibir-magomedsaygitov** [comment] 2021-02-15 11:05
Hello @jblafage. I'm going to close this issue since it's not related to the images. You can either downgrade `mobi-cli` or use `--all-tags` flag in order to `Docker push` task be able to push all the tags into the target container registry.
In case of any questions feel free to reopen this issue. Thank you.

**Closed by dibir-magomedsaygitov** 2021-02-15 11:05 UTC
Labels: Area: Containers, OS: Ubuntu, investigate
