### ISSUE TITLE
brew upgrade fails on gcc

### ISSUE THREAD

**Issue by ivg** [actions/virtual-environments#2391] opened 2021-01-05 22:23 UTC
**Description**  

issuing `brew update; brew upgrade` fails with an error on `brew link`. It is a close relative of #2322  and it prevents us from using brew as we have to perform an upgrade (otherwise other packages become uninstallable) since the base image brew state diverges from the upstream brew specification. We see such errors quite commonly on various packages. 

**Area for Triage**:  

Apple

**Question, Bug, or Feature?**:  

Yes :)

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
  
A successful upgrade.

**Actual behavior**  

A failure.

**Repro steps**  
1. The [workflow file][1]
2. the [action log][2]

[1]: https://github.com/BinaryAnalysisPlatform/bap/blob/master/.github/workflows/build-dev-repo.yml
[2]: https://github.com/BinaryAnalysisPlatform/bap/pull/1263/checks?check_run_id=1652776599

Here is the relative excerpt for your convenience

```
...
=> Upgrading gcc@9 9.3.0 -> 9.3.0_1 
==> Downloading https://homebrew.bintray.com/bottles/gcc%409-9.3.0_1.catalina.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/9da2446533167ddef1c7ca78d132908d6c2a2d808c7f1569a7852db6fa21b00a?response-content-disposition=attachment%3Bfilename%3D%22gcc%409-9.3.0_1.catalina.bottle.tar.gz%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvOWRhMjQ0NjUzMzE2N2RkZWYxYzdjYTc4ZDEzMjkwOGQ2YzJhMmQ4MDhjN2YxNTY5YTc4NTJkYjZmYTIxYjAwYT9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMmdjYyU0MDktOS4zLjBfMS5jYXRhbGluYS5ib3R0bGUudGFyLmd6JTIyIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjA5ODg0MTYxfSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjAuMC4wLjAvMCJ9fX1dfQ__&Signature=Jk14mLDTQkJZH2jt2-n4QrKaF8ixOeB7iPlguaBzK-ld6SO7aQ0olELNP9V~rhzh8govz2lHjOWvFr99OXXXXRFu1Y~aJLF4BdfVXOLNFxnsvtK6ZEnoMOkb~uuyO5xDXJAHocrqeWyYlknhLGCsFSTIQYp070vp6PLwm2ccPvNNoDpe2F8Qiqo5nHsXmehfmeiAc~U~sdhH3mcXYPavKsj9YdlZ7~aunLLARIEEgLtbLQQp5UlEC8GDL3TSFms9IJeUr0rl6c4wmU4YTW~sm7xmW-FoY66lSC5BAUXFDLiOhOHCPJeIZBhcjUty5J5X94TvImkGDqmnKAPSY5w62w__&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA
==> Pouring gcc@9-9.3.0_1.catalina.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/c++-9
Target /usr/local/bin/c++-9
is a symlink belonging to gcc@9. You can unlink it:
  brew unlink gcc@9

To force the link and overwrite all conflicting files:
  brew link --overwrite gcc@9

To list all files that would be deleted:
  brew link --overwrite --dry-run gcc@9
...
```

**Comment by andy-mishechkin** [comment] 2021-01-06 13:47
Hello, @ivg
It looks like gcc formula has some breaking changes. For quick fixing you can use
```
brew unlink gcc@8
brew unlink gcc@9
```
at the beginning of `Configure Homebrew LLVM` task.
Now we are continue to investigate this issue.
Thank you.

**Comment by andy-mishechkin** [comment] 2021-01-12 13:49
Hello, @ivg 
We've reproduced this situation on clear MacOS 10.15 VM and also have got the same issue.
We've open the bug in homebrew-core: https://github.com/Homebrew/homebrew-core/issues/68866

**Comment by andy-mishechkin** [comment] 2021-01-15 14:16
Hello. @ivg 
According to https://github.com/Homebrew/homebrew-core/issues/68866, homebrew-core team has fixed this issue.
I've tested you workflow code on my fork - all works fine.
I think - we can close this ticket. 
If you'll find some issues again - feel free to reopen.

**Closed by andy-mishechkin** 2021-01-15 14:16 UTC
Labels: Area: Apple, OS: macOS, investigate

**Comment by ivg** [comment] 2021-01-15 16:18
thank you, guys!
