### ISSUE TITLE
Java CI - build with Maven, tests failing on Windows 2019 version 20210719.0

### ISSUE THREAD

**Issue by balfonso** [actions/virtual-environments#4107] opened 2021-09-17 12:00 UTC
### Description

Our tests that rely on native libraries have suddenly started fail. We have noticed that the problem started after the virtual environment update. We could run with version 20210711.1 without problem, but with version 20210719.0 we can run only if we skip the tests. 

On our local machines everything works well when running with test, as it was before.

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20210719.0

### Is it regression?

no

### Expected behavior

We need to run script with tests. The last successful run was with VM version 20210711.1.

### Actual behavior

We can not run the same script with tests on lates VM version 20210719.

### Repro steps

![Screen Shot 2021-09-17 at 13 59 17](https://user-images.githubusercontent.com/22661942/133779256-4ca510be-243a-4e49-9e13-a64ae21ae5d1.png)

**Comment by Darleev** [comment] 2021-09-17 12:33
Hello @balfonso,
The current version of the Windows image is 20210907.4. Could you please try to run your test on the latest image build? IT would be great if you provide steps to reproduce the issue or sample repository.
We're looking forward to your reply.

**Comment by balfonso** [comment] 2021-09-20 10:53
Hi, the problem persists even with a newer version, we tested with version 20210914.2. My colleague will provide additional comment with the steps and sample repository.

![thumbnail_image_java_ci_maven](https://user-images.githubusercontent.com/22661942/133990270-e36072cf-1ee3-4d7b-a8ce-b77541a0255f.png)

**Comment by DiachenkoD** [comment] 2021-09-21 10:07
Good afternoon!
Unfortunatelly we can’t share the code examples according to NDA. The build fails on the using some native methods from the *.dll libs. We will try to make an standalone project to provide you with more information.

**Comment by DiachenkoD** [comment] 2021-09-21 22:22
Could we get the log file from the build path?

**Comment by miketimofeev** [comment] 2021-09-27 07:52
Hi @DiachenkoD! Do you have any progress with standalone project preparation? Unfortunately, we can't help your team without a proper reproducible example

**Comment by MaksimZhukov** [comment] 2021-10-06 15:44
Hello @DiachenkoD! 
Please provide us with steps to reproduce the issue or a sample repository for further investigation.
Thanks!

**Comment by DiachenkoD** [comment] 2021-11-30 08:49
Good afternoon @MaksimZhukov !
Sorry for the delay, the issue was postponed due to others tasks.
I have created the public repo, which works on my pc build but fails on the git workflow. 
Please see the attached link. This repo contains a very simple maven project with the one test method calling the native library.
The project is independent of any IDE which you prefer to use, so feel free to install it and run `clean install` manually to see the result of  the building, 
https://github.com/DiachenkoD/TestScriptProject.git

One suggestion is in the installation time on the server, it uses the incorrect method names for the native library.

**Comment by V-Zabayrachny** [comment] 2021-12-02 10:38
Hello @DiachenkoD!
We have looked through example you provided, given that your logs contain the `The forked VM terminated without properly saying goodbye. VM crash or System.exit called?` error it looks like this is purely related to the `maven-surefire-plugin` and its settings, have you tried to give it more granular options? The error is related to forking, have you tried playing with the `forkCount` option in your `pom.xml` file? Apart from that, we have compared the changelogs between the two image versions you provided, there were no considerable java-related changes during that time span.

**Comment by DiachenkoD** [comment] 2021-12-02 11:13
Good afternoon @V-Zabayrachny !
We have been trying to play with the forking before create the first request to you. The question still is the reason why this native libraries work on our machines with no errors. The poms haven’t been changed for years, but such kind of error is fresh one. 
Did you try to build this project on your own machine to ensure that there is no bug in this case?
Native libraries are very sensefull to the request path inside the `ClassLoader` and inside the debug of the workflow I see such kind of problem:
![image](https://user-images.githubusercontent.com/17337633/144411158-e9f4c52b-bdaf-4e31-a2f7-9b23dfab6ca1.png)

Usually it relates to the `UnsatisfiedLinkError`. In the case presented above, we can see the message body which says that the library is found, but the current pass is incorrect for it. The message starts with `j `, I am not sure what is it related to, can only suppose that problem could be somewhere there.

**Comment by V-Zabayrachny** [comment] 2021-12-06 06:34
@DiachenkoD We tried to reproduce the build locally, but it didn't work out. After reviewing the event log, we noticed that the error occurs at the time of calling "klu.solvecomplex". Library KLU.dll it is a third-party library, so we can assume that the problem is related to the work of the library itself. We performed an another check of the workability of tests using "maven" on other projects, it showed that everything works as expected in our images.

**Comment by DiachenkoD** [comment] 2021-12-06 09:38
Hi @V-Zabayrachny!
Locally it works. There is the question. The library contains the methods which path should be exactly repeated by loader on the runtime. So locally it returns the correct path and everything is okay, but on workflow, as I suppose, the path is broken somehow. The interesting part is that it works perfect couple of month ago

**Comment by V-Zabayrachny** [comment] 2021-12-09 11:45
Hello @DiachenkoD!
We have deployed a clean VM with Windows Server 2019 Datacenter (OS build 17363.2300) in Azure. Installed java (openjdk version "1.8.0_312") versions there and added maven (version 3.8.4):
![ява вывод](https://user-images.githubusercontent.com/79155496/145387427-1a5ce346-9001-448f-898f-5fd576980adb.png)
We have cloned the project you provided from [your repository](https://github.com/DiachenkoD/TestScriptProject.git).
To build, we used the commands `mvn clean install` and `mvn -X clean install`, by running them in the project directory «TestScriptProject».
But we also get this error: [hs_err_pid1452.txt](https://github.com/actions/virtual-environments/files/7684726/hs_err_pid1452.txt)
![вывод ошибки](https://user-images.githubusercontent.com/79155496/145389225-78add74a-82d1-4495-832f-7f5521ce99bb.png)
Could you provide the exact java version (including build number) and java vendor (AdoptOpenJDK, OpenJDK, Oracle JDK, etc) you use?
Could you try deploying windows server VM in azure and debug your code there as I'm afraid we don't have experience for such debugging?

**Comment by V-Zabayrachny** [comment] 2021-12-16 12:52
Hello @DiachenkoD. I'm going to close the issue, but feel free to contact us if you have any questions.

**Closed by V-Zabayrachny** 2021-12-16 12:52 UTC
Labels: Area: Java, OS: Windows
