### ISSUE TITLE
OpenSSL link doesn't point to OpenSSL deployment

### ISSUE THREAD

**Issue by Nir-Az** [actions/virtual-environments#4719] opened 2021-12-12 09:30 UTC
### Description

Hi,

I wanted to report that we find it very difficult to keep up with github actions environments updates.

1. Every few month we find our builds failing due to OpenSSL deployment changes (It happened 3 times at the last year)
Last time I used  a generic way to be agnostic to GHA deployment changes using export "OPENSSL_ROOT_DIR=`readlink /usr/local/opt/openssl`  "
Now this doesn't work also..
2. Deprecation on environment, Windows-2016 for example will be deprecated, I wanted to switch to Windows-2019 but it didn't have VS2015/VS2017 on it

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20211207.1

### Is it regression?

Yes

### Expected behavior

OPENSSL_ROOT_DIR=`readlink /usr/local/opt/openssl`  find & set OpenSSL (previously was at 
`Found OpenSSL: /usr/local/Cellar/openssl@1.1)`

### Actual behavior

 Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_INCLUDE_DIR)

### Repro steps

Use this command and verify OpenSSL location
OPENSSL_ROOT_DIR=`readlink /usr/local/opt/openssl`

**Comment by nikolai-frolov** [comment] 2021-12-13 06:55
Hello @Nir-Az. Thanks for reporting, we'll take care about the issue investigation.

**Comment by dibir-magomedsaygitov** [comment] 2021-12-17 12:19
Hello @Nir-Az. I've tried to reproduce the issue but it looks like `readlink /usr/local/opt/openssl` working as expected. Could you please confirm?
![1](https://user-images.githubusercontent.com/61747324/146543207-dcf1c101-7e77-426a-a384-dbae05cb3c31.jpg)

**Comment by Nir-Az** [comment] 2021-12-17 14:25
That's exactly the issue.
Before the update the readlink command returned the **absolute** path to openssl1.1
Now it return a **relative** path to openssl3

This change broke our CI .
We managed to fix it but note that openssl link 2as changed 3 times this year which cause a regression each time..

**Comment by dibir-magomedsaygitov** [comment] 2021-12-17 14:46
@Nir-Az thank you for the provided information. Looks like during `powershell.sh` `openssl1.1` is being redefined by `openssl3.*`. I'll take a closer look.

**Comment by jdogmcsteezy** [comment] 2021-12-20 20:09
Also affects our mac 10.15 build.  Thanks, @Nir-Az for reporting the issue and thank you @dibir-magomedsaygitov for the fix

**Comment by dibir-magomedsaygitov** [comment] 2021-12-22 07:53
Hello @jdogmcsteezy @Nir-Az. We've merged PR with the fix. I'll notify you when the updated images are available to use.

**Comment by Nir-Az** [comment] 2021-12-22 07:54
@dibir-magomedsaygitov  Great, thanks

**Comment by jdogmcsteezy** [comment] 2021-12-22 20:29
@dibir-magomedsaygitov Thanks

**Closed** 2022-01-17 07:02 UTC
Labels: OS: macOS, Area: Common Tools, investigate
