### ISSUE TITLE
Add AWS CLI to windows-latest

### ISSUE THREAD

**Issue by ivansainz** [actions/virtual-environments#654] opened 2020-04-01 15:03 UTC
**Tool information**
- Tool name: AWS CLI
- Add or update? Add
- Desired version: 2
- Approximate size: 24 Mb
- If this is an add request:
  - Brief description of tool: Command line interface tools for AWS
  - URL for tool's homepage: https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-windows.html

**Area for Triage**:
Scripting and command line

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
No. It will need addition to the path.

**Are you willing to submit a PR?**
No

**Comment by maxim-lobanov** [comment] 2020-04-01 15:52
Hello!

This request is duplicate of #13 . AWS CLI was added to image recently. The new image will be deployed by the end of this week.

**Closed** 2020-04-02 08:39 UTC
Labels: enhancement
