### ISSUE TITLE
$PATH does not contain paths defined on /etc/environment

### ISSUE THREAD

**Issue by marcuslopes** [actions/virtual-environments#3695] opened 2021-07-07 20:25 UTC
### Description

When running a task inside a self-hosted Ubuntu build agent (either manual or automatic scaleset), running `echo $PATH` on a self hosted agent returns a very limited number of paths. 
Connecting to the agent via SSH and running `echo $PATH` directly will return the full range of paths inside the PATH variable though.

I am not sure if this can help in the troubleshooting, but I have noticed that even though my image was generated via this repo, there are comment lines and possibly extra config in MS-hosted agents in files like ~/.profile that are not present in my self-hosted agent. I wonder if there would be some extra configuration necessary that is done outside of the image generation scripts available in this repo.

Example of differences between my image's ~/.profile and the MS-hosted one: 
**self-hosted:** 
```
# ~/.profile: executed by Bourne-compatible login shells.

if [ "$BASH" ]; then
  if [ -f ~/.bashrc ]; then
    . ~/.bashrc
  fi
fi
```

mesg n || true

**MS-hosted:**
```
# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi
```

### Virtual environments affected

- [ ] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Image version and build link

**Ubuntu 18**
Image version: releases/ubuntu18/20210606 commit 58b026cedf2363aee66fcdde3981b09704d5bd79
Agent version: 2.187.2

**Ubuntu 20**
Image version: releases/ubuntu20/20210606 commit a26b241d4791b9af60f069b29c6e993595d75349
Agent version: 2.188.3

Packer: 1.6.2, 1.7.2

### Expected behavior

Running a shell script task `echo $PATH` on a self hosted Ubuntu agent should return all of the paths defined inside the /etc/environment file:

`PATH=/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$HOME/.local/bin:/opt/pipx_bin:/usr/share/rust/.cargo/bin:$HOME/.config/composer/vendor/bin:/usr/local/.ghcup/bin:$HOME/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
`

### Actual behavior

Running a shell script task `echo $PATH` on a self hosted Ubuntu agent returns a very limited number of paths:

`/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin`

If I perform the following steps, $PATH gets filled as expected though: 
1. Connect to the virtual machine
2. Open the agent folder `/opt/vsts/a1`
3. Run the following commands: 
```
./env.sh
sudo ./svc.sh stop
sudo ./svc.sh start
```

### Repro steps

1. Build a VM image using the Ubuntu image versions provided 
2. Create a virtual machine on a scaleset using the newly generated image (either manual or automatic scaleset via Azure DevOps)
3. (If manual scaleset only) , install a vsts agent on the virtual machine using a release from the vsts agent repo (https://github.com/microsoft/azure-pipelines-agent)
4. Create a new pipeline (ex.: YAML) and run script `echo $PATH`

**Comment by MaksimZhukov** [comment] 2021-07-08 12:47
Hello @marcuslopes! Thank you for your report. We will take a look

**Comment by MaksimZhukov** [comment] 2021-07-14 10:04
Hello @marcuslopes. Thank you for your patience!
It seems that the issue is most likely related to the Azure pipeline agent, since, as you mentioned, the `PATH` environment variable with correct value exists on the image and is accessible via SSH connection. The fact that your issue can be solved by running the `env.sh` script and restarting the service (`sudo ./svc.sh stop` `sudo ./svc.sh start`) may also indicate that the problem may be caused by the Azure pipeline agent or probably its incorrect initial configuration. 

Could you please create an issue in the [microsoft/azure-pipelines-agent](https://github.com/microsoft/azure-pipelines-agent) repository?

**Comment by marcuslopes** [comment] 2021-07-14 19:28
Thank you for your time Maksim. 
Following your advice, I created an issue in the azure-pipelines-agent: https://github.com/microsoft/azure-pipelines-agent/issues/3461

**Comment by MaksimZhukov** [comment] 2021-07-15 07:45
Thank you!
I'm going to close the issue, but feel free to contact us if you have any questions.

**Closed by MaksimZhukov** 2021-07-15 07:45 UTC
Labels: Area: Image administration, OS: Ubuntu, investigate

**Comment by ChristopheLav** [comment] 2021-08-06 00:28
We continue to investigate with Marcus and we found that we have more than one issue. The PATH is not correct because `$HOME` was not replaced because we miss to execute the post generation scripts like [documented here](https://github.com/actions/virtual-environments/blob/main/docs/create-image-and-azure-resources.md#post-generation-scripts)). So, we setup an VMSS extension to do the job when a VM instance is started.

The main issue remain but we think this can be useful for others :)

**Comment by ChristopheLav** [comment] 2021-10-01 11:06
Hi @MaksimZhukov, can you jump into the discussion here https://github.com/microsoft/azure-pipelines-agent/issues/3461 and help us? Thank you!

**Comment by kuleshovilya** [comment] 2021-10-04 10:25
@MaksimZhukov @ChristopheLav  We looked into the issue, and there is not much we can do on the agent side. 
The issue seems to be stemming from the fact that /etc/environment is loaded on login, but script sets it after that, and agent is installed during that same login session, thus making it unable to read the /etc/env variables(since the agent loads PATH var itself)
I think the changes to the deployment scripts would be required to fix this issue.

**Comment by tonyskidmore** [comment] 2022-04-23 14:13
I have been working on a three part blog series on [Azure DevOps Self-Hosted VMSS Agents](https://www.skidmore.co.uk/series/ado-vmss-agents/).  I looked at this issue again while working through that and came up with a workaround that seems to work for me, based on various comments in the history of this issue. Specifically, in the [PATH issue](https://www.skidmore.co.uk/post/2022_04_20_azure_devops_vmss_agents_part2/#path-issue) in Part 2 I mention what I did to workaround this.  Would be interested to get any feedback.

**Comment by HoLengZai** [comment] 2022-09-18 05:16
Hi @miketimofeev 
I post a workaround to avoid any change on runner-images as it's not related to the runner-images but on how the VM pipeline agent extension for linux deploy the pipeline agent on the VM
https://github.com/microsoft/azure-pipelines-agent/issues/3461#issuecomment-1250117490

@marcuslopes @ChristopheLav 
It is also possible to add the `.env` file in `/agent` folder on the runner-image but I think it's better to create that `.env` file in the custom script Linux extension as it's really specific for the VM pipeline agent extension behaviour/install process
