### ISSUE TITLE
docker compose run does not output any container log

### ISSUE THREAD

**Issue by ste26054** [actions/virtual-environments#5022] opened 2022-01-24 19:53 UTC
**Describe the bug**
Hello, we are using a `docker compose run` command in a particular step as part of our CI process to run specs against a Dockerized Ruby on Rails application.
**Since a few days**, we are unable to see the output from Docker in this step. 

**To Reproduce**
I created [this sample repo](https://github.com/ste26054/ci_test) which mimics parts of our pipeline. It is enough to reproduce the [issue visible in step "Run Specs with docker compose run"](https://github.com/ste26054/ci_test/runs/4926925432?check_suite_focus=true).

The relevant workflow part : 
```yaml
- name: Run Specs with docker compose run
  run: |
    # GENERATES NO OUTPUT :
    docker compose -p ci_test -f docker-compose.test.yml run --name ci_test_output ci_test sh run-tests.sh
    
    # RETRIEVES LOGS FROM PREVIOUS COMMAND AND OUTPUTS CORRECTLY :
    docker logs ci_test_output
- name: Run Specs with docker run
  run: |
    # OUTPUTS LOGS CORRECTLY :
    docker run ci_test:latest sh run-tests.sh
```

The script which is being run by `docker compose run` (nothing special):
```shell
#!/bin/sh

echo "******* Loading database schema *******"
bundle exec rake db:schema:load
echo "***************************************"

echo "******* Running pending database migrations *******"
bundle exec rake db:migrate
echo "***************************************"


echo "******* Running tests *******"
bundle exec rails test -v
```

**Expected behavior**
The output of the `docker compose run` command should be displayed in the job log output.

## Runner Version and Platform
Runner `2.286.1` on `Ubuntu 20.04.3 LTS`
I also noticed that affected runner has the following docker compose version : `Docker Compose (Docker Inc., 2.2.3+azure-1)`
Whereas an unaffected job had the following version : `Docker Compose (Docker Inc., 2.2.2+azure-1)`

## What's not working?
![image](https://user-images.githubusercontent.com/3840020/150853870-a2a2490d-d534-4e9e-a4d5-a0464c9219a3.png)

Note that we can get the logs by using `docker run` instead of `docker compose run`:
![image](https://user-images.githubusercontent.com/3840020/150854305-b463eeb0-fe87-49eb-900c-24583f0c4eb3.png)

But we need to use `docker compose run` for our real world workflow due to the complexity of the app.

Thanks for your help!

**Comment by ethomson** [comment] 2022-02-04 19:39
Moving this to https://github.com/actions/virtual-environments and reopening; this looks like an issue in a new version of docker compose in a virtual environment.

**Comment by miketimofeev** [comment] 2022-02-07 07:36
@ethomson @ste26054 we will take a look

**Comment by mikhailkoliada** [comment] 2022-02-14 20:11
@ste26054 

I've converted your pipeline into the one:

```name: CI

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Run Specs with docker compose run
        run: |
          sudo rm -frv /usr/local/lib/docker
          sudo mkdir -p /usr/local/lib/docker/cli-plugins
          sudo apt-get remove moby-compose || true
          sudo docker system prune -a -f
          sudo  curl -SL https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-linux-x86_64 -o /usr/local/lib/docker/cli-plugins/docker-compose
          sudo chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
          sudo docker compose version
          echo "***** GOING TO RUN DOCKER COMPOSE RUN. LOGS ARE EXPECTED BELOW THIS LINE *****"
          sudo docker compose -p ci_test -f docker-compose.test.yml run --name ci_test_output ci_test sh run-tests.sh
      - name: Run Specs with docker run
        run: |
          echo "GOING TO DOCKER RUN"
          sudo docker run ci_test:latest sh run-tests.sh
      - name: Run Specs with docker-compose run
        run: |
          sudo docker compose -f docker-compose.test.yml rm -f
          echo "***** GOING TO RUN DOCKER-COMPOSE RUN. LOGS ARE EXPECTED BELOW THIS LINE *****"
          sudo docker-compose -p ci_test -f docker-compose.test.yml run --name ci_test_output ci_test sh run-tests.sh```
          
          (on a self-hosted runner), it seems the problem exists in moby docker compose 2.2.3, but once I am installing the separate cli plugin the problem is gone. Might be @cpuguy83 has better knowledge on what's going on.

**Comment by cpuguy83** [comment] 2022-02-15 01:42
Also checking around with folks at Docker.

**Comment by mikhailkoliada** [comment] 2022-02-15 16:49
update: I was wring, 2.2.3 is not working at all (in therms of logs output), 2.2.2 downgrade helps as I said above :)

**Comment by mikhailkoliada** [comment] 2022-02-17 09:55
@ndeloof thanks a lot for your input!

Given that this is not a bug per se I am going to close this issue right now, if anyone has questions left feel free to reach us out again.

**Closed by mikhailkoliada** 2022-02-17 09:55 UTC
Labels: Area: Containers, investigate, bug report

**Comment by ste26054** [comment] 2022-02-24 10:13
Thanks for the investigation, I have added the option `--no-TTY` to `docker compose run` and it is now working as expected!

**Comment by ylhan** [comment] 2022-03-09 21:58
`--no-TTY` causes keyword highlighting to disappear, anyway to avoid this?
