### ISSUE TITLE
Windows agent not working for pipeline running tests since December

### ISSUE THREAD

**Issue by Niharikadutta** [actions/virtual-environments#4877] opened 2022-01-12 22:01 UTC
### Description

Here are the different pool/agent configurations I've tried for a windows agent, all leading to different error/behaviours:

1. Using `windows-latest`​ image causes jobs to get stuck
yml files - [template.yml](https://github.com/dotnet/spark/blob/0d6adce655452635e89f614a385d883cf2b4de5b/azure-pipelines-e2e-tests-template.yml) and [azure-pipelines.yml](https://github.com/dotnet/spark/blob/0d6adce655452635e89f614a385d883cf2b4de5b/azure-pipelines.yml)
Pipeline - [https://dev.azure.com/dnceng/public/_build/results?buildId=1547973&view=results](https://dev.azure.com/dnceng/public/_build/results?buildId=1547973&view=results)

2. Using the `NetCore1ES-Public` pool with ImageOverride of `Build.Windows.Amd64.VS2022.Pre.Open`
yml files - [template.yml](https://github.com/dotnet/spark/blob/8d7406b1c039c568bc9887ad8880e230b0507017/azure-pipelines-e2e-tests-template.yml) and [azure-pipelines.yml](https://github.com/dotnet/spark/blob/8d7406b1c039c568bc9887ad8880e230b0507017/azure-pipelines.yml)
Fails with premature process exit error
Pipeline - [https://dev.azure.com/dnceng/public/_build/results?buildId=1547782&view=results](https://dev.azure.com/dnceng/public/_build/results?buildId=1547782&view=results)

3. Using the `NetCore1ES-Public` pool with ImageOverride of `Build.Windows.10.Amd64.VS2019.Open`
yml files - [template.yml](https://github.com/dotnet/spark/blob/a710571350dbcaa1a63583668623dd92bd298313/azure-pipelines-e2e-tests-template.yml) and [azure-pipelines.yml](https://github.com/dotnet/spark/blob/a710571350dbcaa1a63583668623dd92bd298313/azure-pipelines.yml)
Fails with error - `System.NullReferenceException: Object reference not set to an instance of an object`
Pipeline - [https://dev.azure.com/dnceng/public/_build/results?buildId=1547880&view=results](https://dev.azure.com/dnceng/public/_build/results?buildId=1547880&view=results)

These issues only started occurring in December, before that we used to use the Hosted VS2017​ pool and it used to work fine. 
I'd really appreciate if you could help look into what is happening here, I have Ubuntu 1804 working fine, but need to be able to run my tests on a Windows agent.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

All links provided above in Description

### Is it regression?

Last successful build was in October 2021, those build are not found anymore

### Expected behavior

Pipeline should run successfully on a Windows agent as there have been no code or pipeline changes that are causing these issues on Windows agents. Ubuntu agents are working fine.

### Actual behavior

Pipelines on windows agents either get stuck or error out with unexpected errors

### Repro steps

run the pipeline  for code - https://github.com/dotnet/spark. Raising a PR, making changes to existing PR would reproduce the error.

**Comment by al-cheb** [comment] 2022-01-13 06:10
Hey, @Niharikadutta 
We will take a look at it.

**Comment by nikolai-frolov** [comment] 2022-01-13 08:49
Hello @Niharikadutta, looking at the [dotnet.spark pipeline hystory](https://dev.azure.com/dnceng/public/_build?definitionId=459&_a=summary), there was a [successful build](https://dev.azure.com/dnceng/public/_build/results?buildId=1546309&view=logs&j=749986f8-bc28-5aa3-d90b-dd9b588aa995&t=859d2d79-0b8c-4129-b71d-dd527ef033d1) on Windows image at 1/11/2022, so we are a bit confused by statement that "Last successful build was in October 2021". As far as I can see this pipeline executes code from development branches and most likely all provided builds are affected by changes related issue:
```
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Spark.E2ETest.SparkFixture.<>c__DisplayClass10_0.<.ctor>b__0(Object sender, DataReceivedEventArgs arguments) in D:\a\_work\1\s\dotnet-spark\src\csharp\Microsoft.Spark.E2ETest\SparkFixture.cs:line 79
   at System.Diagnostics.Process.OutputReadNotifyUser(String data)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue(Boolean rethrowInNewThread)
--- End of stack trace from previous location where exception was thrown ---
   at System.Diagnostics.AsyncStreamReader.<>c.<FlushMessageQueue>b__18_0(Object edi)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```
P.S. "1ES Hosted Pool" is a self-hosted pool which is not related to image generation and it's out of virtual-environments team responsibility.

We are going to close this issue if you have no objections.

**Comment by Niharikadutta** [comment] 2022-01-13 19:05
> Hello @Niharikadutta, looking at the [dotnet.spark pipeline hystory](https://dev.azure.com/dnceng/public/_build?definitionId=459&_a=summary), there was a [successful build](https://dev.azure.com/dnceng/public/_build/results?buildId=1546309&view=logs&j=749986f8-bc28-5aa3-d90b-dd9b588aa995&t=859d2d79-0b8c-4129-b71d-dd527ef033d1) on Windows image at 1/11/2022, so we are a bit confused by statement that "Last successful build was in October 2021". As far as I can see this pipeline executes code from development branches and most likely all provided builds are affected by changes related issue:
> 
> ```
> The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
>    at Microsoft.Spark.E2ETest.SparkFixture.<>c__DisplayClass10_0.<.ctor>b__0(Object sender, DataReceivedEventArgs arguments) in D:\a\_work\1\s\dotnet-spark\src\csharp\Microsoft.Spark.E2ETest\SparkFixture.cs:line 79
>    at System.Diagnostics.Process.OutputReadNotifyUser(String data)
>    at System.Diagnostics.AsyncStreamReader.FlushMessageQueue(Boolean rethrowInNewThread)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Diagnostics.AsyncStreamReader.<>c.<FlushMessageQueue>b__18_0(Object edi)
>    at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
>    at System.Threading.ThreadPoolWorkQueue.Dispatch()
>    at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
> ```
> 
> P.S. "1ES Hosted Pool" is a self-hosted pool which is not related to image generation and it's out of virtual-environments team responsibility.
> 
> We are going to close this issue if you have no objections.

Hi @nikolai-frolov  thank you for your reply. The successful build was for a small snippet of the pipeline I was testing to debug and get to the bottom of the issue. The complete pipeline hasn't succeeded for over 2 months (based on history, we don't run tests every day). If this is outside your team's scope, can you point me to the appropriate github project? I was pointed to this project from [azure-pipelines-agent](https://github.com/microsoft/azure-pipelines-agent), so just want to know who can help me look into this.

**Comment by nikolai-frolov** [comment] 2022-01-14 07:40
@Niharikadutta our team owns GitHub Actions hosted runners and [Microsoft-hosted agents](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#use-a-microsoft-hosted-agent) used for Azure Pipelines (but not a self-hosted pools like "1ES Hosted Pool", which created and configured by project owners). Your pipelines for examples 2 and 3 fail with the same error which provided at the my message above and probably it's the same pipeline stuck reason for the example 1. In my guess, this issue should be investigated by SparkFixture.cs owners first.

**Comment by Niharikadutta** [comment] 2022-01-14 18:28
@nikolai-frolov The example 1 is not running on self-hosted pools but on ms pool ( the image is `windows-latest`, as you can see in the linked [template.yml](https://github.com/dotnet/spark/blob/0d6adce655452635e89f614a385d883cf2b4de5b/azure-pipelines-e2e-tests-template.yml) ) where it is getting hung. Can you please help look into why this is happening for the Microsoft-hosted agent? Our code has been the same and there are no changes since it used to work back in November 2021.

**Comment by nikolai-frolov** [comment] 2022-01-18 11:15
@Niharikadutta it seems mentioned hung is related to DotNetCoreCLI@2 task and how it executes commands (I don't rule out that issue can be caused by changes but anyway it should not cause a hung). I would suggest to create a new one issue for the [azure-pipelines-tasks team](https://github.com/Microsoft/azure-pipelines-tasks), most likely they will be able to investigate this deeply. We are going to close this issue since it's not related to image generation.

**Closed** 2022-01-21 14:09 UTC
Labels: Area: .NET Core, Area: Testing and code coverage, OS: Windows, investigate, external

**Comment by Misshunter1** [comment] 2022-01-21 18:21
yes there are specific orders and codes u already okayed.
