### ISSUE TITLE
Not all agents are using the az cli 2.34.1 version 

### ISSUE THREAD

**Issue by neodagen** [actions/virtual-environments#5331] opened 2022-04-01 21:37 UTC
### Description

Not all of our build agents with the ubuntu 20.04 spec are using the az cli 2.34.1 version.
This is causing many failures with uploading to an existing blob storage.
Using the --overwrite flag gives us the following error: Error unrecognized arguments: --overwrite

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

image version 20220227.1

### Repro steps

1. Use the azure cli task in line script: 

> az storage blob upload-batch --destination '$web' --account-name youraccountname  --overwrite true --source yoursource
to upload to a non empty blob storage location in an azure storage account.

2. Receive error.

**Comment by weberlars** [comment] 2022-04-03 13:02
I can confirm this issue, we are currently experiencing the same problem in our pipelines.

We are also running the `ubuntu-20.04` environment, and it is using different image versions when run multiple times. Because these image versions contain different versions of the azure-cli, with the breaking change in `az storage blob upload`, we also experience breaking builds depending on which image is used.

These are the images we see getting used, from what it seems randomly:
* Image version `20220227.1` (containing azure-cli `2.33.1`)
* Image version `20220330.0` (containing azure-cli `2.34.1`)

In addition, the documentation for "Microsoft hosted agents" ( https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml ) is pointing to a Readme for this agent in the `main` branch, which is still referencing image version `20220220.1`:
https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md

**Comment by al-cheb** [comment] 2022-04-04 07:07
The new image rollout with azure-cli 2.34.1 is in progress. We are planning to complete it today or tomorrow - https://github.com/actions/virtual-environments/pull/5314

**Comment by weberlars** [comment] 2022-04-04 11:14
Thanks for the answer @al-cheb. 
For the transition period, we have changed to ubuntu-18.04, as the azure-cli in that agent is reliably set to 2.34.1.

**Comment by miketimofeev** [comment] 2022-04-04 12:52
@weberlars we have updated both images a few hours ago, sorry for the inconvenience.
I'm going to close the issue, but please feel free to contact us if you have any concerns.
Thank you!

**Closed by miketimofeev** 2022-04-04 12:52 UTC
Labels: awaiting-deployment, Area: Scripting and command line, OS: Windows, Area: Image administration
