### ISSUE TITLE
Clang 9.0.0 plus GNU 11.1.0 causes crash when using `std::thread`

### ISSUE THREAD

**Issue by densamoilov** [actions/virtual-environments#3454] opened 2021-05-26 08:55 UTC
**Description**  
After Ubuntu 18.04 [image update](https://github.com/actions/virtual-environments/releases/tag/ubuntu18%2F20210510.0) some tests started failing when using Clang 9.0.0. The reason seems to be incompatibility (probably due to a bug) between Clang 9.0.0 and GNU 11.1.0 headers that are used by Clang. If there are such issues in GNU 11.1.0 then it should probably be opt-in in the image and not the default one.

**Area for Triage**:  
C/C++

**Bug?**: 
Perhaps

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [x] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
 20210517.1

**Expected behavior** 
The code below compiles with Clang 9.0.0 and works.
```cpp
#include <thread>
int main() {
    std::thread t([]{});
    t.join();
    return 0;
}
```
**Actual behavior**  
It crashed at runtime. I narrowed it down to GNU 11.1.0 compiler. When compiling the code snippet above with Clang 9.0.0 it uses GNU header files and in particular `thread` header file from GNU 11.1.0 which causes the aforementioned crash. When overriding path to the headers so that it points to GNU 10.3.0 everything works as expected.

**Repro steps**  
Having Clang 9.0.0 and GNU 11.1.0 installed just run the following command to compile the code snippet:
```bash
clang++ --std=c++11 ./code.cpp -lpthread
./a.out # should crash
```
I could locally workaround it by using headers from GNU 10.3.0 but this is not a solution. Also, this cannot be overrided by setting the default GNU compiler in the system because Clang searches for header files in the directory of the latest GNU compiler.
```bash
clang++ --std=c++11 -I/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10 ./code.cpp -lpthread
```

**Comment by dibir-magomedsaygitov** [comment] 2021-05-26 13:47
Hello @densamoilov. I'm going to close this issue as duplicate of [this ](https://github.com/actions/virtual-environments/issues/3432)one. In case of any questions feel free to contact us. Thank you.

**Comment by densamoilov** [comment] 2021-05-26 18:11
Thanks @dibir-magomedsaygitov, the duplication is in the suggestion on how to fix the issue. But the issues are different, so the end solution may not address this particular issue, e.g. #3451 targets only libraries while the problem I reported is about headers.
We need to make sure that the solution works for both reported issues. I'd suggest to open it until the issues are fixed.

**Comment by dibir-magomedsaygitov** [comment] 2021-05-28 07:07
Hello @densamoilov. We decided to remove GCC and Gfortran 11 from images (see related [announcement](https://github.com/actions/virtual-environments/issues/3467#)). As a workaround we suggest you to remove gcc11 in runtime:
`sudo apt remove libgcc-11-dev gcc-11`

**Comment by MaksimZhukov** [comment] 2021-06-03 10:21
Hello @densamoilov! GCC and Gfortran 11 have been removed from Ubuntu images. I'm closing this issue. Feel free to contact us if you have any questions. Thanks!

**Closed by MaksimZhukov** 2021-06-03 10:21 UTC
Labels: Area: Clang, Area: Scripting and command line, OS: Ubuntu, investigate

**Comment by densamoilov** [comment] 2021-06-03 18:02
Thanks @MaksimZhukov, the fix works just fine.
