### ISSUE TITLE
Add Hub

### ISSUE THREAD

**Issue by tokiwong** [actions/virtual-environments#36] opened 2019-10-14 14:24 UTC
**Tool information**
- Tool name: Hub
- Add or update? Add
- Desired version: 2.12.8 (latest)
- Approximate size: 9.5 MB
- If this is an add request:
  - Brief description of tool: git wrapper that extends extra features with GitHub (like creating GitHub pull requests)
  - URL for tool's homepage: https://github.com/github/hub

**Virtual environments affected**
- [x] macOS 10.14
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Can this tool be installed during the build?**
Yes, can be downloaded and installed from the github page

**Are you willing to submit a PR?**
Yes

**Comment by kaylangan** [comment] 2019-10-15 16:29
👋 Thanks for the suggestion! Are there specific hub commands that you're looking for? The extended git ones seem to be covered by having git installed, but some of the new commands offered by hub seem interesting.

Does [actions/github-script](https://github.com/actions/github-script) offer the functionality you're looking for?

Duplicate of #1

**Comment by tokiwong** [comment] 2019-10-15 18:53
@kaylangan I'm specifically looking for `hub pull-request`

The idea is to have an action on repo A build a project and programmatically create a pull request with artifact changes to repo B, where repo B has its own GH Action that triggers on `pull_request`

**Comment by derek-burdick** [comment] 2019-11-04 05:32
@kaylangan I'm looking for hub api repos/{owner}/{project}/issues/{issue}/comments so that I can post a comment to a Pull Request during an action.

Currently i'm manually downloading 2.12.8 in my Action steps.

**Comment by oldskool** [comment] 2019-11-04 10:38
> @kaylangan I'm looking for hub api repos/{owner}/{project}/issues/{issue}/comments so that I can post a comment to a Pull Request during an action.

You can also use the built-in GITHUB_TOKEN environment variable to directly talk to the API to achieve this, just add a step like:

```
steps:
  - name: Post comment
    env:
      # If your workflow triggers on the pull_request event type, you can access the PR number here
      PR_NUMBER: ${{ github.event.pull_request.number }}
    run: |
      curl -H "Authorization: token ${API_TOKEN}" \
      -XPOST -d '{"body": "Hello world"}' \
      https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/comments
```

This would remove the necessity to manually download Hub and save time on your build.

**Comment by derek-burdick** [comment] 2019-11-05 15:13
As a follow up, if you have text that is not json friendly, you can use JQ to create a JSON document.
jq -nc --arg str "`cat comment.txt`" '{"body": $str}' > comment.json

then do -d @comment.json in curl.

I'm posting the output from terraform show to the pull request.

**Comment by knoopx** [comment] 2019-12-06 10:20
There's no github action that allows to do something as simple as this:

```
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo snap install hub --classic
          build_date=$(date +%Y%m%d)
          build_number=$[$(git tag | grep $build_date | wc -l) + 1]
          tag="$build_date.$build_number"
          hub release create $tag --prerelease -m "$tag" -a dist/*.zip
```

Being able to do it without having to install hub each time would be awesome.

**Comment by oldskool** [comment] 2019-12-06 10:53
> There's no github action that allows to do something as simple as this:

I'm not quite sure how the [create-release](https://github.com/actions/create-release) action would not allow you to do that?

**Comment by knoopx** [comment] 2019-12-06 19:40
no offense but the create-release action is a joke. the snippet I pasted tags the just pushed commit using the current timestamp (20191206.1, 20191206.2, 20191207.1...), creates a release and attaches the first zip match as release asset. there's no easy, straightforward way to accomplish that I know, not even using a combination of several "official" actions.

**Comment by peaceiris** [comment] 2019-12-06 19:48
For reference. https://github.com/actions/virtual-environments/issues/1#issuecomment-536799598

> To download hub for Linux and place the executable into bin/hub of current directory (no need to install it system-wide just to be used in an action):
>
> https://github.com/github/hub/issues/2249#issuecomment-536557540

```sh
wget -nv -O- \
  https://github.com/github/hub/releases/download/v2.12.7/hub-linux-amd64-2.12.7.tgz  | \
  tar xz --strip-components=1 '*/bin/hub'
```

**Comment by mislav** [comment] 2020-01-25 14:23
Added official instructions on how to [download and use hub from within GitHub Actions](https://github.com/github/hub#github-actions)

I wouldn't mind if hub was already bundled within the virtual environment, though!

**Comment by peaceiris** [comment] 2020-01-25 14:40
Thank you!

**Comment by andy-mishechkin** [comment] 2020-03-16 07:55
Hub CLI has been added to Ubuntu 16/18, MacOS, Windows images.
Please feel free to reopen this issue if you'll detect some bugs

**Comment by ydnar** [comment] 2020-03-26 20:26
Verified it works. Thanks all!

**Closed** 2020-03-27 05:01 UTC
Labels: OS: Ubuntu, OS: macOS, awaiting-deployment
