### ISSUE TITLE
glx.h is missing

### ISSUE THREAD

**Issue by arsdever** [actions/virtual-environments#4648] opened 2021-12-01 20:20 UTC
### Description

This is more of a question than a bug report. Is there a `<GL/glx.h>` file available on the `Ubuntu 20.04`?
I'm trying to install `angle` (actually trying to install other packages and this one comes as a dependency) and it fails. I reported the bug on `vcpkg` and [was questioned](https://github.com/microsoft/vcpkg/issues/21524#issuecomment-983461748) whether this file is available:
> Could you find `glx.h` locally? and check the path is right
> ```
> /usr/local/share/vcpkg/buildtrees/angle/src/ee2b7d070a-83a419ab43.clean/src/libANGLE/renderer/gl/glx/FunctionsGLX.cpp:15:10: fatal error: GL/glx.h: No such file or directory
>   15 | #include <GL/glx.h>
>      |          ^~~~~~~~~~
> compilation terminated.
> ```

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20211114.1 https://github.com/arsdever/lcd/runs/4262636323

### Repro steps

Try to install `angle` on `Ubuntu 20.04` machine using `vcpkg`

**Comment by panekj** [comment] 2021-12-01 20:41
`glx.h` is provided by `libglx-dev` package which is not installed.

could you try to run `sudo apt-get update && sudo apt-get install libglx-dev` at the beginning of the workflow and see if that works?

**Comment by arsdever** [comment] 2021-12-01 21:12
@panekj Thanks for the hint. Unfortunately, it didn't resolve the issue. As you see in this [build result](https://github.com/arsdever/lcd/runs/4387215316)
- `Update package repository` runs `sudo apt update`
- `Install dependent packages` runs `sudo apt install libglx-dev`
- `Install packages` runs `vcpkg` and fails. The [artifact file](https://github.com/arsdever/lcd/suites/4524906080/artifacts/121086800) contains the log from `vcpkg` which is still complaining about the missing header.

**Comment by panekj** [comment] 2021-12-01 21:18
According to log it fails on `gl.h` now which is provided by `libgl-dev` package

```
In file included from /usr/local/share/vcpkg/buildtrees/angle/src/ee2b7d070a-83a419ab43.clean/src/libANGLE/renderer/gl/glx/FunctionsGLX.cpp:15:
/usr/include/GL/glx.h:32:10: fatal error: GL/gl.h: No such file or directory
   32 | #include <GL/gl.h>
      |          ^~~~~~~~~
compilation terminated.
```

**Comment by panekj** [comment] 2021-12-01 21:31
As the CMake warning says:
```
CMake Warning at ports/angle/portfile.cmake:3 (message):
  angle currently requires the following libraries from the system package
  manager:

      libx11-dev
      libmesa-dev
      libxi-dev
      libxext-dev

  These can be installed on Ubuntu systems via apt-get install libx11-dev
  libmesa-dev libxi-dev libxext-dev.
```

You should install those in the runtime, `libmesa-dev` should have the `gl`/`glx` headers, unfortunately this is incorrect package name and it probably should be `libgl1-mesa-dev`

**Comment by arsdever** [comment] 2021-12-01 21:54
@panekj Thanks for your guidance. Actually `libgl[x]-dev` packages did help me proceed on the blockage I had, but there is a new one coming. I'll probably install these ones instead, as you again suggested. In any case, I think this thread can be closed since the main goal was reached.
So the answer to my question, as I understood, will be, that some packages might actually be missing from the build machine.

**Comment by shilovmaksim** [comment] 2021-12-02 08:54
Hi @arsdever. I will close the issue since it's not image related, but caused by missing dependencies.
Thank you @panekj for your guidance.

**Closed by shilovmaksim** 2021-12-02 08:54 UTC
Labels: needs triage
