### ISSUE TITLE
Update/Add Android NDK/SDK components for visual studio

### ISSUE THREAD

**Issue by kudaba** [actions/virtual-environments#93] opened 2019-11-14 22:35 UTC
**Tool information**
- Tool name: Android SDK/NDK
- Add or update? Add
- Approximate size:
- If this is an add request:
  - Brief description of tool: Visual studio components for Android development (c++ specificall)
  - URL for tool's homepage: https://docs.microsoft.com/en-us/visualstudio/cross-platform/install-visual-cpp-for-cross-platform-mobile-development?view=vs-2019

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [X] Windows Server 2016 R2
- [X] Windows Server 2019

**Can this tool be installed during the build?**
I think so, but I need to figure out how to invoke the visual studio installer from command line

**Are you willing to submit a PR?**
Yes

** Additional Information **
While it's not listed on the virtual environments page I think the Android SDK is already installed so really I just need the NDK and the And build tools. The components to add are:
* Component.Android.NDK.R16B
* Component.Android.SDK25.Private
* Component.Ant

**Comment by kudaba** [comment] 2019-11-15 07:20
So it turns out that the android sdk is actually installed just not setup correctly. A few registry keys later got it working:

```yml
- name: install ndk
      run: |
        $key = "HKCU:Software\Microsoft\VisualStudio\SecondaryInstaller\VC"
        New-Item $key -force
        New-ItemProperty -Path $key -Name "AndroidHome" -Value "C:\Microsoft\AndroidSDK\25"
        New-ItemProperty -Path $key -Name "AntHome" -Value "c:\program files (x86)\microsoft visual studio\2019\community\Apps\apache-ant-1.9.3"
        New-ItemProperty -Path $key -Name "NdkRoot" -Value "C:\Microsoft\AndroidNDK64\android-ndk-r16b"
        New-ItemProperty -Path $key -Name "JavaHome" -Value "C:\Program Files\Android\jdk\microsoft_dist_openjdk_1.8.0.25"
```

**Comment by kudaba** [comment] 2019-11-15 08:19
Bonus:
The sdk only comes with platform 25 installed and I use 26, here's how to upgrade it:
```yml
        # Echo 'y' to accept user agreement O.o
        Echo 'y' | & C:\Microsoft\AndroidSDK\25\tools\bin\sdkmanager.bat "platforms;android-26"
```

**Comment by maxim-lobanov** [comment] 2020-02-25 10:42
Hi, I see that the following versions of `platforms;android-*`are installed: 19-29.
Please let me know if the issue is still actual and we need to have VS Android components on the image

**Comment by kudaba** [comment] 2020-02-25 17:45
I just tested and everything still fails as described. The NDK does seem to exist already on the disk image, but it's not setup correctly to use out of the box.

Without setting up the registry keys I get this error:
``TRACKER : error TRK0005: Failed to locate: "clang.exe". The system cannot find the file specified.``

Without running the sdkmanager script I get this error:
``C:\Microsoft\AndroidSDK\25\tools\ant\build.xml:538: Unable to resolve project target 'android-26'``

**Comment by kudaba** [comment] 2020-03-27 22:23
An update to this:
* The virtual environment changed from vs Community to Enterprise breaking the Ant directory, turns out I don't need to set the Ant or Java directories, those work properly.
* I tried updating to the Android SDK driectory mentioned in available software but I can't use those directly. The visual studio build system seems to expect an sdk folder to steps above build-tools.
* The platfoms directories aren't usable by themselves, they already exist in both the SDK and NDK folders.
* The android-sdk folder might beusable by other build systems, but not with the current state of visual studios cross platform integration.

I updated my earlier comment to remove reference to java and ant directories, but I still need the rest for it all to work.

**Comment by vsafonkin** [comment] 2020-04-14 06:29
Hi @kudaba , As I see these components is already installed to latest windows image:
[Check VS components](https://github.com/vsafonkin/visual-studio-components/runs/567324898?check_suite_focus=true)
Could you please provide some repro for us, so that we can verify that the installation is incorrect?

Thank you!

**Comment by kudaba** [comment] 2020-04-14 16:39
They are indeed installed, it's just that the default paths from visual studio don't seem to link up correctly, if I don't set those registry values then the build won't find them.

In addition to the components a lot of variants of the sdk and platforms are also installed, as listed here https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md, however they are broken up in a way that the visual studio build system can't use natively as is.

To be honest, thought, there's probably not much point in putting too much effort into this until the following is resolved: https://developercommunity.visualstudio.com/idea/782660/update-the-bundled-android-ndk-to-release-r21-lts.html

Until that's done the options for ndk/sdk/platform are actually quite limited.

**Comment by vsafonkin** [comment] 2020-04-15 10:08
Hi @kudaba , thank you for your point and info about issue with ndk r21, we will follow up it and continue to work when the issue will resolved.

**Comment by vsafonkin** [comment] 2020-06-29 14:00
Hi @kudaba , please, let me know if the problem still actual for you, thanks!

**Comment by vsafonkin** [comment] 2020-07-03 09:18
@kudaba , I've close this issue, feel free to reopen it if you have any troubles.

**Closed by vsafonkin** 2020-07-03 09:18 UTC
Labels: Area: Android, OS: Windows, enhancement, investigate
