### ISSUE TITLE
This check failed - happened since today when no self-hosted instance available

### ISSUE THREAD

**Issue by shwuhk** [actions/virtual-environments#2024] opened 2020-11-10 07:32 UTC
We would create a self-hosted instance in one of our job and so we could use it in the next job. When the next job is started, the instance isn’t registered yet(need around 2 minutes) and so it give out this error. However, the behaviour isn’t the same yesterday while the next job would wait until the instance created. Is there something changed? Thanks.

**Comment by Darleev** [comment] 2020-11-10 11:16
Hello @shwuhk,
Thank you for contacting us.
Could you please provide more details about the issue? Steps to reproduce and pipeline link will be much appreciated.

We are looking forward to your reply.

**Comment by shwuhk** [comment] 2020-11-10 11:30
Thanks for your kindly reply.

After some tests, I find that this issue will be happened when the job need a custom label(e.g. high-performance) instance but there isn't any registered in the self-hosted runners. We solve this now by at least leaving one runner to be registered with this custom label, it doesn't matter if this runner is offline.

I created a new repo to demonstrate this issue.
Please check that in the following pipeline.
https://github.com/shwuhk/test-runner/runs/1379431643

In order to avoid this now, what I can do is to at least have one runner to be registered with `custom-label`. In that case, the job will wait until that runner to be online. Otherwise, it will just check `This check failed`

**Comment by maxim-lobanov** [comment] 2020-11-10 15:13
Hello @shwuhk , I have confirmed with engineers that it is expected behavior.
If label exists but machines are busy or disabled, job will wait for 24 hours.
If label doesn't exist, build will fail.

**Comment by shwuhk** [comment] 2020-11-11 04:31
But this would be quite trouble for a use case like us that an instance will be created when we need.

**Comment by shwuhk** [comment] 2020-11-11 04:50
Also, I think the error message should be more descriptive

**Comment by maxim-lobanov** [comment] 2020-11-11 06:09
@shwuhk , thank you for your feedback, I will share it to related team.
I am closing this issue for now, because as it is mentioned in readme file, in this repository we manage problems related content of Hosted images.

**Closed by maxim-lobanov** 2020-11-11 06:09 UTC
Labels: external, question

**Comment by shwuhk** [comment] 2020-11-11 06:18
Thanks
