### ISSUE TITLE
Actions fail intermittently due to NPM ECONNRESET

### ISSUE THREAD

**Issue by rijkvanzanten** [actions/virtual-environments#3737] opened 2021-07-15 19:39 UTC
### Description

Every now and again, our actions randomly fail due to an ECONNRESET error coming from NPM, see for example https://github.com/directus/directus/runs/3080202193?check_suite_focus=true, https://github.com/directus/directus/pull/5754/checks?check_run_id=2617592226, https://github.com/directus/directus/runs/2611005993 or https://github.com/directus/directus/runs/2602577476. 

I reached out to GitHub Support about this, who referenced me to this repo.

### Virtual environments affected

- [X] Ubuntu 16.04
- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Image version and build link

n/a. Getting a `Error: We are currently unable to download the log. Please try again later.` message now..

### Expected behavior

The connection to NPM shouldn't fail

### Actual behavior

The connection to NPM fails

### Repro steps

1. Setup a workflow that runs `npm ci`
2. See it fail intermittently

**Comment by miketimofeev** [comment] 2021-07-16 05:38
Hi @rijkvanzanten!
It shouldn't be related to the images themselves, we will take a look. Where have you seen connection failures since there is an error with logs in provided runs?

**Comment by miketimofeev** [comment] 2021-07-16 09:53
Well, found the link with connreset 
https://github.com/directus/directus/runs/3080883194?check_suite_focus=true

**Comment by cschleiden** [comment] 2021-07-16 09:53
A more recent run which seems to hit the same error: https://github.com/directus/directus/runs/3080883194?check_suite_focus=true

**Comment by miketimofeev** [comment] 2021-07-16 11:21
@rijkvanzanten old logs are not available as the retention policy has been configured to 5 days.
How often do you see such behavior? Could you please provide minimal repro steps? We assume that something is wrong on the NPM side from time to time.

**Comment by rijkvanzanten** [comment] 2021-07-16 13:36
Hi y'all! Thanks for the swift replies!

> It shouldn't be related to the images themselves, we will take a look

I would agree, it feels like a weird intermittent connection issue between Actions and NPM. Not sure on what side of the equation it goes wrong though..

> We assume that something is wrong on the NPM side from time to time.

I could see this, however, I run `npm install` (and/or CI, doesn't seem to matter) locally dozens of times anywhere between 1 and 50 times a day, and have never seen this specific ECONNRESET error 🤔 I can't recall (personally) seeing the same exact error outside of GitHub Actions. (Though that's obviously very anecdotal evidence)

> old logs are not available as the retention policy has been configured to 5 days.

Gotcha, the error message threw me off there. Should I open a separate ticket here/elsewhere to pick that up?

> Could you please provide minimal repro steps?

It seems to happen on a regular `npm install`, so the minimal repro should be as simple as

```yaml
name: Debug NPM connection
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: |
          npm install
```

> How often do you see such behavior?

Hard to tell with exact accuracy due to the logs retention, though I would estimate between 1-5% of the runs.

**Comment by LeonidLapshin** [comment] 2021-07-21 10:23
Hey, @rijkvanzanten !
I have [forked your repo and tried to reproduce the problem](https://github.com/LeonidLapshin/directus) but have no luck with it :( Seems that it's really rare and no action needed. I'll close this issue but please feel free to reopen it if you have any concerns.
Thanks!

**Closed by LeonidLapshin** 2021-07-21 10:23 UTC
Labels: Area: JavaScript and Node.js, OS: Ubuntu, investigate

**Comment by rijkvanzanten** [comment] 2021-07-21 14:07
Makes sense, I understand this is too much of an edge case to be able to efficiently research and resolve. As for any concerns, the only one I have is that I'd rather not have our CI fail randomly of course 😅 

Is there anything I can do from our side to debug this issue further when it happens?

**Comment by miketimofeev** [comment] 2021-07-21 14:19
@rijkvanzanten please let us know as soon as you get it and provide the links to the failed runs. We will check the underlying infrastructure for the particular run.
Thank you!

**Comment by rijkvanzanten** [comment] 2021-07-21 14:22
Will do!

**Comment by AaronFriel** [comment] 2022-10-12 00:33
Hey folks, bumping an old thread here, we're seeing *a lot* of ECONNRESET issues, primarily in one action: https://github.com/actions/setup-dotnet/issues/333

No recent change in the action, is this an issue with the virtual environment?

**Comment by kmahyyg** [comment] 2024-01-27 10:19
Multiple runs failed from a long time ago, especially in QEMU-based ARM64 docker image building, but amd64 builder is working:


ARM64 using QEMU:
https://github.com/kmahyyg/ztncui-aio/actions/runs/7677880679/job/20927134240
https://github.com/kmahyyg/ztncui-aio/actions/runs/7677807879/job/20926977995
https://github.com/kmahyyg/ztncui-aio/actions/runs/7504706695/job/20449416696

Successful runs using AMD64 directly (same commit):
https://github.com/kmahyyg/ztncui-aio/actions/runs/7677880679/job/20927134295
https://github.com/kmahyyg/ztncui-aio/actions/runs/7677831444/job/20927028783
https://github.com/kmahyyg/ztncui-aio/actions/runs/7504706695/job/20449416799


@miketimofeev

**Comment by kmahyyg** [comment] 2024-01-27 10:20
This can be reproduced stably using GH-Hosted runner on my side.

**Comment by gramnarine** [comment] 2024-02-01 15:04
I have been seeing this intermittently in my org as well.

**Comment by austinpray-mixpanel** [comment] 2024-02-01 17:18
Seeing this pretty often using stock actions/setup-node@v4 

```
npm ERR! code ECONNRESET
npm ERR! network aborted
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
```

under 

```
Current runner version: '2.312.0'
Operating System
  Ubuntu
  20.04.6
  LTS
Runner Image
  Image: ubuntu-20.04
  Version: 20240126.1.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu20/20240126.1/images/ubuntu/Ubuntu2004-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20240126.1
```

**Comment by LeaBroudoEcho3d** [comment] 2024-02-20 16:37
Also seeing this pretty often now, I'm getting the following log:
```
npm ERR! code ECONNRESET
npm ERR! network aborted
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
```
For the following action (the error comes specifically from the `npm ci` command):
```
name: XX
on: [push]
jobs:
  run-defined-frontend-tests:
    runs-on: ubuntu-latest
    name: Webapp Unit Tests
    defaults:
      run:
        working-directory: ./webapp_new
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm ci --legacy-peer-deps
      - run: npm run test:ci
        env:
          CI: true
```

**Comment by undergroundwires** [comment] 2024-03-21 22:12
I get this on macOS runners:

```txt
Current runner version: '2.314.1'
Operating System
  macOS
  12.7.3
  21H1015
Runner Image
  Image: macos-12
  Version: 20240218.1
  Included Software: https://github.com/actions/runner-images/blob/macOS-12/20240218.1/images/macos/macos-12-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macOS-12%2F20240218.1
Runner Image Provisioner
  2.0.341.1+ea3907f30f87ddf37e44fa45b753abddb03811b4
```

**Comment by bcheidemann** [comment] 2024-03-27 13:34
Getting the below error intermittently but regularly.

```
npm ERR! code ECONNRESET
npm ERR! network aborted
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
```

**Comment by dadebue** [comment] 2024-04-02 22:03
FYI: Upgrading to Node 20 in the Dockerfile fixed the problem for me...

**Comment by undergroundwires** [comment] 2024-04-04 11:43
I solved this by upgrading to Node 20 and enforcing IPv4, see [force-ipv4](https://github.com/undergroundwires/privacy.sexy/tree/master/.github/actions/force-ipv4) action.

**Comment by austinpray-mixpanel** [comment] 2024-04-04 15:16
It's worth noting that npm just closed a bug (pending release) where too many connections were being opened during install:
- https://github.com/npm/cli/issues/7072
- https://github.com/TooTallNate/proxy-agents/issues/299

**Comment by buanet** [comment] 2024-04-05 06:04
I got the same error, exactly as @dadebue describes.
But as I have to stay at Node 18 at the moment, I needed another solution than upgrading to Node 20 in my Dockerfile.
So I just update NPM to the new 10.5.1 release and the GHA build is working again. 
Thank you all for commenting this old, closed issue, helping me to fix that! 😄 

Regards,
André

**Comment by dadebue** [comment] 2024-04-09 04:39
The problem is occurring again for me now. Even with Node 20 🤔

**Comment by zburgermeiszter** [comment] 2024-04-23 17:30
I also hit this issue often.
As a temporary solution I leveraged the `nick-fields/retry` action.

```
      - name: Install npm dependencies
        if: steps.cacheNodeModules.outputs.cache-hit != 'true'
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: npm ci
```

**Comment by aylesm** [comment] 2025-01-08 16:33
Seeing this today for the first time.  This is painful.  Across multiple repos.

**Comment by boluokvmd** [comment] 2025-01-08 16:34
> Seeing this today for the first time. This is painful. Across multiple repos.

Me too

**Comment by addy** [comment] 2025-01-08 17:02
Also starting to see this in some of our repos as of today.

**Comment by bmacnaughton** [comment] 2025-01-08 17:39
getting random failures from npm today - different files fail, but consistent failures.

**Comment by tomdracz** [comment] 2025-01-08 18:36
Seeing this a lot today also. Got a job that uses different package managers (npm, bun, yarn etc), but so far only npm fails

**Comment by karthikscale3** [comment] 2025-01-08 18:39
seeing this today

**Comment by jplwood** [comment] 2025-01-08 19:52
Related to issues today: https://github.com/npm/cli/issues/8015 suggests its a registry issue? Anyone have a workaround/solution?

**Comment by victorhahn** [comment] 2025-01-08 20:15
Seeing this issue as well today

**Comment by Firefds** [comment] 2025-01-08 20:15
Same, A LOT!

**Comment by austinpray-mixpanel** [comment] 2025-01-08 20:17
Yup just had a spike of these across all of our github hosted runners

```
npm ERR! code ECONNRESET
npm ERR! network aborted
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
```

**Comment by izzyizzat10** [comment] 2025-01-08 20:36
Same issue here:
````npm error code ECONNRESET
npm error errno ECONNRESET
npm error network Invalid response body while trying to fetch https://registry.npmjs.org/typescript: aborted
npm error network This is a problem related to network connectivity.
npm error network In most cases you are behind a proxy or have bad network settings.
npm error network
npm error network If you are behind a proxy, please make sure that the
npm error network 'proxy' config is set properly.  See: 'npm help config'

**Comment by lucaslacerdacl-o2ebrands** [comment] 2025-01-08 20:44
Same here, sometimes this error appears:
```
npm warn deprecated domexception@4.0.0: Use your platform's native DOMException instead
npm warn deprecated abab@2.0.6: Use your platform's native atob() and btoa() methods instead
npm error code 1
npm error path /home/runner/work/****/node_modules/vite/node_modules/esbuild
npm error command failed
npm error command sh -c node install.js
npm error node:internal/child_process:1124
npm error     result.error = new ErrnoException(result.error, 'spawnSync ' + options.file);
npm error                    ^
npm error
npm error <ref *1> Error: spawnSync /home/runner/work/****/node_modules/vite/node_modules/esbuild/bin/esbuild ETXTBSY
npm error     at Object.spawnSync (node:internal/child_process:1124:20)
npm error     at spawnSync (node:child_process:876:24)
npm error     at Object.execFileSync (node:child_process:919:1[5](https://github.com/****/actions/runs/****/job/****#step:4:6))
npm error     at validateBinaryVersion (/home/runner/work/****/node_modules/vite/node_modules/esbuild/install.js:99:28)
npm error     at /home/runner/work/****/node_modules/vite/node_modules/esbuild/install.js:283:5 {
npm error   errno: -2[6](https://github.com/****/actions/runs/****/job/****#step:4:7),
npm error   code: 'ETXTBSY',
npm error   syscall: 'spawnSync /home/runner/work/****/node_modules/vite/node_modules/esbuild/bin/esbuild',
npm error   path: '/home/runner/work/****/node_modules/vite/node_modules/esbuild/bin/esbuild',
npm error   spawnargs: [ '--version' ],
npm error   error: [Circular *1],
npm error   status: null,
npm error   signal: null,
npm error   output: null,
npm error   pid: 0,
npm error   stdout: null,
npm error   stderr: null
npm error }
npm error
npm error Node.js v20.15.1
npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2025-01-0[8](https://github.com/****/actions/runs/****/job/****#step:4:9)T20_38_56_808Z-debug-0.log
Error: Process completed with exit code 1.
```

**Comment by geoffmiller** [comment] 2025-01-08 20:48
> Same issue here:
> 
> ```
> npm error errno ECONNRESET
> npm error network Invalid response body while trying to fetch https://registry.npmjs.org/typescript: aborted
> npm error network This is a problem related to network connectivity.
> npm error network In most cases you are behind a proxy or have bad network settings.
> npm error network
> npm error network If you are behind a proxy, please make sure that the
> npm error network 'proxy' config is set properly.  See: 'npm help config'
> ```

I have been seeing this exact error. I noticed when I when I remove the `:` from the url `https://registry.npmjs.org/typescript:` it 200s. With the `:` it will always 404. 

The question(s) is "where is this colon coming from?" "Is it expecting something appended to it?"

**Comment by erikmartus** [comment] 2025-01-08 21:11
Seeing this issue occur on every deployment attempt. Our runners are using node 18.20.0 npm 10.5.0

**Comment by Xunnamius** [comment] 2025-01-08 21:21
Also seeing this all over https://github.com/Xunnamius/next-test-api-route-handler/actions and other projects. ECONNRESET. Intermittent failures. Usually node 18 fails, but sometimes node 22. Rarely node 20 for some reason.

Absolutely no issues installing in my local environment. From previous comments, seems the optimal workaround is to retry all npm commands that touch the network (so all of them).

**Comment by brianzhou13** [comment] 2025-01-08 22:01
Seeing this on ours, we are on:
* Node v18.20.1
* npm: 10.5.0

**Comment by toppsdown** [comment] 2025-01-08 22:05
Also seeing this

**Comment by Firefds** [comment] 2025-01-08 22:32
This is an npm registry issue https://status.npmjs.org/incidents/jlqm624klvs2
