### ISSUE TITLE
[macOS] gcc-8 error: dyld: Symbol not found: ___emutls_get_address

### ISSUE THREAD

**Issue by sgshulman** [actions/virtual-environments#2151] opened 2020-11-27 20:04 UTC
**Description**  
The program crashes on macOS if it is compiled with gcc-8. The message is: 
```
dyld: Symbol not found: ___emutls_get_address
  Referenced from: /Users/runner/work/workflow_test/workflow_test/./workflow_test
  Expected in: /usr/lib/libSystem.B.dylib
```
I found it yesterday when catch2 tests in my [repo](https://github.com/sgshulman/DGEM/tree/test) failed with this message. On October 10 the same code worked fine (you can compare the branch "test" with the "master" branch: the difference is only in spaces). 

**Area for Triage**: 
'Apple'
'C/C++'

**Question, Bug, or Feature?**:  
"Bug"

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
The program works correctly.

**Actual behavior**  
The program crashes with the message
```
Run ./workflow_test
dyld: lazy symbol binding failed: Symbol not found: ___emutls_get_address
  Referenced from: /Users/runner/work/workflow_test/workflow_test/./workflow_test
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ___emutls_get_address
  Referenced from: /Users/runner/work/workflow_test/workflow_test/./workflow_test
  Expected in: /usr/lib/libSystem.B.dylib

/Users/runner/work/_temp/7727eef4-6f62-44e9-8eb5-f9e80a1aa0d0.sh: line 1:  1288 Abort trap: 6           ./workflow_test
Error: Process completed with exit code 134.
```

**Repro steps**  
Please, use the following repo for a minimal working example. The code works fine with gcc-9 and clang but crashes with gcc-8.
https://github.com/sgshulman/workflow_test

**Comment by miketimofeev** [comment] 2020-11-30 07:53
Hi @sgshulman!
Could you please provide links to the successful and failed runs? Are they on the same commit?

**Comment by sgshulman** [comment] 2020-11-30 08:20
Hello! Thank you for your response. Yes, sure.
The successful commit is [here](https://github.com/sgshulman/DGEM/commit/173f9f488a8e712870954e480552920aaa017a3e). It was made on October 10. The test run [link](https://github.com/sgshulman/DGEM/runs/1240886743).

The failed commit [example](https://github.com/sgshulman/DGEM/commit/1acaedbacb842c4f952a61d40942f6abdf833ee5). 
Removing 4 spaces in .hpp should not affect the compilation. The test run [result](https://github.com/sgshulman/DGEM/runs/1465346207). Of cause, It is possible to revert spaces with the same [result](https://github.com/sgshulman/DGEM/runs/1472649695).

The Xcode version wasn't specified. So, it should be a default one.

**Comment by al-cheb** [comment] 2020-11-30 08:29
@sgshulman,
Could you please check with the previous Xcode version?

```
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 11.7
```

**Comment by sgshulman** [comment] 2020-11-30 08:40
I'm not sure, I do it correctly. The 11.7 Xcode version does not help.
[Commit](https://github.com/sgshulman/DGEM/commit/851b5fbbe6bcce6fd31c79f7c022de8183872699)
[Test result](https://github.com/sgshulman/DGEM/runs/1472736306)

**Comment by al-cheb** [comment] 2020-11-30 09:46
@sgshulman , Thank you.
Looks like the gcc-8 is broken on the image. The temporary workaround should help:
```
- if: matrix.compiler_name == 'build_gcc8'
        run: |
          brew reinstall gcc@8
```

**Comment by johnny-bit** [comment] 2020-11-30 10:07
Indeed it looks like gcc8 is broken on the image. Additionally I had a chat with Homebrew:

https://github.com/Homebrew/discussions/discussions/183#discussioncomment-142248

It seems like (possibly) XCode is installed without CLT

**Comment by maxim-lobanov** [comment] 2020-11-30 11:23
@johnny-bit , CLT is installed on Hosted images. Homebrew rebuilds broken dependencies from source code always by design.
Let's wait for next deployment and fix

**Comment by sgshulman** [comment] 2020-12-04 08:54
Hello! Thank you very much for your help!!!
After latest macOS releases tests on the same commits work fine both on macOS 10.15 and 11.

Test repo tests results for [macOS 10.15](https://github.com/sgshulman/workflow_test/runs/1497594309) and [macOS 11](https://github.com/sgshulman/workflow_test/runs/1491646480).

In my main repo, everything also works well [now](https://github.com/sgshulman/DGEM/runs/1497606386).

**Comment by miketimofeev** [comment] 2020-12-04 09:36
@sgshulman I'm going to close the issue.
Please feel free to contact us if you have any concerns.
Thank you!

**Closed by miketimofeev** 2020-12-04 09:36 UTC
Labels: Area: Apple, Area: C/C++, OS: macOS, awaiting-deployment, investigate
