### ISSUE TITLE
Running Linux docker image on Windows VM

### ISSUE THREAD

**Issue by nreddipalle** [actions/virtual-environments#2216] opened 2020-12-08 06:27 UTC
**Description**  
This is more of a question. Is it possible to run Linux image on Windows VM. 

**Area for Triage**:  

**Question, Bug, or Feature?**:  

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**  
A description of what you expected to happen.

**Actual behavior**  
A description of what is actually happening.

**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

1. Step 1
2. Step 2

**Comment by maxim-lobanov** [comment] 2020-12-08 06:35
Duplicate of https://github.com/actions/virtual-environments/issues/252
It is not possible for now due to virtualization method that we use

**Closed** 2020-12-08 06:37 UTC
Labels: needs triage

**Comment by nreddipalle** [comment] 2020-12-08 06:41
Is it possible to do with Self-Hosted agent and enabling hyper-v?

**Comment by al-cheb** [comment] 2020-12-08 07:11
It's possible to use self-hosted agent with Docker Desktop and Hyper-V  - https://docs.docker.com/docker-for-windows/
