### ISSUE TITLE
Ubuntu-latest az version

### ISSUE THREAD

**Issue by davidgarciapacksize** [actions/virtual-environments#3538] opened 2021-06-07 15:44 UTC
**Description**  
Installed version of azure cli contains a bug that was fixed on latest. Fix #18276
https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?tabs=azure-cli

**Question, Bug, or Feature?**:  
"Bug": az container create fails with AttributeError: 'ResourcesOperations' object has no attribute 'create_or_update'

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
 https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md 

**Expected behavior**  
`az container create` should NOT throw an exception

**Actual behavior**  
`az container create` throws `AttributeError: 'ResourcesOperations' object has no attribute 'create_or_update'`

**Repro steps**  
- Create a task: AzureCLI@2
- Execute the `az container create` command.

**Comment by miketimofeev** [comment] 2021-06-07 15:55
Hi @davidgarciapacksize!
I'm going to close this one as a duplicate of https://github.com/actions/virtual-environments/issues/3508.
We're going to deploy new images with the new azure-cli in the next few days. Please follow the original issue.
Thank you!

**Closed by miketimofeev** 2021-06-07 15:55 UTC
Labels: needs triage
