### ISSUE TITLE
The pg_config returns the wrong libdir

### ISSUE THREAD

**Issue by dvarrazzo** [actions/virtual-environments#3730] opened 2021-06-29 12:38 UTC
**Describe the bug**
`pg_config --libdir` should return `C:\Program Files\PostgreSQL\13\lib` (as per [Postgres installation](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#postgresql))

It returns instead `C:/STRAWB~1/c/lib` instead.

**To Reproduce**
Run `pg_config --libdir` on the runner. See [example run](https://github.com/psycopg/psycopg3/runs/2938475650?check_suite_focus=true) (the step named "exploring")

## Runner Version and Platform
2.278.0 on Windows

**Comment by miketimofeev** [comment] 2021-07-15 06:30
Hi @dvarrazzo!
I confirm the wrong directory — we will take a look at this.

**Comment by miketimofeev** [comment] 2021-07-15 09:14
@dvarrazzo it's expected behavior because Postgre was removed from the PATH due to the following issue https://github.com/actions/virtual-environments/issues/1089
Please consider adding `$env:PGBIN` to PATH:
```
$env:PATH = "$env:PGBIN;$env:PATH"
```
or running `pg_config` using the full path to the executable:
```
& "$env:PGBIN\pg_config.exe"
```
I'm going to close the issue, please feel free to contact us if you have any concerns.
Thank you!

**Closed by miketimofeev** 2021-07-15 09:14 UTC
Labels: Area: Databases, Area: Image administration, OS: Windows, bug

**Comment by dvarrazzo** [comment] 2021-07-15 18:36
That's not the issue. The issue is that the program returns the wrong values. It means that it's been compiled with a configuration inconsistent with the location it was installed.

**Comment by miketimofeev** [comment] 2021-07-16 07:29
@dvarrazzo strawberry perl comes along with lots of utilities and pg_config is just one of them, that's why it's available in the PATH.

**Comment by dvarrazzo** [comment] 2021-07-17 11:18
I understand. You are right: the directory `C:\Program Files\PostgreSQL\13\bin` contains a pg_config which returns the right path, see [the "test with path" step in this run](https://github.com/psycopg/psycopg/runs/3090923587?check_suite_focus=true)

Thank you very much!
