### ISSUE TITLE
unable exit from job(github actions)the job after running script 

### ISSUE THREAD

**Issue by sriedjx** [actions/virtual-environments#3245] opened 2021-04-23 06:19 UTC
**Description**  
Job is not going exit state(or completed ) after completing script(on remote server)

**state of failure**
when there is continuous generation of output from command github actions running fine but  if there is 30-45 seconds gap for displaying output during execution of commands then github action job going in hold state( or inprogress ) till  github actions  job max time reach (2hr 13min) then going failed state

script is to be run on remote server
ssh -o StrictHostKeyChecking=no -i .id_rsa root@$IPaddress "sh /myscript"
```
make compress-usr
make  mfsroot 
make  iso
make  image 
```
actually script is executing on remote server side but github action is not going completed stage. kindly let me know what could be the reason

**Comment by LeonidLapshin** [comment] 2021-04-25 22:15
Hey, @sriedjx !
Could you please clarify some moments?
1) Is the job failed on Github Actions on that step (step with remote script execution) and what is the exit code?
2) Does it always fails after more or less same period of time (you have mentioned 2h 13m, is it some magic value)?
3) Could you please share the job spec?
4) What type of runner do you use (MacOS, Ubuntu, Windows)?
5) As far as I have understood, you can see the actual script execution on the remote server while it is already failed on Github side, is it correct?

**Comment by sriedjx** [comment] 2021-04-26 05:41
1.yes, script is executing from github actions on remote server and getting expected output on remote server but github actions job is in hold state(i dont knw what state i would call which is not going forward the output should generated while executing the script but its not) Error: Process completed with exit code 255.
2.yes the execution of script doesnt take morethan 20min  but github actions taking 2hr -2hr 15min and failing the job but on remote server script is already executed
3. action file
```
name: edjos build automation
on: push

jobs:
  build:
    name: Digital-Ocean
    runs-on: ubuntu-latest    
    steps:
      - name: Digital Ocean Auth
        uses: digitalocean/action-doctl@v2.1.0
        with:
         token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: edjos droplet
        run: doctl compute droplet create --image 82170717 --size s-2vcpu-4gb --region nyc3 --ssh-keys ${{ secrets.SSH }} mydroplet
      - name: sleep
        run: sleep 480
      - name: login
        run: |
          cat <<EOF  > .id_rsa   
          -----BEGIN OPENSSH PRIVATE KEY-----
          mykey
          -----END OPENSSH PRIVATE KEY-----
          EOF
          chmod 400 .id_rsa
          IPaddress=$(doctl compute droplet list mydroplet | awk 'NR==2 {print $3}')
          echo "$IPaddress"
          ssh -o StrictHostKeyChecking=no -i .id_rsa root@$IPaddress "sh /root/myscript"
```
4. ubuntu-latest 
5. yes, script is executing on remote server which is triggered by github action and on remote server script is generated expected output but github action unable to identify script is executed or not.

**Comment by sriedjx** [comment] 2021-04-27 05:23
please respond back

**Comment by maxim-lobanov** [comment] 2021-04-27 05:31
@sriedjx , could you please temporary replace your sh script with simple echo and report results back?
```
ssh -o StrictHostKeyChecking=no -i .id_rsa root@$IPaddress "echo helloworld"
```

Will the step finish immediately in this case?

**Comment by sriedjx** [comment] 2021-04-27 05:44
it will work, im able to run script remotely but as i said if there is generation output continuously there is no problem with github actions but when some command take time(may it is running something in background which dont need to display output or there is no output for displaying) then problem arises(just observation but not sure) else other commands/script works fine.
anyway here is output of your query
```
Warning: Permanently added '159.89.191.24' (ECDSA) to the list of known hosts.
hello-world
```

**Comment by maxim-lobanov** [comment] 2021-04-27 06:01
If `ssh -o StrictHostKeyChecking=no -i .id_rsa root@$IPaddress "echo helloworld"` finishes successfully without delay
and `ssh -o StrictHostKeyChecking=no -i .id_rsa root@$IPaddress "sh /root/myscript"` hangs for 2 hours, I think something goes wrong during `sh /root/myscript` execution. May be this script hangs and doesn't finish properly.

GitHub Actions timeout is 6 hours so there is no reason for job failure in 2h 13 minutes. I think it is [ssh timeout](https://www.simplified.guide/ssh/disable-timeout)
> if the client's connection is working, yet will still send the encrypted alive message every 30 seconds. It will only disconnect after at least 2 hours of inactivity.

A few more ideas:
- Could you please try to create sh file with `echo helloworld` content and run it `ssh -o StrictHostKeyChecking=no -i .id_rsa root@$IPaddress "sh /root/helloworld.sh"`? Will it hangs the same way?
- Try to add `exit` command after script execution: `ssh -o StrictHostKeyChecking=no -i .id_rsa root@$IPaddress "sh /root/myscript && exit"`

**Comment by sriedjx** [comment] 2021-04-27 06:39
but same script I'm able to run on remote server. and my script is executing and generating expected output on remote server  which is triggered by GitHub Actions but my problem is GitHub Actions job is not going into completed state.

**Comment by sriedjx** [comment] 2021-04-28 03:10
Tried this as you said: `ssh -o StrictHostKeyChecking=no -i .id_rsa root@$IPaddress "sh /root/myscript && exit"` but same error. build failed at 2hrs 12min

logs as below

```
2021-04-27T12:27:42.1934328Z ##[section]Starting: Request a runner to run this job
2021-04-27T12:27:42.6637716Z Can't find any online and idle self-hosted runner in current repository that matches the required labels: 'ubuntu-latest'
2021-04-27T12:27:42.6637859Z Can't find any online and idle self-hosted runner in current repository's account/organization that matches the required labels: 'ubuntu-latest'
2021-04-27T12:27:42.6638357Z Found online and idle hosted runner in current repository's account/organization that matches the required labels: 'ubuntu-latest'
2021-04-27T12:27:42.9077544Z ##[section]Finishing: Request a runner to run this job
2021-04-27T12:27:50.4981530Z Current runner version: '2.278.0'
2021-04-27T12:27:50.5004498Z ##[group]Operating System
2021-04-27T12:27:50.5005387Z Ubuntu
2021-04-27T12:27:50.5005799Z 20.04.2
2021-04-27T12:27:50.5006247Z LTS
2021-04-27T12:27:50.5006761Z ##[endgroup]
2021-04-27T12:27:50.5007290Z ##[group]Virtual Environment
2021-04-27T12:27:50.5007929Z Environment: ubuntu-20.04
2021-04-27T12:27:50.5008448Z Version: 20210419.1
2021-04-27T12:27:50.5009433Z Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20210419.1/images/linux/Ubuntu2004-README.md
2021-04-27T12:27:50.5010791Z Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20210419.1
2021-04-27T12:27:50.5011608Z ##[endgroup]
2021-04-27T12:27:50.5013440Z ##[group]GITHUB_TOKEN Permissions
2021-04-27T12:27:50.5014544Z Actions: write
2021-04-27T12:27:50.5015105Z Checks: write
2021-04-27T12:27:50.5015571Z Contents: write
2021-04-27T12:27:50.5016119Z Deployments: write
2021-04-27T12:27:50.5016720Z Issues: write
2021-04-27T12:27:50.5017256Z Metadata: read
2021-04-27T12:27:50.5017822Z Packages: write
2021-04-27T12:27:50.5018333Z PullRequests: write
2021-04-27T12:27:50.5018975Z RepositoryProjects: write
2021-04-27T12:27:50.5019568Z SecurityEvents: write
2021-04-27T12:27:50.5020142Z Statuses: write
2021-04-27T12:27:50.5020753Z ##[endgroup]
2021-04-27T12:27:50.5023762Z Prepare workflow directory
2021-04-27T12:27:50.5593154Z Prepare all required actions
2021-04-27T12:27:50.5603022Z Getting action download info
2021-04-27T12:27:51.0486209Z Download action repository 'digitalocean/action-doctl@v2.1.0'
2021-04-27T12:27:52.8229420Z ##[group]Run digitalocean/action-doctl@v2.1.0
2021-04-27T12:27:52.8230091Z with:
2021-04-27T12:27:52.8230994Z   token: ***
2021-04-27T12:27:52.8231419Z   version: latest
2021-04-27T12:27:52.8231860Z ##[endgroup]
2021-04-27T12:27:53.6939216Z [command]/usr/bin/tar xz --warning=no-unknown-keyword -C /home/runner/work/_temp/80921f83-d5f0-435e-810c-82a6612dd662 -f /home/runner/work/_temp/c6e9cb48-b15b-4fe3-bba6-9c8f6611c0ac
2021-04-27T12:27:53.6941443Z >>> doctl version v1.59.0 installed to /opt/hostedtoolcache/doctl/1.59.0/x64
2021-04-27T12:27:53.6943214Z [command]/opt/hostedtoolcache/doctl/1.59.0/x64/doctl auth init -t ***
2021-04-27T12:27:53.6944361Z Using token [***]
2021-04-27T12:27:53.6944756Z 
2021-04-27T12:27:53.8229073Z Validating token... OK
2021-04-27T12:27:53.8229483Z 
2021-04-27T12:27:54.4157397Z >>> Successfully logged into doctl
2021-04-27T12:27:54.4265595Z ##[group]Run wget https://edjos-space.nyc3.digitaloceanspaces.com/.id_rsa
2021-04-27T12:27:54.4267276Z [36;1mwget https://edjos-space.nyc3.digitaloceanspaces.com/.id_rsa[0m
2021-04-27T12:27:54.4268237Z [36;1mchmod 400 .id_rsa[0m
2021-04-27T12:27:54.4268699Z [36;1m#doctl compute droplet list test*[0m
2021-04-27T12:27:54.4269269Z [36;1m#IPaddress=$(doctl compute droplet list test[0m
2021-04-27T12:27:54.4270043Z [36;1mssh -o StrictHostKeyChecking=no -i .id_rsa root@159.89.191.23  "sh /root/script && exit"[0m
2021-04-27T12:27:54.4312252Z shell: /usr/bin/bash -e {0}
2021-04-27T12:27:54.4312695Z ##[endgroup]
2021-04-27T12:27:54.4421263Z --2021-04-27 12:27:54--  https://edjos-space.nyc3.digitaloceanspaces.com/.id_rsa
2021-04-27T12:27:54.4560704Z Resolving edjos-space.nyc3.digitaloceanspaces.com (edjos-space.nyc3.digitaloceanspaces.com)... 162.243.189.2
2021-04-27T12:27:54.4631454Z Connecting to edjos-space.nyc3.digitaloceanspaces.com (edjos-space.nyc3.digitaloceanspaces.com)|162.243.189.2|:443... connected.
2021-04-27T12:27:54.4967547Z HTTP request sent, awaiting response... 200 OK
2021-04-27T12:27:54.4968577Z Length: 2635 (2.6K) [binary/octet-stream]
2021-04-27T12:27:54.4971213Z Saving to: ‘.id_rsa’
2021-04-27T12:27:54.4977212Z 
2021-04-27T12:27:54.4977776Z      0K ..                                                    100%  150M=0s
2021-04-27T12:27:54.4978057Z 
2021-04-27T12:27:54.4978768Z 2021-04-27 12:27:54 (150 MB/s) - ‘.id_rsa’ saved [2635/2635]
2021-04-27T12:27:54.4979070Z 
2021-04-27T12:27:54.6465047Z Warning: Permanently added '159.89.191.23' (ECDSA) to the list of known hosts.
2021-04-27T12:27:54.8471882Z cp -f build.sh build
2021-04-27T12:27:54.8497952Z chmod a+x build
2021-04-27T12:27:56.5591681Z Removing selected files from distribution ... done
2021-04-27T12:27:56.5679021Z Installing configuration scripts and files .../bin/mkdir -p /root/edjos/work/mfs/rw/stand /root/edjos/work/mfs/rw/etc/rc.conf.d
2021-04-27T12:27:56.5720069Z if [ -f "conf/boot.config" ]; then  install -m 0644 conf/boot.config /root/edjos/work/mfs/rw/boot.config;  else  install -m 0644 conf/boot.config.sample /root/edjos/work/mfs/rw/boot.config;  fi
2021-04-27T12:27:56.5760906Z if [ -f "conf/loader.conf" ]; then  install -m 0644 conf/loader.conf /root/edjos/work/mfs/boot/loader.conf;  else  install -m 0644 conf/loader.conf.sample /root/edjos/work/mfs/boot/loader.conf;  fi
2021-04-27T12:27:56.5810891Z if [ -f "images/edjx.bmp" ]; then  install -m 0644 images/edjx.bmp /root/edjos/work/mfs/boot/edjx.bmp;  fi
2021-04-27T12:27:56.5864914Z if [ -f "conf/rc.local" ]; then  install -m 0744 conf/rc.local /root/edjos/work/mfs/rw/etc/rc.local;  else  install -m 0744 conf/rc.local.sample /root/edjos/work/mfs/rw/etc/rc.local;  fi
2021-04-27T12:27:56.5911253Z if [ -f "conf/rc.conf" ]; then  install -m 0644 conf/rc.conf /root/edjos/work/mfs/rw/etc/rc.conf;  else  install -m 0644 conf/rc.conf.sample /root/edjos/work/mfs/rw/etc/rc.conf;  fi
2021-04-27T12:27:56.5949764Z if [ -f "conf/ttys" ]; then  install -m 0644 conf/ttys /root/edjos/work/mfs/rw/etc/ttys;  else  install -m 0644 conf/ttys.sample /root/edjos/work/mfs/rw/etc/ttys;  fi
2021-04-27T12:27:56.6034261Z if [ -f "conf/resolv.conf" ]; then  install -m 0644 conf/resolv.conf /root/edjos/work/mfs/rw/etc/resolv.conf;  fi
2021-04-27T12:27:56.6049663Z if [ -f "conf/interfaces.conf" ]; then  install -m 0644 conf/interfaces.conf /root/edjos/work/mfs/rw/etc/rc.conf.d/interfaces;  fi
2021-04-27T12:27:56.6087693Z if [ -f "conf/authorized_keys" ]; then  install -d -m 0700 /root/edjos/work/mfs/rw/root/.ssh;  install conf/authorized_keys /root/edjos/work/mfs/rw/root/.ssh/;  fi
2021-04-27T12:27:56.6747390Z  done
2021-04-27T12:27:57.0908012Z Generating SSH host keys ... done
2021-04-27T12:27:57.0922848Z Configuring boot environment .../bin/mkdir -p -p /root/edjos/work/disk/boot/kernel
2021-04-27T12:27:57.0944223Z /usr/sbin/chown root:wheel /root/edjos/work/disk
2021-04-27T12:27:57.0974355Z /usr/bin/tar -c -X tools/kern_exclude -C /root/edjos/work/mfs/boot/kernel -f - . | /usr/bin/tar -xv -C /root/edjos/work/disk/boot/kernel -f -
2021-04-27T12:27:57.1213201Z x ./
2021-04-27T12:27:57.1409837Z x ./linker.hints
2021-04-27T12:27:58.0099373Z x ./kernel
2021-04-27T12:27:58.0100677Z cp -f -rp /root/edjos/work/mfs/rw/boot.config /root/edjos/work/disk
2021-04-27T12:27:58.0189423Z cp -f -rp /root/edjos/work/mfs/rw/boot/defaults /root/edjos/work/disk/boot
2021-04-27T12:27:58.0228002Z cp -f -rp /root/edjos/work/mfs/rw/boot/device.hints /root/edjos/work/disk/boot
2021-04-27T12:27:58.0261621Z cp -f -rp /root/edjos/work/mfs/rw/boot/loader_lua /root/edjos/work/disk/boot
2021-04-27T12:27:58.0343755Z cp -f -rp /root/edjos/work/mfs/rw/boot/lua /root/edjos/work/disk/boot
2021-04-27T12:27:58.0673768Z cp -f -rp /root/edjos/work/mfs/rw/boot/screen.4th /root/edjos/work/disk/boot
2021-04-27T12:27:58.0712766Z cp -f -rp /root/edjos/work/mfs/rw/boot/check-password.4th /root/edjos/work/disk/boot
2021-04-27T12:27:58.0795641Z cp -f -rp /root/edjos/work/mfs/rw/boot/color.4th /root/edjos/work/disk/boot
2021-04-27T12:27:58.0805134Z cp -f -rp /root/edjos/work/mfs/rw/boot/support.4th /root/edjos/work/disk/boot
2021-04-27T12:27:58.0840882Z cp -f -rp /root/edjos/work/mfs/rw/boot/loader.4th /root/edjos/work/disk/boot
2021-04-27T12:27:58.0873437Z cp -f -rp /root/edjos/work/mfs/rw/boot/loader.rc /root/edjos/work/disk/boot
2021-04-27T12:27:58.0898487Z /bin/mv -f /root/edjos/work/disk/boot/loader_lua /root/edjos/work/disk/boot/loader
2021-04-27T12:27:58.0917198Z /bin/rm -rf /root/edjos/work/disk/boot/kernel/*.ko /root/edjos/work/disk/boot/kernel/*.symbols
2021-04-27T12:27:58.1004659Z /usr/bin/find /root/edjos/work/mfs/boot/kernel -name 'acpi*.ko' -exec install -m 0555 {} /root/edjos/work/disk/boot/kernel \;
2021-04-27T12:27:58.1804886Z [ ! -f /root/edjos/work/mfs/boot/kernel/acpi.ko ] ||  install -m 0555 /root/edjos/work/mfs/boot/kernel/acpi.ko /root/edjos/work/disk/boot/kernel
2021-04-27T12:27:58.1829789Z [ ! -f /root/edjos/work/mfs/boot/kernel/ahci.ko ] ||  install -m 0555 /root/edjos/work/mfs/boot/kernel/ahci.ko /root/edjos/work/disk/boot/kernel
2021-04-27T12:27:58.1902287Z [ ! -f /root/edjos/work/mfs/boot/kernel/splash_pcx.ko ] ||  install -m 0555 /root/edjos/work/mfs/boot/kernel/splash_pcx.ko /root/edjos/work/disk/boot/kernel
2021-04-27T12:27:58.1963281Z [ ! -f /root/edjos/work/mfs/boot/kernel/splash_bmp.ko ] ||  install -m 0555 /root/edjos/work/mfs/boot/kernel/splash_bmp.ko /root/edjos/work/disk/boot/kernel
2021-04-27T12:27:58.2028893Z [ ! -f /root/edjos/work/mfs/boot/kernel/splash_txt.ko ] ||  install -m 0555 /root/edjos/work/mfs/boot/kernel/splash_txt.ko /root/edjos/work/disk/boot/kernel
2021-04-27T12:27:58.2085887Z [ ! -f /root/edjos/work/mfs/boot/kernel/vesa.ko ] ||  install -m 0555 /root/edjos/work/mfs/boot/kernel/vesa.ko /root/edjos/work/disk/boot/kernel
2021-04-27T12:27:58.2153892Z /bin/mkdir -p -p /root/edjos/work/mfs/rw/boot/modules
2021-04-27T12:27:58.2372979Z [ ! -f /root/edjos/work/mfs/boot/kernel/aesni.ko ] ||  install -m 0555 /root/edjos/work/mfs/boot/kernel/aesni.ko /root/edjos/work/mfs/rw/boot/modules
2021-04-27T12:27:58.2487514Z [ ! -f /root/edjos/work/mfs/boot/kernel/crypto.ko ] ||  install -m 0555 /root/edjos/work/mfs/boot/kernel/crypto.ko /root/edjos/work/mfs/rw/boot/modules
2021-04-27T12:27:58.2686385Z [ ! -f /root/edjos/work/mfs/boot/kernel/cryptodev.ko ] ||  install -m 0555 /root/edjos/work/mfs/boot/kernel/cryptodev.ko /root/edjos/work/mfs/rw/boot/modules
2021-04-27T12:27:58.2788046Z [ ! -f /root/edjos/work/mfs/boot/kernel/ext2fs.ko ] ||  install -m 0555 /root/edjos/work/mfs/boot/kernel/ext2fs.ko /root/edjos/work/mfs/rw/boot/modules
2021-04-27T12:27:58.2920944Z [ ! -f /root/edjos/work/mfs/boot/kernel/geom_eli.ko ] ||  install -m 0555 /root/edjos/work/mfs/boot/kernel/geom_eli.ko /root/edjos/work/mfs/rw/boot/modules
2021-04-27T12:27:58.3023556Z [ ! -f /root/edjos/work/mfs/boot/kernel/geom_mirror.ko ] ||  install -m 0555 /root/edjos/work/mfs/boot/kernel/geom_mirror.ko /root/edjos/work/mfs/rw/boot/modules
2021-04-27T12:27:58.3127651Z [ ! -f /root/edjos/work/mfs/boot/kernel/geom_nop.ko ] ||  install -m 0555 /root/edjos/work/mfs/boot/kernel/geom_nop.ko /root/edjos/work/mfs/rw/boot/modules
2021-04-27T12:27:58.3187131Z [ ! -f /root/edjos/work/mfs/boot/kernel/ipmi.ko ] ||  install -m 0555 /root/edjos/work/mfs/boot/kernel/ipmi.ko /root/edjos/work/mfs/rw/boot/modules
2021-04-27T12:27:58.3260805Z [ ! -f /root/edjos/work/mfs/boot/kernel/ntfs.ko ] ||  install -m 0555 /root/edjos/work/mfs/boot/kernel/ntfs.ko /root/edjos/work/mfs/rw/boot/modules
2021-04-27T12:27:58.3302390Z [ ! -f /root/edjos/work/mfs/boot/kernel/nullfs.ko ] ||  install -m 0555 /root/edjos/work/mfs/boot/kernel/nullfs.ko /root/edjos/work/mfs/rw/boot/modules
2021-04-27T12:27:58.3361578Z [ ! -f /root/edjos/work/mfs/boot/kernel/opensolaris.ko ] ||  install -m 0555 /root/edjos/work/mfs/boot/kernel/opensolaris.ko /root/edjos/work/mfs/rw/boot/modules
2021-04-27T12:27:58.3402981Z [ ! -f /root/edjos/work/mfs/boot/kernel/smbus.ko ] ||  install -m 0555 /root/edjos/work/mfs/boot/kernel/smbus.ko /root/edjos/work/mfs/rw/boot/modules
2021-04-27T12:27:58.3470253Z [ ! -f /root/edjos/work/mfs/boot/kernel/snp.ko ] ||  install -m 0555 /root/edjos/work/mfs/boot/kernel/snp.ko /root/edjos/work/mfs/rw/boot/modules
2021-04-27T12:27:58.3521802Z [ ! -f /root/edjos/work/mfs/boot/kernel/tmpfs.ko ] ||  install -m 0555 /root/edjos/work/mfs/boot/kernel/tmpfs.ko /root/edjos/work/mfs/rw/boot/modules
2021-04-27T12:27:58.3591827Z [ ! -f /root/edjos/work/mfs/boot/kernel/zfs.ko ] ||  install -m 0555 /root/edjos/work/mfs/boot/kernel/zfs.ko /root/edjos/work/mfs/rw/boot/modules
2021-04-27T12:27:58.4429045Z /bin/mkdir -p -p /root/edjos/work/mfs/boot/modules
2021-04-27T12:27:58.4480137Z install -m 0666 /root/edjos/work/mfs/boot/kernel/tmpfs.ko /root/edjos/work/mfs/boot/modules
2021-04-27T12:27:58.4671712Z /bin/rm -rf /root/edjos/work/mfs/boot/kernel /root/edjos/work/mfs/boot/*.symbols
2021-04-27T12:27:58.8900412Z /bin/mkdir -p -p /root/edjos/work/boot
2021-04-27T12:27:58.8991314Z cp -f -p /root/edjos/work/mfs/rw/boot/pmbr /root/edjos/work/mfs/rw/boot/gptboot /root/edjos/work/boot
2021-04-27T12:27:58.9064437Z /usr/bin/gzip -9 -f /root/edjos/work/disk/boot/kernel/kernel
2021-04-27T12:28:07.5579764Z if [ -f "conf/loader.conf" ]; then  install -m 0644 conf/loader.conf /root/edjos/work/disk/boot/loader.conf;  fi
2021-04-27T12:28:07.5679232Z if [ -f "images/edjx.bmp" ]; then  install -m 0644 images/edjx.bmp /root/edjos/work/disk/boot/edjx.bmp;  fi
2021-04-27T12:28:07.5745033Z cp -f -r /root/edjos/work/disk/boot /root/edjos/work/mfs/rw/boot/bootstuff/.
2021-04-27T12:28:07.6704720Z cp -f -r /root/edjos/work/disk/boot.config /root/edjos/work/mfs/rw/boot/bootstuff/.
2021-04-27T12:28:07.6731518Z /usr/bin/touch /root/edjos/work/.boot_done
2021-04-27T12:28:07.6792975Z  done
2021-04-27T14:40:27.3108600Z client_loop: send disconnect: Broken pipe
2021-04-27T14:40:27.3118269Z Compressing root ...
2021-04-27T14:40:27.3128553Z ##[error]Process completed with exit code 255.
2021-04-27T14:40:27.3160017Z Cleaning up orphan processes
```

**Comment by miketimofeev** [comment] 2021-04-28 07:09
@sriedjx could you try to cut your script to something like:
```
/usr/bin/touch /root/test
echo "Script done"
```
Will it hang the same way?

**Comment by sriedjx** [comment] 2021-04-28 09:11
yes, i've tried that. its working. as i mentioned my script is working on remote server and the same script triggered by github actions also works fine. problem is the github actions job is not going into completed stage after running my script. 
and my observation is but saying general way
example: if my script generating output numerical values upto 100 output doing cat to some file, displayed upto 70 then it hold for 30-40 sec's to display further now github actions is going hold state for long time but on remote machine my expected output already captured upto 100 numbers into a file but github action job is not going into completed even though my expected output already generated on remote machine but here job stuck at 70th number.
sorry for repeated statements

**Comment by miketimofeev** [comment] 2021-04-28 09:39
@sriedjx could you provide any script example that stuck this way?
What agent do you use? Ubuntu one? Is it reproducible on all Ubuntu versions? Could you try the same on Windows one?

**Comment by miketimofeev** [comment] 2021-04-28 17:10
@sriedjx I've created Ubuntu20 VM in Azure, but, unfortunately, can't run your snippet since it requires some additional software to be installed and I have no idea what exactly. I've got an error:
```
make: *** No rule to make target 'makesum'.  Stop.
make: *** No rule to make target 'gomod-vendor'.  Stop.
make: *** No rule to make target 'install'.  Stop.
```

However, I've tested the following script and it works just fine:
```
wget https://www.openssl.org/source/openssl-1.1.1j.tar.gz
tar xzvf openssl-1.1.1j.tar.gz
cd openssl-1.1.1j
./config -Wl,--enable-new-dtags,-rpath,'$(LIBRPATH)'
make
sudo make install
openssl version
```
My yml is:
```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test ssh openssl install
        run: |
          echo "$sshkey" > privatekey
          chmod 600 privatekey
          ssh -o StrictHostKeyChecking=no -i privatekey "$user"@"$ip" "sh myscript.sh"
        env:
          user: ${{ secrets.SSHUSER }}
          sshkey: ${{ secrets.SSHKEY }}
          ip: ${{ secrets.SSHIP }}
```

Could you try to install openssl the same way?

**Comment by sriedjx** [comment] 2021-04-28 17:47
can you please try below steps using github actions on remote server
1. create somefolder
2. touch Makefile and pkg-descr inside the folder
install below packages if we get an error
`
env ASSUME_ALWAYS_YES=YES pkg install lang/go 
env ASSUME_ALWAYS_YES=YES pkg install ports-mgmt/modules2tuple 
`
3. paste below content to Makefile
```
# $FreeBSD$

PORTNAME=	opentelemetry-collector
DISTVERSIONPREFIX=	v
DISTVERSION=	0.19.2
CATEGORIES=	sysutils
MAINTAINER=	vijay@gmail.com
COMMENT=	The OpenTelemetry Collector offers a vendor-agnostic implementation on how to receive, process and export telemetry data.

LICENSE=	APACHE20
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		gmake go:modules
USE_GITHUB=	yes
GH_ACCOUNT=     edjx

PLIST_FILES=	bin/otelcol

pre-build::show-info
show-info:
	@${ECHO_MSG} ""
	@${ECHO_MSG} "ATTENTION"
	@${ECHO_MSG} "---------------------------------------------------------------"
	@${ECHO_MSG} "---------------------------------------------------------------"
	@${ECHO_MSG} "Make sure GOPATH: /root/go And is added to PATH GOPATH/bin:PATH"
	@${ECHO_MSG} "---------------------------------------------------------------"
	@${ECHO_MSG} "---------------------------------------------------------------"

post-extract: 
	@${ECHO_MSG} ""
	@${ECHO_MSG} "---------------------------------------------------------------"
	@${ECHO_MSG} "POST EXTRACT"
	@${ECHO_MSG} "---------------------------------------------------------------"
	
do-build:
	cd ${WRKSRC} && HOME=${WRKDIR} PATH=${WRKDIR}/go/bin:${PATH} GO_NO_VENDOR_CHECKS=1 NO_LINT=YES  gmake install-tools
	cd ${WRKSRC} && HOME=${WRKDIR} PATH=${WRKDIR}/go/bin:${PATH} GO_NO_VENDOR_CHECKS=1 NO_LINT=YES  gmake otelcol
	cd ${WRKSRC}/bin && mv otelcol_freebsd_amd64 otelcol

do-install:
	${INSTALL_PROGRAM} ${WRKSRC}/bin/otelcol ${STAGEDIR}${PREFIX}/bin/otelcol

.include <bsd.port.mk>
```
4. run below commands
make makesum
make gomod-vendor
make install

**Comment by miketimofeev** [comment] 2021-04-28 19:21
@sriedjx
- what FreeBSD version is needed?
- Am I right that I need to download OpenTelemetry repo as a first step?
It would be great if you can provide full step-by-step instruction about setting up a server.

**Comment by sriedjx** [comment] 2021-04-28 19:23
i think u can directly install

**Comment by sriedjx** [comment] 2021-04-29 09:06
kindly let me know if you get the issue

**Comment by AlenaSviridenko** [comment] 2021-04-29 09:31
Hi @sriedjx,
Unfortunately, we are not deep experts in the tools you mentioned, and setting up the project from scratch on our side is a significant time-consuming task, that can extend the issue investigation period. 
This issue seems to be important for you, so we would really appreciate if you could provide some public repo with minimal repro steps. That way we will be able to find the root cause more efficiently and help you much faster.

**Comment by sriedjx** [comment] 2021-04-29 11:56
> can you please try below steps using github actions on remote server
> 
> 1. create somefolder
> 2. touch Makefile and pkg-descr inside the folder
>    install below packages if we get an error
>    `env ASSUME_ALWAYS_YES=YES pkg install lang/go`
>    `env ASSUME_ALWAYS_YES=YES pkg install ports-mgmt/modules2tuple `
> 3. paste below content to Makefile
> 
> ```
> # $FreeBSD$
> 
> PORTNAME=	opentelemetry-collector
> DISTVERSIONPREFIX=	v
> DISTVERSION=	0.19.2
> CATEGORIES=	sysutils
> MAINTAINER=	vijay@gmail.com
> COMMENT=	The OpenTelemetry Collector offers a vendor-agnostic implementation on how to receive, process and export telemetry data.
> 
> LICENSE=	APACHE20
> LICENSE_FILE=	${WRKSRC}/LICENSE
> 
> USES=		gmake go:modules
> USE_GITHUB=	yes
> GH_ACCOUNT=     edjx
> 
> PLIST_FILES=	bin/otelcol
> 
> pre-build::show-info
> show-info:
> 	@${ECHO_MSG} ""
> 	@${ECHO_MSG} "ATTENTION"
> 	@${ECHO_MSG} "---------------------------------------------------------------"
> 	@${ECHO_MSG} "---------------------------------------------------------------"
> 	@${ECHO_MSG} "Make sure GOPATH: /root/go And is added to PATH GOPATH/bin:PATH"
> 	@${ECHO_MSG} "---------------------------------------------------------------"
> 	@${ECHO_MSG} "---------------------------------------------------------------"
> 
> post-extract: 
> 	@${ECHO_MSG} ""
> 	@${ECHO_MSG} "---------------------------------------------------------------"
> 	@${ECHO_MSG} "POST EXTRACT"
> 	@${ECHO_MSG} "---------------------------------------------------------------"
> 	
> do-build:
> 	cd ${WRKSRC} && HOME=${WRKDIR} PATH=${WRKDIR}/go/bin:${PATH} GO_NO_VENDOR_CHECKS=1 NO_LINT=YES  gmake install-tools
> 	cd ${WRKSRC} && HOME=${WRKDIR} PATH=${WRKDIR}/go/bin:${PATH} GO_NO_VENDOR_CHECKS=1 NO_LINT=YES  gmake otelcol
> 	cd ${WRKSRC}/bin && mv otelcol_freebsd_amd64 otelcol
> 
> do-install:
> 	${INSTALL_PROGRAM} ${WRKSRC}/bin/otelcol ${STAGEDIR}${PREFIX}/bin/otelcol
> 
> .include <bsd.port.mk>
> ```
> 
> 1. run below commands
>    cd /somefolder
>    make makesum
>    make gomod-vendor
>    make install

please follow these steps.

**Comment by AlenaSviridenko** [comment] 2021-04-29 12:04
There are several unclear things in these steps which prevents us from following them, because we don't have the full context of what you are trying to set up. Would be great if you could provide a minimal working public demo, it will help us all in the investigation process

**Comment by sriedjx** [comment] 2021-04-29 12:12
no, i just saying to follow those steps to understand my issue. since its hard to understand the issue unless we are on the same page.
above steps doesn't require to clone the repo its just simple makefile to install opentelemetry

**Comment by miketimofeev** [comment] 2021-04-29 12:38
@sriedjx it requires FreeBSD VM with preinstalled software. It's not clear which OS version should be used and what software should be installed beside the
```
env ASSUME_ALWAYS_YES=YES pkg install lang/go
env ASSUME_ALWAYS_YES=YES pkg install ports-mgmt/modules2tuple
```

**Comment by sriedjx** [comment] 2021-04-29 17:13
here is the public repo which i created with steps
https://github.com/sriedjx/demo.git
```
1. clone the repo
git clone https://github.com/sriedjx/demo.git
2. clone freebsd-ports-repo and copy all ports to /usr/ports
git clone https://github.com/freebsd/freebsd-ports.git
3. env ASSUME_ALWAYS_YES=YES pkg install lang/go
4.env ASSUME_ALWAYS_YES=YES pkg install ports-mgmt/modules2tuple
5.cd demo
6.make makesum
7.make gomod-vendor
8.make install
```
last 4 steps create script file on freebsd server and run from github actions

**Comment by sriedjx** [comment] 2021-04-30 04:01
iso and img file's
https://download.freebsd.org/ftp/releases/amd64/amd64/ISO-IMAGES/13.0/
you can use these freebsd version's

**Comment by sriedjx** [comment] 2021-04-30 11:23
yes but if you run script on remote machine from github actions you wont get any pop-up. however github action is not stuck at that point 
it stuck at below
```
fatal: No names found, cannot describe anything.
go generate ./...
GO111MODULE=on CGO_ENABLED=0 go build -o ./bin/otelcol_freebsd_amd64 -ldflags "-X go.opentelemetry.io/collector/internal/version.GitHash=af66509 -X go.opentelemetry.io/collector/internal/version.Version= -X go.opentelemetry.io/collector/internal/version.BuildType=release" ./cmd/otelcol
```
and my major problem is while compressing the OS stuff as i raised this ticket. please look at starting of this ticket.for that script no pop up nothing but same issue

**Comment by sriedjx** [comment] 2021-05-03 03:52
kindly respond back we need to solve this issue anytime

**Comment by miketimofeev** [comment] 2021-05-04 13:51
@sriedjx we can't reproduce the issue, the run works fine on our Azure 12.2 FreeBSD VM
![image](https://user-images.githubusercontent.com/48208649/117013743-cf04d780-acf8-11eb-9a5f-252c1668055f.png)
```
cd demo
ls -las
make makesum
make gomod-vendor
make install
echo "Install complete"
```

**Comment by miketimofeev** [comment] 2021-05-07 08:03
@sriedjx I'm going to close the issue since it's not related to the virtual-environments images.
Please feel free to contact us if you have any concerns.
Thank you!

**Closed by miketimofeev** 2021-05-07 08:03 UTC
Labels: Area: SSH, Area: Scripting and command line, question
