### ISSUE TITLE
Mac OS X jobs frequently fail for no apparent reason with missing logs and without ever running `if: always ()` steps

### ISSUE THREAD

**Issue by JasonGross** [actions/virtual-environments#736] opened 2020-04-17 02:46 UTC
**Describe the bug**
Frequently my Mac OS X jobs fail.  Usually, when a job fails, the subsequent steps display as canceled and take 0s, and the `if: always ()` steps run anyway, as in:
![image](https://user-images.githubusercontent.com/396076/79526421-4060e200-8033-11ea-828c-391a7675bf27.png)
(From https://github.com/mit-plv/fiat-crypto/runs/593609449?check_suite_focus=true )
However, the Mac job failures, such as https://github.com/mit-plv/fiat-crypto/pull/753/checks?check_run_id=593732097 , display broken logs, where the failing step has no contents (no down arrow), and all subsequent steps fail with 0s, including the `if: always ()` steps:
![image](https://user-images.githubusercontent.com/396076/79526538-828a2380-8033-11ea-8536-1f210e3b137f.png)
Furthermore, if I click the three dots and click "View raw logs", the logs are missing; I get directed to a page like https://github.com/mit-plv/fiat-crypto/commit/c31a955db7a356f1788d979ac9b1ed1a4fc67674/checks/593732097/logs which says only
```
2020-04-16T22:40:17.1881748Z ##[section]Starting: Request a runner to run this job
2020-04-16T22:40:17.9419267Z Requesting a hosted runner in current repository's account/organization with labels: 'macos-latest', require runner match: True
2020-04-16T22:40:18.0349714Z Labels matched hosted runners has been found, waiting for one of them get assigned for this job.
2020-04-16T22:40:18.0610578Z ##[section]Finishing: Request a runner to run this job
```

**Area for Triage**: Apple

**Question, Bug, or Feature?**: Bug

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
I should get sensible logs, or, better, the jobs should not be failing at all (they work fine if I restart the job enough times, and they work fine consistently on Linux and often on Windows)

**Actual behavior**
See above.  Link: https://github.com/mit-plv/fiat-crypto/pull/753/checks?check_run_id=593732097

**Comment by maxim-lobanov** [comment] 2020-04-17 04:32
@JasonGross , thank you for report of this issue!
Unfortunately, this repository manages only image content but we will try to escalate this issue to appropriate team.

@TingluoHuang , @ericsciple , @alepauly , is it something that [actions/runner](https://github.com/actions/runner) does?

**Comment by TingluoHuang** [comment] 2020-04-17 12:16
@maxim-lobanov can you check runner diagnostic for this job to see why the runner can't upload log? I don't know how to access the runner log for hosted mac pool.

**Comment by JasonGross** [comment] 2020-04-21 23:34
I'm now seeing this happen on our Linux jobs too, such as https://github.com/mit-plv/fiat-crypto/pull/766/checks?check_run_id=606437846
![image](https://user-images.githubusercontent.com/396076/79924871-fe56e800-8406-11ea-8ab4-21f10247988a.png)
It seems to be happening on the artifact upload step on Linux, maybe the machines are running out of space or something?

**Comment by maxim-lobanov** [comment] 2020-04-28 14:47
Hello, Just a quick update, issue can come from bug on our backend. We are still looking at it.

**Comment by maxim-lobanov** [comment] 2020-05-08 04:02
@JasonGross , Hello!
Could you please check if you still see the same issues?

**Comment by maxim-lobanov** [comment] 2020-05-14 05:36
Closing this for now but please let us know if you still see the same issue

**Comment by JasonGross** [comment] 2020-05-21 23:24
It's been happening less often, but it just happened again : https://github.com/JasonGross/fiat-crypto/runs/697783422
![image](https://user-images.githubusercontent.com/396076/82615497-95df6000-9b98-11ea-8b65-e616b2c5db72.png)

I've also seen the Mac OS jobs frequently show up as "cancelled" when I didn't cancel them, and I don't believe anyone else did, either.

So I guess this issue should be re-opened

**Comment by svenmuennich** [comment] 2020-06-10 06:21
We've had the same issue on one of our builds scheduled to run Monday through Friday at 01:30 UTC. It would be cancelled _randomly_ after running for about 10-15 minutes.

Last night it succeeded for the first time in weeks but I will continue to monitor.

**Comment by JasonGross** [comment] 2020-06-21 02:31
I've also had frequent random cancellations of GH Actions jobs (especially Mac OS), with missing logs, such as https://github.com/mit-plv/fiat-crypto/runs/791672004?check_suite_focus=true
![image](https://user-images.githubusercontent.com/396076/85215351-55b10000-b345-11ea-93dd-96291c571ad9.png)
And here's one where the logs are present https://github.com/mit-plv/fiat-crypto/runs/791678094?check_suite_focus=true :
![image](https://user-images.githubusercontent.com/396076/85215364-7711ec00-b345-11ea-9363-af6cac4c4fc7.png)

GitHub won't even tell me who canceled these jobs, or why they were canceled.  (Was it because I pushed another commit that triggered the workflow?  Is GitHub now forcibly canceling jobs on old commits, even those which are on the tip of their branch but are not the newest one running across all branches?)

**Comment by cytopia** [comment] 2020-06-21 07:31
I can also confirm that jobs on MacOS are cancelled for no apparent reason: https://github.com/cytopia/pwncat/pull/80/checks?check_run_id=792119613

Additionally to say there are not logs or other info regarding why it had been cancelled

**Comment by TingluoHuang** [comment] 2020-06-22 18:41
Related: https://github.com/github/c2c-actions-compute-sre/issues/927

**Comment by TingluoHuang** [comment] 2020-06-23 02:30
We fixed a configuration issue in the service that causes mac hosted build hit this error every day in 1:00-2:00 AM UTC

**Comment by svenmuennich** [comment] 2020-06-23 05:52
> We fixed a configuration issue in the service that causes mac hosted build hit this error every day in 1:00-2:00 AM UTC

That sounds promising 🎉  Is that fix already live?

**Comment by TingluoHuang** [comment] 2020-06-23 14:27
@svenmuennich the fix is already live, and I can confirm from the telemetry that the fix works as expected.

👇 we no longer have the big spike every night.
![image](https://user-images.githubusercontent.com/1750815/85416043-07198680-b53c-11ea-83ce-5c71de2a7053.png)

**Comment by svenmuennich** [comment] 2020-06-24 06:04
Great! Thank you 🥇

**Comment by maxim-lobanov** [comment] 2020-06-24 06:25
Will keep this issue opened for a few more days, @svenmuennich , @cytopia , @JasonGross , could you please report back if you still see the same issues

**Comment by maxim-lobanov** [comment] 2020-06-24 17:07
@TingluoHuang , can it be something different?

**Comment by TingluoHuang** [comment] 2020-06-24 17:49
@maxim-lobanov yes, https://github.com/mit-plv/fiat-crypto/pull/817/checks?check_run_id=802532325 failed due to https://github.com/github/c2c-actions-compute/issues/643 which is not the one I fixed.

**Comment by JasonGross** [comment] 2020-06-24 18:05
https://github.com/github/c2c-actions-compute/issues/643 is a 404 for me; is there any issue I can track about this (other than this present one)?

**Comment by svenmuennich** [comment] 2020-06-26 08:55
Last night our scheduled build failed again. This time we got an error though:
```
An error occurred while provisioning resources (Error Type: Disconnect).
```

No idea whether that is related to this issue.

**Comment by maxim-lobanov** [comment] 2020-08-19 19:24
Hello everyone!
We have recently done some changes on our side. Could you please check if you still see the same issue (steps without logs)?

**Closed** 2020-08-31 12:44 UTC
Labels: Area: Apple, OS: macOS, investigate

**Comment by alexanderkasten** [comment] 2020-10-07 07:54
> Hello everyone!
> We have recently done some changes on our side. Could you please check if you still see the same issue (steps without logs)?

I have the same problem on macOS https://github.com/atlas-engine/AtlasStudio/runs/1215960239.
<img width="1657" alt="Bildschirmfoto 2020-10-07 um 09 52 58" src="https://user-images.githubusercontent.com/17065920/95303045-04406880-0883-11eb-810f-ceea6bc9e6e4.png">

**Comment by j-stephan** [comment] 2021-06-01 10:22
@maxim-lobanov: We also observe this behaviour from time to time. Example: https://github.com/alpaka-group/alpaka/runs/2708464529?check_suite_focus=true

**Comment by JasonGross** [comment] 2021-07-04 02:21
@maxim-lobanov Would you reopen this bug?  https://github.com/mit-plv/fiat-crypto/runs/2979458972 has the log-less red ❌'s with missing raw logs
![image](https://user-images.githubusercontent.com/396076/124371097-86ac5c00-dc4c-11eb-8003-f50f1d85b564.png)
```
2021-07-03T15:24:52.2128487Z Can't find any online and idle self-hosted or hosted runner in the current repository, account/organization that matches the required labels: 'macos-latest'
2021-07-03T15:24:52.2128608Z Found online and busy hosted runner(s) in the current repository's organization account that matches the required labels: 'macos-latest'. Hit concurrency limits on the hosted runners. Waiting for one of them to get assigned for this job.
2021-07-03T15:24:52.2128637Z Waiting for a hosted runner in 'organization' to pick this job...
```
Download log archive results in an archive which simply does not contain logs for any of the red ❌'s, and with the same incomplete raw logs.

**Comment by miketimofeev** [comment] 2021-07-05 07:08
Hi @JasonGross! Sorry to hear that. 
I've checked the telemetry and the root cause seems to be the same as here — https://github.com/actions/virtual-environments/issues/3517
We will notify the engineering team about these new cases.

**Comment by deivid-rodriguez** [comment] 2021-07-05 10:53
We're also getting this. Just informing in case having more examples can help isolating the root cause. Example run at https://github.com/rubygems/rubygems/runs/2987926029.

**Comment by adam84luong** [comment] 2021-07-18 01:03
![image](https://user-images.githubusercontent.com/423967/126052522-4836a9ec-aea7-4d42-8980-86e026717e5d.png)

I still got the issue, it keep processing very long time and finally automatically canceled with no reason.
while that step in progress, no logs is generated. And if I try to "View Raw Logs" it shows like below

![image](https://user-images.githubusercontent.com/423967/126052538-71170731-bd82-45e5-83bb-7ead96fd0ed4.png)

**Comment by JanBessai** [comment] 2021-08-24 16:02
Same issue.. "Run tests" part of MacOS-latest jobs randomly hang or take forever in https://github.com/combinators/cls-scala
Decided to factor them out into a separate workflow so I can restart them more easily until this gets resolved.

**Comment by JanBessai** [comment] 2021-09-30 12:52
Any update on this?
