### ISSUE TITLE
Correct Node.js build failed after re-running. Docker compose environment variables error

### ISSUE THREAD

**Issue by sergeyampo** [actions/virtual-environments#2609] opened 2021-02-03 01:45 UTC
**Description**  
I have a trivial github actions script where I install yarn and run docker compose files with docker compose --env-file command.
I've restarted already successful build and got an error like:
`
The NODE_ENV variable is not set. Defaulting to a blank string. 
...
The WORKERPOOL_MAX_THREAD variable is not set. Defaulting to a blank string.
The Compose file '././deploy/containers/development/docker-compose.yml' is invalid because:
services.mongodb.ports contains an invalid type, it should be a number, or an object
services.node-app.ports contains an invalid type, it should be a number, or an object
services.redis.ports contains an invalid type, it should be a number, or an object
error Command failed with exit code 1.
...
`
Docker compose port section is working locally and as I said worked on actions before:
`
...
    ports:
      - ${NODE_PORT}:3000
    depends_on:
...
`
I already tried update docker to version 20, but it doesn't work.
**Area for Triage**:  
- valueFor: '**Area for Triage**'
  contains: 'JavaScript and Node.js'
  addLabels: ['Area: JavaScript and Node.js']

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [*] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
20210123.1
**Expected behavior**  
Successful job.

**Actual behavior**  
Error: Process completed with exit code 1.

**Repro steps**  
1. Install yarn
2. Run: /bin/bash ./deploy/stop-containers.sh && docker-compose --env-file ./deploy/env/development/.env -f ./deploy/containers/development/docker-compose.yml up --build --force-recreate -d

**Comment by Darleev** [comment] 2021-02-03 11:42
Hello @sergeyampo,
Our images keep all software in the actual(latest) stable version. Could you please try to upgrade your local docker-compose to the latest version as well?
Also, It would be great if you provide some sample project with minimal steps to reproduce.
I've tried to deploy hello-world,redis docker-compose .yml without any issues.
We are looking forward to your reply.

**Comment by sonallux** [comment] 2021-02-04 17:45
I have experienced the same issue and found the root cause: This is caused by `docker-compose` version `1.28.2` which got updated a few days ago. See the release notes of the [ubuntu-18.04](https://github.com/actions/virtual-environments/releases/tag/ubuntu18%2F20210131.1) or [ubuntu-20.04](https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20210131.1) environment.

`docker-compose` has changed how it is handling relative paths in the `--env-file` parameter. See this issue for more details: https://github.com/docker/compose/issues/8076.

**Comment by Darleev** [comment] 2021-02-08 10:20
Hello @sergeyampo,
Could you please check the replies above and provide the final result of your testing?

We are looking forward to your reply.

**Comment by Darleev** [comment] 2021-02-09 10:41
@sergeyampo I'm going to close the issue until further clarifications from your side.
In case of any questions, feel free to contact us.

**Closed by Darleev** 2021-02-09 10:41 UTC
Labels: Area: Deployment/Release, Area: Scripting and command line, investigate
