### ISSUE TITLE
Update/Add Ninja

### ISSUE THREAD

**Issue by sd185233** [actions/virtual-environments#1531] opened 2020-09-01 14:23 UTC
**Tool information**
- Tool name: Ninja
- Tool license: 
- Add or update? Add
- Desired version: 
- Approximate size: 
- If this is an add request:
  - Brief description of tool: Used for fast C++ builds
  - URL for tool's homepage: https://ninja-build.org/
  - Provide a basic test case to validate the tool's functionality: 

**Area for Triage**:

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [ ] macOS 10.15
- [ x] Ubuntu 16.04 LTS
- [x ] Ubuntu 18.04 LTS
- [x ] Ubuntu 20.04 LTS
- [ x] Windows Server 2016 R2
- [x ] Windows Server 2019

**Can this tool be installed during the build?**
Yes, need to download and add to path

**Tool installation time in runtime**

**Are you willing to submit a PR?**

Also, are there any plans for a CentOS hosted runner?

**Comment by dibir-magomedsaygitov** [comment] 2020-09-01 14:41
Hello, @sd185233.
Your request is a duplicate of [#741](https://github.com/actions/virtual-environments/issues/741). As were discussed in attached issue, currently we have no plans on adding ninja on our images.
I would like to suggest you to install ninja tool in runtime using the following steps:
```
# Ubuntu
sudo apt-get install ninja-build
# Windows
choco install ninja
```

As for your question related to centOS - currently we have no such plans. Different images and more flavors of existing images is something we're always considering. Unfortunately it is not possible for us to provide CentOS images at this time.

**Closed** 2020-09-01 14:43 UTC
Labels: feature request, needs triage

**Comment by marc-hb** [comment] 2024-12-22 18:48
> thanks for your suggestion but considering that it' easy to add Ninja to workflows on demand,...

I just asked runtime installation to be officially documented, please upvote:
- #11235 

Ever growing list of duplicates gathered at:
- https://github.com/actions/runner-images/issues/514#issuecomment-2558554588
