### ISSUE TITLE
Make it easier to output "Managed Images" or "Shared Gallery Images" from template

### ISSUE THREAD

**Issue by spoelstraethan** [actions/virtual-environments#3855] opened 2021-08-04 18:42 UTC
### Description

Currently we are building our own version of the agents to run in a Azure VM Scale Set in our accounts, but the VHD type throws a deprecation warning from Packer so we looked into "Managed Images" instead, and it turned out to be pretty easy, but not very streamlined, but it could be partially automated by integrating with the current Powershell scripts.

```
DEBUG:  217+      >>>> Get-LatestCommit -ErrorAction SilentlyContinue
DEBUG:   51+     process  >>>> {
DEBUG:   52+          >>>> Write-Host "Latest commit:"
Latest commit:
DEBUG:   53+          >>>> git --no-pager log --pretty=format:"Date: %cd; Commit: %H - %s; Author: %an <%ae>" -1
Date: Wed Jul 14 10:54:38 2021 +0000; Commit: ad358c8eb8fde1961567f6e3751ee47d66dc774a - Updating readme file for macOS-11 version 20210712.4 (#3723); Author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>DEBUG:   54+      >>>> }
DEBUG:  219+      >>>> $packerBinary = Get-Command "packer"
DEBUG:  220+     if ( >>>> -not ($packerBinary)) {
DEBUG:  224+     if( >>>> $RestrictToAgentIpAddress -eq $true) {
# ... snipped
vhd: output will be in this color.

==> vhd: Running builder ...
==> vhd: Getting tokens using client secret
==> vhd: Getting tokens using client secret
    vhd: Creating Azure Resource Manager (ARM) client ...
==> vhd: Warning: You are using Azure Packer Builder to create VHDs which is being deprecated, consider using Managed Images. Learn more https://www.packer.io/docs/builders/azure/arm#azure-arm-builder-specific-options
```

The code we are using to make the switch as part of our build pipeline.

```
            git clone https://github.com/actions/virtual-environments.git
            Set-Location ./virtual-environments
            $templatePath = "images\win\windows2019.json"
            $JSON = Get-Content -Path "$templatePath" -Raw | ConvertFrom-Json
            # Print the incoming JSON
            $JSON | ConvertTo-Json -Depth 4 | Out-Host
            # Remove the builder properties that are only for VHD builds
            # basically https://github.com/actions/virtual-environments/blob/d522cafafedd41e155754b78f292b14f3ff62870/images/win/windows2019.json#L45-L50
            $JSON.builders[0].psobject.properties.remove('resource_group_name')
            $JSON.builders[0].psobject.properties.remove('storage_account')
            $JSON.builders[0].psobject.properties.remove('capture_container_name')
            $JSON.builders[0].psobject.properties.remove('capture_name_prefix')
            
            # Assign new properties to the first (and only) element of array <builders>
            # This could also be used to instead add a source shared_image_gallery
            # and/or shared_image_gallery_destination
            $JSON.builders[0] | Add-Member @{ 
              managed_image_resource_group_name = '{{user `resource_group`}}'
              managed_image_name = '{{user `capture_name_prefix`}}{{isotime | clean_resource_name}}'
            }
            
            # Print the resulting JSON
            $JSON | ConvertTo-Json -Depth 4 | Out-Host
            # Write the JSON to a file
            $JSON | ConvertTo-Json -Depth 4 | Out-File $templatePath -Encoding Ascii -Force
```

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019

### Image version and build link

20210803.1

### Expected behavior

Be able to choose VHD or managed image or shared gallery by passing arguments or setting environment variables.

This requires changing the contents of the Windows/Ubuntu template.json files in the `builders` block so it would be fairly easy from the Powershell script.

### Actual behavior

Requires messy overrides after cloning the repository.

```
vhd: output will be in this color.

==> vhd: Running builder ...
==> vhd: Getting tokens using client secret
==> vhd: Getting tokens using client secret
    vhd: Creating Azure Resource Manager (ARM) client ...
==> vhd: Warning: You are using Azure Packer Builder to create VHDs which is being deprecated, consider using Managed Images. Learn more https://www.packer.io/docs/builders/azure/arm#azure-arm-builder-specific-options
```

### Repro steps

```
git clone https://github.com/actions/virtual-environments.git
Set-Location ./virtual-environments
Import-Module .\helpers\GenerateResourcesAndImage.ps1
Write-Host "Executing GenerateResourcesAndImage"
GenerateResourcesAndImage -SubscriptionId $(SUBSCRIPTION_ID) -ResourceGroupName "PackerBuildAgent" -ImageGenerationRepositoryRoot "$pwd" -ImageType Windows2019 -AzureLocation "Central US" -AzureClientId $(AZURE_CLIENT_ID) -AzureClientSecret $(AZURE_CLIENT_SECRET) -AzureTenantId $(AZURE_TENANT_ID) -Force
 ```

**Comment by dibir-magomedsaygitov** [comment] 2021-08-05 06:14
Hello @spoelstraethan. Thank you for your report. We will take a look.

**Comment by LeonidLapshin** [comment] 2021-08-05 09:31
Hey, @spoelstraethan 
```
We don't have plans to switch to manage disks in near future because it will require additional changes on infra side. Also VHDs won't be deprecated in near future, see details in #1037 (comment)
```
this issue is a duplicate of: #3147

**Comment by LeonidLapshin** [comment] 2021-08-09 08:50
Hey, @spoelstraethan 
Currently we don't have plans to modify images creation docs, but we'll appreciate your contribution if you can add [information to docs](https://github.com/actions/virtual-environments/blob/main/docs/create-image-and-azure-resources.md) for other people that want to use managed images. I'll close the issue as a duplicate but still be glad to review the docs PR if you will add it :)
Thank you!

**Closed by LeonidLapshin** 2021-08-09 08:50 UTC
Labels: OS: Windows, Area: Image administration, investigate
