### ISSUE TITLE
Can't use ubuntu-latest runner with alpine:edge or archlinux:latest containers

### ISSUE THREAD

**Issue by Mizux** [actions/virtual-environments#2698] opened 2021-02-12 10:26 UTC
**Description**  
I can't run any `alpine:edge` or `archlinux:latest` containers using the ubuntu-latest GitHub hosted runner

**Area for Triage**:
"Containers", "C/C++"

**Question, Bug, or Feature?**:  
"Bug"

**Virtual environments affected**  
- [x] Ubuntu 18.04 (ubuntu-latest)

**Image version**
Environment: ubuntu-18.04
  Version: 20210208.0

ref:
alpine: https://github.com/Mizux/cmake-cpp/runs/1886378586?check_suite_focus=true
archlinux: https://github.com/Mizux/cmake-cpp/runs/1886378616?check_suite_focus=true

**Expected behavior** 
Build pass...

**Actual behavior**  
* Alpine: permission denied to write (see trace above)

 * Archlinux: can't read some locations (see trace above)
```sh
Step 4/4 : RUN pacman -Syu --noconfirm git base-devel cmake
33
 ---> Running in 66dcaa2a1c0c
34
error: failed to initialize alpm library
35
(could not find or read directory: /var/lib/pacman/)
```

**Repro steps**  
Simply try to run actions job of https://github.com/Mizux/cmake-cpp
side note you can run them locally (if GNU/Linux host with GNU Make and a docker daemon) using:

* Alpine:
```sh
make --directory=ci alpine_build
```

* Archlinux:
```sh
make --directory=ci archlinux_build
```

# Investigation

* It seems related to  `faccessat2` being forbidden see https://github.com/seccomp/libseccomp/issues/314
* related issue: #2658
* Tracked by Alpine maintainers here: https://gitlab.alpinelinux.org/alpine/aports/-/issues/12321

**Comment by Mizux** [comment] 2021-02-12 11:44
I guess step to fix it is:

1. Have support in seccomp/libseccomp ?
2. Have virtual-environnements image using this updated version of the libseccomp
3. Relaunch my failing jobs in mizux/cmake-cpp and google/or-tools

side note: I'm currently using "ubuntu-latest" so if you decide to only do it for 20.04 LTS image please let me know !

**Comment by catthehacker** [comment] 2021-02-12 13:28
Seems like a duplicate of #2658

**Comment by Mizux** [comment] 2021-02-12 15:24
@catthehacker for archlinux good chance this is the same issue, but it also impact `alpine:edge` and here I just want to know when a new libseccomp (2.5.2 once released) will be shipped by github hosted runners so `faccessat2` won't fail

**Comment by vsafonkin** [comment] 2021-02-15 12:25
Hi @Mizux, I've reproduced your issue with `archlinux`, looks like something is broken on the container side. I've found this bug on archlinux bugtracker: https://bugs.archlinux.org/task/69563

You can fix your build using previous version of archlinux docker container: archlinux:base-20210131.0.14634
`archlinux:latest` run: https://github.com/vsafonkin/archlinux-docker-repro/runs/1903102140?check_suite_focus=true
`archlinux:base-20210131.0.14634` run: https://github.com/vsafonkin/archlinux-docker-repro/runs/1903193891?check_suite_focus=true

As I see, the matter is `ldd` tool version: 2.33 is broken, but 2.32 is fine.

**Comment by vsafonkin** [comment] 2021-02-15 14:36
Hi @Mizux, as I see, the issue is following: docker uses 1.0.0-rc92 version of `runc` tool, but `glibc-2.33` in containers requires 1.0.0-rc93. As a temporary workaround you can update `runc` to the latest version in runtime:
```
- name: build latest runc
      run: |
        sudo apt-get install libseccomp-dev
        git clone https://github.com/opencontainers/runc
        cd runc
        make
        sudo make install
```
It works: https://github.com/vsafonkin/cmake-cpp/runs/1903690200?check_suite_focus=true

There is PR in docker mody repo to update this tool: https://github.com/moby/moby/pull/42014
I believe it will be merged soon and we'll update docker on ubuntu runners.

**Comment by Mizux** [comment] 2021-02-15 15:04
@vsafonkin many thanks for doing the last miles !!! I think I can wait for the moby update, not in a hurry since I manage to make it work locally (archlinux host).
BTW thanks again for hunting it down to the moby commit !

**Comment by vsafonkin** [comment] 2021-02-16 09:44
@Mizux, thank you for your help! Could you please close the issue, because it seems resolved?

**Closed** 2021-02-16 09:57 UTC
Labels: Area: Containers, OS: Ubuntu, investigate

**Comment by ejose19** [comment] 2021-02-24 21:41
> Hi @Mizux, as I see, the issue is following: docker uses 1.0.0-rc92 version of `runc` tool, but `glibc-2.33` in containers requires 1.0.0-rc93. As a temporary workaround you can update `runc` to the latest version in runtime:
> 
> ```
> - name: build latest runc
>       run: |
>         sudo apt-get install libseccomp-dev
>         git clone https://github.com/opencontainers/runc
>         cd runc
>         make
>         sudo make install
> ```
> 
> It works: https://github.com/vsafonkin/cmake-cpp/runs/1903690200?check_suite_focus=true
> 
> There is PR in docker moby repo to update this tool: [moby/moby#42014](https://github.com/moby/moby/pull/42014)
> I believe it will be merged soon and we'll update docker on ubuntu runners.
> 
> Related: #2658

This fix works correctly when using `docker build`, but for some reason `docker buildx build` still fails with the original error even if the `--oci-worker-binary` flag is set to use the latest `runc`. Is there anything else to configure or would this be a bug with `buildx`?
