### ISSUE TITLE
Issues installing python packages introduced in delta from windows-2019 20201011.1 --> 20201021.0 images

### ISSUE THREAD

**Issue by MattGal** [actions/virtual-environments#1915] opened 2020-10-27 18:29 UTC
**Description**  

Our pipelines install a varied set of pip packages on Python 3.9 using hosted build agents.  It seems that somewhere when the **windows-2019** image revved from 20201011.1 --> 20201021.0, the agents started to fail when installing packages that indirectly depend on the "cryptography" package:

I also filed this via the [Developer Community site](https://developercommunity.visualstudio.com/content/problem/1234623/breaking-change-installing-python-packages-on-wind.html).

**Area for Triage**:  Python

**Question, Bug, or Feature?**:  Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**  
Installation of pip package `cryptography==2.8` should work

**Actual behavior**  
```
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.27.29110\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\hostedtoolcache\windows\Python\3.9.0\x86\include -IC:\hostedtoolcache\windows\Python\3.9.0\x86\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.27.29110\ATLMFC\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.27.29110\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt /Tcbuild\temp.win32-3.9\Release\_openssl.c /Fobuild\temp.win32-3.9\Release\build\temp.win32-3.9\Release\_openssl.obj
  _openssl.c
  build\temp.win32-3.9\Release\_openssl.c(575): fatal error C1083: Cannot open include file: 'openssl/opensslv.h': No such file or directory
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.27.29110\\bin\\HostX86\\x86\\cl.exe' failed with exit code 2
  ----------------------------------------
  ERROR: Failed building wheel for cryptography
ERROR: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly

```

**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

The following yaml, when run in an Azure Devops pipeline demonstrates the problem

``` .yaml
trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: 3.x
    addToPath: true
    architecture: x86

- script: |
    python -m pip install cryptography==2.8
  displayName: 'Demonstrate regression with pip install of cryptography'
```

**Comment by maxim-lobanov** [comment] 2020-10-27 18:35
@MattGal , Hello,
We didn't have Python 3.9 on 20201011.1.
"20201021.0" is the first image that contains Python 3.9 so looks like your previous builds were run on Python 3.8 but after image update started run on Python 3.9

**Comment by MattGal** [comment] 2020-10-27 18:36
> @MattGal , Hello,
> We didn't have Python 3.9 on 20201011.1.
> "20201021.0" is the first image that contains Python 3.9 so looks like your previous builds were run on Python 3.8 but after image update started run on Python 3.9

Cool.   Please note that python 3.9, both x86 and x64 versions, have no problem installing cryptography 2.8 on my local setup.

**Comment by maxim-lobanov** [comment] 2020-10-27 18:40
We will take a look. Actually, we don't do any customization of Python on Windows. We use official installers provided by Python: https://www.python.org/ftp/python/3.9.0/python-3.9.0-amd64.exe

**Comment by MattGal** [comment] 2020-10-27 18:41
Sure. If I had a machine to investigate, I'd check out the configuration of the C runtime installations on VS

**Comment by Darleev** [comment] 2020-10-28 20:43
Hello @MattGal,
I was able to reproduce the issue on our Windows 2019 agent, and it seems the issue should be addressed to [cryptography directly](https://github.com/pyca/cryptography).
[In the documentation](https://cryptography.io/en/latest/installation.html#building-cryptography-on-windows) I found the following pre-requisites for installing cryptography:
- OpenSSL 1.1.1-latest
- Python 2.7, 3.6+
and our agents satisfy them. Also, as a workaround, you can just install cryptography version 3.1.1 or 3.2.1(or the latest one) instead of the current one. 
If additional information is required, do not hesitate to contact us.

**Comment by Darleev** [comment] 2020-10-30 16:16
I'm going to close the issue.

In case of any questions, feel free to contact us.

**Closed by Darleev** 2020-10-30 16:16 UTC
Labels: Area: Python, OS: Windows, investigate

**Comment by MattGal** [comment] 2020-11-02 18:04
Thanks @Darleev !
