### ISSUE TITLE
Ubuntu jobs fail to fetch apt packages with 402 Payment Required

### ISSUE THREAD

**Issue by JasonGross** [actions/virtual-environments#1983] opened 2020-11-05 01:06 UTC
**Description**  
```
E: Failed to fetch https://packagecloud.io/github/git-lfs/ubuntu/dists/bionic/InRelease  402  Payment Required [IP: 54.183.38.243 443]
E: The repository 'https://packagecloud.io/github/git-lfs/ubuntu bionic InRelease' is no longer signed.
```

**Area for Triage**:  
Packages

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [x] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
Packages can be installed

**Actual behavior**  
Job fails on package install step with 402

**Repro steps**  
https://github.com/mit-plv/fiat-crypto/runs/1355905419?check_suite_focus=true

**Comment by buvinghausen** [comment] 2020-11-05 01:42
@JasonGross it impacts all versions of Ubuntu

https://packagecloud.io/github/git-lfs/ubuntu/dists/focal/InRelease
https://packagecloud.io/github/git-lfs/ubuntu/dists/bionic/InRelease
https://packagecloud.io/github/git-lfs/ubuntu/dists/xenial/InRelease

The issue is our friends at packagecloud.io apparently can't access their key due to non payment.

We are trying to remove the packagecloud line from the sources.list so when you run apt it doesn't try to ping them.  I will post a workaround here if it works.

**Comment by buvinghausen** [comment] 2020-11-05 02:16
Added a step to just remove git-lfs before we do any apt stuff seems to work.

```
      - name: remove git-lfs
        shell: bash
        run: |
          cat /etc/apt/sources.list
          ls /etc/apt/sources.list.d
          sudo rm /etc/apt/sources.list.d/github_git-lfs.list
          sudo rm /etc/apt/sources.list.d/github_git-lfs.list.save
```

**Comment by buvinghausen** [comment] 2020-11-05 03:21
FYi the keys are back online...

**Comment by andy-mishechkin** [comment] 2020-11-05 07:48
I think, we ca close this ticket
If this issue still not decided - feel free to reopen

**Closed by andy-mishechkin** 2020-11-05 07:48 UTC
Labels: needs triage

**Comment by buvinghausen** [comment] 2020-11-05 14:56
@andy-mishechkin yes the issue can be closed this did make it crystal clear we need to look into a self hosted runner so that we don't have 500+ dependencies that don't relate to our software stack any of which can take us down if something goes wrong.

**Comment by oryband** [comment] 2021-06-28 10:08
This issue has just resurfaced.

**Comment by sliddjur** [comment] 2021-06-28 10:24
A google search led me to this thread.
Just had this issue on ubuntu 20.04 on another repo from packagecloud.io. 

```
Err:16 https://packagecloud.io/slacktechnologies/slack/debian jessie InRelease
  402  Payment Required [IP: 54.183.216.24 443]
Reading package lists... Done                                                                                                                                                                                                                                                        
E: Failed to fetch https://packagecloud.io/slacktechnologies/slack/debian/dists/jessie/InRelease  402  Payment Required [IP: 54.183.216.24 443]
E: The repository 'https://packagecloud.io/slacktechnologies/slack/debian jessie InRelease' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by teodoryantcheff** [comment] 2021-06-28 10:37
```
Err:19 https://packagecloud.io/slacktechnologies/slack/ubuntu focal InRelease
  402  Payment Required [IP: 54.183.38.243 443]
E: Failed to fetch https://packagecloud.io/slacktechnologies/slack/ubuntu/dists/focal/InRelease  402  Payment Required [IP: 54.183.38.243 443]
E: The repository 'https://packagecloud.io/slacktechnologies/slack/ubuntu focal InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
Same.

**Comment by whyusername9** [comment] 2021-06-28 10:49
> This issue has just resurfaced in Ubuntu 21.04

I am facing the same error too

**Comment by Syzygianinfern0** [comment] 2021-06-28 12:21
> A google search led me to this thread.
> Just had this issue on ubuntu 20.04 on another repo from packagecloud.io.
> 
> ```
> Err:16 https://packagecloud.io/slacktechnologies/slack/debian jessie InRelease
>   402  Payment Required [IP: 54.183.216.24 443]
> Reading package lists... Done                                                                                                                                                                                                                                                        
> E: Failed to fetch https://packagecloud.io/slacktechnologies/slack/debian/dists/jessie/InRelease  402  Payment Required [IP: 54.183.216.24 443]
> E: The repository 'https://packagecloud.io/slacktechnologies/slack/debian jessie InRelease' is no longer signed.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> ```

Exact same issue! Although I got this 3-4 days ago 🤔

**Comment by buvinghausen** [comment] 2021-06-29 18:54
> This issue has just resurfaced in Ubuntu 21.04

@oryband the failure has nothing to do with the Ubuntu version and everything to do with the git-lfs team not paying their bill at packagecloud.io

**Comment by oryband** [comment] 2021-06-29 19:11
for anyone who is interested, you should revert to installing slack using snap imstead of that ppa usimg apt.

**Comment by omgapuppy** [comment] 2021-07-13 09:03
Just ran into the same with `git-lfs` package. Since the owner seems to be GitHub in this case, that's not great:

```
Failed to fetch https://packagecloud.io/github/git-lfs/ubuntu/dists/focal/InRelease  402  Payment Required
```

**Comment by miketimofeev** [comment] 2021-07-13 14:52
this is the issue with git-lfs and should be resolved by now
https://github.com/git-lfs/git-lfs/issues/4548

**Comment by eye1** [comment] 2022-11-24 16:02
once again: in November 2022
```
^@^@W: https://download.docker.com/linux/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
E: Failed to fetch https://packagecloud.io/github/git-lfs/ubuntu/dists/jammy/InRelease  402  Payment Required [IP: 52.8.159.246 443]
E: The repository 'https://packagecloud.io/github/git-lfs/ubuntu jammy InRelease' is not signed.

Exited with code exit status 100
```

**Comment by felipecrs** [comment] 2022-11-24 17:01
I can confirm the issue. And inside of a Dockerfile the solution above won't help. =/

**Comment by brogerson-rbcv** [comment] 2022-11-24 17:44
```
RUN rm -fv /etc/apt/sources.list.d/github_git-lfs.list && \
    rm -fv /etc/apt/sources.list.d/github_git-lfs.list.save && \
    apt-get update && \
    apt-get install gettext
```

Something like this no?

**Comment by felipecrs** [comment] 2022-11-24 18:08
Oh. Yes, but I don't want to take git-lfs from Ubuntu repos, I want to take it from the git-lfs repo :)

**Comment by mcrysler-ng** [comment] 2024-05-07 16:58
Is there a more general solution for this? I am running into this issue with an AtomEditor package.

**Comment by alan-sanchez** [comment] 2024-05-09 22:51
> Is there a more general solution for this? I am running into this issue with an AtomEditor package.

I'm having the same issue.
