### ISSUE TITLE
libc++-12* not available while clang-12 is

### ISSUE THREAD

**Issue by m6w6** [actions/virtual-environments#3499] opened 2021-06-01 11:33 UTC
**Description**  
While `clang-12` is provided since recently, one cannot install `libc++-12-dev` nor `libc++abi-12-dev` because they're apparently missing in the package repositories.

**Area for Triage**:  
C/C++

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
20210524.1

**Expected behavior**  
I expect `apt-get install libc++12-dev libc++abi-12-dev` to succeed.

**Actual behavior**  
```
E: Unable to locate package libc++-12-dev
E: Couldn't find any package by regex 'libc++-12-dev'
E: Unable to locate package libc++abi-12-dev
E: Couldn't find any package by regex 'libc++abi-12-dev'
```

**Repro steps**  
1. `apt-get update -y && apt-get install -y libc++12-dev libc++abi-12-dev`

**Comment by LeonidLapshin** [comment] 2021-06-01 13:16
Hey, @m6w6 !
Guess this is a duplicate of #3494 , I'll close this one, but feel free to reopen it if I have understood something incorrectly :)

**Closed by LeonidLapshin** 2021-06-01 13:16 UTC
Labels: needs triage
