### ISSUE TITLE
_PyUnicode_DecodeUnicodeEscape on Py3.9, ubuntu-20.04  v 20211108.1

### ISSUE THREAD

**Issue by hbq1** [actions/virtual-environments#4463] opened 2021-11-10 16:56 UTC
### Description

Hello, 

We are getting the following error on py3.9 Github Actions workflow after the ubuntu-20.04 v20211108.1 release (2 days ago):

```
Traceback (most recent call last):
  File "/tmp/distrax-env/bin/pytype", line 5, in <module>
    from pytype.tools.analyze_project.main import main
  File "/tmp/distrax-env/lib/python3.9/site-packages/pytype/tools/analyze_project/main.py", line 13, in <module>
    from pytype import io
  File "/tmp/distrax-env/lib/python3.9/site-packages/pytype/io.py", line 11, in <module>
    from pytype import analyze
  File "/tmp/distrax-env/lib/python3.9/site-packages/pytype/analyze.py", line 6, in <module>
    from pytype import context
  File "/tmp/distrax-env/lib/python3.9/site-packages/pytype/context.py", line 6, in <module>
    from pytype import annotation_utils
  File "/tmp/distrax-env/lib/python3.9/site-packages/pytype/annotation_utils.py", line 12, in <module>
    from pytype.overlays import typing_overlay
  File "/tmp/distrax-env/lib/python3.9/site-packages/pytype/overlays/typing_overlay.py", line 18, in <module>
    from pytype.overlays import collections_overlay
  File "/tmp/distrax-env/lib/python3.9/site-packages/pytype/overlays/collections_overlay.py", line 11, in <module>
    from pytype.pyi import parser
  File "/tmp/distrax-env/lib/python3.9/site-packages/pytype/pyi/parser.py", line 11, in <module>
    from pytype.pyi import classdef
  File "/tmp/distrax-env/lib/python3.9/site-packages/pytype/pyi/classdef.py", line 7, in <module>
    from pytype.pyi.types import ParseError  # pylint: disable=g-importing-member
  File "/tmp/distrax-env/lib/python3.9/site-packages/pytype/pyi/types.py", line 11, in <module>
    from typed_ast import ast3
  File "/tmp/distrax-env/lib/python3.9/site-packages/typed_ast/ast3.py", line 40, in <module>
    from typed_ast import _ast3
ImportError: /tmp/distrax-env/lib/python3.9/site-packages/typed_ast/_ast3.cpython-39-x86_64-linux-gnu.so: undefined symbol: _PyUnicode_DecodeUnicodeEscape
```

Full log: https://github.com/deepmind/distrax/runs/4168111281?check_suite_focus=true

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20211108.1

### Is it regression?

Yes, 20211101.1 seems to work: https://github.com/deepmind/distrax/runs/4156977602?check_suite_focus=true

### Repro steps

See [logs](https://github.com/deepmind/distrax/runs/4156977602?check_suite_focus=true) and [the workflow definition](https://github.com/deepmind/distrax/blob/master/.github/workflows/tests.yml).

**Comment by hbq1** [comment] 2021-11-10 16:59
The error occurs only in py3.9 virtualenv.

**Comment by mikhailkoliada** [comment] 2021-11-12 10:55
The minimal repro is

```csl
pip install typed_ast
python3 -c 'from typed_ast import ast3'
```
I can reproduce the problem with python v3.9.8 even on my personal Linux machine (older versions do not seem to be affected), and as was linked above it looks like the problem was fixed by upstream in their repo already, so nothing we can do about it but waiting for another release.

I am going to close this issue now, but feel free to ping us if you have questions.

**Closed by mikhailkoliada** 2021-11-12 10:55 UTC
Labels: bug, Area: Python, OS: Ubuntu, external

**Comment by hbq1** [comment] 2021-11-12 14:53
Thanks guys! I can confirm that the issue has been resolved.
