### ISSUE TITLE
Regression in 20210718.1: non-terminating job

### ISSUE THREAD

**Issue by gallais** [actions/virtual-environments#3774] opened 2021-07-22 08:25 UTC
### Description

One of our jobs is getting reliably stuck until we either stop it or it gets killed after 6h of runtime.
Restarting a previously successful builds yields this exact behaviour.

Used to work with 20210712.0
Fails with 20210718.1

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Image version and build link

Fails with 20210718.1: https://github.com/idris-lang/Idris2/actions/runs/1044870887

### Is it regression?

Used to work with 20210712.0: https://github.com/idris-lang/Idris2/actions/runs/1043364037

### Repro steps

1. Restart e.g. https://github.com/idris-lang/Idris2/actions/runs/1044870887
2. Wait a couple of hours

**Comment by al-cheb** [comment] 2021-07-22 09:02
Hi, @gallais 
We will take a look at this.

**Comment by dsame** [comment] 2021-07-27 07:42
@gallais i see some evidence the problem is outside the image but somewhere in the idris2 itself 

1. There was the same issue during a build https://github.com/idris-lang/Idris2/issues/163
2. The build sometimes passes on the current image https://github.com/akv-platform/Idris2/runs/3168862269?check_suite_focus=true
3. An attempt to call the build with `strace` makes the build to success once again

`Makefile`

```
 60 idris2-exec: ${TARGET}
 61
 62 ${TARGET}: src/IdrisPaths.idr
 63         strace -ff ${IDRIS2_BOOT} --build ${IDRIS2_APP_IPKG}
 64
 65 # We use FORCE to always rebuild Idris
```

As a result i advise to investigate the possibility of the deadlocks in the code or use `strace -ff ` to build the `ubuntu-bootstrap-racket` and give us a log in case if the build hangs in order we can find out the image problems.

**Comment by dsame** [comment] 2021-07-27 15:25
@gallais please pay attention if i change `%default total` to `%default covering` t
https://github.com/akv-platform/Idris2/commit/73bdde9d0eda6cb7ecf012b6a3507aff7bf8abcd

he compilation of `src/Libraries/System/Directory/Tree.idr` passes but the build hangs in the other file
https://github.com/akv-platform/Idris2/actions/runs/1070555596

**Comment by al-cheb** [comment] 2021-07-28 20:23
@gallais,  Could you please try to rerun failed build, because we have rolled back a recent configuration change- https://github.com/actions/virtual-environments/issues/3805#issuecomment-887884901?

**Comment by dsame** [comment] 2021-07-29 05:40
@gallais the forked master branch (with ubuntu-bootstrap-racket enabled) build now succeeds https://github.com/akv-platform/Idris2/actions/runs/1077259156

**Comment by gallais** [comment] 2021-07-30 14:17
Thanks for all of the work on this! I still don't understand the problem which makes me
worried that, as you suggested, we may generate racket code that's prone to deadlocking.

This morning I restarted https://github.com/idris-lang/Idris2/actions/runs/1044870887 and this time it
 succeeded in the environment 20210726.1.

I'll open a PR to reactivate the racket builds on `main` and see whether that's successful!

**Comment by AlenaSviridenko** [comment] 2021-08-03 12:18
Hi @gallais,
looks like the issue doesn't reproduce anymore, do you mind if I close the issue? Or please, feel free to close it by yourself. Thanks.

**Comment by gallais** [comment] 2021-08-03 12:24
It is indeed gone. Thanks!

**Closed** 2021-08-03 12:24 UTC
Labels: OS: Ubuntu, investigate

**Comment by gallais** [comment] 2021-09-19 11:26
We had this problem creep up again recently but it seems to be gone (for good? :crossed_fingers:)
after [this patch](https://github.com/idris-lang/Idris2/pull/1931/commits/5adb23393ae1657ce4ad5ba5129fef6db3393f14#diff-d17d0e5d981aa6d199392f1fad22b2fa53b27ab667cf963cbe505c8c7cd2ea17) switching from process to monotonic clock time.

I'm not sure why the result would be influenced by the deployed environment
