### ISSUE TITLE
cannot push to another repo

### ISSUE THREAD

**Issue by mgood7123** [actions/virtual-environments#3681] opened 2021-07-02 08:03 UTC
### Description

i cannot push to another repository in github even when i am using a encrypted secret PAT with all scopes granted

i keep getting

```
[master (root-commit) d34fe09] first commit
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 DO_NOT_DELETE_ME.GITHUB_ACTIONS_PREBUILD_EXTERNAL_REPO_RESET_POINT On branch main
nothing to commit, working tree clean
origin	***github.com/mgood7123/prebuilder-ubuntu-latest.git (fetch)
origin	***github.com/mgood7123/prebuilder-ubuntu-latest.git (push)
* remote origin
  Fetch URL: ***github.com/mgood7123/prebuilder-ubuntu-latest.git
  Push  URL: ***github.com/mgood7123/prebuilder-ubuntu-latest.git
  HEAD branch: (unknown)
remote: Invalid username or password.
```

with

```shell
rm -rf .git; \
git init; \
touch DO_NOT_DELETE_ME.GITHUB_ACTIONS_PREBUILD_EXTERNAL_REPO_RESET_POINT; \
git add DO_NOT_DELETE_ME.GITHUB_ACTIONS_PREBUILD_EXTERNAL_REPO_RESET_POINT; \
git commit -m "first commit"; \
git branch -M main; \
git remote add origin https://${{env.REPO_ACCESS_TOKEN}}:x-oauth-basic@github.com/${{github.repository}}-${{matrix.os}}.git; \
git status; \
git remote -v; \
git remote show origin; \
git push --set-upstream origin main; \
```

i have tried credential helper but i get same result

please note that this WORKS if i manually ssh into the build via tmate action, and then invoke the commands stated above

the repo i am pushing to is `https://github.com/mgood7123/prebuilder-ubuntu-latest`

the repository i am pushing from is `https://github.com/mgood7123/prebuilder`

the PAT i am using has all scopes granted to it and is stored in a repository secret in my `https://github.com/mgood7123/prebuilder` repository

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019

### Image version and build link

  Environment: ubuntu-20.04
  Version: 20210628.1
  Included Software: https://github.com/actions/virtual-environments/blob/ubuntu20/20210628.1/images/linux/Ubuntu2004-README.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/ubuntu20%2F20210628.1

https://github.com/mgood7123/prebuilder/runs/2967752965

copy of yaml:
```yaml
name: CMake

on:
  push:
    branches: [ main ]

concurrency:
  group: build
  cancel-in-progress: true

env:
  # Put your secret here
  # to create a secret, go to
  
  # User Profile -> Settings ->
  # Developer Settings (at the bottom of page) -> Persional Access Tokens
  
  # then generate a new token and give it [public_repo] scope and then
  # click [Generate token]
  # finally copy its token id
  
  # next, go to your repository containing this workflow
  # Settings -> Secrets -> New repository secret
    
  # in the [Value] field, past the token id that you copied earlier
  
  # in the [Name] field, enter a name, replacing spaces with underscore (_)
  # for example, we will name it REPO_ACCESS_TOKEN
  
  # and then enter it here as ${{secrets.REPO_ACCESS_TOKEN}}
  
  REPO_ACCESS_TOKEN: ${{secrets.REPO_ACCESS_TOKEN}}
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    strategy:
#      fail-fast: false
      max-parallel: 1
      matrix:
        include:
        
        - os: ubuntu-latest
        - os: macOS-latest
        - os: windows-latest

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2
    
    - name: create EXTERNAL REPO
      run: |
        # modify this to point to your external repo
        git clone https://github.com/${{github.repository}}-${{matrix.os}} EXTERNAL_REPO
        cd EXTERNAL_REPO
        rm -rf .git
        git init
        touch README.md
        git add README.md
        git commit -m "first commit"
        git branch -M main
        # modify this to point to your repo
        git remote add origin https://${{env.REPO_ACCESS_TOKEN}}:x-oauth-basic@github.com/${{github.repository}}-${{matrix.os}}.git
        git status
        git remote -v
        git remote show origin
        git push --set-upstream origin main --force
```

### Expected behavior

i expect the push to succeed since i own the repository

### Actual behavior

the push is failing with invalid username or password

i do not know why

### Repro steps

make a new repository called X

make a new repository called X2

in repository X, create a new workflow

in this workflow, create an action that initializes a new repository with its URL as X2 and then push to X2 (as stated in the X2 initialization readme for empty repositories)

the push will fail even if a PAT is used

however the push can succeed if you add a tmate action and then ssh into the session and push to the repo via the ssh session

**Comment by dibir-magomedsaygitov** [comment] 2021-07-02 09:20
Hello @mgood7123. Thank you for your report. We will take a look.

**Comment by mgood7123** [comment] 2021-07-02 12:13
i also seem to be unable to use my ssh key

ssh -T git@github.com
 Warning: Permanently added the RSA host key for IP address '140.82.112.3' to the list of known hosts.
Hi mgood7123! You've successfully authenticated, but GitHub does not provide shell access.

git clone ssh://git@github.com/mgood7123/prebuilder-ubuntu-latest GITHUB_ACTIONS_PREBUILD_EXTERNAL_REPO_FOLDER

Cloning into 'GITHUB_ACTIONS_PREBUILD_EXTERNAL_REPO_FOLDER'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by mgood7123** [comment] 2021-07-02 13:38
i am also unable to verify ssh in windows

```
    - name: Git - Disable automatic line ending conversion
      run: |
        git config --global core.autocrlf false

    - name: Checkout repository
      uses: actions/checkout@v2
```
```
eval $(ssh-agent -s)
ssh-add GITHUB_ACTIONS_PREBUILD_SSH_KEY <<< ${{env.PUBLIC_ACCESS_TOKEN}}
ssh -vT git@github.com || true
```
```
 Agent pid 1310
Enter passphrase for GITHUB_ACTIONS_PREBUILD_SSH_KEY: Identity added: GITHUB_ACTIONS_PREBUILD_SSH_KEY (GITHUB_ACTIONS_PREBUILD_SSH_KEY)
OpenSSH_8.5p1, OpenSSL 1.1.1k  25 Mar 2021
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Connecting to github.com [140.82.113.4] port 22.
debug1: Connection established.
debug1: identity file /c/Users/runneradmin/.ssh/id_rsa type -1
debug1: identity file /c/Users/runneradmin/.ssh/id_rsa-cert type -1
debug1: identity file /c/Users/runneradmin/.ssh/id_dsa type -1
debug1: identity file /c/Users/runneradmin/.ssh/id_dsa-cert type -1
debug1: identity file /c/Users/runneradmin/.ssh/id_ecdsa type -1
debug1: identity file /c/Users/runneradmin/.ssh/id_ecdsa-cert type -1
debug1: identity file /c/Users/runneradmin/.ssh/id_ecdsa_sk type -1
debug1: identity file /c/Users/runneradmin/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /c/Users/runneradmin/.ssh/id_ed25519 type -1
debug1: identity file /c/Users/runneradmin/.ssh/id_ed25519-cert type -1
debug1: identity file /c/Users/runneradmin/.ssh/id_ed25519_sk type -1
debug1: identity file /c/Users/runneradmin/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /c/Users/runneradmin/.ssh/id_xmss type -1
debug1: identity file /c/Users/runneradmin/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.5
debug1: Remote protocol version 2.0, remote software version babeld-4cec2db4
debug1: compat_banner: no match: babeld-4cec2db4
debug1: Authenticating to github.com:22 as 'git'
debug1: load_hostkeys: fopen /c/Users/runneradmin/.ssh/known_hosts: No such file or directory
debug1: load_hostkeys: fopen /c/Users/runneradmin/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: rsa-sha2-512
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: SSH2_MSG_KEX_ECDH_REPLY received
debug1: Server host key: ssh-rsa SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8
debug1: load_hostkeys: fopen /c/Users/runneradmin/.ssh/known_hosts: No such file or directory
debug1: load_hostkeys: fopen /c/Users/runneradmin/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: hostkeys_find_by_key_hostfile: hostkeys file /c/Users/runneradmin/.ssh/known_hosts does not exist
debug1: hostkeys_find_by_key_hostfile: hostkeys file /c/Users/runneradmin/.ssh/known_hosts2 does not exist
debug1: hostkeys_find_by_key_hostfile: hostkeys file /etc/ssh/ssh_known_hosts2 does not exist
debug1: read_passphrase: can't open /dev/tty: No such device or address
Host key verification failed.
```

**Comment by MaksimZhukov** [comment] 2021-07-05 15:01
Hello @mgood7123! Thank you for the repro steps!
I've created a test repo and added a [yml file](https://github.com/MaksimZhukov/TestNewRepo/blob/main/.github/workflows/git.yml) as you suggested above. I also set up git user name and email address. Generated access token has the `public_repo` scope. Everything works as expected ([workflow run](https://github.com/MaksimZhukov/TestNewRepo/runs/2991216337?check_suite_focus=true)).

Does the issue persist for you?

**Comment by mgood7123** [comment] 2021-07-06 02:17
> Hello @mgood7123! Thank you for the repro steps!
> I've created a test repo and added a [yml file](https://github.com/MaksimZhukov/TestNewRepo/blob/main/.github/workflows/git.yml) as you suggested above. I also set up git user name and email address. Generated access token has the `public_repo` scope. Everything works as expected ([workflow run](https://github.com/MaksimZhukov/TestNewRepo/runs/2991216337?check_suite_focus=true)).
> 
> Does the issue persist for you?

hmmm this is weird

on yours you have `HEAD branch: main`
while on mine i have `HEAD branch: (unknown)`

even though we did the exact same commands

this issue currently does not persist for me as i have switched to using password protected SSH key's as a workaround for this - https://github.com/mgood7123/prebuilder/blob/14bb4e5cdb429639d8367e97b38b6ad932742a05/.github/workflows/prebuilder.yml#L261

**Comment by MaksimZhukov** [comment] 2021-07-06 10:36
The [first run](https://github.com/MaksimZhukov/TestNewRepo/runs/2991136338?check_suite_focus=true) of my workflow includes the same line as yours (`HEAD branch: (unknown)`) and completed successfully.

I'm going to close this issue since it is no longer reproducible. Feel free to contact us if you have any questions or objections. Thank you!

**Closed by MaksimZhukov** 2021-07-06 10:36 UTC
Labels: Area: Git, investigate
