### ISSUE TITLE
Experimental Docker inside action

### ISSUE THREAD

**Issue by elgohr** [actions/virtual-environments#3090] opened 2021-04-04 16:04 UTC
**Description**  
I'm trying to enable experimental Docker inside an action.
Generally https://github.com/actions/virtual-environments/issues/368 was a good hint.
Nevertheless it looks like that doesn't work when not using `run` directly.

Example:
```
on: [push]
jobs:
  build:
    runs-on: [ubuntu-16.04]
    steps:
      - name: Plain job
        run: |
          echo $'{"experimental": true}' | sudo dd status=none of=/etc/docker/daemon.json 
          sudo service docker restart
          docker version -f '{{.Server.Experimental}}' 
      - name: In with
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: lgohr/test-push
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          platforms: linux/amd64,linux/arm64
```

As shown in https://github.com/elgohr/actions-test/runs/2264996919?check_suite_focus=true , the `Plain job` executes fine; where `In with` is not able to find `/etc/docker/daemon.json`.
Even when using the exact same lines of code (see https://github.com/elgohr/Publish-Docker-Github-Action/blob/master/entrypoint.sh#L91 for the actions implementation).
My guess is, that it can't find the file, because it's executed in the given Docker container.
Nevertheless this would limit the use of experimental Docker to non-Docker actions.

**Question, Bug, or Feature?**:  
Question/Bug

**Virtual environments affected**  
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**  
Have a way to use experimental Docker inside a reusable action.

**Actual behavior**  
Fails when trying to adapt workaround for using experimental Docker features.

**Comment by al-cheb** [comment] 2021-04-05 06:33
Hi @elgohr 
We will take a look at it.

**Comment by Darleev** [comment] 2021-04-05 20:30
Hello @elgohr,
I'm not sure that the issue is related to GitHub actions logic since the same behavior can be reproduced locally using the following steps:

- Clone repository https://github.com/elgohr/Publish-Docker-Github-Action
- Open the directory with the code
- Build docker image:

`docker build -t testapp .`

- Run docker container using the following command

`docker run -it -e INPUT_NAME=saymyname -e INPUT_USERNAME=username -e INPUT_PASSWORD=password -e INPUT_PLATFORMS=ubuntu testapp`

And the following error appears:

`dd: can't open '/etc/docker/daemon.json': No such file or directory`

My proposal here is to create `/etc/docker/daemon.json` file during the docker image build procedure(specify in Dockerfile) and set experimental mode using env variables or the same approach with entrypoint, but change experimental from false to true in the daemon.json file.

**Comment by elgohr** [comment] 2021-04-05 21:09
Hey @Darleev ,
we’re talking about Docker in Docker, right?
I guess the „host“ daemon has to have experimental features enabled, when a demon inside a docker (running on the host) wants to use that. 
I thought that the daemon.json is mounted from the host, when using an action - to make that transparent. But looks like this is not the case.

**Comment by Darleev** [comment] 2021-04-06 03:57
@elgohr yes, it's correct.
I've checked docker(docker in docker) image [documentation](https://hub.docker.com/_/docker) and it seems need to use `Rootless` dind image with --experimental flag to enable it inside a docker container. Default docker in docker container starts without experimental mode enabled.
Also, it most probably should work to create a daemon.json file during the docker build procedure.

**Comment by elgohr** [comment] 2021-04-06 15:23
Looks like the inner docker has no access to `service` (see `sudo: service: command not found`) in https://github.com/elgohr/actions-test/runs/2279546077?check_suite_focus=true (step: "Use local my-action").

I was trying to follow your idea in this step (code: https://github.com/elgohr/actions-test/tree/master/.github/actions/local). Did I miss a thing?

**Comment by Darleev** [comment] 2021-04-06 18:14
@elgohr as far as I understand, docker server enabled is not required for your task, and it is only required to enable the DOCKER_CLI experimental feature. In order to do this, you can just specify DOCKER_CLI_EXPERIMENTAL=enabled variable, right before the container run

`export DOCKER_CLI_EXPERIMENTAL=enabled`

Regarding your question: since the docker server is not running in docker image by default and only CLI is available, docker version command will return an error by default, but docker cli version can be checked using command `docker --version`. Also, inside the docker container, `service docker restart` command is not available, since it's an alpine image. 

Could you please provide more context as, why the experimental feature is required for your image?

**Comment by elgohr** [comment] 2021-04-06 18:23
I would like to use `docker buildx` for building multi-platform images. `buildx` uses `buildkit` (https://docs.docker.com/buildx/working-with-buildx/#overview). `buildkit` runs on the host (https://github.com/moby/buildkit#starting-the-buildkitd-daemon).

**Comment by Darleev** [comment] 2021-04-06 18:47
@elgohr it seems I found a way how to implement request which was initially reported here, in order to do this, it is required to start docker container with additional volume configuration: `-v /var/run/docker.sock:/var/run/docker.sock`, after that local docker socket will be transferred into an existing container. I've tested this case locally and it works fine.

**Comment by elgohr** [comment] 2021-04-06 18:52
@Darleev  sorry, I don’t get it.
You found the basic implementation of Docker in Docker.
How would you mount the docker socket inside an action? The mount also requires a privileged execution.

**Comment by Darleev** [comment] 2021-04-06 19:05
@elgohr I see the only example for common workflow, without uses implementation, and most probably it won't work in a such way. An example is available [here](https://stackoverflow.com/questions/58997638/docker-container-volume-does-not-get-mounted-in-github-actions).
Also, please note, that buildx feature is not available out of the box with the docker, and should be installed using an instruction from official github repo: https://github.com/docker/buildx

**Comment by Darleev** [comment] 2021-04-12 10:19
@elgohr Can we assist with the initial issue somehow or maybe it is resolved? Could you please provide an update?

We are looking forward to your reply.

**Comment by elgohr** [comment] 2021-04-13 06:57
Ok, so let's sum this up.
When I got this correct, then `uses` is nothing else than Docker in Docker (when using Docker to build the action).
For using experimental features the following ways exist:
- enable it on the host machine with a step before using the action (and inside the action)
- mount the host daemon into the action and configure it inside of the action

To be honest, both solutions are complex to explain to users of an action.
Would be great to have an easy, documented way to use experimental docker features within an action.

**Comment by Darleev** [comment] 2021-04-15 20:33
@elgohr Our team is responsible for virtual environment agents. In order to improve GitHub actions workflows or possible submit community feature, it's better to contact the GitHub actions team using the following link: https://github.community/c/code-to-cloud/github-actions/41
If additional assistance is required from our side, feel free to contact us.

**Comment by Darleev** [comment] 2021-04-19 05:24
@elgohr I'm going to close the issue.
In case of any questions, do not hesitate to contact us.

**Closed by Darleev** 2021-04-19 05:24 UTC
Labels: OS: Ubuntu, OS: Windows, question
