### ISSUE TITLE
Azure Pipelines Custom VM built from this repo can't restore nuget packages

### ISSUE THREAD

**Issue by obeyda** [actions/virtual-environments#3241] opened 2021-04-22 23:18 UTC
**Description**  
I built a custom VM from this repo, and created a VMSS Agent pool with that image in azure pipelines,
I have a pipelines that contains docker task to build a dotnet core 3.1 application, The task fails when trying to restore nuget packages with this error message:
```
#21 [build 13/16] RUN dotnet restore "myProj.csproj"
#21 sha256:3428e7fe040ff68779e0ebd4
#21 2.550   Determining projects to restore...
#21 63.45 /usr/share/dotnet/sdk/3.1.408/NuGet.targets(128,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [myProj.csproj]
#21 63.45 /usr/share/dotnet/sdk/3.1.408/NuGet.targets(128,5): error :   Resource temporarily unavailable [myProj.csproj]
#21 ERROR: executor failed running [/bin/sh -c dotnet restore "myProj.csproj"]: exit code: 1
```

**Area for Triage**:  
.NET Core
Containers
Packages

**Question, Bug, or Feature?**:  
Question

**Virtual environments affected**  
- [x] Ubuntu 18.04

**Expected behavior**  
The docker build and restore task should execute without errors 

**Actual behavior**  
Task is failing at the restore step

**Repro steps**  
1. Build the VM using packer as shown in the instructions (`CreateAzureVMFromPackerTemplate` script) 
2. Create a Managed VM image with the resulting vhd
3. Create a VMSS with the managed image.
4. Create a self hosted VMSS Agent pool in Azure pipelines

**Comment by LeonidLapshin** [comment] 2021-04-23 07:05
Hey, @obeyda !
Could you please provide some repro (sample app or link to your app/build steps) for that error for troubleshooting?

**Comment by obeyda** [comment] 2021-04-23 15:46
@LeonidLapshin, here's a repo with a sample project.
I tested the pipeline with my vmss agent pool and i had the same issue: 
![image](https://user-images.githubusercontent.com/15065966/115894783-8f650280-a451-11eb-8e6c-01eda4254ae5.png)

**Comment by LeonidLapshin** [comment] 2021-04-30 10:27
Hey, @obeyda !
I have used your app/pipeline definition with manually created ubuntu 16 pool (VMSS used as pool) and got no error. The image itself is just a box for docker and it works, so it seems that there was an issue with a container image, but now I can't reproduce this issue :(

```
Agent machine name: 'vllapshin000002'
Current agent version: '2.186.0'
Current image version: '20210419.1'
Agent running as: 'AzDevOps'
Prepare build directory.
...
2021-04-30T10:19:10.6513212Z #13 [build 5/7] COPY . MyWebApi/
2021-04-30T10:19:10.6513534Z #13 sha256:eca0e640da58b5e7acfef47c4fcefa26cf1fe8f79d608393915da9254b2e9557
2021-04-30T10:19:10.8010793Z #13 DONE 0.2s
2021-04-30T10:19:10.8011277Z 
2021-04-30T10:19:10.8011693Z #14 [build 6/7] WORKDIR /src/MyWebApi
2021-04-30T10:19:10.8012322Z #14 sha256:7f4bba75274c48d8760354f3bbee0b83fc55402606b65f639717b19daa3a6cd0
2021-04-30T10:19:10.9515814Z #14 DONE 0.1s
2021-04-30T10:19:10.9516191Z 
2021-04-30T10:19:10.9518001Z #15 [build 7/7] RUN dotnet build "MyWebApi.csproj" -c Release --no-restore -o /app/build
2021-04-30T10:19:10.9519011Z #15 sha256:99cb64016b2d30378c1de9dbcf25cddfa0df8d058053503dc417e8efd517063c
2021-04-30T10:19:11.7021585Z #15 0.782 Microsoft (R) Build Engine version 16.7.2+b60ddb6f4 for .NET
2021-04-30T10:19:11.7022425Z #15 0.782 Copyright (C) Microsoft Corporation. All rights reserved.
2021-04-30T10:19:11.7022973Z #15 0.782 
2021-04-30T10:19:14.5379715Z #15 3.707   MyWebApi -> /app/build/MyWebApi.dll
2021-04-30T10:19:14.6877782Z #15 3.739 
2021-04-30T10:19:14.6879445Z #15 3.739 Build succeeded.
2021-04-30T10:19:14.6879748Z #15 3.740     0 Warning(s)
2021-04-30T10:19:14.6879981Z #15 3.740     0 Error(s)
2021-04-30T10:19:14.6880188Z #15 3.740 
2021-04-30T10:19:14.6880440Z #15 3.740 Time Elapsed 00:00:02.89
2021-04-30T10:19:14.8379597Z #15 DONE 3.9s
2021-04-30T10:19:14.8380168Z 
2021-04-30T10:19:14.8382370Z #16 [publish 1/1] RUN dotnet publish "MyWebApi.csproj" -c Release --no-restore -o /app/publish
2021-04-30T10:19:14.8383071Z #16 sha256:9a54756ff8d299e33db3d348b4e9ef61b94c847ebd203e3b33a779880dfc2f91
2021-04-30T10:19:15.5884809Z #16 0.807 Microsoft (R) Build Engine version 16.7.2+b60ddb6f4 for .NET
2021-04-30T10:19:15.5885730Z #16 0.807 Copyright (C) Microsoft Corporation. All rights reserved.
2021-04-30T10:19:15.5885974Z #16 0.807 
2021-04-30T10:19:16.5977663Z #16 1.869   MyWebApi -> /src/MyWebApi/bin/Release/netcoreapp3.1/MyWebApi.dll
2021-04-30T10:19:16.7098937Z #16 1.981   MyWebApi -> /app/publish/
2021-04-30T10:19:17.0103951Z #16 DONE 2.1s
2021-04-30T10:19:17.0104145Z 
2021-04-30T10:19:17.0105082Z #17 [final 2/2] COPY --from=publish /app/publish .
2021-04-30T10:19:17.0105828Z #17 sha256:03ab5eb1760da23d9e90c4ede157c98125a689102013da66e9ac0a48ce575174
2021-04-30T10:19:17.1471502Z #17 DONE 0.2s
2021-04-30T10:19:17.2978414Z 
2021-04-30T10:19:17.2979218Z #18 exporting to image
2021-04-30T10:19:17.2979835Z #18 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00
2021-04-30T10:19:17.2980452Z #18 exporting layers
2021-04-30T10:19:18.1517736Z #18 exporting layers 1.0s done
2021-04-30T10:19:18.1518599Z #18 writing image sha256:3e7af313c77d1adb0e265baf29e564c27c4609532fad7ed861315287fb7bbb40
2021-04-30T10:19:18.1812726Z #18 writing image sha256:3e7af313c77d1adb0e265baf29e564c27c4609532fad7ed861315287fb7bbb40 done
2021-04-30T10:19:18.1814962Z #18 naming to docker.io/library/mywebapi:latest done
2021-04-30T10:19:18.1815924Z #18 DONE 1.0s
```

Could you please check if the problem persist?

**Comment by LeonidLapshin** [comment] 2021-05-05 10:24
Hey, @obeyda !
I guess that it was the temporary problem, so I'll close the issue for now, but please, feel free to reopen it if you have any concerns.
Thank you!

**Closed by LeonidLapshin** 2021-05-05 10:24 UTC
Labels: Area: .NET Core, Area: Deployment/Release, Area: Packages, OS: Ubuntu, investigate
