### ISSUE TITLE
Our build is broken again without any changes to our software or build definition

### ISSUE THREAD

**Issue by StingyJack** [actions/virtual-environments#1526] opened 2020-09-01 13:00 UTC
**Description**  
![image](https://user-images.githubusercontent.com/15381181/91853896-e010bc80-ec30-11ea-8404-749946260c13.png)

**Area for Triage**:  

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] macOS 10.15
- [x ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
We expect the service we pay for to be consistently available

**Actual behavior**  
Every few months or so the service is interrupted and there is no notification or attempt made by the provider to rectify it.

**Comment by AlenaSviridenko** [comment] 2020-09-01 13:28
Hi @StingyJack,
Unfortunately, UsePython is not supposed to be used with exact `major.minor.patch` version, because each patch replaces the previous patch. So it is strongly recommended to UsePython task with specified `major.minor` version, e.g. `3.6` instead of `3.6.10`. It will guarantee that your pipeline will use the latest patch of Python 3.6 and will not be broken and you are not depending on a patch that can be erased with the next one.

We are not storing all patches side-by-side because it is not expected that patches could bring breaking changes and it is safe to replace previous one with the next one.

In addition, we are not planning to remove minor versions, at least without an announcement to warn customers about upcoming change. So it is safe to specify exact `major.minor` Python version.

You can track Python versions updates in the releases of this repo https://github.com/actions/python-versions/releases to be aware about changes.

Closing this issue as a duplicate of https://github.com/actions/virtual-environments/issues/1260.

**Closed by AlenaSviridenko** 2020-09-01 13:28 UTC
Labels: Area: Python, OS: Ubuntu, investigate

**Comment by StingyJack** [comment] 2020-09-01 14:59
@AlenaSviridenko - I dont want to switch python versions or float them because that means unplanned and unexpected testing and I dont have time for that. 

Python does not state anywhere that they follow SemVer and the convention you suggest is safe and reliable. 

> In addition, we are not planning to remove minor versions, at least without an announcement to warn customers about upcoming change. So it is safe to specify exact major.minor Python version.

But you _**have**_ removed minor versions, which is the problem here. 3.6.11 would not be missing and my build would not be in error if it was still present.   Nobody ever notifies us when this happens, things just break. 

There is no mention of "supposed" usages that you describe in the [UsePython task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-python-version?view=azure-devops).
