### ISSUE TITLE
MacOS 11.0 Big Sur builds not starting

### ISSUE THREAD

**Issue by kumaraditya303** [actions/virtual-environments#2396] opened 2021-01-07 07:40 UTC
**Description**  
MacOS Big Sur builds are not starting and failing.

**Area for Triage**:  

**Question, Bug, or Feature?**:  

"Bug"
**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [x] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
A description of what you expected to happen.
It should start.
**Actual behavior**  
A description of what is actually happening.
Builds are not starting.
**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.
https://github.com/kumaraditya303/umarkdown/actions/runs/466046639

**Comment by tofi86** [comment] 2021-01-07 07:44
Duplicate of #2381

**Comment by dibir-magomedsaygitov** [comment] 2021-01-07 15:36
Closing as duplicate of [#2381](https://github.com/actions/virtual-environments/issues/2381)

**Closed by dibir-magomedsaygitov** 2021-01-07 15:36 UTC
Labels: needs triage
