### ISSUE TITLE
Add Ubuntu 20.04 LTS envrionment

### ISSUE THREAD

**Issue by rigtorp** [actions/virtual-environments#816] opened 2020-05-01 00:00 UTC
Ubuntu 20.04 LTS (https://releases.ubuntu.com/20.04/) is now out and makes sense to add it as a supported environment while deprecating Ubuntu 16.04 LTS.

**Comment by peaceiris** [comment] 2020-05-01 00:18
This is a duplicate of https://github.com/actions/virtual-environments/issues/228

**Comment by vmapetr** [comment] 2020-05-01 06:34
Hi @rigtorp! Thank you for your feedback! Please check details about Ubuntu 20.04 in related issue https://github.com/actions/virtual-environments/issues/228.

**Closed by vmapetr** 2020-05-01 06:34 UTC
Labels: needs triage
