### ISSUE TITLE
Unreliable downloads from within Github Actions

### ISSUE THREAD

**Issue by newhoggy** [actions/virtual-environments#2584] opened 2021-01-28 20:56 UTC
**Description**  
From time to time, some of our builds in Github Actions get really flaky because HTTPS downloads and git clones intermittently fail.

This has been occurring more often in the past two days.

It appears to be a problem with the network infrastructure at Github itself. We end up having to do work arounds like this:

https://github.com/input-output-hk/cardano-node/pull/2313

I would like Github Actions to be more reliable with downloads and would appreciate if Github can investigate and resolve this issue.

**Area for Triage**:  

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- `ubuntu-latest`
- `macos-latest`
- `windows-latest`

**Expected behavior**  
Downloads/uploads of files from https and clones/fetch/push for git should always work.

**Actual behavior**  
These things fail.

**Repro steps**  
Fork git@github.com:input-output-hk/cardano-node.git, then branch and push a commit.  Occasionally this will fail.

**Comment by LeonidLapshin** [comment] 2021-02-01 10:36
Hey, @newhoggy !
I looked at https://github.com/input-output-hk/cardano-node/pull/2313 and as far as I can see the problem was with checkout job while cloning repo. Steps that I have tried:
1) created an empty repo
2) created a scheduled workflow that tries to clone "input-output-hk/cardano-node" many times (24 clone actions on each job) with checkout job, delete repo and clone again
```
      - uses: actions/checkout@v2
        with:
          repository: 'input-output-hk/cardano-node'
      - name: delete all
        run: | 
          rm -rf ** && find . -name . -o -prune -exec rm -rf -- {} +
```
3) I run it on ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, macos-10.15 and did not catch any error on 50 runs on each OS, 50*24 clone actions totally

Also I have tried steps that you provided(Fork git@github.com:input-output-hk/cardano-node.git, then branch and push a commit), but have no error on push.

Seems that it is related not to images themselves because it fails on any OS, but to some networking while establishing a connection to Github. Windows and macOS runners are located in different datacenters, so connections that fail are from different locations as well and it seems that the problem is related to Github.com itself, not the image or specific datacenter. 

There is a similar issue [Error: The process '/usr/bin/git' failed with exit code 128](https://github.com/actions/checkout/issues/417) in the checkout actions repo. Could you please share details in that ticket if any?
Thank you!

**Comment by LeonidLapshin** [comment] 2021-02-18 07:08
Hey, @newhoggy !
As I have mentioned earlier, seems that the problem is not with the image, so I'll close the issue, but feel free to reopen it if you have any concerns.
Thank you!

**Closed by LeonidLapshin** 2021-02-18 07:08 UTC
Labels: investigate

**Comment by stardustman** [comment] 2021-09-14 03:30
self-hosted github runner, how to do it use checkout actions?
