### ISSUE TITLE
[CMAKE] Could not find psapi using find_library

### ISSUE THREAD

**Issue by julianxhokaxhiu** [actions/virtual-environments#3826] opened 2021-08-01 12:03 UTC
### Description

```
##[error]CMake Error at .build/vcpkg_installed/x86-windows-static/share/ffmpeg/FindFFMPEG.cmake:68 (find_library):
  Could not find FFMPEG_DEPENDENCY_psapi_RELEASE using the following names:
  psapi
Call Stack (most recent call first):
  .build/vcpkg_installed/x86-windows-static/share/ffmpeg/FindFFMPEG.cmake:148 (append_dependencies)
  .build/vcpkg_installed/x86-windows-static/share/ffmpeg/vcpkg-cmake-wrapper.cmake:6 (_find_package)
  C:/vcpkg/scripts/buildsystems/vcpkg.cmake:736 (include)
  CMakeLists.txt:68 (find_package)
-- Configuring incomplete, errors occurred!
See also "D:/a/1/s/.build/CMakeFiles/CMakeOutput.log".
Microsoft (R) Build Engine version 16.10.2+857e5a733 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
```

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019

### Image version and build link

https://dev.azure.com/julianxhokaxhiu/Github/_build/results?buildId=1193&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=d1e88c09-dceb-53c1-5579-19c846f3526a

### Is it regression?

Not sure

### Expected behavior

CMake is able to find the library

### Actual behavior

CMake is not able to find the library

### Repro steps

1. Create a `CMakeLists.txt` file
2. Paste this content inside
    ```cmake
    find_library(PSAPI NAMES "psapi" REQUIRED)
    ```
3. Proof it

Lookup behavior documentation available at this link: https://cmake.org/cmake/help/latest/command/find_library.html

**Comment by julianxhokaxhiu** [comment] 2021-08-01 15:23
Looking at https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md it seems the Windows SDK is not provided by default, and that's why is not able to find the `psapi.lib` file which should be located in this path:
```
C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0\um\x86\Psapi.Lib
```

Running the same CMake command locally on my own workstation where the Windows SDK is installed, is able to successfully find the library.

**Comment by dibir-magomedsaygitov** [comment] 2021-08-01 16:31
Hello @julianxhokaxhiu. Thank you for your report. We will take a look.

**Comment by julianxhokaxhiu** [comment] 2021-08-01 16:43
> Hello @julianxhokaxhiu. Thank you for your report. We will take a look.

First of all, thank you! I really appreciate the time you'll spend on this.

Second, meanwhile you get this fixed, may I ask which is the current `Microsoft.VisualStudio.Component.Windows10SDK.19041` component path on the disk? So I could set it via ENV VAR in CMake using [`CMAKE_WINDOWS_KITS_10_DIR`](https://cmake.org/cmake/help/latest/variable/CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION.html).

Thank you in advance!

**Comment by julianxhokaxhiu** [comment] 2021-08-11 12:32
> Will this action meet your needs? Please note that this action is provided by a third-party and not certified by GitHub.

Hi, thank you for the hint but that's exactly what I'm doing in my own snippet posted in the message. The action is just another way to accomplish the same thing. Would be nice if this is auto-configured in the environment without the need to accomplish that, or, to provide an **official** task which is well documented and maintained in the https://docs.microsoft.com/en-us/azure/devops/pipelines/apps/windows/cpp?view=azure-devops page.

**Comment by dibir-magomedsaygitov** [comment] 2021-08-12 11:57
Hello @julianxhokaxhiu. Thank you for your reply.
I was able to reproduce the issue on my local machine. I think it is expected behavior. If you run `cmake` from default shell, VS tools won't be available. Tasks like `ilammy/msvc-dev-cmd` just enable Visual Studio Command Prompt. Visual Studio Command Prompt is additional shell that is installed by Visual Studio and intended for specific goals - building applications via VS. We should not set it by default. Please take a look at [this discussion](https://github.com/actions/virtual-environments/issues/1621#issuecomment-696654393) for more information.

**Comment by julianxhokaxhiu** [comment] 2021-08-12 13:38
I see. Weird though that is working on my own side without never using that shell. I'm using Windows Terminal with the `Git Bash` environment, running cmake from there ( cmake is found in `C:\Program Files\Cmake`, as instructed by PATH ) and vcpkg is located at `C:\vcpkg` as I cloned the repo there ).

Same goes when building my project on VSCode using [these instructions](https://github.com/julianxhokaxhiu/FFNx#visual-studio-code). Might be the shell you use by default is not inheriting something from the environment, which might be fulfilled by using then the action you suggested.

Allright then, I'll try to integrate your own action in my own pipeline. Is that official and maintained or is it a community action that might be deprecated without due notice?

**Comment by julianxhokaxhiu** [comment] 2021-08-12 15:32
Thank you, I'll do so later then and test it.

So if no further actions are required on your end, I'd close this issue if it's fine by you. Let me know or feel free to do so!

**Comment by dibir-magomedsaygitov** [comment] 2021-08-13 06:50
@julianxhokaxhiu thank you, I'll close this issue. Feel free to contact us in case of any questions.

**Comment by julianxhokaxhiu** [comment] 2021-08-14 15:19
Sorry to re-open it but apparently the solution doesn't work on Azure DevOps: https://dev.azure.com/julianxhokaxhiu/Github/_build/results?buildId=1225&view=results

Error message:
```
/.ci/azure.yml (Line: 52, Col: 9): Task reference must be in the format <NAME>@<MAJOR_VERSION> or <NAME>@<MAJOR_VERSION.MINOR_VERSION.PATCH_VERSION>. For example MyTask@2 or MyTask@2.3.1. The following task reference format is invalid: 'ilammy/msvc-dev-cmd@v1'
```

My `azure.yaml`:
```yaml
steps:
# ...
- task: ilammy/msvc-dev-cmd@v1
# ...
```

**Comment by julianxhokaxhiu** [comment] 2021-08-16 11:05
I was thinking that another way to tackle this is providing a task like this one: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops

But instead it we could name it "DevToolsPowershell" which would start basically this session:
![image](https://user-images.githubusercontent.com/1237070/129553788-9bda9300-6693-47af-8637-19453d4754f4.png)

And the syntax to use it would be:
```yaml
steps:
# ...
- task: DevToolsPowerShell@2
  inputs:
    filePath: path/to/script.ps1
    failOnStderr: true
    pwsh: true
# ...
```

What do you think?

**Comment by miketimofeev** [comment] 2021-08-16 12:01
@julianxhokaxhiu could you please file an issue here as we're not responsible for azure tasks https://github.com/microsoft/azure-pipelines-tasks?

**Comment by miketimofeev** [comment] 2021-08-16 12:07
And could you try one of these solutions?
https://github.com/actions/virtual-environments/issues/294#issuecomment-588090582
https://github.com/actions/virtual-environments/issues/1978#issuecomment-721695697

**Comment by julianxhokaxhiu** [comment] 2021-08-16 13:41
> 
> 
> @julianxhokaxhiu could you please file an issue here as we're not responsible for azure tasks https://github.com/microsoft/azure-pipelines-tasks?

Will do, thanks.

> 
> 
> And could you try one of these solutions?
> [#294 (comment)](https://github.com/actions/virtual-environments/issues/294#issuecomment-588090582)
> [#1978 (comment)](https://github.com/actions/virtual-environments/issues/1978#issuecomment-721695697)

As mentioned [here](https://github.com/actions/virtual-environments/issues/3826#issuecomment-890551809) I'm already using the workaround, so technically my issue is "solved", although I think this deserves a better workflow which is standard and works across projects.

I thought it was worth to share the fact that the proposed solution [here](https://github.com/actions/virtual-environments/issues/3826#issuecomment-896757893) doesn't work on Azure DevOps, but I wasn't aware the tracking of this issue had to be moved on the aforementioned repository. I'll consider opening an Issue or PR, targeting my own proposal which I think it would be a great improvement to the platform.

Regarding this issue feel free to do what you think is right, as now it's clear the scope of this issue is completely out of the governance of what you can do. Thanks!

**Comment by miketimofeev** [comment] 2021-08-16 14:03
@julianxhokaxhiu thanks! I'll close the issue then. Please feel free to contact us if you need any support,

**Closed by miketimofeev** 2021-08-16 14:03 UTC
Labels: Area: C/C++, OS: Windows, investigate
