### ISSUE TITLE
KVM: entry failed, hardware error 0xffffffff

### ISSUE THREAD

**Issue by vt-alt** [actions/virtual-environments#5128] opened 2022-02-23 21:18 UTC
### Description

It's well known that GA does not have KVM support. But sometimes there is `/dev/kvm` device present and tooling (such as `mkosi`) tries to boot `qemu` using KVM support. Most of the times it fails right away, but sometimes boot of Linux proceeds several milliseconds and it fails in the middle of the boot process with `KVM: entry failed, hardware error 0xffffffff` message. Examples:
https://github.com/lkrg-org/lkrg/runs/5251323060?check_suite_focus=true
https://github.com/lkrg-org/lkrg/runs/5251322870?check_suite_focus=true

We would greatly appreciate a bit more explanations of GA KVM setup with the goal to detect this situation and to prevent failure of running qemu with kvm (in generic way).

Currently we [thought that opening /dev/kvm](https://github.com/systemd/mkosi/pull/915) device is enough to reliably detect KVM presence, but if qemu sometimes proceeds to the middle of Linux boot this may signify it wasn't enough.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

  Version: 20220213.1

### Is it regression?

Unknown.

### Expected behavior

No /dev/kvm if there is no KVM support.

### Actual behavior

There is /dev/kvm **sometimes** but qemu fails to work with KVM in the middle of Linux boot.

### Repro steps

It's intermittent.

**Comment by nikolai-frolov** [comment] 2022-02-24 07:07
Hello @vt-alt and thanks for the issue reporting. Could you please provide a simple project/yml where we can reproduce the issue?

**Comment by vt-alt** [comment] 2022-02-25 08:04
Well, there is workflow yml linked from the logs https://github.com/lkrg-org/lkrg/actions/runs/1865735694/workflow I don't know if this is simple enough.
Basically, mkosi checked for presence of `/dev/kvm` so you perhaps can just run `ls -l /dev/kvm` until there is vm with that file.
Since I don't know problem cause I cannot suggest how to debug it afterwards.

**Comment by nikolai-frolov** [comment] 2022-02-25 08:57
Thanks, we'll take a look and reply with findings.

**Comment by miketimofeev** [comment] 2022-02-25 09:33
@vt-alt I suspect this could be related to the different underlying hardware in Azure. Related issue https://github.com/actions/virtual-environments/issues/3389

**Comment by catthehacker** [comment] 2022-02-25 09:51
You could try checking if CPU has SVM (AMD) or VMX (Intel) virtualisation capabilities flags
```sh
grep -E '(vmx|svm)' /proc/cpuinfo
```

**Comment by vt-alt** [comment] 2022-02-27 04:34
I think if there is no VMX or SVM then Linux KVM driver cannot be loaded and thus there will be no `/dev/kvm` device. For example, loading kvm-intel on AMD:
```
# modprobe kvm-intel
modprobe: ERROR: could not insert 'kvm_intel': Operation not supported
# dmesg | tail -1
[1164180.841327] kvm: no hardware support
# ls -l /dev/kvm
ls: cannot access '/dev/kvm': No such file or directory
```
For example loading kvm-amd on Intel:
```
# modprobe kvm-amd
modprobe: ERROR: could not insert 'kvm_amd': Operation not supported
# dmesg | tail -2
[526987.668362] has_svm: not amd
[526987.668399] kvm: no hardware support
# ls -l /dev/kvm
ls: cannot access '/dev/kvm': No such file or directory
```
Perhaps, if `/dev/kvm` is present then there is VMX or SVM that let kernel KVM driver to be loaded.

On GA there, _sometimes_ (not always) is `/dev/kvm` device. But, it's not working properly, thus confusing software that detects availability of KVM by presence of `/dev/kvm`.

Also, Linux is able to boot several milliseconds with qemu KVM support enabled, That would not be possible is there is no KVM driver and there cannot be a driver loaded if there is no VMX or SVM.

**Comment by catthehacker** [comment] 2022-02-27 05:07
> For example, loading kvm-intel on AMD

Well, obviously you can't load module for a specific CPU vendor on a different CPU vendor (world would be much easier if that was possible)
I would recommend *not using kvm accel* or unload kvm modules to prevent failure (`rmmod kvm_intel` then `rmmod kvm` since Azure uses Intel) as you won't get stable virtualisation support due to hardware differences of VMs used in GHA.

> Perhaps, if `/dev/kvm` is present then there is VMX or SVM that let kernel KVM driver to be loaded.

`kvm` modules will load automatically if `svm` or `vmx` flag is present

**Comment by vt-alt** [comment] 2022-02-28 03:11
FYI. I tried to reproduce the issue (where `/dev/kvm` exists) with a simplistic workflow with `ls -l /dev/kvm` but for a day running in `schedule` does not reproduced it.

**Comment by mikhailkoliada** [comment] 2022-02-28 18:40
> FYI. I tried to reproduce the issue (where `/dev/kvm` exists) with a simplistic workflow with `ls -l /dev/kvm` but for a day running in `schedule` does not reproduced it.

Hi!

We are running different types of machines and some of them may or may not have kvm enabled, so the only way for you I guess is to always make sure that no kvm module is loaded in advance with `rmmod`, blacklisting any kbm modules from our side does not seem viable.

**Comment by vt-alt** [comment] 2022-03-01 01:09
@mikhailkoliada Thanks. Yes I just rm'd `/dev/kvm` to fix ways of mkosi. Question was — we wanted to understand more a cause of the problem to invent generic solution — how to detect such non-working kvm, and why it's suddenly fail after some milliseconds of boot.

**Comment by mikhailkoliada** [comment] 2022-03-23 14:26
@vt-alt the thing is, there are virtual machines with and without kvm support, you can never know which machine will be used for which job of yours, so it is better to always check the ability to unload the kvm module straight in the workflow, we can not do anything specific about it.

I am going to close this issue but feel free to reach us out if you have questions left.

**Closed by mikhailkoliada** 2022-03-23 14:26 UTC
Labels: OS: Ubuntu, Area: Common Tools, bug report
