### ISSUE TITLE
Running a Linux self-hosted agent in Docker

### ISSUE THREAD

**Issue by nreddipalle** [actions/virtual-environments#783] opened 2020-04-27 04:02 UTC
**Describe the bug**
This is more of a question/request. Anyone able to successfully build a docker image using the script file https://github.com/actions/virtual-environments/blob/master/images/linux/ubuntu1804.json setting up as dockerfile as reference and try to build an image..

**Area for Triage**: 

**Question, Bug, or Feature?**: 
Question

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
Build an image successfully using the https://github.com/actions/virtual-environments/blob/master/images/linux/ubuntu1804.json as reference

**Actual behavior**
Failing at various shell scripts..

1. Step 1
2. Step 2

**Comment by alepauly** [comment] 2020-04-28 14:23
Hi @nreddipalle, you might be interested in this: https://github.com/actions/virtual-environments/issues/196. This has been tried in the past with mixed results.

**Comment by nreddipalle** [comment] 2020-04-28 14:58
Thanks @alepauly . I will take a look.

**Comment by miketimofeev** [comment] 2021-12-20 10:15
Closing as duplicate of https://github.com/actions/virtual-environments/issues/666

**Closed by miketimofeev** 2021-12-20 10:15 UTC
Labels: question, OS: Ubuntu, Area: Deployment/Release, community-feature
