### ISSUE TITLE
Persistent networking issue breaks all file transfers

### ISSUE THREAD

**Issue by ViRb3** [actions/virtual-environments#3073] opened 2021-04-01 01:23 UTC
**Description**  
I run my personal server that I use to store various building artifacts. The internet uplink is 200 Mbit/s, so it is definitely not slow. When I try to download any file from my server on one of your **macOS** machines, the speed starts really well (upwards of 7MB/s), but as soon as it hits ~70-100MB downloaded, the speed drops down to exactly 19.6kb/s. After a few minutes the connection is lost completely. This issue happens about 19 out of 20 times, where 1 time it would work completely fine. I have been experiencing this for at least the past 7 days, tested dozens of times every day. 

I bolded macOS above because this *only* happens on those machines, *not* on your Linux builders, not on any other server or computer I have tried - and I tried a lot. The only other place where I see this issue is (un)surprisingly [Semaphore CI](https://semaphoreci.com/), and again, only on their macOS machines, not their Linux machines. I suppose you both use the same provider (MacStadium?), and the issue lies there. I verified with multiple home-owned Mac machines and they can download from my server just fine.

I tried replacing my entire server hardware and the issue does not resolve. I contacted my ISP and after an investigation they reported that there are no problems on their end. I tried dozens of combinations of client and server software, and I even tried iperf3 - they all experience the exact same behavior.

This issue is a huge blocker for many of my workflows as I can essentially not build for macOS. Any help is much appreciated.

**Area for Triage**:  
Servers

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
`macos-latest`. I am not sure how to find any other version.

**Expected behavior**  
Downloads from my server complete.

**Actual behavior**  
Downloads hang and break after about 5 minutes.

![2021-04-01_02-27-45](https://user-images.githubusercontent.com/2650170/113230902-eed85400-9291-11eb-85ef-c8072437821c.gif)

**Repro steps**  
I created a simple reproduction repository [here](https://github.com/ViRb3/macos-ci-network-issue). You can see the failing CI logs here:
- Semaphore CI [page](https://virb32.semaphoreci.com/workflows/2fe60e68-0a6a-4930-ba32-f5a7d37618ca?pipeline_id=772d2528-d27c-4a3c-b2ef-a9280697b593), [raw](https://virb32.semaphoreci.com/jobs/f25aabc4-da55-4411-8216-a532eb44b6ce/plain_logs.txt)
- GitHub Actions [page](https://github.com/ViRb3/macos-ci-network-issue/actions/runs/706985909)

Note that for privacy concerns I have added the IP address of my server as a secret, so it will not be visible. If you technically can, by all means feel free to restart or debug the workflows, or to extract the IP address. Otherwise, I am happy to provide you with the IP address in a more private form of communication.

Thank you a lot in advance.

**Comment by miketimofeev** [comment] 2021-04-01 06:38
Hi @ViRb3!
We use different cloud providers so the very first question is — does the issue happens all the time or sometimes download finishes without any issues?

**Comment by ViRb3** [comment] 2021-04-01 11:07
Hello, thanks a lot for the prompt response. Indeed, the issue does not always occur - sometimes the download will complete without absolutely any problems. I'd say the success rate of Semaphore is about 1 in 20, and while I haven't extensively measured the success rate of Github, it seems to be more about 1 in 3 (30%).

**Comment by miketimofeev** [comment] 2021-04-01 11:13
@ViRb3 thanks! That explains a lot. Could you please add the following step to your pipeline so we can correlate the issue with the particular environments?
`ls /usr/local/opt/runner/settings/instancename` — the output will be the instance name

**Comment by ViRb3** [comment] 2021-04-01 11:32
No problem at all! I added the line but the action is taking a long time to start. I will let you know when it runs.

**Comment by Darleev** [comment] 2021-04-01 11:43
@ViRb3 If it is suitable for you, you can add me as a contributor to the test repo and I'll reproduce the issue by myself and collect all required data accordingly.
I guess, push changes to the repo will be enough for triggering GitHub actions workflow and reproduce an error.

**Comment by ViRb3** [comment] 2021-04-01 11:46
@Darleev I have invited you. The action has been queuing for over 20 minutes and still hasn't started, apologies for the delay.

**Comment by Darleev** [comment] 2021-04-01 12:22
@ViRb3 I'm afraid to affect the remote server by GitHub actions downloads. How many simultaneous processes can I call to the remote server? I need to collect statistics and maybe it will be required to start about 30-50 runs.

**Comment by ViRb3** [comment] 2021-04-01 12:30
@Darleev You can run as much as you want/the server can handle, I am counting it in maintenance mode today. It is a Raspberry Pi 4 with 200 Mbit uplink FWIW.

**Comment by ViRb3** [comment] 2021-04-01 13:07
@Darleev I have some additional debug information I would like to share with you, but it contains private identifiers. Can I e-mail you or message you in any private way? I would take the repository private and share in the README, but I'm afraid that I'm running somewhat low on private minutes. Thanks.

**Comment by Darleev** [comment] 2021-04-01 15:14
@ViRb3 May I contact you using e-mail in your profile to clarify all details?

**Comment by ViRb3** [comment] 2021-04-01 17:10
@Darleev I'll be more than happy :)

**Comment by Darleev** [comment] 2021-04-08 14:33
Hello @ViRb3,
We've gathered all required data and forwarded the issue to our internal engineering team.
We will keep you informed.

**Comment by ViRb3** [comment] 2021-04-08 16:03
Thank you very much for the effort and continuous updates @Darleev, I really appreciate everything you are doing!

**Comment by ViRb3** [comment] 2021-04-19 05:18
Hello @Darleev just wondering if there's any update on this situation? Thanks

**Comment by Darleev** [comment] 2021-04-27 19:34
@ViRb3 we're still working on this.
As soon as new details appear, I'll let you know.

**Comment by Darleev** [comment] 2021-08-16 11:12
Hello @ViRb3,
We tried to find a root cause for the issue you experienced in the past, but with no luck at this time. Could you please confirm that issue is still actual?
We're looking forward to your reply.

**Comment by Darleev** [comment] 2021-08-17 19:31
@ViRb3 I'm going to close the issue until further clarifications from your side.
In case of any questions, do not hesitate to contact us.

**Closed by Darleev** 2021-08-17 19:31 UTC
Labels: Area: Apple, Area: Servers, OS: macOS, investigate
