### ISSUE TITLE
Ubuntu: Random checkout error 'RPC failed; curl 18 transfer closed with outstanding read data remaining'

### ISSUE THREAD

**Issue by kinke** [actions/virtual-environments#2198] opened 2020-12-04 12:53 UTC
Since a few days, I'm seeing random git checkout errors on the Ubuntu 16.04 agents. It sometimes works after the built-in retries, e.g.:

```
git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=50 origin +a8493d48a94f309415c9d467b44b45daa7d6e200:refs/remotes/origin/a8493d48a94f309415c9d467b44b45daa7d6e200
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: expected flush after ref listing
##[warning]Git fetch failed with exit code 128, back off 2.551 seconds before retry.
git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=50 origin +a8493d48a94f309415c9d467b44b45daa7d6e200:refs/remotes/origin/a8493d48a94f309415c9d467b44b45daa7d6e200
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: error reading section header 'acknowledgments'
##[warning]Git fetch failed with exit code 128, back off 5.444 seconds before retry.
git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --progress --no-recurse-submodules --depth=50 origin +a8493d48a94f309415c9d467b44b45daa7d6e200:refs/remotes/origin/a8493d48a94f309415c9d467b44b45daa7d6e200
remote: Enumerating objects: 10253, done.        
[...]
```

There's apparently a single retry attempt for git submodules, so most of the time the fatal error shows up there, e.g.:

```
Cloning into '/home/vsts/work/1/s/runtime/phobos'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: expected flush after ref listing
fatal: clone of 'https://github.com/ldc-developers/phobos.git' into submodule path '/home/vsts/work/1/s/runtime/phobos' failed
Failed to clone 'runtime/phobos'. Retry scheduled
Cloning into '/home/vsts/work/1/s/runtime/phobos'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: expected flush after ref listing
fatal: clone of 'https://github.com/ldc-developers/phobos.git' into submodule path '/home/vsts/work/1/s/runtime/phobos' failed
Failed to clone 'runtime/phobos' a second time, aborting
```

See https://dev.azure.com/ldc-developers/ldc/_build/results?buildId=2367&view=results for complete logs.

Windows and Mac agents are working fine.

**Comment by miketimofeev** [comment] 2020-12-04 13:04
Hi @kinke!
Have you tried other Ubuntu images (18&20)? Is the issue reproduced on them?
It would also be great if you can find the very first build where the problem occured.

**Comment by kinke** [comment] 2020-12-04 13:13
Hi!

We only use Ubuntu 16 and I cannot easily test more recent ones (using incompatible prebuilt artifacts...).

There has sadly been a gap of a few days where no CI job was run. It worked on Tuesday with agent v2.177.1 and image 20201116.1 and has apparently started failing yesterday with image 20201129.1 (and same agent v2.177.1).

**Comment by kinke** [comment] 2020-12-04 13:24
Okay, same problem with Ubuntu 18 - needed a retry attempt in https://dev.azure.com/ldc-developers/ldc/_build/results?buildId=2368&view=logs&j=6ea9c875-28ae-5ccb-884f-87b087a71264&t=f2c23072-feb0-51fd-e583-7d0635c80241.

**Comment by miketimofeev** [comment] 2020-12-04 13:54
@kinke thanks for provided data, looks like something wrong with the network.
Could you try setting http.postBuffer to a larger value?
`git config --global http.postBuffer 524288000`
or even
`git config --global http.postBuffer 1048576000`

**Comment by kinke** [comment] 2020-12-04 14:05
No change: https://dev.azure.com/ldc-developers/ldc/_build/results?buildId=2370&view=logs&j=6ea9c875-28ae-5ccb-884f-87b087a71264&t=f2c23072-feb0-51fd-e583-7d0635c80241

**Comment by miketimofeev** [comment] 2020-12-04 14:16
@kinke limiting depth from 50 to something lower doesn't help as well?

**Comment by kinke** [comment] 2020-12-04 14:19
Nope, with depth 1: https://dev.azure.com/ldc-developers/ldc/_build/results?buildId=2371&view=logs&j=d63d0aa7-5d01-5c9f-d5bd-b8a45119ae4e&t=cbe78056-7f38-5e3a-e2fa-239747596e82

**Comment by miketimofeev** [comment] 2020-12-04 14:44
@kinke Thank you. I've tried to fork the repo and set up the same pipeline in azure devops in 2 different orgs — everything works fine with cloning, no errors at all.
We'll investigate deeper, I'll keep you posted.

**Comment by miketimofeev** [comment] 2020-12-04 16:14
Quick update: we're able to reproduce it in the same Azure region, searching for the root cause.

**Comment by kinke** [comment] 2020-12-04 23:09
Thx for looking into this. - FWIW, I've just retriggered the 3 failed Linux jobs for the last relevant pipeline, and this time the checkout worked flawlessly without any retry attempts.

**Comment by Tranduchuy12** [comment] 2020-12-05 02:28
https://github.com/actions/virtual-environments/issues/2198

**Comment by miketimofeev** [comment] 2020-12-05 11:05
@kinke I can't see the issue either. Looks like the network back to normal.
I'm going to close the issue, but please feel free to contact us if the issue reappears.
Thank you!

**Closed by miketimofeev** 2020-12-05 11:05 UTC
Labels: Area: Deployment / Release, OS: Ubuntu, investigate

**Comment by jaapcrezee** [comment] 2026-09-02 12:17
This issue is still present and thus not fixed nor has otherwise disappeared.

Reproduced on Azure Pipelines Microsoft-hosted `ubuntu-24.04` agents in 2026, cloning a GitHub-hosted submodule (eclipse-paho/paho.mqtt.cpp) via `checkout: self` with `submodules: recursive`.

Symptom is intermittent — same pipeline definition, same submodule, sometimes succeeds, sometimes fails:

fatal: could not read Username for 'https://github.com/': terminal prompts disabled
fatal: expected flush after ref listing
fatal: clone of 'https://github.com/eclipse-paho/paho.mqtt.cpp' into submodule path '<path>' failed
Failed to clone '<submodule>'. Retry scheduled
[... retry fails identically ...]
Failed to clone '<submodule>' a second time, aborting

Confirmed not an auth/credentials issue:
- Repo is public; a standalone `git ls-remote https://github.com/eclipse-paho/paho.mqtt.cpp` run as a separate script step on the same agent, same job, succeeds reliably.
- Reproduced identically across two separate Azure DevOps organizations/projects, so it isn't an org-specific token scoping or policy setting.

Confirmed `submodules: recursive` is set correctly on the checkout step (not a case of submodules being unconfigured).

Given the "could not read Username" + "expected flush after ref listing" combination appearing together, and that a plain `ls-remote` from the same agent doesn't reproduce it, this looks consistent with the ref-advertisement being interrupted mid-transfer during the submodule clone specifically (this submodule has 100+ refs including a large number of `refs/pull/*/head` and `refs/pull/*/merge` entries), with git's client misreporting the resulting broken response as needing credentials.

Happy to attach full pipeline YAML and raw logs if useful for triage.

**Comment by jaapcrezee** [comment] 2026-09-02 12:46
Follow-up: setting `retryCountOnTaskFailure: 4` on the checkout step greatly reduces the frequency of failures I'm seeing, but it's symptom management, not a real fix — the underlying intermittent ref-advertisement interruption is still happening, we're just retrying the whole checkout step until it gets lucky.

Minimal repro for reference:

.gitmodules:
[submodule "paho.mqtt.cpp"]
        path = paho.mqtt.cpp
        url = https://github.com/eclipse-paho/paho.mqtt.cpp

azure-pipelines.yml:
pool:
  vmImage: ubuntu-24.04

steps:
  - checkout: self
    submodules: recursive
    clean: true
    retryCountOnTaskFailure: 4

**Comment by Caitlyn50** [comment] 2026-09-02 12:58
> This issue is still present and thus not fixed nor has otherwise disappeared.

Why no do a issue instead of do a comment on a 6 years old issue ?

**Comment by jaapcrezee** [comment] 2026-09-02 13:03
@Caitlyn50 for sure I could file a new issue. Any idea where and under what title?

**Comment by Caitlyn50** [comment] 2026-09-02 13:04
> [@Caitlyn50](https://github.com/Caitlyn50) for sure I could file a new issue. Any idea where and under what title?

By click new issue 

<img width="660" height="1434" alt="Image" src="https://github.com/user-attachments/assets/4d77c922-2a41-44f4-82ad-df8cf11880c1" />
