### ISSUE TITLE
latest windows 2022 agents doesn't have the Storage emulator pre-installed where as 2019 does

### ISSUE THREAD

**Issue by sureshbemagani** [actions/virtual-environments#4650] opened 2021-12-02 06:30 UTC
### Description

The windows 2022 images doesnt have the Storage emulator installed. The same is avialable in 2019 images.

https://github.com/actions/virtual-environments/blob/win22/20211130.3/images/win/Windows2022-Readme.md

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

https://github.com/actions/virtual-environments/blob/win22/20211130.3/images/win/windows2022.json

### Repro steps

Search for storage emulator in this documentation. Same can be observed when we trry to use this agent in the RD wwhich uses Storage emulator as one of the task.

https://github.com/actions/virtual-environments/blob/win22/20211130.3/images/win/Windows2022-Readme.md

**Comment by shilovmaksim** [comment] 2021-12-02 07:36
Hi @sureshbemagani. We will think about adding Azure storage emulator to the Windows 2022 image and will let you know.

**Comment by miketimofeev** [comment] 2021-12-06 14:44
Hi @sureshbemagani!
Could you please point us to the workload\component that contains storage emulator for VS2022?
https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-enterprise?view=vs-2022

**Comment by sureshbemagani** [comment] 2021-12-07 10:32
I dont find it in the link. But, i raised this question because the [storage emulator](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#workloads-components-and-extensions) was part of windows-2019 agents but not windows-2022. If the issue is with vs2022, pls assign this issue to concerned team.

**Comment by miketimofeev** [comment] 2021-12-07 12:57
@sureshbemagani does your local VS2022 installation have this component? If it doesn't work locally either, please address the problem in the https://developercommunity.visualstudio.com/

**Comment by miketimofeev** [comment] 2021-12-13 12:05
@sureshbemagani I'm going to close the issue.
Please feel free to reopen\contact us once the component name is known.
Thank you!

**Closed by miketimofeev** 2021-12-13 12:05 UTC
Labels: OS: Windows, Area: Image administration, Area: Common Tools, feature request

**Comment by maryammadzadeh** [comment] 2022-07-12 03:12
Can we reopen this. The 2022 VS installation has this and this is not a problem locally.

**Comment by miketimofeev** [comment] 2022-07-12 07:29
@maryammadzadeh I still can't see this component for VS2022. Is it a part of some other workload?

**Comment by maryammadzadeh** [comment] 2022-07-12 13:58
"Can we reopen this? The 2022 VS installation has this and this is not a problem locally." - me

Somehow my previous comment is gone (reposted above). I am just using the vs 2022 installed IDE. I'm not sure about the component here. but opening VS 2022 and running tests that start the azure storage emulator does not reproduce the error that ado gives with storage emulator.  It possible that the vmImage in ADO needs to use azurite (but thats is not needed locally). Either way, this is still an issue and should we reopened since at some point the 2019 vmimage will be "blown out" in ADO making builds fail without the 2022 vm image in ado having a solution.

**Comment by maryammadzadeh** [comment] 2022-07-12 14:06
For installed workloads I have: 
![image](https://user-images.githubusercontent.com/43354588/178509241-731bd3e5-c335-4d0a-89ab-9a520d68f5d7.png)

Hope this helps.

**Comment by maryammadzadeh** [comment] 2022-07-12 17:21
Does it help that the error ADO pipeline gives using the vmImage windows-2022 prints
"An error occurred trying to start process 'C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe' with working directory "

It looks like the vm just doesnt have the storage emulator installed by default.

**Comment by al-cheb** [comment] 2022-07-12 17:29
> Does it help that the error ADO pipeline gives using the vmImage windows-2022 prints "An error occurred trying to start process 'C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator\AzureStorageEmulator.exe' with working directory "
> 
> It looks like the vm just doesnt have the storage emulator installed by default.

You could install AzureStorageEmulator in runtime:
`choco install azurestorageemulator`

As I can see - https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator

> The Azure Storage Emulator is now deprecated. Microsoft recommends that you use the [Azurite](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azurite) emulator for local development with Azure Storage.

**Comment by maryammadzadeh** [comment] 2022-07-12 17:38
Also note - I only caught this because I was using windows-latest as my vm image, which worked fine up until a month ago. So when the vm images move forward (im guess windows-latest is no pointing to windows 2022 over time this essentially breaks customer pipelines without notice. Adding the storage emulator or azurite in the latest vm images will prevent breaking changes from happening. Thoughts?

**Comment by maryammadzadeh** [comment] 2022-07-12 17:43
Azurite is  automatically available with vs2022 which is probably why it works. 
![image](https://user-images.githubusercontent.com/43354588/178558158-c4ce56d5-a956-45aa-821f-8a1fff703de2.png)

**Comment by mm-nbergen** [comment] 2023-04-04 17:41
> Azurite is automatically available with vs2022 which is probably why it works.

We've been unable to move to Azure due to some incompatibilities with the TableStorage API (https://github.com/Azure/Azurite/issues/19), which means that Azurite isn't a drop-in replacement for us.  We'll pursue installing the emulator with chocolatey for now.  Thanks for that suggestion, @al-cheb.
