### ISSUE TITLE
Workflow using docker-compose running pytest results I/O operation on closed file 

### ISSUE THREAD

**Issue by BrightRan** [actions/virtual-environments#808] opened 2020-04-30 07:09 UTC
In this [Community Forum ticket](https://github.community/t5/GitHub-Actions/Workflow-using-docker-compose-running-pytest-results-I-O/td-p/56291), the user is trying to setup a workflow for his project, which uses **`docker-compose`** to run tests with **`pytest`**. However executing **`pytest`** results the following error in the workflow run.
```
[3384] Failed to execute script docker-compose
Traceback (most recent call last):
  File "site-packages/dockerpty/pty.py", line 334, in start
  File "site-packages/dockerpty/pty.py", line 367, in _hijack_tty
  File "site-packages/dockerpty/io.py", line 59, in select
  File "site-packages/dockerpty/io.py", line 351, in fileno
  File "site-packages/dockerpty/io.py", line 103, in fileno
  File "socket.py", line 638, in fileno
ValueError: I/O operation on closed file.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 72, in main
  File "compose/cli/main.py", line 128, in perform_command
  File "compose/cli/main.py", line 519, in exec_command
  File "site-packages/dockerpty/pty.py", line 338, in start
  File "site-packages/dockerpty/io.py", line 32, in set_blocking
  File "site-packages/dockerpty/io.py", line 351, in fileno
  File "site-packages/dockerpty/io.py", line 103, in fileno
  File "socket.py", line 638, in fileno
ValueError: I/O operation on closed file.
##[error]Process completed with exit code 255.
```

This project can work fine on the local.

**Comment by swissspidy** [comment] 2020-04-30 15:43
If it helps with investigation, I'm running into the same issue with https://github.com/google/web-stories-wp/pull/1399, where I intend to use Docker to spin up a website for testing.

**Comment by Darleev** [comment] 2020-04-30 19:58
@BrightRan  @swissspidy Hello,
I was not able to reproduce the issue anywhere except GitHub Actions, most probably it is related to specific implementation of Github agents jobs execution. However, we found very similar[ git hub issue with the same problem](https://github.com/docker/compose/issues/5696) and it was fixed by adding -T flag to `docker-compose exec app pytest` like in example below:

`docker-compose exec -T app pytest`

I have tested this workaround in the [public repository provided](https://github.com/villekr/github-actions-dockercompose-pytest), and it is working perfectly fine.

**Comment by BrightRan** [comment] 2020-05-01 06:53
@Darleev ,
Great! I also tested on my side, it works.
Thanks very much for sharing your solution.

**Comment by villekr** [comment] 2020-05-04 04:50
Yep, that -T option does the trick. Thanks for quick actions on this!

**Comment by Darleev** [comment] 2020-05-04 14:15
@villekr I am glad that this solution helped.
In case of any questions, do not hesitate to contact us.

**Closed by Darleev** 2020-05-04 14:15 UTC
Labels: Area: Deployment/Release, OS: Ubuntu, investigate
