### ISSUE TITLE
Same Pipeline fails: WiX toolset ERROR since today (vm image depreciated) 

### ISSUE THREAD

**Issue by PatrickGrub** [actions/virtual-environments#4573] opened 2021-11-23 15:23 UTC
### Description

Our [WiX projects](https://wixtoolset.org/) have been built on azure pipeline vmImage `VS2017-Win2016` for 2 years.
Since today all are failing to build! (read below)

I have read about the [deprecation of that VM Image](https://devblogs.microsoft.com/devops/hosted-pipelines-image-deprecation/#windows) and we should use instead `windows-2019`. But using the new 2019 image I retrieve the same error.

Error:
```
 Error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\WiX\v3.x\Wix.targets" was not found. Confirm that the path in the <Import> declaration is correct and that the file exists on disk.
```

This is the project file that was built successfully with Azure DevOps until today.
[Server_Setupx64.zip](https://github.com/actions/virtual-environments/files/7589083/Server_Setupx64.zip)

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

windows-2019
VS2017-Win2016

### Is it regression?

Yes

### Repro steps

Build on Azure devops vm Image `VS2017-Win2016` a WiX project, see here an example:
[Server_Setupx64.zip](https://github.com/actions/virtual-environments/files/7589124/Server_Setupx64.zip)

**Comment by dibir-magomedsaygitov** [comment] 2021-11-23 15:30
Hello @PatrickGrub. Thank you for your report. Could you please provide us minimal reprosteps to help with the investigation.

**Comment by PatrickGrub** [comment] 2021-11-23 15:30
I think its the same problem like here
https://github.com/actions/virtual-environments/issues/4419#issuecomment-973783256

**Comment by barnson** [comment] 2021-11-23 15:38
https://github.com/actions/virtual-environments/issues/4419#issuecomment-976734435

**Comment by dibir-magomedsaygitov** [comment] 2021-11-23 15:42
Closing this issue as duplicate of [#4419](https://github.com/actions/virtual-environments/issues/4419)

**Closed by dibir-magomedsaygitov** 2021-11-23 15:42 UTC
Labels: needs triage

**Comment by shawntoffel** [comment] 2021-11-23 22:39
We have encountered this problem as well. It seems to be broken only for newer image versions so some builds pass and some fail depending on which image version we get. 

For `vs2017-win2016` our build runs fine on image version `20211109.0`. Image version `20211115.1` fails with above error.

For `windows-2019` image version `20211110.1` passes, and `20211122.1` fails with the above error. 

I'm not sure if it's related, but I see there were some changes to the Install-Wix.ps1 script here  https://github.com/actions/virtual-environments/commit/4672cb208d045a5a6fb0083a0baed1da88af9e68#diff-ba92a7e0ead6d234c40a1e79c585b1642f15d25c54700ddb4ebabf9256927b3e

**Comment by PatrickGrub** [comment] 2021-11-24 12:21
I could solve it by using vm image "windows-latest.

**Comment by AlmightyFuzz** [comment] 2021-11-25 14:00
We've just run into the same issue as @shawntoffel. As of this morning our builds (using `windows-2019` vm) are failing and reporting that the `wix.targets` file cannot be found at `C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\WiX\v3.x\Wix.targets`

On vm image version `20211110.1` the same build is successful, while on vm image version `20211122.1` the build fails with the above error.

**Comment by PatrickGrub** [comment] 2021-11-25 15:37
Indeed it was not solved by using  `windows-latest`. I just had the luck getting image version `20211110.1` . But now sometimes I get image version `20211122.1` and then fails.

Also the "workaround" with the wixproj file did not help I tried windows 2016, 2019 and 2022 images: https://github.com/actions/virtual-environments/issues/4419#issuecomment-978916739

**How can I use in the YML file a specific image version?**

**Comment by PatrickGrub** [comment] 2021-11-25 15:59
Now, I corrected my wixproj file, I have missed deleting the entries in the property group mentioned here: https://github.com/actions/virtual-environments/issues/4419#issuecomment-979319218

Now it works with every image version!
