### ISSUE TITLE
Failures during Python Virtual Environment creation with Poetry since a few days.  

### ISSUE THREAD

**Issue by KelSolaar** [actions/virtual-environments#1343] opened 2020-08-01 06:03 UTC
**Describe the bug**
I noticed recurring failures of [our CI builds](https://github.com/colour-science/colour/actions) since a few days, the builds typically error with and `EOFError`, `PermissionError` or `IOError` on Linux and Windows when the Python Virtual Environments are created with Poetry. Sometimes the build just goes through fine upon being relaunched.

**Area for Triage**: 

Python

**Question, Bug, or Feature?**: 

Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**
The builds should go through and create the Python Virtual Environments without failing.

**Actual behavior**

Here are a few runs that failed:

# EOFError

https://github.com/colour-science/colour/runs/911041143?check_suite_focus=true#step:8:21

```
[EOFError]
Compressed file ended before the end-of-stream marker was reached
```

This one launched a few minutes after with non-code modification passes without problems:

https://github.com/colour-science/colour/actions/runs/182879849

# PermissionError

https://github.com/colour-science/colour/runs/934575620?check_suite_focus=true#step:6:21

```
[PermissionError]
[WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\tmpwgiyjjf_\\matplotlib-3.1.3.tar.gz'
```

# IOError

https://github.com/colour-science/colour/runs/934624329?check_suite_focus=true#step:8:23

```
[IOError]
CRC check failed 0x2d9e3ede != 0x6184ac0fL
```

**Comment by KelSolaar** [comment] 2020-08-01 09:51
We just got another one:

# HTTPError

https://github.com/colour-science/colour/pull/615/checks?check_run_id=934987368

```
502 Server Error: Gateway Error for url: https://files.pythonhosted.org/packages/be/06/81367951cc50695830482eacefdc8289c68770db166a4d4283e7eac22dee/matplotlib-3.2.0.tar.gz
```

**Comment by MaksimZhukov** [comment] 2020-08-05 11:06
Hello @KelSolaar ! Thank you for the your report!

In scope of our investigation of this issue we have found that your CI builds started to fail 13 days ago ([first build](https://github.com/colour-science/colour/runs/901363016?check_suite_focus=true) with `EOFError` error). When builds started to fail the Ubuntu 18.04 image version was 20200717.1 and the Windows 2019 image Version was 20200714.1. The same image versions were used in your successful builds, for example [here](https://github.com/colour-science/colour/runs/897815670?check_suite_focus=true). This means that the Ubuntu and Windows images have not changed and could not cause this issue.

You can check image version by yourself in `Set up job` step in your builds, for example:
![imageVersion](https://user-images.githubusercontent.com/46996400/89404584-eb9cc080-d722-11ea-8ff6-6e92922d4433.png)

Probably, this issue can be caused by some dependencies in your project. Unfortunately, we are not experts in Python and Poetry, but I have noticed something strange in your [build logs](https://github.com/colour-science/colour/runs/934624329?check_suite_focus=true#step:8:23) that you attached to issue description. If you refresh the logs you will see the following error:
```
/home/runner/.poetry/lib/poetry/_vendor/py2.7/subprocess32.py:149: RuntimeWarning: The _posixsubprocess module is not being used. Child process reliability may suffer if your program uses threads.
```
instead of:
```
[IOError]
CRC check failed 0x2d9e3ede != 0x6184ac0fL
```
I have found two issues in the [python-poetry/poetry](https://github.com/python-poetry/poetry) repository related to this error:
- [Issue №1257](https://github.com/python-poetry/poetry/issues/1257)
- [Issue №2106](https://github.com/python-poetry/poetry/issues/2106)

I hope this will be helpful for you.

**Comment by KelSolaar** [comment] 2020-08-06 05:24
Thanks for your time @MaksimZhukov!

We have seen that warning and it has not been an issue so far since we run on Github Actions BUT maybe it is actually one now! I will check the Poetry version too, it could certainly be the root cause, that being said we were always using a fixed version until p**p** started to hit the fan with builds breaking randomly. I will dig more and report if I find something!

**Comment by KelSolaar** [comment] 2020-08-06 06:33
So I tried to reduce the matrix size just to check and without using Python 2 at all to remove it from the equation and 2 builds went through while another popped: https://github.com/colour-science/colour/runs/952379647

```
[ConnectionError]
('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
```

I'm wondering if it could be too many concurrent access to Pypi or something along those lines.

**Comment by MaksimZhukov** [comment] 2020-08-07 15:14
I've configured a workflow using the [fix from issue №1257](https://github.com/python-poetry/poetry/issues/1257#issuecomment-516132057) and I've started getting only two types of errors:
```
[EOFError]
Compressed file ended before the end-of-stream marker was reached
```
and
```
[HTTPError]
502 Server Error: Gateway Error for url: https://files.pythonhosted.org/packages/7d/d4/e4c40c62cd8608ca09f0684e64139c56512e195f2351ac41a472d4dc8b38/matplotlib-3.3.0.tar.gz
```
Basically I run into the first type of error. This error appears randomly on Ubuntu 18.04 and Windows 2019 and does not depend on Python version. As far as I understand, this could be caused by file corruption during download. Probably it is related to some connection issue.

It looks like we have a similar [issue with the pip](https://github.com/actions/virtual-environments/issues/1354) in our repository.

We will continue to investigate this issue and will keep you updated!

**Comment by KelSolaar** [comment] 2020-08-07 22:30
Thanks for looking at that @MaksimZhukov! I’m certainly leaning toward connection related issues too. It seems a bit random but often ending up with the consequences of a network connection ending up abruptly. I will try to re-run my simplified matrix with the verbose args on Poetry. My gut feeling and I could be wrong is that it makes to many concurrent requests at Pypa.

**Comment by KelSolaar** [comment] 2020-08-08 06:37
I just enabled verbose with `-vvv` on the same code than https://github.com/colour-science/colour/runs/952379647 and it is passing: https://github.com/colour-science/colour/runs/960969131

**Comment by MaksimZhukov** [comment] 2020-08-10 10:06
Unfortunately `-vvv` option could not completely solve this issue. I ran 10 builds and 4 of them failed with the same error:
```
[EOFError]
Compressed file ended before the end-of-stream marker was reached
```

**Comment by KelSolaar** [comment] 2020-08-12 08:36
I asked the pypi.org people, and they don't see anything correlated with what we see on their end: https://discuss.python.org/t/error-these-packages-do-not-match-the-hashes-from-the-requirements-file/4926/4?u=kelsolaar

**Comment by MaksimZhukov** [comment] 2020-08-14 14:51
This issue no longer reproduces for me. Could you please check if you still see the same issue?
Thanks!

**Comment by KelSolaar** [comment] 2020-08-15 06:53
It seems to be fine indeed! I will monitor our builds over the next few days and let you know!

**Comment by KelSolaar** [comment] 2020-08-17 10:51
I think it is fixed @MaksimZhukov! Thanks! What was it?

**Comment by MaksimZhukov** [comment] 2020-08-17 11:34
Unfortunately, we do not know. We have not been able to find out the root cause of this issue. It seems that this issue was resolved by itself. 

Please let us know if you encounter this issue again! Thank you!

**Closed** 2020-08-17 11:41 UTC
Labels: Area: Deployment / Release, Area: Python, OS: Ubuntu, OS: Windows, investigate

**Comment by KelSolaar** [comment] 2020-08-17 20:08
> Unfortunately, we do not know. We have not been able to find out the root cause of this issue. It seems that this issue was resolved by itself.

This is quite concerning but glad it is solved.
