### ISSUE TITLE
Tk broken with Python 3.7 on macOS 10.15

### ISSUE THREAD

**Issue by QuLogic** [actions/virtual-environments#5511] opened 2022-05-09 23:24 UTC
### Description

On the mentioned system, loading tk has started failing with:
```
E             File "/Users/runner/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/tkinter/__init__.py", line 2025, in __init__
E               self._loadtk()
E             File "/Users/runner/hostedtoolcache/Python/3.7.13/x64/lib/python3.7/tkinter/__init__.py", line 2040, in _loadtk
E               % (_tkinter.TK_VERSION, tk_version))
E           RuntimeError: tk.h version (8.6) doesn't match libtk.a version (8.5)
```
This used to work on the image from ~1 week ago.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current image version: 20220501.1

https://dev.azure.com/matplotlib/matplotlib/_build/results?buildId=25698&view=logs&j=2a0d89e6-f0af-5d93-2ea5-38c6235c2d51&t=cb21fa9b-a1c3-57fa-90e9-7d9d0311b902&l=381

### Is it regression?

Previously working image version: 20220424.1
https://dev.azure.com/matplotlib/matplotlib/_build/results?buildId=25635&view=logs&j=0de6cdcb-72d7-5519-795d-247cd4b3fb83

### Repro steps

See matplotlib build in links above.

**Comment by QuLogic** [comment] 2022-05-09 23:26
The [documentation update](https://github.com/actions/virtual-environments/commit/30007c570303fe3ca1f13fc1de787667623a2e25) suggests this was likely to be either a bug in updating Python 3.7.12 to 3.7.13 or possibly a change in Homebrew from 3.4.7 to 3.4.9.

**Comment by mikhailkoliada** [comment] 2022-05-10 09:13
A duplicate of https://github.com/actions/setup-python/issues/402

**Closed by mikhailkoliada** 2022-05-10 09:13 UTC
Labels: needs triage, bug report
