### ISSUE TITLE
API rate limit exceeded for Mac OS hosted by GitHub itself

### ISSUE THREAD

**Issue by evandrocoan** [actions/virtual-environments#602] opened 2020-03-23 02:57 UTC
**Describe the bug**
I have setup GitHub Actions for Windows, Linux and Mac OS. Both of them use the https://github.com/arduino/actions, and are working fine, except for the Mac OS machine, which keeps complaining: https://github.com/evandroforks/anki/runs/526371357?check_suite_focus=true
```
 Set up protoc0s
##[error]API rate limit exceeded for 199.7.166.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
Run Arduino/actions/setup-protoc@master
  with:
    version: 3.x
    include-pre-releases: false
  env:
    pythonLocation: /Users/runner/hostedtoolcache/Python/3.7.6/x64
##[error]API rate limit exceeded for 199.7.166.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
```

![image](https://user-images.githubusercontent.com/5332158/77276004-61cee800-6c98-11ea-8e1a-3a2008c9d584.png)

**Area for Triage**: 

**Question, Bug, or Feature?**:
"Bug"

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
GitHub Actions hosted by GitHub itself, should not be complaning about API rate limits, as it is GitHub own server/machine which is originating the GitHub Request for another GitHub Service (GitHub Actions).

**Actual behavior**
API rate limit exceeded.
https://github.com/evandroforks/anki/runs/526371357?check_suite_focus=true

**Comment by maxim-lobanov** [comment] 2020-03-23 09:13
Hello,
The issue comes from the way how GitHub counts requests for rate limit. For unauthorized requests, it limits by IP. All macOS VMs have the same IP address because of infrastructure.

GitHub complains about rate limit regardless of the source of request because GA workflow can be used to spam API too.
The most promising solution is improving those setup tasks to use authorized API requests instead of anonymous ones.
@alepauly , do you have any thoughts about it?

**Comment by fenollp** [comment] 2020-03-23 15:50
I'd like to emphasize that windows and ubuntu runners do not get caught by rate limiting (probably because there are many more of these machines).
This makes it pretty surprising to the user (lessens the user experience).

Isn't it possible for all the runners to use the credentials of the user that pushed commits or created the job?

Do you have a link that helps setup explicit authentication in workflows, so this can be used as a workaround?

**Comment by alepauly** [comment] 2020-03-23 16:34
@evandrocoan, @fenollp: I'm following up with the infrastructure team to figure out solutions to this. I'll update as soon as I get some answers.

**Comment by evandrocoan** [comment] 2020-03-23 16:46
> Isn't it possible for all the runners to use the credentials of the user that pushed commits or created the job?

This seems to be the best to solution to avoid the spammers problem.

**Comment by alepauly** [comment] 2020-03-23 17:56
@evandrocoan Just a quick not that it doesn't look like the `setup-protoc` Action you are using supports specifying the token. If you were able to do that, then you will certainly be able to get around the current issue. I'm still following with infrastructure to see if there is something we can do but I think the better bet is to perhaps contribute to that Action so it allow the API request to be authenticated. Auth'd requests have a higher limit than anonymous so that should solve the problem.

**Comment by evandrocoan** [comment] 2020-03-23 19:33
Thanks for point it out. And as a side note, looks like this think of API rate limit is going to be a more common problem when GitHub Actions get more used. On that case, our Actions Workflow files would have to look like this for every action:
```yml
name: Windows Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache pacman
        uses: actions/cache@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          path: C:\Program Files\Git
          key: ${{ runner.os }}-pacman-${{ hashFiles('**/windows_checks.yml') }}

      - name: Set up python
        uses: actions/setup-python@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          python-version: 3.7

      - name: Set up protoc
        uses: Arduino/actions/setup-protoc@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          node-version: 12

      - name: Upload python wheels
        uses: actions/upload-artifact@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          name: windows_python_wheels
          path: dist
```

If you pay attention, every third part action would require to have an `with: repo-token: ...`, which just seems redundant. As of now, the action which I was getting in trouble with was `Arduino/actions`, but tomorrow it can be any other action. 

So, for a consistent `Workflow` (which always work and do not fail for due third part tools), all actions should have this `with: repo-token: ...` thing. Then, instead of the user (me) keep adding that redundant thing of `with: repo-token: ...`, the GitHub Actions Environment could inject this `with: repo-token: ...` into my recipes automatically. Therefore, all existent actions nowadays (as http://github.com/Arduino/actions) would have to be updated to start accepting this `with: repo-token: ...` thing.

**Comment by fenollp** [comment] 2020-03-23 20:19
In my case the 403s I get from github are from plain curls to github.com. See [these logs on macOS](https://pipelines.actions.githubusercontent.com/oUOdksEit8zdW9voySCih4MnhoBNxALpnImZ9fdEq4ebOxji4l/_apis/pipelines/1/runs/11/signedlogcontent/7?urlExpires=2020-03-23T20%3A17%3A13.6319048Z&urlSigningMethod=HMACV1&urlSignature=6cbNlTSxRQk0aZ9zENeG5pTTiEn0UFeucMK0pz3SQjg%3D).

I agree that this issue is bound to come up more often as GAs usage grows. Let's see what infra people have to say :)

**Comment by maxim-lobanov** [comment] 2020-03-24 06:05
@evandrocoan , Actually, All these actions (except Arduino) doesn't use GitHub API so they are not affected by rate limit issue. The `setup-protoc` is the single one [that use it](https://github.com/arduino/setup-protoc/blob/master/src/installer.ts#L154).
In general, I agree, all actions that invokes GitHub API directly should have repo-token parameter but as I know not many actions really invoke GitHub API.

As for your case, I think I have found the root cause of your issue:
You use legacy version of `setup-protoc` (`uses: Arduino/actions/setup-protoc@master`) task from deprecated repository: https://github.com/arduino/actions/tree/master/setup-protoc.
The new version is available as `uses: arduino/setup-protoc@v1.1.0` and it supports `repo-token` parameter.
Looks like owner of action [doesn't update README properly](https://github.com/marketplace/actions/setup-protoc) so readme points to the old way to install task :(
If you click `Use latest version` button, the correct way to install task will be showed.

Just checked in my repo and 
![image](https://user-images.githubusercontent.com/16715858/77393605-6c7ba100-6dae-11ea-8380-80edaa63d1cb.png)
works perfect for me. Could you please try it from your side?

**Comment by evandrocoan** [comment] 2020-03-24 17:16
Thanks @maxim-lobanov! It is working 100% now! https://github.com/evandroforks/anki/runs/531198664?check_suite_focus=true (the build is just failing due Mac OS related issues I am solving right now).

**Comment by evandrocoan** [comment] 2020-03-25 19:24
Is it safe to expose `repo-token` to third part GitHub Actions?

On this other topic I found this: https://github.community/t5/GitHub-Actions/Github-Actions-Token-Scope/td-p/39811
> GitHub provides a token that you can use to authenticate on behalf of GitHub Actions, it automatically creates a GITHUB_TOKEN secret to use in your workflow.
The permissions of GITHUB_TOKEN are limited to the repository that contains your workflow. If you need a token that requires permissions that aren't available in the GITHUB_TOKEN, you can create a personal access token and set it as a secret in your repository.

So, this means that GitHub Actions which have access to the `repo-token` have only limited scope and can only operate over the repository where the token is coming from? Does it mean they can erase my code and its history if they fell like? So it should not be safe to pass that token and for security, should I make a fork of GitHub Actions requiring the `repo-token`? (after reviewing its code to assure they are not doing anything nasty)

@dae have forked the repository [arduino/setup-protoc](https://github.com/arduino/setup-protoc) because neither he or me know enough about GitHub's actions architecture, to know whether it's safe to be exposing the GitHub token to third party actions (on this case `arduino/setup-protoc`.

Should he keep the fork he did or it is safe to pass the `repo-token` to the `arduino/setup-protoc` action?

**Comment by maxim-lobanov** [comment] 2020-03-26 12:17
@evandrocoan , 
Sorry, I am not super-familiar with the security side of using community actions so could be wrong, but as I know, `GITHUB_TOKEN` doesn't allow to change repo history, push to master, or something similar. It provides permissions like contributor role (create new branch / pull-request)

Also, good practice is pointing to particular version of Action like `arduino/setup-protoc@v1.1.0` instead of `arduino/setup-protoc@master` because usually code base under particular tag is not updated and your pipeline won't stop work unexpectedly due to new update in Action. If you point master branch, all new changes will be consumed automatically.

Also, as a possible solution, you can generate own PAT manually, put it to the secrets and use instead of System GITHUB_TOKEN. In this case, you will be able to configure scope of your PAT and restrict it fully (to overcome API Rate limit, you can disable absolutely all permissions for token).
Drawback of this approach is that your own secret PAT [won't be available in builds that are triggered on pull requests from forks](https://github.community/t5/GitHub-Actions/Make-secrets-available-to-builds-of-forks/td-p/30678).

**Comment by maxim-lobanov** [comment] 2020-03-27 07:41
@evandrocoan , I am planning to close the issue. Please let me know if you have any other questions or have any concerns

**Closed** 2020-03-30 10:32 UTC
Labels: enhancement, question

**Comment by SamuelMarks** [comment] 2021-03-16 03:55
To overcome this issue [for Python] I wrote—and contributed to public domain—this: https://pypi.org/project/ghapi-conversion

> GHAPI-conversion
> ================
> ![Python version range](https://img.shields.io/badge/python-2.7%20|%203.5%20|%203.6%20|%203.7%20|%203.8%20|%203.9%20|%203.10a6-blue.svg) [![License](https://img.shields.io/badge/license-CC0-blue.svg)](https://creativecommons.org/publicdomain/zero/1.0) [![Linting, testing, coverage, and release](https://github.com/offscale/GHAPI-conversion/workflows/Linting,%20testing,%20coverage,%20and%20release/badge.svg)](https://github.com/offscale/GHAPI-conversion/actions) ![Tested OSs, others may work](https://img.shields.io/badge/Tested%20on-Linux%20|%20macOS%20|%20Windows-green) ![Documentation coverage](https://raw.githubusercontent.com/offscale/GHAPI-conversion/master/.github/doccoverage.svg) [![codecov](https://codecov.io/gh/offscale/GHAPI-conversion/branch/master/graph/badge.svg)](https://codecov.io/gh/offscale/GHAPI-conversion)
> [![Code style: black](https://img.shields.io/badge/code%20style-black-000000.svg)](https://github.com/psf/black) [![Imports: isort](https://img.shields.io/badge/%20imports-isort-%231674b1?style=flat&labelColor=ef8336)](https://pycqa.github.io/isort/) [![PyPi: release](https://img.shields.io/pypi/v/ghapi-conversion.svg?maxAge=3600)](https://pypi.org/project/ghapi-conversion)
>
> CLI to replace HTTP GET on GitHub API with clones.
>
> ## Why
>
> In GitHub Actions the macOS machines share the same IP range, meaning that users will come against the GitHub quota often. https://github.com/actions/virtual-environments/issues/602
>
> To overcome this issue, use this tool instead of `pip install -r`. This tool `clone`s rather than `GET`s:
>
>  - `https://api.github.com/repos/<org>/<repo>/zipball#egg=<package_name>`
>  - `https://raw.githubusercontent.com/<org>/<repo>/<branch>/<file>`
>
> Additionally, it reuses already cloned repos.

PS: It is easy enough to add support for `cargo`, `gem`, `cpan`, &etc. However it might be a better idea to rethink the approach, and launch a proxy before you run your dependency manager, that will do the same run-around my tool does.
