### ISSUE TITLE
Android SDK script hangs during packer build

### ISSUE THREAD

**Issue by gswallow** [actions/virtual-environments#1073] opened 2020-06-18 02:04 UTC
**Describe the bug**
For some reason, the Android SDK installer script hangs -- it appears to be that the sdkmanager can't handle running in a non-interactive environment?  I can't reproduce the failure by hand.  See #1072 

**Area for Triage**: 

**Question, Bug, or Feature?**: 
Bug?

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Comment by maxim-lobanov** [comment] 2020-06-29 12:23
Hello @gswallow , could you please share some context where you run image-generation and logs with error.
We build images in Azure and didn't face with this issue. Nightly CI is green.

**Comment by maxim-lobanov** [comment] 2020-07-07 08:20
Closing this for now since we can't reproduce it on our side and we need additional context.

**Closed by maxim-lobanov** 2020-07-07 08:20 UTC
Labels: Area: Android, Area: C/C++, OS: Ubuntu, community-feature
