### ISSUE TITLE
task.setvariable changes variable casing

### ISSUE THREAD

**Issue by asklar** [actions/virtual-environments#1578] opened 2020-09-13 00:25 UTC
**Description**  
Azure DevOps sets NPM_CONFIG_CACHE (all uppercase). Some tools like yarn/node, they manage to add a lowercase version of some npm variables (`npm_config_cache` for example) by directly setting it in an environment block when calling CreateProcess. This breaks some tools when they encounter duplicate variables in their environment block, like msbuild/CL.exe.

I've submitted a fix to the script that sets up the uppercase variable #1566 .
To work around the problem in the meantime, I added a task in my pipeline to reset the NPM_CONFIG_CACHE variable and then reset it as npm_config_cache:
`Write-Host "##vso[task.setvariable variable=npm_config_cache]$npm_config_cache"`

However it seems like `##vso[task.setvariable]` always sets the variable in uppercase. This is a problem because it makes it impossible for anyone to work around the duplicate env variable problem.

**Area for Triage**:  Scripting and command line

**Question, Bug, or Feature?**:  Bug

**Virtual environments affected**  
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [X] Windows Server 2016 R2
- [X] Windows Server 2019

**Expected behavior**  
task.setvariable does not alter the casing of env variables

**Actual behavior**  
task.setvariable uses the uppercase version of a variable's name

**Repro steps**  

```yaml
  - task: PowerShell@2
    displayName: Reset NPM_CONFIG_CACHE
    inputs:
      targetType: "inline"
      script: Write-Host "##vso[task.setvariable variable=lowercase_variable]some value"
  - task: PowerShell@2
    displayName: Display env
    inputs:
      targetType: "inline"
      script:  gci env:* | sort-object name
```

And notice that the variable shown is `LOWERCASE_VARIABLE` instead of `lowercase_variable`.

**Comment by maxim-lobanov** [comment] 2020-09-13 04:09
Hello @asklar , In this repository, we track only issues related to content of Hosted images and we can't address your issue here.

This issue should be moved to https://github.com/microsoft/azure-pipelines-agent because `setvariable` because `setvariable` and other commands is something that azure-pipelines-agent does. But AFAIK, this behavior is by design and can't be changed in near future. GitHub Actions [Runner](https://github.com/actions/runner) does the same.

**Comment by asklar** [comment] 2020-09-13 04:17
thanks @maxim-lobanov - could you transfer the issue there or do I have to file it separately?

**Comment by maxim-lobanov** [comment] 2020-09-13 05:37
@asklar , we can't transfer this issue because issues can be transferred only within single organization. I will close this one.
Also, I have post comment in your issue https://github.com/microsoft/azure-pipelines-tasks/issues/13538. It can be transferred because it is the single org with azure-pipelines-agent.

**Closed by maxim-lobanov** 2020-09-13 05:37 UTC
Labels: Area: Scripting and command line, investigate, needs triage
