### ISSUE TITLE
NVM tool does not create an environment variable

### ISSUE THREAD

**Issue by ritmos** [actions/virtual-environments#1082] opened 2020-06-19 17:00 UTC
**Describe the bug**
The tool nvm is supposed to create an environment variable called NVM_DIR which points to the directory where the tool is installed. 
On the latest mac agent this works, but on ubuntu 19 or 20 this environment variable doesn't work. I have to relly on $HOME/.nvm to make the tool work

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [?] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [?] Windows Server 2016 R2
- [?] Windows Server 2019

**Expected behavior**
NVM_DIR env variable should point to /home/vsts/.nvm

**Actual behavior**
NVM_DIR env variable does not exist

**Comment by maxim-lobanov** [comment] 2020-06-19 17:34
Hello, 
Default shell doesn't load bashrc and this variable is not initialized properly.
Could you please try to invoke bash as
```
- run: printenv | sort
  shell: bash -l {0}
```

**Comment by ritmos** [comment] 2020-06-20 03:48
Hi,
The issue is in Azure Classic Pipelines with the Command Line Task element. I can not pass arguments to it

**Comment by maxim-lobanov** [comment] 2020-06-20 05:42
Could you please try to add `source $HOME/.bash_profile` as a first line to Command Line Task element? It will be the same like `-l` argument in GitHub Actions

**Comment by ritmos** [comment] 2020-06-20 13:59
Sure!

If I only put the `source $HOME/.bash_profile`, I get:
`N/A: version "10.20.1 -> N/A" is not yet installed.

You need to run "nvm install 10.20.1" to install it before using it.
`
(10.20.1 is the version stated at my project's .nvmrc). So it seems, the nvm tool is wrongly installed in the virtual-environment to begin with. Because it should not execute anything (the rest of the tools don't do that). 

The output part for the `printenv | sort` is:

`AGENT_ACCEPTTEEEULA=True
AGENT_BUILDDIRECTORY=/home/vsts/work/1
AGENT_DISABLELOGPLUGIN_TESTFILEPUBLISHERPLUGIN=true
AGENT_DISABLELOGPLUGIN_TESTRESULTLOGPLUGIN=true
SYSTEM_JOBIDENTIFIER=Job_1.__default
SYSTEM_JOBNAME=__default
SYSTEM_JOBPARALLELISMTAG=Private
SYSTEM_JOBPOSITIONINPHASE=1
SYSTEM_PHASEATTEMPT=1
SYSTEM_PHASEDISPLAYNAME=Agent job 1
SYSTEM_PHASEID=2f97f1d8-1234-abcd-8782-cbcebf2b3d67
SYSTEM_PHASENAME=Job_1
SYSTEM_PIPELINESTARTTIME=2020-06-20 09:32:40-04:00
SYSTEM_PLANID=147fe45a-1234-5678-a477-c91d5013597d
SYSTEM_PULLREQUEST_ISFORK=False
SYSTEM_SERVERTYPE=Hosted
SYSTEM_STAGEATTEMPT=1
SYSTEM_STAGEDISPLAYNAME=__default
SYSTEM_STAGEID=96ac2280-1234-5678-99de-dd2da759617d
SYSTEM_STAGENAME=__default
SYSTEM_TASKDEFINITIONSURI=https://mycompany.visualstudio.com/
SYSTEM_TASKDISPLAYNAME=Command Line Script
SYSTEM_TASKINSTANCEID=40b1ee41-1234-5678-aa04-4b76a5c732e5
SYSTEM_TASKINSTANCENAME=CmdLine
SYSTEM_TEAMFOUNDATIONCOLLECTIONURI=https://mycompany.visualstudio.com/
SYSTEM_TEAMFOUNDATIONSERVERURI=https://mycompany.visualstudio.com/
SYSTEM_TEAMPROJECT=SelfValidationEngine
SYSTEM_TEAMPROJECTID=8251b8fb-1234-5678-af95-bbacc17d7c1e
SYSTEM_TIMELINEID=147fe45a-2321-1234-5678-c91d5013597d
SYSTEM_TOTALJOBSINPHASE=1
SYSTEM_WORKFOLDER=/home/vsts/work
TASK_DISPLAYNAME=Command Line Script
TF_BUILD=True
USER=vsts
VCPKG_INSTALLATION_ROOT=/usr/local/share/vcpkg
VSTS_AGENT_PERFLOG=/home/vsts/perflog
VSTS_PROCESS_LOOKUP_ID=vsts_0f30466a-1234-5678-9b97-32b49a0eb6b5
_=/usr/bin/printenv
agent.jobstatus=Succeeded`


*I have edited all the GUIDs and private stuff

I hope this information is useful to understand the issue.

**Comment by maxim-lobanov** [comment] 2020-06-20 14:41
Yep, I have reproduced issue from my side.
NVM tries to resolve version from nvmrc automatically during call `. "$NVM_DIR/nvm.sh` if `.nvmrc` file exists in current directory. 
Also, I have found the root cause. It is because `default` alias for NVM is not specified during image-generation. I will prepare PR with fix. Thank you for your report.

**Comment by ritmos** [comment] 2020-06-20 17:11
Thanks for your help Maxim!

**Comment by maxim-lobanov** [comment] 2020-06-23 09:10
@ritmos , PR with fix is merged.
We are expecting these changes to be deployed next week. I will keep issue opened for now

**Comment by maxim-lobanov** [comment] 2020-07-02 12:22
@ritmos , image was deployed. Could you please test that everything works as expected?

**Comment by maxim-lobanov** [comment] 2020-07-03 13:11
I have confirmed that issue is resolved. Closing the issue.

**Closed by maxim-lobanov** 2020-07-03 13:11 UTC
Labels: OS: Ubuntu, awaiting-deployment, bug

**Comment by ritmos** [comment] 2020-07-08 12:24
Thanks Maxim and sorry for the late feedback. I was off. It seems to work 👏
