### ISSUE TITLE
VCTargetsPath not set correctly

### ISSUE THREAD

**Issue by Xephobia** [actions/virtual-environments#980] opened 2020-06-02 13:58 UTC
**Describe the bug**
I'm trying to build a project using MSbuild, hoever, it need to import Microsoft.Cpp.Default.props , i found out that it happend when VCTargetsPath string is not set correctly (Microsoft.Cpp.Default.props is located here)

**Area for Triage**: 
C/C++ , .NET Core

**Question, Bug, or Feature?**: 
"Bug"

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**
Microsoft.Cpp.Default.props can be imported because VCTargetsPath is correctly set

**Actual behavior**
Microsoft.Cpp.Default.props cannot be imported because VCTargetsPath is not correctly set

1. Step 1
try to build a .vcxproj file with `dotnet msbuild` wich import Microsoft.Cpp.Default.props from VCTargetsPath

**Comment by vmapetr** [comment] 2020-06-02 14:48
Hi @Xephobia!
Thank you for reporting this issue. While we working on this issue, could you please add workaround that define VSTargetsPath as a system environment variable, to your build definition:
```
setx VCTargetsPath "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140" /M
```

**Comment by maxim-lobanov** [comment] 2020-06-03 09:25
Hello @Xephobia !

I think we don't need to fix anything on image.
To build C++ project, you should use command `msbuild <sln_path>` instead of `dotnet msbuild`
As far as I know, you can't build C++ project via dotnet command because dotnet doesn't support C++. It is expected behavior. Please see related dotnet issue: https://github.com/dotnet/sdk/issues/10239.

**Comment by Xephobia** [comment] 2020-06-03 09:27
as far as i know, msbuild from visual studio isn't set on path, is it stocked in any environment variable?

**Comment by maxim-lobanov** [comment] 2020-06-03 09:29
If you use Azure DevOps image, you can use [Visual Studio Build task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/visual-studio-build?view=azure-devops) to build project.
If you use GitHub Actions, you can use [microsoft/setup-msbuild](https://github.com/microsoft/setup-msbuild) to setup msbuild to PATH.

**Comment by maxim-lobanov** [comment] 2020-06-15 19:28
Closing this issue. Feel free to ping me if you have any concerns or objections

**Closed by maxim-lobanov** 2020-06-15 19:28 UTC
Labels: Area: C/C++, OS: Windows, bug
