### ISSUE TITLE
Xcode iOS unit testing error: The request was denied by service delegate

### ISSUE THREAD

**Issue by simondelphia** [actions/virtual-environments#3678] opened 2021-06-30 19:11 UTC
### Description

After upgrade our Github Actions workflows to use macOS 11 I have seen our unit tests fail with this error:

> error = Error Domain=FBSOpenApplicationServiceErrorDomain Code=1 "The request to open "com.myapp.name" failed." UserInfo={BSErrorCodeDescription=RequestDenied, NSLocalizedDescription=The request to open "com.myapp.name" failed., NSUnderlyingError=0x7fea39024630 {Error Domain=FBProcessExit Code=64 "The process failed to launch." UserInfo={NSUnderlyingError=0x7fea39054c80 {Error Domain=RBSRequestErrorDomain Code=4 "Launch prevented due to "prevent launch" assertion" UserInfo={NSLocalizedFailureReason=Launch prevented due to "prevent launch" assertion}}, BSErrorCodeDescription=launch-failed, NSLocalizedFailureReason=The process failed to launch.}}, FBSOpenApplicationRequestID=0xacc, NSLocalizedFailureReason=The request was denied by service delegate (SBMainWorkspace).})

Not sure what to do about it. Wasting a lot of time on our workflows.

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Image version and build link

Not sure where "Set up job" is

### Repro steps

1. Run Xcode unit tests on Github Actions with our repo
2. Sometimes it fails

**Comment by dibir-magomedsaygitov** [comment] 2021-07-01 03:32
Hello @simondelphia. Thank you for your report. Could you please share the link to your repo to help us to investigate the issue.

**Comment by simondelphia** [comment] 2021-07-01 03:36
Thank you for your reply. The repository is private.

**Comment by dibir-magomedsaygitov** [comment] 2021-07-01 07:23
> Thank you for your reply. The repository is private. I am not allowed to make it public. Is there a way forward without that?

Could you please create public repo with minimal reprosteps?

**Comment by simondelphia** [comment] 2021-07-01 17:01
I could try but since I don't know what's causing it I suspect it will be hard to do.

**Comment by miketimofeev** [comment] 2021-07-05 10:23
@simondelphia thanks, we're waiting for the repro. A couple of questions:
- Have you tried different Xcode versions? Are all of them have the issue?
- Is it possible to make screenshots during the tests? I wonder if there is some permission access notification on the desktop.

**Comment by simondelphia** [comment] 2021-07-05 12:23
Well I don't recall this particular error happening prior to using Xcode 11.

How would I take screenshots?

**Comment by miketimofeev** [comment] 2021-07-05 14:31
@simondelphia well, maybe it's better to try video recording instead since `screencapture` will take the screenshot only after the failure occurred. The recording is not that easy, but something like this using `ffmpeg` and node should work:
```
- name: run integration tests
      timeout-minutes: 30
      run: |
          brew install ffmpeg
          tccutil reset ScreenCapture com.apple.Terminal
          node -e "const exec = require('child_process'); exec.exec('ffmpeg -f avfoundation -i 0 -t 420 out.mov'); exec.exec('xcodebuild clean -scheme \"AccessibilityElementAdaptor UI Tests\" -configuration \"UI Testing\" test');"
    - name: upload screenshot
      if: ${{ always() }}
      uses: actions/upload-artifact@master
      with:
        name: out
        path: out.mov
```
Have you tried to select different Xcode versions?
`sudo xcode-select -s "/Applications/Xcode_<version>.app"`
for example
`sudo xcode-select -s "/Applications/Xcode_12.4.app"` or `sudo xcode-select -s "/Applications/Xcode_11.7.app"` (Both version are available on macOS-11 image)

**Comment by simondelphia** [comment] 2021-07-05 14:54
We can't really downgrade our workflows back to Xcode 12.4 because the tests wouldn't compile without changes.

Will look into the recording, thanks for the suggestion. That could be pretty helpful for some other problems we've been having too.

**Comment by Brett-Best** [comment] 2021-07-06 12:29
Might be related to this issue https://developer.apple.com/forums/thread/679098

**Comment by nikita-bykov** [comment] 2021-07-12 12:06
Hello @simondelphia! Were you able to record a video, was it helpful? If the issue persists, could you please provide us with a public simple repository where the issue can be reproduced for further investigation?

**Comment by simondelphia** [comment] 2021-07-12 12:47
No, I couldn't get that command to work. Wasn't sure how it fit in. I've been trying to reproduce it on a self-hosted runner instead.

**Comment by simondelphia** [comment] 2021-07-13 01:51
Haven't been able to reproduce it on my self-hosted runner yet… 

I  couldn't get the syntax right, could you explain this line further?

> node -e "const exec = require('child_process'); exec.exec('ffmpeg -f avfoundation -i 0 -t 420 out.mov'); exec.exec('xcodebuild clean -scheme \"AccessibilityElementAdaptor UI Tests\" -configuration \"UI Testing\" test');"

Would the call to run the tests go after this?

e.g.,

    bundle exec fastlane integration_test

**Comment by simondelphia** [comment] 2021-07-13 14:29
I thought about using `xcrun` but how would you stop the recording when the tests finish?

**Comment by simondelphia** [comment] 2021-07-13 18:55
Getting an "Invalid workflow file: You have an error in your yaml syntax" error.

**Comment by simondelphia** [comment] 2021-07-13 19:15
Seems to get stuck after the `tccutil` line.

**Comment by nikita-bykov** [comment] 2021-07-14 15:03
@simondelphia, some time ago we got an [issue ](https://github.com/actions/virtual-environments/issues/3395)related to Xcode tests and it reproduces only when flag `Application is agent (UIElement)` is enabled in the `Info.plist`. Could you please check if this flag is enabled and if so then disable it and run your tests.
In the `Info.plist`, this flag is specified as follows:
```
<key>LSUIElement</key>
<true/>
```

**Comment by dmitry-shibanov** [comment] 2021-07-14 15:14
Hello @simondelphia. Thank you for your response. I think you can run it without tccutil. The first `exec.exec` starts video recording, the second command should start your ui tests.
You should enter approximate time for video recording to record the case when your UI tests fail.
```
    - name: run ui test and video recording
      run: |
          brew install ffmpeg
          node -e "const exec = require('child_process'); exec.exec('ffmpeg -f avfoundation -i 0 -t 420 out.mov'); exec.exec('command to run tests');"
    - name: upload video
      uses: actions/upload-artifact@master
      with:
        name: out
        path: out.mov
```
 - 420 - is time for recording in seconds.

**Comment by simondelphia** [comment] 2021-07-15 18:17
> @simondelphia, some time ago we got an [issue ](https://github.com/actions/virtual-environments/issues/3395)related to Xcode tests and it reproduces only when flag `Application is agent (UIElement)` is enabled in the `Info.plist`. Could you please check if this flag is enabled and if so then disable it and run your tests.
> In the `Info.plist`, this flag is specified as follows:
> 
> ```
> <key>LSUIElement</key>
> <true/>
> ```

I don't see this key in any of the Info.plist files in my project.

**Comment by dmitry-shibanov** [comment] 2021-07-19 09:51
Hello @simondelphia. Were you able to record a video? Besides, could you please share which IOS simulators do you use (iPhone XS, iPhone 11 or default one) ?

**Comment by simondelphia** [comment] 2021-07-19 12:21
No I haven't gotten it working. 

iPhone 12 simulator.

**Comment by dmitry-shibanov** [comment] 2021-07-20 09:57
Hello @simondelphia. Thank you for your response. Could you please share more details about video recording issue or if it's possible provide us with a public sample repository where the issue can be reproduced.
Besides, could you please try another simulator ?

**Comment by simondelphia** [comment] 2021-07-20 14:24
I got this error when I tried it:

> No files were found with the provided path: out.mov. No artifacts will be uploaded.

```
      - name: run integration tests
        run: |
              brew install ffmpeg
              tccutil reset ScreenCapture com.apple.Terminal
              node -e "const exec = require('child_process'); exec.exec('ffmpeg -f avfoundation -i 0 -t 420 out.mov'); exec.exec('bundle exec fastlane integration_test');"
      - name: upload screenshot
        if: ${{ always() }}
        uses: actions/upload-artifact@master
        with:
           name: out
           path: out.mov
```

**Comment by dmitry-shibanov** [comment] 2021-07-21 13:14
Hello @simondelphia. Could you please tell us in which time your tests are falling. Possibly when your tests are failed they throw exception and it stops node.js process and tool does not have enough time to record a video. Could please try to change time for video recording.

**Comment by SangKaaa** [comment] 2021-07-26 21:57
> ### Sự miêu tả
> Sau khi nâng cấp quy trình làm việc Github Actions của chúng tôi để sử dụng macOS 11, tôi đã thấy các bài kiểm tra đơn vị của chúng tôi không thành công với lỗi này:
> 
> > error = Error Domain = FBSOpenApplicationServiceErrorDomain Code = 1 "Yêu cầu mở" com.myapp.name "không thành công." UserInfo = {BSErrorCodeDescription = RequestDenied, NSLocalizedDescription = Yêu cầu mở "com.myapp.name" không thành công., NSUnderlyingError = 0x7fea39024630 {Error Domain = FBProcessExit Code = 64 "Quá trình không khởi chạy được." UserInfo = {NSUnderlyingError = 0x7fea39054c80 {Error Domain = RBSRequestErrorDomain Code = 4 "Đã ngăn chặn khởi chạy do khẳng định" ngăn chặn khởi chạy "" UserInfo = {NSLocalizedFailureReason = Đã ngăn chặn khởi chạy do "ngăn chặn khởi chạy" khẳng định}}, BSErrorCodeDescriptionReason = khởi chạy không thành công Quá trình không khởi chạy được.}}, FBSOpenApplicationRequestID = 0xacc, NSLocalizedFailureReason = Yêu cầu đã bị từ chối bởi đại diện dịch vụ (SBMainWorkspace).})
> 
> Không chắc chắn phải làm gì về nó. Lãng phí rất nhiều thời gian cho quy trình làm việc của chúng tôi.
> 
> ### Môi trường ảo bị ảnh hưởng
> * [ ]  Ubuntu 16.04
> * [ ]  Ubuntu 18.04
> * [ ]  Ubuntu 20.04
> * [ ]  macOS 10.15
> * [x]  macOS 11
> * [ ]  Windows Server 2016
> * [ ]  Windows Server 2019
> 
> ### Phiên bản hình ảnh và liên kết xây dựng
> Không chắc "Thiết lập công việc" ở đâu
> 
> ### Nó có phải là hồi quy?
> _Không phản hồi_
> 
> ### Hành vi mong đợi
> _Không phản hồi_
> 
> ### Hành vi thực tế
> _Không phản hồi_
> 
> ### Repro các bước
> 1. Chạy thử nghiệm đơn vị Xcode trên Github Actions với repo của chúng tôi
> 2. Đôi khi nó không thành công

**Comment by simondelphia** [comment] 2021-07-26 22:26
> Hello @simondelphia. Could you please tell us in which time your tests are falling. Possibly when your tests are failed they throw exception and it stops node.js process and tool does not have enough time to record a video. Could please try to change time for video recording.

do you mean like the 420?

**Comment by dmitry-shibanov** [comment] 2021-07-27 15:13
Hello @simondelphia. Yes, it is the time for the video recording in seconds. I think it should be lower than the time of your tests cases, because they can produce exit code, that is why the whole node process is canceled and the video is not recorded.

**Comment by simondelphia** [comment] 2021-07-27 15:14
Pretty sure the tests take longer than 420 seconds.

**Comment by simondelphia** [comment] 2021-07-27 20:25
I just saw it again but this time I have it set up to upload the Xcode test logs — in the automatic screenshot it looks like the app was not installed. Maybe that's significant?

**Comment by nikita-bykov** [comment] 2021-08-04 10:11
Hello @simondelphia. 
Unfortunately, we do not have enough information to reproduce the issue and continue investigating. I'm going to close this issue, but if you have updates that could help us to proceed with our investigation, feel free to contact us.

**Closed by nikita-bykov** 2021-08-04 10:11 UTC
Labels: Area: Apple, OS: macOS, investigate

**Comment by simondelphia** [comment] 2021-08-04 15:33
I've created a public repo but the workflows won't run because the repo doesn't have access to macos-11 — I submitted the form.

**Comment by Brett-Best** [comment] 2021-08-04 19:23
@simondelphia In the meantime I’ve added you to a fork of that repo - you’re welcome to use it while you wait, as I’ve got access to macOS 11 Github Actions. https://github.com/Brett-Best/github-actions-test
