### ISSUE TITLE
An error occurred while provisioning resources (Error Type: Failure).

### ISSUE THREAD

**Issue by uchar** [actions/virtual-environments#3250] opened 2021-04-23 17:10 UTC
**Description**  
In my private repo macOS action fails with this error (It doesn't event start) :

`An error occurred while provisioning resources (Error Type: Failure).
`

![image](https://user-images.githubusercontent.com/5172296/115905554-80934580-a47b-11eb-9375-4879768eb661.png)

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [x] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

It doesn't even run, there is no Setup job, so I don't know but the build script contains this : 

```
  ReleaseToAppStore:
    name: Release to the App Store
    runs-on: macos-latest
    needs: buildForiOsPlatform
.....
```

**Comment by LeonidLapshin** [comment] 2021-04-26 08:29
Hi, @uchar !
We will investigate the issue and will return with details soon :)

**Comment by LeonidLapshin** [comment] 2021-04-26 09:50
Hey, @uchar !
This issue is a duplicate of [https://github.com/actions/virtual-environments/issues/1933](https://github.com/actions/virtual-environments/issues/1933), so I'll close this one. There was an update 3 days ago in 1933, so I guess it can be temporary problem due to capacity issues. 

Please, report the problem to the original issue if it still persist.

**Closed by LeonidLapshin** 2021-04-26 09:50 UTC
Labels: OS: macOS, investigate
