### ISSUE TITLE
Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70

### ISSUE THREAD

**Issue by gzeng1** [actions/virtual-environments#5661] opened 2022-06-01 09:14 UTC
### Description

When I install local app in simulator(iphone 13),  the appium get the error as:
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70 

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

MacOS 11

### Repro steps

Xcode version:13.2.1
Appium version: 1.22.3/1.22.0

When I install local app in simulator(iphone 13),  the appium get the error as:
[XCUITest] Unable to launch WebDriverAgent because of xcodebuild failure: xcodebuild failed with code 70 
[appium1.log](https://github.com/actions/virtual-environments/files/8812778/appium1.log)

I checked the xcode version and appium version but I still met this error.
What should I do?

**Comment by al-cheb** [comment] 2022-06-01 09:16
Hey @gzeng1,
Please provide  a test repo and steps how to reproduce the issue.

**Comment by gzeng1** [comment] 2022-06-07 01:19
@al-cheb 
Here is my workflow file:
name: Guest-debug
on:
  #push:
    #branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/Gemfile
    strategy:
      matrix:
        ruby-version: ['2.5.3']

    steps:        
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Set up rspec
        run: gem install rspec
        
      - name: Set up ios dependecies
        run: brew install ios-deploy
            
      - name: Get UDID of simulator and boot
        uses: futureware-tech/simulator-action@v1
        with:
          model: 'iPad Pro (12.9-inch) (5th generation)'
          os: 'iOS'
          erase_before_boot: true
          shutdown_after_job: true

      - name: Get UDID of 2 simulator and boot
        uses: futureware-tech/simulator-action@v1
        with:
          model: 'iPhone 13'
          os: 'iOS'
          erase_before_boot: true
          shutdown_after_job: true
      
      - name: set udid to caps.yml
        run: |
          guest_udid="`xcrun simctl list devices | grep iPhone| grep "(Booted)" | grep -E -o -i "([0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12})"`"
          pos_udid="`xcrun simctl list devices | grep iPad| grep "(Booted)" | grep -E -o -i "([0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12})"`"
          sed -i ''-e 's|guest_udid_payload|'"${guest_udid}"'|g' /Users/runner/work/restaurant-automation/restaurant-automation/library/test_data/caps.yml
          sed -i ''-e 's|pos_udid_payload|'"${pos_udid}"'|g' /Users/runner/work/restaurant-automation/restaurant-automation/library/test_data/caps.yml
      
      - name: appium check
        run: |
          npm install -g appium@1.22.3
          appium -v  
          appium -p 4726 --webdriveragent-port 8101 --session-override --log /Users/runner/work/appium1.log &
      - name: appium 2 check
        run: | 
          appium -p 4723 --webdriveragent-port 8100 --session-override --log /Users/runner/work/appium2.log &
          
      # run test
      - name: Run tests
        run: |
          cd  ${{github.workspace}}/test/guest
          bundle exec ruby main.rb -s bvt -b guest_simulator -e CERT
      # upload appium log
      - name: Upload Appium log
        if: ${{ failure() || success()}}
        uses: actions/upload-artifact@v2
        with:
          name: appium_log-${{ runner.os }}
          path: /Users/runner/work/appium1.log
          
      # upload appium log
      - name: Upload Appium log
        if: ${{ failure() || success()}}
        uses: actions/upload-artifact@v2
        with:
          name: appium_log-${{ runner.os }}
          path: /Users/runner/work/appium2.log
          
      # upload test reports
      - name: Upload reports HTML
        if: ${{ failure() || success()}}
        uses: actions/upload-artifact@v2
        with:
          name: Guest-bvt-cert-report-${{ runner.os }}
          path: ${{ github.workspace }}/test/guest/output/test_results/*.htm

**Comment by gzeng1** [comment] 2022-06-14 01:43
Is there any update or need other info?

**Comment by gzeng1** [comment] 2022-07-04 01:50
Anyone can help on this ?

**Comment by dmitry-shibanov** [comment] 2022-07-04 13:39
Hello @gzeng1. Sorry for the late response. Could you please provide a public repository to reproduce the issue ? We've tried from our side but could not reproduce it. Does the issue reproduce on previous versions of Xcode ?

**Comment by gzeng1** [comment] 2022-07-05 02:22
@dmitry-shibanov Here is the public repository to reproduce the issue: https://github.com/gzeng1/POS_web/actions/workflows/Guest.yml

Please check

**Comment by dmitry-shibanov** [comment] 2022-07-12 11:24
Hello @gzeng1, just a gentle ping.

**Comment by dmitry-shibanov** [comment] 2022-07-18 12:25
Hello @gzeng1. For now I'm going to close the issue because we can't reproduce it from our side. If you get any additional information feel free to ping us.

**Closed by dmitry-shibanov** 2022-07-18 12:25 UTC
Labels: Area: Apple, Area: Scripting and command line, OS: macOS, bug report
