### ISSUE TITLE
Performance of GitHub-hosted macOS runner

### ISSUE THREAD

**Issue by BrightRan** [actions/virtual-environments#1336] opened 2020-07-31 02:47 UTC
Associated community ticket: https://github.community/t/macos-performance/125281

The customer setup a **matrix** in his workflow to run the same job on different OSs (**`ubuntu-latest`** and **`macos-latest`**).
See the workflow here: https://github.com/gitoleg/bap/actions/runs/187608792/workflow

On some steps in the job, the macOS runner takes far more longer time than the Linux runner (even more than 2 times) to run the steps.

Earlier, I also noticed that some users have reported similar problems. Especially some users who need to pay for runners, they complained that the performance of GitHub-hosted macOS runner is slower and they have to pay more.
As we have known, the billing per-minute for macOS runner is 10 times that for Linux runner.

**Comment by maxim-lobanov** [comment] 2020-07-31 05:09
Hello @gitoleg,
Could you please clarify: did you notice any macOS performance issues recently or they always existed?
We are working on some infrastructure changes related to macOS so we need to understand if it could be related

**Comment by gitoleg** [comment] 2020-07-31 11:48
Hello @maxim-lobanov,
We use Github Actions only for 2 months, maybe even less. And I observe the issue in question during all this time.

**Comment by gitoleg** [comment] 2020-07-31 14:57
@maxim-lobanov,
Maybe it will help somehow. This run was even worse. The whole workflow takes 1 hour on Ubuntu and more than 5 on macOS! 
https://github.com/gitoleg/bap/actions/runs/188588845

**Comment by MaksimZhukov** [comment] 2020-08-25 17:45
Hello @gitoleg ! Sorry for the late reply!
It is expected that MacOS performance is lower than Ubuntu (approximately 20 - 30%), but your build time is really longer than expected. Most likely, it is related to known issue with infrastructure but we can't provide ETA right now.
We will keep this issue open until it is resolved. Thank you for your patience! We will keep you informed!

**Comment by MaksimZhukov** [comment] 2020-08-25 17:45
Hello @gitoleg ! Sorry for the late reply!
It is expected that MacOS performance is lower than Ubuntu (approximately 20 - 30%), but your build time is really longer than expected. Most likely, it is related to known issue with infrastructure but we can't provide ETA right now.
We will keep this issue open until it is resolved. Thank you for your patience! We will keep you informed!

**Comment by gitoleg** [comment] 2020-08-25 20:01
@MaksimZhukov  Thanks!

**Comment by sio** [comment] 2020-09-04 08:20
In the past couple of weeks I've also experienced severe performance degradation on macOS runners.

In one project [I've had to increase](https://github.com/sio/Makefile.venv/commit/2d9c6120d83327680976f8541dace30267ace59e) the timeout value for a function that gets called multiple times by the test suite. Previously timeout was set to sensible 60 seconds since the whole suite runs in 40-50 seconds on Ubuntu, but macOS runners [weren't keeping up](https://github.com/sio/Makefile.venv/runs/1070785796?check_suite_focus=true).

In another project I've moved macOS jobs to another CI provider.

**Comment by paresy** [comment] 2020-09-15 10:27
I can confirm that MacOS performance is very flaky and not consistent. Sometimes it is quite fast and sometimes it degrades to 1/4 of the the normal performance. This is very unsatisfying especially on large/long builds due to the high costs.

**Comment by martinbonnin** [comment] 2020-10-30 23:41
Sometimes our 30min build takes more than 6h. For an exemple: https://github.com/apollographql/apollo-android/runs/1325891021?check_suite_focus=true
This happens randomly but seems more frequent recently. Maybe it's a different thing but it's hard to tell. When this happens, I can't get any log to display. Is it possible to see the logs in real time or maybe even ssh into the vm to debug?

**Comment by bdruth** [comment] 2020-11-07 04:58
Chiming in ... running xcodebuild locally: 266s, on macOS runner: 921s ... that's almost a 3.5x slowdown, with a 10x charge penalty ... that's a bit ridiculous, no? Local: MBP 16 (2.3 GHz 8-Core Intel Core i9).

**Comment by detrin** [comment] 2020-11-17 13:33
I can confirm that MacOS performance is 2x-2.5x slower than ubuntu-latest, when testing Julia package https://github.com/detrin/OpenQuantumSystems.jl

**Comment by syoder** [comment] 2020-12-09 17:39
Some anecdata from a few of my projects:

| Step | time on macOS | time on Ubunutu |
|------|----------------|------------------|
| setting up the job | 11s-27s | 3s |
| checking out the repo | 10s-12s | 2s-5s |

I can run my test suite locally in about 1.5m, but it takes ~6m on Github. When you throw in all the other setup and teardown steps, it's ~10m. If it really were only 20%-30% slower than Ubuntu instances, that would be great.

**Comment by locus313** [comment] 2020-12-29 19:11
I am also seeing very slow performance on the macos runners. The recent runs take about an hour to run:
https://github.com/azerothcore/azerothcore-wotlk/actions/runs/449468989
But when testing the build locally on a mac it takes about 12-16 minutes.

I also noticed the queue time is quite long. sometimes the macos builds are queued for 8+ hours.

**Comment by kariharju** [comment] 2021-02-08 13:02
Building for Win(self-hosted for signing), Mac and Linux we are seeing build times ~8min for Linux and over 20min for Mac.
On top of this Mac builds still quite often fail to some mysterious network errors, which causes the Mac builds to run even more.
Add to this the 10x cost aspect of Mac builds in GHA and the end result is that just about all the costs for us come from Mac builds and we need to start looking to self-hosted Mac machines because this is not sustainable.

**Comment by neil-119** [comment] 2021-02-11 20:54
8 minutes to build on a 2018 MacBook Pro.

GitHub Runner:
![image](https://user-images.githubusercontent.com/4636522/107697048-5867b900-6c78-11eb-8e13-37149bf763ba.png)

Literally unusable with that $0.08/minute pricing.

**Comment by danger89** [comment] 2021-03-01 20:10
Still an issue..

**Comment by jpike88** [comment] 2021-03-02 06:39
From start to finish, my build pipeline takes about 10-15 minutes on a MacBook Pro.

This is GitHub actions:

<img width="342" alt="Screenshot 2021-03-02 at 1 39 00 PM" src="https://user-images.githubusercontent.com/9585787/109608572-a6c3f580-7b5c-11eb-8670-cf1b119e1f79.png">

The logs show nothing abnormal.

We just wasted money and time on a sub-standard service. Why even bother releasing it in it's current form, even as a beta.

**Comment by AlenaSviridenko** [comment] 2021-03-03 08:48
Hi folks,
we are sorry for inconveniences, but these are the technical limitations of our macOS runners, their hardware specification can be found in the official docs https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources. 
Improving performance is on our radar, but unfortunately, no ETA for now.

You can track progress in the related roadmap issue https://github.com/github/roadmap/issues/161.
Closing this one, please, feel free to contact us in case of any other questions. Thank you.

**Closed by AlenaSviridenko** 2021-03-03 08:48 UTC
Labels: Area: Image administration, OS: macOS, investigate

**Comment by paresy** [comment] 2021-03-03 09:15
@AlenaSviridenko Initially this issue was about inconsistent performance for MacOS runners. You can run the same job multiple times and it will take hugely different amount of times to complete. Has this been fixes?

I know that no one should compare GA with his own 8-Core MB Pro and that the roadmap item suggests to throw more powerful machines (=money) on a problem which we cannot predict. I love the option to do so, but i prefer the underlying inconsistency to be fixed.

In my option the initial version of this issue is still valid and should be left open, even if it doesn't look good in the issue list.

**Comment by miketimofeev** [comment] 2021-03-03 10:18
@paresy a few details about performance are available here — https://github.com/actions/virtual-environments/issues/2707#issuecomment-782056996 Basically we can revisit this inconsistency later this year when all the migration is finished.

**Comment by smorimoto** [comment] 2021-03-08 04:27
Well, I guess this was probably related to the random access performance of the storage, as shown in another issue that @miketimofeev touched on (#2707). GitHub (and many other CI providers) relies on providers that provide dedicated Mac hardware, but sometimes they provide *very* old hardware. (IIRC: In fact, Bitrise has had similar problems in the past.)

**Comment by smorimoto** [comment] 2021-03-08 04:36
@paresy 

> i prefer the underlying inconsistency to be fixed

I think we already fixed by #2707 in that sense. (But, obviously, this issue is closed for a completely different reason, and it feels strange to me as well.)

**Comment by jpike88** [comment] 2021-03-08 04:46
I've jumped to Bitrise for now, whatever they have going on it works well

**Comment by smorimoto** [comment] 2021-03-08 05:02
@jpike88 Yes, that's why I said, "in the past" :) Bitrise had a similar problem in the past due to old machines from MacStadium. When I investigated into the network stuff for another issue, there was MacStadium (https://bgp.he.net/AS54112), so I suspected that there might be a similar issue this time.

**Comment by neil-119** [comment] 2021-03-09 21:04
I bought a Mac Mini M1 off eBay for $700 and set it up as an on-prem build agent with Azure Pipelines and it works quite well -- build times back down to 8-10 minutes. Pretty sure it should work for GitHub as well with self-hosted runners.

**Comment by smorimoto** [comment] 2021-03-10 00:54
.NET doesn't officially support Apple Silicon yet, and that's a far cry from the point of this discussion.

**Comment by taylorkline** [comment] 2022-01-28 20:21
@AlenaSviridenko Is this still on the roadmap for Q1 2022 as github/roadmap#161 implies?

**Comment by brianpep** [comment] 2022-03-04 00:54
Would definitely love to see some movement on this issue. We are paying 10x the cost of an Ubuntu runner and getting a tenth of the performance. The main issue I have seen every single time is network timeouts. These timeouts can be seen in the live output when a job runs, but they do not appear in the logs once a job has finished. Have jobs that take 2 minutes on Ubuntu, and over an hour on MacOS, with download steps being the biggest difference.

**Comment by miketimofeev** [comment] 2022-03-18 16:12
@brianpep what kind of downloads did you mean? Is it code checkout or some binaries download?

**Comment by Ziao** [comment] 2022-08-15 16:53
Agred. The performance of macos-latest is abysmal. A simple `yarn install` that would take 15 seconds on my local machine (with node_modules and cache removed) takes upwards of 5 minutes on an action. You cannot charge 10x when performance is 0.1 that of other images. For this reason, we are also looking to simply set up our own physical machine. It'll be cheaper in the (not that) long term.

**Comment by smorimoto** [comment] 2022-08-25 17:04
If you can accept arm64, I think Scaleway's product is relatively good.

**Comment by sneps85** [comment] 2022-09-08 06:43
Same here, CocoaPods install taking over 10 minutes, where local it takes not 1. Please upgrade your infrastructure so that macos images perform in a more realistic way.

**Comment by Sytten** [comment] 2022-09-27 21:29
Community link has been deleted, but definitely still an issue. Our rust builds are 3x slower on mac than other platforms... Really not acceptable considering the price charged.

**Comment by kopax-polyconseil** [comment] 2022-11-08 16:01
Hello, we are stuck trying to run iOS-Simulateur with appium end 2 end test using this runner. Did anyone succeed ? 

I am able only using a self hosted runner, any hint can be appreciated!

**Comment by VOvchinnikov** [comment] 2022-11-09 18:59
Our pure python build takes ~15 minutes to run on `ubuntu-latest` runner, but 30+ minutes on `macos-latest` runner - it would be nice if the issue was actually re-opened as not solved.

**Comment by mfkrause** [comment] 2023-02-16 21:45
+1. Larger (and probably more expensive) macOS runners won't resolve the underlying problem. There is absolutely no reason for these VMs being up 500% to 1000% slower when [they have double the RAM and a full virtual core more than their Linux counterparts](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources).
Adding together the pricing and the performance, macOS runners currently run at about 50-100x the pricing of a Linux runner. Definitely **not** paying this longterm and if you think we're going to pay even more for a larger macOS runner just so we can maybe get to the performance level of a base Ubuntu runner, you must be out of your mind. We'll buy three M2 Pro Minis at that rate, host the runner ourselves and will save money in the process.

**Comment by jozefizso** [comment] 2023-06-20 13:15
We also have performance issues with macOS runners.

MacBook Pro Quad-Core: 60 seconds to build our project
MacBook Pro M2 Pro: 14 seconds
GitHub macOS 12 runner: 9 minutes

With the current pricing model for macOS runners this makes our builds super overpriced.

**Comment by ilia-shipitsin** [comment] 2023-06-20 17:36
@jozefizso , can I ask to open an issue on https://support.github.com ?

this particular issue tracker is related to image generation (i.e. software included and so on), we cannot help much with operations

**Comment by jozefizso** [comment] 2023-06-20 18:28
> @jozefizso , can I ask to open an issue on [support.github.com](https://support.github.com) ?
> 
> this particular issue tracker is related to image generation (i.e. software included and so on), we cannot help much with operations

Great, we are waiting a year for macOS 13 build machine.

**Comment by synth** [comment] 2023-08-09 03:59
This should not be closed. We are also experiencing insanely slow performance of macOS runners. This is one issue among many that result in extremely degraded trust in Github, sadly.

**Comment by Ziao** [comment] 2023-08-09 08:02
No official answer or any form of resolution, and the issue is closed? This is really uncool, Github..

**Comment by aviramha** [comment] 2023-08-24 16:57
This affects us as well.

**Comment by Lessica** [comment] 2023-09-01 06:17
![image](https://github.com/actions/runner-images/assets/5410705/c7bfe584-70c3-415f-a2da-0a98b308036d)
Debugging my first iOS app CI script and fail, over 40 times. $100 gone. Not affordable, at all.
