### ISSUE TITLE
Xamarin iOS no longer compiles on macos-latest

### ISSUE THREAD

**Issue by Recurse-blip** [actions/virtual-environments#775] opened 2020-04-23 13:04 UTC
**Describe the bug**
The Xamarin iOS project was building fine until this morning.

I'm getting the following error :
```
 MTOUCH : error MT0091: This version of Xamarin.iOS requires the iOS 13.4 SDK (shipped with Xcode 11.4). Either upgrade Xcode to get the required header files or set the managed linker behaviour to Link Framework SDKs Only in your project's iOS Build Options > Linker Behavior (to try to avoid the new APIs). [/Users/runner/runners/2.166.3/work/1/s/test-project/xamarin-ios/xamarin-ios.csproj]
```

And also getting the following warning :
```
MTOUCH : warning MT0079: The recommended Xcode version for Xamarin.iOS 13.16.0 is Xcode 11.4 or later. The current Xcode version (found in /Applications/Xcode.app/Contents/Developer) is 11.3.1. [/Users/runner/runners/2.166.3/work/1/s/test-project/xamarin-ios/xamarin-ios.csproj]
```

**Area for Triage**: 
Xamarin

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
To build without errors

**Actual behavior**
1. Create a default Xamarin iOS project
2. Compile it using macos-latest

**Comment by Recurse-blip** [comment] 2020-04-23 15:11
Repo :
https://github.com/Recurse-blip/test-project

I'm not sure what is happening but the same command line works on Github Actions
https://github.com/Recurse-blip/test-project/runs/612367999?check_suite_focus=true

But it doesn't in Azure pipeline 
https://dev.azure.com/jonnehbravo/test-project/_build/results?buildId=3&view=logs&j=f342bb14-ba29-5108-1ccc-19c8096b439e&t=eb818a24-636d-5f17-eb0b-084df71517e7

I use the default xcode installation and  use the default xamarin iOS version.

**Comment by maxim-lobanov** [comment] 2020-04-23 16:34
Okay, I think I know the root cause. On the latest image, default Xcode (11.3.1) is inconsistent with default Xamarin.iOS 13.6. 
Sorry for inconvenience, default Xcode will be updated to 11.4.1 with next image rollout.

Could you please try to add the following step to your pipeline to switch Xcode and fix issue right now?
```
sudo xcode-select -s /Applications/Xcode_11.4.app
```

**Comment by Recurse-blip** [comment] 2020-04-23 17:28
Manually choosing Xcode 11.4 fixed it! Thanks

I ended up doing the following :
```
        echo '##vso[task.setvariable variable=MD_APPLE_SDK_ROOT;]'/Applications/Xcode_11.4.app;
        sudo xcode-select --switch /Applications/Xcode_11.4.app/Contents/Developer
```

**Comment by maxim-lobanov** [comment] 2020-04-23 19:52
Great!
I am closing the issue. Feel free to reopen if you have any questions

**Closed by maxim-lobanov** 2020-04-23 19:52 UTC
Labels: Area: Apple, Area: Xamarin, OS: macOS, investigate

**Comment by jbe2277** [comment] 2020-04-29 17:21
@maxim-lobanov When can we expect the next macos image rollout?

**Comment by maxim-lobanov** [comment] 2020-04-29 17:32
@jbe2277 , it should be deployed tomorrow

**Comment by DavidStrickland0** [comment] 2021-05-17 20:49
**It's Back Xamarin iOS no longer compiles on macos-latest as of 5/17/2021**
Error Reads:
This version of Xamarin.iOS requires the iOS 14.5 SDK (shipped with Xcode 12.5). Either upgrade Xcode to get the required header files or set the managed linker behaviour to Link Framework SDKs Only in your project's iOS Build Options > Linker Behavior (to try to avoid the new APIs). [/Users/runner/work/1/s/Forms/Eperture.Xamarin.Forms.iOS/Eperture.Xamarin.Forms.iOS.csproj]


**Currently looking at the log it appears Macos-Latest is attempting to use SDK for IPhoneSimulator14.4**

_CoreCompileInterfaceDefinitions:
  Tool /usr/bin/xcrun execution started with arguments: ibtool --errors --warnings --notices --output-format xml1 --minimum-deployment-target 8.0 --target-device iphone --target-device ipad --auto-activate-custom-fonts --sdk /Applications/Xcode_12.4.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.4.sdk --compilation-directory /Users/runner/work/1/s/Forms/Eperture.Xamarin.Forms.iOS/obj/iPhoneSimulator/Release/ibtool /Users/runner/work/1/s/Forms/Eperture.Xamarin.Forms.iOS/Resources/LaunchScreen.storyboard

**sudo xcode-select --switch /Applications/Xcode_12.5.app/Contents/Developer**
produces
xcode-select: error: invalid developer directory '/Applications/Xcode_12.5.app/Contents/Developer'

**Comment by miketimofeev** [comment] 2021-05-17 21:52
@DavidStrickland0 we're aware of the issue and currently deploying the new VM image without the recent Xamarin version. A possible workaround for the current image can be found here
https://github.com/actions/virtual-environments/issues/3374

**Comment by DavidStrickland0** [comment] 2021-05-17 22:43
@miketimofeev Thanks for the reply Unfortunately I already tried the fix Detailed by @AlenaSviridenko in https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#how-can-i-manually-select-versions-of-tools-on-the-hosted-macos-agent 
 
sudo xcode-select --switch /Applications/Xcode_12.4.app/Contents/Developer 
but the issue is I need 12.5 (per the error message) and
sudo xcode-select --switch /Applications/Xcode_12.5.app/Contents/Developer gives me 
error: invalid developer directory '/Applications/Xcode_12.5.app/Contents/Developer'

Presumably because 12.5 isn't on the 10.5 image (per https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#xcode) and is instead on the 11.0 image
per https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11.0-Readme.md#xcode
Which of course isn't accessable accept by the few and the proud.
