### ISSUE TITLE
qemu system emulators (aarch64, x86_64) crash in the 20.04lts image

### ISSUE THREAD

**Issue by lersek** [actions/virtual-environments#2292] opened 2020-12-17 20:48 UTC
**Description**  
The edk2 project's Platform CI scripts run QEMU:

https://github.com/tianocore/edk2/blob/e6ae24e1d676bb2bdc0fc715b49b04908f41fc10/ArmVirtPkg/PlatformCI/.azurepipelines/Ubuntu-GCC5.yml#L87

https://github.com/tianocore/edk2/blob/e6ae24e1d676bb2bdc0fc715b49b04908f41fc10/OvmfPkg/PlatformCI/.azurepipelines/Ubuntu-GCC5.yml#L131

The first issue is that in Ubuntu Focal (20.04LTS), the "qemu" package is a dummy package, with no dependencies. It does not pull in the QEMU system emulator binaries, and so the CI run fails. In Bionic (18.04LTS), the `qemu` package would pull in the binaries. Compare:

https://packages.ubuntu.com/bionic/qemu
https://packages.ubuntu.com/focal/qemu

Notice how the latter has no dependencies.

Now, I've tried fixing this by modifying our `apt-get install` commands, replacing the `qemu` package, with the `qemu-system` package name. That package pulls in the emulators in both Bionic and Focal:

https://packages.ubuntu.com/bionic/qemu-system
https://packages.ubuntu.com/focal/qemu-system

*However*, we arrive at the second problem: the QEMU binaries in Focal *crash*. Example:

https://github.com/tianocore/edk2/pull/1236

https://dev.azure.com/tianocore/edk2-ci/_build/results?buildId=16975&view=logs&j=cf2d8b26-a21c-5c68-abf4-b944c123e462&t=5ffbbe5c-1d3a-55f5-5ef3-8a0ef80d76a1

`INFO - Segmentation fault (core dumped)`

So at the moment, we're forced to stick with the `ubuntu-18.04` VM image:

https://github.com/tianocore/edk2/pull/1237

but that's not a long-term solution.

**Area for Triage**:  

Packages

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
A description of what you expected to happen.

No crash; QEMU should exit successfully.

Here's the last successful PR for tianocore/edk2, which genuinely used 18.04LTS (i.e. when `ubuntu-latest` still referred to Bionic):

https://github.com/tianocore/edk2/pull/1232

(Sorry I can't find the successful test logs any longer on Azure.)

**Actual behavior**  
A description of what is actually happening.

See above.

**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

1. Fork the tianocore/edk2 repository.
2. Add an empty line to `ReadMe.rst`
3. Submit a pull request against tianocore/edk2 -- don't worry, it will be auto-closed even if the CI run passes (only maintainers can merge PRs, by setting the `push` label manually; so normal PRs exist only for kicking off CI).
4. Watch the CI run fail.

Note: because we cannot wait for this to be fixed -- we can't currently push any patches! --, we're reverting to `ubuntu-18.04` as quickly as we can, per

https://github.com/tianocore/edk2/pull/1237

Once those patches are merged, the above repro steps will no longer work.

Thanks.

**Comment by LeonidLapshin** [comment] 2020-12-18 13:46
Hey, @lersek!
As I can see, the problem is not related to the image, but to specific package (qemu) that fails so nothing can be done from our side, unfortunately. 
I suggest you to specify ubuntu-18.04 explicitly in your workflows and create an issue in [qemu launchpad](https://launchpad.net/ubuntu/+source/qemu/+bugs )

**Comment by LeonidLapshin** [comment] 2020-12-28 18:39
Hi, @lersek!
As I have mentioned earlier, the problem is not related to image, but the qemu itself, so I'll close this issue for now, but feel free to reopen it if you have any suggestions.

**Closed by LeonidLapshin** 2020-12-28 18:39 UTC
Labels: Area: Packages, OS: Ubuntu, investigate

**Comment by lersek** [comment] 2021-01-06 07:46
Likely related Ubuntu ticket: https://bugs.launchpad.net/ubuntu/+source/qemu/+bug/1908577
