### ISSUE TITLE
Android NDK changed break Unity Engine builds that target Android

### ISSUE THREAD

**Issue by StephenHodgson** [actions/virtual-environments#1036] opened 2020-06-12 06:07 UTC
**Describe the bug**
A clear and concise description of what the bug is, and why you consider it to be a bug.

When building apps for Android using the preinstalled Unity Game Engine using the IL2CPP scripting backend, the editor fails to find the NDK path. prev to #913 this worked without problem.

**Area for Triage**: 

**Question, Bug, or Feature?**: 

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**

NDK path should be found correctly. I'm not sure if it's bc the path was hard coded, or if the spaces in the new installation path break the location resolution by the editor.

**Actual behavior**

Builds fail because NDK path is not found.

**Comment by Darleev** [comment] 2020-06-12 10:25
Hello @StephenHodgson,
 ANDROID_NDK_HOME variable has been changed in scope of [pull request](https://github.com/actions/virtual-environments/pull/913).
The current path is: `"C:\Program Files (x86)\Android\android-sdk\ndk-bundle"`
In order to properly reference this path in pipelines, you can use environment variables:
```
ANDROID_NDK_PATH
ANDROID_NDK_HOME
```
Please note that Visual Studio NDK was not removed and still available in agent machines. You can set variables to the previous values using the following syntax:

Azure DevOps Powershell:
```
$androidNDK = (Get-ChildItem -Path "C:\Microsoft\AndroidNDK64\"| Sort-Object -Property Name -Descending | Select-Object -First 1).FullName
Write-Host "##vso[task.setvariable variable=ANDROID_NDK_HOME;]$androidNDK"
Write-Host "##vso[task.setvariable variable=ANDROID_NDK_PATH;]$androidNDK"
```

GitHub Actions Powershell:
```
$androidNDK = (Get-ChildItem -Path "C:\Microsoft\AndroidNDK64\"| Sort-Object -Property Name -Descending | Select-Object -First 1).FullName
echo '::set-env name=ANDROID_NDK_HOME::$androidNDK'
echo '::set-env name=ANDROID_NDK_PATH::$androidNDK'
```

**Comment by StephenHodgson** [comment] 2020-06-12 14:19
I was never using any of the references in my build pipeline. 

I think the path was actually picked up automatically by the editor itself.

- Maybe they had hard codes the path lookup?
- Maybe they looked for the same environment?
- Maybe it's bc the string is not escaped?

I just know it no longer worked as expected, and I was very confused why my builds suddenly stopped working without any obvious changes on my end.

**Comment by Darleev** [comment] 2020-06-12 14:44
@StephenHodgson Is it possible to provide us public repository where the issue can be reproduced? It most probably helps us to speed up the investigation and get new important details.
Currently, I have no idea what is the problem here, but we'll find right way to fix it.

**Comment by StephenHodgson** [comment] 2020-06-12 15:42
This was the last good build before the VM updated and started breaking
https://github.com/XRTK/XRTK-Core/runs/731930341

**Comment by Darleev** [comment] 2020-06-15 13:20
@StephenHodgson   Previously, Visual Studio NDK was used as default one on Windows images.
Recently, we have switched it to the official one provided by android tool manager in scope of #913.
It was a deliberate change that was done for two reasons:
1) Visual Studio NDK is very outdated and won't be updated in the future. On our images, we would like to provide the latest ndk that will be updated in future
2) We would like to be consistent with other images because Ubuntu and macOS images use official android ndk from android tool manager

Unfortunately, we didn't expect that it could be a breaking change for someone.

Looks like Unity build requires installed Unity Hub. When VisualStudio NDK is used, it consumes Unity part of VS and fails with another NDK.
Thank you for raising the separate issues to pre-install Unity Hub, we will consider it.
Currently, I see two ways to unblock you:
1) Install Unity Hub as a part of your pipeline. For example, using the following syntax:
`choco install unity-hub`
2) Switch back to VS NDK using the script that we have provided above.

If additional information or assistance is required, do not hesitate to contact us.

**Comment by StephenHodgson** [comment] 2020-06-15 23:43
I'm fairly certain the chocolatey installation of Unity Hub only works for windows images, not linux or mac, plus it's maintained by a third party unaffiliated with Unity.

**Comment by Darleev** [comment] 2020-06-16 05:57
@StephenHodgson I believe that chocolatey installation is absolutely safe since you can verify initial scripts before using them for your purposes:
https://chocolatey.org/packages/unity-hub#files

In order to install unity-hub on MacOS you can use the following command:

brew cask install unity-hub

However, in case of the official solution is required, the following link can be useful for you:
https://docs.unity3d.com/2019.1/Documentation/Manual/InstallingUnity.html

So, the installer contains install scripts inside which can be used for pipelines.

**Comment by StephenHodgson** [comment] 2020-06-16 06:03
I already have a solution to install with a powershell script. I'm not requesting that.

I'd like to see the hub preinstalled on the image.

**Comment by Darleev** [comment] 2020-06-16 06:17
@StephenHodgson thanks for clarifying the request. The unity hub installation will be considered in scope of another request https://github.com/actions/virtual-environments/issues/1013 . 
I'm going to close this issue.

In case of any questions, feel free to contact us.

**Closed by Darleev** 2020-06-16 06:17 UTC
Labels: Area: Android, OS: Windows, investigate

**Comment by StephenHodgson** [comment] 2020-06-16 15:22
No worries, thanks for the feedback.
