### ISSUE TITLE
Test run has failed during the build / windows22 image

### ISSUE THREAD

**Issue by jamelia1303** [actions/virtual-environments#4636] opened 2021-11-29 18:55 UTC
### Description

    vhd: Configuration         : PesterConfiguration
    vhd: DiscoveryDuration     : 00:00:12.3776868
    vhd: UserDuration          : 00:02:05.4943363
    vhd: FrameworkDuration     : 00:00:08.0136601
    vhd: Failed                : {[-] 2021-11 Cumulative Update Preview for .NET Framework 3.5 and 4.8 for Microsoft server
    vhd:                         operating system version 21H2 for x64 (KB5007293)}
    vhd: FailedBlocks          : {}
    vhd: FailedContainers      : {}
    vhd: Passed                : {[+] Sdkmanager from SDK tools is available, [+] Sdkmanager from Command-line tools is
    vhd:                         available, [+] Platform version platforms;android-27 is installed, [+] Platform version
    vhd:                         platforms;android-28 is installed...}
    vhd: Skipped               : {[!] BizTalk Registry Check, [!] BizTalk Folder Check, [!] BizTalk Build Targets files Check,
    vhd:                         [!] gitversion is installed...}
    vhd: NotRun                : {}
    vhd: Tests                 : {[+] Sdkmanager from SDK tools is available, [+] Sdkmanager from Command-line tools is
    vhd:                         available, [+] Platform version platforms;android-27 is installed, [+] Platform version
    vhd:                         platforms;android-28 is installed...}
    vhd: CodeCoverage          :
    vhd:
==> vhd: Test run has failed
==> vhd: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\TestsHelpers.ps1:73 char:9
==> vhd: +         throw "Test run has failed"
==> vhd: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> vhd:     + CategoryInfo          : OperationStopped: (Test run has failed:String) [], RuntimeException
==> vhd:     + FullyQualifiedErrorId : Test run has failed
==> vhd:
==> vhd: Provisioning step had errors: Running the cleanup provisioner, if present.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

main branch

### Repro steps

Built  the windows22 image using the main branch

**Comment by al-cheb** [comment] 2021-11-29 19:08
Hey, @jamelia1303 
We will take a look at it.

**Comment by HUMBERP** [comment] 2021-11-30 06:27
Same problem here, seems to be that "2021-11 Cumulative Update Preview for .NET Framework 3.5 and 4.8" will remain in state InProgress.

`    vhd:   [-] 2021-11 Cumulative Update Preview for .NET Framework 3.5 and 4.8 for Microsoft server operating system version 21H2 for x64 (KB5007293) 162ms (160ms|2ms)
    vhd:    Expected collection 'Successful' to contain 'InProgress', but it was not found.
    vhd:    at $Status | Should -BeIn $expect, C:\image\Tests\WindowsFeatures.Tests.ps1:78
    vhd:    at <ScriptBlock>, C:\image\Tests\WindowsFeatures.Tests.ps1:78
`

all other updates are fine.

If you look further the first command to get all updates vom microsoft update the preview KB is not in the list, but the -AcceptAll switch brings additional updates ...

`2021-11-29T17:57:48.8609634Z ==> vhd: Provisioning with Powershell...
2021-11-29T17:57:48.8617924Z ==> vhd: Provisioning with powershell script: C:\a\virtual-environments\images\win/scripts/Installers/Install-WindowsUpdates.ps1
2021-11-29T17:58:24.8952295Z     vhd: Starting wuauserv
2021-11-29T17:58:24.8971212Z     vhd:
2021-11-29T17:58:24.8980392Z     vhd: Status   Name               DisplayName
2021-11-29T17:58:24.8987401Z     vhd: ------   ----               -----------
2021-11-29T17:58:24.8994718Z     vhd: Running  wuauserv           Windows Update
2021-11-29T17:58:24.8999338Z     vhd:
2021-11-29T17:58:24.9004585Z     vhd:
2021-11-29T17:58:24.9013472Z     vhd: Getting list of available windows updates
2021-11-29T17:58:43.0665443Z     vhd:
2021-11-29T17:58:43.0695631Z     vhd: ComputerName Status     KB          Size Title
2021-11-29T17:58:43.0724914Z     vhd: ------------ ------     --          ---- -----
2021-11-29T17:58:43.0731895Z     vhd: pkrvmhe69... -------    KB4052623    7MB Update for Microsoft Defender Antivirus antimalware platform - KB4052623 (V...
2021-11-29T17:58:43.0737612Z     vhd: pkrvmhe69... -------    KB5007293   45MB 2021-11 Cumulative Update Preview for .NET Framework 3.5 and 4.8 for Micros...
2021-11-29T17:58:43.0741247Z     vhd: pkrvmhe69... -------    KB2267602  972MB Security Intelligence Update for Microsoft Defender Antivirus - KB2267602 (...
2021-11-29T17:58:43.0746794Z     vhd: pkrvmhe69... -------    KB5007205   23GB 2021-11 Cumulative Update for Microsoft server operating system version 21H...
2021-11-29T17:58:43.0750540Z     vhd:
2021-11-29T17:58:43.0755778Z     vhd:
2021-11-29T17:58:43.0765246Z     vhd: Installing windows updates
2021-11-29T17:58:47.5512339Z     vhd:
2021-11-29T17:58:47.5523660Z     vhd: X ComputerName Result     KB          Size Title
2021-11-29T17:58:47.5534082Z     vhd: - ------------ ------     --          ---- -----
2021-11-29T17:58:47.5542576Z     vhd: 1 pkrvmhe69... Accepted   KB4052623    7MB Update for Microsoft Defender Antivirus antimalware platform - KB4052623 ...
2021-11-29T17:58:47.5549395Z     vhd: 1 pkrvmhe69... Accepted   KB5007293   45MB 2021-11 Cumulative Update Preview for .NET Framework 3.5 and 4.8 for Micr...
2021-11-29T17:58:47.5557797Z     vhd: 1 pkrvmhe69... Accepted   KB2267602  972MB Security Intelligence Update for Microsoft Defender Antivirus - KB2267602...
2021-11-29T17:58:47.5563104Z     vhd: 1 pkrvmhe69... Accepted   KB5007205   23GB 2021-11 Cumulative Update for Microsoft server operating system version 2...
2021-11-29T17:58:49.0787440Z     vhd: 2 pkrvmhe69... Downloaded KB4052623    7MB Update for Microsoft Defender Antivirus antimalware platform - KB4052623 ...
2021-11-29T17:58:51.5972208Z     vhd: 2 pkrvmhe69... Downloaded KB5007293   45MB 2021-11 Cumulative Update Preview for .NET Framework 3.5 and 4.8 for Micr...
2021-11-29T17:58:53.3499891Z     vhd: 2 pkrvmhe69... Downloaded KB2267602  972MB Security Intelligence Update for Microsoft Defender Antivirus - KB2267602...
2021-11-29T17:59:21.3495261Z     vhd: 2 pkrvmhe69... Downloaded KB5007205   23GB 2021-11 Cumulative Update for Microsoft server operating system version 2...
2021-11-29T17:59:44.0948819Z     vhd: 3 pkrvmhe69... Installed  KB4052623    7MB Update for Microsoft Defender Antivirus antimalware platform - KB4052623 ...
2021-11-29T18:00:06.9593045Z     vhd: 3 pkrvmhe69... Installed  KB5007293   45MB 2021-11 Cumulative Update Preview for .NET Framework 3.5 and 4.8 for Micr...
2021-11-29T18:00:19.2092426Z     vhd: 3 pkrvmhe69... Installed  KB2267602  972MB Security Intelligence Update for Microsoft Defender Antivirus - KB2267602...
2021-11-29T18:01:07.7267784Z     vhd: 3 pkrvmhe69... Installed  KB5007205   23GB 2021-11 Cumulative Update for Microsoft server operating system version 2...
2021-11-29T18:01:07.7278230Z     vhd: Reboot is required, but do it manually.`

**Comment by al-cheb** [comment] 2021-11-30 08:57
@jamelia1303 , @HUMBERP , Could you please build an image using this branch?
```
repo: https://github.com/al-cheb/virtual-environments
branch: win-updates-wait
```

**Comment by HUMBERP** [comment] 2021-11-30 09:30
Currently is running a different image-generation. Hope i can run the test this afternoon.

**Comment by stefanes** [comment] 2021-11-30 11:00
I'm running a build now on this fork/branch (~1h 45 min in), I'll get back to you with the result.

I saw the same error popping up on Windows 2019 yesterday, but it the went away the next build. Maybe this fix should go into both Windows 2022 and 2019?

**Comment by jamelia1303** [comment] 2021-11-30 12:57
> win-updates-wait
@al-cheb 
sure.  thank you!
 I'll post the  results in ~ 4 hours.

**Comment by stefanes** [comment] 2021-11-30 14:01
Still got the error in my latest build:
```
    vhd: Describing Windows Updates
    vhd:   [+] WindowsUpdateDone.txt should exist 5ms (2ms|2ms)
    vhd:   [+] 2021-11 Cumulative Update for .NET Framework 3.5 and 4.8 for Microsoft server operating system version 21H2 for x64 (KB5006364) 45ms (44ms|1ms)
    vhd:   [+] 2021-11 Cumulative Update for .NET Framework 3.5 and 4.8 for Microsoft server operating system version 21H2 for x64 (KB5006364) 3ms (2ms|1ms)
    vhd:   [+] 2021-11 Cumulative Update for Microsoft server operating system version 21H2 for x64-based Systems (KB5007205) 3ms (2ms|1ms)
    vhd:   [-] 2021-11 Cumulative Update Preview for .NET Framework 3.5 and 4.8 for Microsoft server operating system version 21H2 for x64 (KB5007293) 153ms (150ms|3ms)
    vhd:    Expected collection 'Successful' to contain 'InProgress', but it was not found.
    vhd:    at $Status | Should -BeIn $expect, C:\image\Tests\WindowsFeatures.Tests.ps1:78
    vhd:    at <ScriptBlock>, C:\image\Tests\WindowsFeatures.Tests.ps1:78
    vhd:   [+] Security Intelligence Update for Microsoft Defender Antivirus - KB2267602 (Version 1.353.1825.0) 3ms (2ms|1ms)
    vhd:   [+] Update for Microsoft Defender Antivirus antimalware platform - KB4052623 (Version 4.18.2110.6) 2ms (1ms|1ms)
    vhd:   [+] Windows Malicious Software Removal Tool x64 - v5.95 (KB890830) 2ms (1ms|1ms)
```

**Comment by al-cheb** [comment] 2021-11-30 20:05
@stefanes , I was able to reproduce the exact behavior from my side.  I have created https://github.com/actions/virtual-environments/pull/4641 PR.

**Comment by al-cheb** [comment] 2021-12-02 08:04
The [#4641](https://github.com/actions/virtual-environments/pull/4641) PR has been merged. I am going to close the thread. Feel free to open it if you have any concerns.

**Closed by al-cheb** 2021-12-02 08:04 UTC
Labels: OS: Windows, Area: Image administration, investigate

**Comment by jamelia1303** [comment] 2022-04-06 14:52
Hello !
I faced the same issue again building but  that time building 2019 agent.
Can you please take a look ? 
I attached logs. 
thank you ! 
20220330.1
win19/20220330.1
Cloning into 'virtual-environments'...
Branch 'releases/win19/20220330' set up to track remote branch 'releases/win19/20220330' from 'origin'.
Switched to a new branch 'releases/win19/20220330'

 At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\TestsHelpers.ps1:73 char:9
==> vhd: +         throw "Test run has failed"
==> vhd: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> vhd:     + CategoryInfo          : OperationStopped: (Test run has failed:String) [], RuntimeException
==> vhd:     + FullyQualifiedErrorId : Test run has failed
==> vhd:
[logs.txt](https://github.com/actions/virtual-environments/files/8428007/logs.txt)

**Comment by al-cheb** [comment] 2022-04-06 15:25
@jamelia1303, You have to use only `main` branch for an image generation. Looks like temporary network issue.
