### ISSUE TITLE
Ubuntu-18.04 is too intruisive - forcing non compatible libstdc++ by default for c++

### ISSUE THREAD

**Issue by Milerius** [actions/virtual-environments#3432] opened 2021-05-21 09:10 UTC
**Description**  

If you go start a fresh ubuntu 18.04 machine you should have the following:

```
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
```

However on your machine we got:

```
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_3.4.26
GLIBCXX_3.4.27
GLIBCXX_3.4.28
GLIBCXX_3.4.29
```

with `GLIBCXX_3.4.29` -> https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html -> break abi forcing end user that download a app that have been build on github actions to have gcc 11.1.0 installed

due to `strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep "GLIBCXX"`

Please do not force such intruisive behaviour by default, every appimage that build on your VM 18.04 force user to atleast have gcc 11.1.0 or ubuntu hirsute

for infos: https://packages.ubuntu.com/bionic/libstdc++6 -> gcc 8.4.0 not gcc 11.1.0, if user want the last gcc, they should use the last ubuntu image, not the 18.04

**Area for Triage**:  

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [x] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  

`strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep "GLIBCXX"`should return `GLIBCXX_3.4.25 GLIBCXX_3.4.26` Maximum, not GLIBCXX_3.4.29

**Actual behavior**  

A simple appimage build on 18.04 will produce the following behaviour:

```cpp
smk762@pig:~/Downloads/atomicdex-desktop-ubuntu-qt-5-15-2-dc34150.zip/atomicdex-desktop-linux-dc34150/AntaraAtomicDexAppDir/usr/bin$ ./atomicdex-desktop
./atomicdex-desktop: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./atomicdex-desktop)
./atomicdex-desktop: /lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by ./atomicdex-desktop)
```

**Repro steps**  

Build an appimage with last version of clang using libstdc++ will produce the above error

**Comment by Darleev** [comment] 2021-05-21 14:08
Hello @Milerius,
There was [another issue](https://github.com/actions/virtual-environments/issues/3280) in the past, where it was requested to add gcc-11 to out Ubuntu images.
We will check this issue internally and inform you as soon as we make a decision.

**Comment by Milerius** [comment] 2021-05-21 14:41
> Hello @Milerius,
> There was [another issue](https://github.com/actions/virtual-environments/issues/3280) in the past, where it was requested to add gcc-11 to out Ubuntu images.
> We will check this issue internally and inform you as soon as we make a decision.

I understand but 11.1.0 break the ABI, should not replace the default libstdc++ and break existing actions too !

Thanks for the response looking forward

**Comment by miketimofeev** [comment] 2021-05-21 14:50
@Milerius a small question — does GCC 10 also breaks the ABI or it's safe to leave the version 10 on the image?

**Comment by Milerius** [comment] 2021-05-22 05:18
> @Milerius a small question — does GCC 10 also breaks the ABI or it's safe to leave version 10 on the image?

I think the maximum version of 18.04 should be GCC 8.4, and on 20.04 GCC 10 according to official Ubuntu release

**Comment by miketimofeev** [comment] 2021-05-26 09:27
@Milerius could you take a look at this PR https://github.com/actions/virtual-environments/pull/3451? What do you think about such an approach?

**Comment by jesec** [comment] 2021-05-27 03:08
In #3376, a workaround has been suggested: 

```
sudo apt-get autoremove -y libgcc-11-dev gcc-11
```

This deals with the header problem. It works well if you don't distribute built binaries to users. If you do distribute built binaries to users, and you expect the binaries to run Ubuntu 18.04, there is one more step to deal with the lib problem:

```
sudo apt-get install --reinstall libstdc++6=8.4.0-1ubuntu1~18.04
```

You have to manually downgrade the C++ standard library.

Unfortunately, `libstdc++` is so important that you can't remove the experimental PPA, uninstall the package and reinstall it from the Ubuntu archive. The version has to be explicitly specified here, and the downgrade must happen with `reinstall`. To get the version number:

```
$ apt-cache policy libstdc++6
libstdc++6:
  Installed: 8.4.0-1ubuntu1~18.04
  Candidate: 11.1.0-1ubuntu1~18.04.1
  Version table:
     11.1.0-1ubuntu1~18.04.1 500
        500 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu bionic/main amd64 Packages
 *** 8.4.0-1ubuntu1~18.04 500
        500 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages
        100 /var/lib/dpkg/status
     8-20180414-1ubuntu2 500
        500 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages
```

This again demonstrated how ugly the issue is. Feel free to share a way that allows the downgrade to happen without explicit version number.

**Comment by JCash** [comment] 2021-05-28 11:55
Thanks for the info @jesec !
However, after adding these two lines:
```
sudo apt-get autoremove -y libgcc-11-dev gcc-11
sudo apt-get install --allow-downgrades --no-remove --reinstall -y libstdc++6=8.4.0-1ubuntu1~18.04
```
I get the error:
> sudo apt-get install --allow-downgrades --no-remove --reinstall -y libstdc++6=8.4.0-1ubuntu1~18.04
Reading package lists...
Building dependency tree...
Reading state information...
The following packages will be REMOVED:
  g++-10 g++-9 libstdc++-10-dev libstdc++-9-dev
The following packages will be DOWNGRADED:
  libstdc++6
0 upgraded, 0 newly installed, 1 downgraded, 4 to remove and 36 not upgraded.
E: Packages need to be removed but remove is disabled.

It seems related to the "--no-remove" flag, but since you got it working, I'm not sure.
Any ideas what I've missed?

**Comment by jesec** [comment] 2021-05-28 12:12
> Thanks for the info @jesec !
> However, after adding these two lines:
> 
> ```
> sudo apt-get autoremove -y libgcc-11-dev gcc-11
> sudo apt-get install --allow-downgrades --no-remove --reinstall -y libstdc++6=8.4.0-1ubuntu1~18.04
> ```
> 
> I get the error:
> 
> > sudo apt-get install --allow-downgrades --no-remove --reinstall -y libstdc++6=8.4.0-1ubuntu1~18.04
> > Reading package lists...
> > Building dependency tree...
> > Reading state information...
> > The following packages will be REMOVED:
> > g++-10 g++-9 libstdc++-10-dev libstdc++-9-dev
> > The following packages will be DOWNGRADED:
> > libstdc++6
> > 0 upgraded, 0 newly installed, 1 downgraded, 4 to remove and 36 not upgraded.
> > E: Packages need to be removed but remove is disabled.
> 
> It seems related to the "--no-remove" flag, but since you got it working, I'm not sure.
> Any ideas what I've missed?

Oops. It seems that on 18.04 the GCC 10 depends on libs from experimental PPA as well...

You have to remove GCC 10 as well in the previous (`autoremove`) step.

**Comment by AlenaSviridenko** [comment] 2021-06-03 11:59
Hey! Ubuntu images without GCC 11 were fully deployed. 
Please, let us know if the issue still persists, or feel free to close the issue if everything works fine. Thanks.

**Closed** 2021-06-07 09:18 UTC
Labels: Area: Clang, OS: Ubuntu, investigate
