### ISSUE TITLE
NPM Scripts works incorrectly on macos-latest

### ISSUE THREAD

**Issue by neatfx** [actions/virtual-environments#1010] opened 2020-06-05 16:39 UTC
**Describe the bug**
`npm scripts` in `job.step.run` works incorrectly

**Area for Triage**: 
Scripting and command line
Bash

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
`npm run dist` --->  run `cat scripts/args.esbuild.app-builder | xargs esbuild`

**Actual behavior**
got `"cannot execute binary file"` error related to `esbuild` from the runner.
a global installed `esbuild` package with config `run: cat scripts/args.esbuild.app-builder | xargs esbuild` works, but then `"command not found"` error occurred after calling other commands from `node_modules/.bin`.

**Comment by Darleev** [comment] 2020-06-08 11:58
Hello @neatfx,
Thank you for the issue reported. Could you please provide us public repository where the issue can be reproduced?
We are looking forward to your reply.

**Comment by neatfx** [comment] 2020-06-09 07:25
@Darleev 

😄 just solved this issue with:

```
run: |
   export NPM_BIN=node_modules/.bin
   export PATH=$PATH:$NPM_BIN
   npm run dist
```

remove these 2 export lines will reproduce the issue:
https://github.com/neatfx/tiny-evt/blob/master/.github/workflows/build-release.yml

**Comment by neatfx** [comment] 2020-06-11 04:54
@Darleev  I've tested and just like u said, nothing wrong...  😭 , but I did met this tricky problem and  it made me crazy. so, just close this issue now ?

**Comment by Darleev** [comment] 2020-06-11 05:48
@neatfx thank you for the information and the details provided. It seems you faced some intermittent issue which has a specific condition to reproduce.
I'm going to close the issue since the initial problem cannot be reproduced at this time.
In case of any issues/questions, do not hesitate to contact us, we will be glad to assist you

**Closed by Darleev** 2020-06-11 05:48 UTC
Labels: Area: Packages, Area: Scripting and command line, OS: macOS, investigate

**Comment by neatfx** [comment] 2020-06-11 07:05
@Darleev my pleasure, thanks for your work 🤝
