### ISSUE TITLE
Xamarin Android builds fail

### ISSUE THREAD

**Issue by AlexChadwickP** [actions/virtual-environments#4462] opened 2021-11-10 15:46 UTC
### Description

We've got a couple of Xamarin Android applications whose build fails when trying to build it on the windows 2022 image. It works on our development machines without any errors. Our best guess is that the image might be missing some Xamarin component. 

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Version: 20211102.4

### Expected behavior

Xamarin build succeeds

### Actual behavior

Xamarin build fails:

Errors are:

```
Error APT2260: attribute tabGravity not found.
Error APT2260: attribute tabIndicatorColor not found.
```

### Repro steps

1. Push Xamarin application(s) to Azure DevOps repository
2. Run Azure pipeline to build solution

**Comment by al-cheb** [comment] 2021-11-10 15:51
Hey, @AlexChadwickP 
Could you please provide public repo with test app that we can reproduce from our site?

**Comment by mikhailkoliada** [comment] 2021-11-12 08:15
@AlexChadwickP, hello! 
Could you please provide a minimalistic example to reproduce the issue?

**Comment by mikhailkoliada** [comment] 2021-11-15 09:01
@AlexChadwickP it looks like you are missing `Xamarin.Android.Support.Design` import. Do you have the module imported?

**Comment by mikhailkoliada** [comment] 2021-11-17 09:21
@AlexChadwickP  I am going to close this issue now as we have not gotten anything to reproduce the issue. Feel free to ping us if you have questions or repro steps ready.

**Closed by mikhailkoliada** 2021-11-17 09:21 UTC
Labels: Area: Xamarin, OS: Windows, investigate
