### ISSUE TITLE
brew update/brew upgrade failing with Error: Not a directory @ dir_s_rmdir error

### ISSUE THREAD

**Issue by traversaro** [actions/virtual-environments#1811] opened 2020-10-14 12:12 UTC
**Description**  
On some scheduled jobs on macOS, since few days the `brew update` and `brew upgrade` are failing. 

**Area for Triage**:  

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
The commands: 
* `brew update` 
* `brew upgrade` 

Should work fine.

**Actual behavior**  
* `brew update` 
* `brew upgrade` 
commands fail with error:
~~~
==> Summary
🍺  /usr/local/Cellar/node@12/12.19.0_1: 4,304 files, 59.5MB
Removing: /usr/local/Cellar/node@12/12.18.4... (4,296 files, 58.9MB)
Removing: /Users/runner/Library/Caches/Homebrew/node@12--12.18.4.catalina.bottle.tar.gz... (15.8MB)
Error: Not a directory @ dir_s_rmdir - /usr/local/Cellar/openssl
==> Upgrading openssl@1.1 1.1.1h -> 1.1.1h 
Removing: /usr/local/Cellar/openssl/1.0.2t... (1,787 files, 12.4MB)
Error: Process completed with exit code 1.
~~~

**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

1. Run `brew update`
2. Run `brew upgrade`

**Comment by traversaro** [comment] 2020-10-14 12:13
I do not have a mac so I can't try to reproduce this, but I checked online and it seems that it is affecting other CI systems: https://github.com/dotnet/runtime/pull/43299 .

**Comment by traversaro** [comment] 2020-10-14 12:14
Example of failing build: https://github.com/robotology/robotology-superbuild/runs/1248677157 .

**Comment by LeonidLapshin** [comment] 2020-10-14 13:36
Hey, @traversaro !
It seems that openssl (Cellar/openssl/1.0.2t) that is the cause of the error will be removed from macOS images soon, [the link to corresponding PR](https://github.com/actions/virtual-environments/pull/1808) 
for now you can workaround this issue with
```
brew uninstall openssl@1.0.2t
```
command before
```
brew update
brew upgrade
```
I have tried to install your dependencies from https://github.com/robotology/robotology-superbuild/blob/master/.github/workflows/ci.yml and 
```
          brew uninstall openssl@1.0.2t
          brew cask install xquartz
          brew update
          brew upgrade
          brew install ace boost cmake eigen gsl ipopt jpeg libedit opencv pkg-config qt5 sqlite swig tinyxml
          brew install libmatio
          brew tap osrf/simulation
          brew install osrf/simulation/gazebo11
          brew install ninja
```
works correctly.
Could you please check the provided workaround?
Thank you!

**Comment by traversaro** [comment] 2020-10-14 13:54
Thanks!

**Comment by traversaro** [comment] 2020-10-14 15:00
Thanks a lot! I tried the workaround in https://github.com/robotology/robotology-superbuild/pull/493 , but doing that in my CI results in this failure: 
~~~
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: Fetching /usr/local/Homebrew/Library/Taps/local/homebrew-openssl failed!
Fetching /usr/local/Homebrew/Library/Taps/local/homebrew-python2 failed!
fatal: invalid upstream 'origin/master'
fatal: invalid upstream 'origin/master'
~~~

**Comment by LeonidLapshin** [comment] 2020-10-14 15:29
@traversaro , seems that happens because of homebrew version, could you please try to run:
```
brew uninstall openssl@1.0.2t
brew uninstall python@2.7.17
brew untap local/openssl
brew untap local/python2
brew cask install xquartz
brew update
brew upgrade
brew install ace boost cmake eigen gsl ipopt jpeg libedit opencv pkg-config qt5 sqlite swig tinyxml
...
```
it should help.
Thank you!

**Comment by traversaro** [comment] 2020-10-14 16:49
Thanks a lot @LeonidLapshin , your workaround is working fine!

**Comment by ppamorim** [comment] 2020-10-21 16:01
@traversaro This still not fixed and the issue was re-introduced yesterday, any idea when this will be fixed again?

**Comment by rdzman** [comment] 2020-10-21 20:15
Workaround is not working for me. That is, doing
```
brew uninstall openssl@1.0.2t
```
before
```
brew update
```
simply results in
```
Uninstalling /usr/local/Cellar/openssl@1.0.2t/1.0.2t... (1,787 files, 12.4MB)
Warning: The following may be openssl@1.0.2t configuration files and have not been removed!
If desired, remove them manually with `rm -rf`:
  /usr/local/etc/openssl
  /usr/local/etc/openssl@1.1
```

And, whether or not a manually `rm -rf` those directories, it is all followed by the same error I was getting before, namely ...
```
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: Fetching /usr/local/Homebrew/Library/Taps/local/homebrew-openssl failed!
Fetching /usr/local/Homebrew/Library/Taps/local/homebrew-python2 failed!
fatal: invalid upstream 'origin/master'
fatal: invalid upstream 'origin/master'
```

**Comment by al-cheb** [comment] 2020-10-21 20:36
@rdzman,
```
brew untap local/homebrew-openssl
brew untap local/homebrew-python2
brew update 
```

**Comment by rdzman** [comment] 2020-10-21 21:07
Thanks @al-cheb. That worked.

**Comment by bagder** [comment] 2020-10-26 13:49
So there's no fix for this, just the workaround for everyone to do themselves?

**Comment by rdzman** [comment] 2020-10-27 15:50
> So there's no fix for this, just the workaround for everyone to do themselves?

And if that's the case, shouldn't this issue be left open until there is a real fix?

**Comment by maxim-lobanov** [comment] 2020-10-27 16:04
Reopening.
Fix was done in https://github.com/actions/virtual-environments/pull/1889 and will be deployed everywhere in 3-4 days

**Comment by traversaro** [comment] 2020-10-29 08:29
Even with the workaround suggested in this issue, now the `brew upgrade` step is failing with: 
~~~
==> Pouring python@3.9-3.9.0_1.catalina.bottle.tar.gz
Error: The `brew link` step did not complete successfully
Warning: These files were overwritten during `brew link` step:
The formula built, but is not symlinked into /usr/local
Could not symlink lib/pkgconfig/python3-embed.pc
Target /usr/local/lib/pkgconfig/python3-embed.pc
is a symlink belonging to python@3.8. You can unlink it:
  brew unlink python@3.8
~~~

I am not sure if this is related to https://github.com/actions/virtual-environments/issues/1929 .

**Comment by traversaro** [comment] 2020-10-29 08:35
The same error occurs even by removing the workaround mentioned in this issue, so it is probably a different problem, but it is anyhow still related to brew update/brew upgrade failing.

**Comment by traversaro** [comment] 2020-10-29 08:55
For the new problem mentioned in https://github.com/actions/virtual-environments/issues/1811#issuecomment-718475660, adding `brew unlink python@3.8` as suggested by the Homebrew error seems to be effective, see https://github.com/robotology/robotology-superbuild/pull/509#issuecomment-718494055 .

**Comment by rdzman** [comment] 2020-10-29 14:55
@traversaro I believe the new issue you mention (reported in Homebrew/homebrew-core#63619) has also been fixed now, in Homebrew/homebrew-core#63665.

**Comment by miketimofeev** [comment] 2020-10-29 21:33
@traversaro the new image has been deployed and 
```
brew update
brew upgrade
```
works just fine!
I'm going to close the issue, but please feel free to contact us if you have any concerns.
Thank you!

**Closed by miketimofeev** 2020-10-29 21:33 UTC
Labels: Area: Apple, Area: Packages, investigate

**Comment by luigiberrettini** [comment] 2020-11-06 18:11
`brew cleanup` gives the same error

**Comment by nunorafaelrocha** [comment] 2020-11-15 11:26
Just by running 

```sh
brew cleanup
```

I get the following error:
```sh
Run brew cleanup
Error: Not a directory @ dir_s_rmdir - /usr/local/Cellar/openssl
Removing: /usr/local/Cellar/openssl/1.0.2t... (1,787 files, 12.4MB)
Error: Process completed with exit code 1.
```

The action doesn't run anything else... https://github.com/nunorafaelrocha/dotfiles/runs/1402373738?check_suite_focus=true

**Comment by nunorafaelrocha** [comment] 2020-11-15 11:28
@miketimofeev the problem isn't because of brew update or upgrade.

Just by running 

```sh
brew cleanup
```

I get the following error:
```sh
Run brew cleanup
Error: Not a directory @ dir_s_rmdir - /usr/local/Cellar/openssl
Removing: /usr/local/Cellar/openssl/1.0.2t... (1,787 files, 12.4MB)
Error: Process completed with exit code 1.
```

The action doesn't run anything else... https://github.com/nunorafaelrocha/dotfiles/runs/1402373738?check_suite_focus=true

**Comment by miketimofeev** [comment] 2020-11-23 15:17
@nunorafaelrocha Sorry for the late answer — this is also related to the outdated openssl formula, which will be removed in the following month. Could you please create a new issue if it's a severe problem for you and we'll try to find a temporary workaround?

**Comment by nunorafaelrocha** [comment] 2020-11-23 15:38
Hi @miketimofeev 👋

Forgot to post here, I've founded a workaround 😄 

Added a step where I delete openssl 

```yml
      - name: Workarounds
         run: |
           brew uninstall openssl@1.0.2t
           rm -rf /usr/local/etc/openssl
           rm -rf /usr/local/etc/openssl@1.1
```

**Comment by 636f7374** [comment] 2021-01-21 11:18
## Reply

* The above solution is now invalid (not working).
* So after many tests, I finally solved this problem.
* Add it before `brew update`.

## Fixed

```text
    - name: TemporaryFix - Brew Package Management (Github/Action#1811)
      run: |
        brew uninstall --force --ignore-dependencies openssl
        brew cleanup -s openssl
        brew cleanup --prune-prefix
        brew install openssl
        brew link --overwrite openssl
```

**Comment by 636f7374** [comment] 2021-01-21 11:32
## Reply

* The above solution is now invalid (not working).
* So after many tests, I finally solved this problem.
* Add it before `brew update`.

## Fixed

```text
    - name: TemporaryFix - Brew Package Management (Github/Action#1811)
      run: |
        brew uninstall --force --ignore-dependencies openssl
        brew cleanup -s openssl
        brew cleanup --prune-prefix
        brew install openssl
        brew link --overwrite openssl
        brew uninstall --force --ignore-dependencies python
        brew cleanup -s python
        brew cleanup --prune-prefix
        brew install python
        brew link --overwrite python
```

**Comment by 636f7374** [comment] 2021-01-21 13:25
## Solution

* The above methods are now invalid (not working).
* After many tests, this can solve this problem.
* Add this before `brew update`.

### Action

```text
    - name: TemporaryFix - Brew Package Management (Github/Action#1811)
      run: |
        brew uninstall --force --ignore-dependencies openssl
        brew cleanup -s openssl
        brew cleanup --prune-prefix
        brew install openssl
        brew uninstall --force --ignore-dependencies python
        rm $(which 2to3)
        brew cleanup -s python
        brew cleanup --prune-prefix
        brew install python
```

**Comment by Patrick-Chong** [comment] 2021-07-22 11:21
Hi, I am running into the same error when running 'brew update': 

(venv) (base) patrickchong@Patricks-MacBook-Pro microblog % brew update
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: Fetching /opt/homebrew/Library/Taps/company/homebrew-team failed!
fatal: 'origin/master' is not a commit and a branch 'master' cannot be created from it
fatal: invalid upstream 'origin/master'


Any ideas how to fix this? I tried some of the above but it doesn't help!

**Comment by rchawathearkin** [comment] 2021-08-13 15:09
Same here. Even after following instructions from https://github.com/actions/virtual-environments/issues/1811#issuecomment-764640553 
Facing issue as follows
```
~ $brew update
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: Fetching /usr/local/Homebrew/Library/Taps/rchawathe/homebrew-local-tap failed!
fatal: 'origin/master' is not a commit and a branch 'master' cannot be created from it
fatal: invalid upstream 'origin/master'
```

**Comment by DhairyeKataria** [comment] 2022-01-15 17:45
> Same here. Even after following instructions from [#1811 (comment)](https://github.com/actions/virtual-environments/issues/1811#issuecomment-764640553) Facing issue as follows
> 
> ```
> ~ $brew update
> fatal: 'origin' does not appear to be a git repository
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> fatal: 'origin' does not appear to be a git repository
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> Error: Fetching /usr/local/Homebrew/Library/Taps/rchawathe/homebrew-local-tap failed!
> fatal: 'origin/master' is not a commit and a branch 'master' cannot be created from it
> fatal: invalid upstream 'origin/master'
> ```

Please Help If you've found the solution!!

Mine gives this output:

brew update
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core failed!
