### ISSUE TITLE
vcpkg install ace:x64-windows fails on windows-latest since 2020-03-23 due to Visual Studio 2019 16.5

### ISSUE THREAD

**Issue by traversaro** [actions/virtual-environments#605] opened 2020-03-23 14:31 UTC
**Describe the bug**
Since a few hours, the command `vcpkg install ace:x64-windows` is failing to complete correctly

**Area for Triage**: 

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**
The ace:x64-windows port should be installed correctly.

**Actual behavior**
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

Run: 
~~~
vcpkg install ace:x64-windows
~~~

See https://github.com/traversaro/reproduce-ace-vcpkg-github-actions-fails for a minimal reproducible example. 
Interestingly, this was working fine as of 12 hours ago, and is working fine if vcpkg is used on our local laptops. Furthermore, the failure is present even on old vcpkg tags.

**Comment by al-cheb** [comment] 2020-03-23 18:17
Hello, @traversaro 
Today we updated Windows Server 2019 with latest version of Visual Studio 16.5.0+29911.84.  Looks like something is incompatible with the VS 2019.

Maybe ugly workaround will help:

```
- name: vcpkg
      run: |
        Remove-Item -Path "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.25.28610" -Force -Recurse
        vcpkg install ace:x64-windows
```

**Comment by traversaro** [comment] 2020-03-23 21:18
Thanks a lot @al-cheb . I tried your workaround, but it seems that removing that directory prevents us to compile vcpkg at all: https://github.com/iit-danieli-joint-lab/idjl-software-dependencies-vcpkg/runs/528765035?check_suite_focus=true .

**Comment by traversaro** [comment] 2020-03-23 22:09
> 
> 
> Thanks a lot @al-cheb . I tried your workaround, but it seems that removing that directory prevents us to compile vcpkg at all: https://github.com/iit-danieli-joint-lab/idjl-software-dependencies-vcpkg/runs/528765035?check_suite_focus=true .

Actually first boostrapping vcpkg, and then deleting that directory seems to work fine (even if I am not sure why), thanks!

**Comment by traversaro** [comment] 2020-03-23 22:37
Interestingly the workaround does not work on a custom vcpkg, and it fails with (see https://github.com/iit-danieli-joint-lab/idjl-software-dependencies-vcpkg/runs/528902446):
~~~
Remove-Item : Cannot remove item C:\Program Files (x86)\Microsoft Visual 
Studio\2019\Enterprise\VC\Tools\MSVC\14.25.28610\bin\Hostx64\x86\mspdbcore.dll: Access to the path 'mspdbcore.dll' is 
denied.
At D:\a\_temp\523feeaa-870a-450f-aae8-ed41f1806374.ps1:3 char:1
+ Remove-Item -Path "${env:ProgramFiles(x86)}\Microsoft Visual Studio\2 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (mspdbcore.dll:FileInfo) [Remove-Item], UnauthorizedAccessException
    + FullyQualifiedErrorId : RemoveFileSystemItemUnAuthorizedAccess,Microsoft.PowerShell.Commands.RemoveItemCommand
##[error]Process completed with exit code 1.
~~~

**Comment by josejavieralvarez** [comment] 2020-03-24 13:48
I'm trying to get a build compiled on https://dev.azure.com/ using a .yml file. The problem I've got is that I need it to run with VS2019 version 16.5, because I'm using a library which won't compile with a previous one. I'm able to compile it from VS2019 16.5 locally, but when compiling on Azure the problem occurs because it is not using 16.5 version of vs2019.
We are using Microsoft-hosted agent windows2019 (https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml).
Is there a way to check what version of vs2019 is being used?
We are setting it as follows:
```
pool:
    vmImage: 'windows-2019'

  variables:
    buildConfiguration: 'Release'
    outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'
    testsOutputDirectory: '$(build.binariesDirectory)/Tests'
    buildPlatform: 'x64'
    vsVersion: '16.0'
```

**Comment by miketimofeev** [comment] 2020-03-25 14:02
@josejavieralvarez VS 16.5 rolling out process isn't finished yet, should be done in 2 days

**Comment by miketimofeev** [comment] 2020-03-30 08:47
@josejavieralvarez VS16.5 rollout has been finished

**Comment by miketimofeev** [comment] 2020-04-27 08:25
The very latest visual studio still has the same issue, waiting for release with the fix.

**Comment by maxim-lobanov** [comment] 2020-05-06 13:16
It is mentioned that the issue will be resolved in Visual Studio 16.6. Currently, it is in preview. Not sure about release date

**Comment by maxim-lobanov** [comment] 2020-05-13 08:11
I am closing this issue because actually, bug is related to Visual Studio. Not the images itself so I don't see any actions items from our side.
As I mentioned previously, fix should be available in Visual Studio 16.6 that will be released soon. We will deliver this update as soon as it is available. You can track new updates in our image documentation.

**Closed by maxim-lobanov** 2020-05-13 08:11 UTC
Labels: Area: C/C++, OS: Windows, awaiting-deployment, bug

**Comment by miketimofeev** [comment] 2020-05-25 18:30
@traversaro VS 16.6 was released and the issue is fixed there. We've started the Image Deployment today and it will take a few days to propagate to all the environments.

**Comment by traversaro** [comment] 2020-05-28 06:45
Thanks @miketimofeev . For the enviroments that still use VS 16.5, the issue has been solved in the master vcpkg branch thanks to https://github.com/microsoft/vcpkg/pull/11369 , so updating to a recent vcpkg commit (as done in https://github.com/traversaro/reproduce-ace-vcpkg-github-actions-fails/pull/2) solves the issue as well.
