### ISSUE TITLE
Add support for creating Arm64 Linux images

### ISSUE THREAD

**Issue by rickardp** [actions/virtual-environments#2552] opened 2021-01-25 22:26 UTC
Both Azure DevOps and GitHub Actions mention supporting Arm64 but only for self-hosted images. Not supporting them here means one would have to start over with a fresh image, which is a lot of work.

Being able to create an Arm64 image and deploy to scale set agents (at least on DevOps, unsure if GH supports it) at least makes the maintenance manageable.

**Comment by AlenaSviridenko** [comment] 2021-01-26 09:56
Hi @rickardp, 
just to clarify, do you mean creating an image template with provisioners for installing software that can be used for setting up self-hosted runners with Linux Arm64?

**Comment by AlenaSviridenko** [comment] 2021-02-02 08:57
Hi!
After some discussions we have to decline this feature request, because we cannot provide templates for images that we cannot test on our side, since Azure doesn't support Arm64 yet. Not providing a template at all is better than provide a broken template, especially given the growing popularity of Arm64 architecture.

Hopefully, this approach will be changes in the future as we see the increasing demand on Arm64. 
I am closing this issue. Please, feel free to create a new one in case of any other questions. Thanks.

**Closed by AlenaSviridenko** 2021-02-02 08:57 UTC
Labels: needs eyes

**Comment by rickardp** [comment] 2021-02-02 18:23
I see your point. My use case is useless without any way to run the agent anyway, so this request was about getting a complete solution, including a place to run my images. I'm sure there is a use case for running build agents on Arm Mac mini's etc, but mine was about cloud hosted arm64 images.

I hope you guys reconsider this eventually as Arm will be an important use case.

**Comment by ArniDagur** [comment] 2021-02-03 10:25
> Azure doesn't support Arm64 yet

Would it be possible to use [multiarch/qemu-user-static](https://github.com/multiarch/qemu-user-static) as dakale suggests in https://github.community/t/testing-against-multiple-architectures/17111/7?

**Comment by catthehacker** [comment] 2021-02-03 10:30
@ArniDagur you definitely can or you can use official Docker actions for setting up `qemu`/`buildx` and building Dockerfiles
https://github.com/marketplace/actions/docker-setup-qemu
https://github.com/marketplace/actions/docker-setup-buildx
https://github.com/marketplace/actions/build-and-push-docker-images

**Comment by christian-kreuzberger-dtx** [comment] 2021-02-03 11:03
For what it is worth, I tried that, and it's super slow... Build takes 5 times as long

**Comment by olehermanse** [comment] 2021-06-29 19:27
> Hi!
> After some discussions we have to decline this feature request, because we cannot provide templates for images that we cannot test on our side, since Azure doesn't support Arm64 yet. Not providing a template at all is better than provide a broken template, especially given the growing popularity of Arm64 architecture.
> 
> Hopefully, this approach will be changes in the future as we see the increasing demand on Arm64.
> I am closing this issue. Please, feel free to create a new one in case of any other questions. Thanks.

@AlenaSviridenko Any update on this?

https://azure.microsoft.com/en-us/updates/azure-devops-pipelines-introduces-support-for-linuxarm64/

**Comment by AlenaSviridenko** [comment] 2021-06-29 19:37
Correct, that is about support of arm64 for self-hosted machines, we have to wait for arm64 in Azure.

**Comment by l1ving** [comment] 2021-11-07 18:45
This appears to now be supported by Azure, could someone take a look at this issue again?

https://azure.microsoft.com/en-us/updates/azure-devops-pipelines-introduces-support-for-linuxarm64/

**Comment by martin-g** [comment] 2021-11-07 19:21
@l1ving See few comments above ^^

**Comment by l1ving** [comment] 2021-11-07 19:28
That's why I'm making a comment, it looks like it's supported on non-self hosted runners as well?

**Comment by l1ving** [comment] 2021-11-07 19:28
Oh. I pasted the wrong link

**Comment by ericdallo** [comment] 2022-04-04 17:22
Should we re-open this issue since now it should be possible to use arm64 with GH ?

**Comment by jerrychong25** [comment] 2022-04-26 09:44
> Azure introduces ARM64 https://azure.microsoft.com/en-us/blog/now-in-preview-azure-virtual-machines-with-ampere-altra-armbased-processors/

Thanks @panekj for sharing!

@ericdallo Yeah we need ARM64 Linux images so that can build in GitHub Actions soon! This will be very useful for developers.

**Comment by jkroepke** [comment] 2022-05-06 14:37
@jerrychong25 ARM64 Docker Images can be build on AMD64 runners. See https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md

**Comment by ruudk** [comment] 2022-05-06 16:45
> @jerrychong25 ARM64 Docker Images can be build on AMD64 runners. See https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md

Sure but it's super slow when building large images.

**Comment by jerrychong25** [comment] 2022-05-07 16:02
> > @jerrychong25 ARM64 Docker Images can be build on AMD64 runners. See https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md
> 
> Sure but it's super slow when building large images.

Yes, hope that there is new ARM64 Linux images that can run normal speed like currently working Github Actions Linux images.

**Comment by pentamassiv** [comment] 2022-06-11 23:54
I saw that a similar ticket was closed because it was a duplicate of this issue. Could this one then be reopened or will Linux on ARM64 not happen?

**Comment by erwan-joly** [comment] 2022-08-13 10:17
@AlenaSviridenko can this issue be reopened please as it now see to be doable (azure support arm images)?

**Comment by pentamassiv** [comment] 2022-09-14 15:29
I guess this is now tracked in https://github.com/actions/runner-images/issues/5631
