### ISSUE TITLE
themaximumspension@gmail.com

### ISSUE THREAD

**Issue by themaximumspension** [actions/virtual-environments#2377] opened 2021-01-01 10:15 UTC
Indeed, creating a `$HOME/.my.cnf` file before running any `mysql` commands works:

```yaml
run: |
  sudo systemctl start mysql
  echo -e '[client]\nuser="root"\npassword="root"' > "$HOME/.my.cnf"
  mysql -e "CREATE DATABASE IF NOT EXISTS october;"
```

I'll leave this issue open to see if we should have a `$HOME/.my.cnf` file created by default.

_Originally posted by @Calinou in https://github.com/actions/virtual-environments/issues/2372#issuecomment-752288208_

**Comment by maxim-lobanov** [comment] 2021-01-03 08:11
Closing as duplicate of https://github.com/actions/virtual-environments/issues/2372

**Closed by maxim-lobanov** 2021-01-03 08:11 UTC
Labels: needs triage
