### ISSUE TITLE
windows-2022 seems to be defaulting to a very old version of Nuget

### ISSUE THREAD

**Issue by tidusjar** [actions/virtual-environments#5303] opened 2022-03-30 08:05 UTC
### Description

When using `windows-2022` as a hosted build agent on Azure Devops, we can no longer restore our .net packages using nuget.

The reason for this is that it seems that the default installed nuget version is `4.1.0`

This issue has only happened in the past day, we use `windows-latest` and it seems in the same timeframe we have switched over to using `windows-2022` instead of `windows-2019` (which is expected).

The fix for this seems to be to run a `NuGetToolInstaller` task, the thing is that even if we do not specify a version in the task, it then correctly picks up nuget `6.1.0`, without this task it's finding `4.1.0` in the cache.

```
 - task: NuGetToolInstaller@1
   displayName: Use NuGet
```

Logs: 

```
Starting: Restore Packages
==============================================================================
Task         : NuGet
Description  : Restore, pack, or push NuGet packages, or run a NuGet command. Supports NuGet.org and authenticated feeds like Azure Artifacts and MyGet. Uses NuGet.exe and works with .NET Framework apps. For .NET Core and .NET Standard apps, use the .NET Core task.
Version      : 2.198.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/package/nuget
==============================================================================
Caching tool: NuGet 4.1.0 x64
Found tool in cache: NuGet 4.1.0 x64
Resolved from tool cache: 4.1.0
Using version: 4.1.0
Found tool in cache: NuGet 4.1.0 x64
SYSTEMVSSCONNECTION exists true
SYSTEMVSSCONNECTION exists true
C:\Windows\system32\chcp.com 65001
Active code page: 65001
Detected NuGet version 4.1.0.2450 / 4.1.0
SYSTEMVSSCONNECTION exists true
C:\hostedtoolcache\windows\NuGet\4.1.0\x64\nuget.exe restore D:\a\1\s\X.sln -PackagesDirectory D:\a\1\s\packages -Verbosity Detailed -NonInteractive -ConfigFile D:\a\1\Nuget\tempNuGet_219920.config
NuGet Version: 4.1.0.2450
```

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20220316.1

### Is it regression?

Unknown, we use `windows-latest`. Previously we were on `windows-2019`

### Expected behavior

Use a later version of nuget. 2019 was running nuget `5.8.0`

### Actual behavior

It's finding nuget `4.1.0` in the cache by default and using that.

### Repro steps

Run nuget restore

**Comment by miketimofeev** [comment] 2022-03-30 08:51
Hi @tidusjar! This is a duplicate of https://github.com/actions/virtual-environments/issues/5238
Both Windows Server 2019 and 2022 contains NuGet 6.1.0.106. ([2019 docs](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#package-management), [2022 docs](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md#package-management)).
All NuGet* related tasks in ADO bring their own version of NuGet that doesn't depend on the image somehow. Please log an issue in the https://github.com/microsoft/azure-pipelines-tasks repository if you see any issues with this task and the NuGet version

**Closed by miketimofeev** 2022-03-30 08:51 UTC
Labels: Area: JavaScript and Node.js, OS: Windows, investigate, bug report
