### ISSUE TITLE
Ubuntu-18.04 20210510 broke Clang 3.9 and 9

### ISSUE THREAD

**Issue by sfan5** [actions/virtual-environments#3376] opened 2021-05-13 13:49 UTC
**Description**  
Since image version `20210510` both clang-3.9 and clang-9 are broken, specifically compilation errors in the C++ stdlib and binaries that segfault.
With no changes to code or CI `20210504.1` does _not_ exhibit this issue, hence this must be a bug in this repo.

**Area for Triage**:  
C/C++

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [x] Ubuntu 18.04

**Image version**
  Version: 20210510.0

**Expected behavior**  
Clang 3.9 and 9 compile C++ code without erroring and/or the resulting binaries segfaulting.
This is the case on `20210504.1` (https://github.com/minetest/minetest/runs/2535472812).

**Actual behavior**  
* Clang 3.9 throws the following warning on every C++ source file: (https://github.com/minetest/minetest/pull/11263/checks?check_run_id=2575483229)
<pre>
[...]
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/cstdint:38:
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/x86_64-linux-gnu/c++/11/bits/c++config.h:558:2: warning: "__STRICT_ANSI__ seems to have been undefined; this is not supported" [-W#warnings]
#warning "__STRICT_ANSI__ seems to have been undefined; this is not supported"
 ^
1 warning generated.
</pre>
...also leading to errors in some cases:
<pre>
In file included from /home/runner/work/minetest/minetest/src/serverenvironment.cpp:20:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/algorithm:61:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_algobase.h:63:
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/ext/numeric_traits.h:64:7: error: static_assert failed "invalid specialization"
      static_assert(__is_integer_nonstrict<_Value>::__value,
      ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/uniform_int_dist.h:251:19: note: in instantiation of template class '__gnu_cxx::__numeric_traits_integer<unsigned __int128>' requested here
          static_assert(!_Wp_traits::__is_signed, "W must be unsigned");
                         ^admittedly 
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/uniform_int_dist.h:307:11: note: in instantiation of function template specialization 'std::uniform_int_distribution<unsigned long>::_S_nd<unsigned __int128, std::mersenne_twister_engine<unsigned long, 32, 624, 397, 31, 2567483615, 11, 4294967295, 7, 2636928640, 15, 4022730752, 18, 1812433253>, unsigned long>' requested here
                __ret = _S_nd<unsigned __int128>(__urng, __u64erange);
                        ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_algo.h:3791:32: note: in instantiation of function template specialization 'std::uniform_int_distribution<unsigned long>::operator()<std::mersenne_twister_engine<unsigned long, 32, 624, 397, 31, 2567483615, 11, 4294967295, 7, 2636928640, 15, 4022730752, 18, 1812433253> >' requested here
        std::iter_swap(__i, __first + __d(__g, __p_type(0, __i - __first)));
                                      ^
/home/runner/work/minetest/minetest/src/serverenvironment.cpp:1438:8: note: in instantiation of function template specialization 'std::shuffle<__gnu_cxx::__normal_iterator<irr::core::vector3d<short> *, std::vector<irr::core::vector3d<short>, std::allocator<irr::core::vector3d<short> > > >, std::mersenne_twister_engine<unsigned long, 32, 624, 397, 31, 2567483615, 11, 4294967295, 7, 2636928640, 15, 4022730752, 18, 1812433253> &>' requested here
                std::shuffle(output.begin(), output.end(), m_rgen);
                     ^
</pre>

* Clang 9 built binaries segfault for no good reason: https://github.com/minetest/minetest/pull/11263/checks?check_run_id=2575482918
  (admittedly I have not narrowed this down but neither the code nor our CI changed so I'm sure this is related)

**Repro steps**  
~~Here's the relevant parts of our CI:
https://github.com/minetest/minetest/blob/master/.github/workflows/build.yml#L75-L120
https://github.com/minetest/minetest/blob/master/util/ci/common.sh
https://github.com/minetest/minetest/blob/master/util/ci/build.sh~~

(see third post)

**Comment by al-cheb** [comment] 2021-05-13 14:40
Hi, @sfan5 
I can't reproduce with minimal repro.
```
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
         - name: Build
           run: |
            sudo apt-get update
            sudo apt-get install -y --no-install-recommends clang-3.9
         - run: |
            echo '#include <string>' > lib.hpp
            echo 'std::string hello();' >> lib.hpp
            echo '#include "lib.hpp"' > lib.cpp
            echo 'std::string hello() { return "hello world\n"; }' >> lib.cpp
            echo '#include <iostream>' > test.cpp
            echo '#include "lib.hpp"' >> test.cpp
            echo 'int main(void) { std::cout << hello();return 0; }' >> test.cpp
            clang++-3.9 -g -O0 -Wall -std=c++11 -o test test.cpp lib.cpp
            ./test
```
![image](https://user-images.githubusercontent.com/47745270/118141558-277f5780-b412-11eb-9961-64da109e9c98.png)

**Comment by sfan5** [comment] 2021-05-13 15:20
Hm, seems to depend on some specifics. Here's a working reproducer: https://github.com/sfan5/temp/actions/runs/839309961

https://github.com/sfan5/temp/blob/master/.github/workflows/build.yml
https://github.com/sfan5/temp/blob/master/test.cpp

**Comment by miketimofeev** [comment] 2021-05-13 15:36
@sfan5 I wonder why there version 11 in the logs:
In file included from /home/runner/work/minetest/minetest/src/serverenvironment.cpp:20:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/**11**/../../../../include/c++/11/algorithm:61:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/**11**/../../../../include/c++/11/bits/stl_algobase.h:63:

My assumption that it's started to be the default one once we've added it.

**Comment by al-cheb** [comment] 2021-05-13 16:07
@sfan5,
Confirm. Removing gcc-11, fix the issue:
`sudo apt remove libgcc-11-dev gcc-11`

**Comment by SadieCat** [comment] 2021-05-14 00:57
We're experiencing this too with Clang 10 (the default clang++) in the Ubuntu 20.04 image. [This](https://github.com/inspircd/inspircd/actions/runs/830774014) run passed previously on Clang but [this](https://github.com/SadieCat/inspircd/actions/runs/839773740) run of the same commit in my personal fork fails on Clang. [The fix mentioned by @sfan5 fixes this problem.](https://github.com/SadieCat/inspircd/actions/runs/840660661)

**Comment by jefgen** [comment] 2021-05-14 23:16
FWIW, the update to the Ubuntu image from version `20210504.1` to `20210510.0` seems to be impacting our builds as well.

We were trying to figure out what local changes might have caused this, as the CI builds were [passing](https://dev.azure.com/ms/icu/_build/results?buildId=164526&view=logs&jobId=f67069c5-d6ce-5849-b704-afed4541a096), but now our test code [segfaults](https://dev.azure.com/ms/icu/_build/results?buildId=166374&view=logs&jobId=38fdaa76-0e8a-5df8-7931-bd250fe978b2). We've tried [reverting](https://github.com/unicode-org/icu/pull/1719) recent local changes, but that didn't make any difference.

Using the [work-around](https://github.com/jefgen/icu/commit/e5c042b3c5627a7b03dcca2ef98e59573e8b6e10) to remove gcc-11 on the updated Ubuntu 18.04 version `20210510.0` image [works](https://dev.azure.com/ms/icu/_build/results?buildId=166683&view=logs&j=38fdaa76-0e8a-5df8-7931-bd250fe978b2&t=38fdaa76-0e8a-5df8-7931-bd250fe978b2) though.

**Comment by matthuisman** [comment] 2021-05-15 08:22
@miketimofeev
Will this be fixed in the image? Or should we use the remove gcc 11 workaround?

**Comment by miketimofeev** [comment] 2021-05-17 09:54
@matthuisman we're working on finding possible solutions. As a workaround, please stick to removing the GCC.

**Comment by nikita-bykov** [comment] 2021-05-20 14:24
Hello @sfan5! 
We install multiple Clang versions side-by-side on our images and unfortunately sometimes it can case unforeseen compatibility conflicts. As a possible solution you can add `-stdlib=libc++` to your Clang command.
Based on your repro steps it will look like this:
`clang++-3.9 -g -O0 -Wall -std=gnu++11 -stdlib=libc++ test.cpp -o test -pthread`

**Comment by jesec** [comment] 2021-05-22 16:22
I can confirm this issue. I don't think it is a good idea to add experimental toolchain to the image, as the addition/modification of standard C/C++ headers and libraries can have wide-ranging (and often undesired) consequences across the whole system.

Filed a revert of #3291: https://github.com/actions/virtual-environments/pull/3436

**Comment by nikita-bykov** [comment] 2021-05-24 10:04
Hello @jesec. Could you please clarify why you think GCC 11 is an unstable version? GCC 11 was officially released on April 27th: https://gcc.gnu.org/gcc-11/.
Based on our [software and images support policy](https://github.com/actions/virtual-environments/blob/main/docs/software-and-images-guidelines.md#software-and-images-support-policy), we install 3 latest major versions of GCC on images.

**Comment by jesec** [comment] 2021-05-24 10:32
> Hello @jesec. Could you please clarify why you think GCC 11 is an unstable version? GCC 11 was officially released on April 27th: https://gcc.gnu.org/gcc-11/.
> Based on our [software and images support policy](https://github.com/actions/virtual-environments/blob/main/docs/software-and-images-guidelines.md#software-and-images-support-policy), we install 3 latest major versions of GCC on images.

GCC is not only a compiler. It is the entire set of toolchain. libstdc++ (C++ standard library that accompanies GCC) and glibc (GNU C standard library) are critical to almost all Linux systems. The whole operating system is built around them. To make it easier to understand, it is a `peerDependency` to everything, incl. the OS. 

In general, things only work when they are on the same page. GCC should not be treated as a "regular" software that can be upgraded freely. It may be marked as `stable` by the upstream, but it is not yet marked as `stable` by operating system (in this case, Ubuntu). As far as I can see, clearly the script added an PPA and pulled the experimental toolchain from there.

And, here we are. We are already having troubles, and I believe that's more than sufficient proof that the toolchain is not ready for production.

**Comment by reynoldsbd** [comment] 2021-05-24 19:20
My expectation when building on the Ubuntu 18.04 pool is that the build environment is roughly representative of a stock Ubuntu 18.04 installation, which is what many of the developers on my team use for local development.

As @jesec points out, although GCC 11 is a perfectly stable and usable release, it does not match the stock Ubuntu 18.04 OS. As a result, my team is observing a number of issues during CI builds that do not repro in their local environments:

* Build failures due to minor header differences in the new GCC 11 standard library
* Runtime failures as described above
* Runtime failures when trying to run CI-built binaries on their local workstation, due to the CI binaries depending on a newer version of libstdc++ than what is available locally

@nikita-bykov I think it's perfectly reasonable to make GCC 11 _available_ on Ubuntu 18.04 images. But can it be installed in such a way that it isn't the _default_?

**Comment by MehdiChinoune** [comment] 2021-05-26 21:43
I wonder how someone using gcc-9 which installed from a ppa  is complaining about gcc-11 because it is installed from the same one.

Use gcc-7 if you want to use the official packages then.

**Comment by nikita-bykov** [comment] 2021-05-28 11:23
We decided to remove GCC 11 and GFortran 11 from Ubuntu 18.04 and Ubuntu 20.04 images. You can find more details in the related [announcement](https://github.com/actions/virtual-environments/issues/3467#).

**Comment by nikita-bykov** [comment] 2021-06-03 10:25
GCC 11 and Gfortran 11 were removed from Ubuntu images.
I'm going to close the issue. Please feel free to contact us if you have any concerns.

**Closed by nikita-bykov** 2021-06-03 10:25 UTC
Labels: Area: Clang, OS: Ubuntu, investigate
