### ISSUE TITLE
Cannot run docker-compose on ubuntu-latest

### ISSUE THREAD

**Issue by Woofenator** [actions/virtual-environments#765] opened 2020-04-22 09:25 UTC
**Describe the bug**
Attempting to run docker-compose results in error `Couldn't connect to Docker daemon at http+docker://localhost - is it running?`. Seems like docker service doesn't get spun up with the environment

**Area for Triage**: 
Deployment/Release

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
For docker-compose to run

**Actual behavior**
Docker compose fails with error `Couldn't connect to Docker daemon at http+docker://localhost - is it running?`

**Comment by Darleev** [comment] 2020-04-22 10:08
Hello @Woofenator, I have double checked the issue with Ubuntu image and docker-compose file, and it seems that the issue is intermittent. I tried the following:
1. Create docker-compose task with empty docker-compose file - everything works fine here.
2. Create bash script and try to start command docker-compose up - everything is fine as well.

Could you please try to reproduce the issue? Is it still actual?

**Comment by Woofenator** [comment] 2020-04-22 10:13
Ok. I tinkered with the job a little bit more. Seems like setting an env variable (in my case `TAG`) is what broke it

**Comment by Darleev** [comment] 2020-04-22 11:00
@Woofenator thank you for the details. Did you try to remove TAG variable? Does it help? I tried to find any information about TAG variable and how it can break docker, but had no luck. I guess, docker fails on another step. Could you please provide us with public repository which contains minimal reproducing steps for the issue reported?

**Comment by Woofenator** [comment] 2020-04-22 12:17
@Darleev Hi! I cannot seem to reproduce the issue in a public repository :(

**Comment by Darleev** [comment] 2020-04-22 12:58
@Woofenator Could you please also clarify about variable? Did you try to remove it? Does it help?

**Comment by Woofenator** [comment] 2020-04-22 13:18
@Darleev Removing the TAG env variable did indeed fix it. Adding it in the clean project doesn't seem to have any effect

**Comment by al-cheb** [comment] 2020-04-22 14:27
@Woofenator, Could you please set TAG as?
```
 env:
        TAG: "dev-${{ github.sha }}"
```

**Comment by Woofenator** [comment] 2020-04-28 08:24
Little bit of progress: No matter how I set the environment variables, the issue persists on my private repo and I cannot reproduce it on the public repo. I did try to check if docker is running, and, lo and behold, it is: 
![image](https://user-images.githubusercontent.com/7696606/80464646-c7229280-8942-11ea-873d-66c4ef91cdff.png)

It's just docker-compose that cannot see the docker daemon on the socket for some reason.

**Comment by Woofenator** [comment] 2020-04-28 08:53
Another thing: I have two workflows with exactly the same definitions. The only differences are the `on` setting (on `branches.staging` & on `branches.workflow_1.0.0`) and their names. The one on the staging branch works just fine, the one on the workflow branch doesn't

**Comment by Darleev** [comment] 2020-04-29 17:27
@Woofenator thank you for provided details. What is the difference between two branches except their names? Could you please provide more information about it? 
Could you please try to add additional command to your pipeline, to retrieve docker daemon log:

`journalctl -u docker.service`

and provide us with a result.

**Comment by johndatserakis** [comment] 2020-05-01 04:24
Hey there - I had the same issue. 

I was working on my workflow on a private repo and at one point I actually got the docker-compose build working (that's how I knew it had worked at some point). The thing was, after a bit, I had started using certain variables in the `docker-compose` file, and that is what brought on the issue.

What's interesting is that my own secrets are fine to use in my `docker-compose` file, but when I tried to use `REPOSITORY_NAME: ${{ github.event.repository.name }}` as an `env:` value to pass and use in the name of my repo for the docker-compose actions, that's when I got the `Couldn't connect to Docker daemon at http+docker://localhost - is it running?`

Removing that usage made the issue go away. Perhaps the string is not being interpreted correctly on the docker side. It's just weird because I've used this pattern before and it's been fine, and also how my variables work fine - you would expect them all to pass or fail I guess.

Anyways, hope it helps.

**Comment by al-cheb** [comment] 2020-05-01 08:03
Hello, @johndatserakis 

Could you please compare behavior with export and env:?

```
    - name: docker
      run: |
        export REPOSITORY_NAME=${{ github.event.repository.name }}
        echo $REPOSITORY_NAME
        docker-compose .....
```

vs

```
    - name: docker
      run: |
        echo $REPOSITORY_NAME
         docker-compose .....
      env: 
        REPOSITORY_NAME: ${{ github.event.repository.name }}
```

**Comment by johndatserakis** [comment] 2020-05-02 01:19
Sure, I already moved passed this but I reverted to try out your tests. I used a secret instead of `github.event.repository.name` as I am no longer using that.

First example worked, second example didn't work, third example didn't work.

The docker error definitely seems tied to an error in the build, it's just that the error message isn't that good. But I think it's more of a docker thing, as my googling showed that others have this issue outside of this space.

Thank you

**Comment by Darleev** [comment] 2020-05-18 05:10
@johndatserakis @Woofenator I was not able to reproduce the issue on my test repositories. I tried to pass parameter follows your examples, but I didn't face the same issue.
Is it possible to provide public repository with steps to reproduce the issue? It will help to find a root cause and speed up the investigation.

**Comment by johndatserakis** [comment] 2020-05-21 23:45
@Darleev thank you for looking into it. For me, I've moved these variables to secrets, and they are working for me now, as they are attached to the `env:` property. So sorry but I am not able to reproduce this situation in my current setup. I will update if things change though. Thanks again.

**Comment by Darleev** [comment] 2020-05-22 08:32
@johndatserakis @Woofenator  thank you for the update. It seems the issue cannot by reproduced at this time. In order to continue the investigation following information is required:
- Step by step instruction how to reproduce the issue, or condition where the issue can be reproduced;
- Public repository where the issue can be reproduced.

Currently, I'm going to close the issue. In case of any questions do not hesitate to contact us.

**Closed** 2020-05-22 11:46 UTC
Labels: Area: Deployment/Release, OS: Ubuntu, investigate

**Comment by saabeilin** [comment] 2020-09-23 22:32
It seems we are affected with exactly the same issue.

**Comment by skelliest** [comment] 2020-10-08 14:21
We are having the same issue on our private repo, and it was also caused by adding an environment variable. Tried quoting the variable and it didn't help, so we'll have to redo our build so that it doesn't have the environment variable.

```
    - name: Build operations and container
      if: steps.cache.outputs.cache-hit != 'true'
      env:
        TAG: "${GITHUB_SHA}"
      run: |
        docker-compose build <image>
```

**Comment by hazcod** [comment] 2020-11-18 06:56
What information do you need in case this is in a private repository? 
I can supply my Action workflow via email or any other private channel.

**Comment by al-cheb** [comment] 2020-11-18 07:47
> What information do you need in case this is in a private repository?
> I can supply my Action workflow via email or any other private channel.

Hello, @hazcod 
Please provide simple steps to reproduce the issue from our side.

**Comment by hazcod** [comment] 2020-11-18 07:55
I can share my workflow privately with someone from GitHub @al-cheb .
But it's basically a `docker-compose ... build`.

**Comment by MaksimZhukov** [comment] 2020-11-30 09:47
Hello @hazcod !
Is it possible for you to prepare public repository with minimal steps to reproduce the issue and file a new issue in [our repository](https://github.com/actions/virtual-environments/issues/new/choose)?
