### ISSUE TITLE
xcodebuild archive hangs regularly on MacOS runners

### ISSUE THREAD

**Issue by michaelfdickey** [actions/virtual-environments#1820] opened 2020-10-14 20:22 UTC
Hello virtual-environments team :wave:

Enterprise Support has a customer reporting an issue with `xcodebuild archive`, while it regularly runs fine locally, it intermittently hangs when running on `macOS-latest`. Debug Logging does does not provide much additional information, and we only see a time stamp for when the script which runs the archive command is launched and then nothing until the action is cancelled manually by the user.  Given the code-signing requirements, reproducing in a public repo is not ideal. Please reach out to me directly with any questions. 

Thanks!

**Comment by MaksimZhukov** [comment] 2020-10-16 10:45
Hello @michaelfdickey !
Could you please clarify whether the issue happens only in builds with signing or not?
Also, does customer use any build tools like fastlane or similar?
Is it possible to provide any repro steps for this issue because we can’t reproduce it from our side.

We have a bunch of test apps that we run during every image deployment. They validate both signing and no-signing builds and we have never noticed the similar issue on those builds.

I guess it could be related to some specific things in customer’s build that we can’t reproduce on our builds. Probably, it can be some huge project that exhaust machine resources during build and it causes machine to hang.

**Comment by michaelfdickey** [comment] 2020-10-20 18:39
Hi @MaksimZhukov I've relayed those questions to the customer and will follow up as soon as I have an update.

**Comment by arielelkin** [comment] 2020-10-21 10:30
Hello @MaksimZhukov 

> Could you please clarify whether the issue happens only in builds with signing or not?

The issue only happens when calling `xcodebuild archive`, so signing is involved. 

> Also, does customer use any build tools like fastlane or similar?

No, just shell scripts and `xcodebuild`commands.

> Is it possible to provide any repro steps for this issue because we can’t reproduce it from our side.

I have made a small demo project with a minimally reproducible example here: 
https://github.com/shapedbyiris/test-ci

The GitHub Actions workflow hangs when we call `xcodebuild archive`. The same command doesn't hang on my local machine. This is the specific command that causes the workflow to hang:
https://github.com/shapedbyiris/test-ci/blob/master/ci/archive.sh#L19

This is one example of a workflow that I had to cancel after it hung up on that command for one hour:
https://github.com/shapedbyiris/test-ci/actions/runs/270539864

**Comment by johnrich85** [comment] 2020-10-21 15:05
Just to add to this, I'm getting similar issues with a react native app where archiving works locally, but hangs indefinitely when run as part of a workflow. It hangs every time, rather than intermittently. The repo is private, but I'm happy to share details if you get in touch directly.  In lieu of that, I'm largely following the guide here:

https://engineering.talkdesk.com/test-and-deploy-an-ios-app-with-github-actions-44de9a7dcef6

The only real difference being that I'm manually signing/provisioning as follows:

```
xcodebuild -workspace {WORKSPACE} \
           -scheme {SCHEME_HERE} \
           -archivePath $PWD/build/{NAME}.xcarchive \
           PROVISIONING_STYLE="Manual" \
           PROVISIONING_PROFILE={ID} \
           CODE_SIGN_STYLE="Manual" \
           CODE_SIGN_IDENTITY={NAME}  \
           clean archive | xcpretty
```

**Comment by MaksimZhukov** [comment] 2020-10-21 18:32
Hello @arielelkin ! 
Thank you for creating a demo project, but unfortunately I don't have permissions to view it. Could you please provide the access to this project?
Thanks!

**Comment by arielelkin** [comment] 2020-10-22 10:02
@MaksimZhukov done

**Comment by MaksimZhukov** [comment] 2020-10-27 14:40
Hello @arielelkin !
We've reproduced the issue from our side, but, unfortunately, we haven't found the root cause yet. We will continue to investigate and keep you updated. Thank you for your patience!

**Comment by MaksimZhukov** [comment] 2020-10-30 13:24
Hello @arielelkin !
We’ve finally figured out why `xcodebuild archive` command hangs. If a keychain is in the `~/Library/Keychains` directory, a modal window to access keychain will be appear. It is expected behavior and I can reproduce it on my machine too.

As a solution you should use any other folder to create a new keychain. For example:
```
KEYCHAIN_PATH=$RUNNER_TEMP/<keychain name>
security create-keychain -p <keychain password> $KEYCHAIN_PATH
```
Could you please verify if it works for you?

I've also listed all commands required to install Apple Provisioning Profile and Certificate below:
```
# To encode Apple Provisioning Profile and Certificate you can use base64 system
# For example: base64 certificate.p12 > encodedCertificate.txt
echo -n "<your secret that includes encoded certificate>" | base64 --decode --output <certificate name>.p12
echo -n "<your secret that includes encoded provision profile>" | base64 --decode --output <profile name>.mobileprovision

KEYCHAIN_PATH=$RUNNER_TEMP/<keychain name>

security create-keychain -p <keychain password> $KEYCHAIN_PATH
security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
security unlock-keychain -p <keychain password> $KEYCHAIN_PATH
security import <certificate name>.p12 -P <p12 password> -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
security list-keychain -d user -s $KEYCHAIN_PATH

mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
cp <profile name>.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles
```

**Comment by arielelkin** [comment] 2020-11-02 18:29
Thanks @MaksimZhukov, that works. 

It would be great if GitHub could include this in https://github.com/actions, because this step is necessary for submitting iOS apps to the App Store.

**Comment by maxim-lobanov** [comment] 2020-11-02 18:31
@alepauly , do you know the best place for such snippet that could be very useful for customers who submit apps from our CI to App Store?
May be `starter-workflows` or `docs` directly?

**Comment by MaksimZhukov** [comment] 2020-11-06 13:03
Hello everyone!
We will create a guide in the near future. We will post update as soon as we have it.

I'm closing this issue since the fix has been provided. Feel free to contact us if you have any questions.
Thanks!

**Closed by MaksimZhukov** 2020-11-06 13:03 UTC
Labels: Area: Apple, investigate

**Comment by johnrich85** [comment] 2020-11-17 13:12
I'm still getting the same issue @MaksimZhukov. As mentioned previously, I'm following this guide:

https://engineering.talkdesk.com/test-and-deploy-an-ios-app-with-github-actions-44de9a7dcef6

But have updated the keychain script so that it's inline with your suggested fix:
```
KEYCHAIN_PATH=$RUNNER_TEMP/build.keychain

set -eo pipefail

gpg --quiet --batch --yes --decrypt --passphrase="$IOS_KEYS" --output ./.github/secrets/mobileprovision ./.github/secrets/app_profile.gpg
gpg --quiet --batch --yes --decrypt --passphrase="$IOS_KEYS" --output ./.github/secrets/Certificates.p12 ./.github/secrets/certificate.gpg

mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles

cp ./.github/secrets/mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/mobileprovision

security create-keychain -p "" $KEYCHAIN_PATH
security import ./.github/secrets/Certificates.p12 -t agg -k $KEYCHAIN_PATH -P "" -A

security list-keychains -s $KEYCHAIN_PATH
security default-keychain -s $KEYCHAIN_PATH
security unlock-keychain -p "" $KEYCHAIN_PATH

security set-key-partition-list -S apple-tool:,apple: -s -k "" $KEYCHAIN_PATH

security find-identity -v -p codesigning
```

As before the build just hangs without feedback/error

**Comment by MaksimZhukov** [comment] 2020-11-27 14:33
Hello @johnrich85 ! 
We can confirm that provided approach works as expected. Probably, your issue is related to specific commands in your script. Could you please try to use the same approach that was suggested above?

**Comment by adamtharani** [comment] 2021-03-03 22:28
Hey @MaksimZhukov, Just wondering if a guide has been created yet? If it has could you provide a link. Thanks :)

**Comment by christinasund** [comment] 2021-03-16 01:56
> Hello @arielelkin !
> We’ve finally figured out why `xcodebuild archive` command hangs. If a keychain is in the `~/Library/Keychains` directory, a modal window to access keychain will appear. It is expected behavior and I can reproduce it on my machine too.
> 
> As a solution you should use any other folder to create a new keychain. For example:
> 
> ```
> KEYCHAIN_PATH=$RUNNER_TEMP/<keychain name>
> security create-keychain -p <keychain password> $KEYCHAIN_PATH
> ```
> 
> Could you please verify if it works for you?
> 
> I've also listed all commands required to install Apple Provisioning Profile and Certificate below:
> 
> ```
> # To encode Apple Provisioning Profile and Certificate you can use base64 system
> # For example: base64 certificate.p12 > encodedCertificate.txt
> echo -n "<your secret that includes encoded certificate>" | base64 --decode --output <certificate name>.p12
> echo -n "<your secret that includes encoded provision profile>" | base64 --decode --output <profile name>.mobileprovision
> 
> KEYCHAIN_PATH=$RUNNER_TEMP/<keychain name>
> 
> security create-keychain -p <keychain password> $KEYCHAIN_PATH
> security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
> security unlock-keychain -p <keychain password> $KEYCHAIN_PATH
> security import <certificate name>.p12 -P <p12 password> -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
> security list-keychain -d user -s $KEYCHAIN_PATH
> 
> mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
> cp <profile name>.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles
> ```

@MaksimZhukov THANK YOU! This ended up being the only solution that worked for me after days of running into problem after problem with GH Actions and Fastlane. I only hit a minor a snag with the `base64` and garbage characters, but just used `gbase64 -di` and it resolved this for me.

example for anyone who may need it:

```
brew install coreutils
echo "$CERTIFICATES_P12" > cert.txt
echo "$CERTIFICATES_PROFILE" > profile.txt
gbase64 -di cert.txt > cert.p12
gbase64 -di profile.txt > profile.mobileprovision
KEYCHAIN_PATH=$RUNNER_TEMP/login.keychain
// ... the rest is same as above
```

Also, for those asking for a guide, you can use the original link as a baseline: https://engineering.talkdesk.com/test-and-deploy-an-ios-app-with-github-actions-44de9a7dcef6

Then follow the steps in this article for the most part, but instead of using the script he provides just use the script that Maksim posted and the modifications I included if you need to. Also, instead of encoding with gpg, use the standard base64 instead. I should have this uploaded to our public repo soon and will post when I can.

**Comment by MaksimZhukov** [comment] 2021-03-16 09:01
Unfortunately, the guide has not been implemented yet. Currently, we are working on it. We will post update as soon as we have it.

You can also try to use the following actions to import your Apple Certificates and Provisioning Profiles: 
1) [Download Apple Provisioning Profiles](https://github.com/marketplace/actions/download-apple-provisioning-profiles) 
2) [Import Code-Signing Certificates](https://github.com/marketplace/actions/import-code-signing-certificates) 

Please note that these actions are not official GitHub actions and managed by community

**Comment by AlenaSviridenko** [comment] 2021-03-30 04:56
Hey,

Finally, guide on how to install certificates to the image is ready, check it out https://docs.github.com/en/actions/guides/installing-an-apple-certificate-on-macos-runners-for-xcode-development

Thank you for your patience!
