### ISSUE TITLE
Pipeline now failing after Windows 2019 image updated

### ISSUE THREAD

**Issue by justinpenguin45** [actions/virtual-environments#4530] opened 2021-11-16 20:13 UTC
### Description

Bower task fails running postinstall script (gulp command)
Error is "ENOENT spawn C:\npm\prefix\gulp ENOENT"
If I take the postinstall script out, then the Bower task succeeds. Maybe it has something to do with gulp then, as the postinstall script is a gulp command. Either way this worked before the image update...

Log below

bower                             postinstall gulp wiredep
bower                                  ENOENT spawn C:\npm\prefix\gulp ENOENT

Stack trace:
Error: spawn C:\npm\prefix\gulp ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)

Console trace:
Error
    at StandardRenderer.error (C:\npm\prefix\node_modules\bower\lib\renderers\StandardRenderer.js:88:37)
    at Logger.<anonymous> (C:\npm\prefix\node_modules\bower\lib\bin\bower.js:113:30)
    at Logger.emit (events.js:400:28)
    at Logger.emit (C:\npm\prefix\node_modules\bower\lib\node_modules\bower-logger\lib\Logger.js:29:39)
    at C:\npm\prefix\node_modules\bower\lib\commands\index.js:49:24
    at _rejected (C:\npm\prefix\node_modules\bower\lib\node_modules\q\q.js:864:24)
    at C:\npm\prefix\node_modules\bower\lib\node_modules\q\q.js:890:30
    at Promise.when (C:\npm\prefix\node_modules\bower\lib\node_modules\q\q.js:1142:31)
    at Promise.promise.promiseDispatch (C:\npm\prefix\node_modules\bower\lib\node_modules\q\q.js:808:41)
    at C:\npm\prefix\node_modules\bower\lib\node_modules\q\q.js:624:44
System info:
Bower version: 1.8.13
Node version: 14.18.1
OS: Windows_NT 10.0.17763 x64
##[error]Bower failed with error: The process 'C:\npm\prefix\bower.cmd' failed with exit code 1

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20211110.1 is where this started failing

### Is it regression?

Version: 20211102.4

### Expected behavior

Bower postinstall script should complete successfully

### Actual behavior

Bower postinstall script fails

### Repro steps

Run the pipeline in Azure

**Comment by mikhailkoliada** [comment] 2021-11-17 07:13
@justinpenguin45 Hello!
Could you post a minimal workflow in a public repo so we could reproduce the issue on our side?

**Comment by justinpenguin45** [comment] 2021-11-17 14:28
That takes quite a bit of time that I don't have at the moment. Any idea
why gulp or bower would have been affected by the image update?

**Comment by justinpenguin45** [comment] 2021-11-18 16:02
This has put us at a standstill. Is there any way we can get back to the working image??

**Comment by miketimofeev** [comment] 2021-11-18 16:49
@justinpenguin45 we don't have much experience with either gulp or bower that's why we are asking for a public repro to speed up the investigation

**Comment by justinpenguin45** [comment] 2021-11-18 19:33
I do understand, and we are all so busy! Thinking out of band here, and this is probably the appropriate place but maybe MS/Azure should give consumers the option to also choose the image (and lock it in) when using the hosted build agents. I locked in the Windows 2019 build agent, but with the image changing from underneath me, could me problematic. It would be cool if once we are using a certain version (image) then we can keep it indefinitely, and can choose to update if we want.

**Comment by shilovmaksim** [comment] 2021-11-29 12:53
Hi @justinpenguin45. We are going to close the issue since there are no repro steps or more detailed information how to reproduce the issue provided.
Feel free to reopen the issue if you have more information provide.

**Closed by shilovmaksim** 2021-11-29 12:53 UTC
Labels: Area: JavaScript and Node.js, investigate
