### ISSUE TITLE
Update [Windows Driver Kit] to latest version (10.0.18362.1) 

### ISSUE THREAD

**Issue by heavenwing** [actions/virtual-environments#259] opened 2020-01-13 06:37 UTC
**Tool information**
- Tool name: Windows Driver Kit in Windows Server 2019
- Add or update? : Update
- Desired version: 10.0.18362.1
- Approximate size: not sure
- If this is an add request:
  - Brief description of tool: to build windows driver project
  - URL for tool's homepage: https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk

**Area for Triage**:

**Question, Bug, or Feature?**: Feature

##[error]C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(382,5): Error MSB8020: The build tools for WindowsKernelModeDriver10.0 (Platform Toolset = 'WindowsKernelModeDriver10.0') cannot be found. To build using the WindowsKernelModeDriver10.0 build tools, please install WindowsKernelModeDriver10.0 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ * ] Windows Server 2019

**Can this tool be installed during the build?**
No

**Are you willing to submit a PR?**
No

**Comment by nibanks** [comment] 2020-02-16 21:37
From what I can tell from [Install-WDK.ps1](https://github.com/actions/virtual-environments/blob/master/images/win/scripts/Installers/Windows2019/Install-WDK.ps1) it should be installing `Version: 10.0.18362.0`:
```PowerShell
# Version: 10.0.18362.0
# Update Validate-WDK.ps1 if the version changes!
# There doesn't seem to be any way to check the version programmatically
```
I'm trying to onboard building a universal Windows driver and I've explicitly targeted this version:
```xml
  <PropertyGroup Label="Globals">
    <ProjectGuid>{C31B028C-E91C-4CF7-A8E7-F385B2AF5F85}</ProjectGuid>
    <TemplateGuid>{1bc93793-694f-48fe-9372-81e2b05556fd}</TemplateGuid>
    <TargetFrameworkVersion>v4.5</TargetFrameworkVersion>
    <MinimumVisualStudioVersion>12.0</MinimumVisualStudioVersion>
    <WindowsTargetPlatformVersion>10.0.18362.0</WindowsTargetPlatformVersion>
  </PropertyGroup>
```
But I get the same build break listed above (MSFT internal build [here](https://microsoft.visualstudio.com/OS/_build/results?buildId=21441935&view=logs&j=a49c099d-8745-53b2-bf27-2743289fa728&t=5119c764-6bb2-5cc8-aba1-40dc545a9dbf)):

> ##[error]C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(382,5): Error MSB8020: The build tools for WindowsKernelModeDriver10.0 (Platform Toolset = 'WindowsKernelModeDriver10.0') cannot be found. To build using the WindowsKernelModeDriver10.0 build tools, please install WindowsKernelModeDriver10.0 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".

This is currently blocking internal Windows Networking work for open sourcing code for dotnet to consume.

**Comment by miketimofeev** [comment] 2020-02-17 11:14
@nibanks thanks for reporting this issue. We are performing an initial investigation.

**Comment by edglas** [comment] 2020-02-19 17:32
@miketimofeev thanks for investigating. Were you able to make any progress? We have an email thread going with @nibanks on this issue. It seems the toolset is not in the path, right?

**Comment by nibanks** [comment] 2020-02-20 00:29
Thanks to some debugging with internal MSFT folks, it looks like it might be an issue of installing the WDK before VS instead of after it.

I'd appreciate it if this could be fixed quickly as this is blocking my team, which is then blocking the dotnet team.

**Comment by miketimofeev** [comment] 2020-02-20 08:54
@edglas @nibanks @heavenwing I've made PR with the fix and with some additional improvements. Feel free to review it
https://github.com/actions/virtual-environments/pull/431

**Comment by nibanks** [comment] 2020-02-20 14:46
Thanks @miketimofeev. It looks good to me. From the time the PR get's merge, how long does it usually take before the my Azure Pipelines images would have the fixe?

**Comment by miketimofeev** [comment] 2020-02-20 15:39
@nibanks approx 1-1.5 week.

**Comment by miketimofeev** [comment] 2020-02-24 07:44
@heavenwing @nibanks as a temporary workaround - could you try to run this powershell script as a first step?
```
try
{
     $process = Start-Process `
    -FilePath "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\VSIXInstaller.exe" `
    -ArgumentList ("/quiet", '"C:\Program Files (x86)\Windows Kits\10\Vsix\VS2019\WDK.vsix"') `
    -Wait `
    -PassThru
}
catch
{
    Write-Host "There is an error during WDK.vsix installation"
    $_
    exit 1
}
```

**Comment by nibanks** [comment] 2020-02-24 15:17
@miketimofeev thanks for the work around! I can confirm (after waiting for nearly 15 minutes) that this allows for my solution to be successfully built.

**Comment by miketimofeev** [comment] 2020-02-24 15:48
@nibanks great! I will notify when the image with the fix is deployed.

**Comment by nibanks** [comment] 2020-02-28 15:25
@miketimofeev any progress here? My understand was that this would hopefully be deployed by sometime today.

**Comment by miketimofeev** [comment] 2020-03-01 17:21
@nibanks it's already deployed to some environments and some are still in processing. The pre-release tag will disappear when it's done
https://github.com/actions/virtual-environments/releases/tag/win19%2F20200225.0

**Comment by nibanks** [comment] 2020-03-02 05:12
According to my testing, it seems that my WDK builds are working without the workaround now.

**Comment by miketimofeev** [comment] 2020-03-02 10:05
@nibanks yes, the deployment has finally finished. Closing the issue, but feel free to reopen if you have any concerns.
Thank you!

**Closed by miketimofeev** 2020-03-02 10:05 UTC
Labels: Area: C/C++, OS: Windows, awaiting-deployment, bug
