### ISSUE TITLE
Xamarin.UITest fails after #1903

### ISSUE THREAD

**Issue by jeromelaban** [actions/virtual-environments#1932] opened 2020-10-29 13:12 UTC
**Description**  
Xamarin.UITest uses the PList specified here: 
https://github.com/MaksimZhukov/virtual-environments/blob/4444dfd517ec0bc970a8c1bd8dbc2a902b9db97c/images/macos/provision/core/xamarin.sh#L90

Which overrides the default version that the pipeline may set using `xcode-select`, after the change in #1903.

**Area for Triage**:  

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
The environment configuration specified by `xcode-select` is used properly, not the default version of the vm image. This makes the testing fail because of https://github.com/microsoft/appcenter/issues/1998.

**Actual behavior**  
Xamarin.UITest fails by using the version specified in the plist file, not the ambient one. The following message is displayed:

```
Using Xamarin Studio override for Apple SDK: /Applications/Xcode_12.app
```

**Repro steps**  
Run Xamarin.UITests tests using a simulator.

**Comment by maxim-lobanov** [comment] 2020-10-29 13:31
Hello @jeromelaban , could you please provide additional context how it affects you? We are not familiar with Xamarin.UITest and don't have enough context to reproduce the issue.

I will provide context around this change:
Recently, we have switched default Xcode to 12.0.1 on images and faced with issue that Xamarin.iOS failed to find default Xcode.
[According to the code](https://github.com/xamarin/Xamarin.MacDev/blob/a1bc6f39b3efe5d817c60d78eaff3f4c2de720ea/Xamarin.MacDev/AppleSdkSettings.cs#L162), I tries to use the following ways to find it:
1) Use `MD_APPLE_SDK_ROOT` variable
2) Use `${HOME}/Library/Preferences/Xamarin/Settings.plist`
3) Fallback to `/Applications/Xcode.app` (on image it is symlink for default Xcode)

Previously, 1 and 2 were not set on images and it went to 3. But after upgrading to Xcode 12, Xamarin.iOS was not able to use Xcode via symlink. This issue was [reported to Xamarin team](https://github.com/xamarin/xamarin-macios/issues/9960) but unfortunately, they don't have fix for this issue and the single suggestion from their side was using Xcode directly without symlink.

According to the [Xamarin.iOS code](https://github.com/xamarin/Xamarin.MacDev/blob/a1bc6f39b3efe5d817c60d78eaff3f4c2de720ea/Xamarin.MacDev/AppleSdkSettings.cs#L162), the single way to prevent fallback to `/Applications/Xcode.app` is setting `MD_APPLE_SDK_ROOT` or `${HOME}/Library/Preferences/Xamarin/Settings.plist`. The second way was implemented from our side.

**Comment by jeromelaban** [comment] 2020-10-29 14:13
Thanks for the fast response.

The Xamarin.UITest source is not public, but the code is basically doing this:

```
private void SetXamarinStudioAppleSDKOverridePath()
	{
		try
		{
			string folderPath = Environment.GetFolderPath(Environment.SpecialFolder.Personal);
			string text = Path.Combine(folderPath, "Library", "Preferences", "Xamarin", "Settings.plist");
			if (File.Exists(text))
			{
				string text2 = PListHelper.ReadPListValueFromFile(text, "AppleSdkRoot");
				Log.Info("Using Xamarin Studio override for Apple SDK: " + text2);
				Environment.SetEnvironmentVariable("DEVELOPER_DIR", text2);
			}
		}
		catch (Exception ex)
		{
			if (!ex.Message.StartsWith("Could not find key", StringComparison.InvariantCultureIgnoreCase))
			{
				Log.Debug("Failed trying to read Xamarin Studio Apple SDK path.", ex);
			}
		}
	}
```
Which takes the version specified in the Settings.plist file, overriding the default version specified even if it has been changed. 

Xamarin.iOS itself is indeed using the proper versions specified, and works properly. (where using [this piece of YAML ](https://github.com/unoplatform/uno/blob/52131326b494a7ff0d6ef6d148b9854c3e84f301/build/ci/templates/ios-build-select-version.yml#L14) in the pipeline to do so), but Xamarin.UITest does not work the same way.

**Comment by maxim-lobanov** [comment] 2020-10-29 14:27
@jeromelaban , thank you for explanation.
Unfortunately, I am not sure about proper fix here.
The problem is that if we don't use `Settings.plist`, the default Xamarin + default Xcode configuration is broken on image because of https://github.com/xamarin/xamarin-macios/issues/9960 and it will cause significant impact.
(without `Settings.plist`, Xamarin.iOS is looking at `/Applications/Xcode.app` and can't resolve Xcode 12 by the symlink)

As a workaround, you can add step `rm -f ${HOME}/Library/Preferences/Xamarin/Settings.plist` and it will unblock you. But of course, it is just a workaround.
Ideally, Xamarin.UITests should look at `MD_APPLE_SDK_ROOT` - the same approach like Xamarin.iOS does but probably, it is not something that could be easily change, right?

**Comment by maxim-lobanov** [comment] 2020-10-29 15:10
@jeromelaban , I also created an issue for Xamarin.IOS because it looks like their logic to resolve Xcode has a bug. It should use `xcode-select` if plist is not found (at least I think so 😄  ): https://github.com/xamarin/xamarin-macios/issues/10003

**Comment by jeromelaban** [comment] 2020-10-29 15:40
@maxim-lobanov Thanks a lot! Removing the file indeed restore the feature back. I wish Xamarin.UITest was open-source, it would help for this kind of troubleshooting :)

**Comment by maxim-lobanov** [comment] 2020-10-30 06:14
@jeromelaban , Xamarin.iOS team has already fixed [an issue](https://github.com/xamarin/xamarin-macios/issues/10003) that I created yesterday in https://github.com/xamarin/Xamarin.MacDev/pull/84. So the next release of Xamarin.iOS will look at `xcode-select` output if plist is not found. After that we will be able to remove plist from images.

Just a better workaround for now:
```bash
/usr/libexec/PlistBuddy -c "add :AppleSdkRoot string $(dirname $(dirname $(xcode-select -p)))" ~/Library/Preferences/Xamarin/Settings.plist
```

**Comment by jeromelaban** [comment] 2020-10-30 11:55
@maxim-lobanov thanks for the troubleshooting!

**Comment by maxim-lobanov** [comment] 2020-11-02 10:30
@jeromelaban , I am closing the issue for now. We will take care about removing plist after installing the next release of Xamarin.iOS and confirming issue is resolved.
Please let me know if you have any concerns

**Closed by maxim-lobanov** 2020-11-02 10:30 UTC
Labels: Area: Apple, Area: Xamarin, OS: macOS, investigate
