### ISSUE TITLE
Bring back JDK 11 on vs2017-win2016 version

### ISSUE THREAD

**Issue by mickael-caro-sonarsource** [actions/virtual-environments#885] opened 2020-05-15 12:01 UTC
**Tool information**
- Tool name: Azure JDK
- Add or update? "bring back"
- Desired version: version 11
C:\Program Files\Java\zulu-11-azure-jdk_11.33.15-11.0.4-win_x64

**Area for Triage**:
Java 

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ X] Windows Server 2016 R2
- [ ] Windows Server 2019

Hi, 

Can you please bring back JDK 11 on win2016-vs2017 hosted image please ? It has broke our pipeline, and this will remain consistent with the version currently available on windows-latest image.

Thanks in advance.

**Comment by maxim-lobanov** [comment] 2020-05-15 12:37
@mickael-caro-sonarsource , thank you for your report. It is not expected because we didn't remove it from the images.
At the first look, it seems that Java 11 is still installed but `$env:JAVA_HOME_11_X64` variable points to `C:\Program Files\Java\zulu-13-azure-jdk_13.31.11-13.0.3-win_x64`
We are looking at it

**Comment by maxim-lobanov** [comment] 2020-05-15 12:50
This issue was caused by #795 PR. We are preparing the fix and will rollout it early next week.
As a workaround, you can use full path to point to Java `C:\Program Files\zulu-11-azure-jdk_11.33.15-11.0.4-win_x64` or add [Java Tool Installer task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/java-tool-installer?view=azure-devops) / [setup-java](https://github.com/actions/setup-java)

**Comment by mickael-caro-sonarsource** [comment] 2020-05-15 12:52
Thanks for your prompt reply ! I'll try to test the workaround.

**Comment by ThadHouse** [comment] 2020-05-18 00:34
Same bug is happening on `windows-2019` too. Just want to make sure its fixed there as well.

**Comment by miketimofeev** [comment] 2020-05-18 07:19
@ThadHouse yeah, the installation script is the same for both Windows version. We're going to start image deployment with the fix today.

**Comment by miketimofeev** [comment] 2020-05-22 12:16
@ThadHouse @mickael-caro-sonarsource both win19 and win16 images have been deployed. Java11 is on its place 😀I'm closing the issue, but feel free to ping me if you have any concerns.

**Closed by miketimofeev** 2020-05-22 12:16 UTC
Labels: Area: Java, OS: Windows, awaiting-deployment, bug
