### ISSUE TITLE
Python on macOS does not have libpython.so

### ISSUE THREAD

**Issue by mrkn** [actions/virtual-environments#125] opened 2019-12-04 01:45 UTC
**Describe the bug**
On macOS environment, all the versions of Python don't have libpython.so shared libraries.
Due to this issue, we cannot run applications, which embed a Python interpreter, on GitHub Actions.

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
The following command shows the appropriate shared library name like `libpython3.6m.so`.

```
python -c 'from distutils.sysconfig import get_config_var; print(get_config_var("LDLIBRARY"))'
```

Pythons on ubuntu-latest have their shared libraries.  [This output](https://github.com/mrkn/github-actions-test/runs/332238280#step:4:8) is the example of expected behavior.

**Actual behavior**
On the current environment, the above command shows the static library name like `libpython3.6m.a`.

See [this output](https://github.com/mrkn/github-actions-test/runs/332238240#step:4:8).

**Comment by smola** [comment] 2020-02-13 09:22
I can confirm the issue. On my cmake builds for macOS, where I force the use of shared libraries, the Python library is detected at `/usr/local/Frameworks/Python.framework/Versions/3.7/lib/libpython3.7m.dylib` while the rest of the Python distribution is detected at `/Users/runner/hostedtoolcache/Python/3.7.6/x64/`. This, of course, creates both build and runtime problems.

Could we get a shared library included in hostedtoolcache's Python install?

**Comment by vmapetr** [comment] 2020-03-03 14:08
@mrkn We compiled hostedtoolcache Python for macOS with enabled shared libraries. It will be available after next image rollout.

**Comment by mrkn** [comment] 2020-03-03 15:17
@vmapetr Thank you!  I’ll try it when it gets available.

**Comment by miketimofeev** [comment] 2020-03-05 18:31
@mrkn the image has been deployed. Could you check the python, please?

**Comment by maxim-lobanov** [comment] 2020-03-12 09:16
Hello @mrkn , just a gentle reminder. Could you please validate that the issue is resolved?

**Comment by mrkn** [comment] 2020-03-12 09:24
@maxim-lobanov Thank you for reminding me.  I've confirmed the problem is fixed!

https://github.com/mrkn/pycall.rb/runs/502764040?check_suite_focus=true#step:8:13

**Comment by maxim-lobanov** [comment] 2020-03-12 09:34
Great, thank you for checking! I am closing the issue

**Closed by maxim-lobanov** 2020-03-12 09:34 UTC
Labels: Area: Python, OS: macOS, awaiting-deployment
