### ISSUE TITLE
SafariDriver unable to create a session using iOS Simulator in MacOS Actions

### ISSUE THREAD

**Issue by bhebert-zmtp** [actions/virtual-environments#1453] opened 2020-08-20 19:24 UTC
**Description**  
SafariDriver appears to be unable to connect to an iOS instance of Safari via the iOS simulator in MacOS actions, even when safaridriver has been enabled, and the tests explicitly reference capabilities that should be available within the MacOS container. Any time the iOS Simulator is requested in the capabilities, safaridriver reports that it cannot find any session hosts that support the requested capabilities.

**Area for Triage**:  

Apple, Containers, Bug, Testing and code coverage

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
SafariDriver *should* be able to create a session successfully. If no iOS Simulator instance was found, it will launch a new instance and *may* throw the following error as the simulator may not have completed booting yet:
```json
{
    "value": {
        "error": "session not created",
        "message": "Could not create a session: Unable to find the RWISimulator associated with the booted simulator: 'iOS 13.6 (17G64) - iPhone SE (2nd generation)' (00527894-6513-47A6-9A3F-3B12D1EAC5E7)",
        "stacktrace": ""
    }
}
```

At this point, attempting to connect a second time is usually successful, and should produce the following output:
```json
{
    "value": {
        "sessionId": "3FA10E71-6A59-4067-8830-A6858DA92608",
        "capabilities": {
            "safari:deviceName": "iPhone SE (2nd generation)",
            "safari:platformVersion": "13.6",
            "safari:automaticInspection": false,
            "webkit:WebRTC": {
                "DisableICECandidateFiltering": false,
                "DisableInsecureMediaCapture": false
            },
            "browserVersion": "13.1.2",
            "safari:deviceType": "iPhone",
            "strictFileInteractability": false,
            "browserName": "Safari",
            "safari:useSimulator": true,
            "safari:platformBuildVersion": "17G64",
            "setWindowRect": false,
            "acceptInsecureCerts": false,
            "safari:deviceUDID": "00527894-6513-47A6-9A3F-3B12D1EAC5E7",
            "safari:automaticProfiling": false,
            "platformName": "iOS",
            "safari:diagnose": false
        }
    }
}
```

**Actual behavior**  
```json
{
    "value": {
        "error": "session not created",
        "message": "Could not create a session: Could not find any session hosts that match the requested capabilities.",
        "stacktrace": ""
    }
}
```

**Repro steps**  
1. Clone [this repository](https://github.com/bhebert-zmtp/GitHubActions_WebDriveriOS).
2. `npm install`
3. `npm run test` (which would produce the expected results locally, but fail on GitHub actions)

**Comment by maxim-lobanov** [comment] 2020-08-25 07:52
@bhebert-zmtp , Thank you for providing repro steps for this issue.
I have confirmed that issue exists and reproduces even I login to MacOS VM directly. Also I have confirmed the everything works as expected on my local box.

I have simplified repro steps a bit:
1) run `/usr/bin/safaridriver --port 50032` in terminal
2) run the following code in PowerShell terminal:
```
$json = @{
  capabilities = @{
    alwaysMatch = @{
      browserName = "Safari";
      platformName = "iOS";
      "safari:useSimulator": "true";
      "safari:deviceType": "iPhone";
    }
  }
}
Invoke-RestMethod -Uri "localhost:50032/session" -Method POST -Body ($json | ConvertTo-Json)
```

Unfortunately, I don't know the root cause of this issue for now (don't have much experience with safaridriver).
What I have tried:
- Checked that simulators are available via `xcrun simctl list devices --json` command
- Started simulator manually before running commands above
- Ran Xcode UI tests on simulators and they pass successfully (simulator is created)
- Ran Selenium tests with `safaridriver` (without capabilities) and Safari works as expected.
- Tried to specify `safari:deviceUUID` property with specific device
- Tried to boot device before tests via `xcrun simctl boot <deviceId>`
- Tried to call `safaridriver` with `--diagnose` flag, no additional output is produced
- Switched Xcode versions

Based on the fact that all use-cases above works as expected, we got into some specific issue that `safaridriver` is not able to find iOS devices.

**Comment by Queenj30** [comment] 2020-08-27 08:52
images/win/scripts/SoftwareReport/SoftwareReport.Tools.psm1

**Comment by Queenj30** [comment] 2020-08-27 08:52
images/win/scripts/SoftwareReport/SoftwareReport.Tools.psm1

**Comment by maxim-lobanov** [comment] 2020-09-02 04:50
Hello @bhebert-zmtp , we have found that root cause of this issue is Xcode 12 beta that is installed on images.
I have built test image with all installed Xcode versions except 12.0 beta and your test case works perfect on that image.
Also I have confirmed that installation of Xcode 12.0 beta on my local box breaks your use-case too.
Unfortunately, I didn't find any way to uninstall Xcode 12.0 beta fully in runtime as a workaround.

We can't remove Xcode 12.0 beta from our images since it is pretty popular and it will impact customers.
I suggest waiting for stable release of Xcode 12.0 to see if this issue is fixed and report this bug to Apple.

**Comment by bhebert-zmtp** [comment] 2020-09-02 12:54
Thanks!

**Comment by maxim-lobanov** [comment] 2020-09-08 07:26
Closing this for now since root cause is found but it is external issue that can't be fixed from our side for now

**Closed by maxim-lobanov** 2020-09-08 07:26 UTC
Labels: Area: Packages, OS: macOS, investigate

**Comment by al-cheb** [comment] 2020-09-08 08:00
@burg, Hi, Brian
Do you you know about that issue?

**Comment by burg** [comment] 2020-09-21 20:09
Hello folks, I wish I had been on the thread earlier!

We found a late-breaking bug in safaridriver + iOS 14 that causes iOS Simulator sessions to fail unless that simulator instance has loaded the Settings > Safari > Advanced screen. The fix for this will be included in later iOS releases / simulator runtimes.

A potential workaround is to enable it manually by loading the settings screen, then using `xcrun simctl clone` to create additional simulators with it enabled.

This bug does not affect simulator runtimes other than iOS 14.0.
