### ISSUE TITLE
rc.exe randomly missing from environment

### ISSUE THREAD

**Issue by matham** [actions/virtual-environments#1087] opened 2020-06-21 05:22 UTC
**Describe the bug**
When building cython code from a python project using pip on windows-latest it randomly errors out with `LINK : fatal error LNK1158: cannot run 'rc.exe'`.

The identical code, will sometimes succeed to build the project and sometimes fail with this error. Generally, I just need to re-run the CI and it succeeds. The problem is that either `rc` should be available or it shouldn't. It shouldn't be randomly missing.

There's a related issue https://github.com/actions/virtual-environments/issues/294, but the problem here is that it sometimes works without adding rc to the path as shown in the issue. So either it should never be found and I need to add that step to add it to the path, or it should always be found (I think this should ideally be the case).

**Area for Triage**: 

C/C++

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [x] Windows Server 2019

**Expected behavior**
`rc` should either always be required to be added to the path or never. Not randomly be missing.

**Actual behavior**

The actual error is:
`LINK : fatal error LNK1158: cannot run 'rc.exe'`
`error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX86\\x64\\link.exe' failed with exit status 1158`.

To replicate, I created a branch of kivy with the only difference adding `-v -v` (to make it more verbose, you can specify `-v` up to 3 times) to pip when it builds the project. The build succeeded: https://github.com/kivy/kivy/runs/791883878?check_suite_focus=true.

Then I created a new commit simply removing one `-v` and the build still succeeded. So I re-ran the build about 7 or 8 times until it failed with the above error message: https://github.com/kivy/kivy/runs/791983410?check_suite_focus=true.

**Comment by al-cheb** [comment] 2020-06-22 13:23
Hello, @matham

I can't reproduce the issue from my side(local and github actions). By default these is no any versions of `rc.exe` available in the `PATH`(you can easily check: `Get-Command rc.exe -ErrorAction SilentlyContinue`)  and currently we don't have any plans to add `rc.exe` to the `PATH ` due to unpredictable results. Could you please provide artifact logs with failed builds if you can reproduce the issue?


```
- name: Install Kivy
    run: |
    . .\.ci\windows_ci.ps1
    [System.Net.WebClient]::new().DownloadFile('https://live.sysinternals.com/procmon.exe' , 'C:\Windows\procmon.exe')
    [System.Net.WebClient]::new().DownloadFile('https://github.com/al-cheb/test/raw/master/procmon.pmc' , 'C:\procmon.pmc')
    procmon.exe /accepteula /backingfile c:\log.pml /quiet
    Install-kivy
    procmon.exe /terminate | Out-Null
    dir C:\
    procmon.exe /Quiet /Minimized /Openlog c:\log.pml /LoadConfig C:\procmon.pmc /SaveApplyFilter /SaveAs C:\pmc.pml | Out-Null
- uses: actions/upload-artifact@v2
    if: always()
    with:
    name: procmon
    path: C:\pmc.pml
```

**Comment by matham** [comment] 2020-06-22 16:31
Hi and thanks for getting back.

I added the procmon stuff and here's the failed action after the first run, luckily: https://github.com/kivy/kivy/runs/796074523?check_suite_focus=true. 

The only potential issue I can see is at the end at this line `12:13:55.3541136 PM	link.exe	1544	RegQueryValue	HKLM\System\CurrentControlSet\Services\bam\State\UserSettings\S-1-5-21-2116643009-3167967168-2279772616-500\\Device\HarddiskVolume2\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.26.28801\bin\Hostx86\x64\link.exe	NAME NOT FOUND	Length: 40`

**Comment by al-cheb** [comment] 2020-06-22 17:44
@matham, Looks like we have got the latest artifact for python 3.8.3, not for the python 3.7.7. We should add something: `procmon-${{ matrix.python }}-${{ matrix.arch }}`

> Or maybe actions/setup-python does add rc to the path when it sets up python?

I can't find any code in the `https://github.com/actions/setup-python` task related to `rc.exe`.

**Comment by matham** [comment] 2020-06-22 19:23
Ok, here's the fixed action with per-vm pocmon file: https://github.com/kivy/kivy/runs/796633367?check_suite_focus=true.

**Comment by al-cheb** [comment] 2020-06-22 21:26
@matham, Thank you for providing logs. 

Failed builds:
1. At the begging we have two instances of link
![image](https://user-images.githubusercontent.com/47745270/85335019-f7228800-b4e4-11ea-9010-a265c1849cc9.png)

2. Differences between `6520` and `6396` pids  is how these processes inherit environment variables.

6396 (PATH):
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\\Extensions\Microsoft\IntelliCode\CLI
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.26.28801\bin\HostX86\x64
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.26.28801\bin\HostX86\x86
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\VC\VCPackages
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\bin\Roslyn
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Team Tools\Performance Tools\x64
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Team Tools\Performance Tools
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\\x64
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\
C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\
C:\Program Files (x86)\HTML Help Workshop
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\FSharp\
C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x86
C:\Program Files (x86)\Windows Kits\10\bin\x86
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\\MSBuild\Current\Bin
C:\windows\Microsoft.NET\Framework\v4.0.30319
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\
C:\hostedtoolcache\windows\Python\3.8.3\x64\share\sdl2\bin
C:\hostedtoolcache\windows\Python\3.8.3\x64\share\glew\bin
C:\hostedtoolcache\windows\Python\3.8.3\x64\share\gstreamer\bin
......
```

6520 (PATH) <----- Much shorter and missing 18 paths
```
C:\hostedtoolcache\windows\Python\3.8.3\x64\share\sdl2\bin
C:\hostedtoolcache\windows\Python\3.8.3\x64\share\glew\bin
C:\hostedtoolcache\windows\Python\3.8.3\x64\share\gstreamer\bin
....
```

Could just be a coincidence, but it is possible to compile `kivy\_clock.c` before `kivy\_event.c` just for test?

**Comment by matham** [comment] 2020-06-23 15:39
Hmm, thanks for tracing this down to setuptools. Shall I open a bug report with them?

**Comment by al-cheb** [comment] 2020-06-23 16:08
@matham,  I think it's a good idea to create a bug report may be they will help us to debug this issue.

**Comment by matham** [comment] 2020-06-23 21:29
I opened https://github.com/pypa/setuptools/issues/2212.

**Comment by al-cheb** [comment] 2020-07-14 06:24
Resolved in  https://github.com/pypa/setuptools/issues/2212.

**Closed by al-cheb** 2020-07-14 06:24 UTC
Labels: Area: C/C++, OS: Windows, investigate
