### ISSUE TITLE
Purge npm/yarn cache before shipping images

### ISSUE THREAD

**Issue by imbsky** [actions/virtual-environments#522] opened 2020-03-08 23:36 UTC

**Comment by miketimofeev** [comment] 2020-03-09 08:17
Hi @imbsky. We're already working on disabling pre-cached npm/yarn packages on the macOS VM image if I get your issue right.

**Comment by imbsky** [comment] 2020-03-09 09:15
Nice

**Comment by miketimofeev** [comment] 2020-03-09 09:42
Closing this issue as it's a duplicate.
Feel free to reopen if you have any concerns.
Thank you!

**Closed by miketimofeev** 2020-03-09 09:42 UTC
Labels: needs triage

**Comment by smorimoto** [comment] 2020-10-14 03:58
@miketimofeev This happens again in the Windows image. Please re-open this issue.

**Comment by smorimoto** [comment] 2020-10-14 04:03
Honestly, why don't you stop installing many tools by default? It seems that you all aren't able to maintain that properly. If you continue to do that, users will just lose.

**Comment by smorimoto** [comment] 2020-10-14 04:07
As I've said many times, continuing to ship such dirty images is not a good idea from a CI perspective. Even if you want to keep shipping such images, it's a really good idea to ship the completely plain images.

**Comment by LeonidLapshin** [comment] 2020-10-14 07:17
Hey, @smorimoto !
Could you please open a new issue with problem description using a [template](https://github.com/actions/virtual-environments/issues/new?assignees=&labels=needs+triage&template=bug-report.md&title=) ?
Thank you!

**Comment by smorimoto** [comment] 2020-10-14 07:21
@LeonidLapshin I have no strong objection to opening a new issue, but the problem is quite simple, and everything is as the title says.
