### ISSUE TITLE
Ability to shutdown/disable system services on an image 

### ISSUE THREAD

**Issue by n1hility** [actions/virtual-environments#348] opened 2020-02-02 01:57 UTC
The Ubuntu images start mysql by default, which interferes with the ability to follow the service pattern with mysql (like all other databases). Steps can't be used to shutdown the service because the services block is ran earlier.

Alternatively a setup-script option would suffice.

For example, the following currently fails because of the port conflict with the pre-running service:
```yaml
services:
    mysql:
        image: mysql:8
        env:
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_pass
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
```

Ideally you would be able to do something liike

```yaml
runs-on: ubuntu-latest
without-service: mysql
```
or Alternatively

```yaml
runs-on: ubuntu-latest
setup-step:
    shell: bash
    run: |
      sudo service mysql stop || true
```

**Comment by bryanmacfarlane** [comment] 2020-02-02 04:57
I don't think the image should start mysql by default.  It should be installed and those that use it, start it.

**Comment by n1hility** [comment] 2020-02-04 16:06
@bryanmacfarlane that would be even better. I assumed it wouldn't be an option because it would break those relying on it already running.

**Comment by bryanmacfarlane** [comment] 2020-02-04 16:13
I don't think we need without-services keyword but a prejob hook in some form would help.  we have considered prejob actions script (they currently support post job).  That would allow someone to write an action 'stop svc' which ensures a service is stopped in a platform agnostic way.  @chrispat

**Comment by ethomson** [comment] 2020-02-04 16:16
This is clever, @n1hility - I like the `without` keyword.

In this case, though, I agree with @bryanmacfarlane: we shouldn't be starting this at all.

@alepauly can we turn this off at startup in the next update?

**Comment by alepauly** [comment] 2020-02-04 16:20
@ethomson I don't think we can do it with the next update since it's a breaking change to anyone that might be assuming it's running. We'll communicate to users to make sure they can prepare and then rollout the change.

**Comment by ethomson** [comment] 2020-02-04 16:22
OK thanks.

**Comment by bryanmacfarlane** [comment] 2020-02-04 16:26
@alepauly - plus one on communicating now (changelog) and then shutting it down in a month or so.  This will also be a good perf win. @n1hility  We still may add the prejob hook for other reasons ...  If you could log an issue in actions/runner, that would be great.

**Comment by n1hility** [comment] 2020-02-06 01:06
@bryanmacfarlane sure will do

**Comment by maxim-lobanov** [comment] 2020-02-06 16:00
@alepauly , @bryanmacfarlane , we have created announcement issue to notify customers about future changes: https://github.com/actions/virtual-environments/issues/375

**Comment by AlenaSviridenko** [comment] 2020-04-10 08:28
closing this issue since MySQL was shut down by default a month ago.

Please, feel free to open new ticket if the issue is still actual.

**Closed by AlenaSviridenko** 2020-04-10 08:28 UTC
Labels: Area: Databases, Area: Scripting and command line, OS: Ubuntu, enhancement
