### ISSUE TITLE
VS2022 Build is not working

### ISSUE THREAD

**Issue by karepa** [actions/virtual-environments#5240] opened 2022-03-16 03:10 UTC
### Description

Hi Team.
Windows-Latest + MSBuild Latest is not working from SQL Reports.

Error:
Error MSB4226: The imported project "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Reporting Services\Microsoft.ReportingServices.MSBuilder.targets" was not found

If I revert to windows-2019 it works.

Regards

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

No Sorry.

### Repro steps

Create a pipeline for windows-latest
Include a build step using latest version.

**Comment by mikhailkoliada** [comment] 2022-03-21 11:40
@karepa Hello! thank you for the report!

Could you please provide a minimal workflow (better in public repo) to reproduce the issue?
Thank you!

**Comment by miketimofeev** [comment] 2022-03-23 15:55
@karepa I'm afraid reporting services are not available for VS2022 at the moment
https://docs.microsoft.com/en-us/sql/ssdt/download-sql-server-data-tools-ssdt?view=sql-server-ver15#changes-in-ssdt-for-visual-studio-2022
Please continue using windows-2019 with VS2019.
I'm going to close the issue. Feel free to contact us if you have any concerns.
Thank you!

**Closed by miketimofeev** 2022-03-23 15:55 UTC
Labels: OS: Windows, bug report

**Comment by arnoj** [comment] 2022-04-04 19:15
The extension for Visual Studio 2022 seems to be [available now](https://marketplace.visualstudio.com/items?itemName=ProBITools.MicrosoftReportProjectsforVisualStudio2022), Would it be possible to install the VSIX in the 2022 image as was done for 2019 please?

**Comment by al-cheb** [comment] 2022-04-04 19:25
@arnoj, Please create a separate issue to add this component on Windows Server 2022.

**Comment by arnoj** [comment] 2022-04-04 21:36
Requested in https://github.com/actions/virtual-environments/issues/5340.
