### ISSUE TITLE
Meson appears to do a mingw build in windows-2022?

### ISSUE THREAD

**Issue by njaard** [actions/virtual-environments#5159] opened 2022-03-01 19:38 UTC
### Description

My repository broke with the switch to Windows 2022.

After the switch, a package that is built with `meson` started to detect mingw and build with that?

In Windows 2022, [the build fails](https://github.com/njaard/libavif-rs/runs/5380094055) with this error:

```
  = note: msvcrt.lib(exe_main.obj) : warning LNK4078: multiple '.drectve' sections found with different attributes (00100A00)
          dav1d.lib(data.c.obj) : error LNK2019: unresolved external symbol __mingw_vfprintf referenced in function fprintf.constprop.0
          dav1d.lib(log.c.obj) : error LNK2001: unresolved external symbol __mingw_vfprintf
          dav1d.lib(picture.c.obj) : error LNK2001: unresolved external symbol __mingw_vfprintf
          dav1d.lib(lib.c.obj) : error LNK2001: unresolved external symbol __mingw_vfprintf
          dav1d.lib(looprestoration_tmpl.c.obj) : error LNK2001: unresolved external symbol ___chkstk_ms
          dav1d.lib(mc_tmpl.c.obj) : error LNK2001: unresolved external symbol ___chkstk_ms
          dav1d.lib(looprestoration_tmpl.c.obj) : error LNK2001: unresolved external symbol ___chkstk_ms
          dav1d.lib(mc_tmpl.c.obj) : error LNK2001: unresolved external symbol ___chkstk_ms
          dav1d.lib(fg_apply_tmpl.c.obj) : error LNK2001: unresolved external symbol ___chkstk_ms
          dav1d.lib(itx_tmpl.c.obj) : error LNK2001: unresolved external symbol ___chkstk_ms
          dav1d.lib(lf_mask.c.obj) : error LNK2001: unresolved external symbol ___chkstk_ms
          dav1d.lib(wedge.c.obj) : error LNK2001: unresolved external symbol ___chkstk_ms
          dav1d.lib(fg_apply_tmpl.c.obj) : error LNK2001: unresolved external symbol ___chkstk_ms
          dav1d.lib(itx_tmpl.c.obj) : error LNK2001: unresolved external symbol ___chkstk_ms
          D:\a\libavif-rs\libavif-rs\target\debug\deps\libdav1d_sys-6e9b938f2d3d6d02.exe : fatal error LNK1120: 2 unresolved externals
```

But I can fix it simply by using Windows 2019.

It seems that CL=cl isn't enough to fix Meson.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20220220.1

https://github.com/njaard/libavif-rs/runs/5378785911

### Is it regression?

https://github.com/njaard/libavif-rs/actions/runs/1918168833

### Repro steps

Build libdav1d on the Windows 2022 image.

**Comment by miketimofeev** [comment] 2022-03-17 17:07
Hi @njaard!
I believe the issue is related to VS2022. Have you tried to build libdav1d locally using VS2022?

**Comment by njaard** [comment] 2022-03-17 17:15
I don't have access to VS2022

**Comment by miketimofeev** [comment] 2022-03-21 13:43
@njaard you have a hardcoded path to the vcvars:
` call "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"`
for VS2022 it should be
` call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"`

**Comment by miketimofeev** [comment] 2022-04-11 14:19
@njaard I'm going to close the issue, feel free to contact us if you have any questions.
Thank you!

**Closed by miketimofeev** 2022-04-11 14:19 UTC
Labels: OS: Windows, Area: Common Tools, bug report
