### ISSUE TITLE
Homebrew no longer works on Mac OS Jobs

### ISSUE THREAD

**Issue by JasonGross** [actions/virtual-environments#1198] opened 2020-07-07 19:50 UTC
**Describe the bug**

I have the build job
```
name: CI (Coq, MacOS)

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:

    runs-on: macos-latest

    env:
      NJOBS: "2"
      COQ_VERSION: "master"

    # initial steps copied from https://github.com/coq/coq/blob/cfc41cb79e2364f19d97e7e5c94262132972b0b2/azure-pipelines.yml#L41-L110
    steps:
    - name: Install system dependencies
      run: |
        set -e
        brew update
        (cd $(brew --repository)/Library/Taps/homebrew/homebrew-core/ && git fetch --shallow-since=${HBCORE_DATE} && git checkout ${HBCORE_REF})
        brew install gnu-time opam pkg-config gtksourceview3 adwaita-icon-theme
        pip3 install macpack
      env:
        HOMEBREW_NO_AUTO_UPDATE: "1"
        HBCORE_DATE: "2019-09-03"
        HBCORE_REF: "44ee64cf4b9f2d2bf000758d356db0c77425e42e"
```

I get the error
```
==> Installing adwaita-icon-theme
==> Pouring adwaita-icon-theme-3.32.0.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/adwaita-icon-theme/3.32.0: 5,827 files, 22.6MB
Error: /usr/local/opt/ruby@2.6 is not a valid keg
```

See https://github.com/mit-plv/fiat-crypto/runs/846886316

**Area for Triage**: Apple

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [x] macOS 10.15

**Expected behavior**

It was working fine before without errors, but it started failing within the past couple of days.

**Actual behavior**
https://github.com/mit-plv/fiat-crypto/runs/846886316

**Comment by vmapetr** [comment] 2020-07-08 04:16
Hi @JasonGross !
I've checked previous [build](https://github.com/mit-plv/fiat-crypto/runs/842753770?check_suite_focus=true) from `columns-base-conversion` branch and it use the same image version - 20200625.2, as [failed](https://github.com/mit-plv/fiat-crypto/runs/846886316) one, but step `Install system dependencies` execute successfully, which mean they both were executed on the same image, with the same set of software.
Is there possibility that there is issue with some internal dependencies in your project?

**Comment by maxim-lobanov** [comment] 2020-07-08 04:47
Agree with @vmapetr , that is definitely not the image issue.

Minimal steps to reproduce:
It will fail:
```bash
brew update
(cd $(brew --repository)/Library/Taps/homebrew/homebrew-core/ && git fetch --shallow-since=2019-09-03 && git checkout 44ee64cf4b9f2d2bf000758d356db0c77425e42e)
brew install adwaita-icon-theme
```

It will pass:
```bash
brew update
brew install adwaita-icon-theme
```

Since you point to the old version of formula, probably some dependencies of `adwaita-icon-theme` are not valid anymore. I believe it is better to ask on forum related to this formula

**Comment by maxim-lobanov** [comment] 2020-07-14 09:26
Closing the issue since it is not related to image.
Please let me know if you have any objections

**Closed by maxim-lobanov** 2020-07-14 09:26 UTC
Labels: Area: Apple, OS: macOS, investigate
