### ISSUE TITLE
Yarn install process fails using windows-latest image

### ISSUE THREAD

**Issue by ajmasia** [actions/virtual-environments#2665] opened 2021-02-09 08:06 UTC
**Description**  
Since the windows-latest image has been updated, I get an error when building an electron app on windows related to a package install that needs to download binaries from AWS to recompile native modules using `node-gyp`. This error did not occur in previous versions of the image.

**Area for Triage**:  
JavaScript and Node.js

**Question, Bug, or Feature?**:  
It is possible that some of the changes in the development environment changes are producing this error since with the previous version of the image and even with the 2016 version it works perfectly. How could this be solved?

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Image version**
`windows-latest` Version: 10.0.17763 Build 1697
[virtual-environments/Windows2019-Readme.md at main · actions/virtual-environments](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md)

**Expected behavior**  
The affected package should compile normally and continue with the job process

**Actual behavior**  
`yarn install` process fails. You can see the logs here:
[5_yarn_install_log.txt](https://github.com/actions/virtual-environments/files/5949752/5_yarn_install_log.txt)

**Repro steps**  
You can test it using this test repo:
https://github.com/ajmasia/vue-electron-playground

**Comment by andy-mishechkin** [comment] 2021-02-11 11:51
Hello, @ajmasia 
I've made some investigation about your issue. The last Windows 2019 release has no any yarn changes, only Node version changes: 14.15.1 -> 14.15.4, but I don't think that it can affect your build. You can check all changes in PR: https://github.com/actions/virtual-environments/pull/2523/commits/6d4d75e7e86a12715cd888a787c2c1c25acd93df
Also I've forked your repository and tried to reproduce your build here:
https://github.com/andy-mishechkin/vue-electron-playground
I've tried to add the next code before `yarn install`:
        ```
  npm config set msvs_version 2015
  npm install --global --production windows-build-tools@4.0.0
```
After that `yarn install` step has been successful:
https://github.com/andy-mishechkin/vue-electron-playground/runs/1872289414?check_suite_focus=true
But in this case I've got the failed build of your application.
Btw, Windows Server 2016 image  contains the next Visual Studio component:
`Microsoft.VisualStudio.Component.Node.Build`, which doesn't contain in Windows Server 2019 image, because Visual Studio 2019 has no this component (https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-enterprise?view=vs-2019&preserve-view=true).
Did you really get the successful build in previous Windows Server 2019 images, or in Windows Server 2016 only ?
Thank you.

**Comment by ajmasia** [comment] 2021-02-11 12:15
Hi @AndreyMaslennikov,

It's true that in January we were using the windows-2019 version, but since it has been updated by Github it has stopped compiling well doing an error trying to download package binaries from AWS. Currently, we have had to migrate to the windows-2016 version, and works fine!

**Comment by ajmasia** [comment] 2021-02-11 12:37
Hi, @AndreyMaslennikov,

I [add](https://github.com/ajmasia/vue-electron-playground/commit/90cc98dc6a325ca481e49b8202bf9fdd45baad6f) a test workflow adding your recommended tools before `yarn install` and works fine using the `windows-latest` image. You can test here: [Add test workflow · ajmasia/vue-electron-playground@90cc98d](https://github.com/ajmasia/vue-electron-playground/actions/runs/557765764)

Is it possible that the error you get is due to a temporary problem with Github communications?

Thanks again!

**Comment by andy-mishechkin** [comment] 2021-02-11 12:51
Sounds good!
`Is it possible that the error you get is due to a temporary problem with Github communications?`
may be. To tell the truth I didn't check it twice.
Thanks for your response, @ajmasia 
I think, we can close this ticket.

Btw, me - @andy-mishechkin, @AndreyMaslennikov - my colleague :-)

**Closed** 2021-02-11 12:51 UTC
Labels: Area: JavaScript and Node.js, OS: Windows, investigate
