### ISSUE TITLE
Networking is Flaky on GitHub Hosted Runners

### ISSUE THREAD

**Issue by iamrecursion** [actions/virtual-environments#1187] opened 2020-07-07 08:22 UTC
**Describe the bug**
Situations that require networking, such as downloading a file using `curl` or running tests that utilise localhost, are proving to be very flaky, with spurious timeouts occurring often.

**Area for Triage**: 
Servers

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [x] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**
Networking behaviour should be consistent, and not cause spurious test failures due to timeouts that are impossible to reproduce on a non-CI machine.

**Actual behavior**
As the issue is _flakiness_, it is difficult to provide a consistent reproduction. The issues primarily occur with the [Engine CI](https://github.com/enso-org/enso/actions?query=workflow%3A%22Engine+CI%22) in the [Enso](https://github.com/enso-org/enso/) repository, and manifest as spurious test failures, or failures to download things using `curl`, and the like. 

1. Execute the workflow.
2. Wait for a failure to happen. 

Virtually all of the failures (e.g. [this one](https://github.com/enso-org/enso/runs/835153517?check_suite_focus=true)) are spurious and seem to occur due to networking timeouts.

**Comment by dsame** [comment] 2020-07-09 02:38
We tried to reproduce the problem from few data centres of Azure and Digital Ocean in different regions and none of the confirmed the network issues by agent itself, but the destination `piccolo.link` might have the bandwidth limited.

To diagnose the exact problem please add `tracepath piccolo.link` (on ubuntu) to a shell task and provide the output of it to your Internet/hosting provider.

**Comment by iamrecursion** [comment] 2020-07-13 08:53
We only very rarely see a failure due to that link. Primarily we are seeing failures for connections using `localhost` where they time out.

**Comment by dsame** [comment] 2020-07-28 09:12
Can you please provide exact URLs which time out?
And still can you add a task with `tracepath localhost` and provide a log? Looks like a DNS problem that leads to incorrect name resolving. tracepath can help to detect this situation in your build

**Comment by dsame** [comment] 2020-08-05 15:32
We do not have the response for a long time and closing the issue.

@iamrecursion please open new issue or reopen this one in case if you still have the problem

**Comment by iamrecursion** [comment] 2020-08-06 08:40
Sorry, I never saw the reply 9 days ago. 

- I can't provide URLs as they're randomly generated on `localhost`. The tests are talking to a local server.
- Logs as follows for Ubuntu. `tracepath` doesn't seem to exist on the macOS and Windows runners where the problems tend to occur.

<details>
<summary>Ubuntu Runner</summary>

```text
 1?: [LOCALHOST]                        0.006ms pmtu 65536
 1:  localhost                                             0.159ms reached
 1:  localhost                                             0.032ms reached
     Resume: pmtu 65536 hops 1 back 1 
```

</details>

**Comment by iamrecursion** [comment] 2020-08-06 08:41
I can't seem to actively re-open this.

**Comment by dsame** [comment] 2020-08-10 06:11
In order to make sure the problem is with networking and not with the local service, please add

`time ping -o localhost` on ubuntu and osx before running the test and send the build logs to us. 

Actually having the same issue on all 3 runners shows the problem with the local server itself rather than with network insrastructure.

**Comment by iamrecursion** [comment] 2020-08-10 12:31
Quite possibly, yes, but it occurs far more often during periods that I could expect the actions machines to be under heavier load.

Do you still want the time stats?

**Comment by dsame** [comment] 2020-08-14 15:11
Do you notice the total build duration increases as well? Can you send the success and failed logs?

**Comment by iamrecursion** [comment] 2020-08-17 09:23
The total build duration doesn't seem to increase, not noticeably in any case. Please find logs attached from a successul and failing run on ubuntu.

[logs_failure_ubuntu-latest.zip](https://github.com/actions/virtual-environments/files/5083355/logs_failure_ubuntu-latest.zip)
[logs_success_ubuntu-latest.zip](https://github.com/actions/virtual-environments/files/5083356/logs_success_ubuntu-latest.zip)

**Comment by Darleev** [comment] 2020-08-24 15:43
Hello @iamrecursion,
As far as I see, currently Ubuntu "Engine CI" runs work fine. It seems one of the latest Ubuntu updates did the trick.
However, your pipeline was affected by the issue [described here](https://github.com/actions/virtual-environments/issues/1437).
Is the issue still actual?

**Comment by iamrecursion** [comment] 2020-08-25 09:34
Yes, the issue is still present, especially on windows. Please find windows logs attached.

[windows_falure.zip](https://github.com/actions/virtual-environments/files/5122831/windows_falure.zip)
[windows_success.zip](https://github.com/actions/virtual-environments/files/5122837/windows_success.zip)

**Comment by LouisCAD** [comment] 2020-08-28 07:28
I'm also encountering network flakiness with timeouts. It happens at almost every run.
Here's a workflow run where you can search for "failed" and see the error happens several time despite a logic to retry twice after first failure: https://github.com/LouisCAD/Splitties/runs/948101638?check_suite_focus=true

**Comment by Darleev** [comment] 2020-09-01 10:44
@LouisCAD as far as I see there was a temporary issue and not everything looks good. Am I correct?
@iamrecursion I have checked current failures for github actions jobs and It seems network issue is not actual anymore. Could you please confirm this?

**Comment by LouisCAD** [comment] 2020-09-01 10:47
@Darleev Last time it happened to me was 2-3 days ago, but the action has been erased as I retried it and there's no history of failures for now in GitHub Actions.

Yesterday, I didn't encounter network issues. I'll comment back here if it surfaces again, but it seems it's no longer reproducing.

**Comment by LouisCAD** [comment] 2020-09-02 00:41
@Darleev It looks like it keeps happening:
![Screenshot 2020-09-02 at 02 38 53](https://user-images.githubusercontent.com/6975237/91919259-97571300-ecc5-11ea-936b-aa758d272c68.png)

For the run that I used for the screenshot, the failure happened on both Windows and macOS.

**Comment by LeonidLapshin** [comment] 2020-09-03 20:23
Hi,@LouisCAD, @iamrecursion,
It seems that your problem can be tied with network offloading, that is turned on by default.
Could you please try to disable TCP/UDP offload before build, it can be done literally with one-line:
`
sudo ethtool -K eth0 tx off rx off
`
Reloading/restarts are not required, performance should not be affected.
Thank you, we are looking forward to your reply.

**Comment by LouisCAD** [comment] 2020-09-04 08:37
@LeonidLapshin Is that command Linux-only? I had timeouts happen on macOS runners too. Also, does Windows have something similar that'd need to be disabled with another command?

**Comment by LeonidLapshin** [comment] 2020-09-04 20:24
Hey, @LouisCAD!

Yes, you right, the ethtool is availible on Ubuntu, but not on MacOS

On Windows the proper command (powershell) is :
`Disable-NetAdapterChecksumOffload -Name * -TcpIPv4 -UdpIPv4 -TcpIPv6 -UdpIPv6`

For now I can not provide the way to change these settings in runtime on MacOS, but I'll definetly try to find the solution.
Could you please test Windows/Ubuntu scenarios?

**Comment by LouisCAD** [comment] 2020-09-05 11:30
@LeonidLapshin I can try for the next time I release a dev or stable version of that affected project, but it's much less likely to show any difference since I didn't witness these timeouts on Windows or Linux in the first place, which is expectable since they have significantly less upload work to do than the job running on macOS.

I'd be best to test with the corresponding setting on macOS to see if there's any difference for the next development versions releases that trigger a lot of uploads.

**Comment by iamrecursion** [comment] 2020-09-07 09:27
We also see the instability on macOS, but less often than on Windows. Configuring this for Windows and Linux _seems_ to have reduced the incidence of the network-related failures significantly. I'll be keeping an eye on it, but at least initially it seems to have helped!

I'm definitely interested in an equivalent setting for macOS.

**Comment by LouisCAD** [comment] 2020-09-14 05:47
For reference, here's another of the several/many occurences of the issue on macOS runners:

`> api.bintray.com:443 failed to respond`

https://github.com/LouisCAD/Splitties/runs/1110382235?check_suite_focus=true

**Comment by LeonidLapshin** [comment] 2020-09-21 15:35
@LouisCAD @iamrecursion 
The proper way of disabling tcp-udp offload on macOS runners is
```
sudo sysctl -w net.link.generic.system.hwcksum_tx=0
sudo sysctl -w net.link.generic.system.hwcksum_rx=0
```
If you can, please add these properties at the start of build, it will disable rx/tx hardware offloading in runtime.
Thank you!

**Comment by iamrecursion** [comment] 2020-09-22 08:09
Fingers crossed this should help with the remaining problems we've having on macOS!

**Comment by LeonidLapshin** [comment] 2020-10-06 08:32
Hey, @LouisCAD @iamrecursion
I'll close the issue, but if the problem persist, feel free to open a new one :)

**Closed by LeonidLapshin** 2020-10-06 08:32 UTC
Labels: Area: Image administration, investigate

**Comment by kethan1** [comment] 2021-02-12 23:05
I was having problems with macOS network problems using this (as mentioned above):
```
sudo sysctl -w net.link.generic.system.hwcksum_tx=0
sudo sysctl -w net.link.generic.system.hwcksum_rx=0
```

And these stackoverflow questions (for yarn and npm), https://stackoverflow.com/questions/51508364/yarn-there-appears-to-be-trouble-with-your-network-connection-retrying, https://stackoverflow.com/questions/39830049/npm-timeout-on-install-while-overseas I could get it working

**Comment by ssbarnea** [comment] 2022-05-03 16:34
It would really be useful to get some feedback from VE team if this workaround is still needed or not for macos.

**Comment by smorimoto** [comment] 2023-04-17 16:07
Hope this helps someone: https://github.com/smorimoto/tune-github-hosted-runner-network
