### ISSUE TITLE
Tests Succeed Locally but not on GitHub Actions

### ISSUE THREAD

**Issue by hentai-chan** [actions/virtual-environments#3722] opened 2021-07-13 10:00 UTC
### Description

The `anonfile` package has a set of 4 functions in a test suite that pass locally but not on GitHub Actions. I am not sure what to make out of it, since *"the existence of the 503 status code does not imply that a server must use it when becoming overloaded. Some servers may wish simply refuse the connection."* This could very well be an anonfile-specific problem but I'd like to have someone else confirm this theory. 

Related issues:
- https://github.com/actions/virtual-environments/issues/531
- https://github.com/actions/virtual-environments/issues/2778

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Image version and build link

https://github.com/nstrydom2/anonfile-api/actions/runs/930076854

### Expected behavior

All tests should run successfully. 

### Actual behavior

Some test fail only on GitHub Actions. I provided more context to this issue [here](https://github.com/nstrydom2/anonfile-api/pull/50).

### Repro steps

1. checkout branch `issue-48`
2. run tests with `pytest --verbose -s` (after installing `anonfile` in a virtual environment)

**Comment by miketimofeev** [comment] 2021-07-13 10:49
Hi @hentai-chan!
Am I right that the last failure was 27 days ago? I'll try to run a few checks in a loop on hosted VMs to see if it's on a regular basis or not. Most likely the issue is not related to the hosted environment.

**Comment by hentai-chan** [comment] 2021-07-13 11:00
Yes, you're right. I don't see a "Re-run jobs" button in the GitHub Actions tab (maybe because I am not the maintainer of the project?). I didn't make any changes in the past few weeks because I was kinda stuck on this problem.

**Comment by miketimofeev** [comment] 2021-07-13 11:03
Yes, maintainers should have such a button, could you ask them to re-run the check in the meantime?
![image](https://user-images.githubusercontent.com/48208649/125441134-294de76e-5b3f-42ab-9b99-17fccf9c27a7.png)

**Comment by hentai-chan** [comment] 2021-07-13 11:05
I'm on it!

**Comment by miketimofeev** [comment] 2021-07-13 15:52
@hentai-chan we've investigated the issue and it seems that the root cause is in the https://anonfiles.com/. All azure VMs (macOS, windows, Ubuntu) returns 503 for this domain name and even locally I'm not able to open the website. Nothing we can do here, unfortunately. Please consider using a self-hosted agent or contact anonfiles.com support.
I'm going to close the issue. Feel free to contact us if you have any concerns.
Thank you!

**Closed by miketimofeev** 2021-07-13 15:52 UTC
Labels: Area: Deployment / Release, OS: Ubuntu, investigate

**Comment by hentai-chan** [comment] 2021-07-13 21:23
Thanks so much for your help. I sent a message to the website admin, hopefully we will be able to clear things out that way. That you're not able to visit the website in a browser is a little concerning though because that means that some regions are blocked from accessing this site. This is an very important insight for future troubleshooting!

**Comment by maxim-lobanov** [comment] 2021-07-14 04:08
@hentai-chan , jfyi - I don't have an access to the https://anonfiles.com/ too from my local machine
