### ISSUE TITLE
[linux] maven install broke

### ISSUE THREAD

**Issue by HUMBERP** [actions/virtual-environments#4503] opened 2021-11-15 07:15 UTC
### Description

Since the maven github tag list returns latest version 3.8.4, but on the constructed maven downloadurl only version 3.8.3 is available the install fails with 404 not found.

```
    vhd: Downloading 'https://www-eu.apache.org/dist/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.zip' to '/tmp/maven.zip'...
    vhd: Error — Either HTTP response code for 'https://www-eu.apache.org/dist/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.zip' is wrong - '404' or exit code is not 0 - '0'. Waiting 30 seconds before the next attempt, 19 attempts left

```

Would it be better to get the "mavenDownloadUrl" by selecting the zipball_url value?

mavenDownloadUrl=$(echo $json | jq -r '.[1] | .zipball_url') 

### Virtual environments affected

- [X] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Date: Fri Nov 12 21:43:33 2021 +0300; Commit: 6dc8234648564472f721007db2336b03cec1b8a1 - [macOS] Remove node version 10.x (#4477); Author: Mikhail Koliada <88318005+mikhailkoliada@users.noreply.github.com>

### Expected behavior

maven will unzip latest version (3.8.4) 

### Actual behavior

maven binary 3.8.4 not found

### Repro steps

Run the packer virtual-environments process for ubuntu20.04

Used the following commit

Date: Fri Nov 12 21:43:33 2021 +0300; Commit: 6dc8234648564472f721007db2336b03cec1b8a1

**Comment by mikhailkoliada** [comment] 2021-11-15 08:20
@HUMBERP Hello!

The problem is that zipball does not have the binary we are installing, only sources

**Comment by HUMBERP** [comment] 2021-11-15 09:16
Ok, what about to use

curl -s "http://dlcdn.apache.org/maven/maven-3/"

and extract the latest version from the returned xml structure?

**Comment by miketimofeev** [comment] 2021-11-15 12:11
@HUMBERP we have decided to stick to the exact version and update the toolset file manually. The changes are merged and the main branch should work now.

**Closed** 2021-11-15 12:22 UTC
Labels: Area: Java
