### ISSUE TITLE
Windows image 20200820.1 missing .Net Core SDK 3.1.401 in cache

### ISSUE THREAD

**Issue by steine** [actions/virtual-environments#1502] opened 2020-08-27 15:14 UTC
**Description**  
Pipeline warns:
```Since you just installed the .NET Core SDK, you will need to reopen the Command Prompt window before running the tool you installed.```
When installing global dotnet tool, in my case `dotnet-ef`.

This makes the pipeline fail from not finding the global tool.

***Getting around the issue***
Using the UseDotNetTask will install the SDK again, but also restart the Command Prompt, allowing us to find and use the global tool.

UseDotNetTask points to that the 3.1.401 SDK is not existing in the cache and is downloaded and installed, even though the SDK is installed and can be used for build tasks prior. 

Excerpt from UseDotNetTask, saying that the SDK is not present in cache:
```Starting: Use .NET Core sdk
==============================================================================
Task         : Use .NET Core
Description  : Acquires a specific version of the .NET Core SDK from the internet or the local cache and adds it to the PATH. Use this task to change the version of .NET Core used in subsequent tasks. Additionally provides proxy support.
Version      : 2.171.1
Author       : Microsoft Corporation
Help         : https://aka.ms/AA4xgy0
==============================================================================
Tool to install: .NET Core sdk version 3.1.x.
Found version 3.1.401 in channel 3.1 for user specified version spec: 3.1.x
Version 3.1.401 was not found in cache.
Getting URL to download .NET Core sdk version: 3.1.401.
```

**Area for Triage**:  
.NET Core

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**  
```Installing version undefined of dotnet-ef as global tool.
"C:\Program Files\dotnet\dotnet.exe" tool install --global dotnet-ef
You can invoke the tool using the following command: dotnet-ef
Tool 'dotnet-ef' (version '3.1.7') was successfully installed.
```

**Actual behavior**  
```Installing version undefined of dotnet-ef as global tool.
"C:\Program Files\dotnet\dotnet.exe" tool install --global dotnet-ef
Since you just installed the .NET Core SDK, you will need to reopen the Command Prompt window before running the tool you installed.
You can invoke the tool using the following command: dotnet-ef
Tool 'dotnet-ef' (version '3.1.7') was successfully installed.
```

**Repro steps**  
1. DevOps pipeline with a global dotnet tool install
2. Use tool

**Comment by MaksimZhukov** [comment] 2020-08-31 12:44
Hello @steine , thank you for the report!
Currently the `Use .NET Core` task download and install the SDK even if it is already installed on machine, this is expected behavior. There is [a similar issue](https://github.com/microsoft/azure-pipelines-tasks/issues/11694) in the `microsoft/azure-pipelines-tasks` repository. It looks like they are planning to change this behavior in the future. You can find more context in [this issue](https://github.com/microsoft/azure-pipelines-tasks/issues/10405).

I'm closing this issue. Please let us know if you have any questions.

**Comment by steine** [comment] 2020-08-31 13:32
Hi @MaksimZhukov, thanks for the quick response.

My issue is not with the `Use .NET Core` but with the image itself.
The comment about `Use .NET Core` is how I solved it for our pipeline.

Previous images worked out of the box when needing, in my case, `dotnet-ef` as a global tool, it installed the tool and could use it at once.

This image says it needs to "restart the terminal", which indicates to me that the image is not setup completely.

BR
//Anders

**Comment by MaksimZhukov** [comment] 2020-08-31 16:31
Thank you for updating the issue description!

We could not reproduce this issue on our side. I have tried to reproduce it on the Windows2019 using SDK Version `3.1.401` with the following commands:
```
dotnet tool install --global dotnet-ef
```
and
```
cd "C:\Program Files\dotnet"
./dotnet.exe tool install --global dotnet-ef
```
All builds were successful and had the following output in logs:
```
You can invoke the tool using the following command: dotnet-ef
Tool 'dotnet-ef' (version '3.1.7') was successfully installed.
```
Could you please provide repro steps or a link to the public build where the issue occurs?

**Comment by steine** [comment] 2020-09-01 07:31
I reverted to the old `azure-pipelines.yml` where we were not using the `UseDotNetTask` "fix" and it no longer fails.
There's no difference in the way our pipeline is setup or used now to how it was setup and used before.

I'll close this issue, thanks for your investigation time.

BR

**Comment by rsemenov** [comment] 2020-09-15 19:38
@steine , I am investigating a similar issue reported by another customer. Could you help us with the following? If you still have a history, do you see a correlation between the `Since you just installed the .NET Core SDK...` message and the prefix of the Agent machine name "WIN-" or "fv-"? Thanks!

**Comment by steine** [comment] 2020-09-16 05:59
@rsemenov ,
We actually ran into this problem again and added the `UseDotNetTask` to reinstall the SDK.

No correlation from what I can see, we have only "WIN-" machines.

BR

Worked, 4 Sept:
```
Agent machine name: 'WIN-M4T1U3TMVLA'
Current agent version: '2.174.1'
Current image version: '20200827.1'
```
Failed, 4 Sept:
```
Agent machine name: 'WIN-AG6N9VURTGL'
Current agent version: '2.174.1'
Current image version: '20200827.1'
```

Failed, 7 Sept:
```
Agent machine name: 'WIN-M4T1U3TMVLA'
Current agent version: '2.174.1'
Current image version: '20200827.1'
```

After this one we reverted to use the extra task again.

**Comment by maxim-lobanov** [comment] 2020-09-16 13:30
Reopened since we have repro for this issue and we will work to fix it

**Comment by rsemenov** [comment] 2020-09-16 13:50
@steine, thanks! We root caused the issue. Sometimes PATH doesn't contain `%USERPROFILE%\.dotnet\tools` due to the timing issue with logon tasks. We will be working on a fix, as a workaround, you can manually make sure that `%USERPROFILE%\.dotnet\tools` is in the PATH before running `dotnet tool install `

**Comment by al-cheb** [comment] 2020-10-08 11:09
Looks like fix has been deployed. Feel free to open the thread if you have any concerns.

**Closed by al-cheb** 2020-10-08 11:09 UTC
Labels: OS: Windows, investigate
