### ISSUE TITLE
Upload images to Azure Marketplace

### ISSUE THREAD

**Issue by srrl** [actions/virtual-environments#176] opened 2019-12-18 04:06 UTC
We are actively using self-hosted Azure PIpelines agents with a slightly modified version of these images. It would be really great to have these images in Azure Marketplace. This will save us lots of time that we currently have to spend on building these images from scratch.

**Comment by dmitryserbin** [comment] 2020-01-23 02:06
+1 we also need this feature!

**Comment by Beffyman** [comment] 2020-01-30 03:48
It's quite often that I find myself wanting an image like this, but with a larger VM size due to certain workloads needing more than 2 cores.  Especially since https://hub.docker.com/_/microsoft-azure-pipelines-vsts-agent is deprecated now in favor of this repo, but without the images it used to publish publicly.

**Comment by jemag** [comment] 2020-03-11 20:25
We also had images based on the https://hub.docker.com/_/microsoft-azure-pipelines-vsts-agent to use as self-hosted agents on our AKS cluster. Not having these images published to dockerhub anymore is quite a bummer for us.

Are there any plans to publish images again?

**Comment by rattek** [comment] 2020-03-12 12:22
We are also basing ourself on the microsoft-azure-pipeline-vsts-agent image and built our own with a subset of dependencies to reduce the ressource needed to self hosted agents on our AKS as well. It would be suitable for us to continue accessing this base image and append our mandatory dependencies on top of it. So for us, the Marketplace scenario is good but dockerhub would be perfect

**Comment by DanBrown-TechSmith** [comment] 2020-03-13 22:15
This would also make these images useful to [Azure Image Builder](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/image-builder-overview?toc=/azure/virtual-machines/windows/toc.json&bc=/azure/virtual-machines/windows/breadcrumb/toc.json)

**Comment by Rzpeg** [comment] 2020-03-17 23:30
I would really appreciate a downloadable pre-built windows container as well.

**Comment by alepauly** [comment] 2020-04-13 21:57
Unfortunately we can't share these images via the gallery due to legal issues so I'm closing this 😞 . But rest assured that this is a topic we often bring up to see if there's anyway to get it done.

**Closed by alepauly** 2020-04-13 21:57 UTC
Labels: Area: Image administration, enhancement

**Comment by jemag** [comment] 2020-04-13 22:19
@alepauly I am a bit confused as to why there would be legal issues since such images have been shared on docker hub for quite a long time and are, technically, still being shared there (although not updated anymore).

Are the legal issues only related to the Azure Marketplace platform and not docker hub? If so, would it be better to create another issue explicitly for docker hub?

**Comment by alepauly** [comment] 2020-04-28 14:22
Hi @jemag, the legal issues are due to the software included in the image and in part the reason why the docker hub image is not updated any longer.

**Comment by chriskilding** [comment] 2021-11-09 11:59
This issue is frequently cited as the reason a number of related issues can't be addressed. Unfortunately the reasoning is quite vague at the moment: "the legal issues are due to the software included in the image" doesn't tell us much. Please could someone from GitHub clarify what exactly the legal problems are with publishing official runner images? I.e. which software components in the images are the cause of this, and why.

**Comment by KuSh** [comment] 2021-11-27 11:40
At least Android Studio and NDK licences prevent redistribution. That could also be the case for Chrome and perhaps for MS SQL tooling (licences are unclear)

**Comment by aledeniz** [comment] 2022-05-09 11:25
@KuSh an chance we could get on the Marketplace a set of images without the problematically licensed software?

**Comment by KuSh** [comment] 2022-05-09 13:30
> @KuSh any chance we could get on the Marketplace a set of images without the problematically licensed software?

I'm not an insider. It certainly doable.
