### ISSUE TITLE
Invalid kcpassword on macOS

### ISSUE THREAD

**Issue by t0rr3sp3dr0** [actions/virtual-environments#5231] opened 2022-03-15 07:15 UTC
### Description

The /etc/kcpassword file on macOS Runners is invalid. It is a 54-byte file, but its size should be a multiple of 11, and trying to decode it doesn’t result on a valid password for user runner.

I believe this was introduced on #5153. If you run the old Python script and the new Bash one, you can check the output differ. The newer script produces an output similar to the expected, but adds or looses bytes depending on the input. More specifically, it looses bytes when it XORs a char with the key and it results in `\0` or `\n` and it adds bytes by padding the string too much.

### Example 1
Raw Input: `wVI=`
Base64 Output:
 - python: `Ct8bHtK83eqjuR8=` (11B decoded, 👍)
 - bash: `3xse0rzd6qO5H30=` (11B decoded, 👎 missing first byte + last byte is garbage)

### Example 2
Raw Input: `}_R#`
Base64 Output:
 - python: `ANYAANK83eqjuR8=` (11B decoded, 👍)
 - bash: `1tK83eqjuR99` (9B decoded, 👎 missing first, third, and fourth bytes + last byte is garbage)

### Example 3
Raw Input: `00000000000`
Base64 Output:
 - python: `BOcfHtK83eqjuR8=` (11B decoded, 👍)
 - bash: `BOcfHtK83eqjuR99` (12B decoded, 👎 last byte is garbage)

### Example 4
Raw Input: `111111111111`
Base64 Output:
 - python: `TLhjEuON7NuSiC5MiVIj0rzd6qO5Hw==` (22B decoded, 👍)
 - bash: `TLhjEuON7NuSiC5MiVIj0rzd6qO5H32J` (24B decoded, 👎 last 2 bytes are garbage)

Given the size of the file inside the runner, I think somehow the garbage bytes are being stripped from the file, but some byte is still being lost when the script is generates kcpassword.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20220307.1

### Is it regression?

Yes

### Expected behavior

kcpassword must be a file with size multiple of 11 and it should contain the password for the user runner when decoded.

### Actual behavior

kcpassword is not valid.

### Repro steps

Check kcpassword size:
```bash
ls -lha /etc/kcpassword
```

Get the password of runner:
```bash
sudo ruby -e 'key = [125, 137, 82, 35, 210, 188, 221, 234, 163, 185, 31]; IO.read("/etc/kcpassword").bytes.each_with_index { |b, i| e = b ^ key[i % key.size]; break if e == 0; print [e].pack("U*") }' > pass
```

Try using the password of runner:
```bash
sudo sysadminctl -resetPasswordFor "${USER}" -newPassword "${USER}" -adminUser "${USER}" -adminPassword "$(cat pass)"
```

**Comment by maxim-lobanov** [comment] 2022-03-15 11:45
Hey @t0rr3sp3dr0 , thank you for your report!

I don't think that it is related to https://github.com/actions/virtual-environments/pull/5153 because new script is not used somewhere yet (anka/Service.Helpers.psm1 is not used in production images yet).
I think the root cause is https://github.com/actions/virtual-environments/pull/5115 where we switched kcpassword.py script from Python 2 to Python 3. I have confirmed locally that that script produces different output for Python 2 & 3. We will take a look deeper

**Comment by maxim-lobanov** [comment] 2022-03-15 12:47
@t0rr3sp3dr0 , Yes, root cause is migrating from Python 2 to 3 and `chr` python function that works differently. 
This PR should fix an issue: https://github.com/actions/virtual-environments/pull/5234
I will try to find some Python experts to review it before merging because I don't have much experience with this language. Feel free to review fi you have.

**Comment by t0rr3sp3dr0** [comment] 2022-03-15 22:33
Hey @maxim-lobanov, you are right. I didn’t notice that Python 2 and 3 produced different outputs. On Python 3, the output was being encoded in UTF-8 instead of being treated as raw bytes when writing it to /etc/kcpassword.

**Comment by t0rr3sp3dr0** [comment] 2022-03-15 22:35
In case someone else is wondering if is possible to fix kcpassword before the fix is pushed to production, I created a simple script the does exactly that:

```python
#!/usr/bin/env python3
import sys

if __name__ == '__main__':
    with open('/etc/kcpassword', 'rb') as f:
        kcpassword = f.read()
    
    kcpassword = kcpassword.decode('utf-8').encode('raw_unicode_escape')
    sys.stdout.buffer.write(kcpassword)
```

So you can recover the password for the runner user by executing:

```bash
sudo python3 -c 'import sys; sys.stdout.buffer.write(open("/etc/kcpassword", "rb").read().decode("utf-8").encode("raw_unicode_escape"))' > kcpassword

ruby -e 'key = [125, 137, 82, 35, 210, 188, 221, 234, 163, 185, 31]; IO.read("/dev/stdin").bytes.each_with_index { |b, i| e = b ^ key[i % key.size]; break if e == 0; print [e].pack("U*") }' < kcpassword > password.txt

cat password.txt
```

**Comment by maxim-lobanov** [comment] 2022-03-16 10:24
Thank you for providing workaround!
PR with fix is merged. I am expecting all images to be updated with the fix by Tue / Wed next week.

**Comment by maxim-lobanov** [comment] 2022-03-16 11:14
As I mentioned earlier, https://github.com/actions/virtual-environments/pull/5153 is not used in production yet but cc @al-cheb to fix it too later

**Comment by al-cheb** [comment] 2022-04-15 07:32
@t0rr3sp3dr0 , Thank you. Fixed.

**Closed by al-cheb** 2022-04-15 07:32 UTC
Labels: bug report
