### ISSUE TITLE
Chained reusable workflows fails with internal error

### ISSUE THREAD

**Issue by nefilim** [actions/virtual-environments#4823] opened 2022-01-01 17:06 UTC
### Description

When calling a reusable workflow with an output and then feeding than input into another reusable workflow, it fails to start the second workflow with an internal error. 

If the first workflow is copied into the outer workflow verbatim it works without problem. 

Failed run: https://github.com/nefilim/github-actions-problems/actions/runs/1643952392
Nested successful run: https://github.com/nefilim/github-actions-problems/actions/runs/1643951275

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Failed run: https://github.com/nefilim/github-actions-problems/actions/runs/1643952392
Nested successful run: https://github.com/nefilim/github-actions-problems/actions/runs/1643951275

### Repro steps

Start flow "DUMMY nested Release and Publish"

**Comment by shilovmaksim** [comment] 2022-01-06 05:51
Hi @nefilim .
Could you please make sure that output and the input values type are match. Otherwise calling reusable workflow will fail with internal error.

Docs reference:
- [#using-inputs-and-secrets-in-a-reusable-workflow](https://docs.github.com/en/actions/learn-github-actions/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow)
- > Pass the input or secret from the caller workflow.
To pass named inputs to a called workflow, use the with keyword in a job. Use the secrets keyword to pass named secrets. For inputs, the data type of the input value must match the type specified in the called workflow (either boolean, number, or string).

**Comment by nefilim** [comment] 2022-01-06 13:21
Hi @shilovmaksim - did you look at the very simple reproducing project I shared? It’s all strings as far as I know…

**Comment by shilovmaksim** [comment] 2022-01-10 09:21
Hi @nefilim .
I checked your repro repo. Your [dummy-release-and-publish.yaml](https://github.com/nefilim/github-actions-problems/blob/main/.github/workflows/dummy-release-and-publish.yaml) workflow fails even with a single job that calling reusable [dummy-release.yaml](https://github.com/nefilim/github-actions-problems/blob/main/.github/workflows/dummy-release.yaml). - example run: https://github.com/shilovmaksim/github-actions-problems/actions/runs/1676550065

I suspect that the problem is with how concurrency set up. [dummy-release-and-publish.yaml](https://github.com/nefilim/github-actions-problems/blob/main/.github/workflows/dummy-release-and-publish.yaml) workflow works fine with concurrency removed: example run - https://github.com/shilovmaksim/github-actions-problems/runs/4759083713?check_suite_focus=true

I'm going to close this issue since it is not related to the images that workflows running on.
If you have any further questions you can ask it on https://github.community/

**Closed by shilovmaksim** 2022-01-10 09:21 UTC
Labels: Area: Common Tools, investigate
