### ISSUE TITLE
Update Azure CLI

### ISSUE THREAD

**Issue by adeliab** [actions/virtual-environments#3556] opened 2021-06-09 12:07 UTC
**Tool information**
- Tool name: Azure CLI
- Add or update? Update
- Desired version: 2.24.1
- Azure CLI 2.24 that is used by the win2016 images from 20210525.0 causes a bug where webapp config appsettings set command causing all values to default to "false". According to their release note, v 2.24.1 has a hotfix to fix this issue https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?tabs=azure-cli#june-01-2021

**Area for Triage**:
Scripting and command line

**Question, Bug, or Feature?**:
Bug

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [x] Windows Server 2016 R2
- [ ] Windows Server 2019

**Comment by miketimofeev** [comment] 2021-06-09 12:20
Hi @adeliab!
I'm going to close this as a duplicate of https://github.com/actions/virtual-environments/issues/3508
Please feel free to contact us if you have any concerns.
Thank you!

**Closed by miketimofeev** 2021-06-09 12:20 UTC
Labels: feature request, needs triage
