### ISSUE TITLE
Gulp-typescript out of memory error

### ISSUE THREAD

**Issue by skhilliard** [actions/virtual-environments#4649] opened 2021-12-01 22:32 UTC
### Description

I recently tried to update an package for my Node.js project (mongoose 5.13.13 from 5.12.8), and it seems to have pushed me over the edge for memory during the typescript compilation phase (using gulp-typescript 5.0.1). Here is the error I see...

[18:24:13] Starting 'node_ts'...

<--- Last few GCs --->

[480:0x58548e0] 225969 ms: Mark-sweep (reduce) 2040.9 (2051.1) -> 2039.9 (2051.8) MB, 2662.0 / 0.0 ms (average mu = 0.095, current mu = 0.003) allocation failure scavenge might not succeed
[480:0x58548e0] 225977 ms: Scavenge (reduce) 2040.9 (2050.8) -> 2040.0 (2051.8) MB, 2.9 / 0.0 ms (average mu = 0.095, current mu = 0.003) allocation failure

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
1: 0xa389b0 node::Abort() [gulp default --semVer=21.11.0.72]
2: 0x96e0af node::FatalError(char const*, char const*) [gulp default --semVer=21.11.0.72]
3: 0xbb7a4e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [gulp default --semVer=21.11.0.72]
4: 0xbb7dc7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [gulp default --semVer=21.11.0.72]
5: 0xd73fd5 [gulp default --semVer=21.11.0.72]
6: 0xd74b5f [gulp default --semVer=21.11.0.72]
7: 0xd8299b v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [gulp default --semVer=21.11.0.72]
8: 0xd8655c v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [gulp default --semVer=21.11.0.72]
9: 0xd54c3b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [gulp default --semVer=21.11.0.72]
10: 0x109d21f v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [gulp default --semVer=21.11.0.72]
11: 0x1446379 [gulp default --semVer=21.11.0.72]
Aborted (core dumped)
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! evolved@1.0.0 build-prod: gulp default "--semVer=21.11.0.72"

I am sure this is newbie question, but do I have options to increase available memory? From what I understand this docker image has 6 GB of physical memory and 13 GB of total memory.

Any suggestions or advice would be greatly appreciated.

Thanks,
Kelly

### Virtual environments affected

- [X] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Environment: ubuntu-18.04
Version: 20211129.1

### Actual behavior

Build runs out of memory (see description)

### Repro steps

[SampleCode.zip](https://github.com/actions/virtual-environments/files/7637506/SampleCode.zip)

In the ZIP file are two folders...testbefore uses mongoose v5.12.8.  testafter uses mongoose v5.13.13.  

You can see the dramatic difference in memory usage by running a local build in VSCode.  Navigate to the service folder, run npm ci to install the packages, and then run 'npm run build'.  You can look at the memory usage of node.exe and see that the amount of memory used in the after version is dramatically higher.

**Comment by shilovmaksim** [comment] 2021-12-02 09:03
Hi @skhilliard . Thank you for your report. We will take a look. Could you please provide minimal workflow or slightly more detailed repro steps to help us with the investigation process.

**Comment by skhilliard** [comment] 2021-12-02 20:01
@shilovmaksim I will do my best, but since this a build issue, it'll be a little challenging.  Here are some instructions for doing a build locally using VSCode (this demonstrates the wildly increased memory usage during a build)...

#node.js
NVM for windows can be used to manage node.js versions on your system.
https://github.com/coreybutler/nvm-windows

To install node.js, run the following commands.
1. nvm install 14.15.4
2. nvm use 14.15.4

#node-gyp
node-gyp and python tooling configuration information for windows, mac or linux can be found here
https://www.npmjs.com/package/node-gyp

This command must be run for every npm version.
1. npm install node-gyp -g
2. npm install --global windows-build-tools (run as Administrator)

#Build and Test
1.  npm ci (from the /source/service directory)
2.  npm run build (from the /source/service directory)

Is this helpful?

Thanks,
Kelly

**Comment by dmitry-shibanov** [comment] 2021-12-08 12:21
Hello @skhilliard. Thank you for your response. Does the issue reproduce locally or only for ci ? We've checked repository of mongoose and it looks like they have a similar [issue](https://github.com/Automattic/mongoose/issues/10349). Could it be related ?

**Comment by skhilliard** [comment] 2021-12-08 12:25
@dmitry-shibanov The dramatic increased memory usage using the newer mongoose library happens in both environments, but (for whatever reason), running locally in VSCode will complete, whereas in the CI environment it throws an exception.

**Comment by dmitry-shibanov** [comment] 2021-12-08 13:19
@skhilliard I think it fails on ci because the hosted runners do not have enough [resources](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources). Could you please try to delete unnecessary software for your project ?

**Comment by skhilliard** [comment] 2021-12-08 13:31
@dmitry-shibanov I am not sure if that will be an option in this case....even with this reduced project I provided, running locally I see node.exe using over 3 GB of memory.  I think the solution to this will be to understand what the problem is in this mongoose library update that is causing such a huge increase in memory usage during the Typescript compilation.

**Comment by dmitry-shibanov** [comment] 2021-12-10 14:36
Hello @skhilliard. Thank you for your response. I'm going to close the issue, because it's not related to hosted images itself. The root cause of the issue comes from mongoose library.

**Closed by dmitry-shibanov** 2021-12-10 14:36 UTC
Labels: Area: JavaScript and Node.js, OS: Ubuntu, investigate, external

**Comment by skhilliard** [comment] 2021-12-10 15:16
@dmitry-shibanov Would you perhaps emphasize this on the [issue](https://github.com/Automattic/mongoose/issues/10349) you mentioned? I have posted similar information on there as well.  Thanks!
