### ISSUE TITLE
PHP tests are broken 

### ISSUE THREAD

**Issue by Kitton** [actions/virtual-environments#1527] opened 2020-09-01 13:21 UTC
**Description**  
After a minor ubuntu(ubuntu-latest == 18.04) update  20200817.1 -> 20200825.1 our tests are broken without any changes in repo
**Area for Triage**:  
PHP, Databases
**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  
tests pass normally

**Actual behavior**  
Tests fail with error:
```
SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails 
```

**Comment by maxim-lobanov** [comment] 2020-09-01 14:04
@Kitton , could you please provide minimal repro steps for your issue? Does your build use any external dependencies (like remote databases or similar)?
You can find all updates that come with 20200825.1 in pull-request: https://github.com/actions/virtual-environments/pull/1495. As I can see, new image doesn't bring any updates related to PHP or SQL

**Comment by Kitton** [comment] 2020-09-02 06:36
@maxim-lobanov it will be a bit tricky for me to create such repo. 
We use `mirromutth/mysql-action@v1.1` from the marketplace and in `ubuntu-20.04 20200825.1` everything keeps working fine

**Comment by maxim-lobanov** [comment] 2020-09-02 08:02
@Kitton , 
Unfortunately, we can't investigate issue deeper without repro steps.

Despite the fact that your build started to fail after 20200817.1 -> 20200825, I think that issue can be caused by something different because
- Error message that you mentioned in the issue description comes from MySQL.
- Your builds don't use pre-installed MySQL. Since you use `mirromutth/mysql-action`, it setup own MySQL instance using docker container and it is used by your build
- `ubuntu-18.04 20200825.1` and `ubuntu20.04 20200825.1` were built on the same commit from this repository so they should be the same from content side. As you mentioned, switching from ubuntu18.04 to ubuntu20.04 resolved the issue.
- No image changes were done that could cause this issue. Full diff of source code for 20200817.1 -> 20200825 can be found [here](https://github.com/actions/virtual-environments/compare/ubuntu18/20200817.1...ubuntu18/20200825.1).

**Comment by maxim-lobanov** [comment] 2020-09-15 09:15
I am closing this issue for now but please let us know if it is still an issue for you and you are ready to provide additional information

**Closed by maxim-lobanov** 2020-09-15 09:15 UTC
Labels: Area: Databases, Area: PHP, OS: Ubuntu, bug, investigate
