### ISSUE TITLE
[macOS] Add MacOS Big Sur for Azure Pipelines Hosted agents

### ISSUE THREAD

**Issue by firaxis** [actions/virtual-environments#2072] opened 2020-11-16 20:42 UTC
Hi!

I wanted to ask, do you have any plans to add macOS 11 support on your hosted agents ?
GHA have it in preview, and we would like too.

-----
_Update from repo owners:_
Hello everyone!

Just an update on this thread. Starting from today, macOS 11 is publicly available for all Azure DevOps users 🚀
You should specify macos-11 image spec to use the new image.
macos-latest image spec still points to the macos-10.15. We will notify about switching macos-latest later this year.

Thank you for everyone for your patience. We will work to make sure that MacOS 12 is available faster.

Note: Availability of macOS 11 in Azure DevOps doesn't mean that the new image will be available in App Center immediately. App Center team has to perform some work on their side to make sure that new Xcode versions are available in App Center Build.

**Comment by maxim-lobanov** [comment] 2020-11-24 11:59
Hello, Thank you for raising feature request!
We definitely have a plan to add MacOS 11.0 to Azure DevOps but unfortunately can't provide ETA right now.
Let's keep this issue opened and we will post update as soon as we have

**Comment by Jon889** [comment] 2020-12-14 11:18
Is there any update on this? 

Also the azure devops documentation points to here for the available hosts, but Big Sur is only available on GitHub Actions, and there's no mention of any difference between Azure DevOps and GitHub Actions.

**Comment by AlenaSviridenko** [comment] 2020-12-15 15:36
Hi @Jon889 , unfortunately, we still have no ETA on providing Big Sur in Azure DevOps, we are still investigating capacity and infrastructure updates required for it. 
Azure DevOps and GitHub Actions are different services and not sharing images, you can find the list of agents available for Azure DevOps on [Microsoft-hosted agents page](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software). 

We will keep you posted with updates, thank you for your patience.

**Comment by Jon889** [comment] 2020-12-15 17:54
Thanks, ok I thought there were similar because the Included Software links in the table in that doc link to this repo.

**Comment by AlenaSviridenko** [comment] 2020-12-16 08:33
Images that we provide for GitHub Actions and Azure DevOps are the same for the same OS versions, but the set of provided images are different due to different infrastructure.

**Comment by ogrisel** [comment] 2021-01-10 18:08
Beyond 11.1 or 11.0 images running on x86_64 hardware, do you plan to add support for 11.1 or 11.0 images running on arm64 hardware (e.g. Apple Silicon M1) or will we have to rely on cross-compilation to build `macos/arm64` software artifacts without being able to run the tests on the CI machine?

**Comment by remyjette** [comment] 2021-01-10 20:18
@ogrisel see #2187

**Comment by Jon889** [comment] 2021-02-01 19:02
Is there any plans for Big Sur on Azure DevOps? Xcode 12.5 beta says it requires Big Sur, and there are some changes like the improved compilation that SPM caching that would be great to have.

**Comment by Jon889** [comment] 2021-02-17 08:19
@AlenaSviridenko can you update us on this?

**Comment by Jon889** [comment] 2021-03-09 18:06
@AlenaSviridenko @maxim-lobanov Any update?

**Comment by AlenaSviridenko** [comment] 2021-03-10 14:42
Hi @Jon889,
sorry for some silence, it is sad to say, but not too many updates. We expect the earliest we can add macOS 11 to AzDO is in April, when we're first able to start adding new capacity, which we still do not have at the moment.
Thank you for your patience.

**Comment by Jon889** [comment] 2021-04-20 18:40
@AlenaSviridenko Is there any update now that we know iOS 14.5 and Xcode 12.5 will be coming out next week?

**Comment by AlenaSviridenko** [comment] 2021-04-21 08:28
Hi 👋,
we're working on a plan to get Big Sur added to the hosted pool sometime in June/July, we are still working on hardware infrastructure to be ready. We are aware about stable Xcode 12.5 coming soon and doing everything possible to make macOS 11 ready as soon as possible.

**Comment by Jon889** [comment] 2021-04-21 08:40
Thanks @AlenaSviridenko for the update! It’s possible to run the agent on Big Sur on our own hardware right?

**Comment by AlenaSviridenko** [comment] 2021-04-21 09:57
Correct, you can use self-hosted runner with Big Sur

**Comment by RobinZergiebel** [comment] 2021-05-18 06:51
Any update on this? We need this for Xcode 12.5.

**Comment by AngryDuckFTW** [comment] 2021-05-20 09:51
requesting an update on this issue too please.

**Comment by joshuapoq** [comment] 2021-05-20 14:04
Slightly off topic but also another reason for wanting this sooner (and an update); is anyone else experiencing a massively increased number of UITest failures caused by bad simulator startup since the beginning of this week (macOS 10.15, XC 12)?

**Comment by AlenaSviridenko** [comment] 2021-05-22 08:18
Hey!
Looping in @vijayma for ADO timelines as they are slightly different from the GitHub Actions.

**Comment by vijayma** [comment] 2021-05-24 18:23
@ahdbilal is working on a plan to make Bug Sur available to internal customers. We will gradually ramp up the capacity for Big Sur as we reclaim the machines from older versions (10.13 and 10.14). The plan is to have at least a few 10s of machines running with Big Sur by the end of this month. The rollout to all internal accounts may take another week after that.

**Comment by AlenaSviridenko** [comment] 2021-05-24 18:34
@vijayma what about public customers? I believe it is mostly them who is asking any timeline on macOS 11, because we have other channels for communication with internal customers

**Comment by vijayma** [comment] 2021-05-24 19:09
At this time, we do not have a good ETA for external customers on Azure Pipelines. We are waiting for some licensing aspects to be sorted out first.

**Comment by Jon889** [comment] 2021-05-24 19:42
Can’t it be the same as GitHub Actions?

**Comment by nor0x** [comment] 2021-06-04 14:47
GitHub Actions is getting macOS 11.0 agents soon (https://github.com/actions/virtual-environments/issues/2486#issuecomment-854422862)
Can we get an update for AZDO or at least a timeline? We are buildless for quite a while now 😕

**Comment by vijayma** [comment] 2021-06-04 15:25
We are working on the logistics for private preview in Azure DevOps. If you are interested in pre-registering for the private preview, please send me an email with the name of your Azure DevOps organization and the # of concurrent jobs you expect to run on macOS-11. We expect this to be available sometime in June.

**Comment by kumar505** [comment] 2021-06-10 09:23
> We are working on the logistics for private preview in Azure DevOps. If you are interested in pre-registering for the private preview, please send me an email with the name of your Azure DevOps organization and the # of concurrent jobs you expect to run on macOS-11. We expect this to be available sometime in June.

@vijayma Any update on this ? We've requested via email as mentioned, but not received any response. Could you let us know the status pls.

**Comment by rmaloney3** [comment] 2021-06-14 18:20
> We are working on the logistics for private preview in Azure DevOps. If you are interested in pre-registering for the private preview, please send me an email with the name of your Azure DevOps organization and the # of concurrent jobs you expect to run on macOS-11. We expect this to be available sometime in June.

@vijayma It's now been 10 days since the last update. I sent an email to you around that time and haven't heard a reply. Do you have a more concrete timeline as to when Azure DevOps customers will have access to macOS 11 pipelines? Or at least when the private preview will open up?

**Comment by vijayma** [comment] 2021-06-15 13:25
The private preview will open up by the end of this month.  We have received a number of requests than what we can safely support during the first phase of the preview. We will go through the requests received so far and respond in the next few days. Thank you for your patience.

**Comment by Axemasta** [comment] 2021-06-18 12:31
Xcode 12.5 was release 2 months ago, I'm starting to see failures in my pipelines:

```
MTOUCH : error MT0180: This version of Xamarin.iOS requires the iOS 14.5 SDK (shipped with Xcode 12.5). 
Either upgrade Xcode to get the required header files or set the managed linker behaviour to Link Framework SDKs Only in your project's iOS Build Options > Linker Behavior (to try to avoid the new APIs).
```

What is the eta for public release?

**Comment by simonbuerger** [comment] 2021-06-18 20:49
Please start planning for macos 12 infrastructure _now_, it's not like the annual release cycle is unpredictable... It's a little crazy we're all waiting for 11 images when 12 preview will be out soon

**Comment by kraigspear** [comment] 2021-06-22 15:10
Here's to Xcode Cloud, coming soon.....

**Comment by AngryDuckFTW** [comment] 2021-06-22 15:15
> The question is what will be first, Azure getting Big Sur installed or Xcode Cloud getting released...

Think its safe to say I will be moving all my company's builds onto Xcode cloud instead of azure, its pretty poor that this is lagging so far behind for a major release that has been out plenty of time now, very disappointing

**Comment by simonbuerger** [comment] 2021-07-01 18:27
And the first MacOS 12 public beta is now available...

It'll be in full public release inside 3 or 4 months if history is any indication. Please can we not be still waiting for 11 build agents by then 🙏

**Comment by melanchall** [comment] 2021-07-06 14:25
macOS 11 has changes in some APIs and I'm not able to test those changes within Azure Pipelines due to no the image. I'm on Windows and it's pretty inconvenient to use virtual machines or so to test my code. You wrote

> we're working on a plan to get Big Sur added to the hosted pool sometime in June/July

Well, it's July now. Maybe it's finally the time to get your users what they need and what they ask you for?

**Comment by AlenaSviridenko** [comment] 2021-07-06 15:15
For registering for the private preview usage, please, send email to @vijayma with the name of your Azure DevOps organization and the # of concurrent jobs you expect to run on macOS-11. These requests are regularly reviewed and new users are included when capacity allows that.

Thanks.

**Comment by jahmai-ca** [comment] 2021-07-07 09:01
> For registering for the private preview usage, please, send email to @vijayma with the name of your Azure DevOps organization and the # of concurrent jobs you expect to run on macOS-11. These requests are regularly reviewed and new users are included when capacity allows that.
> 
> Thanks.

How regularly? I sent a request last Friday and no response as yet...

**Comment by praneetrohida** [comment] 2021-07-07 10:46
> For registering for the private preview usage, please, send email to @vijayma with the name of your Azure DevOps organization and the # of concurrent jobs you expect to run on macOS-11. These requests are regularly reviewed and new users are included when capacity allows that.
> 
> Thanks.

Are the users notified in any way when they are included, or should we just try running the pipeline on `macos-11` to check if we got the access?

**Comment by AlenaSviridenko** [comment] 2021-07-07 14:17
> How regularly? I sent a request last Friday and no response as yet...
currently, it is 2 times a month for now, when capacity is ready for the new load.

@praneetrohida, unfortunately, there is no automatic notifications about it yet. So I suppose you should run your pipelines to check it.

**Comment by simonbuerger** [comment] 2021-07-07 16:45
So we're still begging for table scraps...

**Comment by diogot** [comment] 2021-07-07 18:25
I send the email requesting access to `macOS-11` image to @vijayma a month ago, so far no response nor access to the images, I just tested.
Can I have a status or forecast of when my organization will have access?

Thanks

**Comment by honkmaster** [comment] 2021-07-08 08:37
I also send a request to @vijayma today. We need access to Xcode 12.5, which is only available for Big Sur.

**Comment by metaine** [comment] 2021-07-09 14:31
Can we use Apple Silicon (M1) self-hosted agent?

**Comment by miketimofeev** [comment] 2021-07-09 14:58
@metaine looks like it's not yet implemented https://github.com/microsoft/azure-pipelines-agent/issues/3184

**Comment by metaine** [comment] 2021-07-09 15:17
@miketimofeev it's not clear if it's about microsoft-hosted agents or self-hosted or both

**Comment by aprilmintacpineda** [comment] 2021-07-12 00:52
I also need this https://github.com/actions/virtual-environments/issues/3709

**Comment by miketimofeev** [comment] 2021-07-12 06:10
@metaine both.

**Comment by fespinoza** [comment] 2021-07-14 11:38
grrrrrr this very bad, it's unacceptable how slow this has been

**Comment by simonbuerger** [comment] 2021-07-14 11:53
Do you have ETA for public release of Big Sur images on Azure Pipelines? End of this month, next month, Q4? Also can we get a breakdown of how this happened and how you'll prevent it happening for future MacOS releases? It is of course a pain for me to migrate my companies pipelines to other providers so I would prefer not to, but if this is going to keep happening then what choice do I have but to look into it.

**Comment by bdolewski** [comment] 2021-07-19 06:00
All project in my company has deployment target of iOS 14.5. I am amazed that Big Sur + Xcode 12.5 are *not* the default images s `macos-latest`. It's not like this software was released a couple of days ago.

**Comment by L6Echo** [comment] 2021-07-20 11:01
This ticket is open since November 2020 and it was no surprise that Big Sure will be released. It is very annoying that there is still no public agent after more than 6 month, but it is unacceptable that there is not even an ETA yet.

So please give us at least a ETA. We all have to communicate to customers/partners/chiefs etc. why we are still not able to target iOS 14.5. Please understand that transparency is important and "unfortunately, we still have no ETA" is unacceptable when you had already 6 month time

**Comment by ramtechjoe** [comment] 2021-07-20 18:15
I moved to a self-hosted agent back in May.  Cannot imagine that I would ever return to reliance on Azure supporting the latest mac builds.   Sticking with Azure because that's where my code and backlogs are living, but looking at alternatives and would move as soon as time permits.

**Comment by Jon889** [comment] 2021-07-20 21:42
The problem is I guess that users of mac hosted agents make up a small percentage of users, so MS wouldn’t really care if everyone left it. Especially with Xcode Cloud coming and GitHub actions being the main focus.

**Comment by melanchall** [comment] 2021-07-24 09:46
I believe MS should care about different platforms since they have focus on cross-platform solutions. .NET developers, for example, want to be able to run their CI builds for cross-platform products on different operating systems. As for macOS 11, as I said, there are some API changes in it, so it would be great to have ability to check products compatibility via Azure Pipelines.

**Comment by vijayma** [comment] 2021-07-28 06:07
Hello all, we understand the sentiment on this thread and are sorry that we do not have a generally available offering yet for Big Sur builds in Azure Pipelines. The main reason for us to be in this state is not technical. It is related to licensing. We are still working through the licensing terms to understand whether we can offer Big Sur the same way we offer previous versions of macOS.  We do not want to offer this in a certain model and then realize that we have to change it again.

Regarding the preview request process, we get a huge number of requests every day. We review these requests regularly and process them once every two weeks. That gives us enough time to monitor the usage and ramp up the capacity for supporting more customers. Once your organization is approved, you will receive an email from us. We sincerely appreciate your patience once you send us a request.

**Comment by cquanu** [comment] 2021-07-28 12:13
If you can grant Big Sur for GitHub Actions by filling up a form. Why not AppCenter?

**Comment by AlenaSviridenko** [comment] 2021-07-28 13:58
We cannot do that technically, due to the different nature of account creation for GitHub Actions, Azure DevOps and App Center. App Center uses a dynamically created account name in Azure DevOps underneath your username, which complicates the process of enabling an image for a certain account.

**Comment by cquanu** [comment] 2021-07-28 18:53
So this more of a technical issue instead of licensing right?

**Comment by svaldetero** [comment] 2021-07-28 18:57
> So this more of a technical issue instead of licensing right?

@cquanu I think they mean adding people to the preview for AppCenter is a technical issue; creating/provisioning enough Virtual Machines as a whole is a licensing issue.

**Comment by Jon889** [comment] 2021-07-28 20:48
Surely any licensing issues would also prevent the closed preview that you can get by emailing?

**Comment by L6Echo** [comment] 2021-07-28 23:44
We do understand, that apple changed the license of mac os and that this affects the doability of providing virtual developing environments.

But the license is public (at least) for 7 month now and it's still a blocker? We are paying, not less, to get a managed and up to date CD platform. And be able to build up to date iOS Apps and Frameworks is an important part of it.  And Microsoft stuff (e.g. Visual Studio on Mac, Xamarin) are also already requiring Xcode 12.5. Don't get us wrong, these are not sensitivities. These are just facts and business.

> We are still working through the licensing terms to understand whether we can offer Big Sur the same way we offer previous versions of macOS. We do not want to offer this in a certain model and then realize that we have to change it again.

Anyway, I don't understand why you're arguing to have licensing issues, but you are able to run private previews. But just not in this strong demand. And also the registration process (request per email and (no) response) is somehow Microsoft unworthy...

What does these private preview (if we get accepted) means for production use cases? Are the production ready? Do we have to expect breaking changes?

 **@vijayma @AlenaSviridenko  A lot of users already asked for an ETA. So please tell us, when do you expect to solve this...** August? September? End of the year? Never?

**Comment by aprilmintacpineda** [comment] 2021-07-29 00:14
We should really just deprecate azure pipelines, in my opinion, it's inadequate, my experience with GitHub actions is better.

**Comment by vijayma** [comment] 2021-07-29 15:52
@L6Echo The servers that are offered in preview will be the same images when we make this generally available. There is no change technically in what we do. By offering it as a preview, we retain some flexibility to change how we license this to our customers or charge for it. Unfortunately, we do not have an ETA yet. I will share another update in the middle of August.

**Comment by cquanu** [comment] 2021-07-29 15:56
@vijayma So the question is, are you able to offer it as a preview? - Since you said it's "flexible". You don't have an ETA for the preview, or when it will be generally available?

**Comment by vijayma** [comment] 2021-07-29 16:03
@cquanu In my comments, I am referring to our limitations in making Big Sur publicly and generally available for Azure Pipelines. I am not referring to App Center. 

Your comments, I believe, are related to AppCenter. With AppCenter, as @AlenaSviridenko mentioned, we do not have a preview either because of the way AppCenter uses Azure Pipelines.

**Comment by cquanu** [comment] 2021-07-29 16:08
You are not referring to AppCenter but AppCenter uses Azure Pipelines. 😕

![](https://media1.tenor.com/images/6d603ccd33d70852442d68c0a84e4fb3/tenor.gif?itemid=5325620)

**Comment by simonbuerger** [comment] 2021-07-30 04:26
@vijayma presumably this is going to continue to be an issue in two months time when Monterey is released? Because if we can't build with Monterey by April next year then Azure pipelines will become dead in the water for iOS development as we won't be able to release builds to Apple app store from that point. I'm making some assumptions based on apple's release history and previous SDK deprecation dates, but I think they're quite safe ones.

**Comment by simonbuerger** [comment] 2021-07-30 07:14
@vijayma can you explain the licensing issues in more detail and why they're so hard to overcome? How have other providers done it?

What is the likelihood of positive news in mid-August?

**Comment by honkmaster** [comment] 2021-07-30 07:49
@simonbuerger @vijayma Big Sur was announced more than a year ago including the license changes. I can understand if it takes so long for a small company without trademarks, licenses and patent attorneys to solve the problems but not for a big company like Microsoft.

Although we currently have access to the beta and it works well (thanks for that) we will be looking for an alternative soon. I personally don't expect positive news in August. 

We were really disappointed by Microsoft this year.... App Center had no iOS 14 devices for testing till April / May and now this "little problem" as well. It is really a pity.

**Comment by cquanu** [comment] 2021-07-30 10:31
I am looking for alternatives. What are some good ones?

**Comment by ramtechjoe** [comment] 2021-07-30 15:37
@cquanu I use a [self hosted build agent ](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-osx?view=azure-devops).  I cannot imagine I would ever go back to using a Azure DevOps provided agent after this debacle

**Comment by ataylorme** [comment] 2021-07-30 15:40
@ramtechjoe have you been successful with self-host build agents on Big Sur?

That is probably what I’ll be attempting next. I’m trying to decide between buying Mac Minis or using cloud infrastructure.

**Comment by ramtechjoe** [comment] 2021-07-30 15:51
@ataylorme I have been running self hosted agent since back in May on Big Sur.  I just use my normal development machine, but we only have a couple Xamarin applications and never run more then a single build at a time.  I cannot say how it would scale.

**Comment by simonbuerger** [comment] 2021-07-30 17:16
@ramtechjoe Yeah I'm managing active deployment pipelines across 5 other tenants, and then 6 other active app deployment pipelines (all multi environment 🙈) within our own tenant so self hosting is not much of an option for us.

**Comment by fespinoza** [comment] 2021-08-02 07:59
@vijayma we sent the email to ask access to the previews for macOS 11 for azure pipelines, 2 weeks ago already and we still don't have access :(. Why is all of this so painfully slow :(

**Comment by ericallam** [comment] 2021-08-03 11:51
@ataylorme we use self-hosted Big Sur for Unity builds (still using Microsoft-hosted agents for our Xcode builds though, but looking to switch to self-hosted soon) and the agent works fine. I'd imagine it would work just fine for building Xcode projects

**Comment by s-hintz** [comment] 2021-08-05 13:36
@vijayma 
> The main reason for us to be in this state is not technical. It is related to licensing.

Can you at least support Bug Sur for Microsoft App Center then?

**Comment by hecflores** [comment] 2021-08-09 01:05
Maybe it's time to ask for a feature in Azure DevOps to allow agents to be crowdsourced... Meaning, people publish their own hosting solutions to act as agents and get paid for their use... I'm sure many folks have already gone out and used some hosting provider like Macstadium or their own machines...

**Comment by ryanmendoza** [comment] 2021-08-10 14:41
It appears that the latest macOS build agent available on DevOps is not capable of building enterprise distribution iOS apps due to an outdated code signing library. Currently, apps built with the Catalina latest agent do not launch on iOS 15 at all and we are about a month away from public release.

Other than hosting a machine on-prem, does anyone know of a way around this Microsoft delay in offering required build agents for iOS 15?

**Comment by gredman** [comment] 2021-08-10 21:30
@ryanmendoza we have access to the Big Sur preview now, but prior to that I was re-signing our ad hoc IPAs as described in https://developer.apple.com/forums/thread/682775?answerId=681899022#681899022. [This is the script I used](https://gist.github.com/gredman/25e35a8d622c3cdc2d06e41e1f6c1970) (you'll need to set `SOURCE` to the path of your IPA and `SIGNING_IDENTITY` to the name of your signing identity).

**Comment by maluthbadugecara** [comment] 2021-08-12 03:24
Hi, 

We are also having the issue @ryanmendoza mentioned as we are also under the apple enterprise programme.
One user just upgraded to ios 15 and the app does not open on the device as it was built using XCODE 12.4 on the Dev Ops pipeline.

@gredman Thanks for the workaround mate, highly appreciate it !... going to try it in my pipeline. 
When you say SIGNING_IDENTITY, I assume that I need to point to the Private key file or the certificate (public key) file?

> @ryanmendoza we have access to the Big Sur preview now, but prior to that I was re-signing our ad hoc IPAs as described in https://developer.apple.com/forums/thread/682775?answerId=681899022#681899022. [This is the script I used](https://gist.github.com/gredman/25e35a8d622c3cdc2d06e41e1f6c1970) (you'll need to set `SOURCE` to the path of your IPA and `SIGNING_IDENTITY` to the name of your signing identity).

**Comment by cquanu** [comment] 2021-08-16 21:06
What's the progress now @vijayma? Can we have some updates?

**Comment by maluthbadugecara** [comment] 2021-08-17 03:06
Hi, 
Good morning !
As we are gettign very close to the iOS 15 release, can we please have an ETA on when MacOS BigSur is available on MS hosted agents? Appreciate your assistance.

Best Regards, 
M

**Comment by yvbeek** [comment] 2021-08-17 04:34
> We are happy to announce that macOS-11 is out of preview and now generally available for all the GitHub customers 🥳
> The docs will be updated later this week.

https://github.com/actions/virtual-environments/issues/2486#issuecomment-899752373

@maxim-lobanov @AlenaSviridenko 
Please tell me that the Xcode 12.5 option will be available later today 🙏

**Comment by miketimofeev** [comment] 2021-08-17 07:20
@yvbeek unfortunately, we can't provide ETA for now. Please send an e-mail to @vijayma with justification if you need access

**Comment by simonbuerger** [comment] 2021-08-17 07:38
@miketimofeev is this message from you the "official" update that @vijayma said he would give 3 weeks ago in mid August?

> Unfortunately, we do not have an ETA yet. I will share another update in the middle of August.

So the update on ETA is that there is still no update on ETA?

As a paying customer I don't think it's too much to ask for more of a detailed update than "we have no update"

**Comment by Jon889** [comment] 2021-08-17 08:57
So I assume the licensing is sorted out now that GitHub actions has macOS 11?

https://github.com/actions/virtual-environments/issues/2486#issuecomment-899752373

**Comment by cquanu** [comment] 2021-08-17 10:17
I don't understand, the fact that the issues tab is opened for this repository and we can submit our issue. But thought the team of the virtual environment is not transparent about it but has decided to silo￼ information from us and think that they have given a reasonable answer.

**Comment by FRcarriel** [comment] 2021-08-17 14:35
Please tell me that the Xcode 12.5 option is resolved or not with macos-11 ????🙏

**Comment by philipdvo** [comment] 2021-08-18 00:34
Hi @miketimofeev ,
Could you please provide the email of @vijayma for requesting the Preview of macos-11 on Azure DevOps Pipelines for company?

Thank you

**Comment by maluthbadugecara** [comment] 2021-08-18 06:58
> Hi @miketimofeev ,
> Could you please provide the email of @vijayma for requesting the Preview of macos-11 on Azure DevOps Pipelines for company?
> 
> Thank you

Hi, 

Can we use the preview of macos-11 on Azure DEVOps for Production builds? Please let me know how to request macos 11 preview to be available on Azure DevOPS?

Thanks

**Comment by miketimofeev** [comment] 2021-08-18 07:00
@philipdvo <username>@github.com — this will be his address

**Comment by maluthbadugecara** [comment] 2021-08-18 07:07
@miketimofeev Can we use MacOS 11 Preview on Azure DevOPS to run PRoduction builds?

**Comment by miketimofeev** [comment] 2021-08-18 07:10
@maluthbadugecara you can once you have access to macos-11.

**Comment by phornsby7** [comment] 2021-08-18 16:34
@vijayma and @miketimofeev  Hope your hump day is going well.  I wanted to ask if your able to  give any new updates that we can pass on to `our` bosses?

Anything you share is greatly appreciated.

🙏🏻

**Comment by cquanu** [comment] 2021-08-23 17:35
Any updates?

**Comment by Ahetejaz** [comment] 2021-08-24 03:49
FYI, The Big Sur pool is available for all customers starting today. So, one can start using it in YAML pipelines using the label macos-11.

**Comment by Ahetejaz** [comment] 2021-08-24 03:51
> @vijayma and @miketimofeev Hope your hump day is going well. I wanted to ask if your able to give any new updates that we can pass on to `our` bosses?
> 
> Anything you can share is greatly appreciated.
> 
> 🙏🏻

FYI, The Big Sur pool is available for all customers starting today. So, one can start using it in YAML pipelines using the label macos-11.

**Comment by cquanu** [comment] 2021-08-24 03:51
> FYI, The Big Sur pool is available for all customers starting today. So, one can start using it in YAML pipelines using the label macos-11.

Thanks. But I was asking about AppCenter.

**Comment by maluthbadugecara** [comment] 2021-08-24 04:51
> 
> 
> > @vijayma and @miketimofeev Hope your hump day is going well. I wanted to ask if your able to give any new updates that we can pass on to `our` bosses?
> > Anything you can share is greatly appreciated.
> > 🙏🏻
> 
> FYI, The Big Sur pool is available for all starting today. So, one can start using it in YAML pipelines using the label macos-11.
> 
> With respect to Azure DevOps.

Thanks a lot for the update

**Comment by aprilmintacpineda** [comment] 2021-08-24 04:54
> > @vijayma and @miketimofeev Hope your hump day is going well. I wanted to ask if your able to give any new updates that we can pass on to `our` bosses?
> > Anything you can share is greatly appreciated.
> > 🙏🏻
> 
> FYI, The Big Sur pool is available for all starting today. So, one can start using it in YAML pipelines using the label macos-11.
> 
> With respect to Azure DevOps.

will `macOS-latest` work as well?

**Comment by maxim-lobanov** [comment] 2021-08-24 06:53
Hello everyone!

Just an update on this thread. Starting from today, macOS 11 is publicly available for all Azure DevOps users 🚀 
You should specify `macos-11` image spec to use the new image.
`macos-latest` image spec still points to the `macos-10.15`. We will notify about switching `macos-latest` later this year.

Thank you for everyone for your patience. We will work to make sure that MacOS 12 is available faster.

**Note:** Availability of macOS 11 in Azure DevOps doesn't mean that the new image will be available in App Center immediately. App Center team has to perform some work on their side to make sure that new Xcode versions are available in App Center Build.

**Closed** 2021-08-24 06:56 UTC
Labels: question, OS: macOS, Area: Image administration

**Comment by FarahaDadvarDeveloper** [comment] 2021-09-30 10:03
Hi, 

When will macOS 11.6 host agent be made available on Azure DevOps Pipeline?

**Comment by al-cheb** [comment] 2021-09-30 10:06
> Hi,
> 
> When will macOS 11.6 host agent be made available on Azure DevOps Pipeline?

macOS 11 is  already available on Azure DevOps Pipeline.

**Comment by al-cheb** [comment] 2021-09-30 10:07
> Hi,
> 
> When will macOS 11.6 host agent be made available on Azure DevOps Pipeline?

macOS 11 is publicly available for all Azure DevOps users - https://github.com/actions/virtual-environments/issues/2072#issuecomment-904371992

**Comment by FarahaDadvarDeveloper** [comment] 2021-09-30 10:10
> > Hi,
> > When will macOS 11.6 host agent be made available on Azure DevOps Pipeline?
> 
> macOS 11 is publicly available for all Azure DevOps users - [#2072 (comment)](https://github.com/actions/virtual-environments/issues/2072#issuecomment-904371992)

I was wondering when macOS **11.6** will be available as this will support Xcode 13

**Comment by al-cheb** [comment] 2021-09-30 10:11
> > > Hi,
> > > When will macOS 11.6 host agent be made available on Azure DevOps Pipeline?
> > 
> > 
> > macOS 11 is publicly available for all Azure DevOps users - [#2072 (comment)](https://github.com/actions/virtual-environments/issues/2072#issuecomment-904371992)
> 
> I was wondering when macOS **11.6** will be available as this will support Xcode 13
Already available:
https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md 
`System Version: macOS 11.6 (20G165)`

**Comment by thomthom** [comment] 2021-10-01 19:25
Looking to use XCode 12.5 with Azure Devops, pipeline is not setup via YML, but via the UI. How does one choose an image that support XCode 12.5?

**Comment by miketimofeev** [comment] 2021-10-01 21:48
@thomthom make sure you specify `macos-11` as vm image, it is enough

**Comment by thomthom** [comment] 2021-10-03 09:08
For the record, the source of my confusion was due to me having an old setup. My builds were still using the `Hosted macOS" agents.

![image](https://user-images.githubusercontent.com/192418/135747134-be3eb88c-f9af-4a94-b6f5-aeff6627a0db.png)

Once I switched to Azure Pipelines I got the list of images:

![image](https://user-images.githubusercontent.com/192418/135747161-7535a208-af64-4964-9144-5f641f315cfc.png)
