### ISSUE TITLE
Update kernel version on ubuntu 18.04 images

### ISSUE THREAD

**Issue by ethomson** [actions/virtual-environments#2] opened 2019-09-30 10:29 UTC
**Describe the bug**
The kernel in the Ubuntu 18.04 images suffers [from a kernel bug](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1843018) that prevents [.NET Core from running in a container](https://github.com/dotnet/corefx/issues/40850).

It seems that subsequent updates [may have fixed this](https://github.com/dotnet/corefx/issues/40850#issuecomment-536034039).

**Virtual environments affected**
- [ ] macOS 10.14
- [ ] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
.NET Core containers run correctly

**Actual behavior**
.NET Core container runs fail with "The FileName property should not be a directory unless UseShellExecute is set"

See https://github.community/t5/GitHub-Actions/Docker-build-failure-on-Ubuntu-18-04-host/m-p/33224#M1423

**Comment by dasMulli** [comment] 2019-10-01 21:58
Also note that another common error for the same bug is

```
error MSB6004: The specified task executable location "/" is invalid.
```

depending on the build that is being run. (one is launching the c# compiler, one is launching msbuild worker nodes for parallel builds)

**Comment by rainersigwald** [comment] 2019-10-02 17:05
Status from internal thread:

No ETA as of yet, but:

* It looks like https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1842382 is the duplicate of the Ubuntu bug that has the most traction
* https://bugs.launchpad.net/kernel-sru-workflow/+bug/1846007 is being used as the fix-tracking bug on the Ubuntu side
* https://launchpad.net/ubuntu/+source/linux-azure/ tracks the validation/promotion of the kernel. This is supposed to be fixed in `5.0.0-1022`, which is currently `proposed` (still in testing; not recommended for production systems)

**Comment by alepauly** [comment] 2019-10-14 14:47
@rainersigwald Update with kernel version ```5.0.0-1022-azure``` is rolling out now and should be everywhere by the end of the week.
fyi @kaylangan

**Comment by alepauly** [comment] 2019-11-14 13:11
This has been deployed for a while now, forgot to update issue

**Closed by alepauly** 2019-11-14 13:11 UTC
