### ISSUE TITLE
Delete Install User on Windows Images?

### ISSUE THREAD

**Issue by ryanspletzer** [actions/virtual-environments#1449] opened 2020-08-20 12:26 UTC
**Description**  
Apologies for calling this a bug as it's more of a proposal: Would deleting the install user before the last sysprep step be acceptable?

```json
        {
            "type": "windows-shell",
            "inline": [
                "net user {{user `install_user`}} /delete"
            ]
        },
```

I only bring this up as, from a security standpoint, it's nice to not have an extra user present on the machine.

In our environment we do the image build and then remove the user, and it hasn't had any bad side effects.

If removing the install user should be a choice for people who run the image after it's deployed, I can understand that. (Maybe Microsoft has its uses for this user on their hosted agents.)

**Area for Triage**:  
Servers

**Question, Bug, or Feature?**:  
Question

**Virtual environments affected**  
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**  
Install user is deleted.

**Actual behavior**  
Install user remains.

**Repro steps**  

1. Run the image build.

**Comment by Darleev** [comment] 2020-08-24 13:37
Hello @ryanspletzer,
I can confirm that the user 'installer' exists in current windows machines. Could you please share possible security impact here?
Currently, we don't consider to remove this user due to possible unpredictable impact. 

We are looking forward to your reply.

**Comment by ryanspletzer** [comment] 2020-08-24 15:07
Hi @Darleev, this probably mostly will apply just to enterprises. At our company the policy is to not have local users on Windows Servers, and for the built-in local administrator administrator account we use LAPS to control that password. Having another user on the machine introduces the avenue to side-step domain-based controls like group policy, etc.

Again this is not a huge deal as for these build servers we can simply delete the install user afterward on machine launch. That said, I've actually got a slightly modified version of the packer template that does it as part of the image build, prior to sysprep, with the command above, and we've seen no issues thus far.

Understand how this could lead to downstream impact -- the tests may pass but a deployed server may experience some type of issues that could be hard to predict amongst the many tools.

It seems at present, the install user is only used for VS / .NET 4.8 install, enabling developer mode, and running the initial Windows Update. I'm not sure if VS / .NET 4.8 expects the install user to be there later in order to function properly, but based on experience I've been able to do MSBuild just fine with the install user deleted (though admittedly, we've been doing .NET Core builds with .sln via MSBuild, less full framework). And I would think that developer mode and Windows Update should be OK without the install user later (though I doubt that these machines are patched in-place later by running Windows Update -- likely tossed out in favor of newly built images with latest updates). It seems like developer mode is enabled expressly to support WinAppDriver, which admittedly is something we don't use.

Anyways, just wanted to bring it up for consideration for inclusion in the main repo, since this is something we do in our environment.

**Comment by Darleev** [comment] 2020-08-26 12:11
@ryanspletzer thank you for the detailed description. This information can be very useful for other users who planned to add hosted agents into their environments.
However, we aren't planning to remove the installer user from our images, since the impact is unclear, and our agents are worldwide accessible.
I'm going to close the issue. In case of any issues or questions, feel free to contact us at any time.

**Closed by Darleev** 2020-08-26 12:11 UTC
Labels: Area: Image administration, OS: Windows, investigate, question
