### ISSUE TITLE
Windows-2016 environment removal postponed until April 1st, 2022

### ISSUE THREAD

**Issue by alepauly** [actions/virtual-environments#5238] opened 2022-03-15 20:46 UTC
### Breaking changes

Windows 2016 hosted runners were scheduled for full removal on March 15th, 2022. However, we are still seeing significant usage from customers and we want to give them more time to migrate to the new runners. In order to give customers another chance to move to either `windows-2019` or `windows-2022` we will delay the removal of `windows-2016` until April 1st, 2022.

To raise awareness of the removal, we will have rolling 12-hour periods where the image will be unavailable for customers. During these "brownout" periods, customers will see an error message indicating that the image is slated for removal on April 1st, 2022. The schedule for those brownout periods is as follows for both Azure DevOps and GitHub Actions:

1. Tuesday March 15, 20:00 UTC to March 16, 08:00 UTC
1. Thursday March 17, 08:00 UTC to March 17, 20:00 UTC
1. Friday March 18, 20:00 UTC to March 19, 08:00 UTC
1. Monday March 21, 08:00 UTC to March 21, 20:00 UTC
1. Tuesday March 22, 20:00 UTC to March 23, 08:00 UTC
1. Wednesday March 23, 20:00 UTC to March 24, 08:00 UTC
1. Friday March 25, 08:00 UTC to March 25, 20:00 UTC
1. Sunday March 27, 20:00 UTC to March 28, 08:00 UTC
1. ~~Tuesday March 29~~ Wednesday March 30, 08:00 UTC to March 30, 20:00 UTC
1. Full removal - April 1, 15:00 UTC

See the original announcement at #4312

### Target date

April 1st, 2022

### The motivation for the changes

Windows Server 2016 Active support ends on 11 Jan 2022 and Windows Server 2022 VM image is going out of beta later this year.
As part of our ongoing efforts to keep GitHub and Azure Devops hosted runners updated and secure, the Windows 2016 virtual environment will be removed from GitHub Actions and Azure DevOps.

### Possible impact

Workflows targeting the Windows 2016 image will fail.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Mitigation ways

Change your workflows to use `windows-latest`, `windows-2022`, or `windows-2019`

**Comment by rdhaundiyal** [comment] 2022-03-16 07:19
Hi, I am not using windows-2022 but still getting the error related to 2016
is it some side effect

Deployment canceled by Microsoft.VisualStudio.Services.ReleaseManagement on 3/16/2022, 6:15 PM

**Comment by GokulKannanN** [comment] 2022-03-16 07:33
We are using vmImageName: 'ubuntu-latest' but still we are getting this error.
what is the solution for this  issue.

**Comment by rdhaundiyal** [comment] 2022-03-16 07:40
update, it was the release agent which was by default picking up 2016-17 even after creating a new release from scratch, settign it manually to 2022 worked

**Comment by GokulKannanN** [comment] 2022-03-16 07:42
> worked

I did not understand. Can you please tell me where I have to update 2022.
because Ubuntu does not have 2022, its latest version is 20.04

**Comment by rdhaundiyal** [comment] 2022-03-16 07:44
my issue was related to release , in the release pipeline -> edit, you have agent, clicking on the agent show you the provider
https://blog.novacare.no/devops-change-agent-specification-to-windows-latest/

**Comment by ManaliMnS** [comment] 2022-03-16 07:48
> > worked
> 
> I did not understand. Can you please tell me where I have to update 2022. because Ubuntu does not have 2022, its latest version is 20.04

Go to your release pipeline. Edit . Go to agent job.  Change agent specification to windows latest

**Comment by CodeIn24** [comment] 2022-03-16 13:24
Hi, Just for better understanding, we have self-hosted agent on one of our machines having windows 2016 OS , so this means we have to upgrade the OS and re-host the agent for pipelines to keep running, am I missing anything? 

This option will not work for us considering our setup:
![image](https://user-images.githubusercontent.com/89847036/158598150-a1c44a1b-ac3b-4a49-817a-bb547f4ac013.png)

**Comment by alepauly** [comment] 2022-03-16 13:38
> Hi, Just for better understanding, we have self-hosted agent on one of our machines having windows 2016 OS , so this means we have to upgrade the OS and re-host the agent for pipelines to keep running, am I missing anything?

@CodeIn24 - this doesn't affect self-hosted agents. it's only related to the hosted Windows 2016 virtual environment. You don't need to change anything.

**Comment by CodeIn24** [comment] 2022-03-16 14:20
good to know this, thanks

**Comment by Razakhel** [comment] 2022-03-17 12:31
Hello,

As is the custom with MSVC, the SDK currently available on the `windows-2019` image is broken and does not compile:

```
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\oaidl.h(502,17): error C2059: syntax error: '/'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\oaidl.h(530,17): error C2059: syntax error: '}'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\oaidl.h(531,13): error C2059: syntax error: '}'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\oaidl.h(533,9): error C2059: syntax error: '}'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\oaidl.h(534,5): error C2059: syntax error: '}'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\oaidl.h(665,16): error C2079: 'varDefaultValue' uses undefined struct 'tagVARIANT'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\oaidl.h(950,16): error C2079: 'varValue' uses undefined struct 'tagVARIANT'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\propidlbase.h(319,24): error C2059: syntax error: '/'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\propidlbase.h(378,37): error C2371: 'pvarVal': redefinition; different basic types
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\oaidl.h(510): message : see declaration of 'pvarVal'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\propidlbase.h(379,9): error C2059: syntax error: '}'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\propidlbase.h(380,5): error C2059: syntax error: '}'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\propidlbase.h(383,3): error C2059: syntax error: '}'
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\propidlbase.h(384,1): error C2059: syntax error: '}'
```

I did file a report on this a couple months ago in anticipation, but I guess many users will simply _not_ be able to upgrade the version because of this. Using the `windows-2022` image & VS 2022 works fine for me, but may not be suitable for others. Please either [update the SDK](https://github.com/dotnet/runtime/issues/50342#issuecomment-809012489) or explicitly state that the 2019 image _cannot_ be used for C & C++ users, so they can safely migrate to the 2019 image.

**Comment by toddbellamy** [comment] 2022-03-17 13:57
We are getting the windows-2016 brownout error even though our Pipeline is using windows-latest and the log even shows that windows-2022 agent was used. 
Why?

**Comment by jackweldon** [comment] 2022-03-17 14:03
vmImageName: 'windows-2019'

**Comment by gene-keys** [comment] 2022-03-17 15:29
WHY DO YOU NEED 9 NOTICE WINDOWS IN MARCH? and why do they need to be this long? and why do you impact all pools with this notices even linux

**Comment by slobshay** [comment] 2022-03-20 09:46
Hello, according to brownout plan, there shouldn't be anything now (20.3.2022), although our build failed with brownout message.
Can anyone please assist?

**Comment by eeropenttinen** [comment] 2022-03-20 10:48
> Hello, according to brownout plan, there shouldn't be anything now (20.3.2022), although our build failed with brownout message. Can anyone please assist?

I have exactly the same issue and using windows-2022 which should be working fine.

**Comment by eeropenttinen** [comment] 2022-03-20 10:49
> We are getting the windows-2016 brownout error even though our Pipeline is using windows-latest and the log even shows that windows-2022 agent was used. Why?

I have exactly the same isssue.

**Comment by tabenari** [comment] 2022-03-20 11:34
We had the same issue
Fixed by changing the agent specification for our jobs to windows-latest as suggested in the description:

![image](https://user-images.githubusercontent.com/73182585/159160199-6766095b-fb2f-41b5-8a6f-62dfacd7cfe2.png)

**Comment by dduleep** [comment] 2022-03-20 13:01
we have 1000 classic pipelines with vs2017-win2016 agent, we are planning to migrate all pipelines to windows-2019, looking for an easy update, instead of GUI, any options do we have to update of classic pipeline agent? API or CLI option?

**Comment by geekzter** [comment] 2022-03-21 09:14
> We are getting the windows-2016 brownout error even though our Pipeline is using windows-latest and the log even shows that windows-2022 agent was used. Why?

That should not be happening. What pool are you using? Do you have a screenshot?

**Comment by geekzter** [comment] 2022-03-21 09:23
> We are getting the windows-2016 brownout error even though our Pipeline is using windows-latest and the log even shows that windows-2022 agent was used. Why?

That should not be happening. Is this a UI of YAML pipeline? Are you referencing a pool name? If so which pool?

**Comment by geekzter** [comment] 2022-03-21 10:29
> we have 1000 classic pipelines with vs2017-win2016 agent, we are planning to migrate all pipelines to windows-2019, looking for an easy update, instead of GUI, any options do we have to update of classic pipeline agent? API or CLI option?

You can use the [REST API](https://docs.microsoft.com/en-us/rest/api/azure/devops/build/definitions/update?view=azure-devops-rest-6.0#agentspecification) to update classic / UI pipelines.

**Comment by slobshay** [comment] 2022-03-21 11:53
> > We are getting the windows-2016 brownout error even though our Pipeline is using windows-latest and the log even shows that windows-2022 agent was used. Why?
> 
> That should not be happening. Is this a UI of YAML pipeline? Are you referencing a pool name? If so which pool?

Not anymore, but trust me, it didn't even start to run.
We moved our builds to use windows-2019, all good now.

**Comment by eeropenttinen** [comment] 2022-03-21 16:42
In our case the build works fine (using windows-2022 agent), but deployment to cloud of the web app fails when the pipeline is trying to publish it Azure.

```
steps:
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: build
```

Behind the scenes, it seems it is using something for deployments, windows-2016. I don't know where to change that though.

I can see from logs:
"Deployment canceled by Microsoft.VisualStudio.Services.ReleaseManagement"

**Comment by geekzter** [comment] 2022-03-22 09:37
> 



> In our case the build works fine (using windows-2022 agent), but deployment to cloud of the web app fails when the pipeline is trying to publish it Azure.
> 
> ```
> steps:
> - task: PublishBuildArtifacts@1
>   displayName: 'Publish Artifact: drop'
>   inputs:
>     PathtoPublish: build
> ```
> 
> Behind the scenes, it seems it is using something for deployments, windows-2016. I don't know where to change that though.
> 
> I can see from logs: "Deployment canceled by Microsoft.VisualStudio.Services.ReleaseManagement"

Is this a release pipeline? If so, [this ](https://developercommunity.visualstudio.com/t/deployment-canceled-by-microsoftvisualstudioservic-1/1565171)could apply.

**Comment by FawadBhatti-Experian** [comment] 2022-03-22 13:36
Our application runs on Azure Cloud (Classic) and  trying to upgrade the pipeline to accomodate new changes but after updating the vmImage to windows-2019 or windows-2022 also msbuild version from 15.0 to 16.0 deployment gets failed. 

I would really appreciate if someone help me to fix the issue.

**Comment by HolisticDeveloper** [comment] 2022-03-23 12:16
> we will delay the removal of `windows-2016` until April 1st, 2021.

@alepauly please note your typo in the first paragraph -- should be 2022 instead of 2021.

**Comment by alepauly** [comment] 2022-03-23 12:28
> > we will delay the removal of `windows-2016` until April 1st, 2021.
> 
> @alepauly please note your typo in the first paragraph -- should be 2022 instead of 2021.

Thank you @HolisticDeveloper! Fixed.

**Comment by peternznguyen** [comment] 2022-03-26 07:16
We are using Azure DevOps to build and manage for source code and SSIS packages for Data Warehouse system. Below are the settings that worked fine for vs2019-win2016 image and then changed to Windows-2019 image and failed for SSIS.

I. Fine working setttings

Our current pipeline is configured to run Agent job including

 - Build Database projects
 - Build SSIS


The YAML file 

```
pool:
  name: Azure Pipelines
  demands: msbuild

steps:
- task: MSBuild@1
  displayName: 'Build database projects **/*.sqlproj'
  inputs:
    solution: '**/*.sqlproj'
  condition: succeededOrFailed()

- task: TG.VSTS-SSIS.BuildSSIS-task.BuildSSIS@1
  displayName: 'Build SSIS '
  inputs:
    solnPath: '$/Data Warehouse/odl.datawarehouse/odl.datawarehouse.sln'
    solnConfigName: Development
    projPath: '$/Data Warehouse/odl.datawarehouse/IntegrationServices/DWFrameworkSSIS/DWFrameworkSSIS.dtproj'
    projConfigName: Development
    cmdSwitch: build
    devenvVersion: VS2017ent

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$/Data Warehouse/odl.datawarehouse'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
```




However, lately I was warned as below


```
##[warning]The windows-2016 environment is deprecated and will be removed on April 1st, 2022. For more details, see https://github.com/actions/virtual-environments/issues/5238
Pool: Azure Pipelines
Image: vs2017-win2016
Agent: Hosted Agent
```



Above warnings mean currently we are running VS2017 on Azure Virtual Machine with Windows 2016


II. Changed as warning and SSIS failed


Following the link https://github.com/actions/virtual-environments/issues/5238, 
I changed workflows to use windows-2019 (new Image replaced "vs2017-win2016", not changed SSIS settings) for the pineline, as a result:

 - The job  "Build Database projects" was successful.
 - However, the job "Build SSIS" was failed with warning: ##[error]Internal Error: Microsoft.PowerShell.Commands.WriteErrorException Devenv.com in   
   C:\Program Files (x86)\Microsoft Visual      
   Studio\2017\Enterprise\Common7\IDE\Devenv.com not found

I have searched to try solving the issue "Devenv.com not found" but not any help

Can you guys please help me to fix this as the deprecated date for Win-2016 is coming soon?

Much appreciated!

Peter

**Comment by Munira-Panjwani** [comment] 2022-03-27 22:49
Hi, 

I have updated the yml (below) image
![image](https://user-images.githubusercontent.com/88992466/160304394-0c249559-2263-4cff-af32-0d860038e1b5.png)

But its failing with the error of:
![image](https://user-images.githubusercontent.com/88992466/160304427-37b26756-f0fb-4a98-934c-a0cf14e8a1eb.png)


Help is much appreciated.

Munira

**Comment by nha-vertica** [comment] 2022-03-28 06:52
Regardless of change of Agent Specification Win2019, 2022 or Win-Latest - still getting the brownout which cancels the whole thing regardless of being outside of brownout period

Current time: UTC 06:50 (March 28)

"Friday March 25, 08:00 UTC to March 25, 20:00 UTC
Sunday March 28, 20:00 UTC to March 29, 08:00 UTC
Tuesday March 30, 08:00 UTC to March 30, 20:00 UTC"

**Comment by geekzter** [comment] 2022-03-28 07:56
> Hi,
> 
> I have updated the yml (below) image ![image](https://user-images.githubusercontent.com/88992466/160304394-0c249559-2263-4cff-af32-0d860038e1b5.png)
> 
> But its failing with the error of: ![image](https://user-images.githubusercontent.com/88992466/160304427-37b26756-f0fb-4a98-934c-a0cf14e8a1eb.png)
> 
> Help is much appreciated.
> 
> Munira

You should use 'Azure Pipelines' as pool name instead of 'Hosted VS2017'

**Comment by geekzter** [comment] 2022-03-28 07:57
> Regardless of change of Agent Specification Win2019, 2022 or Win-Latest - still getting the brownout which cancels the whole thing regardless of being outside of brownout period
> 
> Current time: UTC 06:50 (March 28)
> 
> "Friday March 25, 08:00 UTC to March 25, 20:00 UTC Sunday March 28, 20:00 UTC to March 29, 08:00 UTC Tuesday March 30, 08:00 UTC to March 30, 20:00 UTC"

What pool name are you using?

**Comment by nha-vertica** [comment] 2022-03-28 10:13
> > Regardless of change of Agent Specification Win2019, 2022 or Win-Latest - still getting the brownout which cancels the whole thing regardless of being outside of brownout period
> > Current time: UTC 06:50 (March 28)
> > "Friday March 25, 08:00 UTC to March 25, 20:00 UTC Sunday March 28, 20:00 UTC to March 29, 08:00 UTC Tuesday March 30, 08:00 UTC to March 30, 20:00 UTC"
> 
> What pool name are you using?

It works now :)

We have been digging into this and the Agent was set to Win2019, but under the Init Job Task it was running as Win2016 regardless of our changes to the agent - but for some reason it works now, my colleague got a change registered with a change of AgentSpec -> identifier (null -> Windows-2019)

I made several changes but for some reason they were not kicked in even though revisiting the page showed the last windows version I chose.

What happened we don't actually know as he did the same as I did, but maybe something else were wrong in our case.
But the brownout shouldn't have happened anyway, but somewhat good as we thought we had it in order in the first place.

**Comment by miketimofeev** [comment] 2022-03-28 18:58
**Upd**: The latest brownout is shifted to Wednesday, March 30, 08:00 UTC —20:00 UTC

**Comment by Munira-Panjwani** [comment] 2022-03-28 20:53
> > Hi,
> > I have updated the yml (below) image ![image](https://user-images.githubusercontent.com/88992466/160304394-0c249559-2263-4cff-af32-0d860038e1b5.png)
> > But its failing with the error of: ![image](https://user-images.githubusercontent.com/88992466/160304427-37b26756-f0fb-4a98-934c-a0cf14e8a1eb.png)
> > Help is much appreciated.
> > Munira
> 
> You should use 'Azure Pipelines' as pool name instead of 'Hosted VS2017'

It worked now :) 

I completely removed Hosted 2017 and its taking the latest now, so Build started working 

For release deployment, I changed on the Run Agent of every step

**Comment by MMThornberg** [comment] 2022-03-29 12:22
Getting this today despite brownout should not occur today - see OP:

_"This is a scheduled windows-2016 brownout. The windows-2016 environment is deprecated and will be removed on April 1st, 2022. For more details, see https://github.com/actions/virtual-environments/issues/5238"_

**Comment by teeto** [comment] 2022-03-29 17:49
Still getting the error, this is the conf in my yml file:

pool:
  name: 'Azure Pipelines'
  vmImage: 'windows-latest'

In the logs i see is using the hosted agent, could it be the problem?

**Comment by teeto** [comment] 2022-03-29 18:01
Now it works, it has nothing to do with the yml file, its set in the release pipeline config:

![image](https://user-images.githubusercontent.com/1017314/160675724-06b3c3d3-2ee0-4895-afc5-0e548880eac0.png)

**Comment by peternznguyen** [comment] 2022-03-29 20:58
Hi,
Select Windows-Latest but
![image](https://user-images.githubusercontent.com/54497614/160705545-e9d1c3ac-125c-4b6b-9b15-d9382f0c0c48.png)
 but error
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1220,5): Error MSB3644: The reference assemblies for .NETFramework,Version=v4.5 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks

 .NETFramework,Version=v4.8 already install on Azure Virtual Machine Win-2016
![image](https://user-images.githubusercontent.com/54497614/160705981-c36873d2-ca5d-4894-8808-abc9fb3d06bf.png)

Any help much appreciated

**Comment by wildhart** [comment] 2022-03-29 22:35
I'm getting this brownout but I'm outside your published brownout schedule:

![image](https://user-images.githubusercontent.com/12505024/160717760-7e92f720-6ad1-4636-abdc-f547f66f45c8.png)

![image](https://user-images.githubusercontent.com/12505024/160717780-b91ee0d8-266e-4318-b445-c758856a24ea.png)

I'm just trying to deploy a quick hotfix using the same agent as the previous deployment...

**Comment by aroonk1982** [comment] 2022-03-29 23:41
I have tried using each of the below vmImages but still get the Brownout error
ubuntu-latest
windows-latest
windows 2019

Also tried adding 'Azure Pipelines' as the pool name, but still the same error.

![image](https://user-images.githubusercontent.com/38235329/160723771-bacf3ac6-e0f4-408c-8820-46fc7235c217.png)

**Comment by Munira-Panjwani** [comment] 2022-03-29 23:48
> I have tried using each of the below vmImages but still get the Brownout error ubuntu-latest windows-latest windows 2019
> 
> Also tried adding 'Azure Pipelines' as the pool name, but still the same error.
> 
> ![image](https://user-images.githubusercontent.com/38235329/160723771-bacf3ac6-e0f4-408c-8820-46fc7235c217.png)

Try removing the "Azure Pipelines". That worked for me

**Comment by aroonk1982** [comment] 2022-03-29 23:55
> > I have tried using each of the below vmImages but still get the Brownout error ubuntu-latest windows-latest windows 2019
> > Also tried adding 'Azure Pipelines' as the pool name, but still the same error.
> > ![image](https://user-images.githubusercontent.com/38235329/160723771-bacf3ac6-e0f4-408c-8820-46fc7235c217.png)
> 
> Try removing the "Azure Pipelines". That worked for me

Still the same error

**Comment by sebastianrogers** [comment] 2022-03-30 07:13
I had the same issue with 

```yaml
pool:
  name: Hosted
  vmImage: 'windows-latest'
```

Resolved it by removing name: Hosted

```yaml
pool:
  vmImage: 'windows-latest'
```

**Comment by LockpickingDev** [comment] 2022-03-30 19:06
I understand this will affect Workflows (Pipelines, Releases...).  Will this affect Apps already deployed and running on Azure that were deployed with Windows-2016 Builds and Releases?

**Comment by geekzter** [comment] 2022-03-31 07:18
> 

No, but it will affect your ability to-rebuild and re-deploy them.

**Comment by manishvsuryawanshi** [comment] 2022-04-01 09:28
HI, once we updated to latest version 2022, what steps needs to perform with .net code which shows below issue in CI pipeline:

##[error]C:\Users\VssAdministrator\.nuget\packages\microsoft.net.sdk.functions\1.0.24\build\netstandard1.0\Microsoft.NET.Sdk.Functions.Build.targets(41,5): Error : It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.

**Comment by jsoref** [comment] 2022-04-03 06:25
Could someone please reword this message:
> The Windows 2016 environment is deprecated, consider switching to the recent Windows environment version. For more details, see https://github.com/actions/virtual-environments/issues/4312

`the recent Windows environment version` is really grammatically awkward.

Possible fixes:
* `a recent Windows environment`
* `windows-2019, windows-2022, or windows-latest`

**Comment by miketimofeev** [comment] 2022-04-04 08:34
Windows-2016 **is not available anymore in GitHub actions** as it was announced. For ADO the retirement date has been shifted. We will update the issue once the exact date is known.

**Comment by melchiorbc** [comment] 2022-04-11 08:59
> Windows-2016 **is not available anymore in GitHub actions** as it was announced. For ADO the retirement date has been shifted. We will update the issue once the exact date is known.

Any news on a new decom date for ADO Win2016 agents? We spend a lot of effort trying to get teams/pipelines away from Win2016 agents, but since it is still up and running we unfortunately see an increase of people in our company 'accidentally' using it again.

**Comment by miketimofeev** [comment] 2022-04-11 12:28
@melchiorbc the current proposal is June, 30. We will announce it soon.

**Comment by miketimofeev** [comment] 2022-04-14 08:17
New announcement is here https://github.com/actions/virtual-environments/issues/5403

**Closed by miketimofeev** 2022-04-14 08:17 UTC
Labels: Announcement

**Comment by sachinbdoshi** [comment] 2022-04-26 15:55
Well I just closed a case with Microsoft where they confirmed that Agent Pool with vs2017-2016 will be supported until June-2022 and here this article is saying it is being deprecated in April 2022. what is the real truth ? today we received the Windows 2016 brownout error in our build pipeline which is building win 2016 container images.

link to where microsoft updated the information that they will deprecate the agent pools with vs2017-2016 in June 2022.
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software

**Comment by gene-keys** [comment] 2022-04-26 18:23
**IMPORTANT NOTE FOR THOSE OF YOU STILL STRUGGLING WITH WIN2016 BROWNOUT NOTICE.**

**_CHECK EVERYTHING!_** 

NOT JUST YOUR PIPELINE CODE, CHECK PIPELINE TRIGGERS POOLS. CHECK RELEASES POOLS, CHECK ALL THE POOLS EVERYWHERE ON YOUR DEVOPS ACCOUNT. WHAT WILL HAPPEN IS YOU WILL EVENTUALLY FIND SOMETHING STILL SET TO USE WIN2016 POOL. ONCE YOU FIND ALL OF THEM YOUR ACCOUNT WILL NO LONGER GET THE BROWNOUT NOTICE EVEN DURING THE SCHEDULED TIMES. SO IF YOU ARE GETTING THE NOTICE ITS NOT YOUR WIN2017 POOL, OR WIN-LATEST IN THE YML, ITS SOMETHING ELSE, 

AZURE NOTICES ARE DOING A TERRIBLE JOB ON THIS WITH THEIR WORDING AND WHERE THE NOTICE APPEARS. THE NOTICE MEANS YOUR AZURE DEVOPS ACCOUNT IS STILL USING WINDWOS POOL SOMEWHERE, YOU DID NOT CHECK EVEYWHERE.

**Comment by eli-schwartz** [comment] 2022-04-27 00:01
> New announcement is here #5403

I'm still getting brownout cancellations on Azure, which... mention April 1 (confusing) and link to this ticket, As a small UX thing, this should probably update the message text.

The exact job where I saw this is here: https://dev.azure.com/jussi0947/jussi/_build/results?buildId=14019&view=logs&j=e635d226-97b8-55eb-2970-00a63a10ba8b

**Comment by miketimofeev** [comment] 2022-04-27 08:10
@eli-schwartz sorry, we will change the message during the next brownout

**Comment by eli-schwartz** [comment] 2022-05-04 02:24
BTW the message is still the old one :) seen today in https://dev.azure.com/jussi0947/jussi/_build/results?buildId=14088&view=logs&j=678c5357-36f0-50cc-b96e-1a6f7149eed2

**Comment by todd-fraser** [comment] 2022-05-04 03:42
@eli-schwartz @miketimofeev is there anywhere I can find when this brownout will be over?  The only dates I've found listed out specifically are for previous dates.  I was asked to deploy after hours and now I'm getting this deprecation message I'm not able to fix tonight.  Oops.

**Comment by eli-schwartz** [comment] 2022-05-04 03:44
@todd-fraser the new brownout dates are listed at #5403 and hopefully for the next brownout we will get links pointing there instead. :)

**Comment by todd-fraser** [comment] 2022-05-04 03:46
@eli-schwartz Thanks much!  I'll keep working to change the agent tonight.  Not my expertise exactly.  Only deploying to Prod, what could possibly go wrong?

**Comment by eli-schwartz** [comment] 2022-05-04 03:53
I dunno :) for my part, the CI for a build system just fails to test whether it correctly generates VS solution files for the windows-2016 environment (technically, for vs2017, but I think windows-2016 is the only image that has vs2017 installed) so it's a bit questionable whether we should remove those jobs at all.

In the meantime we simply ignore these cancellations. At some point we'll probably switch some jobs over to vs2019 and pray that no users still have vs2017 installed (or that we don't regress for it due to lack of test coverage).

What can go wrong? We could completely fail to generate solution files for an outdated toolchain that no one should use. :laughing:

**Comment by Ziya137200** [comment] 2022-05-04 21:54
> ### Breaking changes
> Windows 2016 hosted runners were scheduled for full removal on March 15th, 2022. However, we are still seeing significant usage from customers and we want to give them more time to migrate to the new runners. In order to give customers another chance to move to either `windows-2019` or `windows-2022` we will delay the removal of `windows-2016` until April 1st, 2022.
> 
> To raise awareness of the removal, we will have rolling 12-hour periods where the image will be unavailable for customers. During these "brownout" periods, customers will see an error message indicating that the image is slated for removal on April 1st, 2022. The schedule for those brownout periods is as follows for both Azure DevOps and GitHub Actions:
> 
> 1. Tuesday March 15, 20:00 UTC to March 16, 08:00 UTC
> 2. Thursday March 17, 08:00 UTC to March 17, 20:00 UTC
> 3. Friday March 18, 20:00 UTC to March 19, 08:00 UTC
> 4. Monday March 21, 08:00 UTC to March 21, 20:00 UTC
> 5. Tuesday March 22, 20:00 UTC to March 23, 08:00 UTC
> 6. Wednesday March 23, 20:00 UTC to March 24, 08:00 UTC
> 7. Friday March 25, 08:00 UTC to March 25, 20:00 UTC
> 8. Sunday March 27, 20:00 UTC to March 28, 08:00 UTC
> 9. ~Tuesday March 29~ Wednesday March 30, 08:00 UTC to March 30, 20:00 UTC
> 10. Full removal - April 1, 15:00 UTC
> 
> See the original announcement at #4312
> 
> ### Target date
> April 1st, 2022
> 
> ### The motivation for the changes
> Windows Server 2016 Active support ends on 11 Jan 2022 and Windows Server 2022 VM image is going out of beta later this year. As part of our ongoing efforts to keep GitHub and Azure Devops hosted runners updated and secure, the Windows 2016 virtual environment will be removed from GitHub Actions and Azure DevOps.
> 
> ### Possible impact
> Workflows targeting the Windows 2016 image will fail.
> 
> ### Virtual environments affected
> * [ ]  Ubuntu 18.04
> * [ ]  Ubuntu 20.04
> * [ ]  macOS 10.15
> * [ ]  macOS 11
> * [x]  Windows Server 2016
> * [ ]  Windows Server 2019
> * [ ]  Windows Server 2022
> 
> ### Mitigation ways
> Change your workflows to use `windows-latest`, `windows-2022`, or `windows-2019`

Duplicate of #

**Comment by Kalmuraee** [comment] 2022-05-23 23:03
My issue is on deployment of the release in azure, I have no idea how to change that to windows-latest.
