### ISSUE TITLE
apt update fails on Ubuntu for 30 mins whenever Microsoft releases a new package

### ISSUE THREAD

**Issue by p--b** [actions/virtual-environments#3410] opened 2021-05-18 11:44 UTC
**Description**  
Whenever a new package is pushed to `packages.microsoft.com`,
Attempting to run `apt-get update` in a pipeline results in the application quitting with exit code `100` and issuing the following error:

```
Get:17 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 Packages [73.2 kB]
Err:17 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 Packages
  File has unexpected size (73402 != 73160). Mirror sync in progress? [IP: 13.66.21.183 443]
  Hashes of expected file:
   - Filesize:73160 [weak]
   - SHA512:782bf0315c8de4314049e599009430053b75a5015491b3d383b09239fcf31857d52bac3399cef8e813f7b2131dce09b03eaf89d79c5ebd2849402cee7aa9d228
   - SHA256:dbf4bf81b4a0a17dae53f2aff3edd4cf5bb1dcd5dcd216ce5c5c8ab7c507a26a
   - SHA1:0e1b47276cae4168a08d8fd981891d4773f053b9 [weak]
   - MD5Sum:0fcf3ed335cd4efde65300bb48c05afe [weak]
  Release file created at: Sat, 15 May 2021 00:38:08 +0000
[... other sources elided for clarity ...]
Fetched 4467 kB in 1s (3248 kB/s)
Reading package lists...
E: Failed to fetch https://packages.microsoft.com/ubuntu/20.04/prod/dists/focal/main/binary-amd64/Packages.bz2  File has unexpected size (73402 != 73160). Mirror sync in progress? [IP: 13.66.21.183 443]
   Hashes of expected file:
    - Filesize:73160 [weak]
    - SHA512:782bf0315c8de4314049e599009430053b75a5015491b3d383b09239fcf31857d52bac3399cef8e813f7b2131dce09b03eaf89d79c5ebd2849402cee7aa9d228
    - SHA256:dbf4bf81b4a0a17dae53f2aff3edd4cf5bb1dcd5dcd216ce5c5c8ab7c507a26a
    - SHA1:0e1b47276cae4168a08d8fd981891d4773f053b9 [weak]
    - MD5Sum:0fcf3ed335cd4efde65300bb48c05afe [weak]
   Release file created at: Sat, 15 May 2021 00:38:08 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

I believe this is due to https://github.com/dotnet/core/issues/4167 , which is (inexplicably) still not resolved.

`packages.microsoft.com` should be removed from the set of default apt sources until the apt repository behaves properly.

**Area for Triage**:  
Packages (?)

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [X] Ubuntu 16.04 (maybe? idk)
- [X] Ubuntu 18.04 (maybe? idk)
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
`20210510.0`

**Expected behavior**  
The release schedule of packages on `packages.microsoft.com` has no bearing on whether I can successfully run my pipeline

**Actual behavior**  
My pipeline fails whenever `packages.microsoft.com` releases a package

**Repro steps**  
1. Wait for a new package to be pushed to `packages.microsoft.com`
2. `sudo apt-get update`

**Comment by Darleev** [comment] 2021-05-18 14:35
Hello @p--b,
Thank you for the issue reported.
Currently, we are not planning to remove `package.microsoft.com` repository from Ubuntu agents. I tried to perform `apt-get update` command several times, but with no luck, I could not reproduce the issue. Could you please provide step by steps instructions or maybe a sample repo to reproduce the issue on our side? 
Also, it would be great if you add `sudo` before `apt-get` update command.
We look forward to hearing from you.

**Comment by p--b** [comment] 2021-05-18 15:49
Hi @Darleev ,

> I tried to perform apt-get update command several times, but with no luck, I could not reproduce the issue

The issue only occurs in the 30 mins or so after someone pushes a new package at `packages.microsoft.com` whilst the  repository is in an inconsistent state. You will need to wait for that to happen, as it appeared to around 0800 UTC today. I would link to a failing CI build that demonstrates this but unfortunately the build where I encountered this is not public. See https://github.com/dotnet/core/issues/4167 for more discussion - it seems that the MS team responsible for this repository are aware of this but have yet to do anything about it or communicate any concrete plan to resolve it. There appears to be some MS-internal links posted on related tickets that might perhaps shed more light to someone who has access within Microsoft:

* https://icm.ad.msft.net/imp/v3/incidents/details/193848733/home 
* https://portal.microsofticm.com/imp/v3/incidents/details/209631783/home

> Also, it would be great if you add sudo before apt-get update command.

Apologies, yes the pipeline in question was running `apt-get` as root. I have updated the steps to reproduce to clarify this.

**Comment by Darleev** [comment] 2021-05-19 10:56
@p--b at this time, we are not planning to remove `package.microsoft.com` repository from our machines due to possible impact for other users who use this repository.
According to the thread in [the provided issue](https://github.com/dotnet/core/issues/4167)(#4176), in case of issue re-occurrence a better way to keep in a touch with the repository team - fill another bug/issue to dotnet repository with all required details.
In case of any questions, feel free to contact us.

**Comment by p--b** [comment] 2021-05-19 11:23
Understood. (I'd argue that the set of people who need or care about `packages.microsoft.com` is a strict subset of people who are disrupted by non-functioning of `apt` in the image, but anyway).

Perhaps it would be a good idea to update the documentation with a warning to users that this unreliable repository is included by default, and some steps to remove it.

I don't know if you have any levers within the Microsoft machine you can pull, but if whoever runs `packages.microsoft.com` could be persuaded to fix their system that presumably would be the best outcome here.

**Comment by Darleev** [comment] 2021-05-24 11:04
@p--b according to the information above, I'm going to close the issue.
In case of any questions, feel free to contact us.

**Comment by p--b** [comment] 2021-05-24 19:22
With respect, I don't really think this issue should be closed:

1. The behaviour as described above is erroneous and results in customers paying for build minutes which will be wasted through no fault of their own.
2. The behaviour is still present in the product as currently released.

Closing the issue would imply that either (1) or (2) is not true, and makes it more difficult for other customers to understand in future why they are experiencing intermittent failures and how they might resolve it themselves. As such, I believe this issue should remain open until the problem is resolved.

> we cannot do anything on our side

I'm not sure exactly who you are referring to here but at the end of the day this repository (and product) is run by a Microsoft-owned company, so I respectfully disagree that it is impossible for anything to be done.

**Comment by AlenaSviridenko** [comment] 2021-05-26 16:47
We will try to escalate this issue, but anyway, we do not own this packages repo, and, in fact, the more customer reports .NET Core team will see in the https://github.com/dotnet/core/issues/4167 - the sooner they'll consider fixing it. So please, also post your report there for visibility.

Since this is still an external issue, I think it should be closed. 
Please, feel free to contact us in case of any questions. Thanks.

**Closed by AlenaSviridenko** 2021-05-26 16:47 UTC
Labels: OS: Ubuntu, question
