### ISSUE TITLE
Cannot resolve localhost to an IPv6 address on ubuntu-latest (all Python versions affected)

### ISSUE THREAD

**Issue by cytopia** [actions/virtual-environments#929] opened 2020-05-22 21:06 UTC
**Describe the bug**
As of today I am getting the following error resolving `localhost` to an IP address on Ubuntu latest:
```
[Errno -5] No address associated with hostname
```

The resolving process is done via Python:
```python
socket.getaddrinfo(...)
```
It affects all Python versions: 2.6, 3.5, 3.6, 3.7, 3.8 pypy2 and pypy3

This has not happened a few days ago and it also does not happen on MacOS or Windows

**Area for Triage**: 
https://github.com/cytopia/pwncat/pull/77/checks?check_run_id=700746839#step:5:2368

**Question, Bug, or Feature?**:
Bug 

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [X] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
`localhost` is resolved to `::1` (IPv6)

**Actual behavior**
The following error is thrown:
```
[Errno -5] No address associated with hostname
```
https://github.com/cytopia/pwncat/pull/77/checks?check_run_id=700886122#step:5:21

Reproducible via the following Python snippet on ubuntu-latest on all available Python versions.
```python
import socket
socket.getaddrinfo("localhost", None)
```
https://github.com/cytopia/pwncat/pull/77/checks?check_run_id=700886122#step:5:21

**Comment by cytopia** [comment] 2020-05-22 21:52
I've investigated this further and it seems like IPv6 support is simply gone: https://github.com/cytopia/pwncat/pull/77/checks?check_run_id=700860054#step:5:37

It smees to be working for IPv4, but not for IPv6 anymore.

**Comment by maxim-lobanov** [comment] 2020-05-23 05:01
Probably, similar to #668

**Comment by cytopia** [comment] 2020-05-23 10:11
> Probably, similar to #668

I don't think so. As I wrote above, the problem started as of today (yesterday). It all worked fine before.

**Comment by miketimofeev** [comment] 2020-05-23 10:28
@cytopia does the same happen on Ubuntu 16? I wonder if it's related to this PR https://github.com/actions/virtual-environments/pull/881

**Comment by cytopia** [comment] 2020-05-23 10:30
Give me a few minutes, will add pipelines for these to try it out

**Comment by cytopia** [comment] 2020-05-23 10:38
Seems to be the same issue on Ubuntu 16: https://github.com/cytopia/pwncat/runs/701818515?check_suite_focus=true#step:5:22 No IPv6 support available anymore

**Comment by al-cheb** [comment] 2020-05-23 11:29
@cytopia 

Could you please test with step?
```
sudo bash -c "cat > /etc/hosts" << EOL
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
EOL
```

**Comment by cytopia** [comment] 2020-05-23 11:32
@al-cheb is there something where I can tell it for a step to only do this on Linux?

**Comment by al-cheb** [comment] 2020-05-23 11:36
```
if [ `uname` = "Linux" ]; then
sudo bash -c "cat > /etc/hosts" << EOL
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
EOL
fi
```

**Comment by cytopia** [comment] 2020-05-23 11:59
Looks good so far. I can resolve it to IPv6 again. Will however also wait for the whole pipeline and report back here

**Comment by agrobbin** [comment] 2020-05-26 16:55
@al-cheb we've started running into a very similar issue, specifically with [Percy.io's](https://percy.io/) image downloading functionality:

```
Error: getaddrinfo ENOTFOUND [foo.bar].localhost
```

We use `.localhost` as a TLD, which up until 5/22 worked just fine, but starting on 5/22 (and I believe alongside the `20200518.1` virtual env release), requests for our assets on that domain are no longer working.

I tried including your suggested change to `/etc/hosts`, and unfortunately still no luck. Any help here would be greatly appreciated!

**Comment by al-cheb** [comment] 2020-05-26 17:30
Hello, @agrobbin
Could you please validate with step?

```
- name: revert
  run: | 
        sudo ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf
```

**Comment by agrobbin** [comment] 2020-05-26 19:17
@al-cheb that line did the trick!

**Comment by agrobbin** [comment] 2020-05-26 19:27
@al-cheb is this something that will be resolved in a future virtual environment release, or should we anticipate having to include this in our Actions YAML file going forward?

**Comment by al-cheb** [comment] 2020-05-26 19:36
@agrobbin, Sorry for the inconvenience. We are planning to revert the https://github.com/actions/virtual-environments/pull/881 PR that is the root cause of this issue. Not until we roll-out a new image with a fix you should use the temporary workaround. I will provide feedback to you when we can delete the workaround.

**Comment by agrobbin** [comment] 2020-05-26 19:37
Sounds good, @al-cheb thanks again for all of your help! In the meantime, I'll keep an eye on these issues.

**Comment by yidongnan** [comment] 2020-06-11 03:25
![image](https://user-images.githubusercontent.com/3163314/84341577-085ec100-abd6-11ea-9b64-e18b983586af.png)

https://github.com/yidongnan/grpc-spring-boot-starter/runs/760320005?check_suite_focus=true#step:3:7

I still have this problem after deleting this patch, is there any cache here?

**Comment by al-cheb** [comment] 2020-06-11 06:40
@yidongnan, Hello
Could you please try to test  https://github.com/actions/virtual-environments/issues/929#issuecomment-633032894 ?

**Comment by yidongnan** [comment] 2020-06-11 06:51
> @al-cheb I just confirmed that removing our patch for this issue no longer causes resolution issues. Looks like things are fixed! Thanks so much for your help.

@al-cheb Using this patch will work, I read the comment  saying that the patch removal is work. I thought the problem was fixed, but when I removed the patch, it found that it did not work.

This is my modification
https://github.com/yidongnan/grpc-spring-boot-starter/pull/367

**Comment by al-cheb** [comment] 2020-06-11 07:16
> > @al-cheb I just confirmed that removing our patch for this issue no longer causes resolution issues. Looks like things are fixed! Thanks so much for your help.
> 
> @al-cheb Using this patch will work, I read the comment saying that the patch removal is work. I thought the problem was fixed, but when I removed the patch, it found that it did not work.
> 
> This is my modification
> [yidongnan/grpc-spring-boot-starter#367](https://github.com/yidongnan/grpc-spring-boot-starter/pull/367)

I think we have got several issues one with resolving IPv4 localhost(revert fixed the issue) and the second one with IPv6.

**Comment by al-cheb** [comment] 2020-06-23 14:44
Hello, @yidongnan 
I can reproduce this behavior with resolving IPv6 localhost name on clean Ubuntu VMs with OS version 18.04+(Azure VM, Hyper-V). The default `/etc/hosts` file on Ubuntu Server 14.04+ is (e.g. for other linux distros - https://gist.github.com/ghoneycutt/e531984406b4b86ace687ea8958a6dc3#file-hosts-md):

![image](https://user-images.githubusercontent.com/47745270/85415373-ed953080-b575-11ea-9e97-06d7234d38dc.png)


I have created a simple test:

```
import java.net.InetAddress;

public class Test {
    public static void main(String[] args) throws Exception {
        InetAddress[] inetAddresses = InetAddress.getAllByName(args[0]);
        for(InetAddress inet : inetAddresses){
            System.out.println(inet);
        }
    }
}
```

Output:
```
ubuntu:~$ java -classpath . Test localhost
localhost/127.0.0.1
ubuntu:~$ java -classpath . Test ip6-localhost
ip6-localhost/0:0:0:0:0:0:0:1
```

Update `/etc/hosts/` file and add the alias `localhost` for `::1`:
```
ubuntu:~$ sed -i 's/::1 ip6-localhost ip6-loopback/::1     localhost ip6-localhost ip6-loopback/g' /etc/hosts
ubuntu:~$ java -classpath . Test localhost
localhost/127.0.0.1
localhost/0:0:0:0:0:0:0:1
```
We are not planning to change/update default name resolution due to unexpected behaviors for other customers.

Workaround:
1. Add  the alias `localhost` for `::1` manually to the pipeline - https://github.com/actions/virtual-environments/issues/929#issuecomment-633032894
2. Change `localhost` name to `ip6-localhost` or `::1` in your test
3. Use only `127.0.0.1` or `::1`

**Comment by yidongnan** [comment] 2020-06-24 02:56
> We are not planning to change/update default name resolution due to unexpected behaviors for other customers.

@al-cheb Thanks for your reply,  I see that ubuntu 18.04 and 14.04 have added ::1 localhost by default, so I think it’s more appropriate to be consistent with the ubuntu official. I think that only by being consistent will no unexpected behavior happen.

![image](https://user-images.githubusercontent.com/3163314/85492538-e880c180-b607-11ea-9ae2-a5ed708bbf14.png)
![image](https://user-images.githubusercontent.com/3163314/85492714-31387a80-b608-11ea-8d0a-594be044d066.png)

**Comment by al-cheb** [comment] 2020-07-01 16:34
Hello, @yidongnan
Fix with alias for ::1 localhost has been deployed. Could you please check from your side?

**Comment by yidongnan** [comment] 2020-07-02 02:49
@al-cheb Looks like things are fixed! Thanks so much for your help.

**Closed** 2020-07-02 06:09 UTC
Labels: Area: Image administration, OS: Ubuntu, awaiting-deployment
