### ISSUE TITLE
GitHub Actions has encountered an internal error when running your job.

### ISSUE THREAD

**Issue by arvinxx** [actions/virtual-environments#2579] opened 2021-01-28 12:41 UTC
**Description**  

when trigger an action, it return the
```
GitHub Actions has encountered an internal error when running your job.
```

**Area for Triage**:  

JavaScript and Node.js

**Question, Bug, or Feature?**:  

Question

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [x ]  Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x ]  macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ x]  Windows Server 2019

**Expected behavior**  

release job should run

**Actual behavior**  
return an error 
```
GitHub Actions has encountered an internal error when running your job.
```

**Repro steps**  

Release configuration yml is here 

https://github.com/arvinxx/umi-electron-template/blob/master/.github/workflows/release.yml

**Comment by andy-mishechkin** [comment] 2021-01-28 14:10
Hello, @arvinxx 
I see, you workflow works without any errors many times. Did you get this error always when you triggered action or sometimes ?
Usually internal errors related to internal GitHub issues. Here is the example:
https://github.com/actions/virtual-environments/issues/2179
You can check the GitHub incidents history here: https://www.githubstatus.com/history (I see we had one incident for today: https://www.githubstatus.com/incidents/tf9v5jjmq2lg , perhaps it was a reason of your internal error).
Thank you.

**Comment by arvinxx** [comment] 2021-01-28 14:22
I get this error always after I change a configuartion. Is there something wrong on my configuration ?
```diff
check:
    name: Code quality check
    runs-on: ubuntu-latest
    outputs:
      # use for build
      semantic: ${{ toJSON(steps.semantic.outputs) }} # ! MUST BE STRING

  build:
    needs: check
    name: Build
+   if: fromJSON(needs.check.outputs.semantic).new_release_published == 'true'
```

**Comment by arvinxx** [comment] 2021-01-31 15:31
is there any update?

**Comment by dsame** [comment] 2021-02-01 14:59
@arvinxx is it possible to get the output of this step (id=semantic)?
https://github.com/arvinxx/umi-electron-template/blob/2a89d6f3ce6ab08d7ab10c1724970b8beac50606/.github/workflows/release.yml#L38

I suppose it is possible if you comment out the condition `if: fromJSON(needs.check.outputs.semantic).new_release_published == 'true'`

**Comment by arvinxx** [comment] 2021-02-01 15:03
Actual I have log the output [here](https://github.com/arvinxx/umi-electron-template/blob/2a89d6f3ce6ab08d7ab10c1724970b8beac50606/.github/workflows/release.yml#L96).
You can find the result [here](https://github.com/arvinxx/umi-electron-template/runs/1806144403?check_suite_focus=true)

**Comment by dsame** [comment] 2021-02-01 22:01
@arvinxx yes, i see the output of the "Semantic Release with dryRun" but i meant "supposed to be parsed". Sorry i was not clear. I wonder where's output name::value set to the `name=new_release_published::something`

Can you please to change you flow a bit:
1. replace `{{ toJSON(steps.semantic.outputs) }}` with `{{ steps.semantic.outputs. new_release_published }}`
here https://github.com/arvinxx/umi-electron-template/blob/2a89d6f3ce6ab08d7ab10c1724970b8beac50606/.github/workflows/release.yml#L13
2. replace all occurrences of `fromJSON(needs.check.outputs.semantic).new_release_published`  to `needs.check.outputs.semantic`

I expect eliminating of JSON conversions either make the build to success or provide more clear error message

**Comment by arvinxx** [comment] 2021-02-02 02:34
It's fixed! Thanks for your help.

But I'm still wondering why I can't use the toJSON and fromJSON function? which is easier to use when there are lots of properties.

**Comment by dsame** [comment] 2021-02-02 04:17
@arvinxx yes, you are right - the issue with JSON still exists and i'm continue to investigate it.

**Comment by maxim-lobanov** [comment] 2021-02-02 07:02
`toJSON` and `fromJSON` methods are implemented on [actions/runner](https://github.com/actions/runner) level. May be @TingluoHuang , @thboop can help here.

**Comment by AlenaSviridenko** [comment] 2021-02-09 09:24
Hi @TingluoHuang, @thboop,
could you please take a look when you have a chance? Maybe it makes sense to move this issue to your board?

**Comment by robdiciuccio** [comment] 2021-02-12 23:47
Similarly, I am experiencing repeated errors ("GitHub Actions has encountered an internal error when running your job.") when some jobs are run. There is no log output, and the same workflow will eventually run without error, but the error rate is extremely high.

https://github.com/robdiciuccio/incubator-superset/actions/runs/562539973

Please advise.

**Comment by dhuyck** [comment] 2021-03-04 19:36
We are suddenly encountering this as well. If this is caused by a configuration error, it would be helpful if that could be surfaced in the error language.

As it is, it reads as if there is a problem on the Github side that should resolve itself. I can't tell if I should be looking for bugs in my code and config, or if I should wait for an errant Github issue to resolve and then re-run my deploy.

**Comment by kavin25** [comment] 2021-03-05 05:50
Even I'm facing this problem now

**Comment by AlenaSviridenko** [comment] 2021-03-12 16:05
Hi @robdiciuccio, @dhuyck, 
this error is very generic, so please, create separate issues with repro if possible for our further investigation.
The original issue with runner and `fromJSON` was fixed. I am going to close this issue.
Thanks.

**Closed by AlenaSviridenko** 2021-03-12 16:05 UTC
Labels: Area: Deployment / Release, investigate
