### ISSUE TITLE
sudo environment pass-through behavior is confusing with Go

### ISSUE THREAD

**Issue by estesp** [actions/virtual-environments#731] opened 2020-04-16 13:43 UTC
**Describe the bug**
When using the [setup-go](https://github.com/actions/setup-go) action to specify an exact release of the Go toolchain, if any follow-on commands in other steps use `sudo` and then, within context as the root user, perform any step which relies on a Go toolchain binary, the `GOROOT` environment used will default back to the latest Go release installed on the ubuntu-18.04 image; today that is Go 1.14.x. This will generate errors, for example, if compiling code which tries to link in Go language standard library content, using the Go binaries in the `$PATH` which will generate mismatch errors given the `setup-go` environment of some non-Go1.14 release:
```
# runtime/internal/atomic
compile: version "go1.14.1" does not match go tool version "go1.13.10"
```

Passing `GOROOT` through the `sudo` command does *not* work; unlike other environment variables which do appear to pass through. For example I can add `sudo GOROOT=$GOROOT _GOROOT=$GOROOT PATH=$PATH GOPATH=$GOPATH` to a command and find that within the environment of the commands run that my special "underscore-prefixed" `_GOROOT` does pass through, and apparently all the other variables, but `GOROOT` itself is reset!?

Output before sudo:
```
GOROOT="/opt/hostedtoolcache/go/1.13.10/x64"
```

Output after sudo:
```
GOROOT="/usr/local/go1.14"
_GOROOT="/opt/hostedtoolcache/go/1.13.10/x64"
```

**Area for Triage**: 
Go

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
I expect that, as long as I pass-through the right Go environment it will be preserved in the context of the commands run with `sudo`. I also would have hoped `sudo -E` would work, but it may be turned off by the configuration of the virtual Ubuntu environment. There is no documentation on the configuration and operation of `sudo` at this time to validate behavior.

**Actual behavior**
I described the behavior of at least `GOROOT` being inexplicably reset during the call through `sudo` but other variables seem to be preserved if passed through.

I created a [repo with actions](https://github.com/estesp/actions-playground) that reproduces the problem.

**Comment by vsafonkin** [comment] 2020-04-21 08:39
Hi @estesp , thank you for the report of this issue! The cause of the issue is Linux security policy that overrides system `$PATH` to default value for sudo. As workaround you can use next step after setup-go task to create symlinks in `/usr/bin` directory for installed Go version:
```
- name: create symlink
  run: sudo ln -f -s $GOROOT/bin/* /usr/bin/ 
```
and use `sudo -E` for preserving user environment in following steps.

**Comment by vsafonkin** [comment] 2020-05-08 09:42
Hi @estesp , I close this issue, please, feel free reopen it if you have any concerns, thank you!

**Closed** 2020-05-08 09:42 UTC
Labels: Area: Go, Area: Image administration, OS: Ubuntu, investigate

**Comment by tianon** [comment] 2020-11-05 22:07
FWIW, the simpler solution here is to combine `sudo -E` with an explicit `PATH`, ala: `sudo -E PATH="$PATH" ...`
