### ISSUE TITLE
Packer build success rate inconsistent 

### ISSUE THREAD

**Issue by dwizzle204** [actions/virtual-environments#1359] opened 2020-08-04 20:08 UTC
**Describe the bug**
Packer builds Ubuntu18 inconsistent. We are struggling to get consistent successful builds out of packer because of the large amount of scripts used together to perform the software installs. With any hiccup in the process the 3hr build can be disrupted and required to start again from scratch.

**Area for Triage**: 

**Question, Bug, or Feature?**: 

Add retry failed attempts into packer config or migrate some of the software installs to ansible when possible

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**
Packer builds should succeed at a higher rate then they do now.

**Actual behavior**
Out of 10 packer builds(using identical configuration) only 4 were successful

**Comment by vmapetr** [comment] 2020-08-05 01:32
Hi @dwizzle204!
Could you please provide some examples of failed builds? It can help us to improve provisioners stability.

**Comment by miketimofeev** [comment] 2020-08-05 07:41
@dwizzle204 we have build pass rate >80%. Could you try suggestions from this thread and change Azure location https://github.com/actions/virtual-environments/issues/507?
Unfortunately, packer doesn't support retries at the moment but we'll appreciate if you provide a PR with some helper retry functions for ubuntu images, which can be used during provision.

**Comment by dwizzle204** [comment] 2020-08-05 14:19
@vmapetr I will get you exact error messages when I return to the office but the firefox.sh script was one for sure I remember being very inconsistent. Looking now it seems there has been some recent modifications to the script so we'll re-pull and see if the problem persists.

@miketimofeev  I was thinking along the lines of https://www.packer.io/docs/templates/provisioners.html#retry-on-error unless I'm missing the functionality the purpose of max_retries

**Comment by miketimofeev** [comment] 2020-08-05 14:22
@dwizzle204 yeah, we had an issue with firefox gecko driver last week, but now the issue is resolved. Thanks for provided link, looks like it's a new feature, we'll give it a try!

**Comment by maxim-lobanov** [comment] 2020-11-18 11:31
Unfortunately, packer retries don't work well for us because it retries the whole provisioner.
If you have something like
```json
{
    "type": "shell",
    "scripts": [
        "./provision/core/xcode-clt.sh",
        "./provision/core/homebrew.sh",
        "./provision/core/dotnet.sh",
        "./provision/core/node.sh"
    ]
},
```
If `node.sh` fails, it will retry all these scripts. 

We have implemented retry logic in different places of Ubuntu image-generation so I am going to close this issue.
If you see any specific scripts that constantly fails during image-generation, please report them as a separate issue.

**Closed by maxim-lobanov** 2020-11-18 11:31 UTC
Labels: OS: Ubuntu, investigate
