### ISSUE TITLE
add .dotnet/tools to path

### ISSUE THREAD

**Issue by Jetersen** [actions/virtual-environments#213] opened 2019-12-29 14:12 UTC
**Describe the bug**
DotNet global tool path should be added to path.

I tried to fix it in https://github.com/actions/setup-dotnet however I was suggested to submit a patch for the virtual environments.

See https://github.com/actions/setup-dotnet/pull/70

**Area for Triage**: .NET Core

**Feature**:

**Virtual environments affected**
- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [N/A] Windows Server 2016 R2
- [WORKS] Windows Server 2019

**Expected behavior**
after installing a dotnet tool it should be accessible.

```bash
dotnet tool install -g gitversion
dotnet gitversion -versiom
5.1.3+Branch.master.Sha.bef8ebc0b62b3ddd0cdafe09b66d68bbfcaf90d5
```

**Actual behavior**
See my repro:
https://github.com/casz/setup-dotnet-global-tool-repro
See my fix working for setup-dotnet action:
https://github.com/casz/setup-dotnet-global-tool-repro/blob/testingFix/.github/workflows/ci.yml

```bash
dotnet tool install -g gitversion
dotnet gitversion -version
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-gitversion does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```

**Comment by casz** [comment] 2019-12-29 14:24
This does not behave as intended:
https://github.com/actions/virtual-environments/blob/95954b3f022a1c4626d112bd4fe82d0812fa6f4b/images/linux/scripts/installers/1804/dotnetcore-sdk.sh#L94

**Comment by casz** [comment] 2019-12-29 14:42
Added tests for all OSes listed here: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idruns-on

See https://github.com/casz/setup-dotnet-global-tool-repro/runs/366837035

**Comment by casz** [comment] 2019-12-29 20:41
Most likely a .NET Core area rather than Git area 😅 
cc @bishal-pdmsft @pulkitaggarwl

**Comment by casz** [comment] 2020-01-06 18:28
I can confirm this also affects Linux and Mac environments on Azure Pipeline.

**Comment by casz** [comment] 2020-01-07 19:24
for anyone using GitHub actions and would like a workaround

Use my branch for actions/setup-dotnet
```yaml
      - name: Setup dotnet
        uses: casz/setup-dotnet@fix/dotnet-global-tool
        with:
          dotnet-version: '3.1.100'
```

**Comment by magne** [comment] 2020-01-08 13:33
I've used the following as a work-around on a Linux worker:
```
      - name: Install SonarCloud scanner
        run: |
          dotnet tool install --global dotnet-sonarscanner --version 4.8.0
          echo "::set-env name=PATH::${PATH}:${HOME}/.dotnet/tools"
```

**Comment by casz** [comment] 2020-02-01 08:16
@bishal-pdMSFT any word on a fix?

**Comment by alepauly** [comment] 2020-02-03 18:42
@casz sorry for the delay, we'll look into this as soon as possible.

**Comment by dotMorten** [comment] 2020-02-04 07:10
Why install globally though? Can't you just install local instead?

**Comment by casz** [comment] 2020-02-04 07:51
Because global in dot tools means installing into the user's folder and putting the tool on path.

Their windows virtual environment already has dotnet tool on path.

**Comment by casz** [comment] 2020-02-04 08:05
Basically I would like to avoid calling all the things needed to install locally.
```bash
dotnet new tool-manifest
dotnet tool install gitversion.tool
dotnet tool run gitversion.tool /output buildserver
```

**Comment by dotMorten** [comment] 2020-02-04 13:53
All the things? It's one an extra parameter during install, and a little extra path in front of the command that launches it.
Is this a convenience thing or a blocker?j
Personally I like it as it creates a nice isolation - especially if you're dealing with multiple versions

**Comment by casz** [comment] 2020-02-04 15:21
It's an unexpected behavior that I would consider blocking or an annoyance having to spent time figuring out why Linux and Mac cannot run tools that I install using `--global`

Whether I install locally or globally is out of the scope of the issue.

The commands work on Windows virtual environments but not Linux/Mac.

**Comment by casz** [comment] 2020-02-04 16:12
I'd like to preface this is in the context of using GitHub actions or Azure pipelines.

Locally on my machine I am using local install for some tools.

**Comment by casz** [comment] 2020-02-12 09:39
Since Mac is not yet open source I hope a similar fix has been added for Macs?

**Comment by maxim-lobanov** [comment] 2020-02-12 09:59
@casz, Yep, we have prepared the same fix for macOS. It is being tested right now. We will keep this issue opened until both fixes are deployed

**Comment by casz** [comment] 2020-02-12 10:00
👏 Thanks ❤️

**Comment by MaksimZhukov** [comment] 2020-02-25 07:57
Hello @casz  , unfortunately, adding the "export PATH" command to the `.bashrc` file didn't solve the issue. We'll continue to work on it.

**Comment by al-cheb** [comment] 2020-03-18 14:41
Hello, @Jetersen 
The PATH environment variable has been updated for Ubuntu/macOS images.

**Closed by al-cheb** 2020-03-18 14:41 UTC
Labels: Area: .NET Core, OS: Ubuntu, OS: macOS, awaiting-deployment, enhancement

**Comment by Jetersen** [comment] 2020-03-18 14:49
Many thanks! 👏

**Comment by gitfool** [comment] 2020-03-18 18:27
Awesome, but could we please change it to _prepend_ the dotnet tools path; i.e.
from:
```
echo "PATH=${CARGO_HOME}/bin:${PATH}:${DOTNET_TOOLS_HOME}:${PHP_COMPOSER_HOME}" | tee -a /etc/environment
```
to:
```
echo "PATH=${CARGO_HOME}/bin:${DOTNET_TOOLS_HOME}:${PATH}:${PHP_COMPOSER_HOME}" | tee -a /etc/environment
```
And please do the same for Windows.
