### ISSUE TITLE
An error occurred while provisioning resources on windows-2022

### ISSUE THREAD

**Issue by mchernyavsky** [actions/virtual-environments#4619] opened 2021-11-29 00:13 UTC
### Description

I'm trying to set up WSL with Rust toolchain via [Setup WSL](https://github.com/marketplace/actions/setup-wsl) action on Windows Server 2022, but my builds hang and crash with an error (see below).

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Build: https://github.com/intellij-rust/intellij-rust/runs/4332945286

### Is it regression?

No

### Expected behavior

The build doesn't hang.

### Actual behavior

The build hangs and then fails with error:

<img width="659" alt="Screenshot 2021-11-26 at 13 40 32" src="https://user-images.githubusercontent.com/6079006/143568246-a71b3bd2-ff3e-4630-b8aa-f7013f8e5078.png">

### Repro steps

Repush last commits in https://github.com/intellij-rust/intellij-rust/pull/7285.

**Comment by shilovmaksim** [comment] 2021-11-29 07:15
Hi @mchernyavsky. Thank you for your report. We will take a look. Could you please provide minimal workflow or slightly more detailed repro steps to help us with the investigation process.

**Comment by mchernyavsky** [comment] 2021-12-01 18:35
@shilovmaksim

1. Create a fork of https://github.com/intellij-rust/intellij-rust repo
2. Enable `check` workflow
3. Create a PR from `wsl-tests` into your main branch

PR in my fork fails with the same result - https://github.com/mchernyavsky/intellij-rust/pull/3

**Comment by dibir-magomedsaygitov** [comment] 2021-12-06 16:34
Hello @mchernyavsky. I've investigated the issue and looks like the root cause was temporary connection issues. I wasn't able to reproduce the issue anymore and as I can see your builds are passing now. Could you please confirm that the issue is not appearing anymore.

**Comment by mchernyavsky** [comment] 2021-12-07 01:22
@dibir-magomedsaygitov

> Could you please confirm that the issue is not appearing anymore.

I still have this issue:
* In intellij-rust repo - https://github.com/intellij-rust/intellij-rust/actions/runs/1546646297
* In my fork - https://github.com/mchernyavsky/intellij-rust/actions/runs/1546766549

**Comment by dibir-magomedsaygitov** [comment] 2021-12-08 11:58
Hello @mchernyavsky. I was able to reproduce the issue on Windows-2022 with your latest changes, but without them - the issue is not appearing. Also, the build doesn't hang if you will use `bash` instead of `wsl-bash {0}` as a shell in `Check environment` step.
Looks like your latest changes are causing the issue or there is an issue in [setup-wsl](https://github.com/Vampire/setup-wsl) action. Unfortunately, we are not experts in `Kotlin `or `setup-wsl` action. Could you please check your project or contact maintainers of the `setup-wsl` action for possible breaking changes?

**Comment by mchernyavsky** [comment] 2021-12-10 12:37
I have created an issue in [setup-wsl](https://github.com/Vampire/setup-wsl) repo - https://github.com/Vampire/setup-wsl/issues/15

**Comment by dibir-magomedsaygitov** [comment] 2021-12-17 07:13
Hello @mchernyavsky. Looks like this issue is [related to rust](https://github.com/Vampire/setup-wsl/issues/15#issuecomment-996383061). I'm going to close this one, but feel free to contact us if you have any questions or concerns. Thank you!

**Closed by dibir-magomedsaygitov** 2021-12-17 07:14 UTC
Labels: OS: Windows, Area: Common Tools, investigate
