### ISSUE TITLE
Rust Tools Unavailable in Ubuntu 18.04 20211129.1

### ISSUE THREAD

**Issue by reynoldsbd** [actions/virtual-environments#4658] opened 2021-12-02 16:39 UTC
### Description

My team's pipeline started failing after the latest Ubuntu 18.04 20211129.1 image was pushed out. It seems that Rust tools such as rustup/cargo/etc. are no longer in PATH.

### Virtual environments affected

- [X] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image Version: 20211129.1

Can't share a build link as this is a private build.

### Is it regression?

Yes, this is a regression. Everything was working on 20211122.1

### Expected behavior

My pipeline should be able to directly call Rust CLI tooling such as the rustup or cargo commands without any additional configuration.

### Actual behavior

Any attempt to call rust CLI tooling fails with errors such as "no such file or directory"

### Repro steps

Example Azure DevOps pipeline which is impacted by this issue:

```yaml
pool:
  vmImage: ubuntu-18.04

steps:
- pwsh: cargo build
```

**Comment by reynoldsbd** [comment] 2021-12-02 17:16
Looks like PATH might be messed up. It contains multiple entries with the literal text `$HOME`. I also don't see any entry for rustup.

The following is output from the PowerShell command `$Env:PATH -split ":"`

```
Dumping PATH:
/opt/microsoft/powershell/7
/home/linuxbrew/.linuxbrew/bin
/home/linuxbrew/.linuxbrew/sbin
$HOME/.local/bin
/opt/pipx_bin
$HOME/.cargo/bin
$HOME/.config/composer/vendor/bin
/usr/local/.ghcup/bin
$HOME/.dotnet/tools
/snap/bin
/usr/local/sbin
/usr/local/bin
/usr/sbin
/usr/bin
/sbin
/bin
/usr/games
/usr/local/games
/snap/bin
```

Perhaps this is related to #4575?

**Comment by reynoldsbd** [comment] 2021-12-02 17:42
If anybody is looking for a workaround (ADO-specific):

```yaml
  - pwsh: |
      Write-Host "##vso[task.prependpath]$Env:HOME/.cargo/bin"
    displayName: Fix Rust PATH
```

**Comment by mikhailkoliada** [comment] 2021-12-02 19:15
Hello @reynoldsbd!
I have written somewhat pretty plain (`head` is just to compress the output and show that binaries are there):

```
trigger:
- main

pool:
  vmImage: ubuntu-18.04

steps:
- pwsh: |
    cargo --help | head -5
    rustup --help | head -5
```
![image](https://user-images.githubusercontent.com/88318005/144487111-e0d8fc32-a6e1-41c4-b287-6a482b1f6317.png)

with the `Current image version: '20211202.1'`

As of `$HOME` in `$PATH` there is nothing wrong with it as it holds the home path of the current user and gets expanded during execution. Please check your project settings.

Considering all above I am going to close the issue, but feel free to re-open it if you have concerns/questions.

**Closed by mikhailkoliada** 2021-12-02 19:15 UTC
Labels: needs triage

**Comment by reynoldsbd** [comment] 2021-12-02 20:30
Thanks for taking a look @mikhailkoliada! Hopefully I just need to move to the latest image version. Still figuring out how to do that on my internal agent pool - will reply with my result once I know more.

---

The following isn't true on Linux:

> As of $HOME in $PATH there is nothing wrong with it as it holds the home path of the current user and gets expanded during execution.

Unlike Windows, environment variable references within PATH are not automatically expanded on Linux. Usually this expansion is performed by the shell while processing _~/.profile_, before the variable is actually set. If I had to guess, I'd say that _~/.profile_ contains (contained?) single-quotes when it really should contain double-quotes.

**Comment by reynoldsbd** [comment] 2021-12-03 15:36
Okay I've got a little more information.

I ran my test on the default "ubuntu-18.04" image and everything works fine. The issue seems specific to our internally-hosted (1ES) agent pools. These pools use the same VM images, but I believe there may be something different about the way the user account is provisioned.

Following up internally to understand more.

**Comment by miketimofeev** [comment] 2021-12-06 14:28
@reynoldsbd I believe, the changes that caused this issue were introduced here and it's by design
https://github.com/actions/virtual-environments/pull/4575
