### ISSUE TITLE
Azure Pipeline task goes to time out when running Visual Studio 2022 from windows-2022 env

### ISSUE THREAD

**Issue by xpouyat** [actions/virtual-environments#4880] opened 2022-01-13 15:22 UTC
### Description

When running windows-2022 env to run Visual Studio 2022 with Azure DevOps CmdLine@2 task, the task runs fine but does not detect that Visual Studio 2022 finished the work.
After 58 min, the task timeout, and job fails.

I call this task to build a MSI based on a Microsoft Installer Project in the solution, for a .NET 6 application.
Microsoft Installer Project is in windows-2022 env.

I experience the same issue with [DevEnvBuild](https://github.com/mmajcica/DevEnvBuild) task. Works with Visual Studio 2019 (, timeout with Visual Studio 2022.

I opened an issue [here](https://github.com/microsoft/azure-pipelines-tasks/issues/15697) but it looks like a potential issue with the windows-2022 environment.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20211219.1

### Is it regression?

yes. Works fin with windows-2019 and Visual Studio 2019

### Expected behavior

The task should end when Visual Studio 2022 finished to build the solution. No timeout.

### Actual behavior

![2022-01-12_10h17_48](https://user-images.githubusercontent.com/8104205/149353611-77f46e49-e822-4dff-b3ec-78645fcda963.png)

```
2022-01-11T21:28:43.9707538Z Updating the Control table...
2022-01-11T21:28:43.9716755Z Updating the ControlEvent table...
2022-01-11T21:28:43.9718617Z Updating the CustomAction table...
2022-01-11T21:28:43.9720316Z Updating the Property table...
2022-01-11T21:28:43.9720854Z
2022-01-11T21:28:43.9722779Z Post-build events finished
2022-01-11T21:28:43.9926453Z ========== Rebuild All: 2 succeeded, 0 failed, 0 skipped ==========
2022-01-11T22:23:29.7358977Z ##[debug]Re-evaluate condition on job cancellation for step: 'CmdLine'.
2022-01-11T22:23:37.3714210Z Terminate batch job (Y/N)?
2022-01-11T22:23:37.5307904Z Entering debug mode. Use h or ? for help.
2022-01-11T22:23:37.5308679Z
2022-01-11T22:23:37.5630910Z At D:\a_tasks\CmdLine_d9bafed4-0b18-4f58-968d-86655b4d2ce9\2.182.0\ps_modules\VstsTaskSdk\ToolFunctions.ps1:113
2022-01-11T22:23:37.5632056Z char:13
2022-01-11T22:23:37.5632349Z
2022-01-11T22:23:37.5632851Z + if ($originalEncoding) {
2022-01-11T22:23:37.5633211Z
2022-01-11T22:23:37.5633733Z + ~~~~~~~~~~~~~~~~~
2022-01-11T22:23:37.8131767Z ##[debug]Leaving Invoke-VstsTool.
2022-01-11T22:23:37.8475086Z ##[debug]Leaving D:\a_tasks\CmdLine_d9bafed4-0b18-4f58-968d-86655b4d2ce9\2.182.0\cmdline.ps1.
2022-01-11T22:23:37.9330128Z ##[error]The operation was canceled.
2022-01-11T22:23:37.9349411Z ##[debug]System.OperationCanceledException: The operation was canceled.
at System.Threading.CancellationToken.ThrowOperationCanceledException()
at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
at Microsoft.VisualStudio.Services.Agent.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.DefaultStepHost.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, CancellationToken cancellationToken)
at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.PowerShell3Handler.RunAsync()
at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
2022-01-11T22:23:37.9359065Z ##[section]Finishing: CmdLine
```

Task waits for 50 min after Visual Studio completed :
**2022-01-11T21:28:43.9926453Z** ========== Rebuild All: 2 succeeded, 0 failed, 0 skipped ==========
**2022-01-11T22:23:29.7358977Z** ##[debug]Re-evaluate condition on job cancellation for step: 'CmdLine'.

### Repro steps

Use AzureDevops with windows-2022 to build a Visual Studio 2022 Solution.
Job YAML is

```
trigger:
  branches:
    include:
    - master
variables:
- name: solution
  value: '**/*.sln'
- name: buildPlatform
  value: 'Any CPU'
- name: buildConfiguration
  value: 'Release'
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: 'windows-2022'
    steps:
    - task: NuGetToolInstaller@1
    - task: NuGetCommand@2
      inputs:
        restoreSolution: '**\AMSExplorer\AMSExplorer.csproj'
    - task: CmdLine@2
      inputs:
        script: '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com" AMSExplorer.sln /Rebuild Release'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)\Setup\Release'
        artifact: 'Signed'
        publishLocation: 'pipeline'
```

When the task CmdLine@2 executes, the task does not detect that Visual Studio 2022 ended.

**Comment by al-cheb** [comment] 2022-01-13 15:27
Hey @xpouyat! 
Could you please share a small app to reproduce the issue?

**Comment by xpouyat** [comment] 2022-01-13 15:37
@al-cheb Ok, I will prepare this

**Comment by xpouyat** [comment] 2022-01-13 18:14
@al-cheb
[project-with-yml.zip](https://github.com/actions/virtual-environments/files/7865044/project-with-yml.zip)
Here is a very simple VS 2022 solution with a .Net 6  app and an installer project. The YML is also in the zip file.
You will experiment two issues I guess :
- task takes 7 min to run Visual Studio 2022 (improvement would be nice but that's ok)
- when Visual Studio 2022 finishes to build the solution and MSI, task still wait until a timeout of 1 hour

**Comment by nikolai-frolov** [comment] 2022-01-18 09:49
Hello @xpouyat, I was able to reproduce a hung on [Win22 environment](https://github.com/nikolai-frolov/image-testing/runs/4849475133?check_suite_focus=true) but looking at the provided error message, issue occurs in the [ToolFunctions.ps1](https://github.com/microsoft/azure-pipelines-task-lib/blob/b901effb8eaf6455b3044d57b0e0b4121aa7aa30/powershell/VstsTaskSdk/ToolFunctions.ps1#L112) which is owned by [azure-pipelines-task-lib team](https://github.com/microsoft/azure-pipelines-task-lib) (I don't rule out that issue can be caused by changes but anyway it should not cause a hung):
```
2022-01-11T22:23:37.5630910Z At D:\a_tasks\CmdLine_d9bafed4-0b18-4f58-968d-86655b4d2ce9\2.182.0\ps_modules\VstsTaskSdk\ToolFunctions.ps1:113
2022-01-11T22:23:37.5632056Z char:13
2022-01-11T22:23:37.5632349Z
2022-01-11T22:23:37.5632851Z + if ($originalEncoding) {
2022-01-11T22:23:37.5633211Z
2022-01-11T22:23:37.5633733Z + ~~~~~~~~~~~~~~~~~
2022-01-11T22:23:37.8131767Z ##[debug]Leaving Invoke-VstsTool.
```
@xpouyat, we are going to close this issue since it's not related to image generation. Please create a new one issue for the [azure-pipelines-task-lib team](https://github.com/microsoft/azure-pipelines-task-lib).

Regarding a delay to start Visual Studio: it is expected for the devenv tool since it performs initialization for the first project run on machine and this delay can actually depend on project size. Anyway I'm not sure if we can do something here, since it's related to devenv tool which is a part of Visual Studio and external for us. I can suggest you to use msbuild instead: it allows restore packages and build project much faster and it's already available in Windows images.

**Comment by nikolai-frolov** [comment] 2022-01-21 14:07
Hi @xpouyat. I have performed additional testing here and would like to share results with you: I tried to execute the same command on my local machine by using Visual Studio Enterprise 2022 and this project also got hung after the building, so most likely this issue is caused by Visual Studio or project code. I would suggest you to report about this issue to the VS owners (https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022)
![image](https://user-images.githubusercontent.com/90333448/150539966-5df3cb11-d3fa-44a2-b66e-ce3d2a9de850.png)
I'm going to close this issue since it's definitely related neither windows image nor azure-pipeline-task as I thought earlier.

**Closed by nikolai-frolov** 2022-01-21 14:07 UTC
Labels: Area: .NET Core, Area: Scripting and command line, OS: Windows, investigate

**Comment by xpouyat** [comment] 2022-01-21 14:29
Ok, let me open an issue to Visual Studio.

**Comment by xpouyat** [comment] 2022-01-21 14:33
Please note that I don't have this issue on my local Windows when I run the same command line with Visual Studio 2022.

**Comment by xpouyat** [comment] 2022-01-21 14:51
https://developercommunity.visualstudio.com/t/Visual-Studio-2022-devenvcom-task-goes/1644249
