### ISSUE TITLE
Switch python version not working properly on Ubuntu

### ISSUE THREAD

**Issue by majorvin** [actions/virtual-environments#302] opened 2020-01-21 14:40 UTC
**Describe the bug**
Using the task switch python version is not working. 

**Area for Triage**: 

**Question, Bug, or Feature?**: 
"Bug"

**Virtual environments affected**
- [ ] macOS 10.15
- [ x] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Actual behavior**
```

Version spec 3.7 for architecture x64 did not match any version in Agent.ToolsDirectory.
Versions in /var/lib/waagent/custom-script/download/1/agent/_work/_tool:
If this is a Microsoft-hosted agent, check that this image supports side-by-side versions of Python at https://aka.ms/hosted-agent-software.
If this is a self-hosted agent, see how to configure side-by-side Python versions at https://go.microsoft.com/fwlink/?linkid=871498.
```

should $AGENT_TOOLSDIRECTORY points to /opts/hostedtoolscache? If yes, then this is not the right behaviour because right now when running on the agent, its pointing to `tools/` and that folder is empty

**Comment by al-cheb** [comment] 2020-01-21 15:21
Hello @majorvin 

Could you please provide steps to reproduce the issue? What kinds of agents do you use self-hosted or github-hosted?

**Comment by majorvin** [comment] 2020-01-22 14:27
Hi @al-cheb nothing special. I just add the python switch task.

**Comment by al-cheb** [comment] 2020-01-22 16:23
Hi @majorvin 

Couldn't reproduce
```
steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - run: |
        python -c "import sys; print(sys.version)"
```

![image](https://user-images.githubusercontent.com/47745270/72912374-97189180-3d4c-11ea-9c74-773dd1c4852d.png)

**Comment by majorvin** [comment] 2020-01-22 16:24
hi @al-cheb can you run it on a freshly build agent?   also, it is ubuntu agent. 
What i noticed so far is i had to run it twice to get it to work on a freshly build agent.

**Comment by al-cheb** [comment] 2020-01-22 16:35
@majorvin 

```
jobs:
  build:
    runs-on: [ubuntu-16.04]
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - run: |
        python -c "import sys; print(sys.platform,sys.version)"
```
![image](https://user-images.githubusercontent.com/47745270/72913512-4d30ab00-3d4e-11ea-9faf-897a3ebcc2b5.png)

**Comment by maxim-lobanov** [comment] 2020-01-22 16:59
@majorvin , could you rerun your build and if still fails, please share small repro?
Also just to confirm, do you use hosted or self-hosted agents to run your builds? (`runs-on` parameter)

**Comment by majorvin** [comment] 2020-01-22 18:13
this runs on self-hosted. 

```

##[debug]Agent.ProxyUrl=undefined
##[debug]Agent.CAInfo=undefined
##[debug]Agent.ClientCert=undefined
##[debug]Agent.SkipCertValidation=undefined
##[debug]Agent.ProxyUrl=undefined
##[debug]Agent.CAInfo=undefined
##[debug]Agent.ClientCert=undefined
##[debug]check path : /var/lib/waagent/custom-script/download/1/agent/_work/_tasks/UsePythonVersion_33c63b11-352b-45a2-ba1b-54cb568a29ca/0.151.2/node_modules/azure-pipelines-tool-lib/lib.json
##[debug]adding resource file: /var/lib/waagent/custom-script/download/1/agent/_work/_tasks/UsePythonVersion_33c63b11-352b-45a2-ba1b-54cb568a29ca/0.151.2/node_modules/azure-pipelines-tool-lib/lib.json
##[debug]system.culture=en-US
##[debug]check path : /var/lib/waagent/custom-script/download/1/agent/_work/_tasks/UsePythonVersion_33c63b11-352b-45a2-ba1b-54cb568a29ca/0.151.2/task.json
##[debug]adding resource file: /var/lib/waagent/custom-script/download/1/agent/_work/_tasks/UsePythonVersion_33c63b11-352b-45a2-ba1b-54cb568a29ca/0.151.2/task.json
##[debug]system.culture=en-US
##[debug]versionSpec=3.7
##[debug]addToPath=true
##[debug]architecture=x64
##[debug]Semantic version spec of 3.7 is 3.7
##[debug]isExplicit: null
##[debug]explicit? false
##[debug]Agent.Version=2.164.3
##[debug]Agent.ToolsDirectory=/var/lib/waagent/custom-script/download/1/agent/_work/_tool
##[debug]evaluating 0 versions
##[debug]match not found
##[debug]Agent.Version=2.164.3
##[debug]Agent.ToolsDirectory=/var/lib/waagent/custom-script/download/1/agent/_work/_tool
##[debug]Agent.Version=2.164.3
##[debug]Agent.ToolsDirectory=/var/lib/waagent/custom-script/download/1/agent/_work/_tool
##[debug]Agent.ToolsDirectory=/var/lib/waagent/custom-script/download/1/agent/_work/_tool
##[debug]task result: Failed
##[error]Version spec 3.7 for architecture x64 did not match any version in Agent.ToolsDirectory.
Versions in /var/lib/waagent/custom-script/download/1/agent/_work/_tool:


If this is a Microsoft-hosted agent, check that this image supports side-by-side versions of Python at https://aka.ms/hosted-agent-software.
If this is a self-hosted agent, see how to configure side-by-side Python versions at https://go.microsoft.com/fwlink/?linkid=871498.
##[debug]Processed: ##vso[task.issue type=error;]Version spec 3.7 for architecture x64 did not match any version in Agent.ToolsDirectory.%0AVersions in /var/lib/waagent/custom-script/download/1/agent/_work/_tool:%0A%0A%0AIf this is a Microsoft-hosted agent, check that this image supports side-by-side versions of Python at https://aka.ms/hosted-agent-software.%0AIf this is a self-hosted agent, see how to configure side-by-side Python versions at https://go.microsoft.com/fwlink/?linkid=871498.
##[debug]Processed: ##vso[task.complete result=Failed;]Version spec 3.7 for architecture x64 did not match any version in Agent.ToolsDirectory.%0AVersions in /var/lib/waagent/custom-script/download/1/agent/_work/_tool:%0A%0A%0AIf this is a Microsoft-hosted agent, check that this image supports side-by-side versions of Python at https://aka.ms/hosted-agent-software.%0AIf this is a self-hosted agent, see how to configure side-by-side Python versions at https://go.microsoft.com/fwlink/?linkid=871498.
Finishing: Use Python 3.7

```

**Comment by majorvin** [comment] 2020-01-23 00:43
> @majorvin , could you rerun your build and if still fails, please share small repro?
> Also just to confirm, do you use hosted or self-hosted agents to run your builds? (`runs-on` parameter)

Running twice on the same agent will make it work.

**Comment by miketimofeev** [comment] 2020-01-29 15:59
@majorvin could you provide some details about your self-hosted pool(what image template was used, how long ago it was built)?

**Comment by majorvin** [comment] 2020-01-29 17:31
@miketimofeev the image have bee n used was ubuntu16/20191209.1 . Most agents gets auto shutdown at night time during off peak hours and come back in the morning.

**Comment by miketimofeev** [comment] 2020-01-30 12:08
@majorvin I'm not sure that your images have properly installed toolcache, because it's supposed to be in /opt/hostedtoolcache directory. I assume that task switch python isn't fully functional on self-hosted agents.

**Comment by asbiin** [comment] 2020-02-27 15:23
I have the same issue.

Python tools are installed in /opt/hostedtoolcache/, according to https://github.com/actions/virtual-environments/blob/master/images/linux/scripts/installers/hosted-tool-cache.sh#L15

When using the UsePythonVersionV0 task, 
- Microsoft-hosted agents look for python tools in /opt/hostedtoolcache/, and it's ok
- self-hosted agents look for python tools in /BASEDIR/_work/_tool, where python is not installed.

Why Agent.ToolsDirectory is not defined to /opt/hostedtoolcache/ on self-hosted agent?

**Comment by maxim-lobanov** [comment] 2020-02-27 17:25
Hi @asbiin ,
During image-generation, we set only `$(AGENT_TOOLSDIRECTORY)` variable that points to the toolcache folder but `UsePythonVersionV0` task uses variable `$(Agent.ToolsDirectory)`. This variable is set by [actions/runner](https://github.com/actions/runner) on job start. So I think this issue should be moved to the runner repository.

**Comment by asbiin** [comment] 2020-02-27 17:46
Thank you for your answer @maxim-lobanov 

You said
> `UsePythonVersionV0` task uses variable `$(Agent.ToolsDirectory)`.

But I tried to set Agent.ToolsDirectory variable in my pipeline, and it's not working, the task still look for tools in `/BASEDIR/_work/_tool`.
I will create an issue to actions/runner.
In the meantime, is it a good idea to build a new image where tools are installed in `_work/_tool`?

**Comment by asbiin** [comment] 2020-02-27 17:59
The [documentation of UsePythonVersion](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/use-python-version?view=azure-devops#how-can-i-configure-a-self-hosted-agent-to-use-this-task) says:
> The desired Python version will have to be added to the tool cache on the self-hosted agent in order for the task to use it. Normally the tool cache is located under the _work/_tool directory of the agent or the path can be overridden by the environment variable AGENT_TOOLSDIRECTORY.

I can't get it work

**Comment by maxim-lobanov** [comment] 2020-02-27 19:27
@asbiin , probably, runner overrides variable to default value on each step so it overrides your custom value.
Yes, I think ` build a new image where tools are installed in _work/_tool` is good idea as a temporary work around.

P.S. I see that your issue in `actions/runner` was closed and you was redirected to `azure-pipelines-agent`. Sorry, just didn't notice that you use AzDO agent. Thought that it was actions one.

**Comment by maxim-lobanov** [comment] 2020-02-27 19:29
Btw, something is pretty similar: https://github.com/microsoft/azure-pipelines-agent/issues/2802

**Comment by maxim-lobanov** [comment] 2020-05-07 13:23
Closing this issue because initial issue is related to self-hosted agent, not Hosted one. Feel free to ping me if you have any concerns

**Closed by maxim-lobanov** 2020-05-07 13:23 UTC
Labels: Area: Image administration, Area: Packages, Area: Python, OS: Ubuntu
