### ISSUE TITLE
Interactive UI testing usable by the Windows Image for 2016/2019 generated by this process

### ISSUE THREAD

**Issue by ShahradGH** [actions/virtual-environments#3180] opened 2021-04-14 09:10 UTC
**Description**  
Using Process written back in 02/2021 - Windows 2019 image generated using process-based packer and fed into a Azure VMSS resource.  This then is integrated into Azure Devops to provide a self-hosted agent pool for Azure Private Endpoint development. (Public DevOps agent cant be used as we are incorporating a virtual network with private endpoints resources)

**Area for Triage**:  
Testing and code coverage

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Image version**

Image version where you are experiencing the issue.

**Expected behavior**  
Be able to select the "configure VM to run interactively" and enable UI testing with the same image, prepared by the process for Windows OS provided in this Git repo.

**Actual behavior**  
The Image generated by this for use cannot run interactive tests (for UI Tests) in Azure DevOps Pipelines. This image is being used to service a Azure VMSS configured with Azure DevOps instance to scale/tear automatically.

**Repro steps**  
1. Generate image for any Windows OS
2. Feed it into a Azure Image file
3. Create VMSS based on this image
4. Azure Devops - create a Self-hosted pool with VMSS as the option
5. Select "Configure VM to run interactively"
6. Run a UI test in Selinium

**Comment by Darleev** [comment] 2021-04-14 12:30
Hello @ShahradGH,
Thank you for contacting us.
We'll investigate the issue. As soon as we find something, we'll let you know.

**Comment by ShahradGH** [comment] 2021-04-14 14:22
@Darleev thank you for triaging.

I have confirmed with Microsoft that:

- The image itself can also not run Azure CLI and Azure Powershell based tasks for this similar reason (DevOps Release steps)
- I have prepared the image multiple times in-case it was a specific run issue (of course adhering to the 4-6 hour turnaround)
- Deployed Image in a different Azure location with eased and in 1 case no restrictions
- I would once I obtain the packer file, not then Deploy to a VM but instead use that vhd output to create an Azure image from (hoping this is correct)

Anything else you need please let me know and I will edit this post

**Comment by LeonidLapshin** [comment] 2021-04-23 06:38
Hey, @ShahradGH !
I have prepared Azure VMSS + Azure DevOps pool based on it, could you please provide some tiny sample app + Selenium test to check it on that pool?
Thank you!

**Comment by ShahradGH** [comment] 2021-04-23 06:56
Hi @LeonidLapshin 

That's something I would need to get off my fellow developers! Bear with me on this as these would need to be anonymised first!

The other test worth emulating in similar fashion is:

The Pool has "Configure for Interactive Testing" enabled from DevOps and try running steps such as Azure Powershell or Azure CLI in release pipeline, even with something simple like:

```
Az --version
```

When I would attempt to run that above, I would get pipeline release errors related to permissions issues with accessing the Az directory.

This essentially is what led to this being raised with MS Support identifying this as "this pool/image is not suitable to run in Headless/UI mode, please turn the tick box off"

Does that help in the first instance?

**Comment by LeonidLapshin** [comment] 2021-04-23 07:34
Thank you for the quick response, @ShahradGH !
My test pool has "Configure for Interactive Testing" option enabled and I have tried `Az --version` and did not get any error related to this:

![image](https://user-images.githubusercontent.com/2534109/115835671-33818600-a41f-11eb-9b23-c7b51d106118.png)


```
2021-04-23T07:27:23.5674989Z ##[section]Starting: PowerShell Script
2021-04-23T07:27:23.5802252Z ==============================================================================
2021-04-23T07:27:23.5802504Z Task         : PowerShell
2021-04-23T07:27:23.5802821Z Description  : Run a PowerShell script on Linux, macOS, or Windows
2021-04-23T07:27:23.5803014Z Version      : 2.180.1
2021-04-23T07:27:23.5803174Z Author       : Microsoft Corporation
2021-04-23T07:27:23.5803409Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
2021-04-23T07:27:23.5803695Z ==============================================================================
2021-04-23T07:27:25.6581628Z Generating script.
2021-04-23T07:27:25.6650508Z ========================== Starting Command Output ===========================
2021-04-23T07:27:25.6850895Z ##[command]"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'C:\a\_temp\96b2d941-ba1c-4926-bd7e-4489b8e30ef7.ps1'"
2021-04-23T07:27:30.7652117Z WARNING: You have 2 updates available. Consider updating your CLI installation with 'az upgrade'
2021-04-23T07:27:30.9031126Z 
2021-04-23T07:27:30.9032738Z azure-cli                         2.22.0 *
2021-04-23T07:27:30.9060787Z Please let us know how we are doing: https://aka.ms/azureclihats
2021-04-23T07:27:30.9061108Z 
2021-04-23T07:27:30.9062671Z and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
2021-04-23T07:27:30.9063071Z core                              2.22.0 *
2021-04-23T07:27:30.9063919Z telemetry                          1.0.6
2021-04-23T07:27:30.9064163Z 
2021-04-23T07:27:30.9064780Z Extensions:
2021-04-23T07:27:30.9065288Z azure-devops                     Unknown
2021-04-23T07:27:30.9065496Z 
2021-04-23T07:27:30.9065869Z Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
2021-04-23T07:27:30.9066518Z Extensions directory 'C:\Program Files\Common Files\AzureCliExtensionDirectory'
2021-04-23T07:27:30.9066817Z 
2021-04-23T07:27:30.9067453Z Python (Windows) 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]
2021-04-23T07:27:30.9067941Z 
2021-04-23T07:27:30.9068500Z Legal docs and information: aka.ms/AzureCliLegal
2021-04-23T07:27:30.9068759Z 
2021-04-23T07:27:30.9068938Z 
2021-04-23T07:27:32.2669034Z ##[section]Finishing: PowerShell Script
```
I guess we need some Selenium-based tests repro to dig into this problem.

**Comment by ShahradGH** [comment] 2021-04-23 07:44
@LeonidLapshin thank you for this quick response back!

This does indeed lead to a image generation issue on my side and I would need to rerun this to see if I walk into any issues.

Other than the instructions provided in the repo, any other steps I could take to ensure a successful build on my side?

https://github.com/actions/virtual-environments/blob/main/docs/create-image-and-azure-resources.md

I will need a little bit of time to respond back with this to update!

**Comment by LeonidLapshin** [comment] 2021-04-23 07:46
I have used https://github.com/actions/virtual-environments/blob/main/docs/create-image-and-azure-resources.md to generate an image and steps that you have provided to create a test pool based on VMSS in Azure so it should be ok just to rebuild the image I guess. Hope it will help, I'll wait for updates in this issue :)
Thank you!

**Comment by ShahradGH** [comment] 2021-04-26 10:45
@LeonidLapshin I have tried multiple builds and throughout the process, I would have to select to retry a build of some kind at least 2-3 times. it soldiers on through though and can generate whats needed?

Thought to ask - do I need to run the post-generation scripts as well?

**Comment by LeonidLapshin** [comment] 2021-04-30 11:19
Hey, @ShahradGH !
I have recreated a self-hosted VMSS based pool (Windows 2019 image) and checked `az --version` again, but still no luck with reproducing the error :( Could you please share your pipeline yaml?

**Comment by ShahradGH** [comment] 2021-05-01 18:01
@LeonidLapshin anyway to send something securely?

**Comment by ShahradGH** [comment] 2021-05-04 09:13
![Agent Settings](https://user-images.githubusercontent.com/4907864/116982897-4cacf100-acc1-11eb-9110-057f476b9416.png)
![StageSettings](https://user-images.githubusercontent.com/4907864/116982900-4d458780-acc1-11eb-93bf-dc2f3d74040b.png)
![VariablesSettings](https://user-images.githubusercontent.com/4907864/116982901-4d458780-acc1-11eb-8de0-596b825b2d6d.png)

The Pipeline Configuration is attached. Done in GUI and not in YAML.

**Comment by ShahradGH** [comment] 2021-05-04 09:15
The Release Pipeline configuration is as attached:

![StageSettings](https://user-images.githubusercontent.com/4907864/116983083-9269b980-acc1-11eb-8e5d-a607eff0c927.png)
![VariablesSettings](https://user-images.githubusercontent.com/4907864/116983086-93025000-acc1-11eb-88c3-0076bedb7280.png)
![Agent Settings](https://user-images.githubusercontent.com/4907864/116983089-93025000-acc1-11eb-8999-059bdfd4d076.png)

**Comment by LeonidLapshin** [comment] 2021-05-05 10:22
Hey, @ShahradGH!
I have reproduced your problem with Azure CLI pipeline task + "Configure VMs to run interactive tests" option enabled on the VMSS based pool in Azure DevOps.

Previously, we have already seen [this problem](https://github.com/actions/virtual-environments/issues/1682) and it seems that you can not use tasks that need administrator privileges with "Configure VMs to run interactive tests" option enabled. If you disable this option - Azure CLI task works, so the problem is somewhere in task/how runner works, but not the image itself. 

I guess you can create an issue in [Azure pipelines tasks repo](https://github.com/Microsoft/azure-pipelines-tasks) with this problem.
Thank you!

**Comment by ShahradGH** [comment] 2021-05-05 10:30
@LeonidLapshin Is this how Microsoft Hosted agents work then - slightly confused by this?

**Comment by LeonidLapshin** [comment] 2021-05-05 11:18
@ShahradGH, I don't have information about "Configure VMs to run interactive tests" option on hosted pools, but I have checked user priviledges both on Github Actions and Azure DevOps and they both run with elevated permissions(Mandatory Label\High Mandatory Level). 

Do you have any problems with "Configure VMs to run interactive tests" unchecked?

**Comment by ShahradGH** [comment] 2021-05-05 11:22
@LeonidLapshin Yes indeed as without it checked, UI tests can't be run!

**Comment by LeonidLapshin** [comment] 2021-05-05 11:27
@ShahradGH could you please share the way(pipeline) how do you run UI test?

**Comment by ShahradGH** [comment] 2021-05-07 15:04
@LeonidLapshin I may have a precedent here to stand up separate set of agents for this.

Can I confirm that I could just use the image I made, stand up a VM from it, and just run the interactive Mode step to it and re-purpose the image for SHAP for Windows?
Local Windows User - I assume I just statically define this either within Image context or on agent (VM) deploy?

**Comment by LeonidLapshin** [comment] 2021-05-08 11:07
Hi, @ShahradGH!
You definitely can use generated image. To use it:
1) Create a VM from that image and use it for self-hosted pool. I have created a managed disk from vhd -> Azure "image" from managed disk -> VM from Azure "image". 
2) After VM creation you can create VM user (this one will be local administrator) through Azure portal
![3](https://user-images.githubusercontent.com/2534109/117536673-1e068180-b005-11eb-99cd-7c12b40bd8b9.png)
3) Install Azure DevOps agent
![1](https://user-images.githubusercontent.com/2534109/117536848-1f847980-b006-11eb-86b1-6a3934f19b60.png)
![2](https://user-images.githubusercontent.com/2534109/117536855-2612f100-b006-11eb-98a0-512da0313457.png)
and use this user while entering data while answering on .\config.cmd questions. When you run this script choose "autologon and run agent on startup" option to run an agent in interactive mode. 
![5](https://user-images.githubusercontent.com/2534109/117536914-768a4e80-b006-11eb-8923-2f62d62e170d.png)
3) use this pool (pool with this type of agents) to run interactive UI tests + some privileged operations (Azure CLI for example)

**Comment by LeonidLapshin** [comment] 2021-05-18 07:18
Hey, @ShahradGH , I'll close the issue, but feel free to reopen it if you have any concerns :)

**Closed by LeonidLapshin** 2021-05-18 07:18 UTC
Labels: Area: Testing and code coverage, OS: Windows, investigate
