### ISSUE TITLE
buildah isn't working in ubuntu-20.04 (version: 20210330.1)

### ISSUE THREAD

**Issue by urfin78** [actions/virtual-environments#3080] opened 2021-04-01 14:27 UTC
**Description**  

The latest 1.20.0 release of buildah isn't working inside the virtual environment from the github-actions. Maybe it's related to this
buildah issue: https://github.com/containers/buildah/issues/3120

**Area for Triage**:  
Containers

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
20210330.1

**Expected behavior**  
Image build with buildah suceeds.

**Actual behavior**  
Image build with buildah fails with
```
STEP 1: FROM debian:buster-slim
Resolved "debian" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Getting image source signatures
Copying blob sha256:75646c2fb4101d306585c9b106be1dfa7d82720baabe1c75b64d759ea8adf341
Copying config sha256:2d7852f9772998f25c37ba35c7767bb995b7bdaf9f7ca0cc4a8cc3fe03dc91dd
Writing manifest to image destination
Storing signatures
level=error msg="error unmounting /home/runner/.local/share/containers/storage/overlay/fce8007137e91d9ab3a0da19119413f9d4c25be13b74ea5ef278905603f52df5/merged: invalid argument"
error mounting new container: error mounting build container "285487a42a975e50ac0ff80dd7f77de4115495867faf3334e9d23700a11eb5cd": error creating overlay mount to /home/runner/.local/share/containers/storage/overlay/fce8007137e91d9ab3a0da19119413f9d4c25be13b74ea5ef278905603f52df5/merged, mount_data=",lowerdir=/home/runner/.local/share/containers/storage/overlay/l/6C2IBJ23INYYCXOX573ZQH5EIX,upperdir=/home/runner/.local/share/containers/storage/overlay/fce8007137e91d9ab3a0da19119413f9d4c25be13b74ea5ef278905603f52df5/diff,workdir=/home/runner/.local/share/containers/storage/overlay/fce8007137e91d9ab3a0da19119413f9d4c25be13b74ea5ef278905603f52df5/work,userxattr": invalid argument
level=error msg="exit status 125"
Error: Process completed with exit code 125.
```

**Repro steps**  
Run the following workflow with the simplest Dockerfile of your choice:
```yaml
  build:
    name: Build Dockerfile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build manual
      run: |
        buildah bud -t test .
```

**Comment by miketimofeev** [comment] 2021-04-01 15:19
Hi @urfin78!
Could you please try the following workaround to build the previous buildah version in runtime? (it takes about 1.5-2min)
```
    - name: Install buildah 1.19
      shell: bash
      run: |
        sudo apt-get remove buildah
        sudo apt-get -y install software-properties-common
        sudo add-apt-repository -y ppa:alexlarsson/flatpak
        sudo apt-get -y -qq update
        sudo apt-get -y install bats libapparmor-dev libdevmapper-dev libglib2.0-dev libgpgme11-dev libseccomp-dev libselinux1-dev skopeo-containers go-md2man
        sudo apt-get -y install golang-1.13
        mkdir ~/buildah
        cd ~/buildah
        export GOPATH=`pwd`
        git clone https://github.com/containers/buildah ./src/github.com/containers/buildah
        cd ./src/github.com/containers/buildah
        git checkout release-1.19
        PATH=/usr/lib/go-1.13/bin:$PATH make runc all SECURITYTAGS="apparmor seccomp"
        sudo make install install.runc
        buildah version
```

**Comment by urfin78** [comment] 2021-04-01 15:27
Building and using the old version on the same runner seems to work:
https://github.com/urfin78/playground/runs/2247288346?check_suite_focus=true

**Comment by miketimofeev** [comment] 2021-04-01 15:37
@urfin78 great, let's wait for an answer in https://github.com/containers/buildah/issues/3120

**Comment by kpfleming** [comment] 2021-04-03 11:50
Same problem for me, the workaround posted above works in my workflows.

**Comment by miketimofeev** [comment] 2021-04-04 21:23
@urfin78 @kpfleming this workaround should be much faster
https://github.com/redhat-actions/buildah-build/issues/45#issuecomment-812043531

**Comment by tetchel** [comment] 2021-04-05 14:39
The Ubuntu-20.04 runner could be modified similarly to the workaround mentioned https://github.com/redhat-actions/buildah-build/issues/45#issuecomment-812043531. 
If the virtual environment used fuse-overlayfs by default, that would fix this issue for all users.

`/etc/containers/containers.conf` would have to be modified to use `mount_program=fuse-overlayfs`.

https://github.com/containers/common/blob/master/docs/containers.conf.5.md

**Comment by miketimofeev** [comment] 2021-04-06 07:10
@urfin78 I'm going to close the issue since the problem is external. Please feel free to contact us if you have any concerns.
Thank you!

**Closed by miketimofeev** 2021-04-06 07:10 UTC
Labels: Area: Containers, OS: Ubuntu, external

**Comment by urfin78** [comment] 2021-04-06 12:55
@miketimofeev If it's expected behaviour from the buildah side, that container configuration should be `mount_program=fuse-overlayfs` when using rootless mode and virtual environments in github-actions run as user, than this has to be changed here. 
At this state nobody will change a thing (the buildah bug report https://github.com/containers/buildah/issues/3120 was also closed) and we will have to use workarounds to get the old functionality back.

**Comment by tetchel** [comment] 2021-04-07 14:47
I agree with @urfin78 that this should be fixed in the virtual environment.

If I had this issue on a system under my control I would edit `storage.conf` as I mentioned above and the problem would go away. 

Since Actions users cannot make persistent changes on the GitHub environments, they have to edit that file in every workflow that uses buildah. And there's no way for them to know how to do that without finding this issue.

**Comment by miketimofeev** [comment] 2021-04-07 14:59
@urfin78 @tetchel sorry, I might have missed the idea. What config file do we need to change from our side to fix it? It would be great if you can submit a PR with the fix.

**Comment by maxim-lobanov** [comment] 2021-04-07 15:06
it is unpredictable how other tools and containers will be affected If we patch `storage.conf` on image side

**Comment by urfin78** [comment] 2021-04-08 07:54
@maxim-lobanov `storage.conf` is used by tools using the shared container storage - at least the redhat container tools `podman`, `buildah` and `skopeo`. I don't know if any other software use this config. Maybe some k8s related tools?
Beside that, as I read in the different issues about this problem, it seems, that the other linux distributions, which provide these packages have the `fuse-overlayfs` package as dependency installed. And if I understand it right, when `fuse-overlayfs`is installed, the `mount_program` option is automatically set to `mount_program=fuse-overlayfs`.

Setting this option is also recommended for rootless setups here https://github.com/containers/storage/blob/master/docs/containers-storage.conf.5.md

But surely it has to be tested properly.

**Comment by miketimofeev** [comment] 2021-04-08 08:00
@urfin78 in that case maybe it's a better solution to install `fuse-overlayfs` package? Or it's not possible for ubuntu?

**Comment by urfin78** [comment] 2021-04-08 09:45
@miketimofeev It was just a guess from reading one of issues regarding the problem: https://github.com/containers/buildah/issues/1745#issuecomment-516728029 
According to that statement, `fuse-overlayfs` has to be installed before `podman` (i think also before the other container tools `buildah` and  `skopeo`). As it genereates the correct config if the package is available. But I haven't tested it myself.

**Comment by tetchel** [comment] 2021-04-08 12:52
As far as I can tell, fuse-overlayfs is already installed on the ubuntu runners. Installing fuse-overlayfs first as suggested may work and is absolutely worth a try.

Otherwise, the storage.conf can be edited as per https://github.com/actions/virtual-environments/issues/3080#issuecomment-813428356 to set it as the default.

**Comment by miketimofeev** [comment] 2021-04-08 15:27
@urfin78 @tetchel I'll try to install `libfuse3-dev` before podman and the other tools installation and get back with the results

**Comment by miketimofeev** [comment] 2021-04-09 09:04
Nope, it didn't help, the option is still disabled:
```
cat /etc/containers/storage.conf | grep mount
# Path to an helper program to use for mounting the file system instead of mounting it
#mount_program = "/usr/bin/fuse-overlayfs"
```

**Comment by tetchel** [comment] 2021-04-09 14:55
FWIW, we added a workaround to https://github.com/redhat-actions/buildah-build so it will work without the workaround above.
