### ISSUE TITLE
Broken Pipe error with Linux builds

### ISSUE THREAD

**Issue by vismid86** [actions/virtual-environments#3414] opened 2021-05-19 03:27 UTC
**Description**  
Broken pipe error seen for any pipe commands. The run is timing out after the error. 

**Area for Triage**:  
Worker machine

**Question, Bug, or Feature?**:  

Bug

**Virtual environments affected**  
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04

**Image version**
Current runner version: '2.278.0'
Operating System
  Ubuntu
  20.04.2
  LTS
Virtual Environment
  Environment: ubuntu-20.04
  Version: 20210510.0

**Expected behavior**  
NO pipe errors.

**Actual behavior**  
grep: write error: Broken pipe

**Repro steps**  
I have reproduced this on a public repository. It looks to be basic issue seen for any pipe output.

PR:
https://github.com/vismid86/ManUProject/pull/15

Run:
https://github.com/vismid86/ManUProject/pull/15/checks?check_run_id=2616475743

**Comment by Darleev** [comment] 2021-05-19 08:17
Hello @vismid86,
I forked your repo and reproduced the issue on my side. However, the issue not in grep command, the main issue, that command
`LATITUDE=0 LONTGITUDE=0 STARTTIME=$(t) app/seed`
could not be correctly completed, and sends broken pipe to grep command. As far as I see, the command unexpectedly ends without any error output. Could you please check the issue on your side?
We are looking forward to your reply.

**Comment by vismid86** [comment] 2021-05-19 08:26
The same command when I run locally on my Linux machine, it works and doesn't throw any error.

Furthermore, if I run a tmate session of the worker in github and run the same command it is successful as well. 

It happens only when run for a workflow automatically.

The command is supposed to be stopped after the matched output with 500 lines and shouldn't throw any pipe errors.

**Comment by vismid86** [comment] 2021-05-27 06:41
Hi, Any update on this? This blocks us from enabling the GitHub actions in our organization. 

As stated above, this issue is seen only when run on a Github worker machine through a workflow trigger.

**Comment by maxim-lobanov** [comment] 2021-05-27 06:50
Could be related to runner and this issue: https://github.com/actions/runner/issues/884 . Customer has noticed very similar behavior on macOS.

**Comment by Darleev** [comment] 2021-05-28 15:26
Hello @vismid86,
Most probably the issue is related to the timeout set in the workflow file. It is required to set enough time to complete Makefile and grep operations. Currently, timeout is set to 3 minutes. I set the timeout to 1 hour, but it seems it's also not enough to complete all operations.
Maybe you can provide more context on this?

**Comment by vismid86** [comment] 2021-05-28 23:47
> Hello @vismid86,
> Most probably the issue is related to the timeout set in the workflow file. It is required to set enough time to complete Makefile and grep operations. Currently, timeout is set to 3 minutes. I set the timeout to 1 hour, but it seems it's also not enough to complete all operations.
> Maybe you can provide more context on this?

Hi, the command takes less than 5 seconds to finish. The timeout was given to atleast cancel on its own saving build minutes. So, it is unrelated.

**Comment by Darleev** [comment] 2021-06-03 12:52
@vismid86 we made deep investigation of the issue, but could not find a reason why infinite look is happening during the workflow execution.  What we can advise here in order to speed up the investigation and give us more context on this:
1. Could you please check [a workflow logs](https://github.com/Darleev/ManUProject/actions/runs/856029452) logs, it seems one of the tests led to infinite loop tests exection.
2. Could you please provide an initial code/code sample(not current binary file) where is it possible to reproduce the same issue? 
3. Try to execute tests one by one to find a test that causes the pipeline to stuck.

We are looking forward to your reply.

**Comment by Darleev** [comment] 2021-06-15 18:01
@vismid86 May we remind you that we're looking forward to your reply.

**Comment by vismid86** [comment] 2021-06-16 00:05
> @vismid86 May we remind you that we're looking forward to your reply.

I did some quick tests. It looks like GitHub actions worker machines are not handling SIGPIPE failures.
The broken pipe message is always printed and may be false alarm.
I couldn't find a way to turn off SIGPIPE or exit. 
Please refer https://github.com/vismid86/ManUProject/pull/15 . I have used some basic bash commands to recreate broken pipe errors. 
Hope this helps.

**Comment by vismid86** [comment] 2021-06-16 00:07
> > @vismid86 May we remind you that we're looking forward to your reply.
> 
> I did some quick tests. It looks like GitHub actions worker machines are not handling SIGPIPE failures.
> The broken pipe message is always printed and may be false alarm.
> I couldn't find a way to turn off SIGPIPE or exit.
> Please refer [vismid86/ManUProject#15](https://github.com/vismid86/ManUProject/pull/15) . I have used some basic bash commands to recreate broken pipe errors.
> Hope this helps.

Also, as I mentioned that when I run a tmate session, I'm able to pass the test. I would reckon running it on a tmate session and compare what's changing between two cases.

**Comment by Darleev** [comment] 2021-06-21 08:52
@vismid86 thank you for the additional information. After the investigation we made a decision that the error itself not related to agents image configuration, and it's better to address it to github runner team, where it will be easier to determine a root cause. The same error has already been investigated in scope of request https://github.com/actions/runner/issues/884 . Could you please provide the details there and involve us in case of any findings related to our image?
I'm going to close this issue. In case of any questions, do not hesitate to contact us.

**Closed by Darleev** 2021-06-21 08:52 UTC
Labels: Area: Scripting and command line, OS: Ubuntu, investigate
