### ISSUE TITLE
Reverse name lookup is broken for current hostname in ubuntu VMs

### ISSUE THREAD

**Issue by lhotari** [actions/virtual-environments#3185] opened 2021-04-14 15:59 UTC
**Description**  

Reverse name lookup is broken for the current hostname. This leads to odd issues. Here are some reports from GitHub Community:
* https://github.community/t/github-action-and-oserror-errno-99-cannot-assign-requested-address/173973
* https://github.community/t/volatile-local-ip-addresses-during-action-run/174362
* https://github.community/t/github-actions-timeout/174533

This is a problem report in apache/pulsar: https://github.com/apache/pulsar/issues/10232
and workaround in apache/pulsar https://github.com/apache/pulsar/pull/10233

I have suggested this general workaround to the problem:
```
- name: Add the current IP address, long hostname and short hostname record to /etc/hosts file
  run: |
     echo -e "$(ip addr show eth0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1)\t$(hostname -f) $(hostname -s)" | sudo tee -a /etc/hosts
```

**Question, Bug, or Feature?**:  Bug

**Virtual environments affected**  
- [x] Ubuntu 16.04
- [x] Ubuntu 18.04
- [x] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Expected behavior**  

`hostname -i`, `nslookup $(hostname -s)` and `nslookup $(hostname -l)`  should return the IP address of the current hostname.

**Actual behavior**  

`hostname -i`, `nslookup $(hostname -s)` or `nslookup $(hostname -l)` returns an IP address that changes and the IP address doesn't belong to the current host.

**Repro steps**  

Add this command to some action and run it `ip a; while [ 1 ]; do nslookup $(hostname); sleep 3; done`

Example output
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:0d:3a:11:ff:4c brd ff:ff:ff:ff:ff:ff
    inet 10.1.1.35/16 brd 10.1.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::20d:3aff:fe11:ff4c/64 scope link 
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:b1:57:12:f2 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever

Server:         127.0.0.53
Address:        127.0.0.53#53

Non-authoritative answer:
Name:   fv-az132-427.w5jmtgevnbgefpdoz44oxoejwc.bx.internal.cloudapp.net
Address: 10.1.1.83

Server:         127.0.0.53
Address:        127.0.0.53#53

Non-authoritative answer:
Name:   fv-az132-427.w5jmtgevnbgefpdoz44oxoejwc.bx.internal.cloudapp.net
Address: 10.1.1.83

Server:         127.0.0.53
Address:        127.0.0.53#53

Non-authoritative answer:
Name:   fv-az132-427.w5jmtgevnbgefpdoz44oxoejwc.bx.internal.cloudapp.net
Address: 10.1.1.83

Server:         127.0.0.53
Address:        127.0.0.53#53

Non-authoritative answer:
Name:   fv-az132-427.w5jmtgevnbgefpdoz44oxoejwc.bx.internal.cloudapp.net
Address: 10.1.1.83

Server:         127.0.0.53
Address:        127.0.0.53#53

Non-authoritative answer:
Name:   fv-az132-427.w5jmtgevnbgefpdoz44oxoejwc.bx.internal.cloudapp.net
Address: 10.1.0.37

Server:         127.0.0.53
Address:        127.0.0.53#53

Non-authoritative answer:
Name:   fv-az132-427.w5jmtgevnbgefpdoz44oxoejwc.bx.internal.cloudapp.net
Address: 10.1.0.37

Server:         127.0.0.53
Address:        127.0.0.53#53

Non-authoritative answer:
Name:   fv-az132-427.w5jmtgevnbgefpdoz44oxoejwc.bx.internal.cloudapp.net
Address: 10.1.0.37

Server:         127.0.0.53
Address:        127.0.0.53#53

Non-authoritative answer:
Name:   fv-az132-427.w5jmtgevnbgefpdoz44oxoejwc.bx.internal.cloudapp.net
Address: 10.1.0.37
```

In the above case, the reverse lookup returns addresses 10.1.1.83 and 10.1.0.37 which aren't the ip addresses of the current host. The address of eth0 is 10.1.1.35 .

**Comment by Darleev** [comment] 2021-04-15 04:25
Hello @lhotari,
Thank you for the detailed report.
We are investigating the issue.

**Comment by progapandist** [comment] 2021-04-16 14:53
I can confirm that this was a major issue for my system tests for a Rails app with Chrome and Capybara (unfortunately, private repo). Github Runner VMs on Ubuntu became blind to localhost and all requests headed there timed out. 

Quick fix is to add this step to workflow: 

```
  # TEMPORATY WHILE GITHUB FIXES THIS https://github.com/actions/virtual-environments/issues/3185
   - name: Add the current IP address, long hostname and short hostname record to /etc/hosts file
     run: |
       echo -e "$(ip addr show eth0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1)\t$(hostname -f) $(hostname -s)" | sudo tee -a /etc/hosts
   # DONT'T FORGET TO REMOVE CODE ABOVE WHEN ISSUE IS ADRESSED!
```

Hope it helps someone and I will subscribe to this issue to see when this is resolved.

**Comment by lhotari** [comment] 2021-04-16 15:25
> Thank you for the detailed report.
> We are investigating the issue.

Hi @Darleev,  Have you made progress in the investigation? 

To me, it seems like a problem caused by Azure Virtual Network configuration for GitHub Runner VMs. Azure added support for [reverse DNS lookups for Azure Virtual Networks in April 2020](https://azure.microsoft.com/en-us/updates/announcing-reverse-dns-support-in-azure-virtual-networks/).
The reverse DNS lookup information is currently invalid. To mitigate this issue, it would be helpful [to disable reverse DNS lookups in the Azure Virtual Networks for GitHub Runner VMs completely](https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-name-resolution-for-vms-and-role-instances#reverse-dns-considerations). The networking support in Linux doesn't require reverse DNS lookups to be in place. It's the invalid reverse DNS lookup information that causes the problems.

What is the ETA of fixing this issue?

**Comment by patrickcarnahan** [comment] 2021-04-16 18:00
@lhotari we have identified the change that caused this problem and are working through potential solutions. We will continue to post updates to this issue. Thanks for reporting!

**Comment by XuanThuLe** [comment] 2021-04-16 23:05
Ok

**Comment by patrickcarnahan** [comment] 2021-04-17 03:27
@lhotari we have isolated the issue and will begin rolling the fix on Monday. Apologies for the inconvenience here.

**Comment by shlomi-noach** [comment] 2021-04-19 08:33
We can confirm that https://github.com/vitessio/vitess CI/workflows suffered major similar issues from hostname resolves, and that @progapandist  's solution in https://github.com/actions/virtual-environments/issues/3185#issuecomment-821233703 fixed the problem (thank you @progapandist !)

**Comment by progapandist** [comment] 2021-04-19 08:34
All credit for that goes to @lhotari, I just retyped his solution to confirm it works :)

**Comment by shlomi-noach** [comment] 2021-04-19 08:46
Then at the cost of spamming this thread just a bit further, thank you @lhotari !

**Comment by chkimes** [comment] 2021-04-19 22:17
For a bit of clarification on the change we're making, we're effectively codifying the hosts file change that was recommended in this issue and running it before providing the VMs to customers. This is a short term fix intended to resolve broken workflows. The PTR record will _still_ be incorrect if queried from the DNS server for the eth0 IP, but at least forward queries for the hostname will be successful. We are working with our cloud provider on a resolution for the PTR record issue, but we expect the resolution there to be longer term.

**Comment by starpit** [comment] 2021-04-19 23:03
Has the update propagated at this point? Curious because we're still seeing the same failures that started 2 weeks ago.

**Comment by chkimes** [comment] 2021-04-19 23:10
The rollout has started but only hit a small subset of customers. It should finish completely before the end of this week.

**Comment by iemejia** [comment] 2021-04-22 04:29
Can somebody here please confirm when this is done so we can remove the workarounds?

**Comment by miketimofeev** [comment] 2021-04-22 06:00
@iemejia it should be finished by now

**Comment by iemejia** [comment] 2021-04-22 20:19
Thanks @miketimofeev it works like a charm now!

**Comment by miketimofeev** [comment] 2021-04-26 11:55
@lhotari I'm going to close the issue since the root cause is fixed. Please feel free to contact us if you have any concerns.
Thank you!

**Closed by miketimofeev** 2021-04-26 11:55 UTC
Labels: Area: Common Tools, OS: Ubuntu, awaiting-deployment, external, investigate

**Comment by lhotari** [comment] 2021-04-26 13:08
> @lhotari I'm going to close the issue since the root cause is fixed. Please feel free to contact us if you have any concerns.
> Thank you!

@miketimofeev Sounds good. Thanks for resolving the issue.

**Comment by XuanThuLe** [comment] 2021-04-26 15:02
Ok
