### ISSUE TITLE
Windows build slow, only with /setup-java:8:openj9

### ISSUE THREAD

**Issue by bmarwell** [actions/virtual-environments#4089] opened 2021-09-15 07:22 UTC
### Description

Description

Hi,

I am using the setup-java action (latest, any v2).

The combination of the OpenJ9 VM (Version: Java 8) and windows-latest will always time out while all other executions will run just fine:

https://github.com/apache/shiro/pull/320/checks

It is always the OpenJ9 java 8 on windows-latest check which will not execute or execute slowly.

**Fault Type**

Permanent - Occurring always

**Blocking?**

Non-Blocking

**Logs**

https://github.com/apache/shiro/pull/320/checks?check_run_id=3583518996

https://github.com/apache/shiro/runs/3376089032?check_suite_focus=true

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Current runner version: '2.281.1'
Operating System
  Microsoft Windows Server 2019
  10.0.17763
  Datacenter
  Environment: windows-2019
  Version: 20210907.4
  Included Software: https://github.com/actions/virtual-environments/blob/win19/20210907.4/images/win/Windows2019-Readme.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/win19%2F20210907.4

https://github.com/apache/shiro/pull/320/checks?check_run_id=3583518996

https://github.com/apache/shiro/runs/3376089032?check_suite_focus=true

### Is it regression?

yes

### Expected behavior

Build will finish successfully in minutes

### Actual behavior

build will abort after 5 hours

### Repro steps

Create an action with windows latest and OpenJ9, Java8 like so:
https://github.com/apache/shiro/blob/main/.github/workflows/maven.yml#L57-L58

Let any action run with OpenJ9 java 8 on windows-latest.

It will time out every time.

**Comment by Darleev** [comment] 2021-09-15 10:36
Hello @bmarwell,
We will check the issue.

**Comment by wojsmol** [comment] 2021-09-15 22:04
@bmarwell For same reason check is waiting for user input [here](https://github.com/apache/shiro/pull/320/checks?check_run_id=3583518996#step:5:1784).

**Comment by bmarwell** [comment] 2021-09-16 05:24
Do you mean "some" reason? Or did you mean "same" and forgot to post a link? 😅

Can you hint me to the user input?
Is something special about windows with this specific java version?

**Comment by wojsmol** [comment] 2021-09-16 08:50
@bgelens I meant "some reason". I'm not a java expert - I just analysed the logs :)

**Comment by dmitry-shibanov** [comment] 2021-09-16 11:23
Hello everyone. The root cause of the issue comes from `choco kotlin` installation. We refactored it. The issue will be resolved in the next images rollout. 

Could you please try to setup PATH environment variable like this as temporary workaround: 
`$env:PATH="C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\ProgramData\chocolatey\lib\maven\apache-maven-3.8.2\bin;C:\hostedtoolcache\windows\Java_Adopt-OpenJ9_jdk\8.0.292-10\x64\bin"`

Hello @bmarwell. Could you please try to use such step:
```
      - name: Build with Maven
        shell: pwsh
        run: |
          if($IsWindows) {
            $JAVA_BIN_PATH = Join-Path $env:JAVA_HOME bin
            $env:PATH = "C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\ProgramData\chocolatey\lib\maven\apache-maven-3.8.2\bin;$JAVA_BIN_PATH"
          }
          mvn verify --errors --batch-mode --no-transfer-progress -Pdocs
```

**Comment by dmitry-shibanov** [comment] 2021-09-24 10:05
Hello everyone, changes were added to the images. 
For now I'm closing the issue.

**Closed by dmitry-shibanov** 2021-09-24 10:05 UTC
Labels: awaiting-deployment, OS: Windows, investigate

**Comment by bmarwell** [comment] 2021-09-25 11:32
Thanks, I was able to verify it works nicely again yesterday. Sorry for not letting you know earlier and thanks a lot for your efforts! 👍🏻
