### ISSUE TITLE
/lib/x86_64-linux-gnu/libstdc++.so.6: cannot allocate memory in static TLS block

### ISSUE THREAD

**Issue by Tenzer** [actions/virtual-environments#4733] opened 2021-12-13 16:05 UTC
### Description

One of our workflows runs a bunch of Python tests against a Django application with MySQL as the backend. One of our tests has suddenly started to fail today with the following error message as the underlying cause:

> /lib/x86_64-linux-gnu/libstdc++.so.6: cannot allocate memory in static TLS block

Looking at what has changed since an earlier successful test run 9 hours earlier, the only thing I can find is that the ubuntu-20.04 virtual environment has changed from version 20211129.1 to 20211209.3.

I can see the 20211209.3 version has a change in the MySQL client version: https://github.com/actions/virtual-environments/pull/4708/files. Is it possible the above error can be contributed to this?

We are caching built wheels between workflow runs. I have tried a test run without the cache to make sure this isn't caused by a Python wheel built against the 20211129.1 virtual environment not working with the libraries available in 20211209.3, but that also failed.

Is there any way to run a specific version of the ubuntu-20.04 virtual environment to verify that it indeed is the version upgrade that is causing this problem?

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20211209.3

### Is it regression?

20211129.1

### Expected behavior

We shouldn't get errors from the low-level C++ standard library about not being able to allocate memory when running our Python tests.

### Actual behavior

We get a stack trace with the following as a conclusion:
> /lib/x86_64-linux-gnu/libstdc++.so.6: cannot allocate memory in static TLS block

The stack trace relates to Django instantiating a MySQL client.

### Repro steps

This happens in a proprietary software project where 1 test out of 4503 fails. I am unfortunately not able to provide more specific guidance on how to reproduce this. Links can however be provided to private workflow runs that are failing.

**Comment by nikolai-frolov** [comment] 2021-12-13 16:16
Hello @Tenzer. Thanks for reporting, but this is a common error message which can be caused by multiple reasons. Unfortunately, it will be difficult to investigate the issue without logs or repro environment. Please provide them to allow us to investigate it.

**Comment by MarcelGerber** [comment] 2021-12-14 09:21
We are running into the same problem.
A Python unit test that relies on MySQL fails with the same error message, and it ran fine with 20211129.1. No changes have been made to the unit test, or any other related part of our setup.

You can see our working/failing runs here:
* [Successful run](https://github.com/owid/etl/runs/4457857520) (Dec 8)
* [Failing run](https://github.com/owid/etl/runs/4510106952) (Dec 13)

**Comment by Tenzer** [comment] 2021-12-14 09:57
@nikolai-frolov I can't easily make a reproduction environment of the test in question, which is partly why I created this report in case other people also experienced the same issue.
For now, we are skipping the single test that fails when run in GitHub Actions.

@MarcelGerber Thanks for sharing!

**Comment by dsame** [comment] 2021-12-15 08:46
It seems some dependency started to request more than 2Kb allocated by default TLS storage.
The workaround is to change of shared libraries loading by adding

`export LD_PRELOAD=/lib/x86_64-linux-gnu/libstdc++.so.6:$LD_PRELOAD` before the running unit tests.

Forked workflow file: https://github.com/akv-demo/etl/commit/c2451658239354971c03edd05757ffb09af76a4e#diff-ee49282f461b4c8ad179f79dd5bcdf93124561074c64a771366caf93e99b9320
And the corresponding success build: https://github.com/akv-demo/etl/actions/runs/1581866053

**Comment by dsame** [comment] 2021-12-16 08:07
@Tenzer does the suggested workaround works for you? Can i close the issue?

**Comment by Tenzer** [comment] 2021-12-16 08:48
Yes, it does work, thank you. Would it be possible to get it baked into the virtual environment, or should it alternately be documented somewhere?

We've since seen the same issue on another repository which also use a Python code base that accesses a MySQL database, so I can't help but wonder how many people this might affect.

**Comment by dsame** [comment] 2021-12-17 08:21
@Tenzer I was not able to locate the exact shared library that caused the problem - it is not reproducible on the small projects. It seems the problem either should be addressed to the python team or we need to gather more input on the same issue to isolate the dependency. Moreover the problem can go away on the next dependency upgrade.

Meanwhile this issue can be used for the documenting the problem.

**Comment by Zeitsperre** [comment] 2021-12-17 21:19
Just as an FYI, I've run into this error today (https://github.com/CSHS-CWRA/RavenPy/pull/146). At first, I thought it was related to libgdal, but thankfully that's not the case:
 - [Not working](https://github.com/CSHS-CWRA/RavenPy/runs/4565366550)
 - [Working](https://github.com/CSHS-CWRA/RavenPy/runs/4231640935)

**Comment by Zeitsperre** [comment] 2021-12-20 16:11
Small update: the `export LD_PRELOAD=/lib/x86_64-linux-gnu/libstdc++.so.6:$LD_PRELOAD` workaround seems to fix the issue. It's already in my workflows (https://github.com/CSHS-CWRA/RavenPy/blob/master/.github/workflows/main.yml)

**Comment by dsame** [comment] 2021-12-23 06:54
I confirmed the problem is caused by this PR
https://github.com/actions/virtual-environments/pull/4674/files
that installed mysql 8.0.26

The build with 8.0.27 reinstlalled from ubuntu repo passes the problematic build:
https://github.com/akv-demo/etl/runs/4615186862?check_suite_focus=true

**Comment by miketimofeev** [comment] 2021-12-23 12:58
@Tenzer we have provided a workaround in this announcement. Sorry for the inconvenience
https://github.com/actions/virtual-environments/issues/4799

**Comment by miketimofeev** [comment] 2022-01-10 08:46
@Tenzer I'm going to close the issue as the workaround is provided. We will update the announcement once the issue is resolved.
Please feel free to contact us if you have any concerns.
Thank you!

**Closed by miketimofeev** 2022-01-10 08:46 UTC
Labels: OS: Ubuntu, investigate

**Comment by freddy123098** [comment] 2022-01-10 08:48
Ok Great.

Thanks @Madhavan ***@***.***>
