### ISSUE TITLE
ubuntu1804.json latest fails in packer with lock issue

### ISSUE THREAD

**Issue by mihsoft** [actions/virtual-environments#2029] opened 2020-11-10 19:46 UTC
When using either self-hosted or Azure DevOps agents the following errors occur after around 3 hours 30 minutes or so (re-run this 10 times now to be sure):

```
==> azure-arm: Provisioning with shell script: /agent/_work/1/s/virtual-environments/images/linux/scripts/base/reboot.sh

    azure-arm: Reboot VM

==> azure-arm: Pausing 30s before the next provisioner...

==> azure-arm: Provisioning with shell script: /agent/_work/1/s/virtual-environments/images/linux/scripts/installers/homebrew-validate.sh

    azure-arm: Validate the Homebrew can run after reboot

    azure-arm: /home/linuxbrew/.linuxbrew/bin/brew

==> azure-arm: Provisioning with shell script: /agent/_work/1/s/virtual-environments/images/linux/scripts/installers/cleanup.sh

==> azure-arm: E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)

==> azure-arm: E: Unable to lock directory /var/lib/apt/lists/

==> azure-arm: Provisioning step had errors: Running the cleanup provisioner, if present...
```

**Comment by Darleev** [comment] 2020-11-11 09:51
Hello,

This issue is a duplicate of https://github.com/actions/virtual-environments-internal/issues/1339 .

In case of any questions, feel free to write in the issue provided.

**Closed by Darleev** 2020-11-11 09:51 UTC
Labels: needs triage
