### ISSUE TITLE
[WINDOWS] .nuspec file suddenly needed when cpack is called.

### ISSUE THREAD

**Issue by sithlord48** [actions/virtual-environments#4384] opened 2021-10-30 13:13 UTC
### Description

Chocolatey was updated to a new version 

Chocolatey was recently updated and its cpack is being called with the command 'cpack' instead of the cpack provided by Cmake.

Community Link: https://github.community/t/windows-actions-suddenly-fail-needing-a-nuspec-file/199483

Times this bug has happened: 
 - Chocolatey 0.11.1 -> .0.11.2 (Fixed)
 - Chocolatey 0.11.2 -> .0.11.3 (OPEN)

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016  (YES?)
- [X] Windows Server 2019
- [ ] Windows Server 2022 (YES?)

### Image version and build link

  Environment: windows-2019
  Version: 20211018.0
  Included Software: https://github.com/actions/virtual-environments/blob/win19/20211018.0/images/win/Windows2019-Readme.md
  Image Release: https://github.com/actions/virtual-environments/releases/tag/win19%2F20211018.0

### Is it regression?

Yes,  Last successful action run: https://github.com/sithlord48/blackchocobo/runs/4016400330?check_suite_focus=true

### Expected behavior

running the command 'cpack' on any os should call cmake's cpack.

### Actual behavior

After chocolatey is updated its cpack is called and the action fails. 

### Repro steps

Run windows build. 
see that Chocolatey version is > 0.11.2
try to run a job w/ cpack not making a nuget package and note the failure. 

```
Chocolatey v0.11.3
No .nuspec files (or more than 1) were found to build in 'D:\a\blackchocobo\blackchocobo'. Please specify the .nuspec file or try in a different directory.
Error: Process completed with exit code 1.
```

**Comment by mikhailkoliada** [comment] 2021-10-31 08:01
A duplicate of https://github.com/actions/virtual-environments/issues/4360

**Closed by mikhailkoliada** 2021-10-31 08:01 UTC
Labels: needs triage
