### ISSUE TITLE
Gradle connection reset

### ISSUE THREAD

**Issue by tyagirajnish** [actions/virtual-environments#2715] opened 2021-02-15 11:38 UTC
**Description**  
gradle randomly throws connection reset error on `macOS 10.14`, `macOS 10.15` virtual environment 

**Area for Triage**:  

**Question, Bug, or Feature?**:  
Bug, Gradle build get failed while downloading jacoco artifacts from central maven also tried private artifactory but same result and some time pipeline works without any code changes

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
20210207.1

**Expected behavior**  
Should not be an issue while downloading jar files from central maven and of course it works on local machine without any issue

**Actual behavior**  
Gradle throw error with below code
```
> Could not resolve all files for configuration ':project:jacocoAnt'.
   > Could not download org.jacoco.ant-0.8.3.jar (org.jacoco:org.jacoco.ant:0.8.3)
      > Could not get resource 'https://repo.maven.apache.org/maven2/org/jacoco/org.jacoco.ant/0.8.3/org.jacoco.ant-0.8.3.jar'.
         > Could not GET 'https://repo.maven.apache.org/maven2/org/jacoco/org.jacoco.ant/0.8.3/org.jacoco.ant-0.8.3.jar'.
            > Connection reset
   > Could not download org.jacoco.report-0.8.3.jar (org.jacoco:org.jacoco.report:0.8.3)
      > Could not get resource 'https://repo.maven.apache.org/maven2/org/jacoco/org.jacoco.report/0.8.3/org.jacoco.report-0.8.3.jar'.
         > Could not GET 'https://repo.maven.apache.org/maven2/org/jacoco/org.jacoco.report/0.8.3/org.jacoco.report-0.8.3.jar'.
            > Connection reset
   > Could not download org.jacoco.core-0.8.3.jar (org.jacoco:org.jacoco.core:0.8.3)
      > Could not get resource 'https://repo.maven.apache.org/maven2/org/jacoco/org.jacoco.core/0.8.3/org.jacoco.core-0.8.3.jar'.
         > Could not GET 'https://repo.maven.apache.org/maven2/org/jacoco/org.jacoco.core/0.8.3/org.jacoco.core-0.8.3.jar'.
            > Connection reset
```

**Repro steps**  
i am using azure pipeline for my android project and in my pipeline i run the unit and ui test, macOS is only supporting android emulators for UI testing, after unit test i also generate code coverage with jacoco and most of the time build get failed with connection reset issue, i have checked every thing inside pipeline it seems like issue with virtual environment

**Comment by LeonidLapshin** [comment] 2021-02-16 07:34
Hey, @tyagirajnish !
We already have faced with timeouts while downloading Maven dependencies due to network timeouts, this issue is flaky, but you can increase http timeouts for Gradle, as far as I can see you can specify 
`./gradlew build -Dorg.gradle.internal.http.socketTimeout=60000 -Dorg.gradle.internal.http.connectionTimeout=60000`
to eliminate these problems. 
Could you please check if these options help?
Thank you!

**Comment by tyagirajnish** [comment] 2021-02-16 08:13
> Hey, @tyagirajnish !
> We already have faced with timeouts while downloading Maven dependencies due to network timeouts, this issue is flaky, but you can increase http timeouts for Gradle, as far as I can see you can specify
> `./gradlew build -Dorg.gradle.internal.http.socketTimeout=60000 -Dorg.gradle.internal.http.connectionTimeout=60000`
> to eliminate these problems.
> Could you please check if these options help?
> Thank you!

let me try with this configuration, i have already tried these configuration `./gradlew build -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120  -Dmaven.wagon.http.retryHandler.count=3` 🤞

**Comment by tyagirajnish** [comment] 2021-02-16 09:21
hey @LeonidLapshin, 
i have tried above configuration and it works on first attempt and then again failed second and third time without any code changes.

 As i said earlier my app repo is multi-product repo so i have to test this config on both pipeline so as of now first pipelines runs 3 times with no issue and failed on second product pipeline on second and third attempt. right now i have increased the **connectionTimeout to 120000** , will let you know the results 
<img width="1129" alt="Screenshot 2021-02-16 at 2 40 20 PM" src="https://user-images.githubusercontent.com/46373586/108042465-d1df1d00-7065-11eb-9f7a-85cf85adcc73.png">

**Comment by LeonidLapshin** [comment] 2021-02-16 13:35
@tyagirajnish I guess that now required settings are
```
systemProp.org.gradle.internal.http.connectionTimeout=300000
systemProp.org.gradle.internal.http.socketTimeout=300000
systemProp.org.gradle.internal.repository.max.retries=10
systemProp.org.gradle.internal.repository.initial.backoff=500
```
could you check them too please?

**Comment by tyagirajnish** [comment] 2021-02-16 14:11
@LeonidLapshin tried but failed again i am sharing some details it might help you to troubleshoot 
gradle.properties file
```
org.gradle.jvmargs=-Xmx4096m -XX:MaxPermSize=4096m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true

systemProp.org.gradle.internal.http.connectionTimeout=300000
systemProp.org.gradle.internal.http.socketTimeout=300000
systemProp.org.gradle.internal.repository.max.retries=10
systemProp.org.gradle.internal.repository.initial.backoff=500
```
Azure pipeline initial logs 
```
Starting: Gradle
==============================================================================
Task         : Gradle
Description  : Build using a Gradle wrapper script
Version      : 2.181.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/gradle
==============================================================================
/Users/runner/work/1/s/gradlew clean test<app>DebugUnitTest create<app>DebugCoverageReport create<app>DebugCoverage -Dorg.gradle.internal.http.socketTimeout=1200000 -Dorg.gradle.internal.http.connectionTimeout=1200000
DEFAULT_JVM_OPTS=""
JAVA_OPTS=""
GRADLE_OPTS="-Xmx4096m "-Xdock:name=Gradle" "-Xdock:icon=/Users/runner/work/1/s/media/gradle.icns""
JVM_OPTS="-Xmx4096m -Xdock:name=Gradle -Xdock:icon=/Users/runner/work/1/s/media/gradle.icns -Dorg.gradle.appname=gradlew"
HOSTNAME="Mac-1613482969045.local"
Running: exec "/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java" "-Xmx4096m -Xdock:name=Gradle -Xdock:icon=/Users/runner/work/1/s/media/gradle.icns -Dorg.gradle.appname=gradlew" -classpath "/Users/runner/work/1/s/gradle/wrapper/gradle-wrapper.jar" org.gradle.wrapper.GradleWrapperMain "clean test<app>DebugUnitTest create<app>DebugCoverageReport create<app>DebugCoverage -Dorg.gradle.internal.http.socketTimeout=1200000 -Dorg.gradle.internal.http.connectionTimeout=1200000"
Downloading https://services.gradle.org/distributions/gradle-6.1.1-all.zip

```

**Comment by tyagirajnish** [comment] 2021-02-16 14:59
@LeonidLapshin i hate to tell you this but still no luck, works for first time and then failed again

**Comment by tyagirajnish** [comment] 2021-02-18 07:44
@LeonidLapshin any suggestion ?

**Comment by LeonidLapshin** [comment] 2021-02-18 08:55
Hello @tyagirajnish !
I'm still researching this problem and found out that it seems not Github-specific, but did not find any other workaround that can help you at the moment. I'll try to research more and will keep you updated.
Thank you!

**Comment by tyagirajnish** [comment] 2021-02-18 09:27
@LeonidLapshin now i am getting more trouble because now it's affecting other project also, same problem but this time different Maven dependencies.

**Comment by LeonidLapshin** [comment] 2021-03-11 07:04
Hey, @tyagirajnish, could you please approve that the problem exists and was not temporary?

**Comment by tyagirajnish** [comment] 2021-03-12 08:39
hey @LeonidLapshin, yes the issue is still there but I found a workaround to fix it, now I am using two Gradle tasks one for my Unit test and another one is for code coverage. The second Gradle task used cache (first task) and completed in 20-30 seconds, I know it increased my build time for 30 seconds but at least I have something instead of broken pipelines .

**Comment by LeonidLapshin** [comment] 2021-03-12 10:17
Hey, @tyagirajnish 
Highly likely these problems caused by Azure SNAT balancer — we already had similar issues with [Maven dependencies downloads](https://github.com/actions/virtual-environments/issues/1499) They were solved by using `"-Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120"` but, unfortunately, I'm not an expert in Gradle and don't know if there are any flags to handle connection settings. 
I suggest using the workaround whether it's possible.

**Comment by LeonidLapshin** [comment] 2021-03-18 10:41
Hi, @tyagirajnish !
As far as I understand, your workaround works, so I'll close this issue, but if you have any concerns feel free to reopen it.
Thank you!

**Closed by LeonidLapshin** 2021-03-18 10:41 UTC
Labels: Area: Java, OS: macOS, investigate

**Comment by sixlettervariables** [comment] 2021-06-18 01:18
Looks like Gradle won't retry if you're using a version older than 6.6.
