### ISSUE TITLE
Image Version: 20210330.1 pip install does not work

### ISSUE THREAD

**Issue by AlexanderRyazanov** [actions/virtual-environments#3069] opened 2021-03-31 10:30 UTC
**Description**  
A clear and concise description of what the bug is, and why you consider it to be a bug.
Script contents:
python -m pip install --upgrade pip setuptools wheel psycopg2
========================== Starting Command Output ===========================
##[debug]which 'bash'
##[debug]found: '/bin/bash'
##[debug]which '/bin/bash'
##[debug]found: '/bin/bash'
##[debug]/bin/bash arg: --noprofile
##[debug]/bin/bash arg: --norc
##[debug]/bin/bash arg: /home/vsts/work/_temp/1e6f4ce6-ce74-4f2f-9888-8c027218d871.sh
##[debug]exec tool: /bin/bash
##[debug]arguments:
##[debug]   --noprofile
##[debug]   --norc
##[debug]   /home/vsts/work/_temp/1e6f4ce6-ce74-4f2f-9888-8c027218d871.sh
/bin/bash --noprofile --norc /home/vsts/work/_temp/1e6f4ce6-ce74-4f2f-9888-8c027218d871.sh
Collecting pip
  Downloading https://files.pythonhosted.org/packages/27/79/8a850fe3496446ff0d584327ae44e7500daf6764ca1a382d2d02789accf7/pip-20.3.4-py2.py3-none-any.whl (1.5MB)
Collecting setuptools
  Downloading https://files.pythonhosted.org/packages/e1/b7/182161210a13158cd3ccc41ee19aadef54496b74f2817cc147006ec932b4/setuptools-44.1.1-py2.py3-none-any.whl (583kB)
Collecting wheel
  Downloading https://files.pythonhosted.org/packages/65/63/39d04c74222770ed1589c0eaba06c05891801219272420b40311cd60c880/wheel-0.36.2-py2.py3-none-any.whl
Collecting psycopg2
  Downloading https://files.pythonhosted.org/packages/fd/ae/98cb7a0cbb1d748ee547b058b14604bd0e9bf285a8e0cc5d148f8a8a952e/psycopg2-2.8.6.tar.gz (383kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named setuptools
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-OHtsPO/psycopg2/
##[debug]Exit code 1 received from tool '/bin/bash'
##[debug]STDIO streams have closed for tool '/bin/bash'
##[error]Bash exited with code '1'.
##[debug]Processed: ##vso[task.issue type=error;]Bash exited with code '1'.
##[debug]task result: Failed
##[debug]Processed: ##vso[task.complete result=Failed;done=true;]

Runs fine on agents with image version https://github.com/actions/virtual-environments/releases/tag/ubuntu18%2F20210318.0
**Area for Triage**:  

**Question, Bug, or Feature?**:  

Bug
**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [*] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**

Image version where you are experiencing the issue.
Image Version: 20210330.1
**Expected behavior**  
A description of what you expected to happen.
Pip install successfully installs the required package
**Actual behavior**  
A description of what is actually happening.
pip install fails with the error:
Command "python setup.py egg_info" failed with error code 1 
**Repro steps**  
A description with steps to reproduce the issue. If your have a public example or repo to share,
please provide the link.

1. Add command line step to pipeline like pip install psycopg2

2. Run the pipeline

**Comment by miketimofeev** [comment] 2021-03-31 10:54
Hi @AlexanderRyazanov!
It looks like the `setuptools` module is not installed for python2 on Ubuntu 18 image for some reason. Could you please add the following step as a workaround?
`pip install setuptools`

I'll take a look at why we don't have preinstalled `setuptools` module anymore.

**Comment by miketimofeev** [comment] 2021-03-31 11:10
@AlexanderRyazanov I've found the root cause, python-setuptools package was installed along with the ansible tool, but we changed the installation method and this package is absent on Ubuntu18 now. 
I'd like to suggest you use https://github.com/actions/setup-python task as the most convenient way to use python in GitHub actions. In this way, the image changes won't affect you in the future

**Comment by AlexanderRyazanov** [comment] 2021-03-31 11:59
@miketimofeev thank you, adding "use python version" task to a pipeline fixed the issue

**Comment by miketimofeev** [comment] 2021-03-31 16:27
@AlexanderRyazanov thanks for the update! We've added the module back anyway just in case and will deploy the new image next week

**Comment by miketimofeev** [comment] 2021-04-08 16:30
@AlexanderRyazanov we've deployed the image with `python-setuptools` package.
I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!

**Closed by miketimofeev** 2021-04-08 16:30 UTC
Labels: Area: Python, Area: Scripting and command line, OS: Ubuntu, awaiting-deployment, bug
