### ISSUE TITLE
Publish official Azure VM images to enable the community to self-host runners easily

### ISSUE THREAD

**Issue by haokanga** [actions/virtual-environments#1175] opened 2020-07-04 17:00 UTC
**Describe the bug**
Our team is able to successfully built VHD files using this repository in order to self-host GitHub Actions runners. 
It took the team hours to study the repository and another several hours to build the images.

The current virtual-environments repository may discourage more users from adopting self-hosted runners due to the complexity and lack of documentation. 
* The repository assumes the readers to have basic/intermediate knowledge of PowerShell and Packer in order to build VM images using the repository. 
* The repository has solid codebase, however the repository has a very minimal documentation which was not written for external audiences. E.g., there is no step-by-step instructions on how to build an image, but only https://github.com/actions/virtual-environments/blob/3892b0063b6be9cc92ca7976394732a7d85be4af/help/CreateImageAndAzureResources.md. As a result, it requires _every_ self-hosted runner adopter to study, modify, and troubleshoot the codebase in order to reproduce the process. This may discourage a part of the community to adopt self-hosted runners and GitHub Actions.

To (re)build images from this repository is unnecessary repeated work for a majority of the community in order to self-host runners. GitHub Action team builds VM images for GitHub's hosted runners on a weekly basis anyway using this repository, if possible, please publish read-only copies of these Azure VM images to public. Publishing Official GitHub Runner Virtual Environments as Azure VM images will enable the community to self-host runners easily. So that the community can have the options between using ready-to-use official images and rebuilding custom GitHub Runner images.

**Area for Triage**: 
Area: Image administration

**Question, Bug, or Feature?**: 
Feature

**Virtual environments affected**
- [x] macOS 10.15
- [x] Ubuntu 16.04 LTS
- [x] Ubuntu 18.04 LTS
- [x] Ubuntu 20.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**
GitHub Actions should release public Azure VM images to the community to enable the community to self-host runners easily, in either format:
* VHD files that allows the community to copy the VHD files and build VM images (VHD approach will be deprecated though #1037)
* Azure Marketplace Images
* Shared Image Gallery

Another path to enable the community to self-host runners easily at scale is by publishing official Docker images, e.g., #666 
Even if GitHub Actions team may not be able to prioritize the releases of official Docker images; publishing the Azure VM images, which already exist in your current automated lifecycle, should require less effort and will create significant values and help grow the community.

**Actual behavior**
The community has to study the codebase and repeat the VM image build process in order to self-host runners.

**Comment by maxim-lobanov** [comment] 2020-07-04 17:25
@haokanga , thank you for your request but unfortunately, we can't publish images somewhere due to legal issues.
Duplicate of https://github.com/actions/virtual-environments/issues/176

**Comment by haokanga** [comment] 2020-07-04 17:37
Hi @maxim-lobanov, sorry to hear that there are legal issues that prevent the public VM/Docker images. It is understandable.

As a workaround, please help provide the community with a much more structured documentation so that the community can follow a process step by step to build the images.

The current codebase has the abstraction layer of the ps1 helper files and YAML automation, which adds to the complexity for the new users to figure out how to build an image manually using the codebase.

Besides, the current documentation has no mentioning about pitfalls such as:
1. OS Requirement. The script must run in Windows OS because some dependencies only exist on Windows. **Symptom**: `Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.` when running on MacOS PowerShell.
2. The ps1 files require dependencies to be installed to the Azure PowerShell such as `Install-Module AzureRM -AllowClobber`. **Symptom**: `Login-AzureRmAccount : The term 'Login-AzureRmAccount' is not recognized as the name of a cmdlet, function, script file, or operable program.`

**Comment by maxim-lobanov** [comment] 2020-07-04 17:48
Thank you for sharing these points. Absolutely agree that there is a lack of documentation how to build own images for now.  
We have an issue https://github.com/actions/virtual-environments/issues/564 to track updating documentation. We are going to prioritize and finish it next a few weeks.

I have moved 2 points that you have described to that issue. Feel free to post any other additional / pitfalls that you have faced with (Since we have configured our image generation CI a long time ago, we may miss any basic points in configuration).

**Comment by haokanga** [comment] 2020-07-04 18:22
Thank you @maxim-lobanov ! I very much appreciate it!

2 major missing parts for the documentation that slow down the community to rebuild the images. The first is the **environment** requirements for the ps1 and Packer scripts, the second is a step-by-step instruction on how to **manually** execute the ps1 and packer scripts.

1. **Environment Requirement for the ps1 and Packer scripts (e.g., OS, software, etc.)**

I saw the Azure Pipelines that are used to build the images are a custom Azure Pipeline Agent pool `pool: ci-agent-pool` https://github.com/actions/virtual-environments/blob/master/images.CI/azure-pipelines/image-generation.yml#L9, which are blackboxes for the users and there can be such hidden dependencies (e.g., `AzureRM`) as pitfalls. 

And as you mentioned, the GitHub Actions team configured the image generation CI pool a long time ago so it definitely worth it to revisit the pool environment in order to decide the precise OS Requirement and Software/Dependencies requirement and share the information to the users.

It will be great if the GitHub Actions team can enable the community to run the ps1 and Packer scripts without any major setup overhead. Instead of maintaining yet another README.md to list the environment requirement and letting users to install and configure them, one efficient solution to addressing the OS and dependencies is **to provide IaC scripts**, so that the community can use the IaC scripts to provision VMs with all the dependencies needed by the ps1 and Packer scripts. 

With the IaC scripts, the users will only need to:
- Run the IaC scripts to provision the VM, e.g., `terraform apply` (or `az group deployment create`, etc.)
- Connect to the VM
- git clone https://github.com/actions/virtual-environments.git
- Follow a step-by-step instructions documented by GitHub Actions team to manually execute the ps1 or packer scripts

The above IaC scripts will be a good and sufficient start.

One step further in future is provide the community with an solution that automates both the VM creation and the image build process, e.g., by using ARM templates + [Azure Custom Script Extension](https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/custom-script-windows), or Terraform + the remote-exec provisioner. 

2. **A step-by-step instruction on how to manually execute the ps1 and Packer scripts**

The current codebase is fully written in favor of Azure Pipeline automation, and the users have to figure out all the moving parts and effectively "reverse-engineer automation back to manual commands". 

So the community needs a step-by-step instructions provided by GitHub Actions team on how to **manually** execute the ps1 or packer scripts.

**Comment by haokanga** [comment] 2020-07-04 21:21
Also, it would be helpful if GitHub Actions add a FAQ paragraph into [the self-hosted runner docs](https://docs.github.com/en/actions/hosting-your-own-runners/) similar to this Azure Pipelines section:
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops#where-can-i-find-the-images-used-for-microsoft-hosted-agents

> "Licensing considerations limit us from distributing Microsoft-hosted images. We are unable to provide these images for you to use in your scale set agents. But, the scripts that we use to generate these images are open source. You are free to use these scripts and create your own custom images."

**Comment by maxim-lobanov** [comment] 2020-07-06 06:24
@haokanga , thank you for suggestions, we will keep it on mind when we are working on #564 .
I am going to close this issue for now since we have the separate issue to track documentation changes.

**Closed by maxim-lobanov** 2020-07-06 06:24 UTC
Labels: Area: Deployment/Release, documentation
