### ISSUE TITLE
Mono.framework MDK is missing for Xamarin.mac builds

### ISSUE THREAD

**Issue by jeromelaban** [actions/virtual-environments#2790] opened 2021-02-25 12:49 UTC
**Description**  
Builds for Xamarin.Mac applications fail with the following message:

```
MMP : error MM5202: Mono.framework MDK is missing. Please install the MDK for your Mono.framework version from https://www.mono-project.com/download/ [/Users/runner/work/1/s/src/SamplesApp/SamplesApp.macOS/SamplesApp.macOS.csproj]
```

The builds where passing two days ago.

**Area for Triage**:  

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
```
Virtual Environment
Environment: macos-10.15
Version: 20210220.1
Included Software: https://github.com/actions/virtual-environments/blob/macOS-10.15/20210220.1/images/macos/macos-10.15-Readme.md
Current image version: '20210220.1'
```

**Expected behavior**  
The build passes

**Actual behavior**  
The build fails with the provided message.

**Repro steps**  
Aside from building a Xamarin.macOS, nothing specific.

**Workaround**
None yet.

**Comment by jeromelaban** [comment] 2021-02-25 12:53
Possibly related to https://github.com/xamarin/xamarin-macios/issues/10652

**Comment by miketimofeev** [comment] 2021-02-25 12:56
Hi @jeromelaban!
Looks like the issue is fixed in the Xamarin.Mac 7.4.0.10, which will be shipped with the new image version in the middle of the next week.
Is it possible for you to use the workaround provided in https://github.com/xamarin/xamarin-macios/issues/10652#issuecomment-785132752 until then?

**Comment by jeromelaban** [comment] 2021-02-25 13:01
Yes I've just noticed that, I'm trying this out! Thanks for the quick turnaround!

**Comment by jeromelaban** [comment] 2021-02-25 13:04
That being said, I really with it was possible to revert a hosted agent build by one version. I understand you cannot provide any arbitrary images, but being able to use the previous one at any point would be very useful for cases like this.

I need to push updates to quite a few repositories as a result, until you publish the updated agent.

**Comment by jeromelaban** [comment] 2021-02-25 13:13
The workaround is working well, thanks !

**Comment by miketimofeev** [comment] 2021-02-25 13:49
@jeromelaban thanks for the confirmation and sorry for the inconvenience! Speaking about using the previous image version — it's on our radar for a long time, but, unfortunately, no ETA at the moment.

**Comment by jeromelaban** [comment] 2021-02-25 14:17
That's good to know! It may not change the priority, but this happens very often and it's generally not at a good time :) It makes sense that you can't validate all scenarios, but an escape hatch is extremely important for us.

You may close this issue at your convenience.

**Comment by miketimofeev** [comment] 2021-02-25 14:55
@jeromelaban I'd prefer to leave the issue until the image is deployed if you don't mind

**Comment by miketimofeev** [comment] 2021-03-05 08:57
@jeromelaban the new image with Xamarin.Mac 7.4.0.10 has been deployed!
I'm going to close the issue but please feel free to contact us if you have any concerns.
Thank you!

**Closed by miketimofeev** 2021-03-05 08:57 UTC
Labels: Area: Xamarin, OS: macOS, awaiting-deployment, bug
