### ISSUE TITLE
osascript: can’t open default scripting component 

### ISSUE THREAD

**Issue by grzegorzkrukowski** [actions/virtual-environments#4201] opened 2021-09-30 19:41 UTC
### Description

We are running macOS builds on macOS 11 machines.

From time to time creating disk images fails and it shows this error:
`osascript: can’t open default scripting component`

We are using osascript to generate DMG files.

After re-running jobs it usually works next time - so it's completely random behaviour

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [X] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Environment: macos-11
Version: 20210927.2

### Expected behavior

osascript should be stable

### Actual behavior

osascript is failing occasionally

### Repro steps

1. Prepare a workflow using `osascript`
2. Run it multiple time as observe random failures

**Comment by al-cheb** [comment] 2021-10-01 07:43
Hello, @grzegorzkrukowski 
Could you please provide steps to reproduce the issue?

**Comment by Bilalbilalmounir** [comment] 2021-10-03 19:14
لينعل طبون مكوم

**Comment by KVROHITH098** [comment] 2021-10-05 05:46
Hi I have a Mac OS can I help you today?

**Comment by grzegorzkrukowski** [comment] 2021-10-05 07:50
Hey - we have been trying to find a best way to reproduce this problem, but this week all builds are working just fine. 
Last week it was completely randomly failing on different apple scripts.

**Comment by Darleev** [comment] 2021-10-05 07:54
@grzegorzkrukowski thank you for the information.
In order to investigate the issue further and figure out the reason of script failures, we need steps to reproduce the issue on our side.
Currently, I'm going to close the issue. In case of any questions, feel free to contact us.

**Comment by grzegorzkrukowski** [comment] 2021-10-15 21:05
Hey @Darleev @KVROHITH098 

I managed to prepare a cut to minimum example which shows the problem.

Here is the failure:
https://github.com/raycast/github-oascript-bug/runs/3910385565?check_suite_focus=true#step:3:12

It basically failed after re-running all job 5 times - it's quite random.
But here you can see it's failing on `/usr/bin/osascript` being run.

**Comment by dsame** [comment] 2021-10-19 04:54
@grzegorzkrukowski 

Hi, while i was not able to reproduce the problem and get more tracing info of active script, can you please change your build to use `dtruss` with `osascript` in order to let us know that is going on on build fail.

Because of SIP limitation it is not possible to debug `/usr/bin/osascript` and you should create unsigned copy of it.

```
sudo cp /usr/bin/osascript /tmp
sudo codesign --remove-signature /tmp/osascript
sudo dtruss -a /tmp/osascript ...
```

The exact commit for your workflow: 
```
https://github.com/akv-platform/github-oascript-bug/commit/da8742d015d20e3bc64142aba35a021dc797eef1
```

**Comment by miketimofeev** [comment] 2021-11-03 10:22
@grzegorzkrukowski I'm going to close the issue.
Please feel free to contact us if you have any concerns.
Thank you!

**Closed by miketimofeev** 2021-11-03 10:22 UTC
Labels: OS: macOS, Area: Common Tools, investigate

**Comment by gputto** [comment] 2022-04-17 12:20
Hi,
I just thought I'd let you all know that I had this *exact* issue -
restarting / reinstalling macOS over the top didn't help whatsoever, I still encountered the:
"osascript: can't open default scripting component." error.

I found a little nugget of usefullness on another forum relating to this, that suggested an audio component file located within "/Library/Audio/Plug-Ins/Components" was to blame.
I removed all the components, and the osascript error disappeared immediately (no restart required).
I re-added the components one at a time, and found that one of my plugins (FabFilter Pro-C 2.component) was causing this issue all along.

Just thought I'd let you all know just in case anyone else has the same issue!
Cheers

**Comment by kalatix** [comment] 2023-01-29 21:44
> Hi, I just thought I'd let you all know that I had this _exact_ issue - restarting / reinstalling macOS over the top didn't help whatsoever, I still encountered the: "osascript: can't open default scripting component." error.
> 
> I found a little nugget of usefullness on another forum relating to this, that suggested an audio component file located within "/Library/Audio/Plug-Ins/Components" was to blame. I removed all the components, and the osascript error disappeared immediately (no restart required). I re-added the components one at a time, and found that one of my plugins (FabFilter Pro-C 2.component) was causing this issue all along.
> 
> Just thought I'd let you all know just in case anyone else has the same issue! Cheers

This worked for me. Moved all plugins from the components folder to the desktop and it was able to continue. Thanks!

**Comment by glennpaulmusic** [comment] 2023-02-03 23:44
I fixed this problem myself! i tried doing what "kalatix" said and it didnt work, but i kept looking at folders close to the library and audio plug ins. There was a folder called "SDKS" that had a bunch of macos.sdk folders that i put in the bin. Once I did that, it let me build and install open core to my hard drive, and now i dont need the flash drive to boot.

This is my first github post. am I a hacker now?

**Comment by Charmfiend** [comment] 2023-05-03 03:00
> Hi, I just thought I'd let you all know that I had this _exact_ issue - restarting / reinstalling macOS over the top didn't help whatsoever, I still encountered the: "osascript: can't open default scripting component." error.
> 
> I found a little nugget of usefullness on another forum relating to this, that suggested an audio component file located within "/Library/Audio/Plug-Ins/Components" was to blame. I removed all the components, and the osascript error disappeared immediately (no restart required). I re-added the components one at a time, and found that one of my plugins (FabFilter Pro-C 2.component) was causing this issue all along.
> 
> Just thought I'd let you all know just in case anyone else has the same issue! Cheers

I found a newly installed audio plugin component ChopSuey.component was causing the "osascript: can't open default scripting component." error. Thank you so much.

**Comment by hteumeuleu** [comment] 2023-08-16 08:09
> 

Oh my, thank you for this. Turns out I had a faulty audio plugin component as well that was causing this issue.
