### ISSUE TITLE
Seg Faults in Linux with Python 3.10.0

### ISSUE THREAD

**Issue by danyeaw** [actions/virtual-environments#4534] opened 2021-11-18 02:46 UTC
### Description

In the GitHub Actions ubuntu-latest runner, I am getting a segmentation fault while running some of my Python tests using Pytest with Python 3.10. The tests all pass fine locally, and all pass with macOS and Windows on GitHub Actions.

I had a similar issue in the past with Python 3.7: https://github.com/actions/virtual-environments/issues/159.

When running the tests with gdb, I am getting:
```
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
__GI___libc_free (mem=0x20) at malloc.c:3102
3102	malloc.c: No such file or directory.
```

### Virtual environments affected

- [x] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

2.284.0

https://github.com/danyeaw/plugin-console-test/actions/runs/1474634868

### Is it regression?

No

### Expected behavior

No Python seg faults when running Python 3.10.0 on CI.

### Actual behavior

```
Run xvfb-run pytest
  xvfb-run pytest
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.10.0/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.0/x64/lib
Fatal Python error: Segmentation fault

Current thread 0x00007f5c20383740 (most recent call first):
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1176 in create_module
  File "<frozen importlib._bootstrap>", line 571 in module_from_spec
  File "<frozen importlib._bootstrap>", line 674 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1006 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/rlcompleter.py", line 210 in <module>
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 883 in exec_module
  File "<frozen importlib._bootstrap>", line 688 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1006 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load
  File "/home/runner/work/plugin-console-test/plugin-console-test/plugin/console.py", line 2 in <module>
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 883 in exec_module
  File "<frozen importlib._bootstrap>", line 688 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1006 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load
  File "/home/runner/work/plugin-console-test/plugin-console-test/tests/test_console.py", line 7 in <module>
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 170 in exec_module
  File "<frozen importlib._bootstrap>", line 688 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1006 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load
  File "<frozen importlib._bootstrap>", line 1050 in _gcd_import
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/importlib/__init__.py", line 126 in import_module
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/_pytest/pathlib.py", line 524 in import_path
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/_pytest/python.py", line 578 in _importtestmodule
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/_pytest/python.py", line 500 in _getobj
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/_pytest/python.py", line 291 in obj
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/_pytest/python.py", line 516 in _inject_setup_module_fixture
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/_pytest/python.py", line 503 in collect
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/_pytest/runner.py", line 341 in <lambda>
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/_pytest/runner.py", line 311 in from_call
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/_pytest/runner.py", line 341 in pytest_make_collect_report
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/_pytest/runner.py", line 458 in collect_one_node
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/_pytest/main.py", line 808 in genitems
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/_pytest/main.py", line 811 in genitems
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/_pytest/main.py", line 634 in perform_collect
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/_pytest/main.py", line 333 in pytest_collection
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/_pytest/main.py", line 322 in _main
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/_pytest/main.py", line 269 in wrap_session
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/_pytest/main.py", line 316 in pytest_cmdline_main
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/_pytest/config/__init__.py", line 162 in main
  File "/opt/hostedtoolcache/Python/3.10.0/x64/lib/python3.10/site-packages/_pytest/config/__init__.py", line 185 in console_main
  File "/opt/hostedtoolcache/Python/3.10.0/x64/bin/pytest", line 8 in <module>

Extension modules: gi._gi, cairo._cairo, gi._gi_cairo (total: 3)
Segmentation fault (core dumped)
```

With gdb:
```
Starting program: /home/runner/work/gaphor/gaphor/.venv/bin/python -m pytest
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffecd36700 (LWP 5413)]
[New Thread 0x7fffebd35700 (LWP 5414)]
[New Thread 0x7fffead34700 (LWP 5415)]
[New Thread 0x7fffe9d33700 (LWP 5416)]
[New Thread 0x7fffdbfff700 (LWP 5417)]
[New Thread 0x7fffdaffe700 (LWP 5418)]
[New Thread 0x7fffd9ffd700 (LWP 5419)]
[New Thread 0x7fffc7fff700 (LWP 5420)]
[Detaching after fork from child process 5421]

Thread 1 "python" received signal SIGSEGV, Segmentation fault.
__GI___libc_free (mem=0x20) at malloc.c:3102
3102	malloc.c: No such file or directory.Starting program: /home/runner/work/gaphor/gaphor/.venv/bin/python -m pytest
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffecd36700 (LWP 5413)]
[New Thread 0x7fffebd35700 (LWP 5414)]
[New Thread 0x7fffead34700 (LWP 5415)]
[New Thread 0x7fffe9d33700 (LWP 5416)]
[New Thread 0x7fffdbfff700 (LWP 5417)]
[New Thread 0x7fffdaffe700 (LWP 5418)]
[New Thread 0x7fffd9ffd700 (LWP 5419)]
[New Thread 0x7fffc7fff700 (LWP 5420)]
[Detaching after fork from child process 5421]

Thread 1 "python" received signal SIGSEGV, Segmentation fault.
__GI___libc_free (mem=0x20) at malloc.c:3102
3102	malloc.c: No such file or directory.
```

### Repro steps

This was initially discussed in https://github.com/gaphor/gaphor/issues/1122. I created a minimum reproducible example here: https://github.com/danyeaw/plugin-console-test.

**Comment by mikhailkoliada** [comment] 2021-11-18 09:13
@danyeaw Hello!
Thanks! We will take a look.

**Comment by danyeaw** [comment] 2021-11-18 11:40
Thanks @mikhailkoliada!

**Comment by dmitry-shibanov** [comment] 2021-11-24 12:50
Hello @danyeaw. We've investigated the issue and it looks like we can't fix it from our side. We think it's mostly related to the python itself. Besides, I want to ask you, if it's required for you to run tests through `xvfb-run` ? We've run your tests without this tools and it works as expected.
Actually the issue with python 3.7 still persists. Previously ubuntu-latest pointed to ubuntu-18.04, but now it uses ubuntu-20.04. If you run your test on ubuntu-18.04, it will fail with the same error.

**Comment by danyeaw** [comment] 2021-11-25 18:07
@dmitry-shibanov Thanks for investigating the issue, I really appreciate it. I have further reduced the minimum reproducible example. It requires:

1. xvfb to run the tests
2. import Gtk and rlcompleter
3. pytest
4. Python 3.7 on ubuntu-18.04 or Python 3.10 or 3.7 on ubuntu-20.04, Python 3.8 and Python 3.9 work on all OSes, all Python versions work in Windows and macOS
5. GitHub Actions runner, I am not able to reproduce this locally

You are right, with this example I don't need xvfb - but the real project that I found this issue with does need it.

**Comment by danyeaw** [comment] 2021-11-28 13:36
I have looked in to this more and it impacts readline or any module that uses readline (doctest, rlcompleter). A workaround is to avoid using modules that use readline.

I also submitted an issue to the Python Bug tracker: https://bugs.python.org/issue45913

I also created a workflow that builds Python with debug enabled: https://github.com/danyeaw/setup-python-debug/

**Comment by dibir-magomedsaygitov** [comment] 2021-12-17 07:16
Hello @danyeaw. I'm going to close this issue since the root cause is in python itself, not the image, but in case of any question or concerns feel free to contact us. Thank you!

**Closed by dibir-magomedsaygitov** 2021-12-17 07:16 UTC
Labels: Area: Python, investigate, external
