### ISSUE TITLE
Windows (C++ builds): The upgrade from 16.8 to 16.9: "C4103: alignment changed after including header"

### ISSUE THREAD

**Issue by adamkewley** [actions/virtual-environments#2988] opened 2021-03-19 09:27 UTC
Hi,

This isn't a fixable issue *per se*--because the fix might involve a downgrade--but I'm posting it for information in case other devs encounter it. The proposed (downstream) fix for this appears to be to not use `/-permissive` in C++ builds. I haven't confirmed this with my own codebase yet. The VS 16.10 preview also seems to contain this issue, so an upgrade may not fix it either.

---

I'm using the `windows-2019` image to build [this](https://github.com/adamkewley/osmv) C++ project. Over the last few days, I have been getting C4103 errors like this:

```text
D:\a\osmv\osmv\third_party\glm\glm\detail\../exponential.hpp(21,1): error C2220: the following warning is treated as an error [D:\a\osmv\osmv\osmv-build\osmv.vcxproj]
D:\a\osmv\osmv\third_party\glm\glm\detail\../exponential.hpp(21,1): warning C4103: alignment changed after including header, may be due to missing #pragma pack(pop) [D:\a\osmv\osmv\osmv-build\osmv.vcxproj]
D:\a\osmv\osmv\third_party\glm\glm\detail/func_geometric.inl(1,1): warning C4103: alignment changed after including header, may be due to missing #pragma pack(pop) [D:\a\osmv\osmv\osmv-build\osmv.vcxproj]
D:\a\osmv\osmv\third_party\glm\glm\ext\../geometric.hpp(116,1): warning C4103: alignment changed after including header, may be due to missing #pragma pack(pop) [D:\a\osmv\osmv\osmv-build\osmv.vcxproj]
D:\a\osmv\osmv\third_party\glm\glm/ext/matrix_transform.hpp(24,1): warning C4103: alignment changed after including header, may be due to missing #pragma pack(pop) [D:\a\osmv\osmv\osmv-build\osmv.vcxproj]
D:\a\osmv\osmv\src/3d/gl.hpp(4,1): warning C4103: alignment changed after including header, may be due to missing #pragma pack(pop) [D:\a\osmv\osmv\osmv-build\osmv.vcxproj]
D:\a\osmv\osmv\src\application.cpp(4,1): warning C4103: alignment changed after including header, may be due to missing #pragma pack(pop) [D:\a\osmv\osmv\osmv-build\osmv.vcxproj]
```

Without there being an obvious relationship to the source code changes. 

My project is in flux, so I do introduce errors frequently. However, this error *appears* to be related to a change in the toolset. Before these messages appeared, the toolchain is 16.8.3 ([link](https://github.com/adamkewley/osmv/runs/2088998538?check_suite_focus=true#step:3:6415)); afterwards, it's 16.9.0 ([link](https://github.com/adamkewley/osmv/runs/2116018340?check_suite_focus=true#step:3:6372)).

I believe this error is related to the toolchain upgrade mentioned in #2878 . Usually, I'd go and fix any issues a toolchain upgrade finds (new error checks, more warnings, etc.), but this particular issue seems to be related to [this](https://developercommunity.visualstudio.com/t/warning-c4103-in-visual-studio-166-update/1057589) change, which an MSFT dev seems to mention can be fixed by unsetting `/-permissive` in my downstream code. However, unsetting that (i.e. making my codebase *more* permissive) will require a fair amount of code changes in my project. This is because I'm using ISO-standard keywords like `and` and `or`, which VS's `permissive` mode (the default) disables (because they may be defined as macros in legacy codebases).

I'm guessing there is little-to-no interest in downgrading the container, so I'm guessing this issue is going to be frozen into the `windows-2019` container from now on. This isn't a *massive* problem for my project--I can just go and refactor those `and`s and `or`s out--but I figured it would be prudent to write this up in case other downstream C++ devs run into it.

Related links:
| Link | Comment |
| - | - |
| [click](https://developercommunity.visualstudio.com/t/warning-c4103-in-visual-studio-166-update/1057589) | related issue: `windows-2019` upgraded MSVC from 16.8 to 16.9 |
| [click](https://github.com/adamkewley/osmv/runs/2116018340?check_suite_focus=true#step:3:6992) | example error |
| [click](https://github.com/adamkewley/osmv/runs/2088998538?check_suite_focus=true#step:3:6415) | example build before |
| [click](https://github.com/adamkewley/osmv/runs/2116018340?check_suite_focus=true#step:3:6372) | example build after |
| [click](https://developercommunity.visualstudio.com/t/warning-c4103-in-visual-studio-166-update/1057589) | related issue on visualstudio.com |

**Comment by maxim-lobanov** [comment] 2021-03-19 09:35
Thank you for heads up @adamkewley!
Unfortunately, we can't do much from our side because Visual Studio doesn't provide way to install non-latest version 😢 
So we can't downgrade VS on our machines. VS19 installer will always install latest (16.9) version starting from release.

**Comment by adamkewley** [comment] 2021-03-19 10:08
Yeah, I suspected that might be the case @maxim-lobanov :<

I can probably just fix this in my own codebase by dropping the `/-permissive` use and refactoring the keywords out - not a big deal on my end. Lucky for me, this is still a prototypical project and I'm sole-developing with only a few (easy to compile/upgrade) in-tree dependencies.

I imagine devs on larger C++ projects /w collaborators, change control workflows, etc. could get stung by this - although it's unlikely that legacy codebases will be using `/-permissive`

**Comment by adamkewley** [comment] 2021-03-19 13:44
Just for supporting information, I can confirm what the visualstudio.com ticket says: disabling `/-permissive` does remove this issue (which seems to originate in `<cmath>`). 

After upgrading to a newer VS on my workstation, I was able to reproduce the issue (align errors, etc.). I then switched off `/-permissive`, removed the `and` keywords, etc. (along with unrelated fixes to make VS's integrated CMake play nice with my custom dependency setup) and I managed to get everything building again. 

Example diff for that (small project):

https://github.com/adamkewley/osmv/commit/881fdf95a8eb448acb5b22384ddb74b117996234

Not a major upheaval for me, but finding the issue took a little time, so hopefull this pops up in other dev's searches if they encounter something similar in CI.

**Comment by miketimofeev** [comment] 2021-04-05 06:28
@adamkewley we have updated the image with visual studio 16.9.31129.286. Could you please check the behavior?

**Comment by adamkewley** [comment] 2021-04-07 08:07
@miketimofeev , I've fixed the core issue in-tree (by refactoring out the things that depend on `/-permissive`), so I can't test it on my latest builds.

What I can do, though, is launch a build against an old commit that I *think* was broken because of this issue (it's a commit just before I went in and manually dropped `/-permissive`). Info:

| Action | Comment |
| - | - |
| [725287707](https://github.com/adamkewley/osmv/actions/runs/725287707) | Re-submitted previously broken build under new branch `check_github-ve-iss-2988` |
| [665926038](https://github.com/adamkewley/osmv/actions/runs/665926038) | Previous build of the exact same commit - failed due to the alignment error |

Build takes a while (I haven't implemented caching yet) but that should hopefully provide you with enough information to see if this is still persisting

**Comment by adamkewley** [comment] 2021-04-07 08:11
I will try and follow this up later to confirm it myself (I'm more familiar with the logs etc)

**Comment by adamkewley** [comment] 2021-04-07 10:58
@miketimofeev , looks like there's still something unusual going on with the alignment stuff:

https://github.com/adamkewley/osmv/runs/2285478793?check_suite_focus=true#step:3:6934

There's other build bugs unrelated to this, but I believe the alignment message is specifically related to the original issue :(

**Comment by miketimofeev** [comment] 2021-04-08 08:18
@adamkewley Sorry to hear that. Could you please raise the issue on https://developercommunity.visualstudio.com/?

**Comment by miketimofeev** [comment] 2021-04-16 07:42
@adamkewley I'm going to close the issue since the root cause seems to be on the VS side and we can't do anything here.
Please feel free to contact us if you have any concerns.
Thank you!

**Closed by miketimofeev** 2021-04-16 07:42 UTC
Labels: Area: C/C++, OS: Windows, bug
