### ISSUE TITLE
Hash Mismatch

### ISSUE THREAD

**Issue by hutson** [actions/virtual-environments#3551] opened 2021-06-08 15:32 UTC
**Description**  

The Visual Studio script fails with SHA256 mismatch:

```
==> ami: Provisioning with powershell script: /home/ubuntu/actions-runner/_work/virtual-environments/virtual-environments/virtual-environments/images/win/scripts/Installers/Install-VS.ps1
    ami: Downloading Bootstrapper ...
    ami: Downloading package from: https://aka.ms/vs/15/release/vs_Enterprise.exe to path C:\Users\INSTAL~1\AppData\Local\Temp\vs_Enterprise.exe .
    ami: Enable short name support on Windows needed for Xamarin Android AOT, defaults appear to have been changed in Azure VMs
    ami: Starting Install ...
    ami: Something went wrong with the install.
    ami:
    ami: You can troubleshoot the package failures by:
    ami:
    ami:     1. Search for solutions using the search URL below for each package failure
    ami:     2. Modify your selections for the affected workloads or components and then retry the installation
    ami:     3. Remove the product from your machine and then install again
    ami:
    ami: If the issue has already been reported on the Developer Community, you can find solutions or workarounds there. If the issue has not been reported, we encourage you to create a new issue so that other developers will be able to find solutions or workarounds. You can create a new issue from within the Visual Studio Installer in the upper-right hand corner using the "Provide feedback" button.
    ami:
    ami: ================================================================================
    ami:
    ami: Package 'Microsoft.VisualC.140.CRT.x64.Store.Msi,version=14.0.24234' failed to download from 'https://download.visualstudio.microsoft.com/download/pr/12045808/91b4a5914d7964d28b101273226f8580/cab1.cab'.
    ami:     Search URL
    ami:         https://aka.ms/VSSetupErrorReports?q=PackageId=Microsoft.VisualC.140.CRT.x64.Store.Msi;PackageAction=DownloadPackage;ReturnCode=0x80096004
    ami:     Details
    ami:         WebClient download failed: SHA256 verification for 'cab1.cab' failed. Expected hash: 9E1553F13DA7166721957C69CFA35BCB6E84FF86ABB12B480A82E65BC35B6E19, Actual hash: 375A80A5B5DBB2F6BACD170636A97AAAADE93C06DB2919452218F0A696FF87A3
    ami:         Bits download failed: The operation being requested was not performed because the user has not logged on to the network. The specified service does not exist. (Exception from HRESULT: 0x800704DD)
    ami:         WinInet download failed: SHA256 verification for 'cab1.cab' failed. Expected hash: 9E1553F13DA7166721957C69CFA35BCB6E84FF86ABB12B480A82E65BC35B6E19, Actual hash: 375A80A5B5DBB2F6BACD170636A97AAAADE93C06DB2919452218F0A696FF87A3
    ami:     Impacted workloads
    ami:         Desktop development with C++ (Microsoft.VisualStudio.Workload.NativeDesktop,version=15.9.28307.102)
    ami:     Impacted components
    ami:         VC++ 2015.3 v14.00 (v140) toolset for desktop (Microsoft.VisualStudio.Component.VC.140,version=15.7.27617.1)
    ami:
    ami: Non zero exit code returned by the installation process : 1
```

Filing this issue mostly for visibility.

It appears this issue came up in the past, #1854, and may an an internal issue with the Microsoft CDN.

**Area for Triage**:  

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Image version**

We are cloning this repository at a specific commit (From just yesterday) and building the image on our own infrastructure.

```
 git clone https://github.com/actions/virtual-environments
git checkout 395eb43c2bdc41bac61cbd0ad4dcdd8f80eb1506
```

**Expected behavior**  

For the Visual Studio installation to complete successfully.

**Actual behavior**  

SHA256 mismatch when downloading a Visual Studio dependency:

```
==> ami: Provisioning with powershell script: /home/ubuntu/actions-runner/_work/virtual-environments/virtual-environments/virtual-environments/images/win/scripts/Installers/Install-VS.ps1
    ami: Downloading Bootstrapper ...
    ami: Downloading package from: https://aka.ms/vs/15/release/vs_Enterprise.exe to path C:\Users\INSTAL~1\AppData\Local\Temp\vs_Enterprise.exe .
    ami: Enable short name support on Windows needed for Xamarin Android AOT, defaults appear to have been changed in Azure VMs
    ami: Starting Install ...
    ami: Something went wrong with the install.
    ami:
    ami: You can troubleshoot the package failures by:
    ami:
    ami:     1. Search for solutions using the search URL below for each package failure
    ami:     2. Modify your selections for the affected workloads or components and then retry the installation
    ami:     3. Remove the product from your machine and then install again
    ami:
    ami: If the issue has already been reported on the Developer Community, you can find solutions or workarounds there. If the issue has not been reported, we encourage you to create a new issue so that other developers will be able to find solutions or workarounds. You can create a new issue from within the Visual Studio Installer in the upper-right hand corner using the "Provide feedback" button.
    ami:
    ami: ================================================================================
    ami:
    ami: Package 'Microsoft.VisualC.140.CRT.x64.Store.Msi,version=14.0.24234' failed to download from 'https://download.visualstudio.microsoft.com/download/pr/12045808/91b4a5914d7964d28b101273226f8580/cab1.cab'.
    ami:     Search URL
    ami:         https://aka.ms/VSSetupErrorReports?q=PackageId=Microsoft.VisualC.140.CRT.x64.Store.Msi;PackageAction=DownloadPackage;ReturnCode=0x80096004
    ami:     Details
    ami:         WebClient download failed: SHA256 verification for 'cab1.cab' failed. Expected hash: 9E1553F13DA7166721957C69CFA35BCB6E84FF86ABB12B480A82E65BC35B6E19, Actual hash: 375A80A5B5DBB2F6BACD170636A97AAAADE93C06DB2919452218F0A696FF87A3
    ami:         Bits download failed: The operation being requested was not performed because the user has not logged on to the network. The specified service does not exist. (Exception from HRESULT: 0x800704DD)
    ami:         WinInet download failed: SHA256 verification for 'cab1.cab' failed. Expected hash: 9E1553F13DA7166721957C69CFA35BCB6E84FF86ABB12B480A82E65BC35B6E19, Actual hash: 375A80A5B5DBB2F6BACD170636A97AAAADE93C06DB2919452218F0A696FF87A3
    ami:     Impacted workloads
    ami:         Desktop development with C++ (Microsoft.VisualStudio.Workload.NativeDesktop,version=15.9.28307.102)
    ami:     Impacted components
    ami:         VC++ 2015.3 v14.00 (v140) toolset for desktop (Microsoft.VisualStudio.Component.VC.140,version=15.7.27617.1)
    ami:
    ami: Non zero exit code returned by the installation process : 1
```

**Repro steps**  

This issue can be reproduced by simply running this repository's own build.

The specific commit listed above generates this specific error in GitHub's Azure build - https://github.visualstudio.com/virtual-environments/_build/results?buildId=110918&view=results

**Comment by miketimofeev** [comment] 2021-06-08 16:54
Hi @hutson!
We're aware of it and already engaged CDN support as the issue is reproducible only from some regions.
As a workaround, the following steps can be added at the very beginning of the [Install-VS.ps1](https://github.com/actions/virtual-environments/blob/main/images/win/scripts/Installers/Install-VS.ps1) script:
```
Copy-Item -Path "$env:windir\System32\drivers\etc\hosts" -Destination "C:\hosts_backup" -Verbose
"68.232.34.200 download.visualstudio.microsoft.com" > "$env:windir\System32\drivers\etc\hosts"
```
and this at the end of the script:
```
Move-Item -Path "C:\hosts_backup" -Destination "$env:windir\System32\drivers\etc\hosts" -Force -Verbose
```

**Comment by miketimofeev** [comment] 2021-06-09 07:46
@hutson this should be resolved by now.
I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!

**Closed by miketimofeev** 2021-06-09 07:46 UTC
Labels: Area: Image administration, OS: Windows, bug
