### ISSUE TITLE
Wrong default Ruby version is used?

### ISSUE THREAD

**Issue by simmel** [actions/virtual-environments#3310] opened 2021-05-04 18:09 UTC
**Description**  
I have a pipeline which uses the default "ubuntu-latest" to validate some puppet conf. Last time it worked was 7 months ago (but the logs are gone so I can't see the version).

**Area for Triage**:  
Ruby

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
20210425.1

**Expected behavior**  
Ruby 2.7 should actually be used and URI.escape which exists in 2.7 should work even though it's removed in 3.0.

**Actual behavior**  
Installed version behaves like 3.0 and URI.escape is missing.

```
libruby2.7:amd64: /usr/lib/ruby/2.7.0/bundler/vendor/uri/lib/uri.rb
libruby2.7:amd64: /usr/lib/ruby/2.7.0/optparse/uri.rb
libruby2.7:amd64: /usr/lib/ruby/2.7.0/open-uri.rb
libruby2.7:amd64: /usr/lib/ruby/2.7.0/uri.rb
libruby2.7:amd64: /usr/lib/ruby/2.7.0/bundler/vendored_uri.rb
-e:1:in `<main>': undefined method `escape' for URI:Module (NoMethodError)
Error: Process completed with exit code 1.
```
**Repro steps**  

```yaml
 CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: install
      run: "sudo apt-get update >/dev/null && sudo apt-get install -y puppet >/dev/null && ruby --version && dpkg -S uri.rb && ruby -ruri -e 'puts URI.escape(\"/a p a\")'"

    - name: puppet parser validate
      run: "puppet parser validate ."
```

**Comment by maxim-lobanov** [comment] 2021-05-04 18:15
@simmel it is recommended to use official Ruby action to make sure that your build uses specific Ruby version: https://github.com/ruby/setup-ruby

**Comment by miketimofeev** [comment] 2021-05-04 18:56
@simmel as @maxim-lobanov mentioned could you try to use setup-ruby task and check if the issue persists? The default ruby version on Ubuntu 20 is definitely 2.7.0

**Comment by simmel** [comment] 2021-05-05 07:46
Using this name made the ruby command work but puppet still doesn't work (which uses the Ruby from Ubuntu):
```yaml
name: CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: install
      run: "sudo apt-get update >/dev/null && sudo apt-get install -y puppet >/dev/null && ruby -ruri -e 'puts URI.escape(\"/a p a\")' && puppet --version"

    - name: puppet parser validate
      run: "puppet parser validate ."
```
gives
```
Run sudo apt-get update >/dev/null && sudo apt-get install -y puppet >/dev/null && ruby -ruri -e 'puts URI.escape("/a p a")' && puppet --version
-e:1: warning: URI.escape is obsolete
/a%20p%20a
/usr/lib/ruby/vendor_ruby/puppet/util.rb:461:in `uri_encode': undefined method `escape' for URI:Module (NoMethodError)
	from /usr/lib/ruby/vendor_ruby/puppet/util.rb:337:in `path_to_uri'
	from /usr/lib/ruby/vendor_ruby/puppet/pops/model/ast.rb:4863:in `register_pcore_types'
	from /usr/lib/ruby/vendor_ruby/puppet/pops.rb:119:in `<module:Puppet>'
	from /usr/lib/ruby/vendor_ruby/puppet/pops.rb:1:in `<top (required)>'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:8:in `<top (required)>'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/lib/ruby/vendor_ruby/puppet/parser.rb:6:in `<top (required)>'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/lib/ruby/vendor_ruby/puppet.rb:299:in `<top (required)>'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/lib/ruby/vendor_ruby/puppet/util/command_line.rb:12:in `<top (required)>'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/bin/puppet:4:in `<main>'
Error: Process completed with exit code 1.
```
So some how the system Ruby is broken.

I have a machine running Ubuntu 20.04 and the Ruby version is the same but it works on my machine just not in Githubs ubuntu-latest. So no offence or anything but it must be something you broke = )

Very fast response time though, thank you for that!

**Comment by miketimofeev** [comment] 2021-05-05 07:52
@simmel thanks for reporting back. We'll take a closer look at this

**Comment by maxim-lobanov** [comment] 2021-05-05 08:24
@simmel what version of puppet do you have on your local machine?
Your example `ruby -ruri -e 'puts URI.escape("/a p a")'` proves that Ruby works correctly on images and something goes wrong with puppet

**Comment by simmel** [comment] 2021-05-05 09:51
I made an public MCVE repo instead to make it easier and here is the latest run (which fails) https://github.com/simmel/actions-virtual-environments-issues-3310/runs/2508107592

For the archive, here is the Github Action config:
```yaml
name: CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: install
      run: "sudo apt-get update >/dev/null && sudo apt-get install -y puppet >/dev/null && dpkg -l '*ruby*' '*puppet*' && which ruby puppet && head -n1 `which puppet` && ruby --version && /usr/bin/ruby --version && ruby -ruri -e 'puts URI.escape(\"/a p a\")'"

    - name: puppet version
      run: "puppet --version"
```

Here is the output (the history/archive):
```
Run sudo apt-get update >/dev/null && sudo apt-get install -y puppet >/dev/null && dpkg -l '*ruby*' '*puppet*' && which ruby puppet && head -n1 `which puppet` && ruby --version && /usr/bin/ruby --version && ruby -ruri -e 'puts URI.escape("/a p a")'
  sudo apt-get update >/dev/null && sudo apt-get install -y puppet >/dev/null && dpkg -l '*ruby*' '*puppet*' && which ruby puppet && head -n1 `which puppet` && ruby --version && /usr/bin/ruby --version && ruby -ruri -e 'puts URI.escape("/a p a")'
  shell: /usr/bin/bash -e {0}
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                       Version          Architecture Description
+++-==========================-================-============-========================================================================
ii  libruby2.7:amd64           2.7.0-5ubuntu1.4 amd64        Libraries necessary to run Ruby 2.7
ii  puppet                     5.5.10-4ubuntu3  all          configuration management system
un  puppet-agent               <none>           <none>       (no description available)
un  puppet-common              <none>           <none>       (no description available)
un  puppetmaster-common        <none>           <none>       (no description available)
ii  ruby                       1:2.7+1          amd64        Interpreter of object-oriented scripting language Ruby (default version)
un  ruby-activesupport-2.3     <none>           <none>       (no description available)
un  ruby-activesupport-3.2     <none>           <none>       (no description available)
ii  ruby-augeas                1:0.5.0-3build7  amd64        Augeas bindings for the Ruby language
un  ruby-benchmark             <none>           <none>       (no description available)
un  ruby-bigdecimal            <none>           <none>       (no description available)
un  ruby-bootsnap              <none>           <none>       (no description available)
un  ruby-cgi                   <none>           <none>       (no description available)
un  ruby-csv                   <none>           <none>       (no description available)
un  ruby-date                  <none>           <none>       (no description available)
un  ruby-dbm                   <none>           <none>       (no description available)
un  ruby-debian                <none>           <none>       (no description available)
ii  ruby-deep-merge            1.1.1-1          all          recursively merge Hash elements in Ruby
un  ruby-delegate              <none>           <none>       (no description available)
ii  ruby-dev:amd64             1:2.7+1          amd64        Header files for compiling extension modules for Ruby (default version)
un  ruby-did-you-mean          <none>           <none>       (no description available)
un  ruby-etc                   <none>           <none>       (no description available)
un  ruby-fcntl                 <none>           <none>       (no description available)
un  ruby-fiddle                <none>           <none>       (no description available)
un  ruby-fileutils             <none>           <none>       (no description available)
un  ruby-forwardable           <none>           <none>       (no description available)
ii  ruby-full                  1:2.7+1          all          Ruby full installation (default version)
un  ruby-gdbm                  <none>           <none>       (no description available)
un  ruby-getoptlong            <none>           <none>       (no description available)
un  ruby-gettext-setup         <none>           <none>       (no description available)
un  ruby-gobject-introspection <none>           <none>       (no description available)
un  ruby-hocon                 <none>           <none>       (no description available)
un  ruby-interpreter           <none>           <none>       (no description available)
un  ruby-io-console            <none>           <none>       (no description available)
un  ruby-ipaddr                <none>           <none>       (no description available)
un  ruby-irb                   <none>           <none>       (no description available)
un  ruby-json                  <none>           <none>       (no description available)
un  ruby-logger                <none>           <none>       (no description available)
un  ruby-matrix                <none>           <none>       (no description available)
ii  ruby-minitest              5.13.0-1         all          Ruby test tools supporting TDD, BDD, mocking, and benchmarking
un  ruby-mutex-m               <none>           <none>       (no description available)
un  ruby-net-pop               <none>           <none>       (no description available)
un  ruby-net-smtp              <none>           <none>       (no description available)
ii  ruby-net-telnet            0.1.1-2          all          telnet client library
un  ruby-observer              <none>           <none>       (no description available)
un  ruby-open3                 <none>           <none>       (no description available)
un  ruby-openssl               <none>           <none>       (no description available)
un  ruby-ostruct               <none>           <none>       (no description available)
ii  ruby-power-assert          1.1.7-1          all          library showing values of variables and method calls in an expression
un  ruby-prime                 <none>           <none>       (no description available)
un  ruby-pstore                <none>           <none>       (no description available)
un  ruby-psych                 <none>           <none>       (no description available)
un  ruby-racc                  <none>           <none>       (no description available)
un  ruby-rdoc                  <none>           <none>       (no description available)
un  ruby-readline              <none>           <none>       (no description available)
un  ruby-readline-ext          <none>           <none>       (no description available)
un  ruby-reline                <none>           <none>       (no description available)
un  ruby-rexml                 <none>           <none>       (no description available)
un  ruby-rrd                   <none>           <none>       (no description available)
un  ruby-rss                   <none>           <none>       (no description available)
un  ruby-sdbm                  <none>           <none>       (no description available)
ii  ruby-selinux:amd64         3.0-1build2      amd64        Ruby bindings to SELinux shared libraries
ii  ruby-shadow                2.5.0-1build2    amd64        interface of shadow password for Ruby
un  ruby-singleton             <none>           <none>       (no description available)
un  ruby-stringio              <none>           <none>       (no description available)
un  ruby-strscan               <none>           <none>       (no description available)
un  ruby-switch                <none>           <none>       (no description available)
ii  ruby-sync                  0.5.0-1          all          two-phase lock with a counter
ii  ruby-test-unit             3.3.5-1          all          unit testing framework for Ruby
un  ruby-timeout               <none>           <none>       (no description available)
un  ruby-tracer                <none>           <none>       (no description available)
un  ruby-uri                   <none>           <none>       (no description available)
un  ruby-webrick               <none>           <none>       (no description available)
ii  ruby-xmlrpc                0.3.0-2          all          XMLRPC library for Ruby
un  ruby-yaml                  <none>           <none>       (no description available)
un  ruby-zlib                  <none>           <none>       (no description available)
ii  ruby2.7                    2.7.0-5ubuntu1.4 amd64        Interpreter of object-oriented scripting language Ruby
ii  ruby2.7-dev:amd64          2.7.0-5ubuntu1.4 amd64        Header files for compiling extension modules for the Ruby 2.7
ii  ruby2.7-doc                2.7.0-5ubuntu1.4 all          Documentation for Ruby 2.7
un  rubygems                   <none>           <none>       (no description available)
ii  rubygems-integration       1.16             all          integration of Debian Ruby packages with Rubygems
/opt/hostedtoolcache/Ruby/2.7.3/x64/bin/ruby
/usr/bin/puppet
#!/usr/bin/ruby
ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-linux]
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
-e:1: warning: URI.escape is obsolete
/a%20p%20a
```
and
```
Run puppet --version
/usr/lib/ruby/vendor_ruby/puppet/util.rb:461:in `uri_encode': undefined method `escape' for URI:Module (NoMethodError)
	from /usr/lib/ruby/vendor_ruby/puppet/util.rb:337:in `path_to_uri'
	from /usr/lib/ruby/vendor_ruby/puppet/pops/model/ast.rb:4863:in `register_pcore_types'
	from /usr/lib/ruby/vendor_ruby/puppet/pops.rb:119:in `<module:Puppet>'
	from /usr/lib/ruby/vendor_ruby/puppet/pops.rb:1:in `<top (required)>'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:8:in `<top (required)>'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/lib/ruby/vendor_ruby/puppet/parser.rb:6:in `<top (required)>'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/lib/ruby/vendor_ruby/puppet.rb:299:in `<top (required)>'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/lib/ruby/vendor_ruby/puppet/util/command_line.rb:12:in `<top (required)>'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/bin/puppet:4:in `<main>'
Error: Process completed with exit code 1.
```

**Comment by simmel** [comment] 2021-05-05 09:52
Here is the output from my local Ubuntu machine:
```terminal
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
$ dpkg -l '*ruby*' '*puppet*' && which ruby puppet && head -n1 `which puppet` && ruby --version && /usr/bin/ruby --version && ruby -ruri -e 'puts URI.escape("/a p a")'
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                       Version          Architecture Description
+++-==========================-================-============-========================================================================
ii  libruby2.7:amd64           2.7.0-5ubuntu1.4 amd64        Libraries necessary to run Ruby 2.7
ii  puppet                     5.5.10-4ubuntu3  all          configuration management system
un  puppet-agent               <none>           <none>       (no description available)
un  puppet-common              <none>           <none>       (no description available)
un  puppetmaster-common        <none>           <none>       (no description available)
ii  ruby                       1:2.7+1          amd64        Interpreter of object-oriented scripting language Ruby (default version)
un  ruby-activesupport-2.3     <none>           <none>       (no description available)
un  ruby-activesupport-3.2     <none>           <none>       (no description available)
ii  ruby-augeas                1:0.5.0-3build7  amd64        Augeas bindings for the Ruby language
un  ruby-benchmark             <none>           <none>       (no description available)
un  ruby-bigdecimal            <none>           <none>       (no description available)
un  ruby-bootsnap              <none>           <none>       (no description available)
un  ruby-cgi                   <none>           <none>       (no description available)
un  ruby-csv                   <none>           <none>       (no description available)
un  ruby-date                  <none>           <none>       (no description available)
un  ruby-dbm                   <none>           <none>       (no description available)
un  ruby-debian                <none>           <none>       (no description available)
ii  ruby-deep-merge            1.1.1-1          all          recursively merge Hash elements in Ruby
un  ruby-delegate              <none>           <none>       (no description available)
un  ruby-dev                   <none>           <none>       (no description available)
un  ruby-did-you-mean          <none>           <none>       (no description available)
un  ruby-etc                   <none>           <none>       (no description available)
un  ruby-fcntl                 <none>           <none>       (no description available)
un  ruby-fiddle                <none>           <none>       (no description available)
un  ruby-fileutils             <none>           <none>       (no description available)
un  ruby-forwardable           <none>           <none>       (no description available)
un  ruby-gdbm                  <none>           <none>       (no description available)
un  ruby-getoptlong            <none>           <none>       (no description available)
un  ruby-gettext-setup         <none>           <none>       (no description available)
un  ruby-gobject-introspection <none>           <none>       (no description available)
un  ruby-hocon                 <none>           <none>       (no description available)
un  ruby-interpreter           <none>           <none>       (no description available)
un  ruby-io-console            <none>           <none>       (no description available)
un  ruby-ipaddr                <none>           <none>       (no description available)
un  ruby-irb                   <none>           <none>       (no description available)
un  ruby-json                  <none>           <none>       (no description available)
un  ruby-logger                <none>           <none>       (no description available)
un  ruby-matrix                <none>           <none>       (no description available)
ii  ruby-minitest              5.13.0-1         all          Ruby test tools supporting TDD, BDD, mocking, and benchmarking
un  ruby-mutex-m               <none>           <none>       (no description available)
un  ruby-net-pop               <none>           <none>       (no description available)
un  ruby-net-smtp              <none>           <none>       (no description available)
ii  ruby-net-telnet            0.1.1-2          all          telnet client library
un  ruby-observer              <none>           <none>       (no description available)
un  ruby-open3                 <none>           <none>       (no description available)
un  ruby-openssl               <none>           <none>       (no description available)
un  ruby-ostruct               <none>           <none>       (no description available)
ii  ruby-power-assert          1.1.7-1          all          library showing values of variables and method calls in an expression
un  ruby-prime                 <none>           <none>       (no description available)
un  ruby-pstore                <none>           <none>       (no description available)
un  ruby-psych                 <none>           <none>       (no description available)
un  ruby-racc                  <none>           <none>       (no description available)
un  ruby-rdoc                  <none>           <none>       (no description available)
un  ruby-readline              <none>           <none>       (no description available)
un  ruby-readline-ext          <none>           <none>       (no description available)
un  ruby-reline                <none>           <none>       (no description available)
un  ruby-rexml                 <none>           <none>       (no description available)
un  ruby-rrd                   <none>           <none>       (no description available)
un  ruby-rss                   <none>           <none>       (no description available)
un  ruby-sdbm                  <none>           <none>       (no description available)
ii  ruby-selinux:amd64         3.0-1build2      amd64        Ruby bindings to SELinux shared libraries
ii  ruby-shadow                2.5.0-1build2    amd64        interface of shadow password for Ruby
un  ruby-singleton             <none>           <none>       (no description available)
un  ruby-stringio              <none>           <none>       (no description available)
un  ruby-strscan               <none>           <none>       (no description available)
un  ruby-switch                <none>           <none>       (no description available)
ii  ruby-sync                  0.5.0-1          all          two-phase lock with a counter
ii  ruby-test-unit             3.3.5-1          all          unit testing framework for Ruby
un  ruby-timeout               <none>           <none>       (no description available)
un  ruby-tracer                <none>           <none>       (no description available)
un  ruby-uri                   <none>           <none>       (no description available)
un  ruby-webrick               <none>           <none>       (no description available)
ii  ruby-xmlrpc                0.3.0-2          all          XMLRPC library for Ruby
un  ruby-yaml                  <none>           <none>       (no description available)
un  ruby-zlib                  <none>           <none>       (no description available)
ii  ruby2.7                    2.7.0-5ubuntu1.4 amd64        Interpreter of object-oriented scripting language Ruby
un  rubygems                   <none>           <none>       (no description available)
ii  rubygems-integration       1.16             all          integration of Debian Ruby packages with Rubygems
/usr/bin/ruby
/usr/bin/puppet
#!/usr/bin/ruby
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
-e:1: warning: URI.escape is obsolete
/a%20p%20a
$ puppet --version
/usr/lib/ruby/vendor_ruby/puppet/util.rb:461: warning: URI.escape is obsolete
5.5.10
```

**Comment by simmel** [comment] 2021-05-05 10:55
> @simmel what version of puppet do you have on your local machine?
> Your example `ruby -ruri -e 'puts URI.escape("/a p a")'` proves that Ruby works correctly on images and something goes wrong with puppet

It does not. That was using the Ruby version `setup-ruby` provides.

See https://github.com/simmel/actions-virtual-environments-issues-3310/runs/2508560076 which tests `setup-ruby`-Ruby and system-Ruby. System-Ruby fails.

**Comment by miketimofeev** [comment] 2021-05-05 11:26
@simmel @maxim-lobanov  I've taken clean Azure ubuntu 20 image and run:
```
sudo apt-get update
sudo apt-get install ruby-full
sudo apt-get install puppet
puppet --version
```
and it seems ruby works fine there, so the issue is in the image. I'll try to dig deeper
```
testadm2@ub20ruby:~$ puppet --version
/usr/lib/ruby/vendor_ruby/puppet/util.rb:461: warning: URI.escape is obsolete
5.5.10
```

**Comment by miketimofeev** [comment] 2021-05-05 11:38
Looks like the root cause in `gem update` — puppet started giving the same error after I updated the gems on the clean VM with ruby.

**Comment by simmel** [comment] 2021-05-05 11:42
Confirmed @miketimofeev 

```terminal
root@de5e6e74c833:/# puppet --version
/usr/lib/ruby/vendor_ruby/puppet/util.rb:461: warning: URI.escape is obsolete
5.5.10
root@de5e6e74c833:/# gem update uri
Updating installed gems
Updating uri
Fetching uri-0.10.1.gem
Successfully installed uri-0.10.1
Parsing documentation for uri-0.10.1
Installing ri documentation for uri-0.10.1
Installing darkfish documentation for uri-0.10.1
Done installing documentation for uri after 1 seconds
Parsing documentation for uri-0.10.1
Done installing documentation for uri after 0 seconds
Gems updated: uri
root@de5e6e74c833:/# puppet --version
Traceback (most recent call last):
        19: from /usr/bin/puppet:4:in `<main>'
        18: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        17: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        16: from /usr/lib/ruby/vendor_ruby/puppet/util/command_line.rb:12:in `<top (required)>'
        15: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        14: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        13: from /usr/lib/ruby/vendor_ruby/puppet.rb:299:in `<top (required)>'
        12: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        11: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        10: from /usr/lib/ruby/vendor_ruby/puppet/parser.rb:6:in `<top (required)>'
         9: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
         8: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
         7: from /usr/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:8:in `<top (required)>'
         6: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
         5: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
         4: from /usr/lib/ruby/vendor_ruby/puppet/pops.rb:1:in `<top (required)>'
         3: from /usr/lib/ruby/vendor_ruby/puppet/pops.rb:119:in `<module:Puppet>'
         2: from /usr/lib/ruby/vendor_ruby/puppet/pops/model/ast.rb:4863:in `register_pcore_types'
         1: from /usr/lib/ruby/vendor_ruby/puppet/util.rb:337:in `path_to_uri'
/usr/lib/ruby/vendor_ruby/puppet/util.rb:461:in `uri_encode': undefined method `escape' for URI:Module (NoMethodError)
root@de5e6e74c833:/#
```

**Comment by simmel** [comment] 2021-05-05 11:49
```
Run sudo apt-get update >/dev/null && sudo apt-get install -y puppet >/dev/null && /usr/bin/gem list uri && /usr/bin/ruby -ruri -e 'puts URI.escape("/a p a")'
security (0.1.3)
uri (0.10.1, default: 0.10.0)
-e:1:in `<main>': undefined method `escape' for URI:Module (NoMethodError)
Error: Process completed with exit code 1.
```
Interesting, 0.10.1 (which is the "broken" one) is installed but not the default. Not sure what "default" means in rubygems though.

**Comment by miketimofeev** [comment] 2021-05-05 11:57
@simmel neither me. However, this workaround solves the issue `sudo gem uninstall uri -v 0.10.1`

**Comment by simmel** [comment] 2021-05-05 12:11
https://github.com/actions/virtual-environments/pull/2751/files#diff-cd3a602dc8e0d7432bae1f80a68dd14d6397606db6474777a1b78f4129f8b345L9-R10

This switch from `gem update --system` which upgrades rubygems to `gem update` which updates *all* gems, including the ones installed by Ubuntu since all gems are installed by the ruby packages.

```terminal
root@de5e6e74c833:/# gem which uri
/usr/lib/ruby/2.7.0/uri.rb
root@de5e6e74c833:/# dpkg -S /usr/lib/ruby/2.7.0/uri.rb
libruby2.7:amd64: /usr/lib/ruby/2.7.0/uri.rb
root@de5e6e74c833:/#
```

**Comment by miketimofeev** [comment] 2021-05-05 12:21
@simmel probably it was not the best idea of mine 😅 I suppose we don't have to update either RubyGems or all the gems.

**Comment by simmel** [comment] 2021-05-05 12:31
In the Python sphere I know there has been issues, the cryptography "scadal" ; P, where if you didn't have a pip version new enough you couldn't install a newer version of the python package cryptography. Things like this are avoided when keeping the tooling upgraded. Then again, setuptools made a new version which broke everything and everyone expected setuptools to always work so noone specified a version for it = D

I think `gem update --system` is fine, but you're the maintainers it's your call.

**Comment by miketimofeev** [comment] 2021-05-06 09:26
@simmel updating RubyGems installed from the apt package is a bad idea, Debian distros don't allow it at all, for instance. We decided to skip gems update as well to avoid issues like this.
The new image with the default gems will be deployed next week.

**Comment by miketimofeev** [comment] 2021-05-13 13:45
@simmel we've deployed new images. I tested the puppet installation and it works fine now.
I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!

**Closed by miketimofeev** 2021-05-13 13:45 UTC
Labels: Area: Ruby, OS: Ubuntu, awaiting-deployment, bug
