### ISSUE TITLE
Missing Powershell on Ubuntu 20.04

### ISSUE THREAD

**Issue by Quatra** [actions/virtual-environments#2101] opened 2020-11-20 14:19 UTC
Hello,

Yesterday, November 19th, we're getting issues with the Azure CLI task that fails to run because the Linux Ubuntu 20.04 is unable to locate the powershell. Below, you'll see the error that we got when running the task. We've tried using Ubuntu 18.04 and we have the same issue. The Azure CLI task version is 2.*. 

2020-11-19T13:16:22.5951803Z ##[error]Script failed with error: Error: Unable to locate executable file: 'powershell'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.

Any ideas how to fix this? Was there something removed in those images that shouldn't?

**Comment by dibir-magomedsaygitov** [comment] 2020-11-20 14:46
Hello, @Quatra. Thank you for your report. Could you please provide repro steps to help us to investigate this issue?

**Comment by Josverl** [comment] 2020-11-20 15:18
@Quatra powerhell on linux is powershell 7 
Powershell 7 uses the `pwsh` executable to start the shell on all platforms

**Comment by maxim-lobanov** [comment] 2020-11-20 15:38
@Quatra , please make sure that you selected `Script Type` as `PowerShell Core`
![Screen Shot 2020-11-20 at 6 20 07 PM](https://user-images.githubusercontent.com/16715858/99818284-15a5b180-2b5f-11eb-8453-62a0bc8bafad.png).

I can reproduce your issue if select `PowerShell` but I guess it is expected behavior because `powershell` executable means `PowerShell Native` on Windows. On lInux, there is only PowerShell Core and it has `pwsh` executable

**Comment by Quatra** [comment] 2020-11-23 15:25
Hello,

It was working fine two weeks ago but it broke on November 20th. Today, I've changed the task to use Powershell Core and I was able to run the script without issue. It is a shame that the support of Powershell is no longer available or is broken.

Thank you for the replies.

**Comment by maxim-lobanov** [comment] 2020-11-23 16:22
@Quatra , could you please make sure that you have saved pipeline with `Powershell Core` and attach log for failed step?
In your previous message, I don't see any error.

**Comment by Quatra** [comment] 2020-12-03 14:07
Hello,

Here's the complete log from November 19

> 2020-11-19T13:16:22.4444369Z ##[section]Starting: Cleanup azure tables
> 2020-11-19T13:16:22.4453655Z ==============================================================================
> 2020-11-19T13:16:22.4454084Z Task         : Azure CLI
> 2020-11-19T13:16:22.4454718Z Description  : Run Azure CLI commands against an Azure subscription in a PowerShell Core/Shell script when running on Linux agent or PowerShell/Powershell Core/Batch script when running on Windows agent.
> 2020-11-19T13:16:22.4455331Z Version      : 2.0.16
> 2020-11-19T13:16:22.4455669Z Author       : Microsoft Corporation
> 2020-11-19T13:16:22.4456132Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-cli
> 2020-11-19T13:16:22.4456645Z ==============================================================================
> 2020-11-19T13:16:22.5951803Z ##[error]Script failed with error: Error: Unable to locate executable file: 'powershell'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
> 2020-11-19T13:16:22.5965200Z ##[section]Finishing: Cleanup azure tables

We've used Powershell Core for that run as well. It doesn't show up in the logs though.

**Comment by maxim-lobanov** [comment] 2020-12-03 14:22
@Quatra could you please share your YAML file or screen of UI configuration?

Based on your error message, it looks like `PowerShell` is selected instead of `PowerShell Core`.
Based on task source code: https://github.com/microsoft/azure-pipelines-tasks/blob/485073dd547a7783aecaf63c3f65990d4568b32b/Tasks/AzureCLIV2/src/ScriptType.ts#L51
`powershell` executable is used only if you specify `PowerShell`. If you choose `PowerShell Core`, executable will be `pwsh`

**Comment by Quatra** [comment] 2020-12-03 18:29
Hello,
I'll try to reproduce the issue again. The previous release that failed was deleted and I've created a new stage with Powershell Core and it seems to have no issue. I'll keep an eye on it. From what I remembered, it was working a few times, but then failed with the same error message.

**Comment by maxim-lobanov** [comment] 2020-12-08 06:55
I am going to close the issue for now since there is no issue from images side. As I mentioned above, It is expected behavior that `powershell` binary is not available on Ubuntu images. Since it is PowerShell Core, binary name is `pwsh`.

If you still experience this issue, I suggest to report it to https://github.com/microsoft/azure-pipelines-tasks since they own AzureCLI task and can help to diagnose if there is an issue from task side. On a quick look, task should use `powershell` binary only if `PowerShell` is chosen in dropdown so I suggest to double check that you have chosen `PowerShell Core` instead of `PowerShell`

**Closed by maxim-lobanov** 2020-12-08 06:55 UTC
Labels: Area: Scripting and command line, OS: Ubuntu, investigate
