### ISSUE TITLE
GeckoDriver not added to the PATH on Windows

### ISSUE THREAD

**Issue by mkht** [actions/virtual-environments#448] opened 2020-02-23 05:01 UTC
**Describe the bug**
Even though Chrome and Edge WebDrivers are added to the PATH, only Firefox GeckoDriver is not added. This is inconsistent behavior.

**Area for Triage**: 

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Expected behavior**
Add the GeckoDriver installation directory (`C:\SeleniumWebDrivers\GeckoDriver`) to the PATH environment variable.

**Actual behavior**
Only Chrome and Edge WebDrivers are added to the PATH
```
// This is a listing of the current WS2019 VM PATH environment variable.
C:/hostedtoolcache/windows\Python\3.6.8\x64
C:/hostedtoolcache/windows\Python\3.6.8\x64\Scripts
C:\Program Files\Mercurial\
C:\ProgramData\kind
C:\vcpkg
C:\cf-cli
C:\Program Files(x86)\NSIS\
C:\Program Files\Mercurial\
C:\hostedtoolcache\windows\Boost\1.72.0
C:\ProgramFiles\dotnet
C:\mysql-5.7.21-winx64\bin
C:\ProgramFiles\Java\zulu-8-azure-jdk_8.40.0.25-8.0.222-win_x64\bin
C:\Program Files (x86)\sbt\bin
C:\Rust\.cargo\bin
C:\hostedtoolcache\windows\Ruby\2.5.7\x64\bin
C:\Go1.12.7\bin
C:\Program Files\Git\bin
C:\hostedtoolcache\windows\Python\3.7.6\x64\Scripts
C:\hostedtoolcache\windows\Python\3.7.6\x64
C:\npm\prefix
C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin
C:\windows\system32
C:\windows
C:\windows\System32\Wbem
C:\windows\System32\WindowsPowerShell\v1.0\
C:\windows\System32\OpenSSH\
C:\ProgramData\Chocolatey\bin
C:\Program Files\Docker
C:\ProgramFiles\PowerShell\6\
C:\Program Files (x86)\Windows Kits\10\Windows PerformanceToolkit\
C:\Program Files\dotnet\
C:\Program Files\Microsoft SQLServer\130\Tools\Binn\
C:\Program Files\Microsoft SQL Server\ClientSDK\ODBC\170\Tools\Binn\
C:\Program Files\Microsoft ServiceFabric\bin\Fabric\Fabric.Code
C:\Program Files\Microsoft SDKs\ServiceFabric\Tools\ServiceFabricLocalClusterManager
C:\Program Files\nodejs\
C:\ProgramFiles\Git\cmd
C:\Program Files\Git\mingw64\bin
C:\ProgramFiles\Git\usr\bin
c:\tools\php
C:\Program Files (x86)\sbt\bin
C:\Program Files (x86)\Subversion\bin
C:\SeleniumWebDrivers\ChromeDriver\
C:\SeleniumWebDrivers\EdgeDriver\
C:\ProgramData\chocolatey\lib\maven\apache-maven-3.6.2\bin
C:\Program Files\CMake\bin
C:\Strawberry\c\bin
C:\Strawberry\perl\site\bin
C:\Strawberry\perl\bin
C:\ProgramFiles\OpenSSL\bin
C:\Users\runneradmin\.dotnet\tools
C
```

**Comment by maxim-lobanov** [comment] 2020-02-23 06:03
Hi @mkht ,

Environment variable for GeckoDriver was added in scope of #349 . Those changes are still delivering and we are expecting that they will be deployed next week.

I am going to close this issue for now because it is duplicate of #349 but feel free to reopen if any

**Closed by maxim-lobanov** 2020-02-23 06:03 UTC
Labels: Area: Deployment/Release, Area: Packages, needs triage
