### ISSUE TITLE
Windows-2019 20220131.1 seems to have broken setup-python

### ISSUE THREAD

**Issue by jku** [actions/virtual-environments#5009] opened 2022-02-03 15:50 UTC
### Description

All our windows runs started failing in setup-python just as windows-latest image updated from 20220123.1 to 20220131.1. 

setup-python@v2 did not change at that point, our workflows have not changed. This is the relevant workflow part:
```
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: 'requirements*.txt'
```

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

failing build with windows-2019 20220131.1: https://github.com/theupdateframework/python-tuf/runs/5049622576

### Is it regression?

successful build with windows-2019 20220123.1 : https://github.com/theupdateframework/python-tuf/runs/5049069425

### Expected behavior

No errors during setup-python

### Actual behavior

Error: The process 'C:\hostedtoolcache\windows\Python\3.10.1\x64\Scripts\pip.exe' failed with exit code 322122547

### Repro steps

1. Use setup-python in a workflow on windows

sorry, I really don't know what else to put here, although the fact that the failure happens at `pip.exe cache dir` implies repro may require using setup-pythons "cache" feature (example above).

**Comment by dibir-magomedsaygitov** [comment] 2022-02-03 17:21
Hello @jku. Thank you for your report. We will take a look.

**Comment by jku** [comment] 2022-02-04 07:33
> the fact that the failure happens at pip.exe cache dir implies repro may require using setup-pythons "cache" feature (example above).

Confirming this: disabling the pip cache feature in setup-python makes it succeed:

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          # cache: 'pip'
          # cache-dependency-path: 'requirements*.txt'

**Comment by dmitry-shibanov** [comment] 2022-02-04 11:04
Hello @jku. Thank you for your report. The issue is related to the [issue](https://github.com/actions/setup-python/issues/328) in the setup-python action.
For now I'm going to close the issue as a duplicate. If you have any question feel free to ping us.

**Closed by dmitry-shibanov** 2022-02-04 11:04 UTC
Labels: Area: Python, OS: Windows, investigate, bug report
