### ISSUE TITLE
Docker push  no longer working in Ubuntu / 20210208.0

### ISSUE THREAD

**Issue by Chili-Man** [actions/virtual-environments#2691] opened 2021-02-11 20:07 UTC
**Description**  
I'm not longer able to do `docker push` to GHCR as of today. Builds that were on the previous virtual environment version of  `20210131.1` were working dandy and we have not made any changes to the docker build/push workflow in over a few months.   

After some experimenting, it appears that downgrading the `moby-cli` package to `19.03.14+azure` fixes the issue that we're seeing. So something in moby-cli version `19.03.15+azure` appears to be breaking `docker push` . 

**Area for Triage**:  
Containers

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
Environment: ubuntu-20.04
Version: 20210208.0

**Expected behavior**  
I expect `docker push` to be able to publish images to GHCR

**Actual behavior**  
```console
Run docker push ghcr.io/foobar/example
  docker push ghcr.io/foobar/example
  shell: /usr/bin/bash -e {0}
Using default tag: latest
The push refers to repository [ghcr.io/foobar/example]
tag does not exist: ghcr.io/foobar/example:latest
Error: Process completed with exit code 1.
```

I'm not sure why it complains that the latest tag for that image does not exist when it clearly does

**Repro steps**  
Any build with `docker buildx --tag some-tag` and then `docker push ghcr.io/foobar/example` should trigger the issue. I can provide the workflow action we're using if requested.

**Comment by IgooorGP** [comment] 2021-02-12 01:38
Hi, @Chili-Man ! My answer here does not really answer your question, but might solve some possible CICD problems that you are facing in production with a quick workaround, so... sorry if this is not what you're looking for!

Here at work we have been experiencing the same issue in our CICD pipelines. Moreover, it seems that it's the same "Azure-based" docker cli version, `19.03.15+azure`, that is causing the problem.

For what we've been seeing, all the times that our pipes failed they had the same stdout message:

```text
Using default tag: latest
```

Which is expected for docker cli in versions [20.10.2](https://github.com/docker/cli/blob/v20.10.2/cli/command/image/push.go#L59) and above, such as [20.10.3](https://github.com/docker/cli/blob/v20.10.3/cli/command/image/push.go#L59), due to the new `-a/--all-tags` flag addition to the client which can be seen in this PR [here](https://github.com/docker/cli/pull/2220/files#diff-f6f762242d9c434bd04b843b61984e2c9cf4a5b9a4086dff2390c3c7b7edbb22R54-R59), I believe.

It seems that `docker push` without the new `--all-tags` flag seems now to look for the default tag, which is `latest`, and if such tag does not exist locally, it will break with a message similar to what you have been experiencing (notice the "latest" in the end):

```text
tag does not exist: ghcr.io/foobar/example:latest  <--- latest (default)
```

Hence, in order to solve the problem, either add the `--all-tags` param with the `docker push` command (doc [here](https://docs.docker.com/engine/reference/commandline/push/#options)) which will push all the tags of your image to the registry or use specific tag name with `docker push` and the docker cli will not look for the default `latest` tag I guess. If you are sure that you are creating an image with the `latest` tag, like  `ghcr.io/foobar/example:latest`, then try running some `docker image ls` on the CICD just to make sure it's really there. Again, this does not solve your problem, but might ease some production troubles.

Moreover, we also ended up using some CICD tasks that fixes docker's cli version in order to make sure that we do not end up using `19.03.15+azure` version anymore. 

Funny thing is that docker's cli version [19.03.15](https://github.com/docker/cli/blob/v19.03.15/cli/command/image/push.go#L42-L69) should not behave like this I believe as the `--all-tags` flag was released on 20.x.x version only.

Hope this helps a bit.

**Comment by Chili-Man** [comment] 2021-02-12 01:47
@IgooorGP ahhh, yeah that doesn't make any sense that we'd have to put the --all-tags flag if its only for CLIs >= 20.10.2 ; But thanks for the tip, much appreciated. I'm going to give that a shot.

**Comment by Chili-Man** [comment] 2021-02-12 04:40
@IgooorGP I have confirmed that your suggested fix of adding the `--all-tags` flags fixes the issue! thanks again for the help!

**Comment by dibir-magomedsaygitov** [comment] 2021-02-12 06:03
Hello @Chili-Man . Thank for your report. I'm going to close this issue as duplicate of [#2686](https://github.com/actions/virtual-environments/issues/2686). Any further discussions will be under [that ](https://github.com/actions/virtual-environments/issues/2686)issue.

**Closed by dibir-magomedsaygitov** 2021-02-12 06:03 UTC
Labels: Area: Deployment/Release, Area: Scripting and command line, needs triage
