### ISSUE TITLE
Xcode and UITests — Failed: Timed out while synthesizing event

### ISSUE THREAD

**Issue by godbout** [actions/virtual-environments#3395] opened 2021-05-15 16:02 UTC
**Description**  
synthesizing events takes too long (more than 30 seconds) which makes UITests fail. (some events are synthesized right away, but for a some tests—random, not the same—it will timeout.)

**Area for Triage**:  
Apple

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
Version: 20210510.1

**Expected behavior**  
synthesizing events should run smoothly and not timeout.

**Actual behavior**  

here's a part of the log:
```
2021-05-15 12:49:30.838966+0000 XUITests-Runner[1454:15770] [Arbitration] starting DTServiceHub child handshake.0 (send: 0x581b, receive: 0xa813)
500
2021-05-15 12:49:30.841757+0000 XUITests-Runner[1454:15523] [Arbitration] attempting connection to singleton: 1391 with send port: 0xa707
501
2021-05-15 12:49:30.843821+0000 XUITests-Runner[1454:15523] [Arbitration] handshake SUCCESSFUL (child: 1460 -> singleton: 1391)
502
    t =     0.40s Open mo.com.sleeplessmind.X
503
    t =     0.45s     Launch mo.com.sleeplessmind.X
504
    t =     0.87s         Wait for accessibility to load
505
    t =     0.96s         Setting up automation session
506
    t =     1.06s         Wait for mo.com.sleeplessmind.X to idle
507
    t =     1.10s Tap TextField
508
    t =     1.10s     Wait for mo.com.sleeplessmind.X to idle
509
    t =     1.13s     Find the TextField
510
    t =     1.16s     Synthesize event
511
    t =    36.59s         Failed: Timed out while synthesizing event.
```

after 35 seconds of wait, the UITest fail. rerunning the jobs may get this test to pass, but another one to fail (that would pass in the previous run).

**Repro steps**  

1. have a couple of UITests that use `tap` and `typeText` 
2. run the ci

**Comment by Darleev** [comment] 2021-05-17 08:06
Hello @godbout,
Could you please provide some sample repo with minimal steps to reproduce the issue?
In the meantime, we will investigate the issue from our side.
We look forward to hearing from you

**Comment by godbout** [comment] 2021-05-17 16:52
hey @Darleev thanks. i'll do a public repo and come back with the URL. hopefully should just take a couple of days. thanks again.

**Comment by dibir-magomedsaygitov** [comment] 2021-05-20 06:42
Hello @godbout. Any updates on repro-steps? We look forward to hearing from you.

**Comment by godbout** [comment] 2021-05-20 18:35
i'll do something over the weekend. sorry for the late!

**Comment by godbout** [comment] 2021-05-23 12:54
ok so i made a public repo here: https://github.com/godbout/gha-uitests-synthetize

of course, i can't reproduce the issue 😅️
my private repo fails. the only difference i see is that it seems the Accessibility dialog shows up (as seen below), which might make sense as my UI Tests are using Accessibility, but strangely it doesn't appear in the public repo where i grab and set AX elements.

```
   t =     0.85s Tap TextField
1767
    t =     0.85s     Wait for X to idle
1768
    t =     0.89s     Find the TextField
1769
    t =     0.99s     Found 1 interrupting element:
1770
    t =     0.99s         Window at {{357.0, 183.0}, {461.0, 171.0}} from Application 'com.apple.accessibility.universalAccessAuthWarn'
1771
    t =     0.99s     Invoking UI interruption monitors for Window at {{357.0, 183.0}, {461.0, 171.0}} from Application 'com.apple.accessibility.universalAccessAuthWarn'
1772
    t =     0.99s         Checking for user permission dialogs...
1773
    t =     0.99s             Checking existence of `StaticText`
1774
    t =     1.14s         Checking for Bluetooth Setup Assistant...
1775
    t =     1.14s             Find the Window at {{357.0, 183.0}, {461.0, 171.0}}
1776
    t =     1.25s         No monitors handled UI interruption, checking to see if element still exists...
1777
    t =     1.26s             Checking existence of `"Accessibility Access" Window`
1778
    t =     1.33s     Did not handle the interruption, but will attempt to continue…
1779
    t =     1.33s     Open mo.com.sleeplessmind.X
1780
    t =     1.37s         Activate mo.com.sleeplessmind.X
1781
    t =     1.37s             Wait for mo.com.sleeplessmind.X to idle
1782
    t =     1.41s     Synthesize event
1783
    t =     2.01s     Wait for mo.com.sleeplessmind.X to idle
1784
    t =     2.07s Type 'some text we will ...' into TextField
```

anyways, i will dig deeper later. you can close the issue if you want, i will reopen if i can come up with something new. thanks!

**Comment by godbout** [comment] 2021-05-23 14:24
ok so i cleaned all i could from the failing repo and made a branch on the public repo. you can see the failure here: https://github.com/godbout/gha-uitests-synthetize/runs/2650248304?check_suite_focus=true

let me know what other info i can give you. thanks!

**Comment by godbout** [comment] 2021-05-23 20:30
ok so i've spent quite some time and i found it. the issue happens when the `Application is agent (UIElement)` setting is set in the `Info.plist`. in my case my app lives in the status bar, but i create a window to run UI Tests. they work fine on my development machines. any chance to make that work in GHA?

**Comment by orj** [comment] 2021-06-10 07:49
@godbout this is often to do with Keyboards.  You can get similar issues locally if you have the Simulator set up to have a hardware keyboard.  There are `defaults` scripts that can ensure that the simulator does not think it has a hardware keyboard.

See https://stackoverflow.com/questions/55845373/disable-ios-simulator-connect-hardware-keyboard-programmatically

**Comment by nikita-bykov** [comment] 2021-06-16 14:40
Hello @godbout. We apologize for such a late reply.
We investigated this issue and looks like it reproduces only when flag `Application is agent (UIElement)` is enabled. Could you please try to disable it to check if it helps?
We are still not sure why this flag causes issues but looks like everything works fine without it.

**Comment by godbout** [comment] 2021-06-16 18:14
hey @nikita-bykov no worries. thanks for taking the time to check into this issue. well, good that you're confirming there's an issue with that setting. on my side, the app needs to be a UIElement (doesn't work if not) and the setting is set in the `Info.plist`. changing the `Info.plist` at runtime is a big no no, so i guess the next step for me is to see if i can switch this programmatically in another way. on your side will you guys still investigate or you're dropping the issue? thanks.

**Comment by dmitry-shibanov** [comment] 2021-06-17 10:28
Hello @godbout. Thank you for your response. Unfortunately we can’t continue further investigation, because it looks like very specific issue. We tested it in various cases and can suppose that the possible root cause of the issue, that the application loses focus when you run it with this `LSUIElement` flag set to true. We’re closing issue for now, but if you get any ideas or suggestions about the root cause of the issue, could you please ping us in the thread ?

**Closed by dmitry-shibanov** 2021-06-17 10:28 UTC
Labels: Area: Testing and code coverage, OS: macOS, investigate

**Comment by godbout** [comment] 2021-06-17 15:21
hi @dmitry-shibanov. alright. strange though that it does work locally, so losing the focus shouldn't be the issue. actually even as an UIElement, the window that is created for the UI Tests is put in the foreground. anyways, if i find a way i'll post it here. thanks!

**Comment by godbout** [comment] 2021-06-17 17:29
ok so i was able to make the public repo i made to show this issue (https://github.com/godbout/gha-uitests-synthetize) pass by setting the `activationPolicy` at to `.regular`: https://developer.apple.com/documentation/appkit/nsapplication/1428621-setactivationpolicy#

unfortunately, this doesn't work with the private app i'm building. actually even making the app not a UIElement doesn't work. i keep having a `...has not loaded accessibility` error message. as i'm burning through my paid ci minutes, i'm gonna give up on this. thanks for the time.
