### ISSUE TITLE
windows-latest (20211122.1) Has not latest dotnet 5 version 12

### ISSUE THREAD

**Issue by patspaeth** [actions/virtual-environments#4600] opened 2021-11-26 10:28 UTC
### Description

We are using the vm windows-latest in our Azure DevOps pipelines and have currently an issue with the dotnet runtime installed on the vm.
We run a dotnet tool that requires dotnet 5.0.12 runtime
but we get an error that this is not installed, but dotnet 5.0.11 is installed.

Expecting from the readme for windows-latest (20211122.1), I would expect that the dotnet runtime of 5.0.12 is installed!
reference: https://github.com/actions/virtual-environments/blob/win19/20211122.1/images/win/Windows2019-Readme.md

Here is the initializing log of our pipeline:
```
Starting: Initialize job
Agent name: 'Azure Pipelines 5'
Agent machine name: 'WIN-1NESLPMR11N'
Current agent version: '2.195.0'
Operating System
Microsoft Windows Server 2019
10.0.17763
Datacenter
Virtual Environment
Environment: windows-2019
Version: 20211122.1
Included Software: https://github.com/actions/virtual-environments/blob/win19/20211122.1/images/win/Windows2019-Readme.md
Image Release: https://github.com/actions/virtual-environments/releases/tag/win19%2F20211122.1
Virtual Environment Provisioner
1.0.0.0-master-20211123-1
Current image version: '20211122.1'
Agent running as: 'VssAdministrator'
Prepare build directory.
Set build variables.
Download all required tasks.
Downloading task: UseDotNet (2.195.0)
Downloading task: CredScan (2.332.0)
Downloading task: PublishSecurityAnalysisLogs (2.316.0)
Downloading task: SdtReport (1.232.0)
Downloading task: PublishBuildArtifacts (1.192.0)
Downloading task: AzureKeyVault (1.182.1)
Downloading task: PowerShell (2.194.0)
Downloading task: CopyFiles (2.190.1)
Downloading task: NuGetAuthenticate (0.194.0)
Downloading task: npmAuthenticate (0.179.0)
Downloading task: CmdLine (2.182.0)
Checking job knob settings.
   Knob: AgentToolsDirectory = C:\hostedtoolcache\windows Source: ${AGENT_TOOLSDIRECTORY} 
   Knob: AgentPerflog = C:\agents\perflog Source: ${VSTS_AGENT_PERFLOG} 
Finished checking job knob settings.
Start tracking orphan processes.
Finishing: Initialize job
```

And here the error message:
```
Starting: Execute Bomfilter
==============================================================================
Task         : PowerShell
Description  : Run a PowerShell script on Linux, macOS, or Windows
Version      : 2.194.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
==============================================================================
Generating script.
========================== Starting Command Output ===========================
"C:\Program Files\PowerShell\7\pwsh.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\ad41a16f-5652-497f-aac3-debe6b5c7b2a.ps1'"
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.12' was not found.
  - The following frameworks were found:
      5.0.11 at [C:\hostedtoolcache\windows\dotnet\shared\Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.12&arch=x64&rid=win10-x64
##[error]PowerShell exited with code '1'.
Finishing: Execute Bomfilter

```

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20211122.1

### Expected behavior

 dotnet runtime 5.0.12 is installed

### Actual behavior

 dotnet runtime 5.0.11 is installed (not 5.0.12)

### Repro steps

Use a dotnet tool that needs dotnet runtime 5.0.12
let it run on the windwos-latest (20211122.1)
Error message will occur:
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.12' was not found.
  - The following frameworks were found:
      5.0.11 at [C:\hostedtoolcache\windows\dotnet\shared\Microsoft.NETCore.App]

**Comment by dibir-magomedsaygitov** [comment] 2021-11-26 11:08
Hello @patspaeth. Thank you for your report. We will take a look.

**Comment by patspaeth** [comment] 2021-11-26 11:15
I want to give some more information:
We use also a Use dotnet taks:
Starting: Use global dotnet sdk
```
==============================================================================
Task         : Use .NET Core
Description  : Acquires a specific version of the .NET Core SDK from the internet or the local cache and adds it to the PATH. Use this task to change the version of .NET Core used in subsequent tasks. Additionally provides proxy support.
Version      : 2.195.0
Author       : Microsoft Corporation
Help         : https://aka.ms/AA4xgy0
==============================================================================
Found version 5.0.402 in channel 5.0 for user specified version spec: 5.0.402
Getting URL to download .NET Core sdk version: 5.0.402.
Detecting OS platform to find correct download package for the OS.
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "& 'D:\a\_tasks\UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6\2.195.0\externals\get-os-platform.ps1'"
Primary:win-x64
Detected platform (Primary): win-x64
Version 5.0.402 was not found in cache.
Downloading: https://download.visualstudio.microsoft.com/download/pr/c826dbd3-e72f-46f7-a60a-8edde0e086de/aced282e985e941bfdd222781c722fe2/dotnet-sdk-5.0.402-win-x64.zip
Extracting downloaded package D:\a\_temp\e487332a-136e-4e86-b310-ec23ab471d51.
Extracting archive
C:\Windows\system32\chcp.com 65001
Active code page: 65001
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('D:\a\_temp\e487332a-136e-4e86-b310-ec23ab471d51', 'D:\a\_temp\bc4e')"
Successfully installed .NET Core sdk version 5.0.402.
Creating global tool path and pre-pending to PATH.
Finishing: Use global dotnet sdk

```

**Comment by V-Zabayrachny** [comment] 2021-11-30 07:57
Hello @patspaeth. We were unable to reproduce your problem, could you please provide a minimal example in a public repo so we could reproduce the issue on our side?

**Comment by V-Zabayrachny** [comment] 2021-12-03 11:23
@patspaeth I'm going to close the issue since we cannot proceed with our investigation due to the lack of repro steps.
Please feel free to contact us if you have any concerns.
Thank you!

**Closed by V-Zabayrachny** 2021-12-03 11:23 UTC
Labels: Area: .NET Core, OS: Windows, investigate
