### ISSUE TITLE
Issue with some i386 packages on UB 20.04 Image now causing impossible dependency problems

### ISSUE THREAD

**Issue by ensiform** [actions/virtual-environments#4620] opened 2021-11-29 00:55 UTC
### Description

I thought it might have been related to this issue but I do not think it is directly related to it as it was wine package specific?
https://github.com/actions/virtual-environments/issues/4589#issuecomment-979413467

>mysteriously failing on libglib2.0-dev:i386 and libsdl2-dev:i386 on my project here:
>
>https://github.com/etfdevs/ETe/runs/4326926427?check_suite_focus=true
>
>Attempting to add the listed packages only further adds more package complaints >https://github.com/etfdevs/ETe/runs/4327104370?check_suite_focus=true
>
>When it built fine the previously action with no issues on packages a couple weeks ago since last action ran.
>
>x86_64 seems to pass/build just fine with same libs but non-i386 as well.

Last successful build on 20.04 : https://github.com/etfdevs/ETe/runs/4195324955?check_suite_focus=true

There appears to be several image updates since then but I had no pushes in between `4195324955` and `4326926427` runs so I do not know how to track down which image update/packages down the chain may have broken these.

Not 100% positive why libglib was needed but SDL is required on this project for unix based builders presently.

I am using Manjaro Linux myself so I do not have an ability to test out Ubuntu repos locally.

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20211122.1

https://github.com/etfdevs/ETe/actions

First failing related to packages: https://github.com/etfdevs/ETe/runs/4326926427?check_suite_focus=true

### Is it regression?

20211108.1

### Expected behavior

Packages should install or be ignored if they are already up to date

### Actual behavior

An unrecoverable state of "broken" package dependencies.

### Repro steps

Utilizing the following apt commands to setup image for necessary libraries:

```sh
sudo dpkg --add-architecture i386
sudo apt-get -qq update
sudo apt-get -y install gcc-multilib g++-multilib ninja-build libglib2.0-dev:i386 libjpeg-dev:i386 libsdl2-dev:i386 libcurl4-openssl-dev:i386
```

**Comment by Sam-Sundar-Apty** [comment] 2021-11-29 06:41
Hi @ensiform,

As a temporary workaround, u can use below command until Github fixes the issue. 

```bash
sudo dpkg --add-architecture i386
sudo apt-get -qq update
sudo apt-get -y install --allow-downgrades libpcre2-8-0=10.34-7 gcc-multilib g++-multilib ninja-build libglib2.0-dev:i386 libjpeg-dev:i386 libsdl2-dev:i386 libcurl4-openssl-dev:i386
```

**Comment by shilovmaksim** [comment] 2021-11-29 07:03
Hi @ensiform. Please try use workaround from @Sam-Sundar-Apty.
I'm going to close this issue as a duplicate of https://github.com/actions/virtual-environments/issues/4589, but feel free to reopen it if you think it's not related.

**Closed by shilovmaksim** 2021-11-29 07:03 UTC
Labels: needs triage

**Comment by ensiform** [comment] 2021-11-29 14:50
Does work for now yes
