### ISSUE TITLE
Add Microsoft SQL Server Express to Windows VMs

### ISSUE THREAD

**Issue by ADmad** [actions/virtual-environments#413] opened 2020-02-15 14:26 UTC
**Tool information**
- Tool name: Microsoft SQL Server Express
- Add or update? Add
- Desired version: 
- Approximate size: 
- If this is an add request:
  - Brief description of tool: 
  - URL for tool's homepage: 

**Area for Triage**:
Databases 

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
I guess so.

**Are you willing to submit a PR?**
Sorry, I don't have enough knowledge for it.

**Comment by mprins** [comment] 2020-02-19 13:37
Would be good to have (developer edition) SQL Server on Ubuntu too.

This is available as an APT package: https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-ubuntu?view=sql-server-ver15

**Comment by MatthewSteeples** [comment] 2020-02-22 12:01
@ADmad it's not advertised, but the 2019 images do contain [SQL LocalDB](https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/sql-server-express-localdb?view=sql-server-ver15) if that helps your use case at all?

The path for that is `C:\Program Files\Microsoft SQL Server\130\Tools\Binn\SqlLocalDB.exe`

**Comment by ADmad** [comment] 2020-02-22 13:49
@MatthewSteeples Thanks for the info, I guess the issue can be closed then. Now I need to figure out how to connect/use it from PHP :slightly_smiling_face:.

**Comment by ADmad** [comment] 2020-02-23 18:21
Reopening this as think https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md should at least be updated to mention that SQL LocalDB is available.

**Comment by miketimofeev** [comment] 2020-02-24 09:58
I've made [a PR](https://github.com/actions/virtual-environments/pull/452) with the changes

**Comment by miketimofeev** [comment] 2020-02-24 14:50
@ADmad Next image rollout will include SQL LocalDB in the readme. Thanks for reporting.

**Comment by mprins** [comment] 2020-03-03 11:23
LocalDB does not support TCP/IP AFAIK (while Express/Developer/etc. do) so connecting through JDBC is basically impossible.

see eg: 
- https://github.com/microsoft/mssql-jdbc/issues/1157
- https://github.com/microsoft/mssql-jdbc/issues/769
- https://github.com/microsoft/mssql-jdbc/issues/1150

using named pipes (which is available in a patched version of the unsupported jTDS driver) is very impractial as the pipename varies per build

**Comment by miketimofeev** [comment] 2020-03-03 13:39
@mprins so we still need to install SQL Server Express to get such functionality, right?

**Comment by mprins** [comment] 2020-03-03 16:54
Yes please; also not sure if express has tcp/ip enabled by default; pretty sure sql server developer does though.

I will also give the choco packages a try if I can find some time this week see: https://chocolatey.org/packages/sql-server-express or https://chocolatey.org/packages/sql-server-2019

I've tried the docker version of sql server developer before, but the windows docker images are stuck at win-server-2016 giving other issues

**Comment by miketimofeev** [comment] 2020-04-10 12:12
@ADmad @mprins Unfortunately we've found serious issues https://github.com/actions/virtual-environments/issues/691 https://github.com/actions/virtual-environments/issues/692 caused by SQL server express installation and going to remove it from the image. 
We will investigate the installation approach more carefully and prepare another PR.
Thank you!

**Comment by ADmad** [comment] 2020-04-10 12:26
@miketimofeev SQL LocalDB suffices for my needs, so the lack of SQL Express isn't an issue for me currently.

I left the issue open as others asked for it.

**Comment by krokofant** [comment] 2020-04-30 10:20
So the LocalDB that's available is an old version and not the newest one shipped with SQL Server 2019?

**Comment by AlenaSviridenko** [comment] 2020-05-13 10:33
Hi @krokofant,
that's correct, LocalDB we are providing is installed with Visual Studio, it can be older that the one provided with SQL Server 2019. 
Currently, we are not planning to install SQL Server 2019 on images due to breaking changes it can bring on them.

**Comment by AlenaSviridenko** [comment] 2020-05-13 10:35
Closing this issue, since we reviewed the possible impact of installing SQL Server Express and decided not to install it now.
Please, feel free to open the new ticket if needed. Thank you.

**Closed by AlenaSviridenko** 2020-05-13 10:35 UTC
Labels: Area: Databases, OS: Windows, investigate

**Comment by mprins** [comment] 2020-05-26 12:38
Bummer, it means it's impossible to test Java applications on Windows+SQL server using GH actions

**Comment by jas88** [comment] 2021-06-01 15:57
@mprins You can install SQL Server 2019 via Choco if you need it - we're doing that on a few projects now.

If it breaks "plain" Windows Server, I'd have preferred offering it as a variant - something like "windows-latest" and "windows-sql-latest". Better than pulling in and running a 1.3GB install file for every single action, surely...

**Comment by mprins** [comment] 2021-06-03 12:24
@jas88 Thanks, I've resorted to a Windows docker image with sql server 2019: https://github.com/mprins/cautious-chainsaw/blob/main/Dockerfile
