### ISSUE TITLE
Failure to install Service Fabric 7 on Win2019

### ISSUE THREAD

**Issue by samrobillard** [actions/virtual-environments#543] opened 2020-03-11 18:18 UTC
**Describe the bug**
It looks like the Service Fabric 7 install starts before its prerequisite, Service Fabric SDK 4.0.7, is installed.

**Area for Triage**: 

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Windows Server 2016 R2
- [X] Windows Server 2019

**Actual behavior**
    image: The software that you obtain using the Web Platform Installer Command Line Tool is licensed to you by its owner.  Microsoft grants you no rights for third party software.
    image: Successfully loaded primary feed: https://webpifeed.blob.core.windows.net/webpifeed/5.1/WebProductList.xml
    image: The following software is going to be installed:
    image: EULA: 'Microsoft Visual C++ 2012 SP1 Redistributable Package (x64)', which is owned by 'Microsoft Corporation', will be downloaded from 'http://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU1/vcredist_x64.exe'.
    image: The license agreement to 'Microsoft Visual C++ 2012 SP1 Redistributable Package (x64)' may be included with the software.
    image: You are responsible for and must separately locate, read and accept these license terms.
    image: EULA: 'Microsoft Azure Service Fabric Runtime - 7.0.470', which is owned by 'Microsoft', will be downloaded from 'https://download.microsoft.com/download/0/0/f/00fbca28-0a64-4c9a-a3a3-b11763ee17e5/MicrosoftServiceFabric.7.0.470.9590.exe'.
    image: The license agreement to 'Microsoft Azure Service Fabric Runtime - 7.0.470' is available at 'http://go.microsoft.com/fwlink/?LinkID=780772&clcid=0x409'.
    image: EULA: 'Microsoft Azure Service Fabric SDK - 4.0.470', which is owned by 'Microsoft', will be downloaded from 'https://download.microsoft.com/download/0/0/f/00fbca28-0a64-4c9a-a3a3-b11763ee17e5/MicrosoftServiceFabricSDK.4.0.470.msi'.
    image: The license agreement to 'Microsoft Azure Service Fabric SDK - 4.0.470' is available at 'http://go.microsoft.com/fwlink/?LinkID=780772&clcid=0x409'.
    image: EULA: 'Microsoft Azure Service Fabric SDK - 4.0.470', which is owned by 'Microsoft' will be installed
    image: The license agreement to 'Microsoft Azure Service Fabric SDK - 4.0.470' may be included with the software.
    image: You are responsible for and must separately locate, read and accept these license terms.
    image: Accepted EULA.
    image: Starting Installation
    image: Started downloading products...
    image: Started downloading: 'Microsoft Visual C++ 2012 SP1 Redistributable Package (x64)'
    image: Downloaded: 'Microsoft Visual C++ 2012 SP1 Redistributable Package (x64)'
    image: Started downloading: 'Microsoft Azure Service Fabric Runtime - 7.0.470'
    image: Started installing Products...
    image: Started installing: 'Microsoft Visual C++ 2012 SP1 Redistributable Package (x64)'
    image: Downloaded: 'Microsoft Azure Service Fabric Runtime - 7.0.470'
    image: Install completed (Success): 'Microsoft Visual C++ 2012 SP1 Redistributable Package (x64)'
    image: Microsoft Visual C++ 2012 SP1 Redistributable Package (x64) : Installed
    image: Started downloading: 'Microsoft Azure Service Fabric SDK - 4.0.470'
    image: Started installing: 'Microsoft Azure Service Fabric Runtime - 7.0.470'
    image: Downloaded: 'Microsoft Azure Service Fabric SDK - 4.0.470'
2020/03/11 17:05:01 packer.exe plugin: [INFO] command 'powershell -executionpolicy bypass "& { if (Test-Path variable:global:ProgressPreference){set-variable -name variable:global:ProgressPreference -value 'SilentlyContinue'};. c:/Windows/Temp/packer-ps-env-vars-5e68f41a-bb74-1531-1613-75bd2e02931c.ps1; &'c:/Windows/Temp/script-5e68f41a-2525-a2f1-7f7e-127e28bff833.ps1'; exit $LastExitCode }"' exited with code: 4294967295

**Comment by samrobillard** [comment] 2020-03-11 18:20
Adding missing part of the log:

    image: Install completed (Failure): 'Microsoft Azure Service Fabric Runtime - 7.0.470'
    image: ServiceFabricRuntime_7_0_cu4 : Failed.
    image:
    image: DependencyFailed : Microsoft Azure Service Fabric SDK - 4.0.470
    image: DependencyFailed : Microsoft Azure Service Fabric SDK - 4.0.470
    image:
    image: Verifying successful installation...
    image: Microsoft Visual C++ 2012 SP1 Redistributable Package (x64) True
    image: Microsoft Azure Service Fabric Runtime - 7.0.470   False
    image:     Log Location: %windir%\Temp\InstallFabricRuntime.log
    image: Microsoft Azure Service Fabric SDK - 4.0.470       False
    image: Microsoft Azure Service Fabric SDK - 4.0.470       False
2020/03/11 17:05:01 packer.exe plugin: c:/Windows/Temp/script-5e68f41a-2525-a2f1-7f7e-127e28bff833.ps1 returned with exit code 4294967295
2020/03/11 17:05:01 [INFO] (telemetry) ending powershell
    image: Install of Products: FAILURE

**Comment by al-cheb** [comment] 2020-03-12 06:29
Hello, @samrobillard 
Looks like a temporary network error.  The build was successfully build - https://github.visualstudio.com/virtual-environments/_build/results?buildId=62072&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=486c0909-f67d-5748-80b3-bb1d531e7b43

**Comment by maxim-lobanov** [comment] 2020-03-16 12:36
@samrobillard , could you please check if the issue is resolved or still actual?

**Comment by samrobillard** [comment] 2020-03-16 12:38
@maxim-lobanov this issue is now resolved even though I was still unable to create a single image yet. Is there a reason this is so unstable?

**Comment by maxim-lobanov** [comment] 2020-03-16 16:05
We are looking at ways to improve stability so thank you for your feedback and provided logs.
We are collecting narrow places in #507 to investigate ways to make it more stable.
I am closing this issue for now, but feel free to update #507 if you see any other issues with reliability

**Closed by maxim-lobanov** 2020-03-16 16:05 UTC
Labels: OS: Windows, needs triage
