### ISSUE TITLE
Add SQL Server Developer Edition

### ISSUE THREAD

**Issue by wsmelton** [actions/virtual-environments#1551] opened 2020-09-07 01:11 UTC
**Tool information**
- Tool name: SQL Server Developer Edition
- Tool license: License is provided free by Microsoft for development purposes
- Add or update? Add
- Desired version: 2016/2017/2019
- Approximate size: 
- If this is an add request:
  - Brief description of tool: SQL Server database system
  - URL for tool's homepage: 
  - Provide a basic test case to validate the tool's functionality: PowerShell modules or applications that want to test against an Edition that is likely to be in production environments. SQL Server Developer Edition has the same functionality as SQL Server Enterprise Edition.

**Area for Triage**:

**Question, Bug, or Feature?**:

**Virtual environments affected**
- [ ] macOS 10.15
- [ ] Ubuntu 16.04 LTS
- [ ] Ubuntu 18.04 LTS
- [ ] Ubuntu 20.04 LTS
- [x] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
I believe the easiest thing would be to offer images from Azure that include SQL Server Developer already installed, and then apply your build steps to that image. The code itself though for installing SQL Server can be done via PowerShell using [dbatools module](https://docs.dbatools.io/#Install-DbaInstance): `Install-DbaInstance` includes the code for this process if you want to strip it out from there.

**Tool installation time in runtime**
The average time depends on the server size, but based on the one I saw noted I would estimate around 10 minutes.

**Are you willing to submit a PR?**
Yes

**Comment by maxim-lobanov** [comment] 2020-09-10 12:17
Hello @wsmelton , this issue looks like duplicate of https://github.com/actions/virtual-environments/issues/1282, correct me if I am wrong

**Comment by wsmelton** [comment] 2020-09-10 12:41
To some degree, yes. That is around using SQL Server Express Edition and/or SQL localdb. The Developer Edition offers more functionality that developers will want available to test against. 

SQL Server Express won't be usable for my needs and purposes.

**Comment by krokofant** [comment] 2020-09-10 13:10
Could we consider adding SQL Server Developer edition and in tandem a newer LocalDB? Wouldn't that cover most needs? Is there any inherit benefit of using Express instead of Developer?

**Comment by wsmelton** [comment] 2020-09-10 13:43
The footprint between Express and Developer for the Database Engine may be a little different, but not extreme. Patching is done the same, and install time is about the same as well. I've installed and configured SQL Server in about 12 minutes using PowerShell DSC. If you are using dbatools it is a bit longer, but less setup and code required.

Express Edition if folks want to include other components of SQL Server to test with (e.g. SSISDB) then Developer has to exists. They can simply add in their workflow to add the feature or component (the installer is cached in Windows for SQL Server).

**Comment by mprins** [comment] 2020-11-18 23:23
Express/localDB does not support JDBC connection, Developer does

**Comment by ghulamostafa** [comment] 2020-12-01 10:30
You can find the steps for installing SQL Server Express on [Ubuntu here](http://ghulamustafa.com/2020/11/28/sql-server-on-ubuntu/). It is used for Digital Ocean VM but can be used with other providers also.

**Comment by mprins** [comment] 2020-12-01 10:53
@ghulamostafa not useful; this request is about "developer" on "windows", so a different product as well as a different OS.
for ubuntu it's really easy to just use the docker image provided by microsoft

**Comment by maxim-lobanov** [comment] 2021-02-11 11:50
Hello everyone, we had some internal discussion about it and decided to not pre-install SQL Server into the images due to maintenance concerns, tool size and tool popularity.

**Closed by maxim-lobanov** 2021-02-11 11:50 UTC
Labels: Area: Databases, OS: Windows, Should we add this?, feature request

**Comment by wsmelton** [comment] 2021-02-11 14:15
That's disappointing because it is the one blocker for us to move off Appveyor for our project.

**Comment by fmms** [comment] 2023-08-27 21:38
has there been any positive news regarding this. I do not need SQL Server though I would have loved to have the IntegrationServices DLLs that come with it in the GAC... Reported at #8174 .
