### ISSUE TITLE
Xamari.iOS build broken on 20210510.1

### ISSUE THREAD

**Issue by tomasz-soltysik** [actions/virtual-environments#3374] opened 2021-05-13 13:20 UTC
**Description**  
Newest Mac agent image has incompatible versions of Xamarin.iOS and Xcode.

> MTOUCH : error MT0180: This version of Xamarin.iOS requires the iOS 14.5 SDK (shipped with Xcode 12.5). Either upgrade Xcode to get the required header files or set the managed linker behaviour to Link Framework SDKs Only in your project's iOS Build Options > Linker Behavior (to try to avoid the new APIs).

[20210510.1 release notes](https://github.com/actions/virtual-environments/blob/releases/macOS-10.15/20210510/images/macos/macos-10.15-Readme.md) contains info that it has Xamari.iOS 14.16, which works only with Xcode 12.5, which is not included in this agent image.

**Area for Triage**: 
Xcode, Xamarin

**Question, Bug, or Feature?**: 
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
20210510.1

**Expected behavior**  
iOS build succeeded

**Actual behavior**  
iOS build will pass only if linker options is set to Link Framework SDKs Only

**Comment by AlenaSviridenko** [comment] 2021-05-13 13:29
Hi @tomasz-soltysik,
as a workaround you can change default Xamarin.iOS versions by switching a default bundle with the code below:
```
steps:
      - uses: actions/checkout@v2
      - name: Select default Xamarin bundle to 6_12_7
        run: |
          XAMARIN_SDK=6_12_7
          $VM_ASSETS/select-xamarin-sdk.sh $XAMARIN_SDK
```


You can read more about bundles and versions assigned to them in the official docs:  https://docs.github.com/en/actions/guides/building-and-testing-xamarin-applications

**Comment by AlenaSviridenko** [comment] 2021-05-13 13:30
Meanwhile, we will investigate the issue, because our internal tests have passed for Xamarin.iOS 14.16 + Xcode 12.4.
Thank you for your report.

**Comment by tomasz-soltysik** [comment] 2021-05-13 13:36
Just to clarify: I'm using Azure Pipelines (Azure Devops).

**Comment by AlenaSviridenko** [comment] 2021-05-13 13:41
Oh, then please, check out this guide https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#how-can-i-manually-select-versions-of-tools-on-the-hosted-macos-agent

**Comment by ramtechjoe** [comment] 2021-05-14 15:44
I believe the issue is because of the Xcode 12.5 update.  Things worked fine for me on Azure pipelines prior to that upgrade

**Comment by mattleibow** [comment] 2021-05-17 22:58
Yeah. In order to test, you have to actually compile a project. I have a testing repo here:
 - yaml: https://github.com/mattleibow/DevOpsTesting/blob/d75a3dc65c1feac37698199a8cb42330214be17a/azure-pipelines.yml#L8
 - pipeline: https://dev.azure.com/mattleibow/OpenSource/_build/results?buildId=536&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=efa2bfe1-554a-50c8-79b6-ef106ad3c7c2

**Comment by DavidStrickland0** [comment] 2021-05-20 22:05
My Builds started working again. Not sure if its a fluke or a fix.

**Comment by miketimofeev** [comment] 2021-05-21 07:08
@DavidStrickland0 @tomasz-soltysik  we have removed the latest Xamarin ios as it's incompatible with Xcode 12.4.
I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!

**Closed by miketimofeev** 2021-05-21 07:08 UTC
Labels: Area: Apple, OS: macOS, question
