### ISSUE TITLE
inconsistent-behaviour-with-robot-docker-compose-mockserver

### ISSUE THREAD

**Issue by general-kroll-4-life** [actions/virtual-environments#5954] opened 2022-07-25 00:21 UTC
### Description

I have one step in a job that uses robot framework to start containers via `docker-compose`, as part of an automated test suite setup.  Sometimes this step (`jobs.dockerbuild['Run robot mocked functional tests']`) runs successfully and other times it just hangs until timeout (without timeout just hangs indefinitely until manual cancellation):

- [successful run](https://github.com/stackql/stackql/actions/runs/2726850894)
- [failed run](https://github.com/stackql/stackql/actions/runs/2725558820)

There is a fair bit going on in the test suite, including java mockservers starting up, docker compose, host network issues.  That being said, my oldish macbook has no issues running this suite.  The lack of visible logs makes it quite difficult to ascertain a cause. 

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

`Version: 20220717.1` for both successful and failed runs.

Builds:

- [successful run](https://github.com/stackql/stackql/actions/runs/2726850894)
- [failed run](https://github.com/stackql/stackql/actions/runs/2725558820)

### Is it regression?

No

### Expected behavior

The step to either repeatedly succeed or repeatedly fail, preferably with some logs visible on failure.

### Actual behavior

The step sometimes seucceeding and other times failing.  On failure logs are sparse at best.

### Repro steps

Run the action with same commit provided in description.

**Comment by al-cheb** [comment] 2022-07-25 07:19
Hey @general-kroll-4-life.
We will take a look at it.

**Comment by al-cheb** [comment] 2022-07-26 14:11
@general-kroll-4-life, I was able to reproduce the same issue on my local vm . The tests got stuck because a docker container had exited. The second attempt to rerun the tests was successful. 

Failed case when containers did not properly start:

```
CONTAINER ID   IMAGE          COMMAND                  CREATED        STATUS    PORTS     NAMES
30249fb34c3b   1ac11fe7d0ee   "/bin/sh -c '#(nop) …"   1 second ago   Created             modest_goldberg
CONTAINER ID   IMAGE          COMMAND                  CREATED        STATUS                  PORTS     NAMES
ac31afc470f1   53158c8bfa36   "/bin/sh -c 'cd ${SR…"   2 minutes ago   Up 2 minutes             affectionate_wilson
CONTAINER ID   IMAGE          COMMAND                  CREATED         STATUS                      PORTS     NAMES
ac31afc470f1   53158c8bfa36   "/bin/sh -c 'cd ${SR…"   3 minutes ago   Exited (0) 13 seconds ago             affectionate_wilson
CONTAINER ID   IMAGE          COMMAND                  CREATED          STATUS         PORTS     NAMES
0680caea36b9   6b707affb801   "/bin/sh -c 'apt-get…"   10 seconds ago   Up 9 seconds             competent_driscoll
CONTAINER ID   IMAGE          COMMAND                  CREATED          STATUS                     PORTS     NAMES
0680caea36b9   6b707affb801   "/bin/sh -c 'apt-get…"   15 seconds ago   Exited (0) 3 seconds ago             competent_driscoll
CONTAINER ID   IMAGE          COMMAND                  CREATED         STATUS                     PORTS     NAMES
0680caea36b9   6b707affb801   "/bin/sh -c 'apt-get…"   6 minutes ago   Exited (0) 6 minutes ago             competent_driscoll
```

Add a second attempt as a workaround:
```
    - name: Second attempt 
      if: always()
      run: |
        robot --variable EXECUTION_PLATFORM:docker test/robot/functional
        cat ./output.xml
```

![image](https://user-images.githubusercontent.com/47745270/181020475-e1d9889c-bcc8-40df-8729-ecc6701c1781.png)


Ps. I am planning to close the issue because it is not related to an image runner and can be reproduced locally.

**Closed by al-cheb** 2022-07-26 14:11 UTC
Labels: Area: Java, Area: Testing and code coverage, OS: Ubuntu, bug report

**Comment by general-kroll-4-life** [comment] 2022-07-27 02:43
Hi Aleksandr,

Thank you kindly.

Much appreciated.

Cheers,

Kieran
