### ISSUE TITLE
[MacOS] java.net.SocketException: Broken pipe (Write failed)

### ISSUE THREAD

**Issue by andrewclaus** [actions/virtual-environments#3596] opened 2021-06-16 16:30 UTC
**Description**  
We are using Azure DevOps pipelines with the macos-latest agent to build our Android projects. Randomly, a build will error out when downloading dependencies with the following SSL error. Re-running the failed job on a new agent usually results in success.

```
Starting: gradle build for release
==============================================================================
Task         : Gradle
Description  : Build using a Gradle wrapper script
Version      : 2.186.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/gradle
==============================================================================
/Users/runner/work/1/s/gradlew assembleRelease
Downloading https://services.gradle.org/distributions/gradle-7.0-bin.zip

Exception in thread "main" java.lang.RuntimeException: javax.net.ssl.SSLException: readHandshakeRecord
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:78)
	at org.gradle.wrapper.Install.createDist(Install.java:47)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:48)
Caused by: javax.net.ssl.SSLException: readHandshakeRecord
	at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1300)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:435)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:197)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:59)
	at org.gradle.wrapper.Download.download(Download.java:45)
	at org.gradle.wrapper.Install$1.call(Install.java:60)
	at org.gradle.wrapper.Install$1.call(Install.java:47)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	... 3 more
	Suppressed: java.net.SocketException: Broken pipe (Write failed)
		at java.net.SocketOutputStream.socketWrite0(Native Method)
		at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
		at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
		at sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:81)
		at sun.security.ssl.TransportContext.fatal(TransportContext.java:355)
		at sun.security.ssl.TransportContext.fatal(TransportContext.java:267)
		at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:438)
		... 13 more
Caused by: java.net.SocketException: Broken pipe (Write failed)
```

**Area for Triage**:  
Android

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [x] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016 R2
- [ ] Windows Server 2019

**Image version**
20210607.1

**Expected behavior**  
Gradle-7.0-bin.zip is downloaded reliably

**Actual behavior**  
Occasionally, this file will be unable to download with the above SSL error.

**Repro steps**  
1. Clone a git repository holding a basic Android project that is using Gradle 7.0 (The gradle version might not matter)
2. Run "/Users/runner/work/1/s/gradlew assemble" which will attempt to download the project dependencies, including gradle 7.0
3. Run these steps on a new macos-latest build agent a bunch of times. Usually this will be successful, but maybe 5% of the time it will fail with an SSL error

**Comment by al-cheb** [comment] 2021-06-17 06:48
Hello, @andrewclaus 
Thank you for your report. We will take a look.

**Comment by Darleev** [comment] 2021-06-20 19:16
Hello @andrewclaus,
Could you please provide minimal steps to reproduce the issue? Is it enough to download gradle binary?
At this time, the issue looks like server-side SSL problems and should be checked from both ends.
We're looking forward to your reply.

**Comment by andrewclaus** [comment] 2021-06-21 15:23
The minimal steps are: 

1. Create a new android project that uses gradle 7.0
2. Upload to git repo
3. Run these steps on a MacOS 10.15 build agent: 
4. clone git repo
5. gradlew clean assemble
6. it will attempt to download the gradle binary and might fail with an SSL error

**Comment by Darleev** [comment] 2021-06-21 16:22
@andrewclaus Could you please provide us a sample repo with minimal steps to reproduce the issue? Steps by steps instruction with sample repo would be also much appreciated.
We're looking forward to your reply.

**Comment by Darleev** [comment] 2021-06-23 19:32
@andrewclaus I tried to build a sample application locally and was not able to reproduce the issue. However, tomorrow I got SSL error locally as well. So, I guess that issue somehow related to Gradle downloading and not agent-specific. Did you face the same issue locally?
We're looking forward to your reply.

**Comment by andrewclaus** [comment] 2021-06-23 21:28
I have not heard complaints from my teammates about gradle failing to download locally, but we do not have to do that very often, unlike the build agents which have to download it every time. So it could very well just be an issue with the gradle download servers.

**Comment by Darleev** [comment] 2021-06-24 08:28
@andrewclaus Have you encountered this problem in recent days on our agents?

**Comment by Darleev** [comment] 2021-06-28 17:21
I'm going to close the issue until further clarifications from your side.
Feel free to contact us at any time.

**Closed by Darleev** 2021-06-28 17:21 UTC
Labels: OS: macOS, investigate
