### ISSUE TITLE
Add windows/servercore:ltsc2019-amd64 to docker cache on Windows Server 2019

### ISSUE THREAD

**Issue by ghelyar** [actions/virtual-environments#3416] opened 2021-05-19 08:36 UTC
**Tool information**
`windows/servercore:ltsc2019` (without `-amd64`) is [cached in the environment](https://github.com/actions/virtual-environments/blob/5abc43a504e4ba8e869ef7f56e3fd7b0a3d8560d/images/win/toolsets/toolset-2019.json#L283), but `dotnet/aspnet:5.0-windowsservercore-ltsc2019` is based on `windows/servercore:ltsc2019-amd64`, which causes it to miss the cache and have to download the whole base image.

`docker inspect` seems to imply they are identical or at least share layers. If they do share any layers, it may just be that the cached `ltsc2019` image is outdated in the environment, and that's what's causing the cache miss rather than the `ltsc2019-amd64` tag.

**Area for Triage**:
Containers

**Question, Bug, or Feature?**:
Feature

**Virtual environments affected**
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Can this tool be installed during the build?**
Yes, update `toolset-2019.json`

**Tool installation time in runtime**
~15 minutes per job

**Are you willing to submit a PR?**
Yes

**Comment by miketimofeev** [comment] 2021-05-19 11:12
Hi @ghelyar!
Your assumptions are correct — the images are the same, and the root cause of the issue is an outdated image.
![image](https://user-images.githubusercontent.com/48208649/118803209-bfb28c00-b8ab-11eb-9cbc-0f5eb84b9618.png)
The new docker `windows/servercore:ltsc2019` image from May 8 will be deployed along with the 20210516 version of windows 2019 later this week.
https://github.com/actions/virtual-environments/blob/releases/win19/20210516/images/win/Windows2019-Readme.md

I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!

**Closed by miketimofeev** 2021-05-19 11:12 UTC
Labels: OS: Windows, feature request, needs eyes
