### ISSUE TITLE
MSBuild failing with error MSB4041 on windows-2019 image versions 20210309.0 and 20210316.1

### ISSUE THREAD

**Issue by edgariscoding** [actions/virtual-environments#2968] opened 2021-03-17 23:49 UTC
**Description**  
Builds have started failing on a windows-2019 image versions 20210309.0 (#2895) and 20210316.1 (#2948) resulting in error MSB4041 when the MSBuild task on an ASP.NET web site project using .NET Framework 4.7.2 is run. 

The error is: System.NotSupportedException: The given path's format is not supported.

The rest of my projects build just fine, it’s isolated to this type of project.

This problem started last Wednesday (2021-03-10) but re-running the build seemed to fix the issue. It happened again on Friday (2021-03-12) but it required 3 runs to get the build to succeed. As of Monday (2021-03-15) it seems that builds fail no matter how many times we re-run them. 

When the build succeeded, it was using image version 20210219.1 (#2768) or older. I assume not all images in the pool had been updated at that point.

No changes have been made to the build pipeline or the referenced task groups within the build pipeline in many months. No changes have been made to the VS solutions or projects either.

Microsoft, I can provide extra logs and my exported build definition if you need me to.

This issue seems to also been reported here:

https://developercommunity.visualstudio.com/t/starting-today-we-can-no-longer-build-any-vbnet-c/1370287

```
2021-03-17T19:16:07.4579040Z ##[section]Starting: Development Job
2021-03-17T19:16:07.6125147Z ##[section]Starting: Initialize job
2021-03-17T19:16:07.6126625Z Agent name: 'Hosted Agent'
2021-03-17T19:16:07.6126963Z Agent machine name: 'fv-az49-168'
2021-03-17T19:16:07.6127184Z Current agent version: '2.183.1'
2021-03-17T19:16:07.6277889Z ##[group]Operating System
2021-03-17T19:16:07.6278126Z Microsoft Windows Server 2019
2021-03-17T19:16:07.6278303Z 10.0.17763
2021-03-17T19:16:07.6278433Z Datacenter
2021-03-17T19:16:07.6278570Z ##[endgroup]
2021-03-17T19:16:07.6278727Z ##[group]Virtual Environment
2021-03-17T19:16:07.6278932Z Environment: windows-2019
2021-03-17T19:16:07.6279105Z Version: 20210316.1
2021-03-17T19:16:07.6279408Z Included Software: https://github.com/actions/virtual-environments/blob/win19/20210316.1/images/win/Windows2019-Readme.md
2021-03-17T19:16:07.6279819Z Image Release: https://github.com/actions/virtual-environments/releases/tag/win19%2F20210316.1
2021-03-17T19:16:07.6280090Z ##[endgroup]
2021-03-17T19:16:07.6281434Z Current image version: '20210316.1'
2021-03-17T19:16:07.6289393Z Agent running as: 'VssAdministrator'
2021-03-17T19:16:07.6333735Z Prepare build directory.
2021-03-17T19:16:07.6619324Z Set build variables.
2021-03-17T19:16:07.6654177Z Download all required tasks.
2021-03-17T19:16:07.6785677Z Downloading task: PowerShell (2.180.1)
2021-03-17T19:16:09.5279176Z Downloading task: GitDownloader (0.4.7)
2021-03-17T19:16:09.6057699Z Downloading task: NuGetCommand (2.179.0)
2021-03-17T19:16:13.1124387Z Downloading task: CmdLine (2.182.0)
2021-03-17T19:16:13.5136388Z Downloading task: FileTransform (1.182.0)
2021-03-17T19:16:14.8908195Z Downloading task: VSBuild (1.183.0)
2021-03-17T19:16:15.0728629Z Downloading task: PublishPipelineArtifact (1.2.3)
2021-03-17T19:16:15.1397704Z Checking job knob settings.
2021-03-17T19:16:15.1407602Z    Knob: AgentToolsDirectory = C:\hostedtoolcache\windows Source: ${AGENT_TOOLSDIRECTORY} 
2021-03-17T19:16:15.1408992Z    Knob: AgentPerflog = c:\vsts\perflog Source: ${VSTS_AGENT_PERFLOG} 
2021-03-17T19:16:15.1410172Z Finished checking job knob settings.
2021-03-17T19:16:15.1885312Z Start tracking orphan processes.
2021-03-17T19:16:15.1950891Z ##[section]Finishing: Initialize job
```

---

```
2021-03-17T19:19:18.6627586Z ##[section]Starting: Build AttorneyPortal
2021-03-17T19:19:18.6761810Z ==============================================================================
2021-03-17T19:19:18.6762121Z Task         : Visual Studio build
2021-03-17T19:19:18.6762418Z Description  : Build with MSBuild and set the Visual Studio version property
2021-03-17T19:19:18.6762682Z Version      : 1.183.0
2021-03-17T19:19:18.6762887Z Author       : Microsoft Corporation
2021-03-17T19:19:18.6763215Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/visual-studio-build
2021-03-17T19:19:18.6763568Z ==============================================================================
2021-03-17T19:19:19.7577582Z ##[command]"D:\a\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.183.0\ps_modules\MSBuildHelpers\vswhere.exe" -version [16.0,17.0) -latest -format json
2021-03-17T19:19:20.8858607Z ##[command]"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\amd64\msbuild.exe" "D:\a\1\s\Sources\AttorneyPortal.sln" /nologo /nr:false /dl:CentralLogger,"D:\a\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.183.0\ps_modules\MSBuildHelpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll";"RootDetailId=e672e71d-1304-40a3-9332-ab33f60662dc|SolutionDir=D:\a\1\s\Sources"*ForwardingLogger,"D:\a\_tasks\VSBuild_71a9a2d3-a98a-4caa-96ab-affca411ecda\1.183.0\ps_modules\MSBuildHelpers\Microsoft.TeamFoundation.DistributedTask.MSBuild.Logger.dll"  /p:platform="Any CPU" /p:configuration="debug" /p:VisualStudioVersion="16.0" /m /p:_MSDeployUserAgent="VSTS_5795f566-bfe6-4344-80ac-51a53af3400b_build_62_0"
2021-03-17T19:19:26.0851296Z Build started 3/17/2021 7:19:26 PM.
2021-03-17T19:19:27.1719660Z ##[error]Sources\AttorneyPortal.sln(0,0): Error MSB4014: The build stopped unexpectedly because of an internal failure.
System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at Microsoft.Build.Construction.ProjectInSolution.get_AbsolutePath()
   at Microsoft.Build.Construction.SolutionProjectGenerator.AddPropertyGroupForSolutionConfiguration(ProjectRootElement msbuildProject, SolutionFile solutionFile, SolutionConfigurationInSolution solutionConfiguration)
   at Microsoft.Build.Construction.SolutionProjectGenerator.CreateTraversalInstance(String wrapperProjectToolsVersion, Boolean explicitToolsVersionSpecified, List`1 projectsInOrder)
   at Microsoft.Build.Construction.SolutionProjectGenerator.CreateSolutionProject(String wrapperProjectToolsVersion, Boolean explicitToolsVersionSpecified)
   at Microsoft.Build.Construction.SolutionProjectGenerator.Generate()
   at Microsoft.Build.Execution.ProjectInstance.GenerateSolutionWrapper(String projectFile, IDictionary`2 globalProperties, String toolsVersion, ILoggingService loggingService, BuildEventContext projectBuildEventContext, IReadOnlyCollection`1 targetNames, ISdkResolverService sdkResolverService, Int32 submissionId)
   at Microsoft.Build.Execution.ProjectInstance.LoadSolutionForBuild(String projectFile, PropertyDictionary`1 globalPropertiesInstances, String toolsVersion, BuildParameters buildParameters, ILoggingService loggingService, BuildEventContext projectBuildEventContext, Boolean isExplicitlyLoaded, IReadOnlyCollection`1 targetNames, ISdkResolverService sdkResolverService, Int32 submissionId)
   at Microsoft.Build.Execution.BuildManager.LoadSolutionIntoConfiguration(BuildRequestConfiguration config, BuildRequest request)
   at Microsoft.Build.Execution.BuildManager.HandleNewRequest(Int32 node, BuildRequestBlocker blocker)
   at Microsoft.Build.Execution.BuildManager.IssueBuildSubmissionToScheduler(BuildSubmission submission, Boolean allowMainThreadBuild)
2021-03-17T19:19:27.1812697Z      0>D:\a\1\s\Sources\AttorneyPortal.sln : error MSB4014: The build stopped unexpectedly because of an internal failure.
2021-03-17T19:19:27.1815138Z D:\a\1\s\Sources\AttorneyPortal.sln : error MSB4014: System.NotSupportedException: The given path's format is not supported.
2021-03-17T19:19:27.1816197Z D:\a\1\s\Sources\AttorneyPortal.sln : error MSB4014:    at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
2021-03-17T19:19:27.1817484Z D:\a\1\s\Sources\AttorneyPortal.sln : error MSB4014:    at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
2021-03-17T19:19:27.1818425Z D:\a\1\s\Sources\AttorneyPortal.sln : error MSB4014:    at Microsoft.Build.Construction.ProjectInSolution.get_AbsolutePath()
2021-03-17T19:19:27.1819585Z D:\a\1\s\Sources\AttorneyPortal.sln : error MSB4014:    at Microsoft.Build.Construction.SolutionProjectGenerator.AddPropertyGroupForSolutionConfiguration(ProjectRootElement msbuildProject, SolutionFile solutionFile, SolutionConfigurationInSolution solutionConfiguration)
2021-03-17T19:19:27.1821862Z D:\a\1\s\Sources\AttorneyPortal.sln : error MSB4014:    at Microsoft.Build.Construction.SolutionProjectGenerator.CreateTraversalInstance(String wrapperProjectToolsVersion, Boolean explicitToolsVersionSpecified, List`1 projectsInOrder)
2021-03-17T19:19:27.1822857Z D:\a\1\s\Sources\AttorneyPortal.sln : error MSB4014:    at Microsoft.Build.Construction.SolutionProjectGenerator.CreateSolutionProject(String wrapperProjectToolsVersion, Boolean explicitToolsVersionSpecified)
2021-03-17T19:19:27.1829553Z D:\a\1\s\Sources\AttorneyPortal.sln : error MSB4014:    at Microsoft.Build.Construction.SolutionProjectGenerator.Generate()
2021-03-17T19:19:27.1830868Z D:\a\1\s\Sources\AttorneyPortal.sln : error MSB4014:    at Microsoft.Build.Execution.ProjectInstance.GenerateSolutionWrapper(String projectFile, IDictionary`2 globalProperties, String toolsVersion, ILoggingService loggingService, BuildEventContext projectBuildEventContext, IReadOnlyCollection`1 targetNames, ISdkResolverService sdkResolverService, Int32 submissionId)
2021-03-17T19:19:27.1832545Z D:\a\1\s\Sources\AttorneyPortal.sln : error MSB4014:    at Microsoft.Build.Execution.ProjectInstance.LoadSolutionForBuild(String projectFile, PropertyDictionary`1 globalPropertiesInstances, String toolsVersion, BuildParameters buildParameters, ILoggingService loggingService, BuildEventContext projectBuildEventContext, Boolean isExplicitlyLoaded, IReadOnlyCollection`1 targetNames, ISdkResolverService sdkResolverService, Int32 submissionId)
2021-03-17T19:19:27.1833697Z D:\a\1\s\Sources\AttorneyPortal.sln : error MSB4014:    at Microsoft.Build.Execution.BuildManager.LoadSolutionIntoConfiguration(BuildRequestConfiguration config, BuildRequest request)
2021-03-17T19:19:27.1834374Z D:\a\1\s\Sources\AttorneyPortal.sln : error MSB4014:    at Microsoft.Build.Execution.BuildManager.HandleNewRequest(Int32 node, BuildRequestBlocker blocker)
2021-03-17T19:19:27.1835172Z D:\a\1\s\Sources\AttorneyPortal.sln : error MSB4014:    at Microsoft.Build.Execution.BuildManager.IssueBuildSubmissionToScheduler(BuildSubmission submission, Boolean allowMainThreadBuild)
2021-03-17T19:19:27.2031585Z 
2021-03-17T19:19:27.2033439Z Build FAILED.
2021-03-17T19:19:27.2460916Z 
2021-03-17T19:19:27.2480405Z          D:\a\1\s\Sources\AttorneyPortal.sln : error MSB4014: The build stopped unexpectedly because of an internal failure.
2021-03-17T19:19:27.2481501Z        D:\a\1\s\Sources\AttorneyPortal.sln : error MSB4014: System.NotSupportedException: The given path's format is not supported.
2021-03-17T19:19:27.2482478Z        D:\a\1\s\Sources\AttorneyPortal.sln : error MSB4014:    at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
2021-03-17T19:19:27.2483425Z        D:\a\1\s\Sources\AttorneyPortal.sln : error MSB4014:    at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
2021-03-17T19:19:27.2485307Z        D:\a\1\s\Sources\AttorneyPortal.sln : error MSB4014:    at Microsoft.Build.Construction.ProjectInSolution.get_AbsolutePath()
2021-03-17T19:19:27.2486229Z        D:\a\1\s\Sources\AttorneyPortal.sln : error MSB4014:    at Microsoft.Build.Construction.SolutionProjectGenerator.AddPropertyGroupForSolutionConfiguration(ProjectRootElement msbuildProject, SolutionFile solutionFile, SolutionConfigurationInSolution solutionConfiguration)
2021-03-17T19:19:27.2487224Z        D:\a\1\s\Sources\AttorneyPortal.sln : error MSB4014:    at Microsoft.Build.Construction.SolutionProjectGenerator.CreateTraversalInstance(String wrapperProjectToolsVersion, Boolean explicitToolsVersionSpecified, List`1 projectsInOrder)
2021-03-17T19:19:27.2488747Z        D:\a\1\s\Sources\AttorneyPortal.sln : error MSB4014:    at Microsoft.Build.Construction.SolutionProjectGenerator.CreateSolutionProject(String wrapperProjectToolsVersion, Boolean explicitToolsVersionSpecified)
2021-03-17T19:19:27.2490059Z        D:\a\1\s\Sources\AttorneyPortal.sln : error MSB4014:    at Microsoft.Build.Construction.SolutionProjectGenerator.Generate()
2021-03-17T19:19:27.2491145Z        D:\a\1\s\Sources\AttorneyPortal.sln : error MSB4014:    at Microsoft.Build.Execution.ProjectInstance.GenerateSolutionWrapper(String projectFile, IDictionary`2 globalProperties, String toolsVersion, ILoggingService loggingService, BuildEventContext projectBuildEventContext, IReadOnlyCollection`1 targetNames, ISdkResolverService sdkResolverService, Int32 submissionId)
2021-03-17T19:19:27.2492650Z        D:\a\1\s\Sources\AttorneyPortal.sln : error MSB4014:    at Microsoft.Build.Execution.ProjectInstance.LoadSolutionForBuild(String projectFile, PropertyDictionary`1 globalPropertiesInstances, String toolsVersion, BuildParameters buildParameters, ILoggingService loggingService, BuildEventContext projectBuildEventContext, Boolean isExplicitlyLoaded, IReadOnlyCollection`1 targetNames, ISdkResolverService sdkResolverService, Int32 submissionId)
2021-03-17T19:19:27.2494011Z        D:\a\1\s\Sources\AttorneyPortal.sln : error MSB4014:    at Microsoft.Build.Execution.BuildManager.LoadSolutionIntoConfiguration(BuildRequestConfiguration config, BuildRequest request)
2021-03-17T19:19:27.2494776Z        D:\a\1\s\Sources\AttorneyPortal.sln : error MSB4014:    at Microsoft.Build.Execution.BuildManager.HandleNewRequest(Int32 node, BuildRequestBlocker blocker)
2021-03-17T19:19:27.2495557Z        D:\a\1\s\Sources\AttorneyPortal.sln : error MSB4014:    at Microsoft.Build.Execution.BuildManager.IssueBuildSubmissionToScheduler(BuildSubmission submission, Boolean allowMainThreadBuild)
2021-03-17T19:19:27.2495946Z 
2021-03-17T19:19:27.2496187Z     0 Warning(s)
2021-03-17T19:19:27.2496480Z     1 Error(s)
2021-03-17T19:19:27.2496736Z 
2021-03-17T19:19:27.2496987Z Time Elapsed 00:00:01.16
2021-03-17T19:19:27.2497490Z MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
2021-03-17T19:19:27.2498477Z System.NotSupportedException: The given path's format is not supported.
2021-03-17T19:19:27.2499259Z    at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
2021-03-17T19:19:27.2500224Z    at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
2021-03-17T19:19:27.2501353Z    at Microsoft.Build.Construction.ProjectInSolution.get_AbsolutePath()
2021-03-17T19:19:27.2502240Z    at Microsoft.Build.Construction.SolutionProjectGenerator.AddPropertyGroupForSolutionConfiguration(ProjectRootElement msbuildProject, SolutionFile solutionFile, SolutionConfigurationInSolution solutionConfiguration)
2021-03-17T19:19:27.2503437Z    at Microsoft.Build.Construction.SolutionProjectGenerator.CreateTraversalInstance(String wrapperProjectToolsVersion, Boolean explicitToolsVersionSpecified, List`1 projectsInOrder)
2021-03-17T19:19:27.2504538Z    at Microsoft.Build.Construction.SolutionProjectGenerator.CreateSolutionProject(String wrapperProjectToolsVersion, Boolean explicitToolsVersionSpecified)
2021-03-17T19:19:27.2505535Z    at Microsoft.Build.Construction.SolutionProjectGenerator.Generate()
2021-03-17T19:19:27.2506674Z    at Microsoft.Build.Execution.ProjectInstance.GenerateSolutionWrapper(String projectFile, IDictionary`2 globalProperties, String toolsVersion, ILoggingService loggingService, BuildEventContext projectBuildEventContext, IReadOnlyCollection`1 targetNames, ISdkResolverService sdkResolverService, Int32 submissionId)
2021-03-17T19:19:27.2508225Z    at Microsoft.Build.Execution.ProjectInstance.LoadSolutionForBuild(String projectFile, PropertyDictionary`1 globalPropertiesInstances, String toolsVersion, BuildParameters buildParameters, ILoggingService loggingService, BuildEventContext projectBuildEventContext, Boolean isExplicitlyLoaded, IReadOnlyCollection`1 targetNames, ISdkResolverService sdkResolverService, Int32 submissionId)
2021-03-17T19:19:27.2510366Z    at Microsoft.Build.Execution.BuildManager.LoadSolutionIntoConfiguration(BuildRequestConfiguration config, BuildRequest request)
2021-03-17T19:19:27.2511252Z    at Microsoft.Build.Execution.BuildManager.HandleNewRequest(Int32 node, BuildRequestBlocker blocker)
2021-03-17T19:19:27.2512070Z    at Microsoft.Build.Execution.BuildManager.IssueBuildSubmissionToScheduler(BuildSubmission submission, Boolean allowMainThreadBuild)
2021-03-17T19:19:27.2512555Z 
2021-03-17T19:19:27.2519588Z MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
2021-03-17T19:19:27.2520214Z System.NotSupportedException: The given path's format is not supported.
2021-03-17T19:19:27.2521729Z    at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Boolean needToValidateProject, String schemaFile, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, TextWriter targetsWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, Boolean isolateProjects, Boolean graphBuild, Boolean lowPriority, String[] inputResultsCaches, String outputResultsCache)
2021-03-17T19:19:27.2524047Z    at Microsoft.Build.CommandLine.MSBuildApp.Execute(String commandLine)
2021-03-17T19:19:27.3009755Z 
2021-03-17T19:19:27.3013365Z Unhandled Exception: System.NotSupportedException: The given path's format is not supported.
2021-03-17T19:19:27.3015141Z    at Microsoft.Build.CommandLine.MSBuildApp.BuildProject(String projectFile, String[] targets, String toolsVersion, Dictionary`2 globalProperties, Dictionary`2 restoreProperties, ILogger[] loggers, LoggerVerbosity verbosity, DistributedLoggerRecord[] distributedLoggerRecords, Boolean needToValidateProject, String schemaFile, Int32 cpuCount, Boolean enableNodeReuse, TextWriter preprocessWriter, TextWriter targetsWriter, Boolean detailedSummary, ISet`1 warningsAsErrors, ISet`1 warningsAsMessages, Boolean enableRestore, ProfilerLogger profilerLogger, Boolean enableProfiler, Boolean interactive, Boolean isolateProjects, Boolean graphBuild, Boolean lowPriority, String[] inputResultsCaches, String outputResultsCache)
2021-03-17T19:19:27.3016793Z    at Microsoft.Build.CommandLine.MSBuildApp.Execute(String commandLine)
2021-03-17T19:19:27.3017912Z    at Microsoft.Build.CommandLine.MSBuildApp.Main()
2021-03-17T19:19:32.4535907Z ##[error]Process 'msbuild.exe' exited with code '-532462766'.
2021-03-17T19:19:32.4858920Z ##[section]Finishing: Build AttorneyPortal
```

**Area for Triage**:  
investigate

**Question, Bug, or Feature?**:  
Bug

**Virtual environments affected**  
- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11.0
- [ ] Windows Server 2016 R2
- [x] Windows Server 2019

**Image version**
20210309.0 and 20210316.1

**Expected behavior**  
Successful build.

**Actual behavior**  
Error MSB4041 as soon as the MSBuild build task for my web site project runs.

**Comment by maxim-lobanov** [comment] 2021-03-18 07:41
Looks like the issue has appeared after upgrading Visual Studio to 16.9. We will investigate it further.

**Comment by edgariscoding** [comment] 2021-03-18 12:33
@maxim-lobanov if you happen to find a temporary workaround let me know, our pull requests are unable to complete because they require a successful build

**Comment by maxim-lobanov** [comment] 2021-03-22 06:29
Hello everyone!
Just an update, we were working with VS team to identify the fix and it was merged recently via https://github.com/dotnet/msbuild/pull/6273. We are expecting the newer version of VS is released this week and we will take it on images as soon as it is available (considering 3 days deployment process duration 😢 )

**Comment by susanadomingos-falck** [comment] 2021-03-24 06:57
@edgariscoding 
To fix our pipeline we had to fall back to vs2017-win2016 with MSBUILD 15.0, and install some additional components (that are packed into the windows-2019 image, but not the win2016 one) :-(

**Comment by Phil-Be** [comment] 2021-03-25 07:28
Hello @maxim-lobanov , 
Can you confirm that the new version of VS will be released this week? 
We're still stuck and dont wan't to have to do the same thing as @susanadomingos-falck . 
Regards,

**Comment by susanadomingos-falck** [comment] 2021-03-25 07:34
This whole situation is fuel on the campfire for the no-Azure advocates... 🙄🤦‍♀️

**Comment by miketimofeev** [comment] 2021-03-25 08:54
@Phil-Be we don't know the exact date, but most likely — yes. Please pay attention that the new image deployment will start on Monday and it will take 3-4 days to propagate the image to all the environments

**Comment by Phil-Be** [comment] 2021-03-25 08:59
As long as we can at least use one of our agents.
The "likely" is still worrying, but no choice?

Thanks for update though

**Comment by susanadomingos-falck** [comment] 2021-03-29 06:16
Hi Staff

1. Will this issue be solved in the new image?
2. Will that new image's deployment start today?

Thank you.

**Comment by maxim-lobanov** [comment] 2021-03-29 08:13
Hello everyone,
Unfortunately, the new version of VS with fix is not available yet: https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes

**Comment by jeevzb** [comment] 2021-03-29 11:13
Hi @maxim-lobanov , Any ETA for the issue. couple of hour pipelines is running into the issue and we are doing lot of manual builds

**Comment by edgariscoding** [comment] 2021-03-29 11:33
Same issue here, we’ve had to halt our deployments to production and we can’t even merge code into the main branches because the PR require a successful build before they can be completed.

**Comment by Phil-Be** [comment] 2021-03-29 11:53
Same here, an ETA would be appreciated.

**Comment by I-Cat** [comment] 2021-03-30 13:57
The issue is here  [ C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\amd64\msbuild.exe"  ]
see the 
amd64

Windows is x32  x64 x86
Windows Phone is amd64

**Comment by miketimofeev** [comment] 2021-03-30 20:21
Good news! The new version 16.9.3 has been released
https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#16.9.3
We're going to start new image deployment tomorrow and plan to finish on Monday the 5th

**Comment by I-Cat** [comment] 2021-04-03 23:38
> Good news! The new version 16.9.3 has been released
> https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#16.9.3
> We're going to start new image deployment tomorrow and plan to finish on Monday the 5th

> Ah arm64 that makes more sense.

**Comment by miketimofeev** [comment] 2021-04-05 06:27
@edgariscoding we have updated the image with visual studio 16.9.31129.286. Could you please check the behavior?

**Comment by edgariscoding** [comment] 2021-04-05 09:31
@miketimofeev  looks to be working! Thank you!

**Comment by miketimofeev** [comment] 2021-04-05 09:33
@edgariscoding I'm going to close the issue. Please feel free to contact us if you have any concerns.
Thank you!

**Closed by miketimofeev** 2021-04-05 09:33 UTC
Labels: Area: .NET Framework, OS: Windows, bug
