### ISSUE TITLE
Windows Driver Build Failure on windows-2022 Image

### ISSUE THREAD

**Issue by nibanks** [actions/virtual-environments#4139] opened 2021-09-23 12:55 UTC
### Description

When we move our Windows driver builds to run on the `windows-2022` image they fail with the following error:
> ##[error]C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(436,5): Error MSB8020: The build tools for WindowsKernelModeDriver10.0 (Platform Toolset = 'WindowsKernelModeDriver10.0') cannot be found. To build using the WindowsKernelModeDriver10.0 build tools, please install WindowsKernelModeDriver10.0 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution".

PR: https://github.com/microsoft/msquic/pull/2025
Pipeline: https://dev.azure.com/ms/msquic/_build/results?buildId=224542&view=logs&j=94396e2f-981e-567a-61e4-6daa52649fcc&t=67d38931-2ffe-5107-01d6-fdb4cd94df8c

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Environment: windows-2022
Version: 20210920.1
Included Software: https://github.com/actions/virtual-environments/blob/win22/20210920.1/images/win/Windows2022-Readme.md
Image Release: https://github.com/actions/virtual-environments/releases/tag/win22%2F20210920.1

### Is it regression?

Yes, at least from windows-latest

### Expected behavior

The build should succeed, just as it does when using `windows-latest`.

### Actual behavior

The build fails.

### Repro steps

1. Run `VSBuild@1` task for a Windows driver on `windows-2022` image.

**Comment by dibir-magomedsaygitov** [comment] 2021-09-23 12:57
Hello @nibanks. Thank you for your report. We will take a look.

**Comment by mikhailkoliada** [comment] 2021-09-24 19:10
Hello @nibanks!

I guess the problem is missing WDK installation in our win22 image. I believe there had been no proper WDK version released by the time we had been preparing the release. Apart from that we are shipping Visual Studio Code 2022 Preview as a part of the image. There is no compatible public WDK release available yet, which means we can not handle this issue right now.

**Comment by nibanks** [comment] 2021-09-24 19:20
Hmm... do you have any contacts that might provide some ETA for a WDK that works with Visual Studio 2022?

**Comment by mikhailkoliada** [comment] 2021-09-27 08:39
@nibanks Looks like there is a question about it [already](https://developercommunity.visualstudio.com/t/vs2022-missing-compatible-wdk/1507277). I'll try to contact Luke to see what's going on and figure out if there is expected ETA.

**Comment by Cymoki** [comment] 2021-09-28 17:40
The WDK team is working to ensure WDK compatibility with Visual Studio 2022. Preview versions of the WDK that supports Visual Studio 2022 will be made available through the Windows Insider Program (WIP) as soon as its ready for insiders to review.

**Comment by mikhailkoliada** [comment] 2021-09-29 08:38
@Cymoki thanks a lot for the update!

@nibanks as there is nothing for us to do yet (and there will be nothing to do in the near future as well I bet) I am going to close this issue for now. Feel free to reopen / file a new one as soon as the WDK release is available and we will surely add it to the image.

**Closed by mikhailkoliada** 2021-09-29 08:38 UTC
Labels: OS: Windows, investigate

**Comment by nibanks** [comment] 2021-09-29 11:09
Ok, but this must block 2022 from becoming latest, as it will break all driver development.

**Comment by miketimofeev** [comment] 2021-09-29 11:42
@nibanks 2022 is in beta state so it won't become latest till GA.
