### ISSUE TITLE
[Windows] ANSI color codes no longer work with Powershell

### ISSUE THREAD

**Issue by MSP-Greg** [actions/virtual-environments#4533] opened 2021-11-17 15:35 UTC
### Description

This is an odd bug.  With 20211102.4, ANSI color codes worked with PowerShell.  With 20211110.1, they stopped working.  But, the jobs also use ANSI color codes with js code in a custom action, and Ruby code.  Both of those still work.

I run Win10 locally, and I can't repo it.

A job with [20211110.1](https://github.com/MSP-Greg/ruby-loco/runs/4176025174), you'll see color from js code in the 'Set up Ruby & MSYS2' step.  The 'build & install' step shows no color (from PowerShell), and the bottom of the 'test' step shows color, which is from Ruby.

A job with [20211102.4](https://github.com/MSP-Greg/ruby-loco/runs/4174550396) has color in the 'build & install' step...

Not sure if this is an 'actions/virtual-environments' issue, an 'actions/runner' issue, or a 'PowerShell issue...

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20211110.1

### Is it regression?

Yes, works in 20211102.4

### Repro steps

I can post code if that would help.

**Comment by mikhailkoliada** [comment] 2021-11-18 07:32
@MSP-Greg Hello!

In virtual-environments we do nothing specific to powershell but installing it. There was recent [update](https://github.com/actions/virtual-environments/commit/08024941c38cc74d608a7e2cde0b1b0a8eba1509#diff-816219d3c9f30fcc1c40f88ca826c1662bf99eded781c1b419dd2dfb577ae227) to powershell 7.2 so might be you hit a problem here. In anyway I believe it is out of scope of our responsibility here. If I were you I would probably try to play with the ANSI colours locally to see if this was the root cause.

I am going to close this issue now, but feel free to ping us if you have more concerns or questions.

**Closed by mikhailkoliada** 2021-11-18 07:32 UTC
Labels: needs triage

**Comment by miketimofeev** [comment] 2021-12-19 10:33
@MSP-Greg indeed! The new image rollout will start tomorrow

**Comment by ClaudiuSchuster** [comment] 2021-12-20 08:58
I want to mention that with pwsh 7.2.1 something new happens related to ANSI color codes:

With pwsh 7.1.5 and 7.2.0 you could do a 
```
$adUserString = Get-ADUser xxxx | Out-String
$adUserString -match "UserPrincipalName\s*:\s*([^\s]*)" | Out-Null
$emailAddress = $matches[1]
```
and you would get a fine EmailAddress what could be used with Send-MailMessage e.g.

with pwsh 7.2.1 this is not more working.
As $matches[1] will start with 
```
`e[0
``` 
and cmdlets like Send-MailMessage will crash if you use that match as to-address.
With pwsh 7.2.1 this is necessary now:
```
$emailAddress = $matches[1] -replace '\x1b\[[0-9;]*m',''
```

**Comment by ClaudiuSchuster** [comment] 2021-12-20 08:59
I want to mention that with pwsh 7.2.1 something new happens related to ANSI color codes:

With pwsh 7.1.5 and 7.2.0 you could do a 
```
$adUserString = Get-ADUser xxxx | Out-String
$adUserString -match "UserPrincipalName\s*:\s*([^\s]*)" | Out-Null
$emailAddress = $matches[1]
```
and you would get a fine EmailAddress what could be used with Send-MailMessage e.g.

with pwsh 7.2.1 this is not more working.
As $matches[1] will start with 
```
`e[0
``` 
and cmdlets like Send-MailMessage will crash if you use that match as to-address.
With pwsh 7.2.1 this is necessary now:
```
$emailAddress = $matches[1] -replace '\x1b\[[0-9;]*m',''
```
