### ISSUE TITLE
UI tests & Android Emulator on GH Actions - System UI isn't responding alert when application loads

### ISSUE THREAD

**Issue by mazgajmaciek** [actions/virtual-environments#3719] opened 2021-07-12 14:38 UTC
We started experiencing Espresso UI tests failing when being ran on GH Actions workflow. We have a logic to grab a screenshot of emulator screen when a given test fail, and right now it looks like all tests fail right after the application under test loads up - app's main window goes out of focus due to "System UI isn't responding" alert and tests fail because app's window is out of focus due to the alert and UI tests cannot find an element defined in the test itself (see attached screenshot).

That I think could potentially point us to some performance issue while the workflow is being run, however it's quite difficult to pinpoint exactly what would be the issue - if there's a way we could add some command to the .yaml workflow file to get you guys a proper log on that - please let me know. Potentially what I could do is to increase the timeout on which we wait for the element (to bypass the time it takes for the alert to disappear) but that seems only like a workaround and not the actual long-term solution.

Also, reading the docs at https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners it is my understanding that every single runner is being assigned 14gb of RAM, therefore I would assume RAM-wise, we should be good, however maybe there is some different performance issue on the runners right now? (e.g like the one mentioned at https://github.com/actions/virtual-environments/issues/2707)

Similarly to https://github.com/actions/virtual-environments/issues/3663 the same tests ran locally on the same codebase and branch are passing just fine.

Example of failing workflow https://github.com/baas-devops-reference/android-us-retail-app/actions/runs/1021523609

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] macOS 10.15
- [ ] macOS 11
- [ ] Windows Server 2016
- [ ] Windows Server 2019

### Image version and build link

https://github.com/baas-devops-reference/android-us-retail-app/actions/runs/1021523609

![checkAccountDetailsVisible](https://user-images.githubusercontent.com/20247520/125306629-a835d380-e32f-11eb-89f2-ffd31915ef3b.png)

### Expected behavior

Same tests ran on the same codebase should pass locally and on the GH workflow run

### Actual behavior

Tests are passing locally but failing on the GH workflow run

### Repro steps

1. Execute a gh workflow pipeline that runs the Android emulator and UI tests (link to example workflow provided)

**Comment by miketimofeev** [comment] 2021-07-12 15:08
Hi @mazgajmaciek!
Unfortunately, we don't have access to your pipeline. Could you please provide minimal repro steps so we can debug the issue?
And a couple of questions:
- Does any of the pieces of advice from this issue help? https://github.com/actions/virtual-environments/issues/2741
- What Android emulator version do you use? There are 2 of them on macOS — the old one, which is in the path, and the most recent one available on `$HOME/Library/Android/sdk/emulator/emulator`

**Comment by mazgajmaciek** [comment] 2021-07-12 16:16
@miketimofeev thanks for a quick response!

> Unfortunately, we don't have access to your pipeline. Could you please provide minimal repro steps so we can debug the issue?
We're using fastlane to _build the build_ - which in the process executes two .sh scripts - first creates the emulator, 2nd one that's executed right after emulator creation, waits for it to boot. Once it's booted - gradle executes the tests.

emulator creation
`#!/usr/bin/env bash

# Install AVD files
echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --install 'system-images;android-30;google_apis;x86'

# Create emulator
echo "no" | $ANDROID_HOME/tools/bin/avdmanager create avd -n google_pixel_xl -d pixel_xl -k 'system-images;android-30;google_apis;x86' -f

$ANDROID_HOME/emulator/emulator -list-avds

echo "Starting emulator google_pixel_xl"

# Start emulator in background
nohup $ANDROID_HOME/emulator/emulator -avd google_pixel_xl -no-snapshot -no-window -no-audio -no-boot-anim -memory 4000 > /dev/null 2>&1 & sleep 5s`

waiting for emulator to boot:
`#!/usr/bin/env bash
sleep 10
echo "list of active devices: $($ANDROID_HOME/platform-tools/adb devices)"
for n in $($ANDROID_HOME/platform-tools/adb devices | egrep -o  'emulator-(\d+)')
do
    echo "waiting for $n to boot"
    $ANDROID_HOME/platform-tools/adb -s $n wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done;'
    echo "$n booted"
done`

> * Does any of the pieces of advice from this issue help? [System UI isn't responding shows up on Android emulators #2741](https://github.com/actions/virtual-environments/issues/2741)
Like I mentioned in my initial message - I can try increasing the timeout to basically wait for the alert to disappear however this seems to me like a workaround still. Maybe I should ask - do you know if potential runner performance issue could be causing that alert to appear in the first place? 

> * What Android emulator version do you use? There are 2 of them on macOS — the old one, which is in the path, and the most recent one available on `$HOME/Library/Android/sdk/emulator/emulator`
I'm guessing I could potentially change `nohup $ANDROID_HOME/emulator/emulator` in the script that creates the emulator to `$HOME/Library/Android/sdk/emulator/emulator` to try if that makes any difference?

**Comment by miketimofeev** [comment] 2021-07-12 16:36
> I'm guessing I could potentially change nohup $ANDROID_HOME/emulator/emulator in the script that creates the emulator to $HOME/Library/Android/sdk/emulator/emulator to try if that makes any difference?

I believe it makes no sense since `$ANDROID_HOME` is `$HOME/Library/Android/sdk/` so you are definitely on the latest emulator version.

> Like I mentioned in my initial message - I can try increasing the timeout to basically wait for the alert to disappear however this seems to me like a workaround still. Maybe I should ask - do you know if potential runner performance issue could be causing that alert to appear in the first place?

Could you try to increase it anyway until we make further investigation? The runner has only 3 cores at the moment and the performance can be poor sometimes, we will try to reproduce the issue and find potential improvements point.

> I'm guessing you'd need more than that so if you could point me what exactly do you need - I'd be more than happy to help.

We will start with those steps and ask for details if needed, thank you!

**Comment by mazgajmaciek** [comment] 2021-07-12 16:59
@miketimofeev sure I can try with increasing timeout for the interim solution. One more question though - in your opinion could we potentially try to switch from macos 10.15 to using Windows/Ubuntu runners? I wonder where they're at when it comes to no of cores?

**Comment by miketimofeev** [comment] 2021-07-12 17:06
@mazgajmaciek I'm not aware of emulator performance issues on either windows or ubuntu VMs, so let's give it a try if it's possible.

**Comment by mazgajmaciek** [comment] 2021-07-21 13:57
@miketimofeev @dsame do we have any update on this issue maybe?

**Comment by dsame** [comment] 2021-07-21 17:29
@mazgajmaciek 

yes, the root of the problem identified by this moment is Google Services bundled SDK 30 and the overall performance of the hosts. 

While we still can not solve the performance issue with SDK30 there's a workaround to detect the "System UI isn't responding" alert and simulated the click on it.

Take a look at this pipeline: https://github.com/akv-platform/espressodemo/blob/main/.github/workflows/blank.yml step `run emulator`

This lets emulator to work in most cases but in ~20% of builds we still see another popup saying "Google Services not responding". We still working on it.

Besides that please pay attention to `modify config.ini` step - there's evidences the setting memory size can change the behaviour a bit.

And finally you can try to use an image without google-api in case if your app does not require them.

**Comment by mazgajmaciek** [comment] 2021-07-21 19:32
thank you @dsame, I'll try to apply the workaround and post the results here.

**Comment by dsame** [comment] 2021-07-21 20:34
@mazgajmaciek 

For better results there should be only one KEYCODE_DPAD_DOWN while dismissing "System Not Responding" alert:

```
 76             *"Not Responding: com.android.systemui"*)
 77               echo "Dismiss System UI isn't responding alert"
 78               # adb shell input keyevent KEYCODE_DPAD_DOWN
 79               adb shell input keyevent KEYCODE_DPAD_DOWN
 80               adb shell input keyevent KEYCODE_ENTER
 ```

**Comment by dsame** [comment] 2021-07-22 09:22
The roadmap to solve the problem:

1. use the script to launch the emulator and make sure there are no any pop ups:
```
nohup "$ANDROID_HOME/emulator/emulator" -avd TestAvd -no-snapshot -no-window -no-audio -no-boot-anim -accel on -wipe-data 2>&1 &
        
        echo "Waiting for device..."
        $ANDROID_HOME/platform-tools/adb wait-for-device shell true
        echo "Android is booting..."
        
        EMU_BOOTED=0
        n=0
        first_launcher=1
        echo 1 > /tmp/failed
        while [[ $EMU_BOOTED = 0 ]];do
            echo "Test for current focus"
            #        $ANDROID_HOME/platform-tools/adb shell dumpsys window
            CURRENT_FOCUS=`$ANDROID_HOME/platform-tools/adb shell dumpsys window 2>/dev/null | grep -i mCurrentFocus`
            echo "Current focus: ${CURRENT_FOCUS}"
            case $CURRENT_FOCUS in
            *"Launcher"*)
              if [[ $first_launcher == 1 ]]; then
                echo "Launcher seems to be ready, wait 10 sec for another popup..."
                sleep 10
                first_launcher=0
              else
                echo "Launcher is ready, Android boot completed"
                EMU_BOOTED=1
                rm /tmp/failed
              fi
            ;;
            *"Not Responding: com.android.systemui"*)
              echo "Dismiss System UI isn't responding alert"
              adb shell input keyevent KEYCODE_ENTER
              adb shell input keyevent KEYCODE_DPAD_DOWN
              adb shell input keyevent KEYCODE_ENTER
              first_launcher=1
            ;;
            *"Not Responding: com.google.android.gms"*)
              echo "Dismiss GMS isn't responding alert"
              adb shell input keyevent KEYCODE_ENTER
              first_launcher=1
            ;;
            *"Not Responding: system"*)
              echo "Dismiss Process system isn't responding alert"
              adb shell input keyevent KEYCODE_ENTER
              first_launcher=1
            ;;
            *"ConversationListActivity"*)
              echo "Close Messaging app"
              adb shell input keyevent KEYCODE_ENTER
              first_launcher=1
            ;;
            *)
              n=$((n + 1))
              echo "Waiting Android to boot 10 sec ($n)..."
              sleep 10
              if [ $n -gt 60 ]; then
                  echo "Android Emulator does not start in 10 minutes"
                  exit 2
              fi
            ;;
            esac
        done
        echo "Android Emulator started."
```

sample build: https://github.com/akv-platform/espressodemo/runs/3132275577?check_suite_focus=true

The suggested script is not 100% robust because there might be another pop ups from the Android System and Google Services: use the  output of "echo "Current focus: ${CURRENT_FOCUS}" to identify it and add the extra branches to close the popup.  

2. Use API levels below 30 for faster emulator launch
3. Use emulator images without google service api to avoid the pop ups
4. To reduce the probability of the pop up increase the memory available to emulator device:

```
        echo 'hw.ramSize=2048MB' >> ~/.android/avd/[Emulator Name].avd/config.ini
```

@mazgajmaciek i am finishing the investigation of this problem  and am not going to provide info within this issue but please feel free to give us more feedback and reopen the issue if needed.

**Comment by mazgajmaciek** [comment] 2021-07-22 09:32
@dsame 

> Use emulator images without google service api to avoid the pop ups

Do you happen to know how one can verify which ones are using google service api and which are not?

**Comment by dsame** [comment] 2021-07-22 11:27
> @dsame
> 
> > Use emulator images without google service api to avoid the pop ups
> 
> Do you happen to know how one can verify which ones are using google service api and which are not?

it is in package name used to create avd

```
    - name: create AVD
      run: |
        export API=`echo ${{matrix.api}}|cut -f 2 -d'-'`
        if [ $API == 28 ]
        then
          export PACKAGE="system-images;android-${API};google_apis;x86"
          export ABI="google_apis/x86"
        else
          export PACKAGE="system-images;android-${API};google_apis;x86_64"
          export ABI="google_apis/x86_64"
        fi
```

**Comment by dsame** [comment] 2021-07-28 20:59
I am closing the issue with the workaround suggested

**Closed by dsame** 2021-07-28 20:59 UTC
Labels: Area: Android, OS: macOS, investigate
